### ISSUE TITLE
Animation not working on mobile

### ISSUE THREAD

**Issue by SabrinaCurry** [airbnb/lottie-android#100]
When I render out the animation with Bodymovin, it works fine on web but when placed in mobile elements start to get distorted or don't show at all. Any idea what may be the problem? Looked through the unsupported feature list and none of the unsupported features are being used in the animations so not too sure whats happening.
[lottie-issues.mov.zip](https://github.com/airbnb/lottie-android/files/772262/lottie-issues.mov.zip)

**Comment by therealsalih** [comment]
Can you send an AE file so we can check out which features aren't coming through?

**Comment by SabrinaCurry** [comment]
Here are the project files, thanks for your help!

[Lotti_Animations.zip](https://github.com/airbnb/lottie-android/files/772459/Lotti_Animations.zip)

**Comment by gpeal** [comment]
From the looks of it, acorn and sappling look fine. Phone is fine except that the numbers are filled in which I'll look in to. Coffee has some issues which I'll also investigate.

[Animations.zip](https://github.com/airbnb/lottie-android/files/772483/Animations.zip)

**Comment by therealsalih** [comment]
In Coffee you're using Alpha Inverted mattes which Lottie doesn't yet support

![screen shot 2017-02-13 at 1 43 11 pm](https://cloud.githubusercontent.com/assets/5893643/22904744/6a46aa00-f1f2-11e6-9a67-1c38e083df46.png)

If you want to work around that for now just change your matte to alpha matte and move the path to the other side

![screen shot 2017-02-13 at 1 44 23 pm](https://cloud.githubusercontent.com/assets/5893643/22904776/8bcda160-f1f2-11e6-8426-547d7220454a.png)

**Comment by gpeal** [comment]
And the numbers are filled in because they use merge paths which we don't support yet. I'll look into adding support for it though.

**Comment by SabrinaCurry** [comment]
Thank you guys for all of the help! Do you know why the others are having issues with Lottie? Is there a certain way it needs to be exported with Bodymovin or is it something with the code?

**Comment by gpeal** [comment]
You can track alpha inverted masks and merge paths in #101 and #102

**Comment by gpeal** [comment]
@SabrinaCurry Which other issues are you referring to?

**Comment by SabrinaCurry** [comment]
When we try to bring things onto a mobile platform some parts of the illustration are disappearing
![screen shot 2017-02-13 at 2 44 39 pm](https://cloud.githubusercontent.com/assets/20654101/22906811/20b4ce5e-f1fb-11e6-9c47-d3bf03d97db6.png)
![screen shot 2017-02-13 at 2 44 58 pm](https://cloud.githubusercontent.com/assets/20654101/22906810/20b47da0-f1fb-11e6-9887-db0fcc1e05c2.png)

 for example the Acorn in the bouncy acorn file and a portion of the sappling in the sappling file

**Comment by therealsalih** [comment]
Thats weird... Maybe try updating to the latest version...

Those three seem to be working fine on my simulator

![feb-13-2017 14-57-28](https://cloud.githubusercontent.com/assets/5893643/22907203/d6829300-f1fc-11e6-9e4a-09b4c5540ac2.gif)

**Comment by buba447** [comment]
@SabrinaCurry I fixed this issue over on the iOS repo and replied to your issue posted over there. Please check it out! :) 
The issue on iOS 
https://github.com/airbnb/lottie-ios/issues/89

Fix here
https://github.com/airbnb/lottie-ios/pull/90

**Comment by SabrinaCurry** [comment]
@buba447 Thank you so much!

@therealsalih I let my team know about the update solution, hopefully that should solve that issue. Thanks for all of your help, greatly appreciated!

**Comment by SabrinaCurry** [comment]
Thanks for all of your help as well @gpeal!

**Comment by gpeal** [comment]
@SabrinaCurry great! I'm going to close out this issue then. Feel free to track #101 and #102
