### ISSUE TITLE
Animation not working correctly on android studio

### ISSUE THREAD

**Issue by supbrosef** [airbnb/lottie-android#1001]
My animation works fine in the lottie preview as shown:
https://www.lottiefiles.com/share/6khKu9

However, when i run it on my android device it shows like the following:
https://gyazo.com/c757844fd29a51189413e3c059745119

I have created a simple animation manipulating a circle which works fine on my device. 

My json file https://www.dropbox.com/s/n9571ykol75wnq7/test.json?dl=0

**Comment by gpeal** [comment]
@supbrosef Can you attach the aep for this? It is difficult to debug without it. You can zip it and attach it as a zip.
