### ISSUE TITLE
Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed  com.airbnb.lottie.CompositionLayer.drawLayer(CompositionLayer.java:91)

### ISSUE THREAD

**Issue by huyaoqing1995** [airbnb/lottie-android#1005]
Hello, in CompositionLayer.java line 91，you can change "canvas.clipRect(originalClipRect, Region.Op.REPLACE);" to "if (Build.VERSION.SDK_INT >= 26) {
canvas.clipPath(mPath);
} else {
canvas.clipPath(mPath, Region.Op.REPLACE);
}
"
in Android P

**Comment by gpeal** [comment]
@huyaoqing1995 Is this still an issue with the latest code?
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/model/layer/CompositionLayer.java#L96

**Comment by huyaoqing1995** [comment]
Oh~ Thaks!  I need to update version ~
