### ISSUE TITLE
OOM use in recyclerView

### ISSUE THREAD

**Issue by xiaobinghe** [airbnb/lottie-android#1008]
I use it in the recyclerView, if too much animation, causing serious damage, and even lead to OOM. Is there any good solution? please help me.

**Comment by gpeal** [comment]
@xiaobinghe If you could attach a project that repros this or do the investigative work to figure out what is leaking, feel free to reopen this but there isn't enough information to act on here.

**Comment by xiaobinghe** [comment]
> @xiaobinghe If you could attach a project that repros this or do the investigative work to figure out what is leaking, feel free to reopen this but there isn't enough information to act on here.

I tried to add animation to each item in the recyclerview, but I found it very stuck. I wanted to find a solution that could optimize it. I never found it. I found in the profile detection that lottieAnimation caused a lot of CPU consumption and memory consumption. I think it may be that I don't know much about Lottie;

**Comment by xiaobinghe** [comment]
> @xiaobinghe If you could attach a project that repros this or do the investigative work to figure out what is leaking, feel free to reopen this but there isn't enough information to act on here.

I tried to add animation to each item in the recyclerview, but I found it very stuck. I wanted to find a solution that could optimize it. I never found it. I found in the profile detection that lottieAnimation caused a lot of CPU consumption and memory consumption. I think it may be that I don't know much about Lottie;

**Comment by xiaobinghe** [comment]
I saw a lot of LottieTaskObser threads created in the android profile detection tool. I want to destroy these threads when they are not needed. Can you tell me what to do?

**Comment by gpeal** [comment]
@xiaobinghe They will stop themselves when they are done parsing. Can you attach a sample project with the latest version of Lottie?

**Comment by gpeal** [comment]
Which version of Lottie did you test this on?
