### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by fang1994042128** [airbnb/lottie-android#1016]
Hello
I used version 2.70。 Some phones have crashed。
I used image resources。
mLottieAnimationView.setImageAssetsFolder("images");
mLottieAnimationView.setAnimation("data.json");

You must set an images folder before loading an image. Set it with LottieComposition#setImagesFolder or LottieDrawable#setImagesFolder
com.airbnb.lottie.manager.ImageAssetManager.bitmapForId(ImageAssetManager.java:107)

**Comment by gpeal** [comment]
http://airbnb.io/lottie/android/images.html
