### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by Simon1121** [airbnb/lottie-android#1017]
java.lang.ClassCastException
android.graphics.PointF cannot be cast to com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation

1 com.airbnb.lottie.model.layer.BaseLayer.setProgress(BaseLayer.java:427)
2 com.airbnb.lottie.model.layer.CompositionLayer.setProgress(CompositionLayer.java:139)
3 com.airbnb.lottie.model.layer.CompositionLayer.setProgress(CompositionLayer.java:139)
4 com.airbnb.lottie.LottieDrawable$1.onAnimationUpdate(LottieDrawable.java:103)
5 com.airbnb.lottie.utils.BaseLottieAnimator.notifyUpdate(BaseLottieAnimator.java:88)
6 com.airbnb.lottie.utils.LottieValueAnimator.doFrame(LottieValueAnimator.java:96)
7 android.view.Choreographer$CallbackRecord.run(Choreographer.java:759)
8 android.view.Choreographer.doCallbacks(Choreographer.java:574)
9 android.view.Choreographer.doFrame(Choreographer.java:543)
10 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
11 android.os.Handler.handleCallback(Handler.java:733)
12 android.os.Handler.dispatchMessage(Handler.java:95)
13 android.os.Looper.loop(Looper.java:136)
14 android.app.ActivityThread.main(ActivityThread.java:5017)
15 java.lang.reflect.Method.invokeNative(Native Method)
16 java.lang.reflect.Method.invoke(Method.java:515)
17 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
18 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
19 dalvik.system.NativeStart.main(Native Method)

My version lottie library is 2.7.0. How can I resolve this issue ?

**Comment by gpeal** [comment]
@Simon1121 Can you provide more repro steps and attach a sample project that repros this?

It's strange that you got two separate unique compilation errors on the same line of code. That makes me thing it's something specific to your project.

**Comment by gpeal** [comment]
I'm going to close this as likely a build specific issue. If you can reproduce this, please attach a project that does.
