### ISSUE TITLE
java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by Simon1121** [airbnb/lottie-android#1018]
java.lang.IncompatibleClassChangeError
interface not implemented

1 com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation.notifyListeners(BaseKeyframeAnimation.java:59)
--
2 com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation.setProgress(BaseKeyframeAnimation.java:55)
3 com.airbnb.lottie.animation.keyframe.TransformKeyframeAnimation.setProgress(TransformKeyframeAnimation.java:86)
4 com.airbnb.lottie.model.layer.BaseLayer.setProgress(BaseLayer.java:412)
5 com.airbnb.lottie.model.layer.CompositionLayer.setProgress(CompositionLayer.java:127)
6 com.airbnb.lottie.LottieDrawable$1.onAnimationUpdate(LottieDrawable.java:103)
7 com.airbnb.lottie.utils.BaseLottieAnimator.notifyUpdate(BaseLottieAnimator.java:88)
8 com.airbnb.lottie.utils.LottieValueAnimator.doFrame(LottieValueAnimator.java:96)
9 android.view.Choreographer$CallbackRecord.run(Choreographer.java:759)
10 android.view.Choreographer.doCallbacks(Choreographer.java:574)
11 android.view.Choreographer.doFrame(Choreographer.java:543)
12 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
13 android.os.Handler.handleCallback(Handler.java:733)
14 android.os.Handler.dispatchMessage(Handler.java:95)
15 android.os.Looper.loop(Looper.java:136)
16 android.app.ActivityThread.main(ActivityThread.java:5017)
17 java.lang.reflect.Method.invokeNative(Native Method)
18 java.lang.reflect.Method.invoke(Method.java:515)
19 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
20 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
21 dalvik.system.NativeStart.main(Native Method)

version 2.7.0

**Comment by gpeal** [comment]
@Simon1121 Can you provide more repro steps and attach a sample project that repros this?

**Comment by gpeal** [comment]
I'm going to close this as likely a build specific issue. If you can reproduce this, please attach a project that does.
