### ISSUE TITLE
getProgress retrun awlays zero.

### ISSUE THREAD

**Issue by taejungkim** [airbnb/lottie-android#103]
```java
animView.addAnimatorUpdateListener(new ValueAnimator.AnimatorUpdateListener(){
   public void onAnimationUpdate(ValueAnimator animator){
       Log.d("test",  animView.getProgress);
   }
}
```

**Comment by gpeal** [comment]
@taejungkim I currently use this in the sample app here: https://github.com/airbnb/lottie-android/blob/master/LottieSample/src/main/java/com/airbnb/lottie/samples/AnimationFragment.java#L117

Can you attach a sample project if you think this is still broken?

**Comment by taejungkim** [comment]
I said LottieAnimView.getProgress() method is broken.

https://github.com/airbnb/lottie-android/blob/master/LottieSample/src/main/java/com/airbnb/lottie/samples/AnimationFragment.java#L179

Sample code is no problem. Because called LottieAnimView.setProgress() in OnSeekBarChangeListener.

https://github.com/airbnb/lottie-android/blob/master/LottieSample/src/main/java/com/airbnb/lottie/samples/AnimationFragment.java#L123

**Comment by taejungkim** [comment]
In addition, I think you should remove progress field in the LottieAnimView class, and the getProgress() method of LottimeAnimView should return the value of lottieDrawable.getProgress().

**Comment by gpeal** [comment]
@taejungkim This will be fixed in the next release.

**Comment by gpeal** [comment]
@taejungkim 1.5.0 is now out!
