### ISSUE TITLE
Android Animation Crashing

### ISSUE THREAD

**Issue by matantedw** [airbnb/lottie-android#1038]
Hoping someone will be able to help or advise as been struggling with this one for several hours/days now

We have a loader animation which works fine for Web & iOS but is crashing our app (as well as the Lottie Preview) app on Android

I have taken several steps already including removing layer from layer from the animation to isolate the issue and whilst it has been narrowed down - repeated update attempts by the designer are not having any effect.

The animation is crashing consistently on **frame 38** which can be seen when loaded into the Lottie Preview App. No errors or warnings are shown before this point. Interesting to note is that if you manually skip past frame 38 using the slider in Lottie Preview - the animation will continue to play and loop without issue getting passed frame 38 which is confusing.

Please find attached the ZIP file containing the After Effects file together with the JSON output
[Animation.zip](https://github.com/airbnb/lottie-android/files/2676413/Animation.zip)

Any advice or confirmation as to whether this is a bug would be appreciated

**Comment by yalematta** [comment]
How are you using your zip file? Inserting it in your assets folder? Which path are you using?

**Comment by matantedw** [comment]
@gpeal - could you please give any indication as to when you may be creating a new release with the included (and latest) fixes?

**Comment by gpeal** [comment]
@matantedw I published 3.0.0-beta1 today actually 😄 It's mostly beta just in name but it should be stable.
