### ISSUE TITLE
Add support for multiply blend mode

### ISSUE THREAD

**Issue by gpeal** [airbnb/lottie-android#1055]

**Comment by ThePixelBug** [comment]
Are any of these blend modes supported on android lottie? Maybe with the 3.0 release?

AE blend modes
normal;
multiply;
screen;
overlay;
darken;
lighten;
color-dodge;
color-burn;
hard-light;
soft-light;
difference;
exclusion;
hue;
saturation;
color;
luminosity;

**Comment by gpeal** [comment]
@ThePixelBug Nope, not yet

**Comment by jhughes696** [comment]
@gpeal  Are blend modes possible at all?  Multiply is the main one that would be a huge help.

**Comment by gpeal** [comment]
https://github.com/airbnb/lottie-android/pull/2408 added support for all blend modes that are backwards compatible. Android Q added more but almost no apps have a minSdk of Q+ so it will be a while before support for those can be added.
