### ISSUE TITLE
Support rounded corners outside of a rectangle properties.

### ISSUE THREAD

**Issue by gpeal** [airbnb/lottie-android#106]

**Comment by tuchangwei** [comment]
do you know how to set rounded corners?
thanks.

**Comment by gpeal** [comment]
@tuchangwei roundedness is a property of a rectangle. That works.
![image](https://user-images.githubusercontent.com/1307745/33220652-d5a424da-d0fe-11e7-86d8-de18894a9cf7.png)

**Comment by MrNinja** [comment]
@gpeal Could I programmatically create an rounded corner LottieAnimationView in Android like iOS?

```
    // Setup our image view with the rect and add rounded corners
    imageView.frame = imageRect
    imageView.layer.masksToBounds = true
    imageView.layer.cornerRadius = imageRect.width / 2;
```

**Comment by gpeal** [comment]
@MrNinja Yes, you can use an [OutlineProvider](https://developer.android.com/reference/android/view/View.html#setOutlineProvider(android.view.ViewOutlineProvider)) on which you can [setRoundedRect](https://developer.android.com/reference/android/graphics/Outline#setRoundRect(android.graphics.Rect,%20float))

**Comment by MrNinja** [comment]
Thank you for your suggest. Let me read more about it.
