### ISSUE TITLE
rippledrawable is not supported because of LAYER_TYPE_SOFTWARE

### ISSUE THREAD

**Issue by heeya333** [airbnb/lottie-android#1073]
For support rippleDrawable as background for touch effect,
I have to set LottieAnimationView layer_type_hardware.
But because of below code,
always set layer_type_software without animating state.
I think it is better to change own view's layer type instead of LAYER_TYPE_SOFTWARE.

  private void enableOrDisableHardwareLayer() {
    boolean useHardwareLayer = this.useHardwareLayer && lottieDrawable.isAnimating();
    setLayerType(useHardwareLayer ? LAYER_TYPE_HARDWARE : LAYER_TYPE_SOFTWARE, null);
  }

**Comment by gpeal** [comment]
@heeya333 Lottie has to use software rendering for certain animations. Some animations (with large masks and mattes) will perform much much worse with hardware rendering than software rendering.

However, the next version of Lottie has a `setRenderMode` API which has `Hardware` `Software` and `Automatic` so you can use that.
