### ISSUE TITLE
How to draw each frame of lottie onto the canvas?

### ISSUE THREAD

**Issue by panzhi1** [airbnb/lottie-android#1074]
Hello ,
I want to make the lottie content into a video. Is there any good way to draw the contents of lottie to the surfaceview?
please help me.

**Comment by gpeal** [comment]
@panzhi1 You can use LottieDrawable directly and call `draw(canvas)` on your SurfaceHolder's locked canvas.

**Comment by astarlabsofficial** [comment]
Hi, How can we use draw(canvas) on your SurfaceHolder's locked canvas.

Any Reference

**Comment by paul726** [comment]
we've got a solution on this blog 
https://medium.com/@guchengyehai1/rendenring-lottie-animation-with-android-surfaceview-76c0662699f6
