### ISSUE TITLE
bug: setProgress() not work somecase

### ISSUE THREAD

**Issue by lzhgreat** [airbnb/lottie-android#1075]
after setAnimation() with same json file, setProgress() with same value will not work .  My test code:  

   mLottie.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mLottie.setImageAssetsFolder("images/");
                mLottie.setAnimation(json_2);
                mLottie.setProgress(1f);
            }
        });

**Comment by gpeal** [comment]
@lzhgreat Can you attach a sample project that reproduces this?
