### ISSUE TITLE
LottieDrawable set bounds not working

### ISSUE THREAD

**Issue by zhangruize** [airbnb/lottie-android#1079]
For some special reasons, I need to use LottieDrawable like `View.getOverlay().add(lottieDrawable)`. But I found the animation content cannot be positioned in center though I set correct bounds via `lottieDrawable.setBounds(...)` after lottie composition loaded.

Is there any way to center LottieDrawable in `View.getOverlay()` ?

**Comment by zhangruize** [comment]
I've found a not quite good solution. I override `draw` method of LottieDrawable, and translate the canvas as I want. Is there any better idea?

**Comment by gpeal** [comment]
@zhangruize Can you attach a sample project?

**Comment by gpeal** [comment]
I think translating for your specific use case is fine. Most of the time, ImageView scaleType is what you would use to achieve this.

**Comment by Krishna-Vyas** [comment]
I'm also trying to setBounds on LottieDrawable, but it's not working. 
When I scale LottieDrawable with setScale(), it setBounds to (0,0,width,height)
but I want to set animation on the bottom-right corner of the drawable. And This work is not UI 
related, So I can't set scaleType on LottieAnimationView. Please tell me how can scale drawable to stay at the bottom-right corner.

**Comment by irgaly** [comment]
I'm facing same issue with `View.getOverlay().add(lottieDrawable)`.
Calling `LottieDrawable.setBounds(x, y, width, height)` does not affect. The animation always appears left top corner of View Overlay.

**Comment by irgaly** [comment]
my workaround, same approach as @zhangruize

```
class PositionedLottieDrawable : LottieDrawable() {
    var x: Float = 0f
    var y: Float = 0f
    override fun draw(canvas: Canvas) {
        canvas.save()
        canvas.translate(x, y)
        super.draw(canvas)
        canvas.restore()
    }
}
```

**Comment by gpeal** [comment]
@Krishna-Vyas @irgaly What version of Lottie? 3.6.0 should respect the bounds you set

**Comment by irgaly** [comment]
I'm using 3.4.0.

I tried Lottie 3.6.1, but the animation appeared at (0, 0).
Here is my code, and I tested it in Android 9.

```kotlin
private val drawable = LottieDrawable()
...
// I watched with debugger, they are x = 792, y = 161 here. 
drawable.setBounds(x, y, drawable.composition.bounds.right + x, drawable.composition.bounds.bottom + y)
targetView.overlay.add(drawable)
drawable.playAnimation()
```
