### ISSUE TITLE
C++ rewrite

### ISSUE THREAD

**Issue by xiaofengfeng110** [airbnb/lottie-android#1081]
Lottie now has Android, iOS, web and other versions。 So we want a unified version, how to rewrite with C++?

**Comment by gpeal** [comment]
@xiaofengfeng110 C++ alone wouldn't give it universal compatibility. If you want to write an opengl/metal/vulkan renderer, that would be a totally separate project. [This](https://skia.org/user/modules/skottie) is the closest thing to that right now.

**Comment by martin-huang** [comment]
Waiting for good news

**Comment by yujifei** [comment]
https://github.com/Samsung/rlottie a pure c++ implementation of lottie
