### ISSUE TITLE
play animation to slowly (Feature request)

### ISSUE THREAD

**Issue by yudikarma** [airbnb/lottie-android#1082]
hi thanks for create animation third party android library for animation .
i want to create some aplication like "Hours Glass" 
can i play json animation slowly to same with setting duration.

ex : my hourglass animatin.json have 5 minute duration. then i wan play that to end at 10 minute.
how i do that ? 

if want to play in 2.5 minut i just setting speed ; 
and if i want to play backward i just setting speed to minus. 
but if i want to play slow how i do that ?

**Comment by gpeal** [comment]
@yudikarma You can call `setProgress(...)` with whatever values you want from 0 to 1 so you can create your own animator/timer/whatever you want to manually control the animation.

**Comment by yudikarma** [comment]
@gpeal i was setProgress(0.5f) but that not make animatin play realy slow.

**Comment by gpeal** [comment]
@yudikarma What do you mean? All that happens when you play an animation is that LottieValueAnimator calls `setProgress()` many times. You could write your own timing and call setProgress with whatever values whenever you want.

**Comment by yudikarma** [comment]
Hi @gpeal, first i want to say sorry because i don't know if we can use AnimatorValue that corresponds to the duration parameter we gave. Now I have implemented the Animator value with Lottie animation, nut now I have a  Confusion on how to apply reverse in it. because when I call animatorvalue.reverse (); my lottieanimation not play reverse.

this my code for Animator value and lotttieanimationview playing
final ValueAnimator animator = ValueAnimator.ofFloat(0f,1f);`
animator.setDuration(60000);
        animator.setInterpolator(new AccelerateInterpolator());
        animator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
            @Override
            public void onAnimationUpdate(ValueAnimator animation) {
                //begin animated
                lottieAnimationView.playAnimation();
                lottieAnimationView.setProgress(animation.getAnimatedFraction());
                lottieAnimationView.setSpeed(animation.getAnimatedFraction());

                lottieAnimationView.addAnimatorListener(new AnimatorListenerAdapter() {
                    @Override
                    public void onAnimationEnd(Animator animation) {
                        lottieAnimationView.cancelAnimation();
                        super.onAnimationEnd(animation);
                    }
                });



            }
        });`

and this code how i call reverse animator:
`animator.reverse();`
when animator set reverse the lottieaimation like confuse betwen speed Plus or minus
