### ISSUE TITLE
Play animation back and forward continuosly

### ISSUE THREAD

**Issue by belka0107** [airbnb/lottie-android#1088]
Hello.
Please help me to understand how is possible play animation forward and back continuosly? Now with code:

intervals:
`descriptionAdapter.intervals = arrayListOf(
Triple(0.0f, 0.12f, 0.28f),
Triple(0.3f, 0.36f, 0.56f),
Triple(0.64f, 0.85f, 0.95f)
)`

`
val holder = p0 as DescriptionItem
var loopCount = 0
holder.descriptionAnimationView.clearAnimation()
    if (position == -1) {
        holder.descriptionAnimationView.pauseAnimation()
        holder.descriptionAnimationView.setMinAndMaxProgress(0f, 0f)
    } else {
        holder.descriptionAnimationView.setMinAndMaxProgress(intervals!![p1].first, intervals!![p1].third)
        val loopListener = object : AnimatorListenerAdapter() {
            override fun onAnimationRepeat(animation: Animator) {
                super.onAnimationRepeat(animation)

                loopCount++
                if (loopCount == 1) {
                    holder.descriptionAnimationView.setMinAndMaxProgress(intervals!![p1].second, intervals!![p1].third)
                }
            }

            override fun onAnimationEnd(animation: Animator?) {
                super.onAnimationEnd(animation)
                
            }
        }

        holder.descriptionAnimationView.addAnimatorListener(loopListener)
    }
    holder.descriptionAnimationView.playAnimation()
`
image jumps from last frame to first, but I want to get smooth transition

**Comment by gpeal** [comment]
@belka0107 Instead of relying on Lottie's animator, you can handle the animation timing yourself just just call `setProgress(...)` with whatever values you want in your animator. That's all Lottie does under the hood.
