### ISSUE TITLE
Large animation occasionally does not play 

### ISSUE THREAD

**Issue by tomblenz** [airbnb/lottie-android#1091]
I've got a 615kb animation file which is loaded into a recyclerview item (which is not reused) and played via:
```
lottieView.repeatMode = LottieDrawable.RESTART
lottieView.repeatCount = LottieDrawable.INFINITE

// later...

lottieView.setAnimation(resId)
lottieView.playAnimation()
```

Half of the time it works, the other half of the time it does not begin playing and sits at 0%.

The anim contains merge paths and this error comes up a few times while the animation is being loaded.
```
W/LOTTIE: Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().
```
Adding either of the following to the view does not supress the error or alleviate the issue.
```
lottieView.enableMergePathsForKitKatAndAbove(true)
//or
app:lottie_enableMergePathsForKitKatAndAbove="true"
```

What DOES seem to work is omitting `playAnimation()` and simply specifying `app:lottie_autoPlay="true"` in xml.  

As a total stab in the dark, I assume the cause is a race condition and the view is trying to play before the animation is fully loaded.

This is on Android Pie.

Unfortunately I'm not comfortable attaching the animation in question as it is a client's and the app is not yet released.

**Comment by gpeal** [comment]
@tomblenz the xml and calling playAnimation() do pretty much the same thing and either should work before the animation is finished loading. I've never seen or heard of anybody having this problems so it's tough to debug without an animation. You can try changing some values in the animation and posting it or trying an animation from lottiefiles in your app to see if it behaves the same.

If you can't do either of those, you'll have to actually debug this. You can place breakpoints in the code in your app in Android Studio and take a look.

**Comment by tomblenz** [comment]
@gpeal Unfortunately I don't have the time right now to dedicate to this - I just thought I'd bring the bug to your attention.  The workaround (autoPlay) works fine for me.  Feel free to close if not bothered :)

After release I may be able to get my client to release the asset for debugging (or I may have time to do it myself).

**Comment by gpeal** [comment]
Okay. Unfortunately this isn't actionable as is but I'll keep an eye out for it.
