### ISSUE TITLE
enableMergePathsForKitKatAndAbove not working

### ISSUE THREAD

**Issue by KennyGoers** [airbnb/lottie-android#1093]
The attached animation plays perfectly fine when enableMergePathsForKitKatAndAbove
 is set to false or not specified at all but prints a warning that the animations contains merge paths. When enableMergePathsForKitKatAndAbove == true the animation animates but  looks incorrect.  I've attached the animation and I have a basic app package, but the "bad image" is reproduced in all variants I've seen.

[anim_umbrella_simple.json.zip](https://github.com/airbnb/lottie-android/files/2804244/anim_umbrella_simple.json.zip)

**Comment by gpeal** [comment]
@KennyGoers Can you attach the aep?
