### ISSUE TITLE
Animation takes a long time to appear

### ISSUE THREAD

**Issue by saketkumar** [airbnb/lottie-android#1095]
I'm trying to show the lottie animation on my splash screen. Below is the code for my SplashActivity. I'm adding delay of 2.5 secs to display the splash and firing an intent to MainActivity after this. But still no animations shows up till 2.5 secs. It just shows white screen. I added 5 secs then it shows up. But I don't want to do like this. I just want to show the animation in 1 sec.

    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_splash);
    LottieAnimationView lottieAnimationView = findViewById(R.id.lottie_animation);
    lottieAnimationView.setAnimation("animation.json");
    lottieAnimationView.playAnimation();
    lottieAnimationView.loop(true);

    Handler mHandler = new Handler(Looper.getMainLooper());
    mHandler.postDelayed(() -> {
     Intent intent = new Intent(SplashActivity.this, MainActivity.class);
     intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP | Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
     startActivity(intent);
    }, 1500);`

What to do here ? 

@gpeal

**Comment by gpeal** [comment]
@saketkumar Lottie has to parse your json file prior to rendering it. You can try to simplify the json file by reducing keyframes, vertices, and making sure that you don't bake in keyframes. How big is your json file?

**Comment by saketkumar** [comment]
@gpeal All my json files are < 100kb. Still taking too much time.

**Comment by saketkumar** [comment]
Still facing the same issue. Is there any way that we can avoid it after first launch ? on every launch it is rendering slow. @gpeal

**Comment by gpeal** [comment]
@saketkumar For subsequent launches, you warn the cache just by using the `LottieCompositionFactory` methods with a cache key. The next time you call it, it'll just return the pre-parsed composition.

**Comment by saketkumar** [comment]
Is this the method https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java#L99 ? Can you please explain more ? @gpeal

**Comment by gpeal** [comment]
@saketkumar If you use the file name method, it will automatically put the serialization task and composition in a cache. So, you can just call that function with no listeners when you want to start getting it ready for the cache then call it again when you actually need it.

**Comment by divyansh169** [comment]
I also ran into the same situation but able to fix it. First make the lottie animation visible to true in the XML file then just your work will be done.
PS: don't include any other code of lottie animation in corresponding Java file.
All this will lead to showing animation on the splash screen as soon as it is launched till the activity get changed after delayed amount of time
