### ISSUE TITLE
Larger Animation w/ Merge Paths does not start/play

### ISSUE THREAD

**Issue by shonshampain** [airbnb/lottie-android#1096]
Minimum app showing the issue is here:
https://github.com/shonshampain/LottieSandbox
Run the apk, notice that one animation does not start
Remove the app:lottie_enableMergePathsForKitKatAndAbove="true" lines from activity_main.xml and re-run and notice that the animation that does not start has its background covering up "something"
Change copy "transparent.png" in the assets folder over "img_0.png" and re-run and notice now what was covered up was the animation that is now more or less working correctly.
Same behavior xml or programatically.

**Comment by gpeal** [comment]
@shonshampain Can you attach the original AEP?

**Comment by shonshampain** [comment]
@gpeal Here you go. Thanks for taking a look at this.
[Evite_Level-Up.zip](https://github.com/airbnb/lottie-android/files/2885070/Evite_Level-Up.zip)

**Comment by gpeal** [comment]
@shonshampain I just took a look at your animation. The issue is actually the MULTIPLY layer you have which Lottie doesn't support. In addition, Lottie has fairly limited text support so the per character palette isn't respected either.
