### ISSUE TITLE
white line appears in the middle of objects in lottie animation

### ISSUE THREAD

**Issue by Mennattu** [airbnb/lottie-android#1102]
I'm working on animations for ios and android applications 
I recently exported an ae animation with bodymovin to a json file. The export shows white lines in the middle of some objects in my file.
when the json file was imported into android studio the lines appeared as shown in the image provided  and the developers sent screenshots showing this problem, so I checked if the transformation with scale property was right to 0% and it was right and I don't know where the problem comes from
I expected normal export as the shapes I was already working with in the after effects like the screenshots I provided
Also when I import the json into lottie preview sometimes the line appears in the middle of the object and sometimes it appears normaly as I designed the animation

-->![image](https://user-images.githubusercontent.com/32979616/52262690-d4b2bd80-2935-11e9-82a4-6fb24eb93d00.png)
![image](https://user-images.githubusercontent.com/32979616/52262707-e2684300-2935-11e9-80e2-9951c00c4d8c.png)
![image](https://user-images.githubusercontent.com/32979616/52262730-f613a980-2935-11e9-9512-c545d64d5b80.png)
![image](https://user-images.githubusercontent.com/32979616/52262768-15123b80-2936-11e9-91f7-75814991c3c3.png)
![image](https://user-images.githubusercontent.com/32979616/52264275-e5653280-2939-11e9-8624-642b9a26442f.png) 

https://www.dropbox.com/sh/h6uwjut25r5cl1g/AACyyiMNKGgTvD2y215tw1Fpa?dl=0

**Comment by gpeal** [comment]
@Mennattu I can't open that aep file with after effects cc on a mac. Can you try exporting differently?
![image](https://user-images.githubusercontent.com/1307745/52903626-17498500-31d5-11e9-831b-9ceff5d8a8f7.png)

**Comment by florianPOLARSTEPS** [comment]
Hi.

We are facing a similar issue currently on Devices running Android <= 8.0 with the lottie 3.0 for Android and Bodymovin plugin 5.5.1.

This is how it is rendered on device
<img width="140" alt="Screenshot 2019-04-10 at 17 01 03" src="https://user-images.githubusercontent.com/21218132/55890081-6054fe80-5bb2-11e9-923b-f609e3b95ca2.png">

The lottie file
[loader.zip](https://github.com/airbnb/lottie-android/files/3064438/loader.zip)

**Comment by florianPOLARSTEPS** [comment]
Update: I managed to fixed my issue by changing a mask around from 
```
inverted: false
mode:add
```

to 
```
inverted: true
mode:subtract
```

So there seems to be something wrong with the mask composition on Android 8.0

**Comment by gpeal** [comment]
@florianPOLARSTEPS Have you tried on 3.0? There were a ton of improvements to masks in 3.0

**Comment by florianPOLARSTEPS** [comment]
@gpeal Yes, we were encountering those issues with 3.0

**Comment by gpeal** [comment]
@Mennattu Your issue was fixed by #1142 so upgrading to 3.0.2 or the soon to be released 3.0.3 will fix it.

@florianPOLARSTEPS I can see your issue and I would either split the mask into separate layers or turn off hardware acceleration with `setRenderMode`. I've opened #1224 to track that.
