### ISSUE TITLE
Load multiple images simultaneously at run time

### ISSUE THREAD

**Issue by mavesonzini** [airbnb/lottie-android#1106]
I have a AE animation with many assets that I want to replace at run time with client images. I've tried doing it with setImageAssetDelegat, but this only returns a bitmap, replacing ALL my placeholders with the SAME image. Is there a way to do this with different images, all loaded to the animation at the same time to be displayed together? thanks

**Comment by gpeal** [comment]
@mavesonzini Can you give them unique assets in the original after effects animation?

**Comment by mavesonzini** [comment]
The original AE animation has png placeholders. This placeholders need to be replaced with images from the client phone when the animation starts running.

**Comment by gpeal** [comment]
@mavesonzini Right, but you should have a unique placeholder for each image you want to replace so you can identify it.
