### ISSUE TITLE
W/LOTTIE: Unable to open asset.

### ISSUE THREAD

**Issue by hoyeolee** [airbnb/lottie-android#1107]
Hi, great job with the lottie,

W/LOTTIE: Unable to open asset.
    java.io.FileNotFoundException: images/bird_img_4.png

It worked 30 minutes ago, but now it doesn't work. I don't know why..
I set the images folder, images are not big.
I'm using the 2.7.0 version.
Any idea for this?

[testtest.zip](https://github.com/airbnb/lottie-android/files/2844706/testtest.zip)

**Comment by gpeal** [comment]
Your animation works fine. You can even put the zip directly in assets and load the composition as a zip file rather than a json with image asset folder.

**Comment by gpeal** [comment]
Looking at your animation, you shouldn't need images though. Try converting your layers to shape layers in After Effects rather than using images.

**Comment by surabhi2789** [comment]
Can we add json to some directory inside assets instead of directly adding to asset?
