### ISSUE TITLE
Problem with drawing lotties with raster images on locked canvas.

### ISSUE THREAD

**Issue by disparate** [airbnb/lottie-android#1108]
I can't draw lotties with raster images on locked canvas (I'm trying to do it on live wallpapers). It seems like no images are drawn, only vector parts.
It works ok on simple lotties and no bug is reproduced when using LottieAnimationView.
Here is the SSCE: https://github.com/disparate/Lottie-surface-issue/tree/master/app/src/main/java/wallpapers/appcraft/com/lottieimagesissue
Version : 3.0.0-beta1 (also reproduced on 2.8.0)

Can you help me with that?

**Comment by gpeal** [comment]
@disparate I don't have time to investigate this for live wallpapers right now. If you are able to solve it, I would probably accept a PR though 😄

**Comment by disparate** [comment]
I investigated a bit and found out that it happened because Callback was not set for lottie drawable. And because of that LottieDrawable couldn't create imageAssetManager to get bitmaps.
The issue was fixed after setting callback.
