### ISSUE TITLE
Listview item will flicker when update to 2.7.0

### ISSUE THREAD

**Issue by xueweiyang** [airbnb/lottie-android#1113]
I want to support praise function，and after I update to 2.7.0，when I scroll the listview，lottieview will flicker and the state will be wrong.

**Comment by gpeal** [comment]
@xueweiyang Can you create a sample project that reproduces this?

**Comment by xueweiyang** [comment]
When I move the invocation of function setAnimation from onViewHolderBind to onViewHolderCreate,the problem has resolved.Thanks for your help and happy new year!
