### ISSUE TITLE
cache not enabled

### ISSUE THREAD

**Issue by pparkppark** [airbnb/lottie-android#1114]
i use lottie 2.8.0.
and load json from url, so i use lottie.setAnimationFromUrl(jsonPath).

in FromUrl Mode, use fileCache but save fileName and load fileName are different.

originUrl : http://front.happypointcard.com/upfiles/appMain/banner/floating/201901071104268207852284518544.json

save fileName : lottie_cache_httpfronthappypointcardcomupfilesappMainbannerfloating201901071104268207852284518544json.json
load fileName :  lottie_cache_httpfronthappypointcardcomupfilesappMainbannerfloating201901071104268207852284518544json.temp.json

so cache logic cant find saved file.

**Comment by gpeal** [comment]
Fixed by https://github.com/airbnb/lottie-android/pull/1040

This is already released in 3.0.0-beta1 (it is stable)
