### ISSUE TITLE
Animation max size

### ISSUE THREAD

**Issue by xgear-public** [airbnb/lottie-android#112]
I have animation with following spec:
```
  "v": "4.5.6",
  "fr": 25,
  "ip": 0,
  "op": 38,
  "w": 360,
  "h": 146,
  "ddd": 0,
.......
```
I want to achieve behavior when animation view fits on screen width.
If i set to LottieAnimationView layout_width="match_parent" and layout_height="wrap_content" i faced with following issue on phones:
if phone's width is 1440px(samsung s7), animation viewport width is 1000px because of LottieComposition MAX_PIXELS = 1000 constraint. So i got space between animation and screen edge. I solved this issue by dynamically changing view height to proper value:
```
DisplayMetrics displayMetrics = getResources().getDisplayMetrics();
		float dpWidth = displayMetrics.widthPixels / displayMetrics.density;
		float dpHeight = displayMetrics.heightPixels / displayMetrics.density;
		mLottieAnimationView.getLayoutParams().height = (int) (displayMetrics.density * 146f / (360f / dpWidth));
```
After applying new height on view, animation viewport fits screen width well. 
So my question is this fix save in terms of stability and performance?
PS: i don't have masks or mattes.

**Comment by gpeal** [comment]
@xgear-public seems like a reasonable restriction to remove if there are no masks or mattes.

**Comment by xgear-public** [comment]
If it is possible - it would be great. Furthermore, i think it would convinient to respect LottieView match_parent atribute in this case. I mean fit animation viewport to screen width(height) if json.getInt("w") * composition.scale more than screen width(height).

**Comment by hafsalrahman** [comment]
Im facing similar issue on etc one, LottieAnimationView is always have a max width it doesn't change width even if I give match parent to fit my screen.

**Comment by gpeal** [comment]
@hafsalrahman I'm not sure I understand your issue. Can you explain it again?

**Comment by m1ga** [comment]
I think I face the same issue. My layout:

```xml
<LinearLayout android:background="#00ffffff" android:layout_height="match_parent" android:layout_width="match_parent" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools">
	<com.airbnb.lottie.LottieAnimationView
		android:id="@+id/animation_view"
		android:layout_gravity="center"
		android:scaleType="center"
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		/>
</LinearLayout>
```

And I set this into a view with a fixed width that is higher than the file width. The LottieAnimationView fills out the whole space (setting a background color to prove it) but the animation is still small in the middle of the view. 
A "autoScale" switch would be nice to have it fill up the space

**Comment by gpeal** [comment]
Use centerCrop instead of center.

**Comment by m1ga** [comment]
👍  I've tested `centerInside` and it wasn't working. `centerCrop`is working in my case. Thanks

**Comment by SirLordPouya** [comment]
Hi
I have same problem as m1ga said but none of ScaleTypes work for me.
here is my code 
`        <com.airbnb.lottie.LottieAnimationView
            android:id="@+id/animation_view"
            android:layout_width="48dp"
            android:layout_height="wrap_content"
            app:lottie_fileName="toggle_switch.json"
            android:layout_gravity="center"
            app:lottie_loop="true"
            app:lottie_autoPlay="true"
            android:scaleType="centerCrop"/>
`
the animation stays very little , center of the animationView.

**Comment by gpeal** [comment]
@SirLordPouya Try setting a fixed height too

**Comment by SirLordPouya** [comment]
@gpeal tnx but nothing changed.
here is my code again
`        <com.airbnb.lottie.LottieAnimationView
            android:id="@+id/animation_view"
            android:layout_width="48dp"
            android:layout_height="48dp"
            android:layout_gravity="center"
            android:scaleType="centerCrop"
            app:lottie_autoPlay="true"
            app:lottie_fileName="toggle_switch.json"
            app:lottie_loop="true" />
`
and here is a pic with layout bounds enabled
![photo_2017-08-12_11-32-45](https://user-images.githubusercontent.com/13719096/29238827-00fbf4ae-7f52-11e7-9b00-0a9a044e255a.jpg)

**Comment by tittokvarghese** [comment]
Hey this is works for me..

<com.airbnb.lottie.LottieAnimationView
            android:id="@+id/mild_waves"
            android:layout_width="match_parent"
            android:layout_height="48dp"
            android:scaleType="centerCrop"
            app:lottie_fileName="mildwaves.json"
            app:lottie_loop="true"
            app:lottie_autoPlay="true" />

**Comment by candrwow** [comment]
I use scaletype=center,it's work,but I don't understand how it work.centercrop/fitxy not work

**Comment by MoustafaElsaghier** [comment]
any solution about that? 
this is my layout code. the image itself becomes smaller and after animate, it becomes larger and animation is distorted
 
`<com.airbnb.lottie.LottieAnimationView
        android:id="@+id/like_btn"
        android:layout_width="48dp"
        android:layout_height="48dp"
        android:layout_gravity="center"
        android:scaleType="center"
        android:src="@drawable/ic_favorite" />`

**Comment by AndrewLotar** [comment]
I set up width in dp that's equal to device width and it scale perfectly good. It doesn't work same with `android:layout_width="match_parent"`.
