### ISSUE TITLE
There is such a problem that needs help

### ISSUE THREAD

**Issue by sangsais** [airbnb/lottie-android#1128]
Problem Description
<com.airbnb.lottie.LottieAnimationView
        android:id="@+id/lottie_animation_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />
![screenshot_2019-02-21-18-36-49-392_com cottontown zsh](https://user-images.githubusercontent.com/6415942/53164646-a7d7f900-360b-11e9-9fa4-1eb237f8cb76.png)

1 Android phone loading json file LottieAnimationView display effect will be partially missing animation
<com.airbnb.lottie.LottieAnimationView
        android:id="@+id/lottie_animation_view"
        android:layout_width="300dp"
        android:layout_height="300dp" />
![screenshot_2019-02-21-18-36-59-507_com cottontown zsh](https://user-images.githubusercontent.com/6415942/53164652-ab6b8000-360b-11e9-9d79-0490c4ce4ab3.png)

2 LottieAnimationView set a fixed width and height will be missing some animation
3 loading using json file + image resource
[培育基地AEP.zip](https://github.com/airbnb/lottie-android/files/2888933/AEP.zip)
![iv_toast_success](https://user-images.githubusercontent.com/6415942/53164152-8aeef600-360a-11e9-953d-9555f03ecc42.png)

this xml 
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/color_ffffff"
    android:fitsSystemWindows="true"
    android:orientation="vertical"
    tools:context=".view.activity.DemoActivity">
    <com.airbnb.lottie.LottieAnimationView
        android:id="@+id/lottie_animation_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />
</LinearLayout>

this code

public class DemoActivity extends BaseActivity {

    @Bind(R.id.lottie_animation_view)
    LottieAnimationView mLottieAnimationView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_using_help);
        ButterKnife.bind(this);
        initView();
    }

    private void initView() {

        //它支持centerCrop 和 centerInside
        mLottieAnimationView.setImageAssetsFolder("lottieIcon");//设置data.json引用的图片资源文件夹
        mLottieAnimationView.setAnimation("pyjd.json");//通过AE生成的图文件(json格式)
        mLottieAnimationView.loop(true);//设置是否循环播放:true为循环.false为播放一次
        mLottieAnimationView.useHardwareAcceleration(true);
        mLottieAnimationView.playAnimation();//开始动画
    }
}
this json file
[购买种子动画.zip](https://github.com/airbnb/lottie-android/files/2888971/default.zip)

**Comment by lordplagus02** [comment]
I'm experiencing a similar issue, in which the animation plays perfectly well on lottiefiles but cuts off halfway through in my android app. Have exhausted all ideas on how to fix it on my end.

**Comment by gpeal** [comment]
@sangsais Can you try without hardware acceleration? Also try different sizes to see if it is a result of a fixed size or whether it has to do with the specific size you are using. Lottie definitely supports fixed size views in general. Finally, try and get your entire animation to be shape layers rather than images. Lottie works much better with shape layers than with images.

**Comment by sangsais** [comment]
Thank you
This problem appears in version 2.2.0
Problem resolution after updating to 2.7.0
