### ISSUE TITLE
Animations run when system animations are disabled

### ISSUE THREAD

**Issue by BoD** [airbnb/lottie-android#1129]
I didn't find this documented except in the changelog but it looks to me that animations shouldn't run when system animations are disabled on the device - however in my case I see them running.

We use `app:lottie_autoPlay="true"` in our layout XML, could it be related to that?

Note: we currently use 2.6.0 (because we can't use AndroidX yet, and also can't use 2.7.0 because of  issue #976)

**Comment by CmoaToto** [comment]
Hey!
I have the same problem, my lottie animations are running during my uitests and make them flaky. And as I set all system animation to 0, shouldn't them not be running?
For now, I need to detect that I am in a ui test and not starting the animation but it makes the code ugly and the use of lottie painful :(
Is it planned to support the system animation scale ?

**Comment by BoD** [comment]
After digging more into this, it looks that this commit is the culprit: https://github.com/airbnb/lottie-android/commit/a212bc8d8c5737a46deafb098e273937d77477b9#diff-3fed8fdab23c1f8e4ddab55a92bb30f1

Basically all logic related to disabling the animations depending on the system settings simply seems to have been removed.

**Comment by gpeal** [comment]
@BoD @CmoaToto I can look in to re-adding this functionality. I would also accept a PR.

**Comment by CmoaToto** [comment]
I'll work on a PR ;)

**Comment by CmoaToto** [comment]
Here is the PR : https://github.com/airbnb/lottie-android/pull/1187 :)

**Comment by adamdanielczyk** [comment]
@CmoaToto @gpeal the merged PR does not seem to help when animation is looping - should it be covered as well?

**Comment by CmoaToto** [comment]
It should!
```
    if (systemAnimationsEnabled || getRepeatCount() == 0) {
      animator.playAnimation();
    }
```
So if `systemAnimationsEnabled` is false and as `getRepeatCount()` return `-1` (https://developer.android.com/reference/android/animation/ValueAnimator.html#INFINITE), there is no `animator.playAnimation()`

However, we rarely experienced a looping animation on one of our lottie during our tests even when `systemAnimationsEnabled` == `false`, but we don't know why for now.

**Comment by adamdanielczyk** [comment]
I have debugged this further and in the case I mentioned, `LottieDrawable.playAnimation()` does not seem to be called. However, `LottieAnimationView.playAnimation()` is called and `wasAnimatingWhenNotShown` flag is set to true. As a result,`LottieDrawable.resumeAnimation()` is called later from `LottieAnimationView.onVisibilityChanged()`. It seems that is how `systemAnimationsEnabled` condition is skipped.

**Comment by adamdanielczyk** [comment]
That's correct, `animator.playAnimation()` will not be called but since `LottieAnimationView.resumeAnimation()` might have been called from another place, `setFrame((int) (getSpeed() < 0 ? getMinFrame() : getMaxFrame()))` would only set animation to last frame and then an animation repeats, isn't that right?

It seems like there should be a similar condition added to `LottieDrawable.resumeAnimation()` or maybe some place deeper like `LottieValueAnimator.postFrameCallback()`. What do you think?

**Comment by CmoaToto** [comment]
I think you're right! great investigation :)
Would you take care of it? If not, I may do so in a near future...

**Comment by adamdanielczyk** [comment]
It seems that it's actually already been done here https://github.com/airbnb/lottie-android/pull/1349 :)
