### ISSUE TITLE
Add support for mask expansion

### ISSUE THREAD

**Issue by ghost** [airbnb/lottie-android#113]
For some reason, in my own app, Lottie will not play a specific animation I have designed. It works for one of the included samples, or a more simple animation I make in AE, but not this specific one:

https://mega.nz/#!z1s1RaCb!cOs8SUHrdzp3qfXYOlfFlXf2wZeItFF4d5RPVFg_JWo (composition I'm trying is Main New)

I first had everything in precomps, but learned that it doesn't support it, so I made a new composition with just four shape layers with animated masks. It just displays white in my app. It shows that there are precomps in that composition, but when exporting with Bodymovin, I shortened it and deleted them.

The exported demo html file also looks exactly how I want it.

Here's a screenshot: http://prntscr.com/e9noo2

Thanks!

**Comment by gpeal** [comment]
@trivisionzero We don't yet support mask expansion.
You can try animating the scale on an ellipse instead for now.

**Comment by Vivimagic** [comment]
Is there an update regarding this? Has this feature been added?

**Comment by gpeal** [comment]
@Vivimagic No but I would accept a PR for it.

**Comment by gpeal** [comment]
I looked into this and I don't think it will be trivial to implement on Android as there is no support for path expansion of the sort that After Effects uses.

I recommend scaling/animating your mask or using a track matte if you need something like this.
