### ISSUE TITLE
animation not smooth & direction is incorrect

### ISSUE THREAD

**Issue by bijuC1983** [airbnb/lottie-android#1130]
Hello,
          I have seen couple of similar issues here but I am facing this issue on both Android & iOS.
The animation is too jittery and skips frames. Also the direction of the animation is incorrect. I cannot attach the original animation due to branding issue, but the designer has recreated the same animation with placeholder text. The demo web preview works correctly.
The demo file, json file, images, aep file etc. can be found [here](https://drive.google.com/open?id=1KGEXX3yDotTaHJPrqUcoYM9SWOflXM_K) 
Any help, feedback or direction will be extremely helpful.
Many Thanks

**Comment by Glurt** [comment]
I'm having similar issues with performance, it seems completely random in that the animation jitters on some high end devices and works perfectly on lower spec devices. Does anyone have any suggestions on where to start trying to fix this?

**Comment by bijuC1983** [comment]
Hello.. Any suggestions on this?

**Comment by gpeal** [comment]
@bijuC1983 I see that you have a ton of images and photoshop layers. Lottie will perform *much* better. You also have a number of masks. They will also perform *much* better on Lottie 3.0 (3.0.0-beta2 is out and is stable)

Finally, try turning on hardware acceleration with `setRenderMode` (Lottie 3 API)
