### ISSUE TITLE
how can i change text lottie json file dynamically 

### ISSUE THREAD

**Issue by sy4tech** [airbnb/lottie-android#1132]
**Read this or your issue will be closed**
hello
I want to change text lottie json file from android .
I did not find it in lottie documentation .
this json file Which I want to modify
https://lottiefiles.com/2283-angel
this text "HALLELUJAH" in the previous file which I want to edit 
I tried this code and did not work with me 👍 
`        lottieAnimationView.addValueCallback(new KeyPath("hallelujah","**"), LottieProperty.TEXT_TRACKING, new LottieValueCallback<>("new Text Change"));
`
Please provide me with the best way to dynamically change the text
* Before opening a new issue, look through existing issues for duplicates.
* Simplify your animation to the simplest animation that reproduces your issue.
* Zip your After Effects AEP file and attach it. Your issue will be auto-closed if it doesn't have an AEP or no explicit reason otherwise is given.
* If you don't know English, run your issue through Google Translate.
* If you leave the template text in your issue, it will be closed.

**Comment by gpeal** [comment]
Use a TextDelegate
