### ISSUE TITLE
Dynamic coloring doesn't work with alpha

### ISSUE THREAD

**Issue by CameronStuartSmith** [airbnb/lottie-android#1134]
Alpha with dynamic color changing does not work

Example code:

`animationView.addValueCallback(
                        new KeyPath(keyPaths),
                        LottieProperty.COLOR,
                        new LottieValueCallback<>(Color.argb(25, 0, 0,255))
                );`

Produces this: ( The object changing is the base of the present )
![screen shot 2019-02-24 at 6 02 04 pm](https://user-images.githubusercontent.com/30812529/53308455-ae11e380-385e-11e9-8e48-35ffaa0d3c79.png)

On iOS, the same effect produces this:
![screen shot 2019-02-24 at 6 01 59 pm](https://user-images.githubusercontent.com/30812529/53308460-b833e200-385e-11e9-8a94-66976072e1d6.png)

**Comment by gpeal** [comment]
In After Effects, color and opacity are two separate properties. You can use the OPACITY property to affect the opacity
![image](https://user-images.githubusercontent.com/1307745/53312794-50d05f00-386b-11e9-9ae0-56f8e95f33f6.png)

**Comment by gpeal** [comment]
A admit that it can be confusing, however.

**Comment by CameronStuartSmith** [comment]
yes it can be a bit confusing only because the iOS version of lottie will actually respond to colors with alpha. working on a lottie wrapper for flutter so I was just trying to be consistent with the two implementations. Thanks for the help and clarification.
