### ISSUE TITLE
how to get bitmap from one frame of lottieAnimationView

### ISSUE THREAD

**Issue by LiLiLiLiSi** [airbnb/lottie-android#1144]
I have setProgress in LottieAnimationView, than I want to get this progress of Lottie's Bitmap

**Comment by ArthurVimond** [comment]
You first have to get the Drawable from the LottieAnimationView (use getDrawable()), then convert this Drawable to a Bitmap, by using a Canvas.
Please have a look on this link to convert a Drawable to a Bitmap: https://stackoverflow.com/questions/3035692/how-to-convert-a-drawable-to-a-bitmap.

**Comment by gpeal** [comment]
^ This is correct. We do it in testing [here](https://github.com/airbnb/lottie-android/blob/master/LottieSample/src/androidTest/java/com/airbnb/lottie/LottieTest.kt#L597).

**Comment by LiLiLiLiSi** [comment]
> You first have to get the Drawable from the LottieAnimationView (use getDrawable()), then convert this Drawable to a Bitmap, by using a Canvas.
> Please have a look on this link to convert a Drawable to a Bitmap: https://stackoverflow.com/questions/3035692/how-to-convert-a-drawable-to-a-bitmap.

thank you~

**Comment by juanchosaravia** [comment]
The link is not valid anymore, here is the updated:
https://github.com/airbnb/lottie-android/blob/master/LottieSample/src/androidTest/java/com/airbnb/lottie/samples/LottieTest.kt

**Comment by AndroidDeveloperLB** [comment]
How do I get the bitmaps as it plays, though?
Can you please show a sample of what you did?

I tried this which used to work for animated GIF/WEBP, but for some reason it doesn't work for Lottie animation:

```
        LottieCompositionFactory.fromRawRes(this, R.raw.car_driving_landscape).addListener { lottieComposition ->
            val drawable = LottieDrawable()
            drawable.callback = object : CallbackEx() {
                override fun invalidateDrawable(who: Drawable) {
                    super.invalidateDrawable(who)
                    Log.d("AppLog", "invalidateDrawable:${who.intrinsicWidth} ${who.intrinsicHeight}")
                }
            }
            drawable.composition = lottieComposition
            drawable.repeatCount = AnimatedImageDrawable.REPEAT_INFINITE
            drawable.playAnimation()
        }
```

The invalidateDrawable doesn't seem to be called, and it seems what I wrote is even similar to some other post:
https://github.com/airbnb/lottie-android/issues/1719
