### ISSUE TITLE
Stroke circle showing a solid fill inside

### ISSUE THREAD

**Issue by Bigbigann** [airbnb/lottie-android#1147]
Hi I have created a simple loading animation using the basic trim effect.

The animation looks good when preview in lottie on web however when it is tested on IOS and Android the stroke circle have a solid shape inside it.

I am not using any effect and the round shape is just a round only with stroke so not sure what is going on here. 

Would anyone know what causes the issue? 

Here is the json file I have exported
[loading_1.json.zip](https://github.com/airbnb/lottie-android/files/2949009/loading_1.json.zip)

And here is the aep file
[loading_debug.aep.zip](https://github.com/airbnb/lottie-android/files/2949010/loading_debug.aep.zip)

Any help would be appreciated! Thank you in advance.

**Comment by gpeal** [comment]
@Bigbigann This seems fine as of lottie 3.0.0-beta2. Likely because we added support for hidden contents.

**Comment by Bigbigann** [comment]
@gpeal thank you for the reply. 

Sorry I am still feeling a little confused could you elaborate a little bit? So is there a solution to the problem? Does the dev need to upgrade lottie version to solve the issue?

**Comment by gpeal** [comment]
@Bigbigann Yes, try 3.0.0-beta3.

**Comment by Bigbigann** [comment]
@gpeal sorry being such a trouble. I am not sure if I could keep replying you here or open a new ticket. I have checked with our developer for some reason it is not possible for us to use the latest version of lottie in app ( we are using lottie 2.7.0). 

I have removed the hidden contents but the problem keeps showing up. I think I am only using trim path ( start / end point and offset ) in the animation so have no idea what causes the issue.  
<img width="151" alt="Screen Shot 2019-03-08 at 12 32 07 PM" src="https://user-images.githubusercontent.com/48397314/54107708-c8db7f00-443e-11e9-832b-52e838de6355.png">

**Comment by gpeal** [comment]
@Bigbigann Unfortunately, you're going to have to ask your developer to upgrade your app to androidx to use the latest version. They're going to start getting stuck on lots of old libraries if they don't.
Here is what it looks like on the latest version.
![Loading](https://user-images.githubusercontent.com/1307745/54134850-ede7d780-43d5-11e9-8baa-4af2a81faf3b.gif)

**Comment by Bigbigann** [comment]
@gpeal cool thank you really appreciate the help!!
