### ISSUE TITLE
setFrame not work properly when ListView scrolls

### ISSUE THREAD

**Issue by RhuanPacheco** [airbnb/lottie-android#1157]
I have a list view in which each item contains an icon created with lottie. The icon is used to add or remove items from the favorites list. The animation is composed in two halves, the add animation to delete and vice versa. I have added limits in the Frames to make the click animation in both directions. Clicking works correctly. The problem comes when you scroll and return that the icon does not show the correct frame, I know that it is because the icon changes since the listview item contains another user. But in my code I have put a setFrame for every time the Adapter of the listview executes getView and it seems that the setFrame does not work at times, sometimes yes, it seems random.

Code on ListView Adapter getView():
```
itemButton.pauseAnimation();

if(favorite) itemButton.setFrame(145);
else itemButton.setFrame(55);

itemButton.setOnClickListener(v -> {
    if(favorite) itemButton.setMinAndMaxFrame(145, 195);
    else itemButton.setMinAndMaxFrame(55, 105);
    itemButton.playAnimation();
    favorite= !favorite;
});
```

**Comment by RhuanPacheco** [comment]
If I make a print of the value of getFrame just after setFrame, many times the value is incorrect, it also seems random.

`System.out.println(favorite+" - "+itemButton.getFrame());`

The output can be:
```
true - 0
true - 105
true - 145 // the right one
false 145
false - 55 // the right one
```

I do not understand why sometimes it does not show the correct frame.

**Comment by gpeal** [comment]
@RhuanPacheco Can you try creating the composition manually using LottieCompositionFactory, then set the composition with that object rather than with an asset/resource name?

**Comment by gpeal** [comment]
Also, what version of Lottie?

**Comment by RhuanPacheco** [comment]
I'm sorry, it was my fault. The problem was that I set the minimum and maximum frame when I click and when the scroll changes position making the ListItem content change the previously set frame range it was not valid for the new ListItem content. The solution has been to set the frame range both when clicking and in the getView of the Adapter.

itemButton.pauseAnimation();

if(favorite) {
    itemButton.setMinAndMaxFrame(145, 195);
    itemButton.setFrame(145);
} else {
    itemButton.setMinAndMaxFrame(55, 105);
    itemButton.setFrame(55);
}

itemButton.setOnClickListener(v -> {
    if(favorite) itemButton.setMinAndMaxFrame(145, 195);
    else itemButton.setMinAndMaxFrame(55, 105);
    itemButton.playAnimation();
    favorite= !favorite;
});
