### ISSUE TITLE
Animations don't work with Lottie Forms 2.7.0

### ISSUE THREAD

**Issue by caseyryan** [airbnb/lottie-android#1158]
I have installed Lottie Forms 2.7.0 to my Xamarin Forms project but I can't make animations play. 
There is no AnimationViewRenderer in lottie's android library, there's no way to use it. Only the iOS version of the renderer is available. When I downgrade the version to 2.5.2.1 the renderer is there and after calling Init() on it, all animations work fine. I tried to reinstall the library twice with the same result. Only the older versions work.
What's wrong with the 2.7.0 version?

**Comment by gpeal** [comment]
You'll have to contact somebody who works on Xamarin about that.

**Comment by caseyryan** [comment]
Sorry :) Google lead me to the wrong repo
