### ISSUE TITLE
Strange shape appears in the last frame of line animation

### ISSUE THREAD

**Issue by Bigbigann** [airbnb/lottie-android#1159]
Hi the animation I create is a line animation. It works well on IOS however on Android it shows a strange shape when the animation ends on the LAST frame (image attached). 

We are currently using v 2.7.0 lottie library and are considering to update to the latest version in the near future. Just wondering if there is a workaround while using the old version of lottie?

![image](https://user-images.githubusercontent.com/48397314/54318040-e16bb500-4649-11e9-8b52-cf1a261dc20c.png)

Here is the aep file.
[onboarding_line_debug.aep.zip](https://github.com/airbnb/lottie-android/files/2963875/onboarding_line_debug.aep.zip)

Here is the json file.
[line.json.zip](https://github.com/airbnb/lottie-android/files/2963877/line.json.zip)

Many thanks in advance.

**Comment by gpeal** [comment]
This renders fine on Lottie 3.0.0-beta2 😄
