### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by EricInCD** [airbnb/lottie-android#116]
Hi,I'm using Lottie on Android,it's really fantastic,but I found a problem.
Before entering the activity which was using lottie,CPU usage is less than 1%,but when I entered it,CPU usage increased to more than 15% and never go down even I quit the activity.

CPU usage:
before:0.85%
entered:17.51%
quit:15.52%

**Comment by gpeal** [comment]
@EricInCD Can you attach a sample project that repros this?

**Comment by EricInCD** [comment]
I created a new project, but I cannot reproduce it, so I think it's my issue.😓

**Comment by AlanCheen** [comment]
I met this case too , the CPU is almost increased to 50%!

What can i do to decrease ?

**Comment by Ernest-su** [comment]
[LottieDemo.zip](https://github.com/airbnb/lottie-android/files/1110818/LottieDemo.zip)

I met this case too , the CPU is increased to 40%!

**Comment by Ernest-su** [comment]
@gpeal I use version 2.0.0

**Comment by ChenSiLiang** [comment]
![cpu_profilier](https://user-images.githubusercontent.com/9266250/35024607-6d1b5396-fb7b-11e7-9bb8-3ef9480edd2f.png)
I use Android Profiler in AS to record about 5s video about CPU usage, It costs about 1/3 more CPU usage than normal.

**Comment by vinayakgupta02** [comment]
Hi guys,
 am using this version "compile 'com.airbnb.android:lottie:2.5.4" I tried multiple animations they were absolutely great, but its true it shoots up the CPU usage once active. 
Actually its not same for all animations, some shooting up to 32% while some shooting up to 5-7% only
Is there any way we could handle it?
