### ISSUE TITLE
Animation works on the web but does not work on the phone

### ISSUE THREAD

**Issue by furkanscream** [airbnb/lottie-android#1161]
Hi, I made an animation using the Puppet Pin Tool with the Duik Bassel plugin, but after searching, I learned that Bodymovin did not support Puppet Pin Tool. I removed the Puppet Pins and used the Arm (or Front leg) Feature in Duik Bassel, I did my animation smoothly and I checked it on LottieFiles. However, my mobile app doesn't appear as it appears on the web.
Where am I making a mistake?

**Json File:**

[yeniJson.zip](https://github.com/airbnb/lottie-android/files/2970739/yeniJson.zip)

**After Effects File:**

[yeniAE.zip](https://github.com/airbnb/lottie-android/files/2970740/yeniAE.zip)

**After Effect preview**

![Screenshot_5](https://user-images.githubusercontent.com/29354459/54434718-f4f94780-473f-11e9-9f41-e82cdb3cab6f.png)

**LottieFiles.com Preview:**

[https://lottiefiles.com/share/syAHvu](https://lottiefiles.com/share/syAHvu)

**My Android Project:**

**Android XML:**

`<com.airbnb.lottie.LottieAnimationView
        android:id="@+id/animation_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:lottie_autoPlay="true"
        app:lottie_enableMergePathsForKitKatAndAbove="true"
        app:lottie_fileName="yeni.json"
        app:lottie_loop="true" />`

**Video of the problem:**

[https://www.youtube.com/watch?v=NggsY5cGsN8&feature=youtu.be&fbclid=IwAR1lwyjW-JpUolV3roSbDouYIXaaSEYkjja8y4obj1AcBzVOzQ5eQSmn5ck](https://www.youtube.com/watch?v=NggsY5cGsN8&feature=youtu.be&fbclid=IwAR1lwyjW-JpUolV3roSbDouYIXaaSEYkjja8y4obj1AcBzVOzQ5eQSmn5ck)

**Lottie Android Application Errors:**

![53501946_312856142766769_6990826046161420288_n](https://user-images.githubusercontent.com/29354459/54435055-b021e080-4740-11e9-9e83-4287bbf2c3cc.png)

**Comment by gpeal** [comment]
As indicated in the screenshot, Lottie Android doesn't support expressions. Feel free to refer to [supported features](http://airbnb.io/lottie/supported-features.html) for more info.

**Comment by furkanscream** [comment]
@gpeal Well, can't any character animation be played with Lottie using Duik Bassel?

**Comment by gpeal** [comment]
@furkanscream Yes, Lottie has some text support but if you animate it with expressions, the expressions will be ignored.

**Comment by marcelo15** [comment]
> @furkanscream Yes, Lottie has some text support but if you animate it with expressions, the expressions will be ignored.

Ok, sorry Im new to this. Im having a similar problem. 
So can I use Duik to animate characters and create json files for Lottie Android?
