### ISSUE TITLE
Feature request: add static image preview when in edit mode.

### ISSUE THREAD

**Issue by mauriciogior** [airbnb/lottie-android#1165]
**This is a feature request.** I can work on it myself if a general agreement as useful exists.

Since it's hard to run animations on preview mode inside Android Studio, I'd like to suggest to show a static image of the first frame or a certain frame (using tools to set it) to render when `isInEditMode()` returns true.

What are your thoughts?

**Comment by gpeal** [comment]
The Android Studio renderer cannot render Lottie, unfortunately. I tried once and pretty much no animations rendered correctly.

**Comment by mauriciogior** [comment]
@gpeal Did you read my suggestion at all? I'm suggesting to render a specific frame of the animation only, and not the animation itself.

**Comment by gpeal** [comment]
@mauriciogior I understand but even individual frames failed to render in most cases. This was about a year ago though so if you want to take another stab at it, feel free 😄

**Comment by khaled-0** [comment]
+1
It would be a good addition.
