### ISSUE TITLE
Pausing an animation that was playing when hidden will play again on resume

### ISSUE THREAD

**Issue by thierryd** [airbnb/lottie-android#1166]
This is similar to issue [#987](https://github.com/airbnb/lottie-android/issues/987)

But the [fix](https://github.com/airbnb/lottie-android/pull/1098) proposed is incorrect, at least in my use case. I do think the fix is correct in some case: if the view is set from VISIBLE to GONE, then the animation must stop. But when the app is put in the background, `onVisibilityChanged` is **not** called. What is called is `onWindowVisibilityChanged`

To replicate the issue:
1. Start a looping animation
2. Put the app in the background
3. Check the profiler in Android Studio

Expected result:
- Nothing is running

What is happening:
- The profiler shows that the animation still runs

**Comment by gpeal** [comment]
@thierryd I just tried this on master. Can you provide more repro steps? I played an animation in the sample app in the repo on loop then pressed home and `onVisibilityChanged` was called.

**Comment by gpeal** [comment]
@thierryd If this is an issue, I'll fix it asap as 3.0 is coming out as soon as later today.

**Comment by thierryd** [comment]
@gpeal  I have create a project to replicate the issue:
https://github.com/thierryd/lottieVisibilityBug

I see that `onVisibilityChanged` is called with a value INVISIBLE on my device (api 26) when the app goes into the background. That's strange, as GONE would make more sense...

`onWindowVisibilityChanged` is called with the value INVISIBLE and then GONE.

Furthermore, I think that the [fix ](https://github.com/airbnb/lottie-android/pull/1098) breaks the following use case:

- Start a looping animation
- Set the view to GONE
- Pause the animation
- Set the view to VISIBLE

Expected result:
- The animation should be paused

What is happening:
- The animation is looping

**Comment by gpeal** [comment]
@thierryd I see, good point. Would simply moving the `onVisibilityChanged` logic to `onWindowVisibilityChanged` resolve this?

**Comment by thierryd** [comment]
@gpeal I think using `onWindowVisibilityChanged` would be valid! :)

**Comment by gpeal** [comment]
@thierryd your app uses 2.8.0. The onVisibilityChanged code was added in 3.0 (beta3 is out now, final is coming very soon). I just verified that it no longer runs in the background just by updating the dependency.

I think your case where you pause a GONE view but that is much less concerning.

**Comment by thierryd** [comment]
@gpeal It is totally normal that the animation is paused when the app is put in the background when 3.0 is used since it contains the [onVisibilityChanged fix](https://github.com/airbnb/lottie-android/pull/1098).

When an app is put in the background, both `onVisibilityChanged` and `onWindowVisibilityChanged` is called.

I have given some more thought and I think you are correct. Ultimately, `onVisibilityChanged` is the way to go to pause/resume an animation. :)

I'm more concern about my use case when the animation is specifically stopped after is was set as View.GONE. We might need another state instead of using a boolean (see `wasAnimatingWhenVisibilityChanged` in [this](https://github.com/airbnb/lottie-android/commit/a6d4f34c10c14c7c87c91cd851a997f915984b7f).

**Comment by gpeal** [comment]
@thierryd I would accept a PR that flips those flags in play/pause/resume/cancel

**Comment by soshial** [comment]
If animation had been looping before app was minimized, shouldn't animation resume playing when app is restored/reopened? @thierryd
