### ISSUE TITLE
Use json animation to report an error

### ISSUE THREAD

**Issue by onedreamyyc** [airbnb/lottie-android#1169]
java.lang.IllegalArgumentException: Key times and values must be the same length [0.0, 0.22923589, 0.6112957, 1.0] vs [124]

Hello author, I don't know why this error occurred, can you explain

**Comment by gpeal** [comment]
@onedreamyyc Which version of Lottie and can you attach your aep file?

**Comment by onedreamyyc** [comment]
bgBoard.json  it is my Json file

**Comment by onedreamyyc** [comment]
[bgBoard.json](url)

**Comment by onedreamyyc** [comment]
[bgAnimation.zip](https://github.com/airbnb/lottie-android/files/3016023/bgAnimation.zip)

Hello author, this is my animation aep file, please help me to see what is wrong, thank you very much

**Comment by gpeal** [comment]
@onedreamyyc I just exported and played your animation with the latest bodymovin plugin and Lottie 3.0. 
Lottie doesn't support gaussian blue effect though.

**Comment by onedreamyyc** [comment]
Okey, I see  thank you .

**Comment by ercanduman** [comment]
Any solution to this issue?

**Comment by ercanduman** [comment]
Updating library to latest version solves the problem

`implementation 'com.airbnb.android:lottie:3.4.0'`

Thanks for this great library
