### ISSUE TITLE
Using Deer animation looks bad

### ISSUE THREAD

**Issue by UdiOshi85** [airbnb/lottie-android#1170]
Hi,
I'm trying to use this lottie
https://lottiefiles.com/978-walking-deer

After downloading i'm setting this in XML:
`<com.airbnb.lottie.LottieAnimationView
                    android:id="@+id/lottie_animation"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    app:layout_constraintTop_toTopOf="@+id/title"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:lottie_fileName="lottie_deer.json"
                    app:lottie_loop="true"/>`

And this is how the deer looks like:
https://ibb.co/0KnstSG

What I'm doing wrong?

Thanks!

**Comment by gpeal** [comment]
Lottie Android doesn't support expressions.
