### ISSUE TITLE
Create thumbnails for lottie composition.

### ISSUE THREAD

**Issue by disparate** [airbnb/lottie-android#1172]
In my application I have a lot of big lotties (some of them with raster images) that are intended to be shown in fullscreen. I was asked by designer to create a screen with thumbnails of lotties (in recyclerview), but it takes much time for them to render and much memory that leads to a lot of work for GC and frames skipping (sometimes even to OOM).

My question is how can I create bitmap previews for first frame of composition that I can then use instead of full composition for thumbnails? Maybe you know how to render it to bitmap in background? Or integrate it somehow with Glide, for example?

Thanks.

**Comment by gpeal** [comment]
You can just follow normal practices to render a drawable to a bitmap as demonstrated in https://github.com/airbnb/lottie-android/issues/1144
