### ISSUE TITLE
Lottie Animation Drawable Renders Incorrectly Inside a Floating Action Button on Android 5

### ISSUE THREAD

**Issue by LucianIacob** [airbnb/lottie-android#1180]
[loading_animation.zip](https://github.com/airbnb/lottie-android/files/3068603/loading_animation.zip)

I'm trying to set a `**LottieDrawable**` as _image drawable_ for a `FloatingActionButton`. The problem comes when I try to run the code on an Android 5 device: the animation is not centered within the button as it is in Android >= 6. Somehow it is losing padding or margin. Anyone has an answer for this problem or maybe an workaround?

```
val lottieDrawable = LottieDrawable()

LottieCompositionFactory.fromRawRes(context, R.raw.loading_anim).addListener { lottieComposition ->
     lottieDrawable.composition = lottieComposition
     lottieDrawable.scale = 0.5F
     lottieDrawable.repeatCount = LottieDrawable.INFINITE
     lottieDrawable.playAnimation()
}

floatingActionButton.setImageDrawable(lottieDrawable)
```

Expected output (works correctly on Android 6,7,8,9,Q):
![Expected_Result](https://user-images.githubusercontent.com/10145568/55958045-6f9a8180-5c70-11e9-905e-75f21602c796.png)

Actual output (Android 5):
![Actual_result_os5](https://user-images.githubusercontent.com/10145568/55958060-76c18f80-5c70-11e9-95ee-28e60deff77f.png)

**Comment by LucianIacob** [comment]
@gpeal any ideas on this, please?

**Comment by gpeal** [comment]
@LucianIacob I haven't seen this before so I'll have to do some debugging. Feel free to do some as well.

**Comment by MonikaJethani** [comment]
@LucianIacob @gpeal Is this still open? Can I work on this?

**Comment by gpeal** [comment]
@MonikaJethani You are welcome to take a look

**Comment by nangonghuang** [comment]
have you set fab size in xml ? maybe you can try 
```
android:scaleType="centerInside"
app:fabCustomSize="50dp"
```
instead of set layout_width and layout_height

**Comment by gpeal** [comment]
@LucianIacob it's likely a bug on FloatingActionButton but if you set the animation _after_ it is laid out, it works.
