### ISSUE TITLE
Support For Character Animator animations

### ISSUE THREAD

**Issue by aadishgoel2013** [airbnb/lottie-android#1181]
# Is there any way to use Character Animator animations inside android with lottie.
I have tried dynamically linking my character animator project to after effects and then to lottie but no success there.

### Only success i got is by 
i can do it is by saving all the frames and then running frames by lottie and playing audio in sync by media player but that increases the size by beyond acceptable limit like 50-60 mb per animation.

So How should i porceed 
@bodymovin
@gpeal 
@therealsalih

**Comment by bodymovin** [comment]
Hi, I'm not sure what the format of character animator is, but as far as I know, it produces a deformation mesh on top of the drawing, which is not supported by the extension or the players unfortunately.

**Comment by gpeal** [comment]
Unfortunately, the character animator is unlikely to be supported on Android in the near future, if ever so I'm going to close this for now.
