### ISSUE TITLE
Text renders right aligned

### ISSUE THREAD

**Issue by luckyde** [airbnb/lottie-android#1182]
Hi there,
I'm trying to render centered text on lottie android and ios, on ios it's fine but on android it right aligns it. What am i doing something wrong? I tried to make the textbox be the full width of the file with no luck.
Also the rounded corners arent respected on android but that's not a big issue i can convert it to a path.
Everything else in the animation renders fine
I can't attach the original after effects file for legal reasons, it's a company file but I'm attaching a dumbed down version of it with just the text

Text keys used: opacity and scale
expected output:
![Screen Shot 2019-04-11 at 12 15 44 PM](https://user-images.githubusercontent.com/10063861/55973434-926a6d00-5c53-11e9-8f12-f218386616bb.png)
Android output
![Screen Shot 2019-04-11 at 12 06 44 PM](https://user-images.githubusercontent.com/10063861/55973459-9dbd9880-5c53-11e9-94c4-4ced1750053a.png)

[100_text.aep.zip](https://github.com/airbnb/lottie-android/files/3069603/100_text.aep.zip)

**Comment by gpeal** [comment]
@luckyde Have you tried with Lottie 3.0? This should be fixed.

**Comment by gpeal** [comment]
Indeed, this is fixed in 3.0
![image](https://user-images.githubusercontent.com/1307745/56078431-3d139480-5de8-11e9-968e-58c0f1a9235f.png)
