### ISSUE TITLE
TextLayer uses incorrect textLineWidth to draw

### ISSUE THREAD

**Issue by cplus2016** [airbnb/lottie-android#1183]
Hi, I am trying to debug the TextLayer.java, I find the `textLineWidth` which used to do text justification may be incorrect.  The `textLineWidth` never consider the `documentData.tracking `value.
![image](https://user-images.githubusercontent.com/11784301/56024998-d9d02680-5d43-11e9-8609-8ee893a2bdc9.png)

**Comment by gpeal** [comment]
@cplus2016 Would it be possible for you to make a PR for this?
