### ISSUE TITLE
playAnimation() is not working when called from onAnimationEnd callback??? 

### ISSUE THREAD

**Issue by ganeshpadhayay** [airbnb/lottie-android#1184]
I am trying to run multiple animations in the same Lottie view 
I am simply calling playAnimation() on the same view again, and it is internally giving onCancel callback then onEnd callback and from onEnd callback, I am again calling playAnimation with a new json.
Now, In Android version 8, 9, I am able to get the onStart Callback after these events and the second animation starts correctly but in Android 7.0 it is not giving callback and hence animation is not starting

Please refer to the following issues as well as they are also relevant to this problem :

https://github.com/airbnb/lottie-android/issues/314

https://github.com/airbnb/lottie-android/issues/174

**Comment by gpeal** [comment]
@ganeshpadhayay I wasn't able to reproduce this on a 7.0 device.
This code worked with and without setting a new animation.
```
        animationView.addAnimatorListener(object: Animator.AnimatorListener {
            override fun onAnimationRepeat(animation: Animator?) {
                Log.d("Gabe", "onAnimationRepeat: ")
            }

            override fun onAnimationEnd(animation: Animator?) {
                Log.d("Gabe", "onAnimationEnd: ")
                animationView.setAnimation("DynamicGradient.json")
                animationView.playAnimation()
            }

            override fun onAnimationCancel(animation: Animator?) {
                Log.d("Gabe", "onAnimationCancel: ")

            }

            override fun onAnimationStart(animation: Animator?) {
                Log.d("Gabe", "onAnimationStart: ")
            }
        })
```

If you think this is still an issue with the latest code (3.0.3), can you reopen this with a sample project?

**Comment by voghDev** [comment]
I can confirm that this code is working with `playAnimation()` called from `onAnimationEnd`

```
    override fun onAnimationEnd(animator: Animator?) {
      if (nextAnimation != null) {
        animationView.setAnimation(nextAnimation)
        animationView.playAnimation()
        nextAnimation = null
      }
    }
```
I'm using version 3.0.4 of the library
