### ISSUE TITLE
Animation Is Different On Android vs Web

### ISSUE THREAD

**Issue by joblolin95** [airbnb/lottie-android#1188]
Hello! 

I have an animation that loops without error in my Android app, as well as in the Android Lottie App. However, it looks noticeably different on Android than when it loops in the web browser.

[Here](https://lottiefiles.com/share/X40qBe) is the Lottie web preview for the file (note, the JSON file can be downloaded from there). I don't have the AE file readily at hand to provide, unfortunately.

On web, the animation loops smoothly without noticeable breaks in it. However, as you may notice, on Android the animation slides downward partway through each iteration, and the transition as it loops is not near as smooth as a result. I've looked over the troubleshooting steps mentioned in the documentation, but still am unable to find the cause of the issue.

Is there a problem with the JSON for this animation that causes this difference?

Thank you!

**Comment by StuStirling** [comment]
I have had something similar just now. Updating to the latest version of Lottie resolved this for me.

**Comment by Moes81** [comment]
It didn't for me. I have different colors in Web and in Android. To whom can I provide the screenshots, `.aep` and `.json`? I'd rather do it by email, since it's an unreleased product.

**Comment by gpeal** [comment]
@Moes81 Does your animation use any unsupported features (such as expressions)?
http://airbnb.io/lottie/#/supported-features

**Comment by Moes81** [comment]
@gpeal Thank's for checking. Our designer told me, she went through the list, and can confirm she only used supported features. Any chance I can get a second opinion for the `.aep` file from you guys?

**Comment by gpeal** [comment]
@Moes81 Can you create a private repository with the aep and share it with me?

**Comment by Moes81** [comment]
@gpeal I invited you to the private repo. Did you receive the invite?
The `.aep` file is in the root folder `vui_animation.aep`. The exported json is located in the `/raw` folder.
If you start the app, you see three animations. Those are 3 different "segments" within the same json. The color of the bottom animation segment is correct.

Thank you very much in advance, for taking a look.

**Comment by dev-aly3n** [comment]
have the same issue. how did you resolve it?
