### ISSUE TITLE
Just for telling you.

### ISSUE THREAD

**Issue by xingxingxiaoyu** [airbnb/lottie-android#119]
I load all jsonFile of your App to a ReceiverView for test,and the Appication dead.

**Comment by gpeal** [comment]
@xingxingxiaoyu can you attach a stack trace?

**Comment by xingxingxiaoyu** [comment]
Sorry,my test appication was deleted because of some reason,but it was not long.
Can i write it and attach a stack trace tomorrow?
Sorry for my poor English.

**Comment by gpeal** [comment]
@xingxingxiaoyu sure, just reopen this when you attach it

**Comment by xingxingxiaoyu** [comment]
sorry,I find that the reason is that I add some string which is not end of ".json",when I scrool recyclerview , it dead.
sorry,good luck.
