### ISSUE TITLE
Repeated stripe on LottieAnimationView when it is full screen

### ISSUE THREAD

**Issue by thirtyyuan** [airbnb/lottie-android#1191]
#### Device ####
Huawei P20 (Only)

#### Version ####
Android 9, EMUI 9.0.0

#### How About My Case ####
I use a LottieAnimationView which is full screen, and I only load it but did not play it, so, it's look like a image as a background. But I found and only found it's generate some repeated stripe on Huawei P20. and I does' not find this appearance on other device. If you have any idea, please tell me, I will try to play the animation to check does it has this phenomenon.

#### Phenomenon ####
![Repeated stripe on LottieAnimationView when it is full screen](https://ws1.sinaimg.cn/large/006tNc79ly1g2dzmn8hn1j30u01qc7d5.jpg)

**Comment by gpeal** [comment]
@thirtyyuan Try setting the renderMode to SOFTWARE

**Comment by thirtyyuan** [comment]
> @thirtyyuan Try setting the renderMode to SOFTWARE

I'll try that, thx!

**Comment by thirtyyuan** [comment]
Can I use `mLottieView.useHardwareAcceleration(false)` to replace `setRenderMode()` when version below 3.0.0? I find the `setRenderMode()` is added in 3.0.0, and the source code almost same with each other.

**Comment by gpeal** [comment]
@thirtyyuan correct. I recommend upgrading to 3.0 though.

**Comment by thirtyyuan** [comment]
OK, but I can't repeat this problem again, even use the device which I find the problem. If I find it again, I'll try. Maybe this issue could be close temporarily.
--
Sent from myMail for Android Monday, 06 May 2019, 10:50PM +08:00 from Gabriel Peal  notifications@github.com :

**Comment by thirtyyuan** [comment]
I have got this problem again, even if I added `useHardwareAcceleration(false)` to mLottieAnimationView.

**Comment by gpeal** [comment]
@thirtyyuan Can you attach a screenshot? Can you also try 3.0. That API has been replaced with `setRenderMode`

**Comment by thirtyyuan** [comment]
Here is a new screenshot about this issue, which is happened just now.
I really want to upgrade to 3.0, but I can't, cause our project have some dependencies still use low version `android.support` rather than `androidx`. I will try to upgrade to `androidx`.
![new_screenshot](https://user-images.githubusercontent.com/16081968/57620159-83f8d380-75ba-11e9-9ef1-3312e8dc0e1b.png)

**Comment by gpeal** [comment]
@thirtyyuan It is _highly_ recommended to upgrade. Androidx alone is worth the upgrade. It is stable and all new improvements and security fixes will be done there.

**Comment by thirtyyuan** [comment]
@gpeal OK，I'm already upgrade androidx for this issue, hope it won't happen ;) Can I ask some another question? Does the whole upgrade just need **Refector**  -> **Migrate to androidx** and add new proguard-rules? How to test or prove the upgrade is truly perfect done?

**Comment by gpeal** [comment]
@thirtyyuan https://developer.android.com/jetpack/androidx/migrate

**Comment by gpeal** [comment]
I'll close this for now. Reopen it with a sample project and animation that can reproduce it if it does. If not, I won't be able to debug it myself.

**Comment by EverGreenArun** [comment]
Hi, I am using androidx only, still facing same issue, Lottie version is "3.2.2"
