### ISSUE TITLE
Can version3.0.0 work with android library?

### ISSUE THREAD

**Issue by jhwsx** [airbnb/lottie-android#1192]
I do not use androidx, how can I use version 3.0.0?

**Comment by gpeal** [comment]
@jhwsx You must upgrade to androidx. It is strongly recommended to do it anyway since many new libraries will start requiring it.

**Comment by jhwsx** [comment]
I am afraid that androix library is not stable.

**Comment by gpeal** [comment]
@jhwsx That's not true
