### ISSUE TITLE
LottieAnimationView setProgress not working  for Lottie 2.7.0

### ISSUE THREAD

**Issue by yigewo** [airbnb/lottie-android#1193]
**Read this or your issue will be closed**

* Before opening a new issue, look through existing issues for duplicates.
* Simplify your animation to the simplest animation that reproduces your issue.
* Zip your After Effects AEP file and attach it. Your issue will be auto-closed if it doesn't have an AEP or no explicit reason otherwise is given.
* If you don't know English, run your issue through Google Translate.
* If you leave the template text in your issue, it will be closed.

**Comment by yigewo** [comment]
This is my code:

    fun updateLottView(isLike: Boolean, anim: Boolean = false) {
              mBottomLikeImg.setAnimation("anim.json")
            if (anim && isLike) {
                mBottomLikeImg.playAnimation()
            } else {
                mBottomLikeImg.progress = (if (isLike) 1 else 0).toFloat()
                mBottomLikeImg.cancelAnimation()
            }
        }
    }

**Comment by gpeal** [comment]
@yigewo Can you try again on 3.0 and reopen with a sample project if it is still an issue?

**Comment by diogojg** [comment]
I'm setting progress to 1.0 and it does not work after onViewCreated() on version 3.0.1.
I have also tried in the XML.,
