### ISSUE TITLE
How do I get the position and size within the specified frame range?

### ISSUE THREAD

**Issue by Airsaid** [airbnb/lottie-android#1197]
I'm now splitting the Lottie animation into a few paragraphs (through the start and end frames), each of which has no connection to the previous animation (and eventually forms a complete image). How do I get the exact location and size of the graphics in each animation?

**Comment by gpeal** [comment]
@Airsaid You can use dynamic properties. Their callback will give you the runtime value on each frame.
http://airbnb.io/lottie/#/android?id=dynamic-properties
