### ISSUE TITLE
Image asset size ignored, no scaling

### ISSUE THREAD

**Issue by mmakmw** [airbnb/lottie-android#1200]
When using image assets in an animation, the _image size_ defined in the .json is _ignored_. The image is _not scaled_ to the defined width and height. It's displayed exactly as big as the image asset is.

In my example, the animation is `100x100` and the image asset is `100x100 px`. If I use an image asset with `200x200 px` (for a better resolution), only a part of the image is visible since it is not scaled to `100x100` to fit in the animation view.

`{...,"assets":[{ "id":"image_0","w":100,"h":100,"u":"images/","p":"img_0.png","e":0 }],...}`

Different `LottieAnimationView` configurations with `scaleType` or `lottie_scale` did not help.

I know, image scaling is working on the iOS implementation. Is this not supported yet on Android?

**Comment by mmakmw** [comment]
@gpeal Thanks for the fix.

- Now, the images do get scaled to the size defined in JSON. 
- However, this produces the same result as if one would use an image of that size initially. 

The desired result would be to have a higher image quality for displays with high dpi. Right now, the resulting image is always of the same low quality no matter of the source image size (quality).

Is there any way to increase the scaled image resolution for better quality?

**Comment by gpeal** [comment]
@mmakmw You can use a BitmapAssetDelegate like [this](http://airbnb.io/lottie/#/android?id=providing-your-own-images)

**Comment by arsen-h** [comment]
Have a same issue 
@mmakmw how did you fixed that? 

@gpeal 
in general, the problem is the same, with increasing image size, the container of this image also increases, but expected larger image in the same container.

On iOS, this is implemented without any additional settings.
Is this feature supported on android?

**Comment by Alrightque** [comment]
Heloc
