### ISSUE TITLE
Possible impact on app startup time?

### ISSUE THREAD

**Issue by geoff-davis-smule** [airbnb/lottie-android#1201]
Hey there,

I’m currently trying to integrate the Lottie SDK into my company's mobile apps. We have a pretty strict process in place for vetting third-party SDKs before we add them. One of these steps involves testing our app’s startup time both before and after integrating an SDK. (In our case, “startup” refers to a point where the OS has launched the app, plus we’ve done a fair amount of startup tasks within the app. We have a point where we consider everything up and running, and we measure that point.)

We're run some crude preliminary test on Android, and observed increases of anywhere from 60-300ms in our app’s launch time with Lottie added. I would guess Lottie's impact on startup time would be extremely low to non-existent. I’m going to do further testing, since the problem might be on our end. However, I also wanted to reach out to you guys and confirm that, for both iOS and Android, Lottie isn’t doing any kind of self-instantiation or running some kind of engine, or doing anything else that could be impacting an app’s startup time. I couldn’t find any evidence of such a thing in your source code, but wanted to be sure.

Thanks,
Geoff

**Comment by gpeal** [comment]
@geoff-davis-smule Lottie doesn't run any code that you don't explicitly call. Are you trying to run an animation on app startup?

**Comment by geoff-davis-smule** [comment]
Thanks for confirming. We are still investigating on our end. The issue might well be with our startup time testing procedures.

I swung by to close this ticket, but it looks like you beat me to the punch by an hour.
