### ISSUE TITLE
How to extend the blur effect that makes lottie support ae

### ISSUE THREAD

**Issue by chongbo2013** [airbnb/lottie-android#1205]
How to extend the blur effect that makes lottie support ae？
thank you.

**Comment by Riaxter** [comment]
Hi, @gpeal . When I upload lottie json file to [Lottie files](https://lottiefiles.com), the blur effect is working well. But when I adjust it to android, the blur effect is gone, and just showing matt image. So what you saying is, blur effect is working in web, but not in android, is it right?
Could you let me know when do you plan to support blur effect on android?
FYI, I tested lottie version "3.3.1".

**Comment by gpeal** [comment]
@Riaxter Blue is [not yet supported](http://airbnb.io/lottie/#/supported-features).
