### ISSUE TITLE
Mulltiple LottieAnimationView with different image folder can't work at same time

### ISSUE THREAD

**Issue by cooliceman** [airbnb/lottie-android#1206]
Scene:I have 4 LottieAnimationView in the same view. and they show four different lottie zip files. each zip contains it's own images folder and images.

If I let the views play again every 5 seconds(all of my lottie animations are less than 5 seconds), app will crash because of exception "You must set an images folder before loading an image. Set it with LottieComposition#setImagesFolder or LottieDrawable#setImagesFolder".

If I uncompress all the zips and put all the lottie images in the same folder, and set  same image folder for all LottieAnimationView, the app work fine and never crash.

Is this a bug?

**Comment by cooliceman** [comment]
> @cooliceman Can you attach a sample project that reproduces this?
@gpeal You can use this demo project 
https://github.com/cooliceman/LottieIssue.git

**Comment by gpeal** [comment]
I was able to reproduce this in your project. However, after migrating to androidx and upgrading to 3.0.1, it went away.

**Comment by 1wayticket** [comment]
> I was able to reproduce this in your project. However, after migrating to androidx and upgrading to 3.0.1, it went away.

Can you share your tips about reproduce this problem. Thank  a lot.
