### ISSUE TITLE
TextDelegate is not rendering properly on below android pie devices

### ISSUE THREAD

**Issue by kartik1225** [airbnb/lottie-android#1208]
I am having a strange issue when I delegate the text in this JSON file it changes the text just fine in android pie devices.

_In android pie devices_
![in pie](https://user-images.githubusercontent.com/21341192/57400174-893bd400-71f0-11e9-8ab2-3b34bb88e325.jpg)

But when I tested the same thing in lower than android pie devices text does not render at all!

_In oreo and below devices_
![in below pie](https://i.imgur.com/PSLZfNh.jpg)

I am using this code to change the text of the animation.

```
// I have already settled animation from a raw file

textDelegate = new TextDelegate(animationView);
textDelegate.setText("THANK YOU", "EDITED TEXT"); 
animationView.setTextDelegate(textDelegate);
```
here is my [AEP.zip](https://filebin.net/dj2n3islxybmr6ch)

**Things that I have already tried**
* Tested this issue with Oreo, Lollipop, and nougat.
* Enabled `enableMergePathsForKitKatAndAbove`.

**Please note This only happens with text that is masked under layer (As per I've noticed). Because it is working fine with my other animations**

Thanks in advance 😃

**Comment by kartik1225** [comment]
The rendering is perfectly fine with software rendering.
It can be enabled like this `animationView.setRenderMode(RenderMode.SOFTWARE);` and all masked Text or Layer will render perfectly.

**Comment by kartik1225** [comment]
This issue is still there in android pie devices even after enabling `animationView.setRenderMode(RenderMode.SOFTWARE)`

**Comment by shirley737** [comment]
Hello @kartik1225, I am also trying to use text delegate, but haven't been able to figure it out yet. I use 
`textDelegate.setText(input,output)`
`animation.setTextDelegate(textDelegate)`
but what is input and what is output? Also, where should I set the keypath to the target text layer? An example would be super appreciated!!!
Thanks!
