### ISSUE TITLE
Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.

### ISSUE THREAD

**Issue by SubhanAli94** [airbnb/lottie-android#1209]
While building lottie-android I am facing following error:

ERROR: The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
root project 'lottie-android' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.0

**Comment by gpeal** [comment]
@SubhanAli94 I think you had local changes and must have changed the Android Gradle Plugin version locally. Master builds fine.
