### ISSUE TITLE
Animation is still played when attached even pause() is called.

### ISSUE THREAD

**Issue by boduan402** [airbnb/lottie-android#1216]
When a LottieAnimationView is [attached](https://github.com/airbnb/lottie-android/blob/3004a3b9b6f6b9039ba2af68c640129f7b0bca2a/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L260) to window, it always play the animation even pause() is called before.

Below is how to reproduce the bug:
- set a LottieAnimationView to autoplay=true in layout.xml
- In activity's onCreate() callback, get the LottieAnimationView and pause() it.
- Then LottieAnimationView is [attachedToWindow](https://github.com/airbnb/lottie-android/blob/3004a3b9b6f6b9039ba2af68c640129f7b0bca2a/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L260) and play the animation by ignoring the pause() call happens earlier. 

The root cause could be [wasAnimatingWhenDetached](https://github.com/airbnb/lottie-android/blob/3004a3b9b6f6b9039ba2af68c640129f7b0bca2a/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L80) is not set to false at [pauseAnimation()](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L765).

**Comment by gpeal** [comment]
This issue regressed in 3.0.5
