### ISSUE TITLE
 The last part of the white screen, no animated pictures 

### ISSUE THREAD

**Issue by wanghaofei** [airbnb/lottie-android#1218]
I use version 2.7.0, designed for JSON resource files, IOS can play normally, Android can not, play to the last part, white screen, what is the reason, the latest version 3.0.1, can you make a low version that does not support androdx? Thank you

**Comment by lovechenghao** [comment]
why Cannot repeat？

**Comment by gpeal** [comment]
@wanghaofei I recommend upgrading your app to androidx for many reasons, not just for Lottie.
https://developer.android.com/jetpack/androidx/migrate

**Comment by gpeal** [comment]
Feel free to reopen with the animation attached if it is an issue with 3.0.2.
