### ISSUE TITLE
lottie cant play animation

### ISSUE THREAD

**Issue by xiexuesong** [airbnb/lottie-android#1228]
lottieAnimationView.setImageAssetsFolder("images2/");
            LottieComposition.Factory.fromAssetFileName(this, "images2/config.json", new OnCompositionLoadedListener() {
                @Override
                public void onCompositionLoaded(final LottieComposition composition) {
                    lottieAnimationView.setComposition(composition);
                    lottieAnimationView.playAnimation();
                }
            });
but it cant play animation ,i dont know why?

**Comment by gpeal** [comment]
Feel free to reopen with a sample project but this isnt't enough to debug with.
You can also try `setComposition("images2/config.json")` instead of using a composition factory.
