### ISSUE TITLE
Lot of unnecessary try/catch blocks in parsing code

### ISSUE THREAD

**Issue by 0legg** [airbnb/lottie-android#123]
Issue: So, exceptions are expensive — https://shipilev.net/blog/2014/exceptional-performance/ . In parsing code there are lot of `try/catch` blocks handling `JSONException` with empty `catch` blocks. In fact, these blocks are for reading optional fields. We can use `opt*` methods of `JSONObject` instead of `get*`, behavior under the hood is the same, but `get*` tries to raise an exception, while `opt*` falls back to null/default value/provided value.

Impact: slower parsing (ok, it won't be as fast as it could be in plugged Jackson/Gson/you name it), bigger memory consumption during parsing, larger codebase.

Proposed solution: replace `get*` with `opt*` where possible — ideally everywhere.

**Comment by 0legg** [comment]
If you have no enough time to put your hands on it, I can make a pool request soon =) Probably, with introducing pluggable architecture this issue will become obsolete.

**Comment by gpeal** [comment]
@0legg great improvement with opt*.

I actually spent a very long time moving everything over to JsonReader which removed this entirely and was way faster and more performant. However, far into the refactor, there were issues with the location of data and structure of the bodymovin json that made it extraordinarily difficult. You can see my attempts here: https://github.com/airbnb/lottie-android/commit/d7227b3a1531195b9e31b2f2bc7e9f16d586ddac

Happy to accept a PR for it. Just let me know if you are so I don't try and do something myself.

**Comment by gpeal** [comment]
@0legg Actually, I just went ahead an switched things over to opt. I'll put up a PR when I finish.

**Comment by 0legg** [comment]
Great job!
