### ISSUE TITLE
setFontAssetDelegate not working after animation is loaded

### ISSUE THREAD

**Issue by kartik1225** [airbnb/lottie-android#1233]
I am using `v3.0.3` and I was trying to change the typeface via setFontAssetDelegate.

```
public void changeFont(final String fontName){
        animationView.setFontAssetDelegate(new FontAssetDelegate(){
            @Override
            public Typeface fetchFont(String fontFamily) {
                return Typeface.createFromAsset(context.getAssets(),"fonts/" + fontName);
            }
        });
}
```
From above method I am trying to change the typeface and it is working fine for the first time *(When the compostion is not loaded)*. 

But when I try to change the typeface again *(after the composition is loaded)* fonts are not changing from the animation.

**Things that I have already tried:**
* `animationView.invalidate();`
* `animationView.cancelAnimation();`
* basicaly I did tried to refresh the `LottieAnimationView` but nothing seems to working.

**Comment by gpeal** [comment]
@kartik1225 Lottie will cache (memoize) the call to fetch the font. If it didn't and somebody had `Typeface.createFromAsset` in their FontAssetDelegate, it would cause performance to be terrible since it would recreate the typeface on every frame. I recommend having your original animation use multiple font families so the delegate gets re-queried.

**Comment by kartik1225** [comment]
Thanks, @gpeal. 
Is there any way to clear all cache from the `LottieAnimatoinView`?  or Force re-render the whole animation with the delegated font.

I tried to clear cache from `LottieCompositionCache.getInstance().clear();` this method but this class is private.

p.s. *I am trying to create an app where a user can export mp4 animations. And I want to add the feature where the user can select the font style from a list of fonts. So performance is not an issue in this case.*

**Comment by kartik1225** [comment]
Is there any solutions available I want to change the font in run time (during the animation) is that possible?

**Comment by frontlink-technology** [comment]
I am facing same issue while using setFontAssetDelegate runtime. If animation is playing, then typeface not updating at that time. Please suggest solution for this...

**Comment by gpeal** [comment]
Would you like to propose an API that would work better for you?

**Comment by Luosoha** [comment]
Any solutions to this issue yet?

**Comment by gpeal** [comment]
I would recommend using the dynamic properties API with `LottieProperty.TYPEFACE` for this use case, it should work just fine.
http://airbnb.io/lottie/#/android?id=dynamic-properties
