### ISSUE TITLE
Android 9 playAnimation() doesn't trigger animation

### ISSUE THREAD

**Issue by keehoo** [airbnb/lottie-android#1236]
Hi,

I'm having issue with 'com.airbnb.android:lottie:3.0.2'.

I explicitly call `playAnimation()` and it seems like it randomly do not play the animation. 
I've had an animation start at button click (same) then without, simply called `playAnimation()`  in `onResume` - result is the same. 

I load the animation from the assets in XML.

In the same `Activity` I also use MotionLayout (beta) which play animations in the same time as Lottie animation. Is there info on those two disagreements? MotionLayout animation plays fine (ish)

`  <com.airbnb.lottie.LottieAnimationView
        android:id="@+id/animation_view"
        android:layout_width="408dp"
        android:layout_height="547dp"
        android:layout_marginTop="8dp"
        android:elevation="1dp"
        android:scaleType="centerInside"
        android:visibility="visible"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="@+id/imageView"
        app:layout_constraintVertical_bias="1.0"
        app:lottie_autoPlay="false"
        app:lottie_loop="false"
        app:lottie_rawRes="@raw/animation"
        app:srcCompat="@drawable/heart3x"
        tools:visibility="visible" />`

`    override fun onResume() {
        super.onResume()
            animation_view.playAnimation()
            motion_container.transitionToEnd()
      }`

**Comment by gpeal** [comment]
@keehoo Can you create a sample project that reproduces this?

**Comment by keehoo** [comment]
Sure, just need to remove proprietary assets, not sure if I'll find a suitable Lottie animation to replace the current one...

**Comment by keehoo** [comment]
@gpeal Please check this repo : https://github.com/keehoo/LottieTests

I get this randomly. When I click play the animation don't start. If you get it right try to kill the app and restart it. I didn't get this behavior on ConstraintLayout.. Tried on emulator and on device.

**Comment by denis-bezrukov** [comment]
@keehoo Can you try to reproduce the issue on the latest version? (3.0.3)

**Comment by keehoo** [comment]
@denis-bezrukov Updated to (3.0.3) - looks like the issue is gone :) Gimme 15 minutes, will be checking some more.
