### ISSUE TITLE
Animations are blurry in 3.0+

### ISSUE THREAD

**Issue by tzmst** [airbnb/lottie-android#1237]
So i wanted to update the lottie from current 2.7.0 i have to 3.0.3, but the animations are blurry, like the anti aliasing is turned off, or some issues with scaling. Did something got changed and i need to activate some settings ? Tried different 3.0+ versions

3.0+
![Screen Shot 2019-05-28 at 4 47 14 PM](https://user-images.githubusercontent.com/3909335/58483253-a23d0280-8168-11e9-9c2a-34b9a7df37e3.png)

2.7.0
![Screen Shot 2019-05-28 at 4 49 37 PM](https://user-images.githubusercontent.com/3909335/58483269-a8cb7a00-8168-11e9-8c89-d9f21803154d.png)

**Comment by gpeal** [comment]
@tzmst Which version of Android? Try turning hardware acceleration off (with setRenderMode)

**Comment by tzmst** [comment]
@gpeal Awesome!! That hit the spot and fixed it thanks a bunch

**Comment by gpeal** [comment]
@tzmst You can also set a fixed size on the view and use `setScale` to scale up the animation to fill it. As is, on older versions of Android, you couldn't scale a hardware accelerated canvas without pixelation. However, if you use setScale, it'll scale the shapes instead of the canvas.
