### ISSUE TITLE
text alignment issue

### ISSUE THREAD

**Issue by zishanj** [airbnb/lottie-android#1238]
I am still facing alignment issue with lottie 3.0.1

```
<com.airbnb.lottie.LottieAnimationView
            android:id="@+id/completed_animation_view"
            app:lottie_fileName="topic_completed.json"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_gravity="center"
            android:scaleType="centerInside"
            android:visibility="@{viewModel.isCompleted ? View.VISIBLE : View.GONE}"
            tools:visibility="visible"/>
```
result:

![image](https://user-images.githubusercontent.com/1451292/58483035-fd76f100-8178-11e9-99d6-8f78e78e677a.png)

I have tried with `centerCrop` also but there is no effect on alignment. The complete text is _you have taken one step ahead_, but it get cropped due to misalignment. On web it appears perfectly, even if I resize the browser, the width get auto adjusted and there is not misalignment of text.

_Originally posted by @zishanj in https://github.com/airbnb/lottie-android/issues/388#issuecomment-496515255_

**Comment by gpeal** [comment]
@zishanj Can you attach your animation?

**Comment by zishanj** [comment]
I have it on [LottieFiles](https://lottiefiles.com/share/dQobDq)

**Comment by zishanj** [comment]
Any update on this issue?

**Comment by gpeal** [comment]
@zishanj probably not for a few weeks. If you'd like to debug it, I would be happy to accept a pull request.

**Comment by chanjungkim** [comment]
Have you solved this issue?

**Comment by gpeal** [comment]
Lottie doesn't support the bounce properties you are using.

**Comment by zishanj** [comment]
@gpeal Its very well supported on web version of Lottie. There should be a possibility to support it on mobile devices.

**Comment by gpeal** [comment]
@zishanj The web player runs on javascript and can execute After Effects expressions. The mobile versions would need a built in interpreter to do the same thing. It's not technically impossible but not currently on the roadmap.
