### ISSUE TITLE
Android Studio Color shift

### ISSUE THREAD

**Issue by Gusfavoreto** [airbnb/lottie-android#1239]
MacOs
Safari Version 12.1.1
After Effects 16.1.1

I am doing some simple animations to load on Android. But when I load the JSON file on Android Studio the color are changed, Blue turns red, green turns yellow, red stay red. But is I load on LottieFile website works, and I try to change color there, some elements doesn't change its colors. Originally the design is with gradient, but its not loading, says that wasn't able to find keyframes. 
[Lottie_color.aep.zip](https://github.com/airbnb/lottie-android/files/3230105/Lottie_color.aep.zip)
![Screen Shot 2019-05-28 at 3 42 21 PM](https://user-images.githubusercontent.com/35354935/58518876-cea34f80-8165-11e9-8bcd-f0ca0c8c38eb.png)

I exported as old version.

I am not a developer, I am just a motion guy trying so send some files correct ;)
Thank you,
Gus

**Comment by gpeal** [comment]
@Gusfavoreto My guess is that it has something to do with that emulator. It looks fine on my Pixel 3 for what it's worth. Can you try it on a physical device?

**Comment by Gusfavoreto** [comment]
Hey @gpeal,I will try!

Thank you,
Gus

**Comment by Gusfavoreto** [comment]
I couldn't find a device to try. There is any solution to fix the emulator or the son file? 

Thanks,
Gus

**Comment by Gusfavoreto** [comment]
Hey @gpeal how did you load in your physical device? I connected via USB and load from Android Studio and I am having the same issue. Did you sent the son file to device?
Sorry the dummy question, but I have no idea.

Thanks,
Gus

**Comment by gpeal** [comment]
@Gusfavoreto Yes, I loaded it onto a physical device and it looked exactly like lottiefiles

**Comment by Gusfavoreto** [comment]
@gpeal How did you load? I have the file on the physical device but I just find app to read the son, not to load the animation. And when I send from Android Studio to preview in the device, the colors is still wrong.
How did you load the file? use an app or something?

Thanks,
Gus

**Comment by gpeal** [comment]
@Gusfavoreto Try downloading the Lottie app from the Play store and scan the qr code when you're previewing it on lottiefiles

**Comment by gpeal** [comment]
@Gusfavoreto I'm going to close this for now. Feel free to reopen it with more information if there is something actionable.
