### ISSUE TITLE
Reload LottieComposition will flash (3.0.3)

### ISSUE THREAD

**Issue by thirtyyuan** [airbnb/lottie-android#1240]
#### Device Info: OnePlus 5T, Android 9.0

I try to upgrade from 2.7.0 to 3.0.3, but I got a "flash" when I reload LottieComposition to a LottieAnimationView, which doesn't appear in 2.7.0.

Here are my [sample code](https://github.com/thirtyyuan/LottieTest). It will be load and show LottieCompostition in `onStart()` at first time, and reload and show again when you click the `Start` button. Now, you will find the same problem as me.

BTW, at some times, the Lottie on `match_degree_title` won't show, but `animationListener` will call `onAnimationEnd()` directly. 

If you know how to solve the two problems, please tell me, Thx!

**Comment by gpeal** [comment]
@thirtyyuan For now, set `view.frame = 0` before each `setComposition` and that'll fix it but I'll look in to this

**Comment by thirtyyuan** [comment]
Thx, it's  don't flash again, and I'm trying to repeat the problem which `match_degree_title` won't show again, I will close this issue until I find some new problems.
