### ISSUE TITLE
Abnormal stop of lottie animation

### ISSUE THREAD

**Issue by zxc120301945** [airbnb/lottie-android#1241]
Switch the fragment in the activity, then switch the fragment through the viewpager in the fragment. At this time, execute the lottie animation in one of the fragments, then switch the fragment through the activity, then jump to another activity, and then return to the previous activity. Then switch to the fragment that is executing the lottie animation, at this point the lottie animation stops.
View problems by code source
![image](https://user-images.githubusercontent.com/14074954/58607545-a127e480-82d2-11e9-8f9e-8445305181b0.png)
This method will be called when the fragment is switched, and then called again when the activity jumps. On the second call, the value of wasAnimatingWhenVisibilityChanged will be assigned false again by isAnimating(). This time, it will return to the currently executing lottie animation. In the fragment, the resumeAnimation() method in the onVisibilityChanged callback will not be executed.

**Comment by gpeal** [comment]
I think this PR will fix it. Please try 3.0.4

**Comment by zxc120301945** [comment]
OK

**Comment by gpeal** [comment]
@zxc120301945 3.0.5 now
