### ISSUE TITLE
When I turn off the screen and light up again. It doesn't work in list.

### ISSUE THREAD

**Issue by iostyle** [airbnb/lottie-android#1247]
When I turn off the screen and light up again. It doesn't work in list.
Latest Lottie Version.
On any of my phones.
![recored](https://user-images.githubusercontent.com/22219146/58699946-648ee280-83d1-11e9-8df6-3f5c1948b25f.gif)

**Comment by gpeal** [comment]
@iostyle Please try 3.0.5. There were a few fixes

**Comment by gpeal** [comment]
If this still happens in 3.0.5, feel free to reopen but please include a sample project that repros it.

**Comment by iostyle** [comment]
@gpeal still happens in 3.0.5

**Comment by gpeal** [comment]
@iostyle I just published 3.0.6 which fixed another visibility bug. Could you try that?

**Comment by iostyle** [comment]
I'm sorry to tell you that the issus is still there

**Comment by iostyle** [comment]
@gpeal  Which version did you support lifecycle

**Comment by gpeal** [comment]
@iostyle Can you attach a sample app that reproduces this? It seems to work fine from my tests.

**Comment by iostyle** [comment]
I haven't found out what the problem is, it may be my problem.If I find the problem in the future, I will give feedback.
