### ISSUE TITLE
setProgress does not interpolate between frames

### ISSUE THREAD

**Issue by jannisveerkamp** [airbnb/lottie-android#1250]
Lottie on Android doesn't interpolate between two Frames when using the `setProgress(..)` method. It just "rounds" to the next full frame (e.g. different progress values lead to the same frame shown). [setProgress](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java#L680) does this rounding:
```
setFrame((int) MiscUtils.lerp(composition.getStartFrame(), composition.getEndFrame(), progress));
```

The iOS however seem to interpolate between Frames. And of course Lottie does this internally when the animation is played normally. Hence I think it should be possible for `setProgress` too 😃 

My usecase is to align the animation progress to a scroll state. See [this Stackoverflow article](https://stackoverflow.com/questions/55063434/align-android-lottie-animation-to-scrolling/55124308) for a visual representation of the problem.

A simpler way to reproduce the issue is to create a `ValueAnimator` and manually update the animation progress. The issue is not dependent on any specific animation.

```
val valueAnimator = ValueAnimator.ofFloat(0f, 1f)
valueAnimator.duration = 30000
valueAnimator.addUpdateListener { animation ->
    lottieAnimationView.progress = animation.animatedFraction
}
valueAnimator.start()
```

Any chance this could be supported by Lottie?

**Comment by methelas** [comment]
I'm having the exact same issue. It would be great if setProgress could interpolate between frames on Android too.
Unfortunately the solution from SO doesn't work for me so I'm stuck with a bit rough animation :/

**Comment by gpeal** [comment]
Seems reasonable. I'd accept a PR or I'll try and get around to this soon.

**Comment by jannisveerkamp** [comment]
Awesome - that was fast 👍
