### ISSUE TITLE
please support PorterDuff ADD  MULTIPLY and so on

### ISSUE THREAD

**Issue by chongbo2013** [airbnb/lottie-android#1251]
[lottie.zip](https://github.com/airbnb/lottie-android/files/3256531/lottie.zip)
I use the AE above to use the image for ADD operation, invalid effect

I know that android supports PorterDuff ADD request to implement the ADD mode of its picture.

**Comment by gpeal** [comment]
@chongbo2013 Can you attach the AEP file?

**Comment by gpeal** [comment]
I'm not sure I understand exactly what you are asking for. What is the after effects features you need?

**Comment by chongbo2013** [comment]
> @ chongbo2013你可以附加AEP文件？

你好，aep文件在最上面  lottie.zip

**Comment by gpeal** [comment]
@chongbo2013 Your aep didn't attach.

**Comment by chongbo2013** [comment]
> @chongbo2013 Your aep didn't attach.
Excuse me, I thought I passed, I am making up now.
[Uploading 简化的端午 folder.zip…]()

**Comment by chongbo2013** [comment]
[简化的端午 folder.zip](https://github.com/airbnb/lottie-android/files/3324685/folder.zip)

**Comment by gpeal** [comment]
Duplicate of #1055
