### ISSUE TITLE
a json file cannot animate right in android 4.4

### ISSUE THREAD

**Issue by nangonghuang** [airbnb/lottie-android#1254]
this file : [json file ](https://assets10.lottiefiles.com/packages/lf20_XSoY95.json)   cannot annimation right on one android 4.4 device of mine ,

i have tried the lottie app to scan QRcode or load from url,it works fine on my android 8.0 device,and still can't work on 4.4 。 

and where can i find the android version support messages of lottie,or the api document file ?
on [lottie website](http://airbnb.io/lottie/#/)   i can only find how to import and basic use。

**Comment by gpeal** [comment]
@nangonghuang Try `setRenderMode(RenderMode.SOFTWARE)`

**Comment by nangonghuang** [comment]
> @nangonghuang Try `setRenderMode(RenderMode.SOFTWARE)`

`setRenderMode`  makes no different .
on my android 4.4 device,it looks like this,and don't show animation, lottie sample app can't load from it's QR code()
<img width="116" alt="android 4 4" src="https://user-images.githubusercontent.com/13362002/59429254-f5be7a00-8e11-11e9-8821-d04567c52d48.png">

on Nexus6p 8.1, it looks like this, with some stokes,but don't kown what's the problem. lottie sample app displayed it all right,

<img width="117" alt="nexus6p" src="https://user-images.githubusercontent.com/13362002/59429255-f6efa700-8e11-11e9-83d3-1895839b7200.png">

```html
 <com.airbnb.lottie.LottieAnimationView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="@android:color/transparent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:lottie_autoPlay="true"
        app:lottie_fileName="refresh.json"
        app:lottie_loop="true"
        app:lottie_renderMode="software" />
```

**Comment by gpeal** [comment]
@nangonghuang It turns out that the renderMode attr was ignored and that's what caused your spinner to not render on old devices. However, there is a bug on KitKat where the mask renders artifacts on a software rendered canvas so I'm looking in to that.
