### ISSUE TITLE
指定LottieAnimationView的宽高不能自动适配json的尺寸

### ISSUE THREAD

**Issue by chenyan-github** [airbnb/lottie-android#1257]
1. 我的json文件中的w,h的宽高为68, 68.
2. LottieAnimationView layout_width和layout_height都指定为50dp时，动画显示正常；但当我都设置为30dp时，则动画显示不正常，动画中的位移就会超过控件的边界。
3. 按文档中所说的，json文件中宽高单位相当于是dp，为什么我缩小控件的宽高时，json中的位移比例没有自动做缩放适配？

**Comment by gpeal** [comment]
You can use `android:scaleType="centerInside"`

**Comment by chenyan-github** [comment]
> You can use `android:scaleType="centerInside"`
我试过设置为centerinside依然不行

**Comment by 1187180735** [comment]
> > 您可以使用`android:scaleType="centerInside"`
> > 我试过设置为centerinside依然不行

您好，问下 这个问题解决了吗
