### ISSUE TITLE
This simple mask made with ae, but on android, it shows an error

### ISSUE THREAD

**Issue by chongbo2013** [airbnb/lottie-android#1259]
This simple mask made with ae, but on android, it shows an error, ask for help, thanks
Aep file in the zip file, thanks
[ae项目.zip](https://github.com/airbnb/lottie-android/files/3279344/ae.zip)

**Comment by chongbo2013** [comment]
hello...

**Comment by gpeal** [comment]
@chongbo2013 Please simplify your animation to the simplest possible animation that reproduces your issue and describe exactly what the issue is. I don't have time to reverse engineer your entire animation.
