### ISSUE TITLE
> You can use `android:scaleType="centerInside"`

### ISSUE THREAD

**Issue by chenyan-github** [airbnb/lottie-android#1260]
> You can use `android:scaleType="centerInside"`
我试过设置为centerinside依然不行

_Originally posted by @chenyan-github in https://github.com/airbnb/lottie-android/issues/1257#issuecomment-501197030_

**Comment by gpeal** [comment]
Please attach a sample project that repros this.

**Comment by gpeal** [comment]
@chenyan-github

**Comment by chenyan-github** [comment]
ok, my test demo project already upload to github respository: https://github.com/chenyan-github/LottieDemo,  you can download it and run. now only ImageView sizes(68dp and 100dp) can play right on Android. The same json can play right on IOS platform, so I can't understand.

**Comment by chenyan-github** [comment]
@gpeal This is my demo url: https://github.com/chenyan-github/LottieDemo

**Comment by gpeal** [comment]
@chenyan-github What exactly is the issue that you are having? Is it that the animation doesn't scale up when it is smaller than the view and the scale type is centerInside?

**Comment by chenyan-github** [comment]
> @chenyan-github What exactly is the issue that you are having? Is it that the animation doesn't scale up when it is smaller than the view and the scale type is centerInside?

yes, i use centerinside, you can use my json files play on ios compare with android, our ios lottie library is 2.5.0 and android lottie version is 2.5.5.

**Comment by chenyan-github** [comment]
my issues is this json files can't play correctly on android, you can pick the json files "ic_tab_chat.json" and "ic_tab_contacts.json" in my demo project assets directory.

**Comment by gpeal** [comment]
Please repro on 3.0. A lot has changed since 2.5.5. There is a new issue-repro module that you can use to reproduce this issue in a fork.
