### ISSUE TITLE
Why is the setting mode to loop and still allocate memory?

### ISSUE THREAD

**Issue by qiongtony** [airbnb/lottie-android#1267]
My app needs animation looping, but it's very inefficient, because memory is always allocated during loop playback, resulting in frequent memory recycling.
There is no difference in setting the effect of different strategies.
![Result of the application running in the android studio profile detection.](https://user-images.githubusercontent.com/14202091/59490637-ccf0c000-8eb7-11e9-8c59-2dc0fad9c957.png)

**Comment by qiongtony** [comment]
This is the zip file for my lottie file.
[lottie_file_name.zip](https://github.com/airbnb/lottie-android/files/3289480/lottie_file_name.zip)

**Comment by gpeal** [comment]
@qiongtony What version of Lottie and can you attach your lottie animation, not a gif?

**Comment by gpeal** [comment]
Closing for now. Feel free to reopen with more information.
