### ISSUE TITLE
How to use with JsonReader?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [airbnb/lottie-android#1270]
On v3.0.3 , I could use this:

            val reader = android.util.JsonReader(BufferedReader(InputStreamReader(FileInputStream(File(filePath)))))
            animationView.setAnimation(reader, null)

But when I've recently updated to 3.0.6 , it says I need to use `com.airbnb.lottie.parser.moshi.JsonReader` instead.

It doesn't seem like the normal JsonReader , and I can't pass it what I've passed to it.

How can I use the new JsonReader of Lottie? What should I do?

**Comment by gpeal** [comment]
@AndroidDeveloperLB Hmm, this was an unintended consequence of us switching out the underlying JsonReader for performance and to fix some OEM specific crashes. I'll expose the InputStream version then you can do `setAnimation(FileInputStream(...))`

**Comment by AndroidDeveloperLB** [comment]
What is the best way to handle the InputStream ? Is this currently possible ?
Does it close it automatically, or do I have to close it myself?

**Comment by gpeal** [comment]
You can use `LottieCompisitionFactory.fromInputStream(InputStream, cacheKey)` and yes, it will close it.

**Comment by AndroidDeveloperLB** [comment]
You probably mean `LottieCompositionFactory.fromJsonInputStream(FileInputStream(File(filePath)), null)`

But what do I do with it exactly? It looks like a background task. 

I want to set the animation of the `LottieAnimationView` to use it.
There is no `animationView.setAnimation(...)` to use what's coming from this function...

![image](https://user-images.githubusercontent.com/5357526/59660295-d7110800-91b0-11e9-8316-14f29467fccb.png)

**Comment by gpeal** [comment]
@AndroidDeveloperLB You can add a listener on the task then call `animationView.setComposition` I'll expose better APIs through LottieAnimationView in a future version to simplify/wrap this but for now, that will work just fine.

**Comment by AndroidDeveloperLB** [comment]
I want to set the animation and let the View handle it, just like any other source of animation.
If there is a new animation to set for it, the previous one will be cancelled. 
At least, that's how it worked so far, no?
Meaning that if I had called `animationView.setAnimation(whatever...)` and soon after I called `        animationView.setAnimation(whatever2...)` , it will ditch what it had tried to load before.

If I use a listener, I will need to somehow manage this situation, because I can't just tell it to set the animation when it's done, as there might be a different animation being set between the time I started to the time I got a callback from the listener.
This requires extending the animation view of Lottie.

Can you please show how to use what you wrote?

**Comment by gpeal** [comment]
@AndroidDeveloperLB As I mentioned, I am going to add an `InputStream` version directly on LottieAnimationView

**Comment by gpeal** [comment]
In the mean time, you could also convert it to a String and pass the json string in. Not ideal but I'll fix this soon.

**Comment by AndroidDeveloperLB** [comment]
Can you please let me know after it gets fixed?

**Comment by AndroidDeveloperLB** [comment]
So which version to use, that allows to use InputStream?

**Comment by gpeal** [comment]
The next release, it'll likely by 3.1.0. I hope to release it this week.

**Comment by AndroidDeveloperLB** [comment]
What's the best way then, to set animation from File (or file path) ?

**Comment by AndroidDeveloperLB** [comment]
Is it this:
```
animationView.setAnimationFromUrl(filePath)
```
?

**Comment by gpeal** [comment]
Right now, read the file as a string then pass it to `setAnimationFromJson`. I'll make a new release this week though.

**Comment by AndroidDeveloperLB** [comment]
Does setAnimationFromUrl work fine with filePath as I wrote?

**Comment by gpeal** [comment]
@AndroidDeveloperLB No because a file is not a network url.

**Comment by AndroidDeveloperLB** [comment]
@gpeal I see. In the docs they say as if it's a normal file, so I thought it can be used too.

**Comment by AndroidDeveloperLB** [comment]
@gpeal So for now it's possible to do as such:

```
            val jsonStr = IOUtils.toString(BufferedReader(InputStreamReader(FileInputStream(File(filePath)))))
            animationView.setAnimationFromJson(jsonStr, null)
```
?
Sadly this is on the UI thread, but should work fine for now on tiny files...

**Comment by gpeal** [comment]
@AndroidDeveloperLB or `LottieCompositionFactory.fromInputStream(...)`

**Comment by AndroidDeveloperLB** [comment]
@gpeal There is no such thing:

![image](https://user-images.githubusercontent.com/5357526/60609415-49e1cc00-9dca-11e9-9ff4-24cb76ae548b.png)

And if you mean `fromJsonInputStream` instead, I don't see how to set it to the animationView :

![image](https://user-images.githubusercontent.com/5357526/60609512-86152c80-9dca-11e9-8fbc-a757a43c1e29.png)

**Comment by gpeal** [comment]
@AndroidDeveloperLB Yes, `fromJsonInputStream`. Add a success listener to that and call `setComposition` on your `LottieAnimationView` with the result.

**Comment by AndroidDeveloperLB** [comment]
I see. Sadly due to this issue:
https://github.com/airbnb/lottie-android/issues/1298
I went back to v3.0.3 .
v3.0.7 caused a lot of issues for users due to this crash (or at least so it seems for now).
