### ISSUE TITLE
how to set Dynamic Text in Json ? 

### ISSUE THREAD

**Issue by axitasavani** [airbnb/lottie-android#1271]
i have a new user to used the Lottie library in Android. 
So Can you please Tell me Hoe to used Text Delegate and Add Custom Text, Fonts, Color Etc?

**Comment by axitasavani** [comment]
Using TextDelegate my issue is resolved.

**Comment by shirley737** [comment]
Hello @axitasavani , can you show me an example of how to use TextDelegate? I haven't been able to find the documentation yet. 

Thank you so much!
