### ISSUE TITLE
Is that any way to change Text Color in Json ?

### ISSUE THREAD

**Issue by axitasavani** [airbnb/lottie-android#1272]
lottieAnimationView.addValueCallback(
                        new KeyPath("**"),
                        LottieProperty.COLOR_FILTER,
                        new SimpleLottieValueCallback<ColorFilter>() {
                            @Override
                            public ColorFilter getValue(LottieFrameInfo<ColorFilter> frameInfo) {
                                return new PorterDuffColorFilter(Color.CYAN, PorterDuff.Mode.SRC_ATOP);
                            }
                        }
                );

-> this Code is not working for me.
So please Help me.

**Comment by gpeal** [comment]
Use COLOR not COLOR_FILTER
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/model/layer/TextLayer.java#L414

**Comment by axitasavani** [comment]
ok. i will try this. Thank you So Much.

**Comment by axitasavani** [comment]
Can i change Font, a stroke of text?

**Comment by gpeal** [comment]
@axitasavani 
Yes, you can use `LottieProperty.STROKE_COLOR` and `STROKE_WIDTH` You can also use `FontAssetDelegate` to replace the fonts with your own
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/FontAssetDelegate.java

**Comment by kartik1225** [comment]
*LottieProperty.STROKE_COLOR* is not changing the text color. I have also tried all of this #1342

**Comment by jiajingchao** [comment]
I tried to change the text color, but it didn't take effect:
lottieView.addValueCallback(KeyPath("**"), LottieProperty.COLOR) { Color.Red.toArgb() }
