### ISSUE TITLE
 NetworkCache isTemp usage error

### ISSUE THREAD

**Issue by JoinGitLiu** [airbnb/lottie-android#1277]
When I downloaded the json file with **NetworkFetcher.fetchSync**(Context context, String url) I found that the file could be written to the cache, but the cache file could not be read. The reason is that **NetworkCache's 131 line isTemp** is reversed and should be 
` ( ! isTemp ? extension.tempExtension(): extension.extension)`

**Comment by gpeal** [comment]
Duplicate of #1114. I also recommend upgrading Lottie.
