### ISSUE TITLE
Crash on android-19

### ISSUE THREAD

**Issue by kooguma** [airbnb/lottie-android#1282]
**The lottie crash on android-19**
_the related issues #759_ 
there is more information I found about the bug ( I hope you can add the method setAnimation(JSONObject json) back plz...)

- **steps to reproduce the bug**

1. use the [DynamicGradient](https://github.com/airbnb/lottie-android/blob/master/LottieSample/src/main/assets/DynamicGradient.json) provided by the LottieSamples
 try the code as follow

```java          
            InputStream is = getResources().getAssets().open("DynamicGradient.json");
            byte[] buf = new byte[is.available()];
            is.read(buf);
            String json1 = new String(buf);
            jsonObject = new JSONObject(json1);
            String json2 = jsonObject.toString();
            lottie.setAnimation(json1);  //works well
            //lottie.setAnimation(json2); //crash
```
2. when you set the animation source from the json1 everything works well. but if try the json2, the lottie will crash

3. there are the key part of json1 and json2
the left side is the 'correct json' while the right side is the 'wrong json'

![lottie-bug](https://user-images.githubusercontent.com/13082276/59985585-2352c100-9665-11e9-8067-462d5df46033.jpg)

**when I place the ''ty'': "gs" at the first position, everything works well.**

- **why the json string is messed up?**
 when api <= android-19, the JSONObject uses the HashMap to store the key-value pair
 when api > android-20, the JSONObject uses the LinkedHashMap to store the key-value pair

- **what's really matters?**
the [ContentModelParser](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/parser/ContentModelParser.java) skip the key-value pair before the 'ty' key !! As for the json2(the messed up json), it skips all the key-value before the ''ty'': "gs", so the values of 'o' and 'w' are both null!!  it seems like that by default ContentModelParser sticks to the rule that the 'ty' should be placed at the first position. which I think is unreasonable as the json should not rely on the order.
there is code may be wrong
```java
   while (reader.hasNext()) {
      switch (reader.selectName(NAMES)) {
        case 0:
          type = reader.nextString();
          break typeLoop;
        case 1:
          d = reader.nextInt();
          break;
        default:
         // it skips the all the key-value before the 'ty'!!
          reader.skipName();
          reader.skipValue();
      }
    }
```

**Comment by gpeal** [comment]
@kooguma The JSON order does matter for parsing performance reasons. Although it is not typical for json, the order of keys does matter in this specific case for Lottie. 

That is an interesting discovery you made regarding the order of keys for JsonObject on <=19, however. I wasn't aware of that difference.
