### ISSUE TITLE
Readme Documentation is Extremely Sparse

### ISSUE THREAD

**Issue by cren90** [airbnb/lottie-android#1285]
Currently, the documentation is just a set of sample animations and the Gradle dependency information. Compared to the documentation for the other Lottie projects (i.e. [iOS](https://github.com/airbnb/lottie-ios)) it is awful.

**Comment by gpeal** [comment]
@cren90 Did click the link to the documentation site?
http://airbnb.io/lottie/#/android

**Comment by cren90** [comment]
The link in the github repo takes you to http://airbnb.io/lottie. I had been on that page before and had clicked the android link in the "Lottie for..." header, which redirects to this GitHub repo. I was unaware that the links on the left would direct me to a different page than the link with the same name in that header. For consistency with the other Lottie repos, I still recommend having the Readme updated.

**Comment by gpeal** [comment]
Got it, good to know. I'll update this next time I work on the docs. You can open a PR [here](https://github.com/airbnb/lottie) or directly on the README for this reop if you have any docs suggestions.
