### ISSUE TITLE
Animation doesn't work with latest (3.0.7) version

### ISSUE THREAD

**Issue by kbehl82** [airbnb/lottie-android#1286]
When upgrading Android Lottie version from 2.8.0 to 3.0.7 the animation stopped working. The attached has the json and aep files. This is happening on around 60 json files we use. We currently cannot upgrade to the latest version. What do we need to do to fix this?

[lottieIssue.zip](https://github.com/airbnb/lottie-android/files/3322735/lottieIssue.zip)

Also, we are seeing crashes with the attached on Lottie version 2.8.0. It seems sporadic and on different devices and OS versions. Some work and some crash, but they have been created in the same way. This is the reason we want to upgrade to the latest version (3.0.7). If this issue can be fixed then we won't be upgrading. 

Please let me know if you need any more information. Cheers

**Comment by gpeal** [comment]
@kbehl82 Can you be more specific? What do you mean by "stopped working"?
Also, can you provide the stack trace for the crash?

**Comment by gpeal** [comment]
This is what I'm seeing for your animation which looks correct to me.
![Animation](https://user-images.githubusercontent.com/1307745/60119970-a3942780-9734-11e9-9322-567266bb2353.gif)

**Comment by gpeal** [comment]
@kbehl82 Can you attach a sample project that reproduces this?

**Comment by kbehl82** [comment]
Sure. Also, we are using an epoxy carousel to hold the icons if that would make a difference

**Comment by kbehl82** [comment]
We fixed the issue by doing the following:
