### ISSUE TITLE
Add cache strategy feature

### ISSUE THREAD

**Issue by fleficher** [airbnb/lottie-android#1289]
Hello there 👋 

It seems that it's not possible to control how animations are cached by Lottie.

I'm using multiple Lottie animations in my app. All of them are cached in memory and take a lot a memory involving OutOfMemory errors. Currently, we can't control which animation are cache in memory or disable this feature completely.

I've seen a `lottie_cacheStrategy` attribute in LottieAnimationView code but it doesn't seem to exist anymore 😢 . Why has it been removed?

Here's a sample of a memory dump showing the excessive amount of memory used by Lottie:

![58666818-b46b9c00-8334-11e9-8d96-00070946de70](https://user-images.githubusercontent.com/6464646/60214104-23211400-9865-11e9-84bd-19e2165b5dc5.png)

**Comment by fleficher** [comment]
@gpeal why closing this issue? There's no provided solution at the moment :/

**Comment by sunmTree** [comment]
any way to clear LottitCompositionCache?

**Comment by kartik1225** [comment]
I am also looking for a solution for this.

**Comment by axitasavani** [comment]
Is there find any solution for clear LottitCompositionCache?

**Comment by sunmTree** [comment]
> Is there find any solution for clear LottitCompositionCache?

You can use Java Reflection to invoke "LottieCompositionCache.clear()" , but not sure influence

**Comment by kartik1225** [comment]
@sunmTree  can you please give me a little bit more details on this?
I am less familiar with the Reflection API.

**Comment by sunmTree** [comment]
> @sunmTree can you please give me a little bit more details on this?
> I am less familiar with the Reflection API.

Like this

```
try {
         Class<?> lottieCacheClass = Class.forName("com.airbnb.lottie.model.LottieCompositionCache");
            Method instance = lottieCacheClass.getDeclaredMethod("getInstance");
            Method clearMethod = lottieCacheClass.getMethod("clear", null);
            clearMethod.invoke(instance.invoke(null, null));
        } catch (ClassNotFoundException | NoSuchMethodException
                | IllegalAccessException | InvocationTargetException e) {
            e.printStackTrace();
        }
```

[User Java Reflection](https://www.oracle.com/technical-resources/articles/java/javareflection.html)

**Comment by sunmTree** [comment]
> @sunmTree can you please give me a little bit more details on this?
> I am less familiar with the Reflection API.

Like this:

```
try {
            Class<?> lottieCacheClass = Class.forName("com.airbnb.lottie.model.LottieCompositionCache");
            Method instance = lottieCacheClass.getDeclaredMethod("getInstance");
            Method clearMethod = lottieCacheClass.getMethod("clear", null);
            clearMethod.invoke(instance.invoke(null, null));
        } catch (ClassNotFoundException | NoSuchMethodException
                | IllegalAccessException | InvocationTargetException e) {
            e.printStackTrace();
        }
```

[Using Java Reflection](https://www.oracle.com/technical-resources/articles/java/javareflection.html)

**Comment by kartik1225** [comment]
> > @sunmTree can you please give me a little bit more details on this?
> > I am less familiar with the Reflection API.
> 
> Like this:
> 
> ```
> try {
>             Class<?> lottieCacheClass = Class.forName("com.airbnb.lottie.model.LottieCompositionCache");
>             Method instance = lottieCacheClass.getDeclaredMethod("getInstance");
>             Method clearMethod = lottieCacheClass.getMethod("clear", null);
>             clearMethod.invoke(instance.invoke(null, null));
>         } catch (ClassNotFoundException | NoSuchMethodException
>                 | IllegalAccessException | InvocationTargetException e) {
>             e.printStackTrace();
>         }
> ```
> 
> [Using Java Reflection](https://www.oracle.com/technical-resources/articles/java/javareflection.html)

Thank you so much for the response. But apparently this is not clearing the  `LottieCompositionCache` 
I am trying the change the font in the loaded composition but due to cache it always takes the old fonts once the lottie composition has been loaded.
but still thanks for the response.

**Comment by timbru31** [comment]
Unfortunately, URLs are still being cached and PR #1450 did not fix this. Let me quickly outline the problem. When the `cacheKey` is `null`, the cache function of the `LottieCompositionFactory` recognized and honors this case: https://github.com/airbnb/lottie-android/blob/ee942249214dd6bb1540b746ca0b678a6382b5ee/lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java#L459-L474

Therefore a new network fetch is initiated, as it should be: https://github.com/airbnb/lottie-android/blob/ee942249214dd6bb1540b746ca0b678a6382b5ee/lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java#L80-L88

However, the `NetworkFetcher` looks in it's cache and returns the cached file, i.e., the end user still sees the wrong animation. IMHO the NetworkFetcher needs to be adjusted to honor the no cache flag, too: https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/network/NetworkFetcher.java#L42

**Comment by atoropov** [comment]
Additionally to implementing option to disable caching, can you please provide a way to clear it programmatically?
Also that wouldn't be an issue if actual caching would not be so "aggressive". I'm using downloading from url, but if content by url changes, app never sees that and continue using cached animation.

**Comment by messi-wpy** [comment]
there is no such things ,anyway i can't find it --LottitCompositionCache. and lottie_cacheStrategy and cacheStrategy , it should have been removed
