### ISSUE TITLE
PerformanceTracker says all frames took 0ms to render

### ISSUE THREAD

**Issue by lbenedetto** [airbnb/lottie-android#1291]
I'm trying to use the performance tracker to see which layer is causing the animation to play at extremely slow framerate.
```
LottieCompositionFactory.fromRawRes(getContext(), R.raw.welcome_animation).addListener(composition -> {
    animation.setComposition(composition);
    animation.setPerformanceTrackingEnabled(true);
    PerformanceTracker tracker = animation.getPerformanceTracker();
    tracker.logRenderTimes();
    animation.playAnimation();
});
```
But I'm getting outputs like this, with all layers taking 0.00 to render.
```
D/LOTTIE: Render times:
D/LOTTIE: 		                          F2Sh:0.00
D/LOTTIE: 		                          F2LA:0.00
D/LOTTIE: 		                   __container:0.00
D/LOTTIE: 		                       melon 2:0.00
D/LOTTIE: 		          Light_green Outlines:0.00
D/LOTTIE: 		                           F1M:0.00
D/LOTTIE: 		                        Scene3:0.00
D/LOTTIE: 		           HighFive_AllInOne 2:0.00
D/LOTTIE: 		           Dark_green Outlines:0.00
...
```

tracker.getSortedRenderTimes also says 0 for everything.

If I addFrameListener, my listener never gets called.

**Comment by gpeal** [comment]
@lbenedetto I just ran this and it seemed to work. If you can reopen this with a sample project that reproduces this, I'll take another look. It's possible that it actually took <0.01ms to render if it's hardware accelerated.
