### ISSUE TITLE
How to change the tint of glyphs programmically?

### ISSUE THREAD

**Issue by moelle89** [airbnb/lottie-android#1294]
Hey, 
sorry if this was already discussed and solved, but it is bugging me for long already and i still wasnt able to fix it by myself.

I am trying to change the color of a text layer ( glyphs ) - i know how to change the color of normal shapes but wasn´t able to change the color of a text layer so far. - I found another issue thread over here that explained to use COLOR instead of COLOR_FILTER for text layers. - I tried it without success.

Here is what I have tried - first valuecallback for the  keypath *fg* (shapes) is working fine, the second for the keypath *fg2* (text)  doesnt work.

https://pastebin.com/M5FQVmQG

**Comment by gpeal** [comment]
@moelle89 Can you attach a sample project that reproduces this?

**Comment by moelle89** [comment]
> @moelle89 Can you attach a sample project that reproduces this?

is the json file itself enaugh or do u want to see the code where i am trying to tint it?

here u got the json file - the keyframe of the text layer is called "text" (unlike my example of the first post, there it was called "fg2")

so i m trying to tint the text layer "text" via java - changing the color of any other object, like shapes for example, works fine for me.

[slide01test.zip](https://github.com/airbnb/lottie-android/files/3346932/slide01test.zip)

**Comment by moelle89** [comment]
**Can be closed**. - now it makes sense why nothing worked for me. - I only uses the text-tool in after effects to edit the textColor - I missed the part that i have to add a separate fillColor to a text layer. - Sorry for this.
