### ISSUE TITLE
Change Text on Animation

### ISSUE THREAD

**Issue by hashweather** [airbnb/lottie-android#1295]
Hi all, I am new to body moving, but recently learnt how to use Lottie View on android

I currently have the JSON of a cool text animation that I grabbed from lottie-files.com.

Now, How can I alter that text and use my own text instead so the animation uses my text instead of the original text. Thanks.

**Comment by gpeal** [comment]
You can use a TextDelegate
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L723
