### ISSUE TITLE
Add lottie_startDelay tag attribute

### ISSUE THREAD

**Issue by softlion** [airbnb/lottie-android#1296]
Currently, when a lottie animation is set to auto start in a fragment layout xml, and this fragment is transitioning on screen, the animation plays during the transition.

To fix that, autoplay has to be disabled and the call to start have to be moved into viewcreated, using a delay function, which content has to be guarded against early fragment pause/destroy to prevent side effects.

A simple lottie_startDelay xml attribute would make this feature much easier to use.

**Comment by gpeal** [comment]
I would rather keep this on the application side of things rather than include it in the library. You could create your own extension function or something for your app though.

**Comment by softlion** [comment]
You can not create an extension function for xml tags .................................................................
