### ISSUE TITLE
update to 3.0.1 ,cause dependencies error

### ISSUE THREAD

**Issue by memoryjs** [airbnb/lottie-android#1297]
When I first use it, I created a demo application in android studio with the version 3.0.1,but error happened,log below:

Dependencies using groupId com.android.support and androidx.* can not be combined but found IdeMavenCoordinates{myGroupId='com.android.support', myArtifactId='drawerlayout', myVersion='28.0.0', myPacking='aar', myClassifier='null'} and IdeMavenCoordinates{myGroupId='androidx.drawerlayout', myArtifactId='drawerlayout', myVersion='1.0.0', myPacking='aar', myClassifier='null'} incompatible dependencies less... (Ctrl+F1) 
Inspection info:There are some combinations of libraries, or tools and libraries, that are incompatible, or can lead to bugs. One such incompatibility is compiling with a version of the Android support libraries that is not the latest version (or in particular, a version lower than your targetSdkVersion).  Issue id: GradleCompatible

but the version 2.7.0 works ok

**Comment by gpeal** [comment]
@memoryjs Lottie 3.0+ is only compatible with [androidx](https://developer.android.com/jetpack/androidx/migrate). I made a one-time `3.0.3-support` but I wouldn't count on any future updates and recommend switching to androidx.

**Comment by memoryjs** [comment]
> @memoryjs Lottie 3.0+ is only compatible with [androidx](https://developer.android.com/jetpack/androidx/migrate). I made a one-time `3.0.3-support` but I wouldn't count on any future updates and recommend switching to androidx.

OK,I know,now I use the versoin 2.7.0 , it works .I will not update the 3.x version util our project is compatiable with androidx

**Comment by gpeal** [comment]
@memoryjs you can use 3.0.3-support for now but I recommend upgrading.

**Comment by memoryjs** [comment]
> @memoryjs you can use 3.0.3-support for now but I recommend upgrading.

OK，thanks
