### ISSUE TITLE
Animation procceed exception

### ISSUE THREAD

**Issue by NamHofstadter** [airbnb/lottie-android#1301]
when I start a Animation in Android , I can only see the fisrt frame and the last frame,but the same resource is doing perfect in IOS device.
I use version 2.7.0,please help

**Comment by NamHofstadter** [comment]
and I have used HardwareAcceleration,but it doesn't help

**Comment by NamHofstadter** [comment]
@Gabriel Peal

**Comment by gpeal** [comment]
@NamHofstadter please try 3.0 first and if it still fails, you can reopen this but please attach your animation. A lot has changed since 2.7 and I no longer support 2.7

**Comment by NamHofstadter** [comment]
Is there a probility to use 3.0 without androidx?

**Comment by gpeal** [comment]
@NamHofstadter There was a one-time port `3.0.3-support`

**Comment by NamHofstadter** [comment]
I have download the newest version of lottie(3.0.7), and I made it useful without androidx, hope it will be helpful to others
[lottie.zip](https://github.com/airbnb/lottie-android/files/3395124/lottie.zip)

**Comment by NamHofstadter** [comment]
Thank you for your efforts
