### ISSUE TITLE
Lottie Animation Drawable is Behaving Different on Different Device

### ISSUE THREAD

**Issue by vkiranmaniya** [airbnb/lottie-android#1303]
## Issue Description
I'm creating the video by recording the frames in Lottie drawable. When I create the video of animation, the animation shifts slightly toward left or right in some device. Also in some device, the video just contains the half around animation duration. I have used OpenGL for video rendering and it works fine in OpenGL supported device. However, Some device has support to OpenGL but still fails to render the video from Lottie drawable. please consider the following test outcomes

>> ### Test Outcome
>> SM-J530F : OpenGL 3.2 (Failed to render, just renders the first frame of animation)
>> LG G6: OpenGL 3.2 (Working Perfectly)
>> NOKIA 6 PLUS: OpenGL 3.2 (Failed to render, renders half duration of animation only)
>> SM105F : OpenGL 2 (Failed to render) 

## Environment Info
+ Lottie v3.0.5
+ Android API 23
+ OpenGL v3.2

**Comment by boduan402** [comment]
Disable hardware render mode might be helpful.

**Comment by gpeal** [comment]
@vkiranmaniya Try what @boduan402 said. 
Does it look correct when you play your animations with LottieAnimationView?

**Comment by vkiranmaniya** [comment]
It, Looks correct when I render it as animation on view. but issues in LottieDrwable Frames, The frames slightly shifted in LottieDrawable and causes a shift in the rendered video from LottieDrawable. However, the behavior is different as the device varies. have you any clue regarding why it's happening?

**Comment by gpeal** [comment]
@vkiranmaniya You'll have to attach a sample project

**Comment by vkiranmaniya** [comment]
Here is the code snippet. let me explain the flow,
1. Load Lottie Animation. `loadJSONFromFile()` function loads the Lottie JSON file from device storage.
2. Create Composition from the JSON file and get the LottieDrawable.
3. Convert the entire image sequence contained in Lottie Drawable to Bitmap, will be used with renderer function to merge it with video.

`private void loadAnimation() {

        String json = loadJSONFromFile();
        drawable = new LottieDrawable();
        //LottieComposition composition = LottieComposition.Factory.fromJsonSync(json);
        LottieCompositionFactory.fromJsonString(json, getString(R.string.app_name)).addListener(new LottieListener<LottieComposition>() {
            @Override
            public void onResult(LottieComposition result) {
                //LottieDrawable drawable = (LottieDrawable) animView.getDrawable();
                animView.setComposition(result);
                if (bitmapList!=null && bitmapList.size()>0) {
                    animView.setImageAssetDelegate(new ImageAssetDelegate() {
                        @Nullable
                        @Override
                        public Bitmap fetchBitmap(LottieImageAsset asset) {
                            return bitmapList.get(asset.getFileName());
                        /*File file = new File(imagesFolderPath, asset.getFileName());
                        final Bitmap[] loadedBitmap = {null};
                          Glide.with(MainActivity.this).asBitmap().load(file).into(new SimpleTarget<Bitmap>() {
                          @Override
                          public void onResourceReady(@NonNull Bitmap resource, @Nullable Transition<? super Bitmap> transition) {
                                 loadedBitmap[0] = resource;
                            }
                          });
                          return loadedBitmap[0];*/
                        }
                    });
                }
                drawable = (LottieDrawable) animView.getDrawable();
                processBtn.setEnabled(true);
            }
        }).addFailureListener(new LottieListener<Throwable>() {
            @Override
            public void onResult(Throwable result) {
                result.printStackTrace();
                Crashlytics.logException(result);
            }
        });
    } `

**What I'm trying to achieve?**
I'm trying to create a merged video with background video and Lottie animation as video on top of it. consider 2 layers as the background is video and on top of it, the Lottie animation as a video. The JSON we are using is exported with the recommended plugin of Lottie with after effect.

**What is the outcome till now?**
1. I renderer the video from Lottie Animation successfully. but in some device, the Lottie frames returns blank bitmap so the rendered video is not properly exported.
2. In some Devices, Lottie Animation Image position shift either left or right. Lottie couldn't maintain the rendered frame propositions.

**What I'm Using?**
OpenGL to Render the Video
Lottie to get the Image sequence and generate video from it.


Here is the sample Lottie JSON exported from after effect.(JSON not supported as an attachment, so I attached as a text file) it's using the images attached below.

[animation.txt](https://github.com/airbnb/lottie-android/files/3410253/animation.txt)
![img_3](https://user-images.githubusercontent.com/22276302/61522729-91a25d80-aa30-11e9-8dc9-1190f0af58ec.png)
![img_2](https://user-images.githubusercontent.com/22276302/61522730-91a25d80-aa30-11e9-884b-165b1f7e876f.png)
![img_1](https://user-images.githubusercontent.com/22276302/61522733-923af400-aa30-11e9-8e21-327a3ed65a93.png)
![img_0](https://user-images.githubusercontent.com/22276302/61522734-923af400-aa30-11e9-8271-3e1eeed8f95d.png)
![img_3 (1)](https://user-images.githubusercontent.com/22276302/61522735-92d38a80-aa30-11e9-9c6c-508968c8d713.png)

**Comment by gpeal** [comment]
@vkiranmaniya Could this be related to #731 ?

**Comment by vkiranmaniya** [comment]
No, I guess. because rendering the video is not an issue. Here the issue is Lottie Animation behavior. Marking the point once again
1. LottieDrawable returns null frame in some device
2. The LottieDrawable frame does not maintain the proposition of animation and shift either left or a right little bit.
3. Behaves Differently when the Animation Composition has mutli layer image assets.

**Comment by vkiranmaniya** [comment]
@gpeal THe issue #731 is using FFmpeg for rendering, In my case, I'm working with OpenGL.

**Comment by gpeal** [comment]
@vkiranmaniya You only attached your json file. Please make a zip file with the json and required images. Better yet, please make the smallest animation that reproduces your issue. Reverse engineering the entire animation is very time consuming.

**Comment by vkiranmaniya** [comment]
[JF78_NEW.zip](https://github.com/airbnb/lottie-android/files/3416150/JF78_NEW.zip)
@gpeal  Let me tell you that, this is the only animation creating the issue, when I render the animation without image asset, it works fine. So you must go through this type of animation includes image asset and exported from After Effects.

**Comment by vkiranmaniya** [comment]
@gpeal is there any update on this issue?

**Comment by vkiranmaniya** [comment]
Here is a link of video for your reference.[https://drive.google.com/file/d/1fhq3Y1GU40F3t9GIqLQx80IGOpCOrpHq/view?usp=sharing](Issue Preview). When i play the animation, it plays completely perfect, but when i iterate over the bitmaps in LottieComposition, It is different. I performed two tests over it. In the first test, you can see the fluctuating animation image and the other test is with debug mode. debug mode exports the Lottie drawables in image folder. You can look at it.

**Comment by vkiranmaniya** [comment]
I tried once again by keeping the Animation Asset images into android assets and loaded from there. It worked fine.

**Comment by axitasavani** [comment]
Hi, @vkiranmaniya I have the same problem with my application, but in my case, i have already picked an image from an android asset but it's still not working Can you please give me some guides for that?
