### ISSUE TITLE
Is it possible to detect when the animation has started ?

### ISSUE THREAD

**Issue by Kelve17** [airbnb/lottie-android#1307]
I would like to add some more animations along with the json animation. For that, i would like to start both animations at the same time.

**Comment by gpeal** [comment]
@Kelve17 Yes, with an AnimatorListener or AnimationUpdateListener
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L596
