### ISSUE TITLE
json files cannot play correctly on android

### ISSUE THREAD

**Issue by chenyan-github** [airbnb/lottie-android#1309]
[this json file can't play correctly on android platform](https://lottiefiles.com/share/IFw77i)

**Comment by chenyan-github** [comment]
https://lottiefiles.com/share/IFw77i

**Comment by RuanXiaoHui** [comment]
我可以正常播放啊，你使用的是什么版本的Lottie? 我当前使用的是2.7.0的版本目测了没问题

**Comment by gpeal** [comment]
This seems to play correctly with the latest version. Reopen with the specific issue if you can still repro this on 3.1.0-SNAPSHOT.
