### ISSUE TITLE
cpu

### ISSUE THREAD

**Issue by 12ndxu** [airbnb/lottie-android#1315]
I use lottie:3.0.6 to show some animation,when it work the cpu temperature will rise to 70℃ from 40℃，how to optimize it

**Comment by gpeal** [comment]
http://airbnb.io/lottie/#/android?id=performance

**Comment by 12ndxu** [comment]
how to use Hardware Acceleration in lottie:3.0.6

**Comment by gpeal** [comment]
@12ndxu `setRenderMode`

**Comment by 12ndxu** [comment]
I use  `face_lav.setRenderMode(RenderMode.HARDWARE)` but the temperature also rise to 70℃ , what's wrong?
