### ISSUE TITLE
No .git directory found!But I didn't install git,How to solve the problem

### ISSUE THREAD

**Issue by azxcffdgadf** [airbnb/lottie-android#1316]
The first is to have this same problem. But it does not meet my situation. I did not install git. How to solve this problem.
(首先是有这个相同的问题.但是不符合我的情况.我并没有安装git.怎么解决这个问题.-->No .git directory found!)

**Comment by gpeal** [comment]
@azxcffdgadf This issue isn't related to Lottie. If you want to clone the repo, run `git clone git@github.com:airbnb/lottie-android.git`
