### ISSUE TITLE
MemoryLeak in LottieDrawable

### ISSUE THREAD

**Issue by zjupure** [airbnb/lottie-android#1319]
In LottieDrawable consturction method, it will auto add a annoyous update listener and refer the drawable and context, cause the activity leak. How to remove the update listener to avoid memory leak?
```
animator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
      @Override public void onAnimationUpdate(ValueAnimator animation) {
        if (compositionLayer != null) {
          compositionLayer.setProgress(animator.getValue());
        }
      }
    });
```

![reliao_img_1563248619472](https://user-images.githubusercontent.com/5836221/61264394-04a49d80-a7bf-11e9-941c-e0875c3fd26e.png)

**Comment by gpeal** [comment]
@zjupure You shouldn't reuse your LottieDrawable. Create a `LottieComposition` with `LottieCompositionFactory` if you want to do that. On top of that, Lottie caches compositions internally so you don't need to worry about passing around a drawable. The next time you call `setComposition`, it will automatically reuse the composition from the previous drawable.

**Comment by zjupure** [comment]
@gpeal we don't reuse lottieDrawable, we only set json to LottieImageView and it create a LottieDrawable bind with the View who hold the activity context. We call playAnimation()/pauseAnimation() according to Activity lifecycle. But the ValueAnimator was hold by android framework class ValueAnimator$AnimationHandler though the activity has been destoryed.
You can see the memory leak reference. It's cause by LottieDrawable construction method, but no place to remove the updateListener.

PS: com.airbnb.lottie.com1 ----> com.airbnb.lottie.LottieDrawable$1  it's an anonymous inner class.

**Comment by gpeal** [comment]
@zjupure Can you set up a sample project with Leak Canary 2.0 that and repro the leak?

**Comment by zjupure** [comment]
It is dumped from online data and not easy to produce.  I read ValueAnimator source and have some suspects. When animator is scheduled, AnimationHandler singleton will hold the reference to ValueAnimator. Until animator is canceled or stopped, AnimationHandler will remove the reference. So it might have a case:
1) lottie animation is playing, AnimationHandler hold it.
2) activity is destroyed, the animation not be canceled or stopped, it will be scheduled in background util end. There will be a bit time memory leak cause that activity cannot be recycled by GC.
3) How long the leak time is decided by animation left duration.

To avoid this case, we manually call LottieAnimationView#cacelAnimation() in activity#onDestory() lifecycle callback.  It release the reference from AnimationHandler to ValueAnimation.

**Comment by gpeal** [comment]
Newer versions of Lottie will unschedule the drawable when it is detached from the window.

**Comment by wyan-github** [comment]
@gpeal I found the same problem when i add a lottie view and then remove the view before the json load finished. I think it becasue the loader is not canceled when the view is detached from the window.
So when json load finished, it wound start a new animtor. Then the lottiedrawable is leaked because the view won,t be used, we have no chance to cancel the animtor of lottiedrawable.
