### ISSUE TITLE
Gradients seem to not be rendered correctly

### ISSUE THREAD

**Issue by mbasaglia** [airbnb/lottie-android#1325]
I've noticed gradient colors look off, I assume it isn't parsing the offsets in the color arrays.

I don't have the aftereffects file as I generated the lottie json in another way, but I have a minimal example: [out.zip](https://github.com/airbnb/lottie-android/files/3405878/out.zip)

The example has 3 rectangles: a yellow one to the left, an orange one to the right, and one in the middle with a gradient between the two colors.

Lottie web renders it correctly, but on android the gradient looks blue.

**Comment by mbasaglia** [comment]
Note: rlottie also renders it correctly (same as lottie-web) so it does seem lottie-android to be diverging from them

**Comment by gpeal** [comment]
@mbasaglia Can you attach the complete and unmodified json file?

**Comment by mbasaglia** [comment]
https://pastebin.com/TZYKWN71

**Comment by gpeal** [comment]
This looks correct now:
![image](https://user-images.githubusercontent.com/1307745/62585008-cd7c5600-b86b-11e9-8bc1-c1bbeddf873c.png)
Fixed by #1333
