### ISSUE TITLE
React native lottie not animating images which are parented to a shape layer's contents.

### ISSUE THREAD

**Issue by rocifier** [airbnb/lottie-android#1338]
**Checklist**
1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work:

===========

[Wheel Spin Broken Example.zip](https://github.com/airbnb/lottie-android/files/3438005/Wheel.Spin.Broken.Example.zip)

===========

**Describe the bug**
React native lottie doesn't animate images which are parented to a shape layer's contents.

**What version of Lottie did you test this on?**
All

**What version of Android did you test this on?**
All

**Steps To Reproduce**
1. Export using bodymovin 5.4.4 (compatible with current React Native)
2. Try the json file with a web preview, and observe the icons aligned and rotating to the wheel segments.
3. Use the <Lottie> component with correct images folder on its props in react native. (react native 0.59.8 with lottie-react-native 2.6.1)
4. Observe that icons are fixed in one place while the segments spin, unlike in the web version.

**Screenshots**
![bug](https://user-images.githubusercontent.com/1772304/61992525-ba22fb00-b0b3-11e9-8a24-87f4aecd368a.png)

**Comment by gpeal** [comment]
Please open an issue on https://github.com/react-native-community/lottie-react-native/
