### ISSUE TITLE
Dynamic Text doesn't change color using a ValueCallback

### ISSUE THREAD

**Issue by danh32** [airbnb/lottie-android#1342]
** If you don't use this template, your issue will be closed **

**Checklist**
1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Describe the bug**
We're using both dynamic text and coloring some elements in our animation at runtime using `ValueCallback`. Unfortunately, it looks like it's impossible to target the dynamic texts. We have tried: 

```
        animation.addValueCallback(
            KeyPath("**"),
            LottieProperty.STROKE_COLOR
        ) {
            context!!.getThemeColor(android.R.attr.textColorPrimary)
        }
        animation.addValueCallback(
            KeyPath("**"),
            LottieProperty.COLOR
        ) {
            context!!.getThemeColor(android.R.attr.textColorPrimary)
        }
```

and it colors everything else in the animation except for our texts.

**What version of Lottie did you test this on?**
3.0.7

**What version of Android did you test this on?**
api 23 - 28

**Steps To Reproduce**

**Screenshots**

Let me know if you need anything else from me. Happy to provide any of the above if it's useful.

**Comment by kartik1225** [comment]
Same from me I am trying to find the solution for it from past 3 months, If someone knows the solution then that would be really helpful.

**Comment by gpeal** [comment]
@kartik1225 For now, make the text color animatable, just set the start and end color to be the same then dynamic properties will work.

**Comment by kartik1225** [comment]
What property I have to change/animate?

In `after effect`?

In Effect panel?
![](https://imgur.com/gPRX9mA)

or in the text editor?
![](https://imgur.com/OSjySj7)

And what `LottieProperty` I have to change?
`LottieProperty.COLOR` , `LottieProperty.COLOR_FILTER` or `LottieProperty.STROKE_COLOR`
