### ISSUE TITLE
Shift in Animation Frames and Slow Rendering

### ISSUE THREAD

**Issue by vkiranmaniya** [airbnb/lottie-android#1344]
**Description**
I have custom animation exported from After Effect by the Lottie plugin. The animation is using custom image assets. When I create and play the Lottie composition, it slightly shifts either left or right in some devices. Lottie is also rendering the animation bit slow and animation is fluctuating. I tested it with 30 and 12 FPS animations but all fails.

**Environment**
Lottie v3.0.7

**Android Versions**

Name | Version | API Level
-- | -- | --
Marshmallow | 6.0 | API level 23
Nougat | 7.1 | API level 25
Lollipop | 5.1 | API level 22

**Notes**
1. Animation has multiple asset images, should be loaded from the file system, not from android assets
2. I created a Lottie composition by loading assets as a bitmap and gave to Lottie.
3. by Iterating over each frame of Lottie composition, I've noticed that frames are not drowned correctly.
4. Tested with Animation  30 FPS and 12 FPS

**Comment by gpeal** [comment]
For performance, experiment with software or hardware rendering (`setRenderMode`).

Regarding the shifting, try 3.1.0-SNAPSHOT, it may be fixed.
Other than that, there is nothing else actionable from this issue.
