### ISSUE TITLE
View.unscheduleDrawable is not working for LottieDrawable.

### ISSUE THREAD

**Issue by hua3505** [airbnb/lottie-android#1345]
View.unscheduleDrawable is not working for LottieDrawable. And LottieDrawalbe's Animation will never stop.
Steps:
1. ImageView.setImageDrawable(oneLottieDrawable);oneLottieDrawable.start();
2. ImageView.setImageDrawable(newDrawalbeAnyType)
It's also happen when use  View.setBackground.

ImageView will call unscheduleDrawable to stop old drawable's animation. 
```java
public void unscheduleDrawable(Drawable who) {
    if (mAttachInfo != null && who != null) {
        mAttachInfo.mViewRootImpl.mChoreographer.removeCallbacks(
                Choreographer.CALLBACK_ANIMATION, null, who);
    }
}
```
But LottieDrawable use LottieValueAnimator. And LottieVauleAnimator.postFrameCallback did  not add LottieDrawable as token. So mChoreographer.removeCallbacks cannot remove callback that LottieValueAnimator post before.
```java
  protected void postFrameCallback() {
    if (isRunning()) {
      removeFrameCallback(false);
      Choreographer.getInstance().postFrameCallback(this);
    }
  }
```

**Comment by gpeal** [comment]
@hua3505 Could you please put up a pull request for this?

**Comment by gpeal** [comment]
Fixed by https://github.com/airbnb/lottie-android/commit/adb331b1a911bfe27a778870102e302335b68e17
