### ISSUE TITLE
Animation became blurred after update the lottie version.

### ISSUE THREAD

**Issue by Aquarids** [airbnb/lottie-android#1347]
**Describe the bug**
After I updated the version from 0.2.8 to 3.0.1, the animation became blurred. Is this a bug or should I change my code with the new version?

**What version of Lottie did you test this on?**
v3.0.1
**What version of Android did you test this on?**
Android 8.0.0

**Steps To Reproduce**
Use LottieAnimationView to load a anim json file.

**Comment by gpeal** [comment]
Please include a sample project that reproduces this and reopen if you are able to do that. There isn't enough information to provide assistance as-is.

**Comment by Aquarids** [comment]
Thanks for your replay, here is the sample project:

https://github.com/Aquarids/issue-lottie-1347-example

Change the version of lottie in build.gradle, it should reproduces the problem.

version 3.0.1:

![v3.0.1](https://user-images.githubusercontent.com/35091294/62852820-22f9ac80-bd1d-11e9-912f-dfdcce618514.png)

version 2.8.0:

![v2.8.0](https://user-images.githubusercontent.com/35091294/62852824-2725ca00-bd1d-11e9-805f-241a4a47b000.png)

**Comment by gpeal** [comment]
@Aquarids Try `setRenderMode(RenderMode.SOFTWARE)`

**Comment by Aquarids** [comment]
@gpeal It works. Thank you for your patience.

**Comment by ud17** [comment]
@gpeal Thank you ! Worked for me too!
