### ISSUE TITLE
Very slow animation from version 3.0.0

### ISSUE THREAD

**Issue by lorenc-tomasz** [airbnb/lottie-android#1358]
Hi,
I have used waves animation. It never was fast, but from version 3.0.0 is really laggy. On iOS everything works OK.

[waves.json.zip](https://github.com/airbnb/lottie-android/files/3496667/waves.json.zip)

**Comment by gpeal** [comment]
@lorenc-tomasz Try with `setRenderMode` set to hardware or software, different animations perform better with different settings.

**Comment by lorenc-tomasz** [comment]
Tried both. Similar result.

**Comment by gpeal** [comment]
@lorenc-tomasz Can you attach the aep?
