### ISSUE TITLE
Android Q requires non-SDK interface blacklists and graylists. Is there such a call involved in Lottie?

### ISSUE THREAD

**Issue by xiaobinghe** [airbnb/lottie-android#1359]
In my project, Lottie is used. With the release of Android Q, it is necessary to adapt it. In the Android Q version, Google officially prohibits the use of non-SDK interfaces, and sets up blacklists and graylists. I want to confirm Lottie. Is there a non-SDK called, thank you!

**Comment by gpeal** [comment]
Lottie doesn't use any private Android APIs
