### ISSUE TITLE
lottie animation-NullPointerException-crash,why?

### ISSUE THREAD

**Issue by RuanXiaoHui** [airbnb/lottie-android#1363]
java.lang.NullPointerException

Attempt to invoke virtual method 'com.airbnb.lottie.PerformanceTracker com.airbnb.lottie.LottieComposition.getPerformanceTracker()' on a null object reference

**Comment by gpeal** [comment]
Please follow the template

**Comment by zboing** [comment]
This issue happens rarely when you're switching between fragments or activities and I was able to reproduce it with:

implementation 'com.airbnb.android:lottie:3.1.0' and target sdk 32

My recommendation is to call the animation by using a method with NonNull annotation.

    private void showAnimation(@NonNull LottieAnimationView anim)
{
     //do whatever you like with the anim
}

**Comment by gpeal** [comment]
@zboing 3.2.0 is quite old now. Could you try upgrading?
