### ISSUE TITLE
Update Glide

### ISSUE THREAD

**Issue by edgar-zigis** [airbnb/lottie-android#1365]
**Is your feature request related to a problem? Please describe.**
New Kotlin version of 1.3.50 uses new annotation processing, which is used by Glide 4.9.0, however, when I update Glide in my application, then it collides with the version you use in your bundle (4.8.0), which crashes my app after some usage.

**Describe the solution you'd like**
Please update Glide used in your library.

**Comment by gpeal** [comment]
Lottie doesn't use Glide.
