### ISSUE TITLE
引用报错 implementation 'com.airbnb.android:lottie:3.0.7'

### ISSUE THREAD

**Issue by chenni521** [airbnb/lottie-android#1366]
Error:(1570) resource android:attr/fontVariationSettings not found.
Error:failed linking references.
Error:(11) error: resource android:attr/dialogCornerRadius not found.
Error:(9, 5) error: resource android:attr/dialogCornerRadius not found.
Information:Gradle tasks [:IMLib:generateDebugSources, :IMLib:generateDebugAndroidTestSources, :IMLib:mockableAndroidJar, :CallKit:generateDebugSources, :CallKit:generateDebugAndroidTestSources, :CallKit:mockableAndroidJar, :IMKit:generateDebugSources, :IMKit:generateDebugAndroidTestSources, :IMKit:mockableAndroidJar, :CallLib:generateDebugSources, :CallLib:generateDebugAndroidTestSources, :CallLib:mockableAndroidJar, :pushpermission:generateDebugSources, :pushpermission:generateDebugAndroidTestSources, :pushpermission:mockableAndroidJar, :app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar]
Information:See complete output in console
Error:(252, 5) error: resource android:attr/ttcIndex not found.
Error:Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt
Information:BUILD FAILED in 19s
Information:1 warning
Error:(11) resource android:attr/dialogCornerRadius not found.
Error:(7) resource android:attr/dialogCornerRadius not found.
Error:com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
D:\work\OnePlusOne\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml
Error:(1570) resource android:attr/ttcIndex not found.
D:\.gradle\caches\transforms-1\files-1.1\appcompat-1.0.0.aar\c0d285ccb4c3c0950d8fa94bf2fa328d\res\values-v28\values-v28.xml
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Information:13 errors
D:\work\OnePlusOne\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
D:\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\a34078050c08208eca5b0cbd677bfd47\res\values\values.xml
Warning:The `android.dexOptions.incremental` property is deprecated and it has no effect on the build process.
Error:java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:(252, 5) error: resource android:attr/fontVariationSettings not found.

**Comment by gpeal** [comment]
```
Error:(11) resource android:attr/dialogCornerRadius not found.
Error:(7) resource android:attr/dialogCornerRadius not found.
```
^ This is not Lottie related
