### ISSUE TITLE
How to konw play fail status?

### ISSUE THREAD

**Issue by donadoo** [airbnb/lottie-android#1367]
**Describe the solution you'd like**
Only AnimatorUpdateListener and AnimatorListener? how to know play json file with error?
I want to display a gif image if lottie play fail? is there any listener which I can know play fail?

**Comment by gpeal** [comment]
@donadoo You can use a LottieCompositionFactory manually. You can set a failure listener and then call `setComposition` in the success case.

[This](https://github.com/airbnb/lottie-android/pull/1350) is also coming in 3.1.0
