### ISSUE TITLE
java.io.FileNotFoundException when try to load animation from sd card

### ISSUE THREAD

**Issue by mfpolat** [airbnb/lottie-android#1375]
Hi I am trying to user this great library to create animation as described below
1. download animation.json file to sd card
2. download  all images needed in same folder with json file 
3. set lottieanimationview.setAnimationFromJson()

however i couldn't succeed. 
this is what animation json look like

`{
  "v": "5.4.1",
  "fr": 25,
  "ip": 0,
  "op": 1,
  "w": 600,
  "h": 750,
  "nm": "poster",
  "ddd": 0,
  "assets": [
    {
      "id": "image_0",
      "w": 176,
      "h": 246,
      "u": "assets/",
      "p": "asset1-4.png",
      "e": 0
    },
    {
      "id": "image_1",
      "w": 176,
      "h": 246,
      "u": "images/",
      "p": "mouth1.png",
      "e": 0
    },
    {
      "id": "image_2",
      "w": 176,
      "h": 246,
      "u": "images/",
      "p": "mouthblack1.png",
      "e": 0
    },
    {
      "id": "image_3",
      "w": 176,
      "h": 246,
      "u": "images/",
      "p": "face1.png",
      "e": 0
    }
  ],
  "layers": [
    {
      "ddd": 0,
      "ind": 1,
      "ty": 2,
      "nm": "hair1",
      "refId": "image_0",
      "sr": 1,
      "ks": {
        "o": {
          "a": 0,
          "k": 100,
          "ix": 11
        },
        "r": {
          "a": 0,
          "k": -1,
          "ix": 10
        },
        "p": {
          "a": 0,
          "k": [
            369.359,
            274.345,
            0
          ],
          "ix": 2
        },
        "a": {
          "a": 0,
          "k": [
            88,
            123,
            0
          ],
          "ix": 1
        },
        "s": {
          "a": 0,
          "k": [
            185.054,
            185.054,
            100
          ],
          "ix": 6
        }
      },
      "ao": 0,
      "ip": 0,
      "op": 1,
      "st": -187,
      "bm": 0
    },
    {
      "ddd": 0,
      "ind": 2,
      "ty": 2,
      "nm": "mouth1.png",
      "cl": "png",
      "refId": "image_1",
      "sr": 1,
      "ks": {
        "o": {
          "a": 0,
          "k": 100,
          "ix": 11
        },
        "r": {
          "a": 0,
          "k": -1,
          "ix": 10
        },
        "p": {
          "a": 1,
          "k": [
            {
              "i": {
                "x": 0.833,
                "y": 0.833
              },
              "o": {
                "x": 0.167,
                "y": 0.167
              },
              "n": "0p833_0p833_0p167_0p167",
              "t": -187,
              "s": [
                371.302,
                291.422,
                0
              ],
              "e": [
                371.689,
                302.865,
                0
              ],
              "to": [
                0,
                0,
                0
              ],
              "ti": [
                0,
                0,
                0
              ]
            },
            {
              "i": {
                "x": 0.833,
                "y": 0.833
              },
              "o": {
                "x": 0.167,
                "y": 0.167
              },
              "n": "0p833_0p833_0p167_0p167",
              "t": -175,
              "s": [
                371.689,
                302.865,
                0
              ],
              "e": [
                371.302,
                291.422,
                0
              ],
              "to": [
                0,
                0,
                0
              ],
              "ti": [
                0,
                0,
                0
              ]
            },
            {
              "i": {
                "x": 0.833,
                "y": 0.833
              },
              "o": {
                "x": 0.167,
                "y": 0.167
              },
              "n": "0p833_0p833_0p167_0p167",
              "t": -162,
              "s": [
                371.302,
                291.422,
                0
              ],
              "e": [
                371.302,
                291.422,
                0
              ],
              "to": [
                0,
                0,
                0
              ],
              "ti": [
                0,
                0,
                0
              ]
            },
            {
              "i": {
                "x": 0.833,
                "y": 0.833
              },
              "o": {
                "x": 0.167,
                "y": 0.167
              },
              "n": "0p833_0p833_0p167_0p167",
              "t": -134,
              "s": [
                371.302,
                291.422,
                0
              ],
              "e": [
                371.689,
                302.865,
                0
              ],
              "to": [
                0,
                0,
                0
              ],
              "ti": [
                0,
                0,
                0
              ]
            },
            {
              "i": {
                "x": 0.833,
                "y": 0.833
              },
              "o": {
                "x": 0.167,
                "y": 0.167
              },
              "n": "0p833_0p833_0p167_0p167",
              "t": -122,
              "s": [
                371.689,
                302.865,
                0
              ],
              "e": [
                371.302,
                291.422,
                0
              ],
              "to": [
                0,
                0,
                0
              ],
              "ti": [
                0,
                0,
                0
              ]
            },
            {
              "i": {
                "x": 0.833,
                "y": 0.833
              },
              "o": {
                "x": 0.167,
                "y": 0.167
              },
              "n": "0p833_0p833_0p167_0p167",
              "t": -109,
              "s": [
                371.302,
                291.422,
                0
              ],
              "e": [
                371.302,
                291.422,
                0
              ],
              "to": [
                0,
                0,
                0
              ],
              "ti": [
                0,
                0,
                0
              ]
            },
            {
              "i": {
                "x": 0.833,
                "y": 0.833
              },
              "o": {
                "x": 0.167,
                "y": 0.167
              },
              "n": "0p833_0p833_0p167_0p167",
              "t": -45,
              "s": [
                371.302,
                291.422,
                0
              ],
              "e": [
                371.689,
                302.865,
                0
              ],
              "to": [
                0,
                0,
                0
              ],
              "ti": [
                0,
                0,
                0
              ]
            },
            {
              "i": {
                "x": 0.833,
                "y": 0.833
              },
              "o": {
                "x": 0.167,
                "y": 0.167
              },
              "n": "0p833_0p833_0p167_0p167",
              "t": -33,
              "s": [
                371.689,
                302.865,
                0
              ],
              "e": [
                371.302,
                291.422,
                0
              ],
              "to": [
                0,
                0,
                0
              ],
              "ti": [
                0,
                0,
                0
              ]
            },
            {
              "i": {
                "x": 0.833,
                "y": 0.833
              },
              "o": {
                "x": 0.167,
                "y": 0.167
              },
              "n": "0p833_0p833_0p167_0p167",
              "t": -20,
              "s": [
                371.302,
                291.422,
                0
              ],
              "e": [
                371.302,
                291.422,
                0
              ],
              "to": [
                0,
                0,
                0
              ],
              "ti": [
                0,
                0,
                0
              ]
            },
            {
              "i": {
                "x": 0.833,
                "y": 0.833
              },
              "o": {
                "x": 0.167,
                "y": 0.167
              },
              "n": "0p833_0p833_0p167_0p167",
              "t": 14,
              "s": [
                371.302,
                291.422,
                0
              ],
              "e": [
                371.689,
                302.865,
                0
              ],
              "to": [
                0,
                0,
                0
              ],
              "ti": [
                0,
                0,
                0
              ]
            },
            {
              "i": {
                "x": 0.833,
                "y": 0.833
              },
              "o": {
                "x": 0.167,
                "y": 0.167
              },
              "n": "0p833_0p833_0p167_0p167",
              "t": 26,
              "s": [
                371.689,
                302.865,
                0
              ],
              "e": [
                371.302,
                291.422,
                0
              ],
              "to": [
                0,
                0,
                0
              ],
              "ti": [
                0,
                0,
                0
              ]
            },
            {
              "t": 39
            }
          ],
          "ix": 2
        },
        "a": {
          "a": 0,
          "k": [
            88,
            123,
            0
          ],
          "ix": 1
        },
        "s": {
          "a": 0,
          "k": [
            83.075,
            83.075,
            100
          ],
          "ix": 6
        }
      },
      "ao": 0,
      "ip": 0,
      "op": 1,
      "st": -187,
      "bm": 0
    },
    {
      "ddd": 0,
      "ind": 3,
      "ty": 2,
      "nm": "mouthblack1.png",
      "cl": "png",
      "refId": "image_2",
      "sr": 1,
      "ks": {
        "o": {
          "a": 0,
          "k": 100,
          "ix": 11
        },
        "r": {
          "a": 0,
          "k": -1,
          "ix": 10
        },
        "p": {
          "a": 0,
          "k": [
            371.302,
            291.422,
            0
          ],
          "ix": 2
        },
        "a": {
          "a": 0,
          "k": [
            88,
            123,
            0
          ],
          "ix": 1
        },
        "s": {
          "a": 0,
          "k": [
            83.075,
            83.075,
            100
          ],
          "ix": 6
        }
      },
      "ao": 0,
      "ip": 0,
      "op": 1,
      "st": -187,
      "bm": 0
    },
    {
      "ddd": 0,
      "ind": 4,
      "ty": 2,
      "nm": "face1.png",
      "cl": "png",
      "refId": "image_3",
      "sr": 1,
      "ks": {
        "o": {
          "a": 0,
          "k": 100,
          "ix": 11
        },
        "r": {
          "a": 0,
          "k": -1,
          "ix": 10
        },
        "p": {
          "a": 0,
          "k": [
            371.302,
            291.422,
            0
          ],
          "ix": 2
        },
        "a": {
          "a": 0,
          "k": [
            88,
            123,
            0
          ],
          "ix": 1
        },
        "s": {
          "a": 0,
          "k": [
            83.075,
            83.075,
            100
          ],
          "ix": 6
        }
      },
      "ao": 0,
      "ip": 0,
      "op": 1,
      "st": -187,
      "bm": 0
    }
  ],
  "markers": []
}`

and all the files needed is in the same folder with json file. 
Is it a supported feature ? if it is how can i work around this error

Thanks

**Comment by gpeal** [comment]
@mfpolat You'll have to create an `ImageAssetDelegate` and read the bitmaps from your sd card when Lottie asks for them.
Part of the reason Lottie can't do this automatically is that it requires permissions and Lottie isn't going to request permissions on your behalf.

**Comment by mfpolat** [comment]
Is there any example of how can i create `ImageAssetDelegate ` and use it with my json file ?

**Comment by gpeal** [comment]
@mfpolat http://airbnb.io/lottie/#/android?id=providing-your-own-images
