### ISSUE TITLE
Rendering animations using Graphics2D in java/swing apps

### ISSUE THREAD

**Issue by soleypasban** [airbnb/lottie-android#1381]
Hey guys,

We are willing to use AE animations inside our swing app using Graphics2D. However, as there is no plugin/library for it yet, we are going to implement it by ourselves.

I wonder if we will be able to do it without much issues, such as android specific dependencies, etc.

Looking forward to hearing from you soon.

**Comment by gpeal** [comment]
@soleypasban Not sure what exactly you mean here but nothing about Lottie is inherently tied to any platform which is why there are web, Android, iOS, and Skia renderers for it.
