### ISSUE TITLE
Rotating shape with gradient stroke rotates shape but not gradient

### ISSUE THREAD

**Issue by imjoeybrennan** [airbnb/lottie-android#1382]
[rotate-gradient-android.zip](https://github.com/airbnb/lottie-android/files/3581080/rotate-gradient-android.zip)

When rotating shape with gradient stroke Android Lottie rotates the shape but not it's gradient, which is unexpected as AE, Lottie iOS, and Lottie Web rotate the gradient as well. ~~Not sure even how to do this alternatively for Android to maintain consistencies between iOS and Android. ~~

Let me know if you have noticed this inconsistency and if this is a bug that can be fixed and/or an alternative method to accomplish the same effect.

Thanks in advance!

UPDATE: this only happens with gradient strokes. Gradient fills rotate as expected. 
ALTERNATIVE ROUTE: So as an alternative, one can outline the stroke and use a gradient fill.

**Comment by gpeal** [comment]
@imjoeybrennan Can you attach a gif of what is happening vs what is expected? It seems to be working correctly for me.

**Comment by gpeal** [comment]
I just trimmed and zoomed in the rotating gradient in your file and it seems to be behaving correctly on master. If you think there is still an issue, please fork the repo and reproduce it in the issue-repro module then link to that so I can fix it directly.

<img width="959" alt="Screen Shot 2019-11-30 at 2 06 26 PM" src="https://user-images.githubusercontent.com/1307745/69906600-d6dd8100-137a-11ea-9a5e-d211429fce9a.png">
<img width="957" alt="Screen Shot 2019-11-30 at 2 06 07 PM" src="https://user-images.githubusercontent.com/1307745/69906601-d6dd8100-137a-11ea-9864-b9ff0c02abf4.png">
<img width="958" alt="Screen Shot 2019-11-30 at 2 05 45 PM" src="https://user-images.githubusercontent.com/1307745/69906602-d6dd8100-137a-11ea-8a5e-70e7f1703d38.png">


[rotate-gradient-android (converted).aep.zip](https://github.com/airbnb/lottie-android/files/3907603/rotate-gradient-android.converted.aep.zip)
