### ISSUE TITLE
Hardwareacceleration looks like not working in Huawei Honor 9. (use 2.7.0)

### ISSUE THREAD

**Issue by fb0122** [airbnb/lottie-android#1383]
hello,  I am currently using 2.7.0，I turned on hardware acceleration, When I monitor the frame rate on different phones, I found that the FPS on Huawei honor 9 phones is only 20. at the same time , FPS is 60 on other phones.  When I use latest lottie version, it looks fine. But I have to use 2.7.0, I want to know what is the difference between these two versions in this regard?
Thanks~

**Comment by fb0122** [comment]
All running on Android P

**Comment by gpeal** [comment]
@fb0122 there are tons of changes, you can see the full list in the [changelog](https://github.com/airbnb/lottie-android/blob/master/CHANGELOG.md). I made a one-time 3.0.3-support version that uses the support lib. It's out of date but might work for you. I highly recommend upgrading to androidx though.
