### ISSUE TITLE
Crash: java.lang.IllegalStateException Unable to create layer for LottieAnimationView, size 1088x-448 max size 8192 color type 4 has context 1 

### ISSUE THREAD

**Issue by lchad** [airbnb/lottie-android#1387]
I just upgrade lottie version from 2.7.0 to 3.0.7.
I got some new crash in the latest version app.

StackTrace in Android 9:
# main(2)

java.lang.IllegalStateException

Unable to create layer for LottieAnimationView, size 1088x-448 max size 16384 color type 4 has context 1

1 android.os.MessageQueue.nativePollOnce(Native Method)
--
2 android.os.MessageQueue.next(MessageQueue.java:330)
3 android.os.Looper.loop(Looper.java:169)
4 android.app.ActivityThread.main(ActivityThread.java:7083)
5 java.lang.reflect.Method.invoke(Native Method)
6 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
7 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

Anyone is try to fix this problem?

**Comment by GeeJoe** [comment]
Face the same issue，when will this problem to be solved?

**Comment by lchad** [comment]
it's is really hard to reproduce.
in a one million DAU App, crash about 10 times everyday.

**Comment by Sanjay-F** [comment]
+1 

---

**StackTrace in Android 5.0/5.1:**
  
java.lang.IllegalStateException: Unable to create layer for LottieAnimationView @62b16e5
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:143)
at android.os.Looper.loop(Looper.java:122)
at android.app.ActivityThread.main(ActivityThread.java:5418)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by GeeJoe** [comment]
> it is really hard to reproduce.
> in a one million DAU App, crash about 10 times everyday.

+1 @gpeal @lchad

**Comment by gpeal** [comment]
@GeeJoe @Sanjay-F You can use `setRenderMode(RenderModel.SOFTWARE)` to get around this.

**Comment by DineshBabuYadav** [comment]
@gpeal , where should i set this "setRenderMode(RenderModel.SOFTWARE)"

**Comment by gpeal** [comment]
@DineshBabuYadav on your `LottieAnimationView`

**Comment by andrewmunn** [comment]
Seeing this crash exclusively on Android 9 devices, even after setting the rendering mode to Software in the XML:
```
Fatal Exception: java.lang.IllegalStateException: Unable to create layer for LottieAnimationView, size 1024x0 max size 8192 color type 4 has context 1
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:181)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by andrewmunn** [comment]
Update: Upgrading to `3.1.0` and using software rendering mode seems to have fixed the crash.

**Comment by nokite** [comment]
I only see this crash on Samsung devices - J4+ and J6+

**Comment by mochadwi** [comment]
Any updates on this? is this related to the dirty xml layout as well? In my case, I've `scrollview <- recycler view <- inside nested recyclerview`

**Comment by lchad** [comment]
3.0.7 + `setRenderMode(RenderModel.SOFTWARE)` can not fix this problem.

**Comment by lylissuperman** [comment]
3.1.0  , Face the same issue，when will this problem to be solved?
java.lang.IllegalStateException
Unable to create layer for LottieAnimationView @564d826
1	android.os.MessageQueue.nativePollOnce(Native Method)
2	android.os.MessageQueue.next(MessageQueue.java:148)
3	android.os.Looper.loop(Looper.java:151)
4	android.app.ActivityThread.main(ActivityThread.java:5714)
5	java.lang.reflect.Method.invoke(Native Method)
6	java.lang.reflect.Method.invoke(Method.java:372)
7	com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
8	com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by lchad** [comment]
> 3.1.0 , Face the same issue，when will this problem to be solved?
> java.lang.IllegalStateException
> Unable to create layer for LottieAnimationView @564d826
> 1 android.os.MessageQueue.nativePollOnce(Native Method)
> 2 android.os.MessageQueue.next(MessageQueue.java:148)
> 3 android.os.Looper.loop(Looper.java:151)
> 4 android.app.ActivityThread.main(ActivityThread.java:5714)
> 5 java.lang.reflect.Method.invoke(Native Method)
> 6 java.lang.reflect.Method.invoke(Method.java:372)
> 7 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
> 8 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

tried `setRenderMode(RenderModel.SOFTWARE)` ?

**Comment by dandroidbluecrew** [comment]
I'm seeing this as well in Crashlytics.  Already have it using `app:lottie_renderMode="software"` in the layout xml for the LottieAnimationView, and using `implementation 'com.airbnb.android:lottie:3.1.0'` in the build.gradle.

Note that for me it's only happening on LG devices with Android 9.

**Comment by gpeal** [comment]
@dandroidbluecrew Are you sure it isn't caused by another animation?

**Comment by dandroidbluecrew** [comment]
@gpeal This is really the only animation in the app, and the crash started showing up in Crashlytics in the exact build where we first integrated the Lottie SDK and added the animation.  
I suppose we might be doing something that's forcing the error, here's more info on the setup:

We have it in the layout XML nested within some other layout elements:

```
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:id="@+id/root_layout"
    xmlns:tools="http://schemas.android.com/tools"
    android:background="@color/white">

    <androidx.core.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fillViewport="true">

        <androidx.constraintlayout.widget.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <com.airbnb.lottie.LottieAnimationView
                android:id="@+id/top_background_animation"
                android:layout_width="match_parent"
                android:layout_height="227dp"
                android:background="@color/brand_blue"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                app:lottie_fileName="animations/confetti.json"
                app:lottie_loop="false"
                app:lottie_autoPlay="false"
                app:lottie_renderMode="software"
                 />

          //...................
```

Devices affected:

<img width="736" alt="Screen Shot 2019-12-10 at 7 21 49 PM" src="https://user-images.githubusercontent.com/52673801/70588685-5db40a00-1b82-11ea-92f9-270de6e28017.png">


Here is the stack trace that shows up in Crashlytics:

```
Fatal Exception: java.lang.IllegalStateException: Unable to create layer for ConstraintLayout, size 768x5568 max size 8192 color type 4 has context 1
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next + 326(MessageQueue.java:326)
       at android.os.Looper.loop + 170(Looper.java:170)
       at android.app.ActivityThread.main + 6993(ActivityThread.java:6993)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 493(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main + 884(ZygoteInit.java:884)
```

**Comment by gpeal** [comment]
@lchad @GeeJoe @DineshBabuYadav @andrewmunn Can you share the complete set of devices this is happening on?

**Comment by lchad** [comment]
![image](https://user-images.githubusercontent.com/6659831/70980661-9efe6980-20ee-11ea-8a1e-f18bedf2861c.png)

**Comment by lchad** [comment]
@gpeal

**Comment by tilalapradip** [comment]
> Any updates on this? is this related to the dirty xml layout & animation as well for below API 5.0? In my case, I've `scrollview <- recycler view <- inside nested recyclerview`

Yes, its related to same, as RecyclerView inside scrollview or nestedscrollview try to load all items at once. As RecyclerView loads all items also that are not visible. If you put log inside onBindViewHolder of RecylerView you find that all items loads at the start instead of based on the visibility of the item. This causes the parent LinearLayout (inside the ScrollView) to throw exception.

**Comment by gpeal** [comment]
I just ordered an LG Aristo 3 Plus. Let's see if I can reproduce this. @dandroidbluecrew Could you attach the animation that crashes?

**Comment by dandroidbluecrew** [comment]
@gpeal Thank you for continuing to look into this!

Here's the animation:

[confetti.json.zip](https://github.com/airbnb/lottie-android/files/4003256/confetti.json.zip)


Also, here's the current device list in Crashlytics for our latest build:

<img width="752" alt="Screen Shot 2019-12-26 at 10 50 37 AM" src="https://user-images.githubusercontent.com/52673801/71486969-a9df8b00-27cd-11ea-9412-5d68daebc050.png">

**Comment by gpeal** [comment]
@lchad @dandroidbluecrew @mochadwi @nokite The Aristo 3+ arrived running Pie and I am unable to reproduce the crash with the attached animation. I tried different combinations of hardware/software rendering and rendering many animations or animations that are larger than the screen (or both), landscape and portrait.

One theme I see in the stack traces where the full message was posted is that one dimension was either larger than the screen dimension (1088 or 5568) or 0. Can you try and adjust your layouts such that this never happens?

Any other information you can provide (animations, layouts, etc.) would be helpful.

**Comment by mochadwi** [comment]
Thanks for providing answer @gpeal , I see, so we need to configure multi-dimension to overcome this issue?

**Comment by gpeal** [comment]
@mochadwi It totally depends in the layout itself. Just try to make sure it is constrained to the screen size however you construct your layouts. This may or may not require landscape layouts depending on the specifics of your app.

**Comment by GeeJoe** [comment]
> @lchad @GeeJoe @DineshBabuYadav @andrewmunn Can you share the complete set of devices this is happening on?
I tried setRenderMode(RenderModel.SOFTWARE) and it worked for me

**Comment by GeeJoe** [comment]
But I get a new crash on Android 7.0 recently. Here is the stack of the crash
![image](https://user-images.githubusercontent.com/13412420/72674417-230e8d00-3ab1-11ea-9535-123304be9266.png)

It is similar to this [https://github.com/airbnb/lottie-android/issues/1199](issue),which the recommend answer is also setRenderMode(RenderModel.SOFTWARE)

I haven't try it，the stack is confused
@gpeal

**Comment by carloshs94** [comment]
im also having this issue, only on Android 9.
1800 DAU, i got like 18 crashes.
i'll try with render mode software. do you recommend doing it only on android 9?

The LottieView is inside a RelativeLayout, nothing fancy, not inside a recyclerview

Fatal Exception: java.lang.IllegalStateException: Unable to create layer for LottieAnimationView, size 1088x-320 max size 16384 color type 4 has context 1
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next + 326(MessageQueue.java:326)
       at android.os.Looper.loop + 181(Looper.java:181)
       at android.app.ActivityThread.main + 6986(ActivityThread.java:6986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 494(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main + 1445(ZygoteInit.java:1445)

@gpeal 
these are the failing devices: 
SM-J260A
Galaxy J7 Prime2
Galaxy S9
Galaxy J7 Neo
Xiaomi Poco F1
FIG-LX1
Y9 Prime 2019

**Comment by gpeal** [comment]
@carloshs94 1088 is slightly taller than 1080 which might be the resolution for some of those devices. Could you check your layout and see if there is anything that could cause it to be taller than the screen?

**Comment by li-gjhawar** [comment]
Why does this happen on these specific samsung and lg devices?

**Comment by JaEdmuva** [comment]
For me it's happening only for HUAWEI devices (nova, honor 6x, P9 lite) on Android 7.0. I'm using lottie in react-native `"lottie-react-native": "3.1.1"` which internally uses `com.airbnb.android:lottie:3.0.0`

**Comment by urgentx** [comment]
Occurring for me on Vodafone 895

**Comment by krottv** [comment]
Version 3.5 and it still happens.

**Comment by coopermaruyama** [comment]
I had this same issue in my app, it was because I was doing something like this:

```jsx
<LottieAnimationView
  onAnimationDidFinish={() => {
    this.setState({ didFinishAnimation: true })
  })
  style={{ display: this.state.didFinishAnimation ? 'none' : undefined }}
/>
```

The root cause was flipping the display property between `none` and `undefined`.

Just like a lot of posters here, I was also only getting this crash on certain android phones.

I was able to fix it with the same behavior by using `transform: [{ scale:  0}]` instead of `display: none` in order to hide the animation.

So the new code that no longer crashes became:

```jsx
<LottieAnimationView
  onAnimationDidFinish={() => {
    this.setState({ didFinishAnimation: true })
  })
  style={{ display: this.state.didFinishAnimation ? [{ scale:  0}] : [] }}
/>
```

**Comment by Pacey6** [comment]
When will release a new version to fix this?
