### ISSUE TITLE
Lottie animation not working for Android 10 on Version 3.0.7

### ISSUE THREAD

**Issue by rahulpwar654** [airbnb/lottie-android#1391]
Lottie animation not working for Android 10 on Version 3.0.7 but works fine on version 3.0.0.
on Android 10, Version 3.0.7  only renders lottie json first screen  but doesn't animate. 

Testing on Essential Phone-1 with Android 10 
Lottie file used path = LottieSample/src/main/assets/lottiefiles/day_night_cycle.json

**Comment by CraZyLegenD** [comment]
I can confirm the same issue on 3.0.7

**Comment by gpeal** [comment]
@rahulpwar654 @CraZyLegenD It works fine on master on my Pixel 3. Do you have animations disabled?

**Comment by rahulpwar654** [comment]
if animations were  disabled it won't be working on  version 3.0.0.

**Comment by gpeal** [comment]
@rahulpwar654 That is the expected behavior. It respects system animations and jumps to the end.

**Comment by gpeal** [comment]
#1129

**Comment by filipuic** [comment]
@gpeal it looks like he meant "no, animations were not disabled". Maybe it's still an issue.

**Comment by QUK-Pesiloman** [comment]
@filipuic 

You right, the animations will not working and it jump to the end animation when you turn off all option DRAWING in DEVELOPER OPTIONS.

**Comment by rajshreetiwari** [comment]
Hello @gpeal , i am facing the same but little weird problem, on Samsung A10 , Oneplus os 10.0 highest resolution my lottie animations images are cutting from left, what can i do, please sugest

**Comment by yejiurui** [comment]
it`s right ，please don`t turn off all option in developer options in android settings

**Comment by iamjosephmj** [comment]
This looked interesting, I was able to make Lottie animations work with:

**Comment by gpeal** [comment]
@lolitaCrastaAcko This library doesn't run on flutter. You are probably posting on the wrong repo.
