### ISSUE TITLE
TextLayers don't combine unicode combining characters

### ISSUE THREAD

**Issue by Adimote-work** [airbnb/lottie-android#1396]
**Checklist**

- [X] 1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
- [X] 2. I know what part of my animation doesn't work.
- [X] 3. I have created a simplified version of my animation 
- [X] 4. I have attached the AEP file - You can use [this one from a similar bug](https://github.com/airbnb/lottie-web/files/3177765/hindi.animation.zip). I think the json file is invalid so you'll need to re-export and set the FontAssetDelegate to something which returns `Typeface.DEFAULT`.

**Describe the bug**
Text which uses unicode [combining characters](https://en.wikipedia.org/wiki/Combining_character) (notably Hindi) is rendered character-by-character, ignoring the need for combining characters to be rendered as one.

Combining characters (i.e. diacritics) are unicode characters representing a modification to a previous character. For example: '​း' is a diacritic which can be added to 'ဆီ' to make 'ဆီး'.

In Lottie android it's rendered as 'ဆီ​း' (the circle denotes a missing previous character for the diacritic) which is invalid Hindi.

I believe this is caused by the text being split into individual characters, then [`canvas.drawText()` is called on each individual character](https://github.com/airbnb/lottie-android/blob/5e12628a0ded9eb37473a3b7b54d0cccf8ef86be/lottie/src/main/java/com/airbnb/lottie/model/layer/TextLayer.java#L355), ignoring the need for combining characters to remain with their preceding characters.

It seems Lottie for web had a similar issue: https://github.com/airbnb/lottie-web/issues/1603 but [their fix](https://github.com/airbnb/lottie-web/commit/978935d35f6ee40a015cbf451ba11f55df3dab4d) just handled the hindi characters, it's probably best to support all combining characters.

**What version of Lottie did you test this on?**

3.0.1 (but this is still an issue at head)

**What version of Android did you test this on?**

Q and P

**Steps To Reproduce**
1. Render the animation (set the FontAssetDelegate to something which always returns `Typeface.DEFAULT`)
2. See the error

**Comment by kartik1225** [comment]
It's also not working in Gujarati (language) font. 
![Font rendering error in gujrati](https://i.ibb.co/9Zf0Svg/Screenshot-2019-11-04-at-10-38-32-PM.png)

**Comment by Adimote-work** [comment]
It looks like the canonical way of iterating through graphemes (characters, including diacritics) is to use the BreakIterator https://developer.android.com/reference/java/text/BreakIterator

**Comment by gpeal** [comment]
@Adimote-work @kartik1225 I would accept a PR for this. You may want to check out the [code point parsing](https://github.com/airbnb/lottie-android/blob/5e12628a0ded9eb37473a3b7b54d0cccf8ef86be/lottie/src/main/java/com/airbnb/lottie/model/layer/TextLayer.java#L373) as well. I can't read Hindi or Gujarati myself so this one will be difficult for me to do well.

**Comment by Prajyot-** [comment]
We too are facing the same issue in android. @gpeal you need not actually understand the language, all you need to see that there are no dotted circles getting displayed. 

Here is similar issue mentioned with web player -> https://github.com/airbnb/lottie-web/issues/1603 

And the patch code for resolving the issue in web -> https://github.com/airbnb/lottie-web/commit/978935d35f6ee40a015cbf451ba11f55df3dab4d

**Comment by kuchnaya-hub** [comment]
It seems the isModifier() Method  Of TextLayer, just needs to add support for Character.getType(codePoint) == Character.DIRECTIONALITY_NONSPACING_MARK also to support Unicode characters for Hindi.

Please someone add that to the method to enable Support for Languages such as Hindi.

private static boolean isModifier(int codePoint) {
 
  return Character.getType(codePoint) == Character.FORMAT ||
      Character.getType(codePoint) == Character.MODIFIER_SYMBOL ||
      Character.getType(codePoint) == Character.NON_SPACING_MARK ||
      Character.getType(codePoint) == Character.OTHER_SYMBOL ||
    **Character.getType(codePoint) == Character.DIRECTIONALITY_NONSPACING_MARK ||**
    Character.getType(codePoint) == Character.SURROGATE;
}

**Comment by mmdumi** [comment]
Hi guys,
Sorry to bother you with this. Does anybody know if this issue will get solved sometimes in the next 1-2 months ?

**Comment by gpeal** [comment]
I would happily accept a PR for this

**Comment by mmdumi** [comment]
Do you know when we should expect a release version for this issue ?

**Comment by gpeal** [comment]
@mmdumi Today!
