### ISSUE TITLE
Does Lottie support play voice ?

### ISSUE THREAD

**Issue by donadoo** [airbnb/lottie-android#1398]
**Is your feature request related to a problem? Please describe.**

I want to play voice with lottie, just use one json/zip file, including voice file.  but I don't know whether lottie could support or not? 

I test this lottie file 
https://lottiefiles.com/630-voice?page=9
no voice could hear.

**Comment by gpeal** [comment]
Lottie doesn't do anything with audio. Voice is just the name of the animation.
