### ISSUE TITLE
regarding make lottie library

### ISSUE THREAD

**Issue by Jungaaaa** [airbnb/lottie-android#1399]
**Read this or your issue will be closed**

* Before opening a new issue, look through existing issues for duplicates.
* Simplify your animation to the simplest animation that reproduces your issue.
* Zip your After Effects AEP file and attach it. Your issue will be auto-closed if it doesn't have an AEP or no explicit reason otherwise is given.
* If you don't know English, run your issue through Google Translate.
* If you leave the template text in your issue, it will be closed.

Heelo, I'm using the lottie library very well.

I want to make lottie AAR library. 
so I was downloaded the lottie code by
git clone https://github.com/airbnb/lottie-android.git.

and Open the project on Android studio. and build APKs.
but I get the message below.
APK(s) generated successfully: 
Module 'LottieSample': locate or analyze the APK. 
Module 'issue-repro': locate or analyze the APK.

How can I get Module lottie's output? Why don't create Module lottie's output?
Please let me know. Thank you!

**Comment by gpeal** [comment]
`./gradlew lottie:assembleRelease` produces `lottie/build/outputs/aar/lottie-release.aar`
