### ISSUE TITLE
Lottie Objects keep pulling up (memory leak).

### ISSUE THREAD

**Issue by Jungaaaa** [airbnb/lottie-android#1402]
** If you don't use this template, your issue will be closed **

**Checklist**
1. Fork this repository into your account.
1. Reproduce your issue in the issue-repro module. Issues without a repro in the issue-repro 
module may be auto-closed.

**Link to fork with a repro in the issue-repro module**

**Describe the bug**

**Steps To Reproduce**

(1) I set tint color to LottieAnimationView like below.
((LottieAnimationView) mIcon).addValueCallback(
                    new KeyPath("**"),
                    LottieProperty.COLOR_FILTER,
                    new LottieValueCallback<ColorFilter>(new SimpleColorFilter(iconColor)));

Every time this part is called, the objects 
(LottieFrameInfo, LottieValueCallback, LottieDrawable, KeyPath, ValueCallbackKeyframeAnimation, Keyframe etc.) are allocation. It makes the memory leak.
I know that if we use regarding add API, we will use remove API too. 
Is there any API related remove?

Please share any idea regarding this problem to me, Thank you.

**Comment by gpeal** [comment]
@Jungaaaa Please follow the issue template which includes reproducing this in a fork of the repo in the issue-repro module.

**Comment by gpeal** [comment]
There isn't enough information to reproduce your issue. Please repro this in the issue-repro module in this repo and post a link to your fork so I can take a look.
