### ISSUE TITLE
Release a new version of lottie

### ISSUE THREAD

**Issue by carstenhag** [airbnb/lottie-android#1405]
Hey, could you please release a new lottie version with the fix for #1376 applied (or perhaps just a release from master)?

Using the SNAPSHOT version could work, but it is not quite good to do so. Afaik a RC-Version would be good. Thanks in advance!

**Comment by PatrickGaissert** [comment]
We are also experiencing a lot of glitches with the current version that seam to be fixed with the current master. Since we want release soon it would be great to have a new stable build soon.

**Comment by carstenhag** [comment]
Hello @plnice and @gpeal, sorry for pinging, but could you please comment on this? Thanks! 🙂

**Comment by gpeal** [comment]
@carstenhag I'll release 3.1.0 ASAP

**Comment by gpeal** [comment]
@carstenhag @PatrickGaissert @r-ralph @alexandrudumbravan-nutmeg @asavill @MattWilliams89 @mmakmw 3.1.0 is out 😄

**Comment by carstenhag** [comment]
🎉🎉🎊🎊🎉🎉🎉
