### ISSUE TITLE
lottie版本从2.7.0升级到了3.0.7后，产生了奔溃

### ISSUE THREAD

**Issue by AndroidStudy2015** [airbnb/lottie-android#1410]
lottie版本从2.7.0升级到了3.0.7后，产生了这个奔溃
You must set an images folder before loading an image. Set it with LottieComposition#setImagesFolder or LottieDrawable#setImagesFolder
在2.7.0上是运行正常的，升级后，有一定概率出现上面的bug

**Comment by boduan402** [comment]
Can you post the crash callstack? 

Meanwhile, I would suggest you update the title/description to English so that it can benefit developers with different language background.

**Comment by gpeal** [comment]
http://airbnb.io/lottie/#/android?id=images
