### ISSUE TITLE
Rendered correctly in ae Bodymov, but rendered incorrectly in android lottie

### ISSUE THREAD

**Issue by chongbo2013** [airbnb/lottie-android#1412]
** If you don't use this template, your issue will be closed **

**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file
[ape.zip](https://github.com/airbnb/lottie-android/files/3739966/ape.zip)
 (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Describe the bug**
Rendered correctly in ae Bodymov, but rendered incorrectly in android lottie

**What version of Lottie did you test this on the new 3.1.0

**What version of Android did you test this on 8.0

**Steps To Reproduce**

**Screenshots**

*Lottie is supported and developed on nights and weekends. Please consider [sponsoring Lottie](%5Bhttps://github.com/users/gpeal/sponsorship%5D(https://github.com/users/gpeal/sponsorship) to help support this issue as well as future investments.*

**Comment by gpeal** [comment]
@chongbo2013 Please follow step 3 and explain, specifically, what your issue is.
