### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by bwalkernz** [airbnb/lottie-android#1414]
Hi can you please give us advice on how to get the CUP usage down on this type of animation?

*Lottie is supported and developed on nights and weekends. Please consider [sponsoring Lottie](https://github.com/users/gpeal/sponsorship) to prioritize this issue and help support this issue as well as future investments.*

**Comment by bwalkernz** [comment]
[Ripple_V2_Trans.json.zip](https://github.com/airbnb/lottie-android/files/3759486/Ripple_V2_Trans.json.zip)

**Comment by gpeal** [comment]
@bwalkernz You can use the sample app to see which layers are taking the longest to render. Your animation uses several effects that aren't even supported by Lottie such as master delay and follow stretch.
