### ISSUE TITLE
Animated Vector Drawable (AVD) Vs Json file

### ISSUE THREAD

**Issue by Tsouza29** [airbnb/lottie-android#1416]
**Read this or your issue will be closed**

* Before opening a new issue, look through existing issues for duplicates.
* Simplify your animation to the simplest animation that reproduces your issue.
* Zip your After Effects AEP file and attach it. Your issue will be auto-closed if it doesn't have an AEP or no explicit reason otherwise is given.
* If you don't know English, run your issue through Google Translate.
* If you leave the template text in your issue, it will be closed.

Hi, 

I was recently wondering about changing some json animations that I use on an app to animated vector drawable. 

I started taking a look on how to do that and didn't find any material telling which features are supported when using vector drawable animations and how to test them, like I have when using lottiefiles.com 

Either, I was guessing if AVD has a really better performance to make me change all the animations from Json to AVD a worthy effort.

Can you help me to understand those questions?
Cheers

**Comment by gpeal** [comment]
@Tsouza29 there is a comparison on the docs site [here](http://airbnb.io/lottie/#/android?id=lottie-vs-android-vector-drawable-avd).
