### ISSUE TITLE
Request to render lottie with opengl to improve animation efficiency

### ISSUE THREAD

**Issue by chongbo2013** [airbnb/lottie-android#1417]
**Describe the solution you'd like**

*Lottie is supported and developed on nights and weekends. Please consider [sponsoring Lottie](https://github.com/users/gpeal/sponsorship) to prioritize this issue and help support this issue as well as future investments.*

**Comment by gpeal** [comment]
Lottie already does that. Lottie -> Skia -> OpenGL/Vulkan.

**Comment by Viacheslav01** [comment]
Is the lottie lib use skia?

**Comment by gpeal** [comment]
Yes, Android (since Oreo) uses Skia under the hood.
