### ISSUE TITLE
Different png images on the same animation (same json file) in a list

### ISSUE THREAD

**Issue by Lamba15** [airbnb/lottie-android#1419]
Caching Animations
If you fire multiple animation requests for the same animation in parallel such as a wishlist heart in a RecyclerView subsequent requests will join the existing task so it only gets parsed once

the animation only get parsed once with the same images this is a snippet of my recyclerview code

```
switch (list.get(position).getCode()) {
                    case 1:
                        imageView.setImageAssetsFolder("valka_body_parts");
                        break;
                    case 2:
                        imageView.setImageAssetsFolder("ogen_body_parts");
                        break;
                }
```

only the valka body parts are loaded because it's the first one to fire and it's the only to fire as documented, how can I fire each request by it's own or disable caching 

![Screenshot_20191106-002648_Valka](https://user-images.githubusercontent.com/20637736/68251742-733a8f00-002c-11ea-8b53-13053cf7f932.jpg)

it's the same lottie file (char_standing.json) which is good but setImageAssetsFolder didn't update

**Comment by gpeal** [comment]
@Lamba15 You can use LottieCompositionFactory manually to create the composition. Those functions let you pass in your own cache key so you don't the same composition back multiple times.

**Comment by gpeal** [comment]
@Lamba15 You can now solve this by using different (or no) cache keys
https://github.com/airbnb/lottie-android/pull/1450
https://github.com/airbnb/lottie-android/pull/1502
