### ISSUE TITLE
Want to support random algorithm

### ISSUE THREAD

**Issue by VipMinF** [airbnb/lottie-android#142]
I have a requirement and each object can randomly generated coordinates when the animation begins 
![26a1369d4ab93197b64e1900ec92c8a0b9c8a009727ea-rbv1hs_fw658](https://cloud.githubusercontent.com/assets/25290829/23163831/21ed50d2-f86f-11e6-9d6c-c73405bc6694.gif)

**Comment by gpeal** [comment]
@vipminf you'd have to render this in after effects. Lottie doesn't do dynamic positioning.

**Comment by zeeeliza** [comment]
It took me some time to find out who you are and I did Ms. Curry,s
