### ISSUE TITLE
Picture deformation

### ISSUE THREAD

**Issue by zhupengxiang** [airbnb/lottie-android#1423]
Why is the picture inside the animation distorted and some pictures are not displayed intact?
![QQ图片20191108103851](https://user-images.githubusercontent.com/17894209/68445138-02ee6200-0214-11ea-8ec0-22c0ebe285e5.png)

![QQ图片20191108103945](https://user-images.githubusercontent.com/17894209/68445191-24e7e480-0214-11ea-8bc1-9e18f5112afa.png)

**Comment by gpeal** [comment]
Please reopen this with an animation setup in the issue-repro module and an aep file.
