### ISSUE TITLE
Why text support only fontfamily ('fFamily') not fontname('fName') ? 

### ISSUE THREAD

**Issue by axitasavani** [airbnb/lottie-android#1424]
** If you don't use this template, your issue will be closed **

**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 

**Describe the bug**

hello, I have to make one animation that is considered text-based animation and in this animation 

```
"fonts": {
    "list": [
      {
        "fName": "OpenSans-Bold",
        "fFamily": "Open Sans",
        "fStyle": "Bold",
        "ascent": 75.9994506835938
      },
      {
        "fName": "Raleway-Bold",
        "fFamily": "Raleway",
        "fStyle": "Bold",
        "ascent": 72.9995727539063
      }
    ]
  } 

```

and here is the JSON of part and font object, but when playing this animation not getting fontname but it's getting fonfamily only like Font is rendering in "OpenSans-Bold" but its actually render in "Open Sans" this.  So what is the problem and why this is happed Can you give me any solution for this? 

**What version of Lottie did you test this on?**
3.1.0

**What version of Android did you test this on?**
5,6,7,8,9

**Steps To Reproduce**

1. Just play animation
2.please, check the below Screenshots. 
-First one is from adobe after effect ( Text 1: J E N N I F E R, Text 2: G R A P H I C S  D E S I G N E R)
-Second one is from android Device( Text 1: J E N N I F E R, Text 2: G R A P H I C S  D E S I G N E R)

**Screenshots**
![vlcsnap-2019-11-08-11h36m04s631](https://user-images.githubusercontent.com/44259547/68454652-51edc480-021f-11ea-9066-5aefabf39bed.png)
![vlcsnap-2019-11-08-11h56m40s177](https://user-images.githubusercontent.com/44259547/68454653-52865b00-021f-11ea-8d3e-8ff4477354c4.png)

**Comment by axitasavani** [comment]
Hi, i have one solution for this issue Can i used that solution for me?

**Comment by cyan0777** [comment]
Hi, I meet a similar question, font family cannot be found. What is your solution to this issue?

**Comment by gpeal** [comment]
@axitasavani Feel free to put up a PR

**Comment by gpeal** [comment]
Font family is the name of the font file. Font name is the name of the font within the file.
