### ISSUE TITLE
The animation did not show complete

### ISSUE THREAD

**Issue by zhupengxiang** [airbnb/lottie-android#1427]
1. The animation does not show the complete middle white picture is not displayed
2. lottie version 3.1.0
3. [test.aep.zip](https://github.com/airbnb/lottie-android/files/3829509/test.aep.zip)
   [test.json.zip](https://github.com/airbnb/lottie-android/files/3829512/test.json.zip)
![QQ图片20191111104615](https://user-images.githubusercontent.com/17894209/68557345-899f7b00-0470-11ea-9f96-c9bafafcfcd7.png)

The actual effect should be the following
![QQ图片20191111104720](https://user-images.githubusercontent.com/17894209/68557405-ac319400-0470-11ea-80c1-efa236104fe0.png)

**Comment by boduan402** [comment]
For reference, there an error thrown out when parsing the mask, `Unknown mask mode` :

https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/parser/MaskParser.java#L41

In this case, the under-going mode is "n" which is supported (only "a", "s", "i" are supported).

**Comment by boduan402** [comment]
Hey Pengxiang, mind updating your issue description to English to get help from engineers all over the world? Thanks

**Comment by zhupengxiang** [comment]
The animation does not show the complete middle white picture is not displayed

**Comment by zhupengxiang** [comment]
So how should I solve this problem?

**Comment by zhupengxiang** [comment]
https://lottiefiles.com/share/JlZT1B    
Online parsing json animation is no problem

**Comment by huage2580** [comment]
have the similar problem。
in Android ，3.0.3-support
https://lottiefiles.com/share/34sn40

**Comment by boduan402** [comment]
AFAIK, not all modes are supported:
https://github.com/airbnb/lottie-web/blob/master/docs/json/helpers/mask.json

https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/parser/MaskParser.java#L41

**Comment by gpeal** [comment]
@huage2580 Please open a separate issue following the issue template. Every rendering issue is likely a separate issue.

**Comment by zhupengxiang** [comment]
@gpeal  I am using version 3.2.2. The animation still cannot be displayed completely.  But the load from assets in the lottie sample can be displayed.  May I ask what is the reason

**Comment by gpeal** [comment]
@zhupengxiang Because the fix went in after 3.2.2 was released
https://github.com/airbnb/lottie-android/commits/master

**Comment by zhupengxiang** [comment]
@gpeal Thanks! :smile:

**Comment by kirilamenski** [comment]
@gpeal Was this added in 3.3.0? I faced with the same issue my lottie file works great on iOs and in online [preview](https://lottiefiles.com/share/CEN1R4) but for [android](http://i.imgur.com/jLX0Csf.png) it doesn't display full animation. I use 3.3.0 lottie version.

**Comment by gpeal** [comment]
@kirilamenski That is likely a separate issue. Please file a separate issue for it.

**Comment by gpeal** [comment]
Please attach the aep when you do.
