### ISSUE TITLE
Autoplay not working on saved view instance

### ISSUE THREAD

**Issue by CodeRedDev** [airbnb/lottie-android#1428]
**Link to demo app for the issue**
https://github.com/CodeRedDev/LottieAutoplay

**Describe the bug**
In some cases it may be necessary to store the instance of a fragments view to save time and memory recreating it (see [StackOverflow backed by Ian Lake](https://stackoverflow.com/questions/54581071/fragments-destroyed-recreated-with-jetpacks-android-navigation-components/55039009#55039009) ). In these cases `autoPlay` would fail on a re-attachment of the fragment.

This is caused by

https://github.com/airbnb/lottie-android/blob/3a5d706bad862a4eec9e3b4bc10a0c693077987e/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L310-L311

Although in a normal scenario it will work in the cases like described above it will fail to play the animation and you would have to manually call `playAnimation()` in `onResume()` or the like. Also if you look at it from a logical point of view it does not make a lot of sense that `autoPlay` should only be applied once.

**Steps To Reproduce**

1. Checkout the demo app
2. Click on 'bottom nav 2'
2. Click on 'bottom nav 1'
4. See the animation not playing

**Comment by CodeRedDev** [comment]
@gpeal  Just for information could you explain why `autoPlay` from XML should only apply once?

**Comment by rutujapagire** [comment]
**autoplay="false" not working**
**below syntax-**
<lottie-player src="./assets/blue.json"  background="transparent"  speed="1" loop autoplay="false">
    </lottie-player>
