### ISSUE TITLE
Support saving LottieAnimatioView's state during configuration changes, if set ONLY from xml

### ISSUE THREAD

**Issue by Charis1331** [airbnb/lottie-android#1429]
**Is your feature request related to a problem? Please describe.**
If I declare my LottieAnimationView **solely** in xml and pass,, as attrs, the options to _auto_start_ and loop indefinitely (repeat_count = -1) and change the orientation of my device, then the animation restarts.

**Describe the solution you'd like**
I would like the state (paused, ended) of the LottieAnimationView to be saved during configuration changes (e.g. orientation), if it is **solely** set via **.xml**.

**Additional context**
```
    <com.airbnb.lottie.LottieAnimationView
        android:id="@+id/profile_pic"
        android:layout_width="100dp"
        android:layout_height="100dp"
        app:lottie_autoPlay="true"
        app:lottie_rawRes="@raw/result_success"
        app:lottie_repeatCount="-1" />
```

**Comment by gpeal** [comment]
This is not something we plan on supporting. I recommend adding some sort of a wrapper in your code.
