### ISSUE TITLE
LottieAnimationView and image assets folder

### ISSUE THREAD

**Issue by GokulEpiphany** [airbnb/lottie-android#143]
There is no function to set ImageAssetsFolder on LottieAnimationView although readme suggests one! Can you please look into it?Am I missing something?

**Comment by gpeal** [comment]
@GokulEpiphany sorry, this is confusing. It'll be released in 1.5 in the next day or two.

**Comment by GokulEpiphany** [comment]
No problem! just checked #136 and got a clearer picture!

**Comment by zeeeliza** [comment]
That's the problem I don't know how to view #136 I gave you my ph# why can't you just send it to my phone

**Comment by gpeal** [comment]
@GokulEpiphany 1.5.0 is out!

**Comment by GokulEpiphany** [comment]
@gpeal A big thanks 👍
