### ISSUE TITLE
Lottie is using too much Native memory 

### ISSUE THREAD

**Issue by pawan12soni** [airbnb/lottie-android#1431]
Hello,
I am using lottie animation on splash screen, When i remove lottie, the **Native** memory stays within 20 MB but when I add lottie animation the **Native** memory goes above 100 MB. How can I clear this memory Please help.

**Comment by gpeal** [comment]
If you are using a hardware accelerated animation, this will happen but isn't necessarily something to worry about too much. Try reducing masks and matte usage to improve things.
