### ISSUE TITLE
Lottie Animation rendering is not smooth on Android Device

### ISSUE THREAD

**Issue by akumar-atheer** [airbnb/lottie-android#1436]
**Describe the bug**
The animation rendering is different on Android device when compared to web based rendering.

**What version of Lottie did you test this on?**
Lottie Version 3.1.0

**What version of Android did you test this on?**
Android version 10 and Android 8.1
Tried with multiple devices and the behaviour is the same.

**Link to Lottie animation: https://lottiefiles.com/8374-sphere-loader**

**Video showing difference in behaviour across Web and Android app: https://drive.google.com/file/d/1p7vU59n-zjKIgwt8ttclpt00uqJbepWW/view?usp=sharing**

**Comment by gpeal** [comment]
@akumar-atheer Lottie doesn't support expressions
http://airbnb.io/lottie/#/supported-features
