### ISSUE TITLE
about support28 and lottie2.7.0

### ISSUE THREAD

**Issue by wangshaolei** [airbnb/lottie-android#1438]
I have a bug in version2.7.0( lottie java.util.List com.airbnb.lottie.model.content.ShapeData.getCurves NullPointerException)

and the bug fix 3.x version, but our project can't update androidx, and now is support28.

can I take my other ways? thanks~

**Comment by huage2580** [comment]
use this：3.0.3-support 
`com.airbnb.android:lottie:3.0.3-support`
Maybe this branch solved your problem.

**Comment by wangshaolei** [comment]
> use this：3.0.3-support
> `com.airbnb.android:lottie:3.0.3-support`
> Maybe this branch solved your problem.

hey,
thanks, and I try do it.
