### ISSUE TITLE
Pull to refresh example with reflection

### ISSUE THREAD

**Issue by eagskunst** [airbnb/lottie-android#1439]
** If you don't use this template, your issue will be closed **

**Is your feature request related to a problem? Please describe.**
I have found a way to add a LottieDrawable into the SwipeRefreshLayout circle. I would like to add it as an example. The downside I see is that I get the solution through reflection API.

**Describe the solution you'd like**
Add the example if there's no problem that it comes with reflection.

**Describe alternatives you've considered**
Making a custom view from 0. But would take more time and there are already some libraries that do the trick.

**Additional context**

**Comment by gpeal** [comment]
@eagskunst That's an issue you'll have to take up with the maintainer of `SwipeRefreshLayout`. Lottie can provide a drawable but it would be up to them to allow you to set it.
