### ISSUE TITLE
You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by xiaoyu0828** [airbnb/lottie-android#1444]
App crashes after import， Prompt missing theme

**Comment by gpeal** [comment]
I don't think this is related to Lottie.

**Comment by xiaoyu0828** [comment]
Because the theme in Lottie library conflicts with my app theme

**Comment by gpeal** [comment]
@xiaoyu0828 The lottie library doesn't have a theme

**Comment by xiaoyu0828** [comment]
First of all, thank you. There is no problem before importing the library. After importing, it can be compiled and cannot run

**Comment by gpeal** [comment]
@xiaoyu0828 Please follow the issue template for reporting a bug which will require enough information to debug your issue. Without it, there is nothing I can do.

**Comment by xiaoyu0828** [comment]
ok  thank  。

**Comment by JavohirYakubov** [comment]
how to fix this?

**Comment by JavohirYakubov** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{Activity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

**Comment by tomerpetel** [comment]
Seeing it in 6.0.0 as well. from the stackTrace we can see that the Theme for some reason doesn't hold the AppCompatTheme_windowActionBar value 

` private ViewGroup createSubDecor() {
        TypedArray a = mContext.obtainStyledAttributes(R.styleable.AppCompatTheme);

        if (!a.hasValue(R.styleable.AppCompatTheme_windowActionBar)) {
            a.recycle();
            throw new IllegalStateException(
                    **"You need to use a Theme.AppCompat theme (or descendant) with this activity.");**
        }
         ....`

It's started once I upgraded my Lottie lib from 4.2.1. to 6.0.0

**Comment by prudencioj** [comment]
Upgraded from 4.0.0 to 6.0.0 and I'm getting the same error.
@gpeal can you reopen this issue?

**Comment by gpeal** [comment]
@prudencioj I don't think this is Lottie related.

**Comment by tomerpetel** [comment]
@gpeal The only variable changed is the Lottie version. Any ideas how to proceed from here?

**Comment by gpeal** [comment]
Can you attach a project that reproduces this?
