### ISSUE TITLE
no animation effect in Huawei P30 pro

### ISSUE THREAD

**Issue by chenbangjie** [airbnb/lottie-android#1445]
We found that there is no animation effect in Huawei P30 pro 。

What version of Lottie did you test this on?
Lottie Version 3.2.2 and Lottie Version 3.1.0

What version of Android did you test this on?
Android version 9    EMUI 9.1.0
[Abnormal video](https://raw.githubusercontent.com/chenbangjie/bj/master/SVID_20191129_165719_1.mp4)

**Comment by gpeal** [comment]
@chenbangjie It looks like you have system animations disabled. Please reopen if that is not the case.

**Comment by xujinping** [comment]
LottieAnimationView.setIgnoreDisabledSystemAnimations(true)  isOk
