### ISSUE TITLE
How to load json animation from sdcard?

### ISSUE THREAD

**Issue by AlexMercier** [airbnb/lottie-android#1451]
How to load animation from json file on sdcard?
In sample app I found only one example, I folowed this code https://github.com/airbnb/lottie-android/blob/ee942249214dd6bb1540b746ca0b678a6382b5ee/LottieSample/src/main/kotlin/com/airbnb/lottie/samples/PreviewFragment.kt#L103 and this example brought me to one method and it related to `viewModel.fetchAnimation(args)`
but in sample I don't see what is the **viewModel**.  
Where can I found more clear sample for loading animation from file?

**Comment by gpeal** [comment]
@AlexMercier Get a FileInputStream to the animation file like [this](https://stackoverflow.com/a/15653817/715633) then usd `LottieCompositionFactory.fromJsonInputStream`

**Comment by AlexMercier** [comment]
@gpeal Thanks, And one question, how can I check if file already in cache? I use cache key but I must open stream every time before calling fromJsonInputStream.  I don't want to open file stream if file already is cached. I have recylcerview with animations and I think its a bad idea to open a file streams every time after user scrolled the list. So I want to reduce i/o operations to a minimum, only when I sure that file not in cache.

And one thing, I could be wrong but it's seems that stream not auto closed if file already in cache, method just return cache result and missing close a stream:(https://github.com/airbnb/lottie-android/blob/ee942249214dd6bb1540b746ca0b678a6382b5ee/lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java#L251

**Comment by gpeal** [comment]
@AlexMercier You can use the `LottieCompositionFactory` methods to hold your own reference to the composition if you'd like. That being said, you should measure the performance of opening the input stream without doing any reading. It may not be a problem in practice.
