### ISSUE TITLE
java.lang.NullPointerException  LottieComposition.getBounds()' on a null object reference

### ISSUE THREAD

**Issue by wangyudong211** [airbnb/lottie-android#1452]
Lottie 2.7.0

Android7.0 and Android9.0 

java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Rect com.airbnb.lottie.LottieComposition.getBounds()' on a null object reference
com.airbnb.lottie.LottieDrawable.float getMaxScale(android.graphics.Canvas)(LottieDrawable.java:929)
com.airbnb.lottie.LottieDrawable.void draw(android.graphics.Canvas)(LottieDrawable.java:289)
android.widget.ImageView.onDraw(ImageView.java:1432)
android.view.View.draw(View.java:20483)
android.view.View.buildDrawingCacheImpl(View.java:19696)
android.view.View.buildDrawingCache(View.java:19550)
android.view.View.draw(View.java:20203)
android.view.ViewGroup.drawChild(ViewGroup.java:4394)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
android.view.View.updateDisplayListIfDirty(View.java:19285)
android.view.View.draw(View.java:20211)
android.view.ViewGroup.drawChild(ViewGroup.java:4394)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
android.view.View.draw(View.java:20486)
android.view.View.updateDisplayListIfDirty(View.java:19294)
android.view.View.draw(View.java:20211)
android.view.ViewGroup.drawChild(ViewGroup.java:4394)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
android.view.View.draw(View.java:20486)
android.view.View.updateDisplayListIfDirty(View.java:19294)
android.view.View.draw(View.java:20211)
android.view.ViewGroup.drawChild(ViewGroup.java:4394)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
android.view.View.updateDisplayListIfDirty(View.java:19285)
android.view.View.draw(View.java:20211)
android.view.ViewGroup.drawChild(ViewGroup.java:4394)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
android.view.View.draw(View.java:20486)
com.android.internal.policy.DecorView.draw(DecorView.java:928)
android.view.View.updateDisplayListIfDirty(View.java:19294)
android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:740)
android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:746)
android.view.ThreadedRenderer.draw(ThreadedRenderer.java:861)
android.view.ViewRootImpl.draw(ViewRootImpl.java:3586)
android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3382)
android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2714)
android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
android.view.Choreographer.doCallbacks(Choreographer.java:893)
android.view.Choreographer.doFrame(Choreographer.java:812)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
android.os.Handler.handleCallback(Handler.java:907)
android.os.Handler.dispatchMessage(Handler.java:105)
android.os.Looper.loop(Looper.java:216)
android.os.HandlerThread.run(HandlerThread.java:65)

We have not experienced this problem in the main process, and this problem has occurred in another process

**Comment by wangyudong211** [comment]
not necessarily happen

**Comment by gpeal** [comment]
This is an extremely old version of Lottie. Please upgrade.
