### ISSUE TITLE
Animation unexpectedly is interrupted

### ISSUE THREAD

**Issue by dimakasilov** [airbnb/lottie-android#1454]
**Describe the bug**
I have project, a mobile app for which I recently created a download screen animation. In ios everything works as it should, and in android there were problems with one of the elements of animation.

The animation contains a pattern that should be smoothly shaded in blue. All design consists of a pattern and a blue circle, the pattern is a mask for a circle, the circle increases from 0% to 100% for several seconds and this blue pattern has to be visible until the end of animation. The pattern I drew in Illustrator and exported to after effects, there created a blue circle for which the pattern made a mask. As a result, after exporting the json file, the pattern begins to paint blue and is interrupted on the middle of the animation, just disappearing.

For the experiment I created arbitrary figures and red circle, arbitrary figures I made mask for red circle and after rendering these figures are painted red as I need to.

In animation, I used Alpha Matte to create a mask. I checked supported features, Alpha Matte is supported. I think the problem is the pattern, but I don 't know what 's wrong with it, please tell me. In all animation I have 2 such patterns, this one works quite badly, and the other little. Help us find a solution.

The question is why does the pattern disappear on half the animation, and the arbitrary figures drawn in after effects work normally?!

I attached the file source after effects, json file and video as the animation should work and how it works on android (samsung galaxy s8).

Please respond as soon as possible because in a few days launch the application in the play market. Thank you.

**What version of Lottie did you test this on?**
Version: 5.5.2

**What version of Android did you test this on?**
9

**Steps To Reproduce**

1. Download json file to android phone
2. Watch the animation interrupt

**Screenshots**
Ae, json
 and video: https://drive.google.com/open?id=1-VtUX0Sm16UvDa1VCKWcNTbIjo6pJ658

**Comment by gpeal** [comment]
@dimakasilov Did you delete the files off of Drive?
