### ISSUE TITLE
Crash on parsing color (please check string length before call Color.parseColor)

### ISSUE THREAD

**Issue by legion-zver** [airbnb/lottie-android#1455]
<img width="719" alt="Снимок экрана 2019-12-06 в 00 10 20" src="https://user-images.githubusercontent.com/12369572/70274306-f3cfe500-17bc-11ea-87a9-6cfbb0496be0.png">

<img width="558" alt="Снимок экрана 2019-12-06 в 00 11 52" src="https://user-images.githubusercontent.com/12369572/70274337-034f2e00-17bd-11ea-9294-1bfcefb179e2.png">

Lottie-android v3.3.0

**Comment by gpeal** [comment]
Please follow the issue
