### ISSUE TITLE
MultipleText not display properly as Y-position (Anchor Point Issue).

### ISSUE THREAD

**Issue by axitasavani** [airbnb/lottie-android#1459]
** If you don't use this template, your issue will be closed **

**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Describe the bug**
I have used simple text to write a single line and multiple line demo for text animation but is that problem to display with given alignment like center, left, right position also text of X-position is perfect but Y-position is not displayed properly.

**What version of Lottie did you test this on?**
3.3.0

**What version of Android did you test this on?**
All Android OS (5,6,7,8,9)

**Steps To Reproduce**

1. Just set animation on view and display error.
2.here is the animation file : 

[zip.zip](https://github.com/airbnb/lottie-android/files/3943030/zip.zip)

**Screenshots**

**1) mobile screenshot** 

![image](https://user-images.githubusercontent.com/44259547/70494691-464d3080-1b32-11ea-909b-13929be39492.png)

**2) an original screenshot of simple SingleText and Multiple Text .and given alignment** 

![image](https://user-images.githubusercontent.com/44259547/70494779-a17f2300-1b32-11ea-88af-f79313fbb602.png)

**3)here, this screenshot is compared to the two images.**

![image](https://user-images.githubusercontent.com/44259547/70494923-1f432e80-1b33-11ea-9693-ed5cd5e51785.png)

**Now, Can you please tell me what is the problem to not properly display Y-position in animation.** 

*Lottie is supported and developed on nights and weekends. Please consider [sponsoring Lottie](https://github.com/users/gpeal/sponsorship) to prioritize this issue and help support this issue as well as future investments.*

**Comment by gpeal** [comment]
Fixed by https://github.com/airbnb/lottie-android/pull/2162
