### ISSUE TITLE
Lottie 3.3.0     is no display in onAnimationEnd

### ISSUE THREAD

**Issue by wojiaojay123** [airbnb/lottie-android#1465]
animation.setAnimationListener(new Animation.AnimationListener() {
                @Override
                public void onAnimationStart(Animation animation) {

                }

                @Override
                public void onAnimationEnd(Animation animation) {
                    lottie.playAnimation();
                }

                @Override
                public void onAnimationRepeat(Animation animation) {

                }
}

**Comment by gpeal** [comment]
@wojiaojay123 Please create a repro in the issue-repro module

**Comment by gpeal** [comment]
@wojiaojay123 I just tried this in the issue-repro module and it worked for me. Please follow the full issue template for support.
