### ISSUE TITLE
Lottie intermittently does not start my animation

### ISSUE THREAD

**Issue by mkano9** [airbnb/lottie-android#1468]
**Describe the bug**
Version 3.3.1.
The animation from `setAnimation(...)` sometimes does not start. 

Here is my code upon click events:

    cancelAnimation()
    if (turnOn) {
        progress = 0f // I want the animation to restart from the beginning
        setAnimation(R.raw.lottie_turned_on)
        playAnimation()
    } else {
         setImageResource(R.drawable.ic_turned_off)
    }

After looking deeper into this, I believe there is a racing condition. Below is the flow I observed.

So in LottieAnimationView https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java, 

Inside the `setAnimation(resId)` method, it instantiates a `LottieTask` which executes a `LottieFutureTask` asynchronously to retrieve a cached composition. While this future task is executing to fetch a `result`, `setAnimation(resId)` proceeds to call `setCompositionTask(task);`. This method updates the reference of `this.compositionTask` to the new `task` after chaining a method call to `.addListener(loadedListener)`. 

In the `addListener(...)` method, it triggers a listener callback immediately if `result` already exists.

    if (result != null && result.getValue() != null) {
      listener.onResult(result.getValue());
    }

The `listener.onResult(...)` then triggers a method call to `setComposition(...)` which performs the rendering. Inside `setComposition(...)`, there is this condition that early-exits the method. 

    boolean isNewComposition = lottieDrawable.setComposition(composition);
    enableOrDisableHardwareLayer();
    if (getDrawable() == lottieDrawable && !isNewComposition) {
      // We can avoid re-setting the drawable, and invalidating the view, since the composition
      // hasn't changed.
      return;
    }

Lastly, `setComposition(...)` method leads to `onVisibilityChanged(...)` to start/resume the animation if it's ready to.

Here is the problem. 
If the future task completes before the `addListener(...)` method is called, the `if (result != null && result.getValue() != null)` condition becomes true and immediately triggers `setComposition(...)` which is supposed to lead to rendering the animation, but it won't yet because the conditions in `onVisibilityChanged(...)` won't resume the animation. Then when the second (the expected one) call to `setComposition(...)` gets called, it will just early-exit the method because the `composition` has already been set from last time even though it didn't resume the animation.

Any ideas?

**Steps To Reproduce**
It happens intermittently, so I couldn't found a way to reproduce every time. From my experience, it seems more likely to reproduce if you try it on an emulator or low-end device. It happens very rarely maybe in about once in <20 attempts.

I haven't been able to reproduce it on a little sample app project :/ I wonder if it has to with the sample app being too light.

**Comment by gpeal** [comment]
@mkano9 Is your code running on a different thread?
You can simulate slow points around the code by inserting
```
try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
    }
```
Can you try to reproduce it in the issue-repro module to determine where exactly the race condition is?

**Comment by mkano9** [comment]
> Is your code running on a different thread?
No, I'm no doing anything special with threads, so my code is on the main thread.

> Can you try to reproduce it in the issue-repro module to determine where exactly the race condition is?
I simulated my theory by inserting a thread sleep, but the animation runs without problems on the repro module. So looks like hitting the early return statement in `onVisibilityChanged(...)` when `isShowing()` is false is not what causes problems. 
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L299

Can you think of any wild theories why it may not animate in this scenario?

**Comment by gpeal** [comment]
@mkano9 I can't right now and I'd be happy to take a look if you can help narrow down a repro. I haven't heard any other reports of this though.

**Comment by mkano9** [comment]
Sounds good, thanks. I decided to go with AnimatedVectorDrawable for now. I will look into it again if I come across the same issue next time I use Lottie.
