### ISSUE TITLE
Assets question

### ISSUE THREAD

**Issue by xgear-public** [airbnb/lottie-android#147]
After updating on 1.5.0 version i have got 

>   java.lang.RuntimeException: An error occurred while executing doInBackground()
>                                                                         at android.os.AsyncTask$3.done(AsyncTask.java:325)
>                                                                         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
>                                                                         at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
>                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:242)
>                                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
>                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
>                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
>                                                                         at java.lang.Thread.run(Thread.java:761)
>                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.json.JSONArray.length()' on a null object reference
>                                                                         at com.airbnb.lottie.LottieComposition$Factory.parseImages(LottieComposition.java:238)
>                                                                         at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(LottieComposition.java:202)
>                                                                         at com.airbnb.lottie.LottieComposition$Factory.fromInputStream(LottieComposition.java:167)
>                                                                         at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java:17)
>                                                                         at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java:7)
>                                                                         at android.os.AsyncTask$2.call(AsyncTask.java:305)
>                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>                                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
>                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
>                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
>                                                                         at java.lang.Thread.run(Thread.java:761) 

because my json animation file doesn't have. **"assets"**:[] array. After manual modification of json file (I added empty **"assets"** array) crash was fixed. NPE is connected with 
`JSONArray assetsJson = json.optJSONArray("assets");`
Do you assume json file must have **"assets"** array (at least empty array)?

**Comment by gpeal** [comment]
@xgear-public Can you attach your AE file?

**Comment by xgear-public** [comment]
Sorry, but i can't. Designer said that he just don't use precompositions and image assets.

**Comment by gpeal** [comment]
@xgear-public Understood if you can't attach your production ae files but can your designer make one that repros his issue? Maybe he can delete everything except what's broken and then change the shape or something. Having a repro case will allow me to fix it.

**Comment by xgear-public** [comment]
Well, i don't think designer has some issues. My point is:
[LottieComposition](https://github.com/airbnb/lottie-android/blob/v1.0.3/lottie/src/main/java/com/airbnb/lottie/LottieComposition.java#L160) v 1.0.3
If json doesn't contain **"assets"** object array, JSONException e cought and everything is fine.
Now, in [LottieComposition](https://github.com/airbnb/lottie-android/blob/v1.5.0/lottie/src/main/java/com/airbnb/lottie/LottieComposition.java#L201) v1.5.0 optJSONArray method is used? and if json file doesn't have it - null returned, and then you pass it to [parseImages()](https://github.com/airbnb/lottie-android/blob/v1.5.0/lottie/src/main/java/com/airbnb/lottie/LottieComposition.java#L238) where NPE occurs.
int length = assetsJson.length();

**Comment by gpeal** [comment]
@xgear-public I can add the check but I'm curious as to why your json doesn't include an assets[] array.
