### ISSUE TITLE
Animation do not shows properly

### ISSUE THREAD

**Issue by mohammadbahadori99** [airbnb/lottie-android#1476]
Animation object don't rotate properly. for example check [this animation ](https://assets8.lottiefiles.com/packages/lf20_dhKO1k.json)
when i use this  in my android project, the fish shows up but it do not rotate and it move while it's fix.I'm using 3.3.1 version

**Comment by gpeal** [comment]
Duplicate of #1401

**Comment by NiHang** [comment]
I also encountered this problem, which version solved it?

**Comment by NahlaSaadAlDeen** [comment]
Any ideas, please?
