### ISSUE TITLE
How to recover last state of Json or Animation ?

### ISSUE THREAD

**Issue by axitasavani** [airbnb/lottie-android#1480]
**Read this or your issue will be closed**

Hi, 
I want to know that if I'll change the animation color like Shape color, So i want to know that is that any way to save that JSON or State because of that after animation color change i want to display the same color changed animation in next screen So.

can you please help me ?

**Comment by gpeal** [comment]
@axitasavani You'll need to set it up programmatically in your code. There is no way to write it back to the json file.
