### ISSUE TITLE
Android memory growth when loop="true"

### ISSUE THREAD

**Issue by gvozditskiy** [airbnb/lottie-android#1481]
I faced with growing memory consumption like it was described here #1141 #746 
Lg G5 with Android 6.0.1
Lottie version 3.0.7, 3.3.1
Sony xz2 Compact with Android 9.0 - everything is fine

**Comment by gpeal** [comment]
@gvozditskiy You're going to provide more information than that. Is it native heap or java heap? Can you capture a heap dump or use the Android Studio allocation tracker to determine the actual objects that are accumulating?

**Comment by gvozditskiy** [comment]
I am observing constantly increasing native heap.
There are heap dumps under the same conditions. Differences only in the loop parameter.
1.  app:lottie_loop="false"
![lottie-no-loop](https://user-images.githubusercontent.com/16043598/72416262-51295f80-3787-11ea-8d23-38c10a12caf1.png)
[dump](https://drive.google.com/file/d/1ywF8PApnS5PPultBW1vcCHCECtEDqr86/view?usp=sharing)

2. app:lottie_loop="true"
![lottie](https://user-images.githubusercontent.com/16043598/72416523-e2003b00-3787-11ea-94a6-0862b0157d83.png)
[dump](https://drive.google.com/file/d/14erRu80QpKyo6GVnVbId4bPqxycnbZMM/view?usp=sharing)

**Comment by gpeal** [comment]
@gvozditskiy Can you attach the animation that this is happening with? This isn't happening on any I have tested.

**Comment by gvozditskiy** [comment]
Sent to your email

**Comment by gpeal** [comment]
@gvozditskiy Here is the issue-repro app in the repro with your animation on repeat
hardware rendering:
![image](https://user-images.githubusercontent.com/1307745/75097322-6aa99c80-55ba-11ea-81df-aca0dcca2e85.png)
software rendering:
![image](https://user-images.githubusercontent.com/1307745/75097331-9462c380-55ba-11ea-960f-612f22b61ac4.png)

I'm certainly not seeing the kind of memory growth you are reporting. It's hard for me to diagnose this but if you are worried about it, you can use software rendering (which isn't always worse anyway).

I'm going to close this for now unless you can give more specific ways to reproduce or would like to look into it further yourself.

**Comment by gvozditskiy** [comment]
Seems like software rendering really solved our problem. Thank you.

**Comment by Gloud-Zhao** [comment]
I used "app:lottie_renderMode="software"" but still have the same problem
