### ISSUE TITLE
Click listener for objects playing in lottie view.

### ISSUE THREAD

**Issue by Pankti16** [airbnb/lottie-android#1487]
With lottie-web it is possible to add click listener, but how can I achieve the same in android.
For eg;
```anim = bodymovin.loadAnimation(animData);
anim.addEventListener('DOMLoaded', function(){

$("#hamburger").on("click", function () {
  anim.playSegments([[0,20]],true);
  $("#bodymovin").css("z-index", "4");
  $("#bodymovin").css("transition", "z-index 0s step-end, opacity 0s linear");
  $("#hamburger").css("display", "none");
  $("#hamburger").css("cursor", "default");
  });
})
```

**Comment by gpeal** [comment]
@Pankti16 Unfortunately there isn't a trivial way to do this right now and it isn't on the feature roadmap to add it. I would consider a PR but it might not be trivial to do without a lot of plumbing.
