### ISSUE TITLE
API 19 (Kitkat) LottieCompositionFactory.fromRawRes results in no visible animation without errors

### ISSUE THREAD

**Issue by StefanDeBruijn** [airbnb/lottie-android#1491]
Lottie version: 3.3.1
Android API 19 and above

LottieSwipeRefreshLayout (a 1 on 1 copy paste of `SwipeRefreshLayout `where  `mProgress`  (the circle progress indicator) is replaced with a Lottie animation) : https://gist.github.com/StefanDeBruijn/de1669fe548dd57cde661fbe299cb658

Lottie file: https://gist.github.com/StefanDeBruijn/c8bfceedcdbe856e3a6fcfd3c37580ee

While using the above LottieSwipeRefreshLayout within a ViewPager of 4 Fragments, only on specifically API 19 the animation would not load (see screenshot)

I found that the problem is fixed when using `fromRawResSync` rather than `fromRawRes` as per;

```
    private void createProgressView() {
        mCircleView = new CircleImageView(getContext(), CIRCLE_BG_LIGHT);
        mProgress = new LottieDrawable();
        LottieResult<LottieComposition> lottieResult = LottieCompositionFactory.fromRawResSync(getContext(), R.raw.pull_to_refresh);
        mProgress.setComposition(lottieResult.getValue());
        mProgress.setRepeatCount(LottieDrawable.INFINITE);
        mCircleView.setImageDrawable(mProgress);
        mCircleView.setVisibility(View.GONE);
        addView(mCircleView);
    }
```

There's 2 more strange things around this which lead me to believe this might be a bug around repeated usage of  `fromRawRes`: 

1. I've tried the same lottie json on a simple static Fragment in multiple ways (LottieAnimationView, ImageView with LottieDrawable, from assets and raw res) which worked fine
2. With the above described situation with the ViewPager, every now and then the animation would suddenly work on 1 out of 4 pages randomly (not always the same page) 🤔 

![image](https://user-images.githubusercontent.com/7021747/73356282-e5201e80-4291-11ea-9d71-60710cfe1a5c.png)

**Comment by gpeal** [comment]
@StefanDeBruijn If you have time to debug and put up a PR for this, that would be extremely helpful.

**Comment by gpeal** [comment]
If not, it would help me to fork the repo and create a reproduction in the issue-repro module so I don't have to manually set up a whole project and hope that it behaves the same way.

**Comment by StefanDeBruijn** [comment]
@gpeal I'll try to setup a new empty project for you to see the problem, going to take a bit of time though

**Comment by StefanDeBruijn** [comment]
Closing this as it contains a lot of unrelated info and opened a new more focussed ticket: 
https://github.com/airbnb/lottie-android/issues/1492
