### ISSUE TITLE
LottieCompositionFactory Async methods do not load animation on API < 24 when composition is set outside of LottieListener

### ISSUE THREAD

**Issue by StefanDeBruijn** [airbnb/lottie-android#1492]
Tested on APIs: 19, 21, 24 and 29
Lottie version: 3.3.1

This is a follow up issue for https://github.com/airbnb/lottie-android/issues/1491, since that contained info which turned out to be unrelated.

### The problem:
While creating this issue and the test project, I've discovered the real problem: 
I'm calling `setImageDrawable(lottieDrawable)` outside of the `LottieListener`. When moving this within the listener's callback, it works fine on all API levels tested.

I'll leave this test project and issue up, since it is strange how this approach works on api 24+ but not on api < 24 🤔 
I am happy to accept its a case of 'works as expected' though and for the ticket to simply be closed without further action.

Test project: https://github.com/StefanDeBruijn/TestLottieComposition

Screenshots:

| API 19        | API 21           | API 24           |
| ------------- |:-------------:| :-------------:| 
|![api19](https://user-images.githubusercontent.com/7021747/73447800-65f51e00-4357-11ea-8623-9aeaa5c0a7e6.png)|![api21](https://user-images.githubusercontent.com/7021747/73447804-67bee180-4357-11ea-9e2c-2365d2af7e2e.png)|![api24](https://user-images.githubusercontent.com/7021747/73447810-6988a500-4357-11ea-8bf2-2f4cbf36c032.png)|

Details about the test project:
All related code is found in `FirstFragment.kt`. 
Code that causes the error is marked with // FIXME

It loads both our custom Lottie animation (`pull_to_refresh.json`) and another random animation from LottieFiles (`control.json`), in various ways (`fromRawRes`, `fromRawResSync`, `fromAsset` and the standard XML way).

**Comment by gpeal** [comment]
@StefanDeBruijn I figured it out. The animation was, in fact, loading. However, only Marshmallow and above update drawable bounds every time it is invalidated.
