### ISSUE TITLE
the lotte file is being rendered correctly in the lotte preview section but when i'm trying to use that JSON file in android or IOS its not rendering similar to the preview section

### ISSUE THREAD

**Issue by doujin5** [airbnb/lottie-android#1496]
the lotte file is being rendered correctly in the lotte preview section in web but when I'm

 trying to use that JSON file in android or IOS it's not rendering similar to the preview section 
I'm attaching the preview link https://lottiefiles.com/share/Spqee4

when I'm using the JSON file in android the fade in yellow circle is not coming.

i have used the lotte version 3.0.0 on android

**Comment by gpeal** [comment]
@doujin5 Lottie doesn't support effects. Use a normal solid fill to achieve your animation here.
http://airbnb.io/lottie/#/supported-features
