### ISSUE TITLE
Lottie setAnimation from /raw can not replace

### ISSUE THREAD

**Issue by linhnguyen-idnow** [airbnb/lottie-android#1497]
I'm using Lottie 3.0.3-support.
I have a fragment to load animation from /raw folder with some json files. when onActivityCreated() call, I try to reset new animation file but It cannot work, It always keep the old one. I define some switch/ case to load difference animation. but when the first one call, and the rest cannot change to another animation even I display fragment by create the new fragment, not just reset animation by call setAnimation(). It's not happen when I apply resource from URL.

**Comment by linhnguyen-idnow** [comment]
Here is the code: 
@Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        switch (id) {
                case 1:
                    imageInstruction.setAnimation(R.raw.a1);
                    break;

                case 2:
                    imageInstruction.setAnimation(R.raw.a2);
                    break;
       }
}

**Comment by kathir-t** [comment]
@linhnguyen-idnow Did you solve the problem? If so, could you please post relevant information or code?
