### ISSUE TITLE
onAnimationEnd called twice when system animations are disabled

### ISSUE THREAD

**Issue by BoD** [airbnb/lottie-android#1500]
** If you don't use this template, your issue will be closed **

**Checklist**

1. Fork this repository into your account.
2. Reproduce your issue in the issue-repro module. Issues without a repro in the issue-repro 
   module may be auto-closed.

**Link to fork with a repro in the issue-repro module**
https://github.com/BoD/lottie-android/blob/master/issue-repro/src/main/java/com/airbnb/lottie/issues/MainActivity.kt

**Describe the bug**
When system animations are disabled, `onAnimationEnd` is called twice

**Steps To Reproduce**

- Call `setAnimation on` a `LottieAnimationView`
- Add an animation listener
- Disable system animations on the device
- Run the app and notice that `onAnimationEnd` is called twice

It is correctly called only once, when system animations are not disabled.

**Comment by gpeal** [comment]
@BoD It's because autoPlay is true in xml so the animation is getting played twice, once from auto play and once from your call to playAnimation.

**Comment by BoD** [comment]
Thanks for replying. However, how come this doesn't happen when system animations are not disabled?

**Comment by gpeal** [comment]
@BoD The second call noops because it is still playing.
