### ISSUE TITLE
how to support hardware acceleration

### ISSUE THREAD

**Issue by HJ-Money** [airbnb/lottie-android#151]
I want to know why is the reason that software acceleration is set to be default in stead of hardware acceleration. Further more, are these choice cause by compatible issues or else？

**Comment by bduncavage** [comment]
You can enable hardware acceleration yourself if you'd like. Just call setLayerType() on the LottieAnimationView and use LAYER_TYPE_HARDWARE. You might experience rendering issues on some devices though, which is why they probably use the software layer by default.

**Comment by 0legg** [comment]
Lottie uses some canvas operations that are unsupported by hardware accelerated views, or supported only in later versions of Android — you can find details [here](https://developer.android.com/guide/topics/graphics/hardware-accel.html#unsupported). 

By the way, I have an idea how partial hardware acceleration can be achieved:

1. We can know for sure from this table whether canvas operation is hardware accelerated or not.
1. We can create an interface `Accelerable` with only method `boolean isHardwareAccelerable` that will return `true` iff both all layers' children are hardware accelerable and layer itself doesn't use unsupported canvas methods (we can know it for sure from layer data).
1. Probably, there can be animation profiles introduced, where `baseline` stands for restricted set of actions, which are supported by hardware accelerated views, and advanced supports as much features as possible.
1. And, as the last step, we can instrument `LottieAnimationView` with method which helps do decide whether view should turn on acceleration or not (say, it's not accelerated by default, and accelerated iff it's explicitly set up to be accelerated and used animation can be accelerated).
1. Another way of supporting hardware acceleration will be just to drop unsupported methods, so rendering won't be precise copy of AE output, but it'll be accelerated.

@gpeal Any thoughts on my ideas?

**Comment by gpeal** [comment]
@0legg I would love to find a way to make Lottie hardware accelerated when it works. I spent some time investigating it earlier in the project but focused more on just getting feature "complete". I know the Facebook keyframes team had some issues with hardware acceleration where their animations would be inconsistently broken on some random devices that they were either not able to repro or fix and ended up just disabling it as a result.
That being said, it's worth investigating and if we can start to derive a set of hardware profiles based on the feature usage of a given composition and api level, I think that would be a fantastic addition to the project.

Masks and mattes would see a particular improvement because they leverage Canvas#saveLayer which is much faster with hardware acceleration.

**Comment by HJ-Money** [comment]
Thx! 
Here is my case. I have tried to play an slightly complicated animation which has images on Lottie. I can see the run out effect is much stable and faster with hardware acceleration. Most importantly, it dose not drop any frame and runs smoothly. Worth notice that there's obivous lag under software acceleration. Sincerely hope there's as approporate hardware acceleration method to apply on Lottie maybe just like 0legg said. 

Thx again!

**Comment by gpeal** [comment]
@HJ-Money and your animation rendered correctly with hardware acceleration?

**Comment by gpeal** [comment]
I just tried turning on hardware acceleration on LottieLogo2 and there are some nasty scaling artifacts. I'll have to look in to why these are happening.
![image](https://cloud.githubusercontent.com/assets/1307745/23290029/b5a7ff72-fa02-11e6-960d-fb55c5b3450a.png)

**Comment by HJ-Money** [comment]
@gpeal Yes, the effect rendered  with hardware acceleration is same as with software acceleration.On one hand, I guess the animtion maybe only use the api which can supported by hardware acceleration. On the other hand, I test my animtion on Android 6.0. And also, I modify the source code LottieComposition.fromJsonSync(), and I set scale = 1f, not by density which can result in twisted rendering in my case.

I test LottieLogo2 with hardware acceleration on my phone(Android 6.0), and it's effect looks like without 
Anti-aliasing  just like what you show.

BTW, my English is so poor, and maybe some points cannot be clarified clearly. Excuse me for any mistakes since my not-so-good English.

Thx for your reply!

**Comment by gpeal** [comment]
@HJ-Money Yeah you definitely don't want to change the composition scale. It won't do exactly what you expect. It's set to the density to the units of position in after effects get translatated to dp. Without that scale being the screen density, things will be off.

**Comment by jeliza1215** [comment]
He's  not going to compromise  his status with the hardware these choices are based upon years of studying the software, So therefore, the use of hardware is not the best choice to use

**Comment by jeliza1215** [comment]
other intrusion will be deleated!  emails changed by software, harddrive
 is now shutting down! Software is more powerful than you thought!

**Comment by gpeal** [comment]
The lack of anti aliasing support is really going to make this difficult. Layers that have scale anywhere up the parent tree are going to cause nasty scaling artifacts like in the screenshot above.
It is possible to optimize the animation itself to not do this but it would require some coordination between the designer and engineer.

**Comment by gpeal** [comment]
@0legg With 2.0.0 (2.0.0-beta1 is live now), hardware acceleration is better supported out of the box due to how the transformation matrices are applied. There is now a method on LottieAnimationView to enable hardware acceleration. It actually seemed to hurt performance in some cases for me and obviously some features aren't supported but feel free to experiment with it on your own animations.

Do you want more work done on this specific issue?

**Comment by HJ-Money** [comment]
@gpeal Hello, I come again.

Lottie 2.0 is very good, and it solved many problems. And I am still confused by some code.
At first, I found a promble in Image Animtion under hardware acceleration. From the Image Animtion demo (WeAccept.json), **I can see the Images under soft acceleration are bigger than which under hardware acceleration.**

![1](https://cloud.githubusercontent.com/assets/7287869/24072297/4bbdb676-0c20-11e7-8549-6c69130f3c59.png)

![2](https://cloud.githubusercontent.com/assets/7287869/24072300/510e0ba8-0c20-11e7-889b-563f190bb24c.png)

And it also happens in my cases which has images. I try to find the reason these days and I found the Images are scaled by density under soft acceleration. But I could not found the root cause of this.

However, I succeed in finding two ways to solve this issue.
**The first way** :
I modifyed the draw() method on class ImageLayer:

```
Rect mSrc = new Rect();
  Rect mDst = new Rect();
  int mDensity = context.getResources().getDisplayMetrics().density;

  @Override public void drawLayer(@NonNull Canvas canvas, Matrix parentMatrix, int parentAlpha) {
    String refId = layerModel.getRefId();
    Bitmap bitmap = lottieDrawable.getImageAsset(refId);
    if (bitmap == null) {
      return;
    }

    paint.setAlpha(parentAlpha);
    canvas.save();
    canvas.concat(parentMatrix);
    mSrc.set(0, 0, bitmap.getWidth(), bitmap.getHeight());
    mDst.set(0, 0, bitmap.getWidth() * mDensity, bitmap.getHeight() * mDensity);
    canvas.drawBitmap(bitmap, mSrc, mDst, paint);
    //canvas.drawBitmap(bitmap, 0, 0 , paint);
    canvas.restore();
  }
```

We can see 
`canvas.drawBitmap(bitmap, 0, 0 , paint);`
is the same effect as 
```
mSrc.set(0, 0, bitmap.getWidth(), bitmap.getHeight());
    mDst.set(0, 0, bitmap.getWidth() * mDensity, bitmap.getHeight() * mDensity);
    canvas.drawBitmap(bitmap, mSrc, mDst, paint);
```
under soft acceleration. It is very strange and Abnormal.






Before I clarify **the second way**, I have some questions about these code below in LottieComposition.fromJsonSync() :

`float scale = res.getDisplayMetrics().density;`

I want to know why scale is setted by density. This could be result in the animtion scaled by density even though the AnimView's witdh and hight are setttd to WRAP_CONTENT.In other words, the animtion is not the same size as what the designer has made.It is scaled by density.

I think it should be added a field mInDensity which represents density of the source animtion just like BitmapFactory.Options.inDensity in Android. And the animtion are scale by screen density and mInDensity so that it can solve the transform between dp and px.

So the second way is :

1.Add twos fields `mInDensity` and `mInDensityDpi`(160,320,480 and so on), and it should be setted before the animtion play.These parameters are known when the designer export the json or earlier.

2.Modify LottieComposition.fromJsonSync():

`float scale = res.getDisplayMetrics().density;`

should be changed to 

`float scale = res.getDisplayMetrics().density / mInDensity;`


3.Modify ImageAssetBitmapManager.bitmapForId():

`opts.inDensity = 160;`

should be changed to

`opts.inDensity = mInDensityDpi;`

Done.


But this way can cause another issue.The demo animtion 9squares-AIBoardman.json will be off. May be this is the situation you have mentioned on above reply "Without that scale being the screen density, things will be off".
This issue i think it is caused by these code in StrokeContent.draw() :
```
    if (paint.getStrokeWidth() < 1) {
      // Android draws a hairline stroke for 0, After Effects doesn't.
      return;
    }

```
I changed it to 

```
    if (paint.getStrokeWidth() <= 0) {
      // Android draws a hairline stroke for 0, After Effects doesn't.
      return;
    }
```

And it is ok for the demo animtions.

Above is my views, welcome to discuss,thx~

**Comment by gpeal** [comment]
@HJ-Money Thanks for the detailed breakdown.
 Some properties are scaled by density so that they look the same on all devices. Anything that is pixels in After Effects such as position becomes Dp in lottie. 

Your first solution worked (with some slight code cleanup).

**Comment by gpeal** [comment]
I'm going to close this issue. The sample app now has a menu option to toggle hardware acceleration if you want to try it. It significantly improves some animations but hurts others so use at your own discretion.
