### ISSUE TITLE
Strange bug !

### ISSUE THREAD

**Issue by flashiran1** [airbnb/lottie-android#1518]
hi I do not know what to say See the gif below

<img src="https://dl.dropboxusercontent.com/s/b2azwwbrqi8sz18/123.gif">

Library version: 3.3.0
Android version: API 21 Android 5.1.1
Support library version: Use AndroidX Verison appcompat:1.1.0 And material:1.2.0-alpha05
Device brand: Huawei
Device model: huawei p7-l10a

```xml

<androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/colorAccent2">

        <com.airbnb.lottie.LottieAnimationView
            android:id="@+id/animation_view"
            android:layout_width="0dp"
            android:layout_height="0dp"
            app:layout_constraintBottom_toTopOf="@+id/guideline"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="@+id/guideline222"
            app:lottie_autoPlay="true"
            app:lottie_loop="true"
            app:lottie_rawRes="@raw/data_white"
            app:lottie_scale="0.3" />
 </androidx.constraintlayout.widget.ConstraintLayout>
```

**Comment by flashiran1** [comment]
what happened ? Why close?

**Comment by gpeal** [comment]
You didn't attach any repro steps.

**Comment by flashiran1** [comment]
What should I do now to answer my question?

**Comment by flashiran1** [comment]
Everything is in the picture I followed these steps

**Comment by gpeal** [comment]
@flashiran1 I can't repro it without your animation.

**Comment by flashiran1** [comment]
This is my animation
https://dl.dropboxusercontent.com/s/ygey20vzd9y0rq5/data_white.json

**Comment by flashiran1** [comment]
@gpeal
Sorry Did you solve this problem?

**Comment by Liar1995** [comment]
I have the same problem. The animation will directly execute onanimationend() for the first time, and the second callback will not respond. Does this problem solve now? @flashiran1

**Comment by gpeal** [comment]
@flashiran1 What is your problem? The animation 404s.
