### ISSUE TITLE
New Feature Request: Add sound along with animations. 

### ISSUE THREAD

**Issue by ujjwalagrawal17** [airbnb/lottie-android#1519]
** If you don't use this template, your issue will be closed **

**Is your feature request related to a problem? Please describe.**
New Feature Request: 
I am developing an application for generating dynamic wedding videos. I want to display animations+dynamic texts+sound before generating actual videos if possible. Lottie seems to be a perfect fit but it doesn't have sound support yet. Can someone guide me how can I add it?

**Describe the solution you'd like**
Add sound along with animations. 

**Describe alternatives you've considered**
We are generating dynamic videos in server end and have not find any alternatives to do it in Android yet.

**Additional context**

*Lottie is supported and developed on nights and weekends. Please consider [sponsoring Lottie](https://github.com/users/gpeal/sponsorship) to prioritize this issue and help support this issue as well as future investments.*

**Comment by gpeal** [comment]
@ujjwalagrawal17 Unfortunately, this is not something we plan to support. You can set up listeners to tie this into your own code! You should be able to know just about anything you want from the animation with listeners.

**Comment by ujjwalagrawal17** [comment]
Thanks. I will try that out.

**Comment by 1wayticket** [comment]
you can try svga!

> Thanks. I will try that out.
