### ISSUE TITLE
onAnimationStart() not being called

### ISSUE THREAD

**Issue by alexandrebodi** [airbnb/lottie-android#1520]
On 3.3.0 (or 3.3.1), if I add an `AnimatorListener` to my `LottieAnimationView` using `addAnimatorListener()`, the callback `onAnimationStart()` is simply not invoked.

Which is quite unfortunate, since I need XML attribute `lottie_cacheComposition`, so I can't really use a version older than 3.3.0.

FYI, I'm setting up my animation source using `lottie_rawRes` *without* setting `lottie_autoPlay` (which, AFAIK defaults to **false**). And I call `playAnimation()` *after* I add my listener.

**Comment by gpeal** [comment]
@alexandrebodi It just worked for me in my testing. Please reopen this with a repro in the issue-repro module if you can reproduce it.

**Comment by alexandrebodi** [comment]
Thanks for the quick reply, Gabriel. I tested it using release 3.4.0 and it's working again. Best regards.
