### ISSUE TITLE
Add support for defStyleAttr to LottieAnimationView

### ISSUE THREAD

**Issue by ataulm** [airbnb/lottie-android#1523]
**Is your feature request related to a problem? Please describe.**

`LottieAnimationView` provides the 3-arg view constructor, which allows passing a `defStyleAttr` from a subclass (e.g. `MyLoadingSpinnerView`), but doesn't use it.

This means that any `LottieAnimationView`-specific attributes will not be read from a default style.

**Describe the solution you'd like**

Pass the `defStyleAttr` to the `init` function, and pass it when [obtaining styled attributes](https://developer.android.com/reference/android/content/Context#obtainStyledAttributes(android.util.AttributeSet,%20int%5B%5D,%20int,%20int)):

```java
private void init(@Nullable AttributeSet attrs, @AttrRes int defStyleAttr) {
    TypedArray ta = getContext().obtainStyledAttributes(attrs, R.styleable.LottieAnimationView, defStyleAttr, 0);
    if (!isInEditMode()) {
        boolean hasRawRes = ta.hasValue(R.styleable.LottieAnimationView_lottie_rawRes);
        ...
```

**Describe alternatives you've considered**

Applying the style explicitly in the layout every time:

```kotlin
<MyLoadingSpinnerView
    style="@style/Widget.MyApp.MyLoadingSpinnerView"
    android:layout_width="40dp"
    android:layout_height="40dp" />
```

**Additional context**

Happy to do a PR if this issue is accepted!

*Lottie is supported and developed on nights and weekends. Please consider [sponsoring Lottie](https://github.com/users/gpeal/sponsorship) to prioritize this issue and help support this issue as well as future investments.*

**Comment by gpeal** [comment]
@ataulm I would accept a PR for this!
