### ISSUE TITLE
Is there a possible to provide api to slow down frame rate?

### ISSUE THREAD

**Issue by rantianhua** [airbnb/lottie-android#1527]
There is an animation running all the time in my app, lottie will cost most of the cpu time. In my Samsung 5.1(3 cpu),  it's easily to consume over 120% cpu and then it's easy to cause ANR because of other events cannot get cpu time.

**Describe the solution you'd like**
Optimize the output json file makes no much effect, so i wonder know that is there a possible to provide an api to slow down the frame rate so that release more cpu time.

**Describe alternatives you've considered**
Noop.

**Additional context**
Json File : 
[Uploading bell_ground_normal.json.zip…]()

**Comment by gpeal** [comment]
@rantianhua Most animations run pretty efficiently. You have a few options:
1) Turn on hardware rendering. That will make the animations not run on the ui thread.
2) Optimize your animation. Check out the [performance docs](http://airbnb.io/lottie/#/android?id=performance). Things like masks and mattes have a major impact on performance.
3) Write your own animator. You can use the setProgress API and write your own animator to drive animations at whatever rate you'd like. I recommend one of the previous options but this would be a better last resort than Lottie including this out of the box.
