### ISSUE TITLE
Found a crash, v3.4.0 android 7.0

### ISSUE THREAD

**Issue by hu03ping** [airbnb/lottie-android#1533]
java.lang.IllegalArgumentException
Underflow in restoreToCount - more restores than saves
0 | Native Methodandroid.graphics.Canvas.native_restoreToCount
-- | --
1 | Canvas.java line 548android.graphics.Canvas.restoreToCount
2 | LottieDrawable.java line 1224com.airbnb.lottie.LottieDrawable.drawWithOriginalAspectRatio
3 | LottieDrawable.java line 380com.airbnb.lottie.LottieDrawable.drawInternal
4 | LottieDrawable.java line 370com.airbnb.lottie.LottieDrawable.draw
5 | ImageView.java line 1286android.widget.ImageView.onDraw
6 | View.java line 17119android.view.View.draw
7 | View.java line 16094android.view.View.updateDisplayListIfDirty
8 | View.java line 16885android.view.View.draw
9 | ViewGroup.java line 3777android.view.ViewGroup.drawChild
10 | ViewGroup.java line 3563android.view.ViewGroup.dispatchDraw
11 | View.java line 16089android.view.View.updateDisplayListIfDirty
12 | ViewGroup.java line 3761android.view.ViewGroup.recreateChildDisplayList
13 | ViewGroup.java line 3741android.view.ViewGroup.dispatchGetDisplayList
14 | View.java line 16057android.view.View.updateDisplayListIfDirty
15 | ViewGroup.java line 3761android.view.ViewGroup.recreateChildDisplayList
16 | ViewGroup.java line 3741android.view.ViewGroup.dispatchGetDisplayList
17 | View.java line 16057android.view.View.updateDisplayListIfDirty
18 | ViewGroup.java line 3761android.view.ViewGroup.recreateChildDisplayList
19 | ViewGroup.java line 3741android.view.ViewGroup.dispatchGetDisplayList
20 | View.java line 16057android.view.View.updateDisplayListIfDirty
21 | ViewGroup.java line 3761android.view.ViewGroup.recreateChildDisplayList
22 | ViewGroup.java line 3741android.view.ViewGroup.dispatchGetDisplayList
23 | View.java line 16057android.view.View.updateDisplayListIfDirty
24 | ViewGroup.java line 3761android.view.ViewGroup.recreateChildDisplayList
25 | ViewGroup.java line 3741android.view.ViewGroup.dispatchGetDisplayList
26 | View.java line 16057android.view.View.updateDisplayListIfDirty
27 | ViewGroup.java line 3761android.view.ViewGroup.recreateChildDisplayList
28 | ViewGroup.java line 3741android.view.ViewGroup.dispatchGetDisplayList
29 | View.java line 16057android.view.View.updateDisplayListIfDirty
30 | ViewGroup.java line 3761android.view.ViewGroup.recreateChildDisplayList
31 | ViewGroup.java line 3741android.view.ViewGroup.dispatchGetDisplayList
32 | View.java line 16057android.view.View.updateDisplayListIfDirty
33 | ViewGroup.java line 3761android.view.ViewGroup.recreateChildDisplayList
34 | ViewGroup.java line 3741android.view.ViewGroup.dispatchGetDisplayList
35 | View.java line 16057android.view.View.updateDisplayListIfDirty
36 | ViewGroup.java line 3761android.view.ViewGroup.recreateChildDisplayList
37 | ViewGroup.java line 3741android.view.ViewGroup.dispatchGetDisplayList
38 | View.java line 16057android.view.View.updateDisplayListIfDirty
39 | ViewGroup.java line 3761android.view.ViewGroup.recreateChildDisplayList
40 | ViewGroup.java line 3741android.view.ViewGroup.dispatchGetDisplayList
41 | View.java line 16057android.view.View.updateDisplayListIfDirty
42 | ViewGroup.java line 3761android.view.ViewGroup.recreateChildDisplayList
43 | ViewGroup.java line 3741android.view.ViewGroup.dispatchGetDisplayList
44 | View.java line 16057android.view.View.updateDisplayListIfDirty
45 | ViewGroup.java line 3761android.view.ViewGroup.recreateChildDisplayList
46 | ViewGroup.java line 3741android.view.ViewGroup.dispatchGetDisplayList
47 | View.java line 16057android.view.View.updateDisplayListIfDirty
48 | ViewGroup.java line 3761android.view.ViewGroup.recreateChildDisplayList
49 | ViewGroup.java line 3741android.view.ViewGroup.dispatchGetDisplayList
50 | View.java line 16057android.view.View.updateDisplayListIfDirty
51 | ViewGroup.java line 3761android.view.ViewGroup.recreateChildDisplayList
52 | ViewGroup.java line 3741android.view.ViewGroup.dispatchGetDisplayList
53 | View.java line 16057android.view.View.updateDisplayListIfDirty
54 | ThreadedRenderer.java line 657android.view.ThreadedRenderer.updateViewTreeDisplayList
55 | ThreadedRenderer.java line 663android.view.ThreadedRenderer.updateRootDisplayList
56 | ThreadedRenderer.java line 771android.view.ThreadedRenderer.draw
57 | ViewRootImpl.java line 2833android.view.ViewRootImpl.draw
58 | ViewRootImpl.java line 2641android.view.ViewRootImpl.performDraw
59 | ViewRootImpl.java line 2248android.view.ViewRootImpl.performTraversals
60 | ViewRootImpl.java line 1268android.view.ViewRootImpl.doTraversal
61 | ViewRootImpl.java line 6350android.view.ViewRootImpl$TraversalRunnable.run
62 | Choreographer.java line 871android.view.Choreographer$CallbackRecord.run
63 | Choreographer.java line 683android.view.Choreographer.doCallbacks
64 | Choreographer.java line 619android.view.Choreographer.doFrame
65 | Choreographer.java line 857android.view.Choreographer$FrameDisplayEventReceiver.run
66 | Handler.java line 751android.os.Handler.handleCallback
67 | Handler.java line 95android.os.Handler.dispatchMessage
68 | Looper.java line 154android.os.Looper.loop
69 | ActivityThread.java line 6217android.app.ActivityThread.main
70 | Native Methodjava.lang.reflect.Method.invoke
71 | ZygoteInit.java line 885com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
72 | ZygoteInit.java line 775com.android.internal.os.ZygoteInit.main

**Comment by gpeal** [comment]
Please reopen this issue with reproduction steps and the animation that is crashing.

**Comment by jcdhlzq** [comment]
@hu03ping hello, have you solved this problem?
i've met the problem in huawei Q with lottie3.0.0

**Comment by Kingsavage3** [comment]
No stop to all

**Comment by Kingsavage3** [comment]
Stop

**Comment by Kingsavage3** [comment]
Stop

**Comment by Kingsavage3** [comment]
Stop

**Comment by Kingsavage3** [comment]
Unscrew subscribe
