### ISSUE TITLE
Memory Leak happends with OnCompositionLoadedListener

### ISSUE THREAD

**Issue by ouyangpeng** [airbnb/lottie-android#1535]
lottie version： 2.2.5 
problems：I found a memory leak in my team's project when using lottie .

using Android studio profile check the memory leak 

![image](https://user-images.githubusercontent.com/5885735/77406880-470f8700-6df0-11ea-9221-b4898268ac3c.png)

by MAT:
![image](https://user-images.githubusercontent.com/5885735/77406794-25ae9b00-6df0-11ea-9cee-beecc2f3b79c.png)

the source of LoadingPupWindowHolder：
![image](https://user-images.githubusercontent.com/5885735/77406955-61496500-6df0-11ea-8287-56dc07cc67ec.png)

using the method of `com.airbnb.lottie.LottieComposition.Factory#fromAssetFileName`
```java
/**
     * Loads a composition from a file stored in /assets.
     */
    public static Cancellable fromAssetFileName(Context context, String fileName,
        OnCompositionLoadedListener loadedListener) {
      InputStream stream;
      try {
        stream = context.getAssets().open(fileName);
      } catch (IOException e) {
        throw new IllegalStateException("Unable to find file " + fileName, e);
      }
      return fromInputStream(context, stream, loadedListener);
    }

    /**
     * Loads a composition from an arbitrary input stream.
     * <p>
     * ex: fromInputStream(context, new FileInputStream(filePath), (composition) -> {});
     */
    public static Cancellable fromInputStream(Context context, InputStream stream,
        OnCompositionLoadedListener loadedListener) {
      FileCompositionLoader loader =
          new FileCompositionLoader(context.getResources(), loadedListener);
      loader.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR, stream);
      return loader;
    }
```

FileCompositionLoader

```java
package com.airbnb.lottie.model;

import android.content.res.Resources;

import com.airbnb.lottie.LottieComposition;
import com.airbnb.lottie.OnCompositionLoadedListener;

import java.io.InputStream;

public final class FileCompositionLoader extends CompositionLoader<InputStream> {
  private final Resources res;
  private final OnCompositionLoadedListener loadedListener;

  public FileCompositionLoader(Resources res, OnCompositionLoadedListener loadedListener) {
    this.res = res;
    this.loadedListener = loadedListener;
  }

  @Override protected LottieComposition doInBackground(InputStream... params) {
    return LottieComposition.Factory.fromInputStream(res, params[0]);
  }

  @Override protected void onPostExecute(LottieComposition composition) {
    loadedListener.onCompositionLoaded(composition);
  }
}

```

i think   this loadedListener cause the memory leak ,how to solve it?

![image](https://user-images.githubusercontent.com/5885735/77407211-c1d8a200-6df0-11ea-93a2-d20d26240ff3.png)

**Comment by gpeal** [comment]
This version is extremely old. Please reopen if this happens on 3.4.0

**Comment by ouyangpeng** [comment]
lottie 2.2.5 
![image](https://user-images.githubusercontent.com/5885735/77493713-be8bf780-6e7e-11ea-8d95-b3c9f7942cf8.png)

------

lottie 3.3.1 
![image](https://user-images.githubusercontent.com/5885735/77493778-f1ce8680-6e7e-11ea-8ecb-c64ed5fef3e4.png)

add Listener
![image](https://user-images.githubusercontent.com/5885735/77493784-f7c46780-6e7e-11ea-9b99-166ec460047b.png)

remove Listener
![Uploading image.png…]()

ListenerAdapter
![image](https://user-images.githubusercontent.com/5885735/77493748-d8c5d580-6e7e-11ea-969c-29389ed4ea90.png)

------

It seems to be fixed , the listener can be removed .
