### ISSUE TITLE
Adding dependency failed

### ISSUE THREAD

**Issue by AbhiAndroidManiac** [airbnb/lottie-android#1536]
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not download lottie.aar (com.airbnb.android:lottie:3.0.0)
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not download lottie.aar (com.airbnb.android:lottie:3.0.0)
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not download lottie.aar (com.airbnb.android:lottie:3.0.0)
Show Details
Affected Modules: app

**Comment by gpeal** [comment]
@AbhiAndroidManiac I don't think this is an issue with the library itself, likely with your own internet. 
Also, 3.4.0 is the latest version.
