### ISSUE TITLE
animation balls not reaching below their starting point

### ISSUE THREAD

**Issue by drorsun** [airbnb/lottie-android#154]
The attached aftereffect json [feed_loader.json.zip](https://github.com/airbnb/lottie-android/files/796306/feed_loader.json.zip) holds animation that takes 3 balls, bounces them up and then down below their starting point and then back up to the starting point.

The actual result fails to move those balls below their starting point, thus looking less springy and cool.
Perhaps this is a problem with negative values in the json file - but notice that I have zero understanding of that format.

Attaching also a gif that shows how this animation should have looked like:

![loader_00](https://cloud.githubusercontent.com/assets/10059165/23258937/4e512d50-f9d3-11e6-91ba-c5de5f174020.gif)

Thanks 
Dror

**Comment by therealsalih** [comment]
Hi @drorsun can you attach the AE file? Thanks!

**Comment by gpeal** [comment]
@drorsun Just took a look at your json file and it looks like you're using an expression. Unfortunately we don't yet support expressions. You should be able to achieve this without expressions though.

**Comment by drorsun** [comment]
ok, thanks. will check how to make it without expressions.
