### ISSUE TITLE
Unexpected keyword 'const' in strict mode / Lottie Player

### ISSUE THREAD

**Issue by peterlinkt** [airbnb/lottie-android#1540]
iMac Retina 4k late 2015
OSX El Capitan
Browser safari: version 9.1.2 (11601.7.7)

The Lottie animation works fine in different browser desktop/mobile. I only have a problem with Safari who gives:
unexpected keyword 'const' in strict mode
lottie-player.js is called from cdn '<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>'

<img width="726" alt="Schermafbeelding 2020-04-05 om 15 09 47" src="https://user-images.githubusercontent.com/5982884/78499201-95594a00-774f-11ea-9214-5216247b466c.png">

**Comment by gpeal** [comment]
I think you posted this in the wrong project. This repo is for the Android library only.
