### ISSUE TITLE
potential NPE issues in LinkedHashTreeMap.java

### ISSUE THREAD

**Issue by HermioneSW** [airbnb/lottie-android#1541]
Hi,
We are developing a new static analysis tool for catching bugs in Java code. Upon scanning your codebase we find the following:

In ```LinkedHashTreeMap.java``` (/lottie/src/main/java/com/airbnb/lottie/parser/moshi/LinkedHashTreeMap.java) ```rebalance``` function at line 338, we guess ```right``` can be a null since it is checked in```int rightHeight = right != null ? right.height : 0;``` at line 343, If it is indeed the case, then ```Node<K, V> rightLeft = right.left;``` and ```Node<K, V> rightRight = right.right;``` may throw a NPE at line 347 and 348.

Would you please take a look and confirm this is indeed a bug? Thanks a million!!!

**Comment by gpeal** [comment]
@HermioneSW This was [copied from Moshi](https://github.com/square/moshi/blob/master/moshi/src/main/java/com/squareup/moshi/LinkedHashTreeMap.java). We never never seen this cause any issues here and it would likely have been fixed at some point in the last 3 years if it caused an issue now.

I'm going to close this unless it presents itself in the real world. You may open an issue on their repo if you believe it should be fixed though.
