### ISSUE TITLE
LottieDrawable setBounds() method does not scale or position drawable

### ISSUE THREAD

**Issue by ashankar12** [airbnb/lottie-android#1542]
**Description:**
`LottieDrawable` does not scale or position when the `setBounds(left, top, right, bottom)` is called when the drawable is explicitly instantiated outside of a view and drawn directly to the Canvas using an onDraw() call. I am not using `LottieAnimationView` (and my use case requires it to be this way).

Android [drawables](https://developer.android.com/reference/android/graphics/drawable/Drawable) are expected to follow setBounds and scale accordingly.

**Lottie Version**
3.4.0

**Android Version**
29.0.3

**Steps To Reproduce**

_Code_
```
drawable = LottieDrawable()
var composition = LottieCompositionFactory.fromJsonStringSync(res, "") // res is any animation as JSON string
drawable.setComposition(composition.value)
//            var drawableWidth = composition.value?.bounds?.width()
//            drawable.scale = 0.5f
drawable.setBounds(0, 0, 100, 100) // Does nothing for positioning and scaling
drawable.repeatCount = LottieDrawable.INFINITE
drawable.playAnimation()

...
...

drawable.draw(canvas)
```

The animation fires and update handlers work as expected. However, the positioning and scaling is incorrect. I can manually scale the drawable by calling `setScale()`.

However, if I do the same thing using a `LottieAnimationView` and set its layout, the animation is scaled and positioned correctly.

This issue is reproducible with any Lottie Animation file.

**Comment by WinKawaks** [comment]
You can change the original aspect ratio like this.
```java
canvas.save();
canvas.translate(mLottieDrawable.getPaddingLeft(), mLottieDrawable.getPaddingTop());
canvas.scale(mLottieDrawable.getCanvasScaleX(), mLottieDrawable.getCanvasScaleY());
mLottieDrawable.draw(canvas);
canvas.restore();
```

**Comment by ashankar12** [comment]
@WinKawaks agreed and thanks for that info. Is `setBounds()` not expected to scale and position the `LottieDrawable`?

**Comment by WinKawaks** [comment]
> @WinKawaks agreed and thanks for that info. Is `setBounds()` not expected to scale and position the `LottieDrawable`?

LottieDrawable does not support modifying the original aspect ratio, but you can encapsulate a new "BoundsLottieDrawable" yourself.
