### ISSUE TITLE
Does lottie-android support joystick'n sliders?

### ISSUE THREAD

**Issue by WinKawaks** [airbnb/lottie-android#1544]
I find that joystick'n sliders performs very well when combined with the sensor. How do I use this feature on Android like Web? 

Some demos of joystick'n sliders:
https://codepen.io/airnan/pen/EmdXGo
https://nerdmanship.github.io/lottie-proto/

**Comment by gpeal** [comment]
With [dynamic properties](http://airbnb.io/lottie/#/android?id=dynamic-properties).
