### ISSUE TITLE
Exporting error message

### ISSUE THREAD

**Issue by AdidiF** [airbnb/lottie-android#1548]
Hey,
I tried to export some kind of animation and I got this error message while exporting:

<img width="934" alt="צילום מסך 2020-04-16 ב-14 50 19" src="https://user-images.githubusercontent.com/63790139/79452994-b8a6b380-7ff1-11ea-94f5-1eaa9314ae4a.png">

and it showen it again and again, can you tell me please what can make this errors?
thank you 🙏

**Comment by gpeal** [comment]
@AdidiF This repo is just for Android.
