### ISSUE TITLE
Animation not rendering on Blackberry Keyone (Android)

### ISSUE THREAD

**Issue by EDBII** [airbnb/lottie-android#1549]
This JSON file attached animates fine on the desktop (Web) Lottiefiles, and when using the iPhone Lottiefiles app.  However, when rendering on a Blackberry Keyone with the Lottiefiles app and QR code, I get an error "There was an error loading the Composition."

Suggestions?
[Green.zip](https://github.com/airbnb/lottie-android/files/4488260/Green.zip)

**Comment by gpeal** [comment]
@EDBII This renders fine with Lottie. The issue is that you just scanned the json file without the image.
