### ISSUE TITLE
LottieAnimationView does not cancel animation

### ISSUE THREAD

**Issue by MimikFc7** [airbnb/lottie-android#1552]
Hello! thanx for your component, ths is very cool!
but i have strange bug:
I create Frame (androidx)

open frame, with static boolean field, when static field is true i begin animation, when false cancel animation,

but if i begin animation:

`class TestAnimationFragment extends Fragment {

    public static boolean playAnimation = false;
    private static TestAnimationFragment instance;
    
    public static TestAnimationFragment getInstance()
    {
        if(instance == null)
        {
            instance = new TestAnimationFragment();
        }
        return instance;
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        return inflater.inflate(R.layout.fragmentanimation, container, false);
    }

    @Override
    public void onViewCreated(View v, Bundle savedInstance) {

        if (playAnimation == true) {
            LottieAnimationView.setAnimation("myanimation.json");
            LottieAnimationView.setProgress(0);
            LottieAnimationView.playAnimation();
        } else {

            LottieAnimationView.cancelAnimation();
            LottieAnimationView.setProgress(0);

        }
    }
}`

if i open frame - play animation - close frame, open frame cancel animation, animation not canceled.

**Comment by gpeal** [comment]
@MimikFc7 It is impossible to say what exactly is happening from the limited code sample. However, you should never keep a static reference to a Fragment. Without more information, I am unable to help but if you can reproduce it in the issue-repro module in the repo, I can take a look.
