### ISSUE TITLE
Upgrade Okio to 2.x

### ISSUE THREAD

**Issue by kbrosnan** [airbnb/lottie-android#1554]
We are writing an a Kotlin app that uses Lottie and OkHTTP. We are considering replacing Lottie due to the project's reliance on Okio 1.x. This causes a circular dependency that is caught by Gradle when using OkHTTP 4.x and Lottie in the same project. I see that about a year ago the project added a comment `   // Do not ugprade to 2.0 because it will bring in Kotlin as a transitive dependency.` to the project's `build.gradle`. Has anything changed? 

1. Clone https://github.com/mozilla-mobile/fenix
2. Change the [mockwebserver value](https://github.com/mozilla-mobile/fenix/blob/a9692d9bce69688226086f94b0284831b06ba533/buildSrc/src/main/java/Dependencies.kt#L43) to a current 4.x release.  ex: `4.5.0`
3. Compile debug app
4. Circular dependency error from the compiler. OkHTTP wants Okio 2.x and Lottie wants Okio 1.x

https://github.com/mozilla-mobile/fenix/issues/8169#issuecomment-600231224

**Comment by gpeal** [comment]
@kbrosnan Hmm, I'm surprised nobody else has mentioned this yet. What do you think the ideal way to support it would be? At this point, I may start replacing some bits of the app with Kotlin. It's a pretty reasonable expectation at this point.

**Comment by ekager** [comment]
@gpeal is it still a requirement to not pull in Kotlin as a transitive dependency? I think we can maybe define an Okio updated version ourselves to work around this for now, but would be better if Lottie were updated with the newer version in case there were ever a breaking change.

**Comment by gpeal** [comment]
@ekager @kbrosnan  I try pretty hard to keep Lottie entirely free of any transitive dependencies to avoid issues like this one. If I upgrade okio to 2.x, will it break apps with okhttp 3.x?

**Comment by kbrosnan** [comment]
Looking at [okio's 2.0.0-rc1](https://square.github.io/okio/changelog/#version-200-rc1) release notes page they have the following notes about migrating from 1.x to 2.x

> Okio 2 is a major release that upgrades the library’s implementation language from Java to Kotlin.

> Okio 2.x is binary-compatible with Okio 1.x and does not change any behavior. Classes and .jar files compiled against 1.x can be used with 2.x without recompiling.

>  Okio 2.x is .java source compatible with Okio 1.x in all but one corner case. In Okio 1.x Buffer would throw an unchecked IllegalStateException when attempting to read more bytes than available. Okio 2.x now throws a checked EOFException in this case. This is now consistent with the behavior of its BufferedSource interface. Java callers that don’t already catch IOException will now need to.

> Okio 2.x is .kt source-incompatible with Okio 1.x. This release adopts Kotlin idioms where they are available. [omitted list of idioms, see link to full release notes]

**Comment by gpeal** [comment]
@kbrosnan Can we close this out then? :)

**Comment by mstange** [comment]
Doesn't the circular dependency issue still exist?
