### ISSUE TITLE
Lottie Dynamic Properties--TRANSFORM_POSITION is incorrect

### ISSUE THREAD

**Issue by WinKawaks** [airbnb/lottie-android#1555]
I tried to modify the position of a certain layer through Dynamic Properties.
```
animationView.addValueCallback(
                path,
                LottieProperty.TRANSFORM_POSITION,
                new SimpleLottieValueCallback<PointF>() {
                    @Override
                    public PointF getValue(LottieFrameInfo<PointF> frameInfo) {
                        mPointF.set(300, 300);
                        return mPointF;
                    }
                }
        );
```
The composition's width is 600 and height is 600. When I set mPointF (600, 600), I found that the layer is drawn to the canvas outside the view. And I found (300, 300) is probably the position of the lower right corner of the view.

When I use TRANSFORM_POSITION and TRANSFORM_SCALE at the same time，I found TRANSFORM_SCALE will change the center point of the layer.

It seems that the TRANSFORM_POSITION and TRANSFORM_SCALE feature behave differently on Android devices and AE. How can I get the edge position of lottie and set a layer to the right position?

![image](https://user-images.githubusercontent.com/20330575/80485490-14772200-898c-11ea-936c-3114cf2aa97d.png)
![image](https://user-images.githubusercontent.com/20330575/80485497-1a6d0300-898c-11ea-9a36-643da3b635e6.png)

**Comment by gpeal** [comment]
@WinKawaks This heavily depends on your composition and it's impossible to give an answer without a full example. However, one thing to note is that px in after effects are rendered as dp on Android so you need to scale your values appropriately.

**Comment by gpeal** [comment]
You can reopen this with an example attached if there is more to take a look at.
