### ISSUE TITLE
Double selectable background (rectangular and round) on Android M

### ISSUE THREAD

**Issue by astirtrotter** [airbnb/lottie-android#1560]
Following steps will reproduce this issue.

```xml
<com.airbnb.lottie.LottieAnimationView
        android:id="@+id/lottieButton"
        android:layout_width="@dimen/button_size"
        android:layout_height="@dimen/button_size"
        android:scaleType="centerInside"/>
```

```kotlin
// set round selectable background
val outValue = TypedValue()
context.theme.resolveAttribute(android.R.attr.selectableItemBackgroundBorderless, outValue, true)
lottieButton.setBackgroundResource(outValue.resourceId)

// set image/animation
// no matter what image/animation is used, this issue happens
lottieButton.setImageResource(R.drawable.xxx)  // [optional] any drawable resource
lottieButton.setAnimation(xxx)  // [optional] any animation
```

- lottie version: 3.4.0
- OS: Android M

Attached an example screenshot on my device.
![sort](https://user-images.githubusercontent.com/13758840/81069837-0473bb00-8f15-11ea-89cc-bb6d379f2ccf.png)

---

FNI: On Android N or later, all works fine.

**Comment by gpeal** [comment]
@astirtrotter LottieAnimationView is just a normal ImageView and the LottieDrawable that does the rendering has no knowledge of the pressed state so it is likely related to your layout/theme unrelated to Lottie.

**Comment by astirtrotter** [comment]
@gpeal I also thought so, but if you replace LottieAnimationView with general ImageView, then it works fine.

**Comment by voronnate** [comment]
@gpeal Is it possible to look into this issue in more detail? Perhaps if we put a bounty on it?
