### ISSUE TITLE
Animation not playing ,only a preview image is showing.

### ISSUE THREAD

**Issue by jerinjacob1999** [airbnb/lottie-android#1561]
**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I tried different Lottie files from Lottiefiles.com, all have the same error

**Describe the bug**
I'm not using Android Studio , a platform named app inventor
This is the app log when loading animation from URL.

``W/zygote  ( 4150): Unexpected CPU variant for X86 using defaults: x86
I/MultiDex( 4150): VM with version 2.1.0 has multidex support
I/MultiDex( 4150): install: doIt = true
I/MultiDex( 4150): VM has multidex support, MultiDex support library is disabled.
D/AppInventorCompatActivity( 4150): Setting classic mode from YAIL: true
D/AppInventorCompatActivity( 4150): Already have a title bar (classic mode): android.widget.TextView{31f313e V.ED..... ......ID 0,0-0,0 #1020016 android:id/title}
D/Form    ( 4150): Form Screen1 got onCreate
I/Form    ( 4150): activeForm is now Screen1
D/Form    ( 4150): deviceDensity = 3.0
I/Form    ( 4150): compatScalingFactor = 1.1247803
D/Form    ( 4150): MULTI: _initialized = false formName = Screen1
D/Form    ( 4150): MultiDex already installed.
D/Form    ( 4150): onCreateFinish called 1589025983964
D/Form    ( 4150): recomputeLayout called
D/Form    ( 4150): About to create a new ScaledFrameLayout
D/Form    ( 4150): Sizing(Responsive)
D/Form    ( 4150): formWidth = 360 formHeight = 592
I/Form    ( 4150): calling Initialize method for Object com.google.appinventor.components.runtime.Menu@e900a31
I/Form    ( 4150): Form Screen1 got onResume
D/OpenGLRenderer( 4150): HWUI GL Pipeline
I/zygote  ( 4150): Background concurrent copying GC freed 18615(3MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 2027KB/3MB, paused 22us total 169.731ms
D/        ( 4150): HostConnection::get() New Host Connection established 0xe57b1b00, tid 4192
I/zygote  ( 4150): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
I/OpenGLRenderer( 4150): Initialized EGL, version 1.4
D/OpenGLRenderer( 4150): Swap behavior 1
W/OpenGLRenderer( 4150): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer( 4150): Swap behavior 0
D/EGL_emulation( 4150): eglCreateContext: 0xf033a6a0: maj 2 min 0 rcv 2
D/EGL_emulation( 4150): eglMakeCurrent: 0xf033a6a0: ver 2 0 (tinfo 0xd5bada50)
D/Form    ( 4150): onGlobalLayout(): diffPercent = 0.1515625
D/Form    ( 4150): keyboard hidden!
D/Form    ( 4150): Sizing(Responsive)
D/Form    ( 4150): formWidth = 360 formHeight = 592
D/Form    ( 4150): ReplayFormOrientation()
D/Form    ( 4150): Sizing(Responsive)
D/Form    ( 4150): formWidth = 360 formHeight = 592
D/Form    ( 4150): onGlobalLayout(): diffPercent = 0.1515625
D/Form    ( 4150): keyboard hidden!
D/EGL_emulation( 4150): eglMakeCurrent: 0xf033a6a0: ver 2 0 (tinfo 0xd5bada50)
I/zygote  ( 4150): Do partial code cache collection, code=30KB, data=27KB
I/zygote  ( 4150): After code cache collection, code=25KB, data=26KB
I/zygote  ( 4150): Increasing code cache capacity to 128KB
I/zygote  ( 4150): Deoptimizing gnu.bytecode.Method gnu.bytecode.ClassType.getDeclaredMethod(java.lang.String, gnu.bytecode.Type[]) due to JIT same target
W/LOTTIE  ( 4150): Lottie doesn't support expressions.
W/LOTTIE  ( 4150): Lottie doesn't support layer effects. If you are using them for  fills, strokes, trim paths etc. then try adding them directly as contents  in your shape. Found: [WING-END-FILL: Path 1 [1.1.0], WING-END-FILL: Path 1 [1.1.1], WING-END-FILL: Path 1 [1.1.2], WING-END-FILL: Path 1 [1.1.3]]
I/zygote  ( 4150): Do partial code cache collection, code=61KB, data=40KB
I/zygote  ( 4150): After code cache collection, code=51KB, data=37KB
I/zygote  ( 4150): Increasing code cache capacity to 256KB
W/LOTTIE  ( 4150): Lottie doesn't support layer effects. If you are using them for  fills, strokes, trim paths etc. then try adding them directly as contents  in your shape. Found: [WING-SIDE-FILL: Path 1 [1.1.0], WING-SIDE-FILL: Path 1 [1.1.1], WING-SIDE-FILL: Path 1 [1.1.2], WING-SIDE-FILL: Path 1 [1.1.3]]
W/LOTTIE  ( 4150): Lottie doesn't support 3D layers.
W/LOTTIE  ( 4150): Lottie doesn't support layer effects. If you are using them for  fills, strokes, trim paths etc. then try adding them directly as contents  in your shape. Found: [WING-TOP-FILL: Path 1 [1.1.0], WING-TOP-FILL: Path 1 [1.1.1], WING-TOP-FILL: Path 1 [1.1.2], WING-TOP-FILL: Path 1 [1.1.3]]
W/LOTTIE  ( 4150): Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().
I/zygote  ( 4150): Do full code cache collection, code=125KB, data=78KB
I/zygote  ( 4150): After code cache collection, code=61KB, data=36KB
W/LOTTIE  ( 4150): Animation contains merge paths but they are disabled.
I/zygote  ( 4150): Background concurrent copying GC freed 218392(5MB) AllocSpace objects, 0(0B) LOS objects, 31% free, 13MB/19MB, paused 27us total 207.675ms
I/zygote  ( 4150): Do partial code cache collection, code=119KB, data=75KB
I/zygote  ( 4150): After code cache collection, code=113KB, data=73KB
I/zygote  ( 4150): Increasing code cache capacity to 512KB
D/Form    ( 4150): onGlobalLayout(): diffPercent = 0.1515625
D/Form    ( 4150): keyboard hidden!
I/zygote  ( 4150): Do full code cache collection, code=251KB, data=142KB
I/zygote  ( 4150): After code cache collection, code=120KB, data=65KB``

[2020-05-09 17-37-25 debug log.txt](https://github.com/airbnb/lottie-android/files/4603639/2020-05-09.17-37-25.debug.log.txt)

**What version of Lottie did you test this on?**
I'm using Lottie latest version

**What version of Android did you test this on?**
Android 10 and Android 8.1

**Comment by gpeal** [comment]
@jerinjacob1999 This is probably an App Inventor issue, not a Lottie Android issue. You can try scanning the lottiefiles qr codes for the same animations with the Lottie app on the Play Store if you want to check.
