### ISSUE TITLE
Fatal Exception: android.os.BadParcelableException

### ISSUE THREAD

**Issue by Jiwei0810** [airbnb/lottie-android#1565]
Version used: com.airbnb.android:lottie:3.4.0
appcompat: androidx

minSdkVersion = 17
minSdkVersion_v8 = 21
compileSdkVersion = 28
targetSdkVersion = 28
buildToolsVersion = "28.0.3"

Device used:Android 9

stack trace:-

Fatal Exception: android.os.BadParcelableException
ClassNotFoundException when unmarshalling: com.airbnb.lottie.LottieAnimationView$SavedState

android.os.Parcel.readParcelableCreator (Parcel.java:2855)
android.os.Parcel.readParcelable (Parcel.java:2781)
android.os.Parcel.readValue (Parcel.java:2684)
android.os.Parcel.readSparseArrayInternal (Parcel.java:3134)
android.os.Parcel.readSparseArray (Parcel.java:2367)
android.os.Parcel.readValue (Parcel.java:2741)
android.os.Parcel.readArrayMapInternal (Parcel.java:3053)
android.os.BaseBundle.initializeFromParcelLocked (BaseBundle.java:288)
android.os.BaseBundle.unparcel (BaseBundle.java:232)
android.os.Bundle.getSparseParcelableArray (Bundle.java:1010)
com.android.internal.policy.PhoneWindow.restoreHierarchyState (PhoneWindow.java:2204)
android.app.Activity.onRestoreInstanceState (Activity.java:1204)
**com.xxx.CurrentActivity.onRestoreInstanceState (CurrentActivity.java:377)**
android.app.Activity.performRestoreInstanceState (Activity.java:1159)
android.app.Instrumentation.callActivityOnRestoreInstanceState (Instrumentation.java:1317)
android.app.ActivityThread.handleStartActivity (ActivityThread.java:3215)
android.app.servertransaction.TransactionExecutor.performLifecycleSequence (TransactionExecutor.java:185)
android.app.servertransaction.TransactionExecutor.cycleToPath (TransactionExecutor.java:170)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:147)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:73)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2038)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:226)
android.app.ActivityThread.main (ActivityThread.java:7178)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:576)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:942)

**Comment by gpeal** [comment]
@Jiwei0810 Can you reproduce this? Are you using proguard?

**Comment by Jiwei0810** [comment]
We using  proguard.
In the proguard-rules.pro ---example:    -keep class com.airbnb.lottie.*
com.airbnb.lottie need -keep?

**Comment by venumanas87** [comment]
Same problem the app is continuously crashing due to this

**Comment by gpeal** [comment]
@Jiwei0810 @venumanas87 Please attach a sample project that reproduces this.

**Comment by Jiwei0810** [comment]
> @ Jiwei0810 @ venumanas87请附加一个复制此示例项目。

Sorry we are an online project, I saw the error from FireBase, I cannot provide a sample project

**Comment by gpeal** [comment]
@Jiwei0810 Sorry, I am unable to provide assistance without a sample project and reproduction steps.
