### ISSUE TITLE
Out of memory: crash when show many animations frequently (RAM can't release after animation done)

### ISSUE THREAD

**Issue by xensius** [airbnb/lottie-android#1566]
** Lottie v3.0.1 and also on Lottie v3.4.0

** Describe the bug:
My app shows many different gift animations frequently. ex: A,B,C,D, ... is gift animation. My app will play animation A then animation A done, app will play animation B .... then for C, D, ...

i logged usage ram info, and i see when animation play RAM usage increased but when animation is done, RAM usage is not released or hard to release and make a crash when get full RAM.
i checked on devices: the issue occurs on Redmi 3s (Android 6.0), Samsung GT-I9505 (Android 5.01), Asus Asus_X008D (Android 7.0) but Lottie works OK about RAM usage on Samsung A20s (Android 9.0).

i used codes to playAnimation with Lottie:
```
            lottieAnimationView.setComposition(composition);            

            lottieAnimationView.setProgress(0f);
            lottieAnimationView.resumeAnimation();

```
and listen AnimationEnded by `lottieAnimationView.addAnimatorListener` to play next gift animation.

Thank team very much and hope get your reply soon!!!

**Comment by gpeal** [comment]
This is not enough information to debug with. Please attach a sample project using the issue-repro module here that demonstrates the leak.

**Comment by xensius** [comment]
Version used: com.airbnb.android:lottie:3.4.0
appcompat: androidx

minSdkVersion 16
targetSdkVersion 29
compileSdkVersion = 29
buildToolsVersion = "29.0.2"

Device used: Redmi 3s (Android 6.0), Samsung GT-I9505 (Android 5.01), Asus Asus_X008D (Android 7.0)

sample project: https://github.com/xensius/TestLottie

Thank team very much and hope get your reply soon!!!
