### ISSUE TITLE
Resizing animations in Android with LottieAnimationView

### ISSUE THREAD

**Issue by artcrespo** [airbnb/lottie-android#1568]
**Environment Android**
Using AndroidX libraries

**Bug description**
Many animations are doesn't scale properly. Testing with two different animations with the same declaration in the XML.

**Lottie version**
'com.airbnb.android:lottie:3.4.0'

**Android version**
9

**Steps To Reproduce**

1. Git clone from https://github.com/artcrespo/lottie_testing_samples.git
2. Debug the application with Android Studio
3. To test with the other animation simply comment the code inside activity_main.xml
4. The same declaration in XML for the two different Lottie animations (I don't know if it is the expected behaviour and if it is I would like to be able to resize the home animation to the size of the biking guy) Thank you!

**Screenshots**

![98363031_2798182166960513_3572478063654469632_n](https://user-images.githubusercontent.com/17773799/82258724-5c082280-9928-11ea-885d-1ede5d19c7e8.jpg)

![99142335_580694902553890_3159173382235226112_n](https://user-images.githubusercontent.com/17773799/82258738-64605d80-9928-11ea-97c5-7eb165b50059.jpg)

**Comment by gpeal** [comment]
The animation itself is 800x800 and the house is very small in the center of it. To make it scale, crop the composition to the bounds of the house.
