### ISSUE TITLE
AndroidOS/Agent.YM Malware reported in APK generated with Lottie 

### ISSUE THREAD

**Issue by Arjunjoshi123** [airbnb/lottie-android#1571]
**Link to fork with a repro in the issue-repro module**
- Tested With V 3.3.0 and V 3.4.0

**Describe the bug**
- AndroidOS/Agent.YM Malware was reported in APK generated with Lottie  v 3.3.0/v 3.4.0
- This was Tested in VirusTotal.com

**Steps To Reproduce**
1. Create the Blank project in android studio with adding the lottie dependency i.e
  implementation 'com.airbnb.android:lottie:3.4.0'    in build.gradle file 

2. Genarate the signed release apk

3.Upload and Test the genarated apk in VirusTotal.com

4. The error reported by "VirusTotal" file is attached
![LottieIssue](https://user-images.githubusercontent.com/34054384/82455059-269e3900-9ad0-11ea-8865-0ba831a09f70.PNG)

I have also attached sample andriod  project to demonstrate it.
[AndriodStudioProject.zip](https://github.com/airbnb/lottie-android/files/4657310/AndriodStudioProject.zip)

Please let me know what is the issue in project or if i am missing something

Is there any way to find if its a false alarm.

Thanks in Advance,
Arjun

**Comment by gpeal** [comment]
@Arjunjoshi123 This must be an issue with the virus reporting tool. The only transitive dependency in Lottie is okio.
