### ISSUE TITLE
Crash while setting animation through URL

### ISSUE THREAD

**Issue by AyushGoel529** [airbnb/lottie-android#1577]
We are setting a lottie animation through URL: 
In below code view is of type LottieAnimationView.

try {
            String lottieUrl = Constants.LOTTIE_BASE_URL + lottieName + ".json";
            view.setAnimationFromUrl(lottieUrl);
      } catch (Exception e) {
            e.printStackTrace();
     }

Even if the above code is in try catch, it throughs some crash reported on play console. I have cross checked all the Lottie URL we are using and they are fine.

Below is the error log. Please help to resolve the crash or catch the same.

Error Log:

Caused by java.lang.IllegalStateException
Unable to parse composition
com.airbnb.lottie.LottieAnimationView$1.onResult (LottieAnimationView.java:74)
com.airbnb.lottie.LottieAnimationView$1.onResult (LottieAnimationView.java:67)
com.airbnb.lottie.LottieAnimationView$3.onResult (LottieAnimationView.java:91)
com.airbnb.lottie.LottieAnimationView$3.onResult (LottieAnimationView.java:84)
com.airbnb.lottie.LottieTask.notifyFailureListeners (LottieTask.java:158)
com.airbnb.lottie.LottieTask.access$200 (LottieTask.java:27)
com.airbnb.lottie.LottieTask$1.run (LottieTask.java:133)
android.os.Handler.handleCallback (Handler.java:883)
android.os.Handler.dispatchMessage (Handler.java:100)
android.os.Looper.loop (Looper.java:214)
android.app.ActivityThread.main (ActivityThread.java:7397)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:935)

Caused by java.io.IOException
unexpected end of stream on com.android.okhttp.Address@3dda0fb2
com.android.okhttp.internal.http.Http1xStream.readResponse (Http1xStream.java:203)
com.android.okhttp.internal.http.Http1xStream.readResponseHeaders (Http1xStream.java:129)
com.android.okhttp.internal.http.HttpEngine.readNetworkResponse (HttpEngine.java:750)
com.android.okhttp.internal.http.HttpEngine.readResponse (HttpEngine.java:622)
com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute (HttpURLConnectionImpl.java:475)
com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse (HttpURLConnectionImpl.java:411)
com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode (HttpURLConnectionImpl.java:542)
com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode (DelegatingHttpsURLConnection.java:106)
com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode (HttpsURLConnectionImpl.java:30)
com.google.firebase.perf.network.zzf.getErrorStream (zzf.java:142)
com.google.firebase.perf.network.zzc.getErrorStream (zzc.java:38)
com.airbnb.lottie.network.NetworkFetcher.fetchFromNetworkInternal (NetworkFetcher.java:96)
com.airbnb.lottie.network.NetworkFetcher.fetchFromNetwork (NetworkFetcher.java:79)
com.airbnb.lottie.network.NetworkFetcher.fetchSync (NetworkFetcher.java:48)
com.airbnb.lottie.network.NetworkFetcher.fetchSync (NetworkFetcher.java:31)
com.airbnb.lottie.LottieCompositionFactory$1.call (LottieCompositionFactory.java:84)
com.airbnb.lottie.LottieCompositionFactory$1.call (LottieCompositionFactory.java:81)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:919)

Caused by java.io.EOFException
\n not found: size=0 content=...
com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict (RealBufferedSource.java:202)
com.android.okhttp.internal.http.Http1xStream.readResponse (Http1xStream.java:188)
com.android.okhttp.internal.http.Http1xStream.readResponseHeaders (Http1xStream.java:129)
com.android.okhttp.internal.http.HttpEngine.readNetworkResponse (HttpEngine.java:750)
com.android.okhttp.internal.http.HttpEngine.readResponse (HttpEngine.java:622)
com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute (HttpURLConnectionImpl.java:475)
com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse (HttpURLConnectionImpl.java:411)
com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode (HttpURLConnectionImpl.java:542)
com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode (DelegatingHttpsURLConnection.java:106)
com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode (HttpsURLConnectionImpl.java:30)
com.google.firebase.perf.network.zzf.getErrorStream (zzf.java:142)
com.google.firebase.perf.network.zzc.getErrorStream (zzc.java:38)
com.airbnb.lottie.network.NetworkFetcher.fetchFromNetworkInternal (NetworkFetcher.java:96)
com.airbnb.lottie.network.NetworkFetcher.fetchFromNetwork (NetworkFetcher.java:79)
com.airbnb.lottie.network.NetworkFetcher.fetchSync (NetworkFetcher.java:48)
com.airbnb.lottie.network.NetworkFetcher.fetchSync (NetworkFetcher.java:31)
com.airbnb.lottie.LottieCompositionFactory$1.call (LottieCompositionFactory.java:84)
com.airbnb.lottie.LottieCompositionFactory$1.call (LottieCompositionFactory.java:81)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:919).

**Comment by gpeal** [comment]
@AyushGoel529 `setAnimationFromUrl` fetches the animation asynchronously. Since network requests can fail, you should set a failure listener on the animation view.

**Comment by slice-ojamsivasai** [comment]
Could you share the code of failure listener ? @gpeal ?

**Comment by AyushGoel529** [comment]
@slice-ojamsivasai 

lottieAnimationView.setFailureListener(throwable ->
                        sendException(new Exception("Lottie error " + lottieUrl, throwable))
                );
 
lottieAnimationView.setAnimationFromUrl(lottieUrl);

**Comment by AdityaPahilwani** [comment]
@AyushGoel529 what's sendException is doing exactly here?

**Comment by AyushGoel529** [comment]
> @AyushGoel529 what's sendException is doing exactly here?

It is for logging purpose
