### ISSUE TITLE
Support setting LottieAnimationView.DEFAULT_FAILURE_LISTENER 

### ISSUE THREAD

**Issue by Joy-Zhang** [airbnb/lottie-android#1578]
** If you don't use this template, your issue will be closed **

**Is your feature request related to a problem? Please describe.**
My app have some 3rd-party dependencies which use LottieAnimationView and have some parsing error. It will finally cause a crash. I want to ignore their error by setting ```LottieAnimationView.DEFAULT_FAILURE_LISTENER```. Furthermore, I hope that I can collect more error information to feedback to these dependencies' owner.

**Describe the solution you'd like**
Maybe just simply make ```LottieAnimationView.DEFAULT_FAILURE_LISTENER``` public and non-final

**Describe alternatives you've considered**
Setting LottieAnimationView.DEFAULT_FAILURE_LISTENER through reflection in ```Application.onCreate```.
```java
try {
    Field failureListener = LottieAnimationView.class.getDeclaredField("DEFAULT_FAILURE_LISTENER");
    failureListener.setAccessible(true);
    failureListener.set(null, new LottieListener<Throwable>() {
        @Override
        public void onResult(Throwable throwable) {
           if (BuildConfig.DEBUG) {
              // maybe I can collect some error information
               throw new IllegalStateException("Unable to parse composition", throwable);
           }
        }
    });
} catch (Throwable t) {
    // ignore
    // t.printStackTrace();
}
```
This solution will slowdown startup because of reflection.

**Additional context**

*Lottie is supported and developed on nights and weekends. Please consider [sponsoring Lottie](https://github.com/users/gpeal/sponsorship) to prioritize this issue and help support this issue as well as future investments.*

**Comment by gpeal** [comment]
@Joy-Zhang Can you just set the normal failure listener?
