### ISSUE TITLE
Add resetter for minFrame/maxFrame properties

### ISSUE THREAD

**Issue by carstenhag** [airbnb/lottie-android#1585]
**Is your feature request related to a problem? Please describe.**
Programatically I first want something to loop, so I set a min and max frame, but after a specific action, I want to play the remaining end of the animation and stop looping.

**Describe the solution you'd like**
Either add a  `resetMinFrame()/resetMaxFrame()` or if the lib would be in kotlin make the `setMinFrame()/setMaxFrame()` methods have an optional argument, that when not specified, resets the min/max values.

**Describe alternatives you've considered**
Create a kotlin extension with this code:

```kt
fun LottieAnimationView.resetMaxFrame() {
    val frames = this.composition?.durationFrames?.toInt() ?: 0
    this.setMaxFrame(frames)
}
```

**Additional context**
None

*Lottie is supported and developed on nights and weekends. Please consider [sponsoring Lottie](https://github.com/users/gpeal/sponsorship) to prioritize this issue and help support this issue as well as future investments.*

**Comment by gpeal** [comment]
@carstenhag Could you call `setProgress(0f, 1f)` instead?

**Comment by carstenhag** [comment]
Ah, I don't know the documentation of that on top of my head, but does it really reset the min and max frames? If so, it would be a bit unexpected to me.

**Comment by gpeal** [comment]
@carstenhag Sorry, I meant `setMin/setMax/setMinAndMaxProgress`

**Comment by gpeal** [comment]
Let me know if that isn't sufficient for you.

**Comment by carstenhag** [comment]
Sorry for not commenting before, forgot about this. So for `minFrame` I can just use 0, but for `maxFrame` I thought I would need the precise frame amount.

Looking at the code @ `LottieValueAnimator.java` and `setMinAndMaxFrames`, seems like I could just pass in any max value and it should work, right?

As in: `LottieAnimationView.setMaxFrame(Int.MAX_VALUE)`. If this works (haven't tried) it would be useful to have it documented at `LottieAnimationView.setMaxFrame` or to add an `  public void setMaxFrame()` without argument which resets it to the max 👍 . What do you think?

**Comment by carstenhag** [comment]
@gpeal Just saw this issue still being referenced in our code, can you please look at the above comment? :) Thanks!
