### ISSUE TITLE
怎么手动停止这个循环动画

### ISSUE THREAD

**Issue by Ysrfengnull** [airbnb/lottie-android#1587]
我在代码里开启了一个循环，怎么手动停止这个循环动画 ，调用lavMenu.cancelAnimation(); 无效
 private void setSelect(View view, boolean selected) {
        LottieAnimationView lavMenu = view.findViewById(R.id.lav_menu);
        lavMenu.loop(false);
        lavMenu.setSelected(selected);
        if (lavMenu.isAnimating()) {
            lavMenu.cancelAnimation();
        }
        lavMenu.setProgress(0f);
        if (selected) {
            lavMenu.setMinAndMaxProgress(0.5f,1.0f);
            lavMenu.loop(true);
            lavMenu.playAnimation();
        }
    }

**Comment by JackZ-2019** [comment]
imgLottie.addAnimatorUpdateListener(valueAnimator -> {
            // 判断动画加载结束
            if (imgLottie.isAnimating()
                    && valueAnimator.getAnimatedFraction() == 1f) {
                imgLottie.pauseAnimation();
            }
        });
