### ISSUE TITLE
lottie animation doesn't show up in android studio build

### ISSUE THREAD

**Issue by michaelmitelman** [airbnb/lottie-android#1588]
**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features). Yes.
2. I know what part of my animation doesn't work. Yes.
3. I have created a simplified version of my animation  No.
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work. No.

**Describe the bug**
Animation of [running dog](https://lottiefiles.com/1187-puppy-run) doesn't show in the activity, although I defined the widget exactly as you defined in readme file. It shows blank page instead of the animation.
**What version of Lottie did you test this on?**
  3.4.1
**What version of Android did you test this on?**
  3.6.1

**Screenshots**

*Lottie is supported and developed on nights and weekends. Please consider [sponsoring Lottie](https://github.com/users/gpeal/sponsorship) to prioritize this issue and help support this issue as well as future investments.*

**Comment by carstenhag** [comment]
Do you mean just the layout preview? Or is it not showing up in the app itself?

**Comment by michaelmitelman** [comment]
@carstenhag It not showing up in the app itself, It doesn't show animation when I use this animation.

**Comment by gpeal** [comment]
@michaelmitelman That animation has images. You have to include them ([docs](http://airbnb.io/lottie/#/android?id=images))

If you download the aep file from lottiefiles, you'll get them. The animation works fine once you do that.
