### ISSUE TITLE
Make LottieAnimationView drop-in replacement of ImageView

### ISSUE THREAD

**Issue by 0legg** [airbnb/lottie-android#159]
So, right now, as `LottieAnimationView` is subclassing `AppCompatImageView`, we almost can use it as ImageView replacement for all needs, not limited to animations. But there are few drawbacks, which can affect behavior of some non-Lottie drawables inside it:

1. `LottieAnimationView` overrides `invalidateDrawable()` without making calls to super, so some Drawables that are relying on calls to this methods will be broken.
1. `LottieAnimationView` handles its own internal `Drawable` instance, and it's not propagated back to parent class
1. There are no animation cleanup methods called when we're changing drawable through `setImageDrawable()` or any other `ImageView` methods — and no exception is raised if we're misusing these methods.
1. `LottieAnimationView` is forced to have software layer, while in some usecases it can affect performance and memory consumption.

Are there any plans to improve `LottieAnimationView` behavior as an `ImageView` or are you willing to accept PRs resolving these issues?

**Comment by hzsweers** [comment]
all of these can be gated by checking for the existence of a provided `LottieDrawable` methods right? I wouldn't call these "issues" as much as implementation details/optimizations that we can simply gate.

**Comment by gpeal** [comment]
@0legg I gated a few methods in the above commit. Feel free to submit a PR if you'd like more than that.

**Comment by hzsweers** [comment]
What would you think of just encapsulating it in a LottieDelegate helper class with matching APIs to callback? Similar to AppCompatDelegate's callbacks

**Comment by gpeal** [comment]
@hzsweers Seems reasonable. Would you like to do a PR for that?

**Comment by hzsweers** [comment]
can do :+1:
