### ISSUE TITLE
Talkback Support

### ISSUE THREAD

**Issue by crackjack** [airbnb/lottie-android#1591]
**Is your feature request related to a problem? Please describe.**
I am not sure if this already exists, but I was unable to find it. I see that Dynamic Localized Text can be added using the TextDelegate, I was wondering how would one set custom ContentDescription for that text?

**Describe the solution you'd like**
In Android if `textView` is a TextView, the text and contentDescription could be set as follows:
```
textView.setText("My Custom Text"); // you would use the R.string value here
textView.setContentDescription("My Custom Talkback Announcement");
```

**Describe alternatives you've considered**
I haven't considered anything, but overriding [AccessibilityDelegate](https://developer.android.com/reference/android/view/View.AccessibilityDelegate) might be something

**Additional context**
N/A

*Lottie is supported and developed on nights and weekends. Please consider [sponsoring Lottie](https://github.com/users/gpeal/sponsorship) to prioritize this issue and help support this issue as well as future investments.*

**Comment by gpeal** [comment]
@crackjack Lottie could have many TextLayers embedded in an animation so I don't think there is a way to generically set the content description. You can set it yourself though.

**Comment by crackjack** [comment]
You said "I can set it myself", how exactly do you mean?

**Comment by inteliphone** [comment]
@gpeal that is a very unsatisfactory outcome. The Content Description for any visual or interactive component is a blank canvas for a human to write a description, it is not automated from the content and shouldn't be, it could even be localized while the media is not - so the possible presence of embedded TextLayers in an animation is not a reason to avoid making Lottie Accessible. Please reopen this ticket and provide a solution.
