### ISSUE TITLE
#1830 com.airbnb.lottie.parser.moshi.JsonEncodingException 

### ISSUE THREAD

**Issue by lzy2626** [airbnb/lottie-android#1594]
use version3.3.0
bugly crash

#1830 com.airbnb.lottie.parser.moshi.JsonEncodingException
Use JsonReader.setLenient(true) to accept malformed JSON at path $
com.airbnb.lottie.LottieAnimationView$1.a(LottieAnimationView.java:74)

crash log：

1 java.lang.IllegalStateException:Unable to parse composition
--
2 com.airbnb.lottie.LottieAnimationView$1.a(LottieAnimationView.java:74)
3 ......
4 Caused by:
5 com.airbnb.lottie.parser.moshi.JsonEncodingException:Expected ':' at path $.layers[0].ks.s.k[1].null
6 com.airbnb.lottie.parser.moshi.JsonReader.a(JsonReader.java:249)
7 com.airbnb.lottie.parser.moshi.b.o(JsonUtf8Reader.java:285)
8 com.airbnb.lottie.parser.moshi.b.e(JsonUtf8Reader.java:166)
9 com.airbnb.lottie.parser.q.a(KeyframeParser.java:93)
10 com.airbnb.lottie.parser.q.a(KeyframeParser.java:68)
11 com.airbnb.lottie.parser.r.a(KeyframesParser.java:41)
12 com.airbnb.lottie.parser.d.a(AnimatableValueParser.java:79)
13 com.airbnb.lottie.parser.d.d(AnimatableValueParser.java:49)
14 com.airbnb.lottie.parser.c.a(AnimatableTransformParser.java:75)
15 com.airbnb.lottie.parser.s.a(LayerParser.java:132)
16 com.airbnb.lottie.parser.t.a(LottieCompositionMoshiParser.java:121)
17 com.airbnb.lottie.parser.t.a(LottieCompositionMoshiParser.java:87)
18 com.airbnb.lottie.g.a(LottieCompositionFactory.java:353)
19 com.airbnb.lottie.g.b(LottieCompositionFactory.java:346)
20 com.airbnb.lottie.g.a(LottieCompositionFactory.java:276)
21 com.airbnb.lottie.g.b(LottieCompositionFactory.java:269)
22 com.airbnb.lottie.g.c(LottieCompositionFactory.java:163)
23 com.airbnb.lottie.g$4.a(LottieCompositionFactory.java:128)
24 com.airbnb.lottie.g$4.call(LottieCompositionFactory.java:125)
25 java.util.concurrent.FutureTask.run(FutureTask.java:237)
26 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
27 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
28 java.lang.Thread.run(Thread.java:818)

**Comment by gpeal** [comment]
Please reopen with a sample project that reproduces this.
