### ISSUE TITLE
Z Index Ordering

### ISSUE THREAD

**Issue by lawloretienne** [airbnb/lottie-android#1597]
I am having a similar issue to the one posted here

https://stackoverflow.com/questions/46693868/lottie-animation-library-z-ordering-issue

The Z index ordering is being ignored. Why is that?

**Comment by lawloretienne** [comment]
This is what the layout looks like
https://gist.github.com/lawloretienne/0b7625e7f4d0fd9157c5298275c92db6

**Comment by lawloretienne** [comment]
I am using version 3.4.0 of the lottie library.

**Comment by gpeal** [comment]
@lawloretienne Lottie doesn't do anything special with z indexing. Can you be more specific?
