### ISSUE TITLE
Font setting through R.font

### ISSUE THREAD

**Issue by crackjack** [airbnb/lottie-android#1598]
** If you don't use this template, your issue will be closed **

**Is your feature request related to a problem? Please describe.**
I can see that using FontDelegate one can pass the font path, but is there a way to reference the Font using `R.font`?

**Describe the solution you'd like**
Ability to set font in AnimationView using `style` or `font`

**Describe alternatives you've considered**
Embedded fonts in JSON, and putting fonts inside assets folder

**Additional context**
NA

*Lottie is supported and developed on nights and weekends. Please consider [sponsoring Lottie](https://github.com/users/gpeal/sponsorship) to prioritize this issue and help support this issue as well as future investments.*

**Comment by gpeal** [comment]
@crackjack You can load it yourself with a FontAssetDelegate
https://github.com/airbnb/lottie-android/blob/1330634a058fb32012e190dd1b6dab6c10069674/LottieSample/src/main/kotlin/com/airbnb/lottie/samples/PlayerFragment.kt#L115
