### ISSUE TITLE
 Skipped 1 frames!  The application may be doing too much work on its main thread.

### ISSUE THREAD

**Issue by 18301877418** [airbnb/lottie-android#1599]
Put the animation in the XML file and play it will appear  I/Choreographer: Skipped 1 frames!  The application may be doing too much work on its main thread.

**Comment by 18301877418** [comment]
If I turn off the animation, it won't appear

**Comment by gpeal** [comment]
I'm not sure what the issue you are reporting is. Please reopen and clarify.
