### ISSUE TITLE
I can't modify the gradient with the lottie editor.

### ISSUE THREAD

**Issue by bluefanc** [airbnb/lottie-android#1602]
I can't modify the gradient with the lottie editor.

It's a json file that was well modified before, but trying to modify the collar again, and it's loaded indefinitely.

I have to change gradiant end color.

#BB6B04 to #5B8B10

Help me please.

![image](https://user-images.githubusercontent.com/68847960/88527134-d5fb0d00-d037-11ea-86b8-c819c4fa7a4b.png)

![20200727_183325](https://user-images.githubusercontent.com/68847960/88527051-b4018a80-d037-11ea-8944-5ea05317181d.png)

![20200727_183621](https://user-images.githubusercontent.com/68847960/88527374-21adb680-d038-11ea-9bb3-ecc7d73f5042.png)

[capsule_out_sg_3.zip](https://github.com/airbnb/lottie-android/files/4981157/capsule_out_sg_3.zip)

**Comment by bluefanc** [comment]
attached my json file

**Comment by carstenhag** [comment]
Are you sure you posted this in the correct repository? This repo is the lottie-*android* repository. There's no preview or editor on this library.

**Comment by gpeal** [comment]
@bluefanc Lottiefiles isn't maintained by us. Please contact them about this.
