### ISSUE TITLE
Animation rendered is incorrect on Android. 

### ISSUE THREAD

**Issue by ubarua123** [airbnb/lottie-android#1605]
**If you don't use this template, your issue will be closed**

**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Describe the bug**
The animation rendered on Android is incomplete. I have attached the GIF which i created from the JSON using your preview website. And the other gif is the one rendered on the Andorid Device. 
If you see the last part, the animation does a little jump sort of animation towards the end. But in the android rendered, it doesn't. It just stays there. The jumping part doesn't render.

**What version of Lottie did you test this on?**
3.4.1

**What version of Android did you test this on?**
Android 29

**Steps To Reproduce**

There aren't any special steps. The code I used to put in my XML
```
<com.airbnb.lottie.LottieAnimationView
        android:id="@+id/loading_lottie_anim_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:lottie_autoPlay="true"
        app:lottie_loop="true"
        app:lottie_rawRes="@raw/lottie_loading"
        />
```

**Screenshots**
PFA. 
**NOTE** The android gif is a little janky since i converted from mp4.

*Lottie is supported and developed on nights and weekends. Please consider [sponsoring Lottie](https://github.com/users/gpeal/sponsorship) to prioritize this issue and help support this issue as well as future investments.*

![android_rendered](https://user-images.githubusercontent.com/8141308/89054771-ffd56c00-d376-11ea-9d4e-dcaecdc5cc53.gif)
![animation_on_web](https://user-images.githubusercontent.com/8141308/89054785-04018980-d377-11ea-9bcc-3d2a1a2ed30e.gif)

**Comment by gpeal** [comment]
@ubarua123 Please attach your animation. Are you sure you aren't using any unsupported features such as expressions?

**Comment by ubarua123** [comment]
@gpeal PFA json file used. 

[lottie_loading.json.zip](https://github.com/airbnb/lottie-android/files/5054902/lottie_loading.json.zip)

> Are you sure you aren't using any unsupported features such as expressions?

I haven't used any expressions or anything. 

My layout:
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:id="@+id/root_container"
    android:background="@color/white">

    <TextView
        android:id="@+id/loading_text"
        style="@style/TextAppearance.TextView.Black.15sp"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="8dp"
        android:visibility="gone"
        android:text="@string/please_wait"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/loading_lottie_anim_view" />

    <com.airbnb.lottie.LottieAnimationView
        android:id="@+id/loading_lottie_anim_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:lottie_autoPlay="true"
        app:lottie_loop="true"
        app:lottie_scale="0.7"
        app:lottie_rawRes="@raw/lottie_loading"
         />
</androidx.constraintlayout.widget.ConstraintLayout>
```
I don't even do start and stop animation. I just hide and show this layout.

**Comment by gpeal** [comment]
Lottie doesn't support elastic controllers. If you [check for warnings](http://airbnb.io/lottie/#/android?id=check-for-warnings), it'll let you know that.
