### ISSUE TITLE
Update To Version 3.0 and above，has ANR on device Android 5.1.1。

### ISSUE THREAD

**Issue by githubZYQ** [airbnb/lottie-android#1606]
1. Update To Version 3.0 and above，has ANR on device Android 5.1.1,but not found on device Android 9.0。
Use Version 2.7.0 or 2.8.0,  no such phenomenon has been observed.
2. This page has five lottieAnimationViews and one is play.
3.setRenderMode(RenderMode.HARDWARE);

Lottie log：
08-03 10:19:09.571 14307-14544/cn.nova.phone W/LOTTIE: Lottie doesn't support layer effects. If you are using them for  fills, strokes, trim paths etc. then try adding them directly as contents  in your shape. Found: [色相/饱和度]
08-03 10:19:09.571 14307-14544/cn.nova.phone W/LOTTIE: Lottie doesn't support layer effects. If you are using them for  fills, strokes, trim paths etc. then try adding them directly as contents  in your shape. Found: [色相/饱和度]
08-03 10:20:21.016 14307-14737/cn.nova.phone W/LOTTIE: Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().
08-03 10:20:23.003 14307-14737/cn.nova.phone W/LOTTIE: Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().
08-03 10:20:24.343 14307-14737/cn.nova.phone W/LOTTIE: Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().
08-03 10:20:24.343 14307-14737/cn.nova.phone W/LOTTIE: Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().

If you have good Suggestions and discoveries, please let me know. Thank you!

**Comment by githubZYQ** [comment]
Supplement: Such phenomenon has been observed on device android 6.0.
To solve:
When add this code ,  no such phenomenon has been observed（Lottile 3.4.0 and Device with Anroid 5.1.0 or 6.0）.
`if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.M) {
            mLottieAnimationView.setRenderMode(RenderMode.SOFTWARE);
        }else {
            mLottieAnimationView.setRenderMode(RenderMode.HARDWARE);
        }`
So I think it hanppened with above Version 3.0.0,setRenderMode(RenderMode.HARDWARE),It is not compatible with Anroid 5.1.0 or 6.0.
I hope Lottie can fix the above question in Version 3.5.0+.
If you have good Suggestions and discoveries, please let me know. Thank you!

**Comment by joe-ifit** [comment]
I am also seeing this issue on Android 5.1 with Lottie 3.0.6.  If I downgrade to 2.7 the animation starts working.  I tried your `setRenderMode` workaround and that did not fix it for me.

**Comment by githubZYQ** [comment]
Did you use app:lottie_fileName in xml file? If so, use “setAnimation” to set json file could help you.

**Comment by gpeal** [comment]
@githubZYQ @joe-ifit What is the stack for the ANR?

**Comment by joe-ifit** [comment]
I'm seeing this on Xamarin.Android stack

**Comment by githubZYQ** [comment]
@gpeal ANR:
`08-11 09:29:40.708 499-519/? E/ActivityManager: ANR in cn.nova.phone (cn.nova.phone/.ui.MainActivity)
    PID: 3319
    Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 47.  Wait queue head age: 5506.9ms.)
    Load: 1.69 / 0.79 / 0.29
    CPU usage from 6431ms to 1115ms ago:
      68% 95/mediaserver: 57% user + 11% kernel / faults: 473 minor
      23% 3319/cn.nova.phone: 13% user + 9.9% kernel / faults: 17884 minor 1 major
      7.8% 86/surfaceflinger: 2% user + 5.8% kernel / faults: 652 minor
      6% 3833/cn.nova.phone:channel: 4.5% user + 1.5% kernel / faults: 2168 minor
      5.4% 499/system_server: 1.5% user + 3.9% kernel / faults: 2797 minor 1 major
      2.4% 3527/logcat: 1.1% user + 1.3% kernel / faults: 8 minor
      2% 81/logd: 0.5% user + 1.5% kernel / faults: 3 minor
      1.8% 3778/cn.nova.phone:channel: 0.9% user + 0.9% kernel / faults: 3064 minor 1 major
      1.5% 101/flush-8:1: 0% user + 1.5% kernel / faults: 209 minor
      0.9% 79/flush-8:2: 0.1% user + 0.7% kernel / faults: 75 minor
      0.7% 977/com.eg.android.AlipayGphone: 0.3% user + 0.3% kernel / faults: 633 minor 1 major
      0% 3/ksoftirqd/0: 0% user + 0% kernel
      0.1% 6/kworker/u8:0: 0% user + 0.1% kernel
      0.1% 7/rcu_preempt: 0% user + 0.1% kernel
      0.1% 16/ksoftirqd/2: 0% user + 0.1% kernel
      0.1% 20/ksoftirqd/3: 0% user + 0.1% kernel
      0.1% 30/kworker/0:1: 0% user + 0.1% kernel
      0% 58/kworker/3:1: 0% user + 0% kernel
      0.1% 75/jbd2/sdb3-8: 0% user + 0.1% kernel
      0.1% 91/netd: 0% user + 0.1% kernel / faults: 56 minor
      0% 594/com.android.systemui: 0% user + 0% kernel / faults: 71 minor
      0% 1411/com.eg.android.AlipayGphone:push: 0% user + 0% kernel / faults: 16 minor 1 major
    34% TOTAL: 23% user + 11% kernel + 0% iowait + 0.4% softirq
    CPU usage from 3229ms to 3742ms later:
      9.8% 499/system_server: 0% user + 9.8% kernel / faults: 285 minor
        5.8% 510/FinalizerDaemon: 0% user + 5.8% kernel
        1.9% 517/SensorService: 0% user + 1.9% kernel
        1.9% 519/ActivityManager: 0% user + 1.9% kernel
        1.9% 525/Thread-28: 0% user + 1.9% kernel
      1.6% 95/mediaserver: 0% user + 1.6% kernel
    4.5% TOTAL: 0.5% user + 4% kernel
08-11 09:29:40.762 3319-3377/? E/crashsdk: ANR occurred in process: cn.nova.phone
08-11 09:29:53.667 499-519/? I/ActivityManager: Skipping duplicate ANR: ProcessRecord{1f48e15d 3319:cn.nova.phone/u0a165} executing service cn.nova.phone/com.umeng.message.UmengMessageCallbackHandlerService
`

**Comment by githubZYQ** [comment]
After set “.json” in code instead of in xml，and "setRenderMode(RenderMode.SOFTWARE)",ANR didn't happen again.
![image](https://user-images.githubusercontent.com/20163522/89847698-300edd00-dbb7-11ea-8a0e-73009e482976.png)

**Comment by gpeal** [comment]
Hardware acceleration varies greatly device to device, Android version to Android version, and animation to animation. It may always be necessary to fall back to software rendering depending on the combination of those 3 and Lottie can't definitively know which one is best so falling back to software rendering for older devices is probably best here.

**Comment by githubZYQ** [comment]
Thank you very much！
