### ISSUE TITLE
Allow change of gradient colors after animation has started

### ISSUE THREAD

**Issue by jobernolte** [airbnb/lottie-android#1608]
** If you don't use this template, your issue will be closed **

**Is your feature request related to a problem? Please describe.**
We have a use case, where the colors of gradient must be changed multiple times after an animation has been started. Simply replacing the value callback doesn't help, as GradientFillContent hashes internally a LinearGradient object. This hashed object is not removed from the hash, when we replace the callback and change the colors.

**Describe the solution you'd like**
Setting a new value callback for a gradient should replace the existing gradient.

**Describe alternatives you've considered**
My current workaround is: 
* Call clearComposition() on LottieDrawable
* Set the new value callback
* Call setComposition(..) on LottieDrawable with the existing LottieComposition

**Comment by gpeal** [comment]
You can, actually!
Here is an example:
https://github.com/airbnb/lottie-android/blob/b7bd15c7a7bbd9f0f576170937b11a69be485527/LottieSample/src/androidTest/java/com/airbnb/lottie/samples/LottieTest.kt#L694

It uses [dynamic properties](http://airbnb.io/lottie/#/android?id=dynamic-properties)

**Comment by gpeal** [comment]
@jobernolte I would accept a PR for this.
