### ISSUE TITLE
java.lang.AssertionError

### ISSUE THREAD

**Issue by Android-Adam** [airbnb/lottie-android#1609]
** If you don't use this template, your issue will be closed **

**Describe the bug**

1 java.lang.IllegalStateException:Unable to parse composition
--
2 com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:68)
3 ......
4 Caused by:
5 java.lang.AssertionError:
6 android.util.JsonReader.peek(JsonReader.java:363)
7 android.util.JsonReader.expect(JsonReader.java:308)
8 android.util.JsonReader.beginObject(JsonReader.java:293)
9 com.airbnb.lottie.parser.LottieCompositionParser.parse(LottieCompositionParser.java:42)
10 com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSync(LottieCompositionFactory.java:229)
11 com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:163)
12 com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:157)
13 com.airbnb.lottie.LottieCompositionFactory.fromAssetSync(LottieCompositionFactory.java:100)
14 com.airbnb.lottie.LottieCompositionFactory$1.call(LottieCompositionFactory.java:81)
15 com.airbnb.lottie.LottieCompositionFactory$1.call(LottieCompositionFactory.java:79)
16 java.util.concurrent.FutureTask.run(FutureTask.java:266)
17 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
18 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
19 java.lang.Thread.run(Thread.java:784)

**What version of Lottie did you test this on?**

com.airbnb.android:lottie:2.7.0

**What version of Android did you test this on?**

android 8.0

**Comment by Android-Adam** [comment]
I know there are similar problems before, but the solution I need.Please tell me directly how to solve it, thank you

**Comment by gpeal** [comment]
Please attach your animation? It looks like you're trying to parse an invalid json file.

**Comment by Android-Adam** [comment]
> Please attach your animation? It looks like you're trying to parse an invalid json file.

My json is valid, this problem will only appear on Android 8.0 and 8.1 systems

**Comment by gpeal** [comment]
@Android-Adam I can't help you without more information then. 3.1.0 has a totally new streaming json parser so I suggest you upgrade and see if that resolves your issue. (3.4.1 is the latest version)
