### ISSUE TITLE
Animation gets clipped when view has a fixed size

### ISSUE THREAD

**Issue by gpeal** [airbnb/lottie-android#161]
Requires more investigation. Likely due to masks/mattes + saveLayer/drawBitmap.

@qmetzler-luna

**Comment by gpeal** [comment]
@qmetzler-luna I know what's going on. You can work around this by changing your composition size to the display size you want. The composition size in px will be natively converted to dp when rendered so change your composition to be 75px.

**Comment by gpeal** [comment]
This will be released with 1.5.2

**Comment by qmetzler-luna** [comment]
@gpeal Thanks, it's working a lot better but if I downsize too much I'm still having some issue
see attached with 45dp for example.
[analytics.aep.zip](https://github.com/airbnb/lottie-android/files/805928/analytics.aep.zip)

**Comment by gpeal** [comment]
@qmetzler-luna I just released 1.5.2 which is definitely an improvement with your samples. Thanks for sending them by the way.
Analytics is still not matting perfectly because you have visible matte layers. Can you try altering your animation so that matte layers don't need to be visible?
