### ISSUE TITLE
Android OS-5 and below Android OS does't display proper Scale animation on Text 

### ISSUE THREAD

**Issue by axitasavani** [airbnb/lottie-android#1610]
** If you don't use this template, your issue will be closed **

**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Describe the bug**

**What version of Lottie did you test this on?**
3.4.0

**What version of Android did you test this on?**
Android Version : 5,6,7,8,9,10

**Steps To Reproduce**

1. Just pick aftereffects JSON 
2. Render in Android Device
3. os-5 and below doesn't display proper animation but in version 6 and above display proper animation
4. please check below zip folder that have JSON, and that two video (Android OS_5_Device, AndroidOS_7_Device)
5. please check carefully that OS-5 Device doesn't display proper animation of text then another way OS-7 is displaying proper animation.
6. As I applied the same animation On any Shape or Image then it works perfectly in all Android OS.
7. Can you please suggest any solution or any hint that what is the issue in only OS-5 or below OS...
 
**JSON File, ScreenRecoder Video of Android Device**
[lottiejson_screenrecordervideo.zip](https://github.com/airbnb/lottie-android/files/5111935/lottiejson_screenrecordervideo.zip)

*Lottie is supported and developed on nights and weekends. Please consider [sponsoring Lottie](https://github.com/users/gpeal/sponsorship) to prioritize this issue and help support this issue as well as future investments.*

**Comment by AxitaKathiriya** [comment]
Face the same issue In OS 5. Can Anyone Provide solution of this issue?

**Comment by gpeal** [comment]
I believe this was fixed in 3.4.4 with https://github.com/airbnb/lottie-android/pull/1635

![image](https://user-images.githubusercontent.com/1307745/103142421-9b190600-46b7-11eb-9a07-71a9af010bd8.png)
