### ISSUE TITLE
JsonEncodingException

### ISSUE THREAD

**Issue by SagittariusSum** [airbnb/lottie-android#1611]
**Read this or your issue will be closed**

* Before opening a new issue, look through existing issues for duplicates.
* Simplify your animation to the simplest animation that reproduces your issue.
* Zip your After Effects AEP file and attach it. Your issue will be auto-closed if it doesn't have an AEP or no explicit reason otherwise is given.
* If you don't know English, run your issue through Google Translate.
* If you leave the template text in your issue, it will be closed.

**Comment by gpeal** [comment]
Please reopen with the animation that is failing.

**Comment by zhuangzhitu** [comment]
> Please reopen with the animation that is failing.

What does this mean, please

**Comment by gpeal** [comment]
@zhuangzhitu The stack trace indicates that Lottie was fed invalid json. This is likely not a Lottie bug
