### ISSUE TITLE
Slow animation on older devices (on 2.8.0 it works ok)

### ISSUE THREAD

**Issue by lorenc-tomasz** [airbnb/lottie-android#1627]
Hi,
I have this animation: https://1drv.ms/u/s!AuHh1Cwn9BGwt_9p2YXLHIQFjeSkMg?e=x7U1AI It works OK with version 2.8.0 but on any version higher than that the animation is very slow on older devices. I looks like it doesn't have hardware acceleration. Forcing it on newer libs doesn't help. 

There is full animation we use on iOS: https://1drv.ms/u/s!AuHh1Cwn9BGwt_9owjlCzchZV4aWDA?e=kzZlFA It bigger but there is no problem with it on iOS. 

PS I have only JSON files :(

**Comment by gpeal** [comment]
@lorenc-tomasz When you say "it looks like it doesn't have hardware acceleration" what do you mean, exactly?

**Comment by lorenc-tomasz** [comment]
Hi,
sorry for late answer. I have forgotten to test it with `setRenderMode(RenderMode.Software)`. So it's works much better with Software render mode but still a little bit worse than on 2.8.0. Still on newer devices automode works OK, but we need to support older devices as well, so probably I will go with Software mode, but I would be greatfull if you would find some time to check this animation. 

Kind regards,
Tom

**Comment by gpeal** [comment]
@lorenc-tomasz I'm not seeing any performance issues on my 5.0 test devices. Feel free to investigate this further and open a PR if you think further action is needed. There have been no other reports of performance regressions.
