### ISSUE TITLE
Min SDK version

### ISSUE THREAD

**Issue by angeldevil** [airbnb/lottie-android#163]
The minSdkVersion is 14 in **build.gradle**. But it says **Lottie supports Jellybean (API 16) and above.** in README. So which is the min SDK level?

**Comment by gpeal** [comment]
@angeldevil good catch. It used to be 16. I lowered it to 14 and never changed the readme.

**Comment by handstandsam** [comment]
The `minSdk` is now 16 as of Feb 14, 2018.

Commit: https://github.com/airbnb/lottie-android/commit/a212bc8d8c5737a46deafb098e273937d77477b9

`I had to bump the minSdk to 16 to support Choreographer.`
