### ISSUE TITLE
Red bounding box (on v3.4.3)

### ISSUE THREAD

**Issue by GuilhE** [airbnb/lottie-android#1640]
**Describe the bug**

My animations have a "debug red bounding box" that sometimes disappear when the animation is finished. 

**Steps To Reproduce**

I've updated to the latest version, 3.4.3 and now my animations have a "debug red bounding box".
If I downgrade they disappear (does this exclude possible .json  error/misconfiguration)?

`const val lottie: String = "3.4.3"`:
![sample](https://user-images.githubusercontent.com/2677139/94921077-72fe7a00-04af-11eb-8df6-253777082cb1.png)

`const val lottie: String = "3.4.2"`:
![sample2](https://user-images.githubusercontent.com/2677139/94921327-059f1900-04b0-11eb-8e16-203037c579e7.png)

What could it be? 🤔 
I didn't found any mention about it in the release notes.

Thanks.

**Comment by gpeal** [comment]
@GuilhE This is a regression. I'll put up 3.4.4 shortly. For now, please use 3.4.2.

**Comment by gpeal** [comment]
3.4.4 has been released. It should be available once Maven Central picks it up.
