### ISSUE TITLE
Can we add lottie json inside some package in assets instead of directly adding to asset folder?

### ISSUE THREAD

**Issue by surabhi2789** [airbnb/lottie-android#1641]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gpeal** [comment]
Yes, you can
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L810
You can also put it in res/raw and use `R.raw.anim_name`
