### ISSUE TITLE
Files may contain hardcoded sensitive information like usernames, passwords, keys etc.

### ISSUE THREAD

**Issue by RanaTahirSohail** [airbnb/lottie-android#1643]
Our security code analysis raises this error "Files may contain hardcoded sensitive information like usernames, passwords, keys
etc". Can you please provide any security certificate or your reviews about this issue. Thanks

implementation 'com.airbnb.android:lottie:3.2.2'

**Comment by gpeal** [comment]
@RanaTahirSohail Can you include a concrete example of the issue?
