### ISSUE TITLE
addAnimatorPauseListener() support

### ISSUE THREAD

**Issue by Jean-Daniel** [airbnb/lottie-android#1644]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**Is your feature request related to a problem? Please describe.**
Using lottie for Android 3.4.4, I'm trying to play a sound in sync with an animation. But I didn't find a reliable way to detect when the animation pause/resume, as the `LottieAnimationView` does not provide callback on these actions.

**Describe the solution you'd like**
Android provide an `Animator.AnimatorPauseListener` interface alongside `Animator.AnimatorListener`.

`LottieAnimationView` API already supports `Animator.AnimatorListener`, but it does not supports `Animator.AnimatorPauseListener`

Supporting this kind of listener would be a natural extension of the `LottieAnimationView` API.

`LottieAnimationView.addAnimatorPauseListener()`
`LottieAnimationView.removeAnimatorPauseListener()`

**Describe alternatives you've considered**
Actually, I'm subclassing LottieAnimationView to generate and dispatch pause/resume events when pauseAnimation()/resumeAnimation() is invoked, but it does not allow me to reuse the `Animator.AnimatorPauseListener` interface as I don't have access to the `ValueAnimator` that should be passed to the callback, and it would be better if implemented directly on the underlying drawable.

**Comment by linean** [comment]
I ran into a similar problem recently. Based on current implementation it should be very easy to plug in `AnimatorPauseListener` .
