### ISSUE TITLE
Fallback resource for accessibility option "Remove animations"

### ISSUE THREAD

**Issue by rafamatias** [airbnb/lottie-android#1646]
**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Is your feature request related to a problem? Please describe.**
Yes, it is. 
While working with AOSP, I had an issue when an accessibility option called "Remove animations" was enabled. It seems even with the attribute `app:lottie_fallbackRes`, there is no preview or alternative view. 

Millions of users will see this tutorial, thus, we could not ignore people that need this accessibility option.

**Describe the solution you'd like**
1. Have a new attribute name `lottie_accessibilityRes`;
2. or make `lottie_fallbackRes` works for this accessibility case.

**Describe alternatives you've considered**
For both cases, `LottieAnimationView` should be able to provide a static version of the current animation (preview).

**Additional context**
To handle this case, I needed to use `ImageView#setImageResource` or drawable for each instance of `LottieAnimationView`.
I know Lottie already uses the setting `Settings.Global#ANIMATOR_DURATION_SCALE` and does not play animations based on that value.

Thank you.

**Comment by gpeal** [comment]
@rafamatias exciting to see Lottie used in AOSP 😄  When you talk about the remove animations accessibiliy setting, are you referring to setting the animation scale to 0 in developer options?

**Comment by rafamatias** [comment]
Hi @gpeal. Yes, it's correct. The setting animator_duration_scale.

**Comment by gpeal** [comment]
@rafamatias In general, I've been trying to keep the API surface area as small as possible for maintenance reasons. This seems like something that you could build into the AOSP setup fairly easily. Lottie uses [this utils function](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/utils/Utils.java#L261) to get the animation scale and then snaps to the end of the animation and calls the correct listeners.

**Comment by gpeal** [comment]
@rafamatias Any suggestions here?

**Comment by rafamatias** [comment]
Hi @gpeal. Yes, we could get the animation scale value with this utility class, but we still need to handle it and replace the animation using `ImageView.setImageResource`. For complex cases, when we need to change animation many times using a same view, we need to handle this issue when the accessibility option is enabled.

If we intend to keep Lottie as simple as possible, probably we don't need a workaround for this case. I thought it could be something like `app:lottie_fallbackRes`.

I can investigate this issue and provide a patch. What do you think?

Thank you.

**Comment by gpeal** [comment]
@rafamatia Fallback [already exists](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/res/values/attrs.xml#L9) for when loading an animation via a URL or parsing an animation fails and is usually some sort of failure/no internet src.

This API would have to very clearly indicate that it will be used when the animation scale is 0/animations are disabled.

**Comment by gpeal** [comment]
I'm going to close this due to lack of activity but if you want to reconsider this, please propose a new specific API that would solve the requirement above.
