### ISSUE TITLE
Caused by: java.lang.NullPointerException: Attempt to read from field 'com.airbnb.lottie.LottieDrawable com.airbnb.lottie.model.layer.BaseLayer.lottieDrawable' on a null object reference

### ISSUE THREAD

**Issue by w2hhda** [airbnb/lottie-android#1650]
I have a problem on android 9:

10-17 16:12:27.687 E/AndroidRuntime(11897): Caused by: java.lang.NullPointerException: Attempt to read from field 'com.airbnb.lottie.LottieDrawable com.airbnb.lottie.model.layer.BaseLayer.lottieDrawable' on a null object reference
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at com.airbnb.lottie.model.layer.CompositionLayer.setProgress(CompositionLayer.java:135)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at java.lang.reflect.Method.invoke(Native Method)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at com.lody.whale.WhaleRuntime.invokeOriginalMethodNative(Native Method)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at com.lody.whale.WhaleRuntime.invokeOriginalMethod(WhaleRuntime.java:70)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at com.lody.whale.xposed.XposedBridge.invokeOriginalMethod(XposedBridge.java:294)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at com.lody.whale.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:239)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at com.lody.whale.WhaleRuntime.handleHookedMethod(WhaleRuntime.java:62)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at com.airbnb.lottie.model.layer.CompositionLayer.setProgress(Native Method)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at com.airbnb.lottie.LottieDrawable$1.onAnimationUpdate(LottieDrawable.java:74)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at com.airbnb.lottie.utils.BaseLottieAnimator.notifyUpdate(BaseLottieAnimator.java:88)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at com.airbnb.lottie.utils.LottieValueAnimator.setComposition(LottieValueAnimator.java:150)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:217)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:504)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:81)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:79)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at com.airbnb.lottie.LottieTask.addListener(LottieTask.java:80)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at com.airbnb.lottie.LottieAnimationView.setCompositionTask(LottieAnimationView.java:481)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at com.airbnb.lottie.LottieAnimationView.setAnimation(LottieAnimationView.java:389)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at java.lang.reflect.Method.invoke(Native Method)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at com.lody.whale.WhaleRuntime.invokeOriginalMethodNative(Native Method)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at com.lody.whale.WhaleRuntime.invokeOriginalMethod(WhaleRuntime.java:70)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at com.lody.whale.xposed.XposedBridge.invokeOriginalMethod(XposedBridge.java:294)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at com.lody.whale.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:239)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at com.lody.whale.WhaleRuntime.handleHookedMethod(WhaleRuntime.java:62)
10-17 16:12:27.687 E/AndroidRuntime(11897): 	at com.airbnb.lottie.LottieAnimationView.setAnimation(Native Method)

**Comment by gpeal** [comment]
@w2hhda It looks like there is a lot going on here in which the Xposed framework is intercepting various things. Considering nobody else has had this issue, this is almost certainly an issue with whatever Xposed modules are active.

**Comment by aliceInWahed** [comment]
hi there, I had the same issues on mostly Android 9
<img width="626" alt="Screenshot 2022-05-26 at 1 36 07 PM" src="https://user-images.githubusercontent.com/79141836/170425201-3903d891-8a87-470d-9291-66559689ec54.png">
