### ISSUE TITLE
Animation can't resume when ancestor view visibility changed

### ISSUE THREAD

**Issue by tuesda** [airbnb/lottie-android#1653]
LottieAnimationView should try to resume animation in onVisibilityAggregated like onVisibilityChanged which paused in onDetachFromWindow(), because when ancestor view's visibility changed, only `LottieAnimationView.onVisibilityAggregated` method is called.

**Comment by gpeal** [comment]
@tuesda onVisibilityAggregated was only added in API 24 so Lottie would have to fall back to the current behavior for <24. I'm concerned that engineers testing their apps will only test on 24+ and never realize that things are broken on older devices. For that reason, I'm leaning towards the slightly suboptimal but more consistent behavior. Thoughts?

**Comment by tuesda** [comment]
@gpeal  ok, appreciate your response.
