### ISSUE TITLE
TextDelegate private method can't be overridden

### ISSUE THREAD

**Issue by itopenup** [airbnb/lottie-android#1661]
https://github.com/airbnb/lottie-android/blob/d3dd2c87b2ec61b202c9837d1aa7c2a3f61b22f6/lottie/src/main/java/com/airbnb/lottie/TextDelegate.java#L47

**Comment by gpeal** [comment]
@itopenup To use TextDelegate, you call `setText("INPUT", "OUTPUT")`. `getText()` is called internally by Lottie to get the output text for the given input text.

The input text is the original text from After Effects. The output text is the text you want to replace it with.
