### ISSUE TITLE
Changing raw res of setAnimation() on LottieAnimationView causes a noticeable flicker

### ISSUE THREAD

**Issue by LassassinX** [airbnb/lottie-android#1665]
I have a LottieImageView into which I wish to show multiple animations through multiple .json files depending on the user. However, when I try to change it using LottieAnimationView.setAnimation(); the animation becomes completely invisible for about a second and then the next animation loads in. Is there anyway to make this transition flawless by somehow preloading the animation ? A good step by step solution in java is very much appreciated. 

**What version of Lottie did you test this on?**
3.4.2

**What version of Android did you test this on?**
Android 10.0

**Steps to reproduce the behavior:**

1. Make a LottieAnimationView
2. Have atleast 2 .json files in res/raw
3. Use LottieAnimationView.setAnimation() on another json
4. You will see that the animation goes away completely for about a second before loading the new one

**Comment by gpeal** [comment]
@LassassinX Yes, Lottie can't synchronously show a new animation. It has to load and parse the JSON file which takes several MS and must be done on a background thread. However, Lottie has a fairly robust internal caching mechanism.

If you know an animation will be used, just call `LottieCompositionFactory.fromRasRes(R.raw.your_animation)` at point ~1s or more prior to needing it and it should fix this issue.

**Comment by LassassinX** [comment]
Hello, I have implemented what you have said. However, this solution is pretty inconsistent. Sometimes I see a slight flicker, sometimes I do not. My code for a simple test is as follows : 

        new Handler().postDelayed(() -> {
            LottieCompositionFactory.fromRawRes(this,R.raw.rocket_repeat);
        }, 1700);

        new Handler().postDelayed(() -> {
            animationView.setAnimation(R.raw.rocket_repeat);
            animationView.playAnimation();
        }, 2900);

        new Handler().postDelayed(() -> {
            LottieCompositionFactory.fromRawRes(this , R.raw.rocket_fail);
        }, 6500);

        new Handler().postDelayed(() -> {
            animationView.setAnimation(R.raw.rocket_fail);
            animationView.playAnimation();
        }, 8000);

        new Handler().postDelayed(() -> {
            animationView.setVisibility(View.GONE);
        }, 8800);

TIA

**Comment by gpeal** [comment]
@LassassinX It's going to depend on how fast your phone is or how large the json file is.
No need to post delay the factory methods. Just call them all at the beginning. You can even do it earlier in your application if you think you'll use the animations. There isn't much overhead to proactively parse them.
