### ISSUE TITLE
Add dynamic property for text alignment and text style

### ISSUE THREAD

**Issue by Luosoha** [airbnb/lottie-android#1666]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**Is your feature request related to a problem? Please describe.**
- I've been using TextDelegate to change the text of Lottie animations, and the justification is always center by default. I want to make it left aligned but can't find a way to do it. So it would be nice to have a dynamic property like TEXT_ALIGNMENT or TEXT_JUSTIFICATION to solve this.
- Also I am trying to adjust the style of the text to _itablic_, **bold** and **_italic bold_** so a dynamic property like TEXT_STYLE would be a big help.

If you have any workarounds to solve these problems please give me an advice. Thanks.

**Describe the solution you'd like**
- Add a dynamic property for text alignment or a way to change the justification in **DocumentData**:
`@SuppressWarnings("WeakerAccess") public final Justification justification;`
- Add a dynamic property for text style:
`Typeface typeface = lottieDrawable.getTypeface(font.getFamily(), font.getStyle());`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gpeal** [comment]
@Luosoha Any interest in making a PR for this?

**Comment by Luosoha** [comment]
@gpeal I tried to change the text justification but it seems to break the animation, could you help me on this?
Also here is a PR for the text style: https://github.com/airbnb/lottie-android/pull/1678/files

**Comment by Luosoha** [comment]
@gpeal Since I can't make a reasonable PR for this issue, can you support me with this feature?
Thanks!
