### ISSUE TITLE
Path Expression

### ISSUE THREAD

**Issue by hananafif** [airbnb/lottie-android#1668]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i want to loop my path properties in lottie, path isn't support `loopOut()` or `loopIn()`

**Describe the solution you'd like**
Loop on path is using this expression `valueAtTime(time % key(numKeys).time)` but it's not support on lottie exported files

**Describe alternatives you've considered**
i create another layer, then mask it with my path

**Comment by gpeal** [comment]
Lottie Android can't do expressions because it's a javascript based programming language and there is no trivial way to evaluate them on Android.
