### ISSUE TITLE
Improve the performance of mattes and masks

### ISSUE THREAD

**Issue by sureMOE** [airbnb/lottie-android#167]
This seems to be an issue that's relegated to Android playback of JSON files that isn't reproducible on iOS. When using track mattes from After Effects, frame rates just plummet. Not sure what exactly is going on, but wondering if anybody else has seen same issues.

**Comment by gpeal** [comment]
@sureMOE This is a known issue right now and isn't trivial to solve on Android but I'm playing around with several options.
One thing you can do to help is to reduce the size of your composition, reduce the number of layers with a matte or mask, or find an alternative way to achieve the same visual effect without them.
Lottie will render your composition at the dp equivalent of the composition size. So if you set your composition to 500x500, it will be roughly 1500x1500px on most devices. Each layer with a mask or matte has to do a bitmap write of that size on every frame.
