### ISSUE TITLE
Why this lottie file is rendered fragmentary on some phones?

### ISSUE THREAD

**Issue by jhwsx** [airbnb/lottie-android#1675]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Describe the bug**
As attached [anim_video_extract.zip](https://github.com/airbnb/lottie-android/files/5514331/anim_video_extract.zip), the lottie file is rendered perfectly on most of our test devices, however, is rendered fragmentary on a few test devices, such as OPPO OPPO R9sk Android 6.0.1, API 23, Motorola XT1650 Android 8.0.0, API 26.

**What version of Lottie did you test this on?**
3.5.0
**What version of Android did you test this on?**
6.0.1,8.0.0
**Steps To Reproduce**
1. I use this lottie in xml like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <data>

    </data>

    <LinearLayout
        android:id="@+id/container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:background="@drawable/common_background">
        <com.airbnb.lottie.LottieAnimationView
            android:id="@+id/lottie_animation_view"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center_horizontal"
            app:lottie_autoPlay="true"
            app:lottie_loop="true"
            app:lottie_rawRes="@raw/anim_video_extract" />
    </LinearLayout>
</layout>
```
Then, I inflate this xml into an empty activity. 
These are all my app's codes.
2. Install the apk on my test device;
3. Start my app, then the bug happens.

**Screenshots**
Expected result:
![Screenshot from 2020-11-10 10-40-44](https://user-images.githubusercontent.com/19379538/98620940-37be5900-2341-11eb-9c0d-e2b846a7c08f.png)
Actual result:
![Screenshot from 2020-11-10 10-18-30](https://user-images.githubusercontent.com/19379538/98619415-2758af00-233e-11eb-924a-d5d2e6ed92c3.png)

**Comment by gpeal** [comment]
@jhwsx I was able to reproduce this on the Moto XT1650. It works if you set the render mode to software but I'll look into why this is happening.

**Comment by jhwsx** [comment]
@gpeal Thanks a billion.
