### ISSUE TITLE
Animation play well on web, but incomplete on iOS

### ISSUE THREAD

**Issue by cuicmex** [airbnb/lottie-android#1676]
I have a json file for lottie animation.
https://lottiefiles.com/share/f44vtncy
https://assets3.lottiefiles.com/packages/lf20_f44vtncy.json

Using lottiefiles.com, the animation plays fine, but when I tested the same animation on LottieF

iles iOS, it doesn't show all elements in the animation. (The rays coming out of the star are not all shown)

LottieFiles iOS version: 1.2.1

1. Load animation in lottiefiles.com
2. Read animation QR with LottieFiles iOS
3. See the difference between the rays coming out from the star 

The attached zip contain the mov file showing both cases.
[RPReplay_Final1604660837.MOV.zip](https://github.com/airbnb/lottie-android/files/5516424/RPReplay_Final1604660837.MOV.zip)

**Comment by gpeal** [comment]
I think you meant to post this on https://github.com/airbnb/lottie-ios
