### ISSUE TITLE
addAnimatorListener Doens't give call backs on 2G networks

### ISSUE THREAD

**Issue by yaseen2591** [airbnb/lottie-android#168]
I'm using the addAnimationListener to get callback from onAnimationEnd method . It works fine unless it has 2G or very slow internet connection

        `animationView.addAnimatorListener(new Animator.AnimatorListener() {
                    @Override
                    public void onAnimationStart(Animator animator) {

                    }

                    @Override
                    public void onAnimationEnd(Animator animator) {
                        Log.d(TAG, "Animation Completed");
                         startNextActivity();
                    }

                    @Override
                    public void onAnimationCancel(Animator animator) {
                        Log.d(TAG, "Animation cancelled Main Activity");
                    }

                    @Override
                    public void onAnimationRepeat(Animator animator) {

                    }
                });`

**Comment by gpeal** [comment]
@yaseen2591 Lottie doesn't do anything network related. My guess is that the issue lies somewhere else in your code.
