### ISSUE TITLE
Dynamic Text alignment shifting

### ISSUE THREAD

**Issue by samiam2020** [airbnb/lottie-android#1682]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Describe the bug**
The text in this animation is not rendering correctly. One group is suppose to be right aligned and the other group is supposed to be left aligned, but it's flipping. I need the text to be dynamic rather than baked compound paths because we are going to be switching out numbers and the headline.

**What version of Lottie did you test this on?**
I'm testing this on the most recent version of Lottiefiles think that's Lottie version 3.4, I'm a motion designer trying to QA for the developer, so my coding knowledge is limited

**What version of Android did you test this on?**
Android v10

**Steps To Reproduce**

1. upload JSONs to Lottiefiles and preview on android phone. '...'

**Screenshots**
[TroubleShooting.zip](https://github.com/airbnb/lottie-android/files/5551296/TroubleShooting.zip)
![how type supposed to stack shot 2](https://user-images.githubusercontent.com/58047407/99347641-6ad68000-284c-11eb-86d7-7aec8c8da66f.png)
![how type supposed to stack shot 1](https://user-images.githubusercontent.com/58047407/99347644-6e6a0700-284c-11eb-99e3-ad34fc35d8d7.png)
![how type appears on android](https://user-images.githubusercontent.com/58047407/99347675-7de95000-284c-11eb-9325-308cdbbfff1c.png)

**Comment by dion-george** [comment]
The latest version is 3.5.0
Could you update and check once?

**Comment by samiam2020** [comment]
@dion-george Thanks, that got us to a workable solution. We were able to find a work around with your help. There is still the odd requirement of us needing to place the font group in an location off the canvas to get it to align correctly but at least it's working.
Have to position off canvas:
![Screen Shot 2020-11-17 at 10 35 29 PM](https://user-images.githubusercontent.com/58047407/99496353-f3c2e980-2928-11eb-84c1-64d2573a84f2.png)
 
To get text to appear like we wanted it.

**Comment by dion-george** [comment]
Awesome, did you do anything more, or just updated to the latest version?

**Comment by samiam2020** [comment]
@dion-george updated to latest version. and then because of the way after effects handles anchor points we had to shift it off the canvas. Another issue we were having was something with the fonts. we have two lines of text using 2 different weights (bold and Demi). For some reason it wasn't recognizing the correct font weights seemed like they were one level lower than we wanted them. Demi looked like regular, and bold looked like Demi we couldn't get a heavier weight. is there some issue with styling dynamic fonts? 

this is what we wanted it to look like:
![what we wanted](https://user-images.githubusercontent.com/58047407/99505532-cc264e00-2935-11eb-815f-34a279c57327.png)
this is what it was looking like: 
![looked like](https://user-images.githubusercontent.com/58047407/99505534-cd577b00-2935-11eb-9612-43f4dfe110f2.png)
