### ISSUE TITLE
Lottie Animation is slow when loading data with PagingDataAdapter and PagingDataSource

### ISSUE THREAD

**Issue by bogdanmunteanu** [airbnb/lottie-android#1687]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**Checklist**

1. Lottie Android version 3.5.0 
2.Android 10 
3. Huawei P30 Pro with hardware acceleration enabled

**Describe the bug**
I am working on an app in which the user logs in, the Main Activity is started via Intent and hosting multiple fragments. Two of these fragments contain PagingDataAdapters that load data and display the loading state with a LottieAnimationView. These fragments are instantiated at the same time , and my guess is that the LottieAnimationViews load the animation from the same json file (it's the same animation). These LottieAnimationViews load the animation very slow in this particular situation(loading when new activity is rendered). After that , if I trigger the animation , it performs good. 

Is there a specific setting that I'm missing here , reganding the configuration of Lottie ?

**Steps To Reproduce**
N/A

**Comment by gpeal** [comment]
@bogdanmunteanu Lottie will join any in-flight animations so if you have two screens or multiple rows in the same RecyclerView loading the same thing, it will only load and parse the json once.

If you think you might be loading a screen, you can preemptively call `LottieCompositionFactory.fromRawRes(context, R.raw.your_animation)` (or another factory method) anywhere in your application then it'll be pre-parsed and loaded when your screen starts.

**Comment by bogdanmunteanu** [comment]
@gpeal , thank you for your response. Can you give me an example of how to use the composition factory ? I've searched on previous issues where you mentioned this but couldn't find any examples.

**Comment by gpeal** [comment]
@bogdanmunteanu Just call that line of code from anywhere in your application without worrying about the return value. It will kick off an async job that will load, parse, and cache the animation so when you actually us it, it will be available immediately.

**Comment by bogdanmunteanu** [comment]
Good , will try and keep you updated. Thanks again for the response 👍

**Comment by bogdanmunteanu** [comment]
@gpeal , the result is the same. I'll leave some relevant code below.

`        <androidx.constraintlayout.widget.ConstraintLayout
            android:layout_width="300dp"
            android:layout_height="300dp"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent">

            <com.airbnb.lottie.LottieAnimationView
                android:id="@+id/activeOrdersAnimation"
                android:layout_width="48dp"
                android:layout_height="48dp"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                app:lottie_loop="true"
                app:lottie_speed="1" />

            <TextView
                android:id="@+id/actOrdersRefreshText"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:fontFamily="@font/poppins_light"
                android:padding="20dp"
                android:text="Orders are updating....please wait"
                android:textColor="@color/cafetino_orange_disabled"
                android:textSize="14sp"
                app:layout_constraintEnd_toEndOf="@+id/activeOrdersAnimation"
                app:layout_constraintStart_toStartOf="@+id/activeOrdersAnimation"
                app:layout_constraintTop_toBottomOf="@+id/activeOrdersAnimation" />
`. --- LottieAnimationView

in the Activity that is hosting the fragments , in onCreate: 
```
        LottieCompositionFactory.fromAsset(this, "CafetinoLogoRotate.json").addListener {
            loadingAnimation = it
        }
```

in the Fragment : 
` rvActiveOrders.visibility = View.GONE
            emptyListLayout.visibility = View.GONE
            actOrdersLoadingLayout.visibility = View.VISIBLE
            (activity as MainActivity).loadingAnimation?.let {
                activeOrdersAnimation.setComposition(it)
                activeOrdersAnimation.playAnimation()
            } ?: run {
                activeOrdersAnimation.visibility = View.GONE
            }`

**Comment by gpeal** [comment]
You don't have to manually store and set the composition. It is cached my Lottie under the hood. 
Simply call `LottieCompositionFactory.fromAsset(this, "CafetinoLogoRotate.json")` in your Activity and set `app:lottie_fileName="CafetineLogoRotate.json"` in your XML file.

Is this ViewPager shown right on app launch?

**Comment by bogdanmunteanu** [comment]
Actually , the fragments are in a FragmentPagerAdapter . And it's shown on activity start , yes.

**Comment by gpeal** [comment]
@bogdanmunteanu In that case, there isn't any advantage in pre-loading them in your Activity because your Activity and fragments start at the same time.

Ultimately, the animations have to be loaded from json and parsed which can't be done synchronously on the main thread. Given that, what would you propose Lottie do here?

**Comment by bogdanmunteanu** [comment]
Actually, I don't know:) I'll try to load the data in the activity and just observe in fragments, so that the fragments won't have so much to do.I think the problem lies in the fact that when Lottie is parsing the Json in the background , that thread is overwhelmed with feeding constant data from the paging data source. Another solution I'll try is dispatching the data feeding coroutine to a computation thread. Will keep you updated.Thanks.

**Comment by gpeal** [comment]
@bogdanmunteanu Not sure I follow. Phones have many cores and can run a _ton_ of threads these days.

**Comment by bogdanmunteanu** [comment]
@gpeal you can close the issue. Turns out that the issue was caused by a custom view that was leaking. Lottie ia working perfectly. Keep up the good work 💯
