### ISSUE TITLE
Rendering issue on mobile app

### ISSUE THREAD

**Issue by AdrienDuchateau** [airbnb/lottie-android#1694]
Hi!

I read similar issues on github, but I can't find a solution myself...
I created a Lottie: https://lottiefiles.com/share/1dr0wucb, preview looks fine on desktop browser, but it looks broken on the Lottie mobile app : [RPReplay_Final1606996906.MP4.zip](https://github.com/airbnb/lottie-android/files/5635892/RPReplay_Final1606996906.MP4.zip)

Here is the AE file:
[checkmark.aep.zip](https://github.com/airbnb/lottie-android/files/5635909/checkmark.aep.zip)

Any solution for this?

Thanks a lot!
Adrien

**Comment by gpeal** [comment]
Your animation uses multiple features that are unsupported on Android including expressions and some sort of layer effect (tracer le chemin?).
Please refer to [this table](http://airbnb.io/lottie/#/supported-features) for the supported features.

**Comment by AdrienDuchateau** [comment]
ok thanks for your quick answer!
