### ISSUE TITLE
Strange behaviour when mixing LottieCompositionFactory and static drawable

### ISSUE THREAD

**Issue by vellrya** [airbnb/lottie-android#1696]
**Checklist**

1. Fork this repository into your account. -
2. Reproduce your issue in the issue-repro module. Issues without a repro in the issue-repro 
   module may be auto-closed. -
_- Maybe I'll be lucky :)_

**Describe the bug**
I found strange behaviour when using LottieAnimationView with static image and LottieCompositionFactory.
Lottie version: 3.5.0

**Steps To Reproduce**

1. Load animation to LAV with LCF - works perfectly.
2. Load static image to LAV with Glide (or .setImageDrawable - same result) - no problem
3. Load the same animation object from p. 1 with the same cache key - oops, no animation, static image will stay in LAV.
I can change static image and repeat p. 3 many times, but animation from p.1 will not work anymore.

There is a bad temp solution I found: If I change cache key of p.1 animation or load other animation after static image, I can successfully play animation number 1 again. 
Also transitions "static-static" and "animation-animation" always have no problem.

Here the relevant logcat and code sample, please, take a look:

```
        <com.airbnb.lottie.LottieAnimationView
            android:id="@+id/resPreviewLAV"
            android:layout_width="150dp"
            android:layout_height="150dp"
            android:layout_centerInParent="true"
            android:translationY="@dimen/preview_translate_y"
            app:lottie_autoPlay="false"
            app:lottie_loop="true" />
```

```
if (res.animated) {
	println("animated resource:")
	val compositionCancellable = LottieCompositionFactory.fromZipStream(
		ZipInputStream(getPath(res), res.getResCacheKey()
	)
	println("Old composition: "+binding.resPreviewLAV.composition)
	compositionCancellable.addListener {
		println("compositionCancellable success")
		binding.resPreviewLAV.setComposition(it)
		binding.resPreviewLAV.playAnimation()
	}.addFailureListener {
		println("Fail in lottie")
		it.printStackTrace()
	}
} else {
	println("static resource:")
	Glide.with(this).load(getStaticPath(res))
		.fitCenter().centerInside().into(binding.resPreviewLAV)
}
```

Logcat with //comments

> I: Updated preview: ResModel(animated=true)
> I: animated resource:
> I: Old composition: null
> I: compositionCancellable success
> //correct animation showed
> I: Updated preview: ResModel(animated=false)
> I: static resource:
> //correct static image showed
> I: Updated preview: ResModel(animated=true)
> //Same object of animated ResModel as no. 1
> I: animated resource:
> //UNSET - is it normal for cached animation?
> I: Old composition: LottieComposition:
> I: 	UNSET
> I: 		Parents: UNSET->UNSET->UNSET	
> I: 	UNSET
> I: 		Parents: UNSET->UNSET	
> I: 	UNSET
> I: 		Parents: UNSET->UNSET	
> I: 		Shapes:
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@24f3fe5, com.airbnb.lottie.model.animatable.AnimatableTransform@1542aba]}
> I: 			ShapeGroup{name='null' Shapes: [ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@bb70d6b, com.airbnb.lottie.model.animatable.AnimatableTransform@ec980c8]}, ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, ShapeFill{color=, fillEnabled=false}, com.airbnb.lottie.model.animatable.AnimatableTransform@3b8f561]}, ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, ShapeFill{color=, fillEnabled=false}, com.airbnb.lottie.model.animatable.AnimatableTransform@a8a3886]}, com.airbnb.lottie.model.animatable.AnimatableTransform@7b71547]}
> I: 	UNSET
> I: 		Parents: UNSET->UNSET->UNSET	
> I: 		Shapes:
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, ShapeFill{color=, fillEnabled=false}, com.airbnb.lottie.model.animatable.AnimatableTransform@d59e174]}
> I: 	UNSET
> I: 		Parents: UNSET->UNSET->UNSET	
> I: 		Shapes:
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, ShapeFill{color=, fillEnabled=false}, com.airbnb.lottie.model.animatable.AnimatableTransform@5ae869d]}
> I: 	UNSET
> I: 		Parents: UNSET->UNSET->UNSET	
> I: 		Shapes:
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@2c15712, ShapeFill{color=, fillEnabled=false}, com.airbnb.lottie.model.animatable.AnimatableTransform@ec5bee3]}
> I: 	UNSET
> I: 		Parents: UNSET->UNSET->UNSET->UNSET	
> I: 		Shapes:
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@eda0e0, com.airbnb.lottie.model.animatable.AnimatableTransform@971ef99]}
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@5d9d25e, com.airbnb.lottie.model.animatable.AnimatableTransform@e8b663f]}
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, ShapeFill{color=, fillEnabled=false}, com.airbnb.lottie.model.animatable.AnimatableTransform@e3beb0c]}
> I: 	UNSET
> I: 		Parents: UNSET->UNSET->UNSET	
> I: 		Shapes:
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, ShapeFill{color=, fillEnabled=false}, com.airbnb.lottie.model.animatable.AnimatableTransform@868ec55]}
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@b6cb66a, com.airbnb.lottie.model.animatable.AnimatableTransform@cda275b]}
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@c42abf8, com.airbnb.lottie.model.animatable.AnimatableTransform@298f8d1]}
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@997cf36, com.airbnb.lottie.model.animatable.AnimatableTransform@89de37]}
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@1f28fa4, ShapeFill{color=, fillEnabled=false}, com.airbnb.lottie.model.animatable.AnimatableTransform@8e3510d]}
> I: 	UNSET
> I: 		Parents: UNSET->UNSET->UNSET	
> I: 		Shapes:
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@889a8c2, ShapeFill{color=, fillEnabled=false}, com.airbnb.lottie.model.animatable.AnimatableTransform@c1426d3]}
> I: 	UNSET
> I: 		Parents: UNSET->UNSET->UNSET->UNSET	
> I: 		Shapes:
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@29b0210, com.airbnb.lottie.model.animatable.AnimatableTransform@f00f109]}
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@2cd8f0e, com.airbnb.lottie.model.animatable.AnimatableTransform@5f05d2f]}
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, ShapeFill{color=, fillEnabled=false}, com.airbnb.lottie.model.animatable.AnimatableTransform@5162f3c]}
> I: 	UNSET
> I: 		Parents: UNSET->UNSET->UNSET	
> I: 		Shapes:
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, ShapeFill{color=, fillEnabled=false}, com.airbnb.lottie.model.animatable.AnimatableTransform@13e94c5]}
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@e578e1a, com.airbnb.lottie.model.animatable.AnimatableTransform@aaf9d4b]}
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@1b50328, com.airbnb.lottie.model.animatable.AnimatableTransform@9f8b841]}
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@a5071e6, ShapeFill{color=, fillEnabled=false}, com.airbnb.lottie.model.animatable.AnimatableTransform@4d8c327]}
> I: 	UNSET
> I: 		Parents: UNSET->UNSET->UNSET	
> I: 		Shapes:
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@2eb29d4, ShapeFill{color=, fillEnabled=false}, com.airbnb.lottie.model.animatable.AnimatableTransform@2d7977d]}
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@da1c672, ShapeFill{color=, fillEnabled=false}, com.airbnb.lottie.model.animatable.AnimatableTransform@6846ac3]}
> I: 	UNSET
> I: 		Parents: UNSET->UNSET->UNSET	
> I: 		Shapes:
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, ShapeFill{color=, fillEnabled=false}, com.airbnb.lottie.model.animatable.AnimatableTransform@4bb0f40]}
> I: 	UNSET
> I: 		Parents: UNSET->UNSET->UNSET	
> I: 		Shapes:
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@dcb2e79, ShapeFill{color=, fillEnabled=false}, com.airbnb.lottie.model.animatable.AnimatableTransform@241d7be]}
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@b8f01f, com.airbnb.lottie.model.animatable.AnimatableTransform@ee1df6c]}
> I: 	UNSET
> I: 		Parents: UNSET	
> I: 		Shapes:
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@1c73935, ShapeFill{color=, fillEnabled=false}, com.airbnb.lottie.model.animatable.AnimatableTransform@93fb1ca]}
> I: 	UNSET
> I: 		Parents: UNSET	
> I: 		Shapes:
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@4866f3b, ShapeFill{color=, fillEnabled=false}, com.airbnb.lottie.model.animatable.AnimatableTransform@5c38658]}
> I: 	UNSET
> I: 	UNSET
> I: 		Parents: UNSET	
> I: 		Shapes:
> I: 			ShapeGroup{name='null' Shapes: [ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@73f33b1, com.airbnb.lottie.model.animatable.AnimatableTransform@38f2096]}, ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@9e2c417, com.airbnb.lottie.model.animatable.AnimatableTransform@e16b004]}, com.airbnb.lottie.model.animatable.AnimatableTransform@6259ed]}
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, com.airbnb.lottie.model.content.ShapeStroke@b94b022, com.airbnb.lottie.model.animatable.AnimatableTransform@8458ab3]}
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, ShapeFill{color=, fillEnabled=false}, com.airbnb.lottie.model.animatable.AnimatableTransform@f50c870]}
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, ShapeFill{color=, fillEnabled=false}, com.airbnb.lottie.model.animatable.AnimatableTransform@917a7e9]}
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, ShapeFill{color=, fillEnabled=false}, com.airbnb.lottie.model.animatable.AnimatableTransform@b71ac6e]}
> I: 			ShapeGroup{name='null' Shapes: [ShapePath{name=null, index=0}, ShapeFill{color=, fillEnabled=false}, com.airbnb.lottie.model.animatable.AnimatableTransform@d041f0f]}
> I: compositionCancellable success
> I: compositionCancellable success
> //no animation, previous static image stay in LAV. Listener called twice sometimes, sometimes one.
> W: A resource failed to call end. 
> W: A resource failed to call close. 
> //Is it from lottie?
>

**Comment by gpeal** [comment]
@vellrya Can you create a repro in the issue-repro module per the issue template please?

**Comment by vellrya** [comment]
Unfortuanetely, fork of repository required Studio 4.2 to open, but I perefer not to use Beta version of IDE. There is no stable 4.2 release right now.
> This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.2 or newer.

**Comment by gpeal** [comment]
@vellrya You can download and run it side by side without affecting your current installation.

**Comment by vellrya** [comment]
Reproduced: https://github.com/vellrya/lottie-android

**Comment by vellrya** [comment]
I made this steps:
1. Remove this if statement:
https://github.com/airbnb/lottie-android/blob/2cf9b8501c0ae3b1875577e002ce758875c1f04e/lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java#L211-L213

2. There is check for drawable equality in LottieAnimationView.setComposition:
https://github.com/airbnb/lottie-android/blob/2cf9b8501c0ae3b1875577e002ce758875c1f04e/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L550-L556

I rewrite this as follow:

```
if (getDrawable() == lottieDrawable) return;
boolean isNewComposition = lottieDrawable.setComposition(composition);
enableOrDisableHardwareLayer();
```
Now it works.

Likely, this solution has side effect on performance, but if drawable was changed, we need to reset composition anyway, am I right?
