### ISSUE TITLE
Fetch current Lottie layer color programmatically

### ISSUE THREAD

**Issue by chrislworkaccount** [airbnb/lottie-android#1697]
I am working on a project for iOS, Android and RN. I am using the KeyPath object to update colors for a keypath. That piece works fine. I can't seem to find a way to fetch the current color of a layer by Keypath. I need the current colors to create color profiles so I can create different themed versions for the same Lottie animation.

To fetch the color I am hoping to find something as simple as KeyPath("my key path").getCurrentColor()? Anyway to accomplish that is much appreciated

Below is what I am doing to set the color on Android, and this works fine.

    fun applyColorForTag(colorMap: Map<String, String>?) {
        mIllustrationView.addValueCallback(
            KeyPath(colorMap?.get("tag"), "**"),
            LottieProperty.COLOR_FILTER,
            object : SimpleLottieValueCallback<ColorFilter?> {
                override fun getValue(frameInfo: LottieFrameInfo<ColorFilter?>?): ColorFilter? {
                    return PorterDuffColorFilter(
                        Color.parseColor(colorMap?.get("color")),
                        PorterDuff.Mode.SRC_ATOP
                    )
                }
            }
        )
    }

**Comment by gpeal** [comment]
@chrislworkaccount if you call `invalidate` on the drawable, it'll re-render and then call your callback. Would that work?

**Comment by chrislworkaccount** [comment]
Which drawable? the "mIllustrationView" is a LottieAnimationView. If I call invalidate on it I can detect the current color for a layer?

**Comment by gpeal** [comment]
@chrislworkaccount Yes, try adding the value callback you have then calling invalidate on the view. That will cause it to redraw and call you callback. Note that it won't happen synchronously though.

**Comment by chrislworkaccount** [comment]
I am still not seeing how it will return the current color not the one I am setting it to? Apologize and I am learning how to use these methods. this is returning the color I am setting it to, not the current color. what would go in the getValue method to return current? if you have a code example it would be great.

    fun applyColorForTag2(colorMap: Map<String, String>?) {
        mIllustrationView.addValueCallback(
            KeyPath(colorMap?.get("tag"), "**"),
            LottieProperty.COLOR_FILTER,
            object : SimpleLottieValueCallback<ColorFilter?> {
                override fun getValue(frameInfo: LottieFrameInfo<ColorFilter?>?): ColorFilter? {
                    return PorterDuffColorFilter(
//                        Color.parseColor(colorMap?.get("color")),
                        IllustrationUtils().randomRGBColor(), //for demo only
                        PorterDuff.Mode.SRC_ATOP
                    )
                }
            }
        )

**Comment by chrislworkaccount** [comment]
thanks for the pointers but I could not find a way to get it working through the lottie apis so i needed to traverse the json to track it down. now i can convert the RGBA color to hex for the shape layers to use in my theming

prints -> colorinfo: [0.294000004787,0.298000021542,0.458999992819,1]
              val colormaps: JSONArray =
                JsonPath.read(
                    json, "$.layers[2].shapes[1].it[1].c.k"
                )
            Log.i("colorinfo", colormaps.toString())
        }`

**Comment by gpeal** [comment]
Looks like you got this working your own way but you in your `getValue()` you would use `frameInfo.startValue` + `frameInfo.endValue` + `frameInfo.getInterpolatedKeyframeProgress()` to figure out what the current value is and then return null if you want it to use the default value.
