### ISSUE TITLE
Make LottieDrawable stateful

### ISSUE THREAD

**Issue by razer89** [airbnb/lottie-android#170]
Is it possible that in future LottieDrawable will be stateful? It will be great for using with CompoundButtons. Thanks for awesome library!

**Comment by gpeal** [comment]
@razer89 Could you make your own StateListDrawable and just add child LottieDrawables for each desired state?

**Comment by razer89** [comment]
@gpeal yes, I can. But I'm talking about parsing drawables from JSON for desired states. I gues, it is not very clean to create drawables for every button in my app. I understand - Adobe After Effects can't describe every state, but probably you have any ideas?

**Comment by razer89** [comment]
Another problem - com.airbnb.lottie.LottieDrawable#setComposition has a package access. I can't creat LottieDrawables directly, reflection only (or inherit my own with "com.airbnb.lottie" package name)

**Comment by gpeal** [comment]
@razer89 I'll make it public in 1.5.3 which I'm going to release today

**Comment by razer89** [comment]
@gpeal thank you!

**Comment by gpeal** [comment]
@razer89 1.5.2 with setComposition public is not available. 
I'll think about an API that might work here but for now, you may be best off creating your own StateListDrawable.

**Comment by gpeal** [comment]
@razer89 

#180 tracked making the methods public.

I think you should compose LottieDrawables in a StateListDrawable rather than it bundling the functionality itself.
