### ISSUE TITLE
Spin

### ISSUE THREAD

**Issue by medsauce** [airbnb/lottie-android#1700]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I think a functional rotating lottie would be a nice touch. Maybe with a hover like the old windows logo

**Comment by gpeal** [comment]
@medsauce I'm sorry, I don't understand what you are asking for.

**Comment by medsauce** [comment]
I am new git member. My request was supposed to be a suggestion for the logo. My thought was to bring back the rotation on logo like an old pin wheel sign. Or a barbers spinning pole. On your site. I will of course learn myself eventually. Though of course my suggestion and your knowledge would allow me to learn more effectively and in efficiently on how this would be done.

**Comment by gpeal** [comment]
@medsauce you may be posting this in the wrong place. This repo is for reporting issues with the Lottie Android library. Did you intend to send this to Lottiefiles or somewhere else?

**Comment by gpeal** [comment]
I'm going to close this for now unless there is a specific request for Lottie Android.
