### ISSUE TITLE
Emojis in text delegates disappear on Android 8.1 and below

### ISSUE THREAD

**Issue by JoachimNoergaard** [airbnb/lottie-android#1701]
**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.
[gift_cinema_animation_3.json.zip](https://github.com/airbnb/lottie-android/files/5728814/gift_cinema_animation_3.json.zip)

**Describe the bug**
When sending strings containing emojis via the text delegate on Android version 8.1. and below the emoji is replaced with a blank. The emoji is present all the way until drawText is called on the canvas.

**What version of Lottie did you test this on?**
3.4.4

**What version of Android did you test this on?**
Android 8.1. API level 27

**Steps To Reproduce**

1. Assign a text with emojis (e.g. popcorn) to the text delegate in the animations file
4. At the end of the animation it appears visually aligned to the left, because the emoji is replaced with a blank

**Screenshots**
Expected
<img width="161" alt="good" src="https://user-images.githubusercontent.com/15686040/102871001-21c2ae80-443e-11eb-8c2a-2c24961115a3.png">
Actual 
<img width="161" alt="bad copy" src="https://user-images.githubusercontent.com/15686040/102871245-7b2add80-443e-11eb-8dca-480dc63ae0b4.png">

**Comment by gpeal** [comment]
@JoachimNoergaard Your font may not support that emoji on Android 8. I just did a quick test where I tried to use the `Typeface.DEFAULT` to render 🍿 in a TextView and it wasn't able to render it either.
```
text_view.text = String(Character.toChars(0x1F37F))
```

If that fails, Lottie won't be able to render it either.

**Comment by gpeal** [comment]
@JoachimNoergaard I'm going to close this for now because I don't think it is an issue with Lottie's rendering per my message above. If you think there is something wrong with Lottie's rendering, feel free to reopen this with more specific information.

**Comment by JoachimNoergaard** [comment]
From what I know, Android canvas drawText has an issue with emojis on api 27 and previous versions. The closest I have been to finding a solution is this https://stackoverflow.com/questions/41212092/drawing-emojis-on-android-canvas-using-unicode-values/41225433#41225433

**Comment by gpeal** [comment]
@JoachimNoergaard If you are able to take a look and put up a PR, I would be open to that but otherwise, it's unlikely that I'll have a chance to take this one on myself.

**Comment by JoachimNoergaard** [comment]
Honestly, I think the best solution is to state in the documentation that emojis are only supported from API 28 and up. The solution alternatives with compatible text views seem undesirable and at the same time the number of devices with older Android versions decline.
