### ISSUE TITLE
Animated Typography - bug

### ISSUE THREAD

**Issue by bexsadirov** [airbnb/lottie-android#171]
On my android device the typography animations behave very strange (letters "L" and "F"). You can see it on the attached screenshot. My device is Samsung S5 mini, that have Android 6.0.1
![lottie_bug](https://cloud.githubusercontent.com/assets/16705217/23472470/1fe50f46-fed7-11e6-85d3-8d9e911101c1.png)

**Comment by gpeal** [comment]
@bexsadirov Strange... They look fine for me. Which version of the app is this in? And you don't have force gpu rendering on in developer settings do you?

**Comment by gpeal** [comment]
Actually my Galaxy S7 seems to be doing that too. I'll take a look. Thanks.

**Comment by bexsadirov** [comment]
@gpeal It is the last version. And on google play you can also see the last comment of "Евгений Тимофеев" writing about this bug too.
