### ISSUE TITLE
ImageLayer draw bitmap  with size from LottieImageAsset.width  LottieImageAsset.height

### ISSUE THREAD

**Issue by soongao** [airbnb/lottie-android#1716]
ImageLayer: draw bitmap  with size from LottieImageAsset.width  LottieImageAsset.height

I expect

**draw bitmap with the specified size instead of the original size**

  @Override public void drawLayer(@NonNull Canvas canvas, Matrix parentMatrix, int parentAlpha) {
*****
    src.set(0, 0, bitmap.getWidth(), bitmap.getHeight());
    dst.set(0, 0, (int) ([**current LottieImageAsset.width**] * density), (int) ([**current LottieImageAsset.height**]  * density));
****
  }

Why not do this

**Comment by gpeal** [comment]
Duplicate of #1705
