### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by skovacevic96** [airbnb/lottie-android#1717]
Hello, this actually is not a bug but a performance issue. I am making an app that is using Android Advanced Navigation Sample https://github.com/android/architecture-components-samples/tree/master/NavigationAdvancedSample. It basically means that I am having 3 bottom tabs with 3 different graphs, each of them have starting destinations that are really UI expensive. I have 3 animations that serve as menu icons so when the user click on them animation starts and in that moment bottom navigation changes graph. Well, here is the issue. Animations start lagging on every device because fragment calls onCreateView() and CPU usage drastically increases. If I turn connection to the internet off, there is no data and thus these 3 fragments are empty - animations are not laggy. In other parts of the app other animations work just fine and they are much more demanding. These same animations work perfectly fine on iOS. Is there a smart way to  avoid this? I went over all the issues and StackOverflow but could not find a solution to this, it's just that in general FPS drops down and it kills the animation. One tab has no RecyclerViews and navigating to it is not an issue but the other two are just a disaster. What I also found out is that after a while, when I go back and forth from one tab to another. performance improves slightly. The weirdest thing is that animation is not laggy in a way that it stutters, it looks like it increases speed or if it is skipping frames. Happy new year!

**Comment by gpeal** [comment]
@skovacevic96 Are you sure that the performance issues are related to Lottie? I would recommend:
1) Removing Lottie to see if there is a difference
2) Trying the animations in the Lottie sample app on the Play Store or from the repo. You can drag the animation on top of the Lottiefiles website then scan the qr code with the app and it'll start playing in the app. Once it's playing you can tap render graph at the bottom to see how long each frame takes to render and then tap "view render times per layer" to see if any particular layers are causing a performance issue.
3) Check out any of the performance info from [the docs](http://airbnb.io/lottie/#/android?id=performance)

Beyond that, without a specific performance issue that has a solution, I'll have to close this.

**Comment by gpeal** [comment]
I'm going to close this since it isn't directly actionable.
