### ISSUE TITLE
ImageAssetManager will casue crash when decode asset throw IOException

### ISSUE THREAD

**Issue by 1wayticket** [airbnb/lottie-android#1718]
Littie v3.1.0
 I have met some crash logs about Lottie recently.  When I read the source code ,I find there maybe a bug.
Class:com.airbnb.lottie.manager.ImageAssetManager
```
 InputStream is;
    try {
      if (TextUtils.isEmpty(imagesFolder)) {
        throw new IllegalStateException("You must set an images folder before loading an image." +
            " Set it with LottieComposition#setImagesFolder or LottieDrawable#setImagesFolder");
      }
      is = context.getAssets().open(imagesFolder + filename);
    } catch (IOException e) {
      Logger.warning("Unable to open asset.", e);
      return null;
    }
    bitmap = BitmapFactory.decodeStream(is, null, opts);
    bitmap = Utils.resizeBitmapIfNeeded(bitmap, asset.getWidth(), asset.getHeight());
```
When AssetManager open file throw IOException,this **is** is null,and this **bitmap** will be null.and **Utils.resizeBitmapIfNeeded** will throw NPE.
I find the newest version alse has the problem, so please recheck these code,thanks!

**Comment by gpeal** [comment]
@1wayticket But the function returns null inside the catch block so it won't continue to the resize line.

**Comment by 1wayticket** [comment]
> @1wayticket But the function returns null inside the catch block so it won't continue to the resize line.

Sorry for my mistake. But we do collect NEP as below 
```

1 com.airbnb.lottie.utils.Utils.android.graphics.Bitmap resizeBitmapIfNeeded(android.graphics.Bitmap,int,int)(Utils.java:248)
--
2 com.airbnb.lottie.manager.ImageAssetManager.android.graphics.Bitmap bitmapForId(java.lang.String)(ImageAssetManager.java:117)
3 com.airbnb.lottie.LottieDrawable.android.graphics.Bitmap getImageAsset(java.lang.String)(LottieDrawable.java:974)
4 com.airbnb.lottie.model.layer.ImageLayer.android.graphics.Bitmap getBitmap()(ImageLayer.java:63)
5 com.airbnb.lottie.model.layer.ImageLayer.void drawLayer(android.graphics.Canvas,android.graphics.Matrix,int)(ImageLayer.java:33)
6 com.airbnb.lottie.model.layer.BaseLayer.void draw(android.graphics.Canvas,android.graphics.Matrix,int)(BaseLayer.java:221)
7 com.airbnb.lottie.model.layer.CompositionLayer.void drawLayer(android.graphics.Canvas,android.graphics.Matrix,int)(CompositionLayer.java:113)
8 com.airbnb.lottie.model.layer.BaseLayer.void draw(android.graphics.Canvas,android.graphics.Matrix,int)(BaseLayer.java:221)
9 com.airbnb.lottie.LottieDrawable.void draw(android.graphics.Canvas)(LottieDrawable.java:357)
10 android.widget.ImageView.onDraw(ImageView.java:1478)

```
It happend occasionly about 4/10000 among various devices, we can't reproduce it.
So can you give me some help?

**Comment by gpeal** [comment]
It looks like [BitmapFactory.decodeStream can return null](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/manager/ImageAssetManager.java). I can add a null check for that case.

**Comment by 1wayticket** [comment]
> It looks like [BitmapFactory.decodeStream can return null](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/manager/ImageAssetManager.java). I can add a null check for that case.

Thanks a lot!

**Comment by gpeal** [comment]
@1wayticket reopening to track this.

**Comment by 1wayticket** [comment]
@gpeal[ The commit](https://github.com/airbnb/lottie-android/pull/1729/commits/1c8f3012b4c6fc012fe16cd063cb09be8551d8e8) seemed useless becasue the the param bitmap is null sometimes.
```
1 com.airbnb.lottie.utils.Utils.android.graphics.Bitmap resizeBitmapIfNeeded(android.graphics.Bitmap,int,int)(Utils.java:248)
--
2 com.airbnb.lottie.manager.ImageAssetManager.android.graphics.Bitmap bitmapForId(java.lang.String)(ImageAssetManager.java:117)
3 com.airbnb.lottie.LottieDrawable.android.graphics.Bitmap getImageAsset(java.lang.String)(LottieDrawable.java:974)
4 com.airbnb.lottie.model.layer.ImageLayer.android.graphics.Bitmap getBitmap()(ImageLayer.java:63)
5 com.airbnb.lottie.model.layer.ImageLayer.void drawLayer(android.graphics.Canvas,android.graphics.Matrix,int)(ImageLayer.java:33)
6 com.airbnb.lottie.model.layer.BaseLayer.void draw(android.graphics.Canvas,android.graphics.Matrix,int)(BaseLayer.java:221)
7 com.airbnb.lottie.model.layer.CompositionLayer.void drawLayer(android.graphics.Canvas,android.graphics.Matrix,int)(CompositionLayer.java:113)
8 com.airbnb.lottie.model.layer.BaseLayer.void draw(android.graphics.Canvas,android.graphics.Matrix,int)(BaseLayer.java:221)
9 com.airbnb.lottie.LottieDrawable.void draw(android.graphics.Canvas)(LottieDrawable.java:357)
10 android.widget.ImageView.onDraw(ImageView.java:1478)
```
Can you add a null check before the method as below 
```
        bitmap = BitmapFactory.decodeStream(is, null, opts);
        if (bitmap == null) {
            return null;
        }
        bitmap = Utils.resizeBitmapIfNeeded(bitmap, asset.getWidth(), asset.getHeight());
```
Maybe our lottie file has problem or their's a bug about decode bitmap?

**Comment by gpeal** [comment]
@1wayticket The commit prevents Lottie from [potentially crashing](https://developer.android.com/reference/kotlin/android/graphics/BitmapFactory#decodestream). If it decodes successfully but returns null then it's actually null. If you think there is another issue, feel free to open another issue if you have a repro.

**Comment by 1wayticket** [comment]
@gpeal Allright~
