### ISSUE TITLE
LottieDrawable doesn't play animation when used as DynamicDrawableSpan inside SpannableString

### ISSUE THREAD

**Issue by Jimmy-JC** [airbnb/lottie-android#1719]
I'm facing an issue regarding animation not played, I've implemented a LottieDrawableSpan as wrote in android docs for using [DynamicDrawableSpan](https://developer.android.com/reference/kotlin/android/text/style/DynamicDrawableSpan) as seen here

```kotlin
class LottieDrawableSpan(private val context: Context) : DynamicDrawableSpan() {
    
    override fun getDrawable(): Drawable {
        val lottieDrawable = LottieDrawable()
        lottieDrawable.composition = LottieCompositionFactory.fromRawResSync(context, R.raw.loader).value
        lottieDrawable.setBounds(0, 0, lottieDrawable.intrinsicWidth, lottieDrawable.intrinsicHeight)
        lottieDrawable.repeatCount = Int.MAX_VALUE
        lottieDrawable.playAnimation()
        return lottieDrawable
    }
    
}
```
It's working fine when it's come to use this drawable inside ImageView, but the animation isn't played inside SpannableString
Bellow is the method used to replace text with drawable one normal and another with Lottie 
```kotlin
    private fun addSpanImage(textView: TextView, drawableSpan: DynamicDrawableSpan) {
        val string = SpannableString("Text with a drawable span")
        string.setSpan(drawableSpan, 12, 20, Spanned.SPAN_EXCLUSIVE_EXCLUSIVE)
        textView.text = string
    }
```
A video for how it looks like using the drawable inside image view and textview can be found here 

https://user-images.githubusercontent.com/69200029/104131297-91192780-5386-11eb-8ef2-ec6810283e15.mp4

**Comment by gpeal** [comment]
@Jimmy-JC I've never tried to do this but almost certainly, the problem is that nothing is registering as the Drawable's callback via [setCallback](https://developer.android.com/reference/kotlin/android/graphics/drawable/Drawable#setcallback). Drawable use the callback to notify their parent that they need to be redrawn.

**Comment by Jimmy-JC** [comment]
Thanks @gpeal fixed and working fine

**Comment by Hommilist** [comment]
@Jimmy-JC can you show me your code,how to fix it. I try set callback(Textview),but it didn't work. that Textview contains spannablestring.thanks

**Comment by Jimmy-JC** [comment]
@Hommilist 
```kotlin

    private fun getSpannableString(): SpannableString {
        val lottieDrawable = getLottieDrawable()
        val spannableString = TODO("Init your spannableString using lottieDrawable")
        lottieDrawable.callback = callback
        lottieDrawable.playAnimation()
        return spannableString
    }

    private val callback = object : Drawable.Callback {
        override fun scheduleDrawable(who: Drawable, what: Runnable, `when`: Long) {}
        override fun unscheduleDrawable(who: Drawable, what: Runnable) {}
        override fun invalidateDrawable(who: Drawable) {
            yourView.invalidate()
        }
    }
```

**Comment by Hommilist** [comment]
@Jimmy-JC it works，thank you.

**Comment by FYSong** [comment]
> @Hommilist
> 
> ```kotlin
>     private fun getSpannableString(): SpannableString {
>         val lottieDrawable = getLottieDrawable()
>         val spannableString = TODO("Init your spannableString using lottieDrawable")
>         lottieDrawable.callback = callback
>         lottieDrawable.playAnimation()
>         return spannableString
>     }
> 
>     private val callback = object : Drawable.Callback {
>         override fun scheduleDrawable(who: Drawable, what: Runnable, `when`: Long) {}
>         override fun unscheduleDrawable(who: Drawable, what: Runnable) {}
>         override fun invalidateDrawable(who: Drawable) {
>             yourView.invalidate()
>         }
>     }
> ```

it doesn't work on my scene. would you pls do favor help me point out the problem? here's my code
`getLottieDrawable{
        val sp = SpannableString("hello world")
        sp.setSpan(LottieDrawableSpan(it), 0,3,Spanned.SPAN_EXCLUSIVE_EXCLUSIVE)
        tvLottie.text = sp
        it.callback = callback
        it.playAnimation()
  }

private fun getLottieDrawable(callback: ((LottieDrawable) -> Unit)){
        val lottieDrawable: LottieDrawable = LottieDrawable()
        lottieDrawable.repeatCount = -1
        lottieDrawable.setImagesAssetsFolder(assetFolder2)
        LottieCompositionFactory.fromAsset(this, assetJson2, null).addListener {
            lottieDrawable.composition = it
            lottieDrawable.setBounds(0, 0, lottieDrawable.intrinsicWidth, lottieDrawable.intrinsicHeight)
            lottieDrawable.repeatCount = Int.MAX_VALUE
            callback.invoke(lottieDrawable)
        }
   }
  
  private val callback = object : Drawable.Callback {
        override fun scheduleDrawable(who: Drawable, what: Runnable, `when`: Long) {}
        override fun unscheduleDrawable(who: Drawable, what: Runnable) {}
        override fun invalidateDrawable(who: Drawable) {
            tvLottie.invalidate()
        }
    }

`

**Comment by FYSong** [comment]
> > @Hommilist
> > ```kotlin
> >     private fun getSpannableString(): SpannableString {
> >         val lottieDrawable = getLottieDrawable()
> >         val spannableString = TODO("Init your spannableString using lottieDrawable")
> >         lottieDrawable.callback = callback
> >         lottieDrawable.playAnimation()
> >         return spannableString
> >     }
> > 
> >     private val callback = object : Drawable.Callback {
> >         override fun scheduleDrawable(who: Drawable, what: Runnable, `when`: Long) {}
> >         override fun unscheduleDrawable(who: Drawable, what: Runnable) {}
> >         override fun invalidateDrawable(who: Drawable) {
> >             yourView.invalidate()
> >         }
> >     }
> > ```
> 
> it doesn't work on my scene. would you pls do a favor to help me point out the problem? here's my code @gpeal @Hommilist @Jimmy-JC
> 
> ```
> getLottieDrawable{
>         val sp = SpannableString("hello world")
>         sp.setSpan(LottieDrawableSpan(it), 0,3,Spanned.SPAN_EXCLUSIVE_EXCLUSIVE)
>         tvLottie.text = sp
>         it.callback = callback
>         it.playAnimation()
> }
> 
> private fun getLottieDrawable(callback: ((LottieDrawable) -> Unit)){
>         val lottieDrawable: LottieDrawable = LottieDrawable()
>         lottieDrawable.repeatCount = -1
>         lottieDrawable.setImagesAssetsFolder(assetFolder2)
>         LottieCompositionFactory.fromAsset(this, assetJson2, null).addListener {
>             lottieDrawable.composition = it
>             lottieDrawable.setBounds(0, 0, lottieDrawable.intrinsicWidth, lottieDrawable.intrinsicHeight)
>             lottieDrawable.repeatCount = Int.MAX_VALUE
>             callback.invoke(lottieDrawable)
>         }
>    }
>   
> private val callback = object : Drawable.Callback {
>         override fun scheduleDrawable(who: Drawable, what: Runnable, `when`: Long) {}
>         override fun unscheduleDrawable(who: Drawable, what: Runnable) {}
>         override fun invalidateDrawable(who: Drawable) {
>             tvLottie.invalidate()
>         }
>  }
> 
> class LottieDrawableSpan(private val lottieDrawable:Drawable) : DynamicDrawableSpan() {
>     override fun getDrawable(): Drawable {
>         return  lottieDrawable
>     }
> }
> ```

I found out the source code in ImageAssetManager  just limit independent LottieDrawable read image
```
    if (!(callback instanceof View)) {
      Logger.warning("LottieDrawable must be inside of a view for images to work.");
      this.imageAssets = new HashMap<>();
      context = null;
      return;
    }
```
that confuse me, what ' s the purpose?
