### ISSUE TITLE
Issue on S6 Can't play

### ISSUE THREAD

**Issue by zhuangzhitu** [airbnb/lottie-android#1720]
Galaxy S6 edge Android 7.0
Issue：
Version: 3.5.0
I'm using this phone, and I'm running in the sample project, and I'm sure I can't play animation,
But why can I play with version 2.7.0?

**Comment by zhuangzhitu** [comment]
[IMG_1510.MP4.zip](https://github.com/airbnb/lottie-android/files/5795538/IMG_1510.MP4.zip)

**Comment by gpeal** [comment]
@zhuangzhitu Do you have any of the system animation scales set to 0 in developer options?

**Comment by zhuangzhitu** [comment]
> @zhuangzhitu Do you have any of the system animation scales set to 0 in developer options?

Really, why will the new version not play by default? For example, 2.7.0 plays fine

**Comment by zhuangzhitu** [comment]
> @zhuangzhitu Do you have any of the system animation scales set to 0 in developer options?

Indeed, I have turned off the animation scaling of one image. Why is that? 2.7.0 is good again?

**Comment by gpeal** [comment]
It changed in [3.0.1](https://github.com/airbnb/lottie-android/blob/master/CHANGELOG.md#bugs-fixed-14)

**Comment by zhuangzhitu** [comment]
> It changed in [3.0.1](https://github.com/airbnb/lottie-android/blob/master/CHANGELOG.md#bugs-fixed-14). Lottie should respect the animation scale set by the OS.

ok
