### ISSUE TITLE
Error on display the animation

### ISSUE THREAD

**Issue by mateusfsilva** [airbnb/lottie-android#1722]
The animation is not showing the spin effect.

Lottie for Android 3.4.0
Android 11 (RQ1A.201205.003)

Open this file on Lottie
https://drive.google.com/file/d/1cVpwuU14P1xuddupK1AvbluXYJ2SplR9/view?usp=sharing

Animation on the LottieFiles:
![animation_500_kjokrclb](https://user-images.githubusercontent.com/3394090/104199180-e0eb0380-5405-11eb-9d60-a9cf7964376d.gif)

Animation on the Lottie for Android:
https://user-images.githubusercontent.com/3394090/104199285-0546e000-5406-11eb-9d94-aba02f06eed3.mp4

**Comment by gpeal** [comment]
Lottie doesn't support 3D or Cinema 4D effects.
You can check what it supported [here](http://airbnb.io/lottie/#/supported-features)
