### ISSUE TITLE
equals??

### ISSUE THREAD

**Issue by qw903157902** [airbnb/lottie-android#1723]
https://github.com/airbnb/lottie-android/blob/1d3fca2fbb1aee5c3ad2926a21d55b59bb032549/lottie/src/main/java/com/airbnb/lottie/LottieResult.java#L47

line#L47     return getException().toString().equals(that.getException().toString());  ??????????

**Comment by gpeal** [comment]
@qw903157902 Would you like to propose an alternative? Since these exceptions come from internally in the Lottie library, the message and stack traces should be comparable.

**Comment by gpeal** [comment]
I'm going to close this due to the lack of a clear request or proposal. You may reopen this if you can clarify what you are asking for.
