### ISSUE TITLE
imageAssetsFolder is null

### ISSUE THREAD

**Issue by YasserYan** [airbnb/lottie-android#1724]
```
// LottieAnimationView
@Override protected void onRestoreInstanceState(Parcelable state) {
    ...
    lottieDrawable.setImagesAssetsFolder(ss.imageAssetsFolder);

  }
```

Should we check whether ss.imageAssetsFolder is null? When I set imageAssetsFolder in onCreateView and If there is a saveState and imageAssetsFolder is null, then restore the state, imageAssetsFolder turn into null, and crash

eg
```
override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        ...

       if (isShow){
            lottieAnimationView.imageAssetsFolder = "image/"
        } else {
            lottieAnimationView.isVisible = false
        }

    }
```

**Comment by gpeal** [comment]
@YasserYan You can just set `app:lottie_imageAssetsFolder="image"` in your layout file and that's it :)

**Comment by YasserYan** [comment]
Can you write it in your [document](http://airbnb.io/lottie/#/)? This document recommends to use setImagesAssetsFolder

**Comment by gpeal** [comment]
Done http://airbnb.io/lottie/#/android?id=images
