### ISSUE TITLE
@qw903157902 Would you like to propose an alternative? Since these exceptions come from internally in the Lottie library, the message and stack traces should be comparable.

### ISSUE THREAD

**Issue by 877898444** [airbnb/lottie-android#1726]
@qw903157902 Would you like to propose an alternative? Since these exceptions come from internally in the Lottie library, the message and stack traces should be comparable.

_Originally posted by @gpeal in https://github.com/airbnb/lottie-android/issues/1723#issuecomment-759586537_

He means that "that" is missing

**Comment by gpeal** [comment]
@877898444 I don't follow. Please respond to that issue rather than creating a new one.

**Comment by qw903157902** [comment]
Compare yourself to yourself
Does that make sense

**Comment by qw903157902** [comment]
@gpeal

**Comment by gpeal** [comment]
@qw903157902 I'm still not following
