### ISSUE TITLE
Reusing LottieAnimationView with different animations cause problems

### ISSUE THREAD

**Issue by victor5171** [airbnb/lottie-android#1727]
**Describe the bug**
I have a case on my project where I reuse a LottieAnimationView, switching the animation using setAnimation(int rawRes).

On my first playAnimation it works normally, but when I try to switch to a different animation and then play it, the animator stays frozen on the last frame of the previously played animation.

The same problem happens if I try to play the same animation, only changing the min and max frames with setMinAndMaxFrame(final String startMarkerName, final String endMarkerName, final boolean playEndMarkerStartFrame)

**What version of Lottie did you test this on?**
Works on 3.5.0, broken on 3.6.0

**What version of Android did you test this on?**
Android 10

**Steps To Reproduce**

1. Use Lottie 3.6.0
2. Assign an animation
2. Play it
3. Wait for it to end
4. Assign a different animation or the same with different min and max frames
5. Play the animation on the same LottieAnimationView

**Comment by pedroromao-acceptto** [comment]
It's happening the same using 3.6.0. Just start using Lottie and it was strange that the same was not happening to anyone else. Apparently is a bug.

**Comment by romaopedro** [comment]
It's happening the same using 3.6.0. Just start using Lottie and it was strange that the same was not happening to anyone else. Apparently is a bug.

**Comment by kaeawc** [comment]
Seeing the same in Hinge - we have this exact case in our main screen animated loader. Has worked fine for 2 years until upgrading to 3.6.0.

**Comment by gpeal** [comment]
Thanks for the report. I'll look into this. I'll also accept a PR.

**Comment by natansalda** [comment]
Hello, I have the same issue in my app - works fine on 3.5 but broken on 3.6

**Comment by gpeal** [comment]
@natansalda Can you post a repro so I can take a look?

**Comment by Acedev003** [comment]
Hey, same issue here with me. At first I thought I had done something wrong, but now I realize that others have faced the same issue too. Calling different animations using the same lottieAnimationView leads to some calls being skipped entirely.

**Use case**

I'm using  lottieAnimationView as a button that requires the animation to played each time the user interacts with it. 

**Example Code**
```
LottieAnimationView animView = (LottieAnimationView) findViewById(R.id.lottieview);

 animView.setOnClickListener(new View.OnClickListener() {  
            @Override  
            public void onClick(View view)
           {  
               if(condition)
                       animView .setAnimation("lottie1.json");                  // lottie1 and lottie2 files in assets folder
               else
                       animView .setAnimation("lottie2.json");
                
               animView.playAnimation();

            }  
});  
```
**Issue**

 The first 2-3 button clicks _usually_ runs as expected with animView easily transitioning between lottie1 and lottie2 animation (looping=false) during a button press and then back to lottie1. However after that , even though the button click event occurs successfully, the lottieview fails to render and remains blank 😶😶. This occurs randomly, though I've noticed that it usually starts during the 5th or 6th transition.

**Lottie Build Version :** 3.6.0
**Android Version :** Android 10

**Comment by gpeal** [comment]
Lottie 3.6.1 has been released with a fix for this.

**Comment by bhumitbelani** [comment]
with 3.6.1 is still not working for me 
same issue

**Comment by benjaminVadon** [comment]
As a workaround, at least when using setMinAndMaxFrame, you can cancel animation before using it and restart playing after. It seems working for my app's users (I can't reproduce the bug on my own)

**Comment by EMVignesh96** [comment]
Facing the same issue, is the LottieAnimationView not reusable? Once an animation ends, no other animation can be rendered on it again.

**Comment by AndreyAsadchy** [comment]
Removing `app:lottie_autoPlay="true"` from XML and calling `playAnimation()` manually fixed it for me.
