### ISSUE TITLE
Add support for text

### ISSUE THREAD

**Issue by KucherenkoIhor** [airbnb/lottie-android#173]
Hello. Can Lottie display text?? 
[single_buton.txt](https://github.com/airbnb/lottie-android/files/813581/single_buton.txt)
I have button with text "LET'S DO  IT" and text doesn't display.

**Comment by 0legg** [comment]
Can be done the same way image assets works utilizing Calligraphy (or just loading plain typefaces from assets)

**Comment by tehfailsafe** [comment]
@0legg Can you elaborate? If I'm just using roboto, you're saying just drop the font file in the assets folder and use `lottieView.setImageAssetsFolder("assets");`?

**Comment by gpeal** [comment]
Text glyph rendering now works! I'll open specific issues for further text enhancements and reference this one.

**Comment by fentonbutcher** [comment]
Hi, I've tried exporting an animation via bodymovin that contains text and it still isn't displaying.  I've installed the release from a day ago. Any help would be appreciated

**Comment by gpeal** [comment]
@fentonbutcher upgrade bodymovin to 4.9.0. You can also check composition.getWarnings(). It'll give you some hints.

**Comment by fentonbutcher** [comment]
@gpeal where do I check the composition.getWarnings().?
Also, I have checked 'Gliphs  - checked converts fonts into shapes'. I still can't see any text. Have upgraded to the most recent 4.9.0 version

**Comment by gpeal** [comment]
@fentonbutcher Also make sure you have the latest Lottie (2.1.0)

**Comment by fentonbutcher** [comment]
We're using Lottie it for react native. Has that also been updated?

**Comment by gpeal** [comment]
@fentonbutcher not yet but try explicitly putting 2.1.0 in your gradle file to see if you can force it to use a newer version.

**Comment by fentonbutcher** [comment]
@gpeal is there a time frame for updating for react native?

**Comment by fentonbutcher** [comment]
@gpeal just thought i'd say... thanks for the help so far :)

**Comment by gpeal** [comment]
@fentonbutcher I pushed 1.2.0 for react native which supports text :)

**Comment by fentonbutcher** [comment]
@gpeal is it possible to use dynamic text with this now as well in the same way as:

https://codepen.io/airnan/pen/ZLVJmq?editors=0010

**Comment by gpeal** [comment]
@fentonbutcher Yes, use a text deleate

**Comment by fentonbutcher** [comment]
@gpeal do I need to install a new version of bodymovin for after effects to get this to work?

**Comment by fentonbutcher** [comment]
[text_test_v01.aep.zip](https://github.com/airbnb/lottie-android/files/1169627/text_test_v01.aep.zip)

**Comment by fentonbutcher** [comment]
@gpeal do you have an example after effects file that contains text that hasn't been outlined that I could use as a reference?

**Comment by fentonbutcher** [comment]
here's an example of what we see when pasting the .json into a codepen test

https://codepen.io/torrens/project/editor/DVvqmo/

**Comment by gpeal** [comment]
Yes, you need 4.9.0 or later. It works fine for me.

**Comment by gpeal** [comment]
@fentonbutcher ^

**Comment by fentonbutcher** [comment]
@gpeal sorry for all the questions - can you confirm that it works fine in react native for you (just realised that this thread is under lottie-android)

**Comment by gpeal** [comment]
@fentonbutcher Are you using lottie-react-native 1.2.0?

**Comment by fentonbutcher** [comment]
@gpeal One of our devs will be in contact on this thread to confirm details. The app we are building will need to function offline as well as online. Would this have an impact on the fonts rendering?

**Comment by torrens** [comment]
@gpeal  I'm using lottie-react-native v1.2.0 in an Expo application.  @fentonbutcher has created a JSON file using After Effects 2017 and the BodyMovin plugin.  Unfortunately, the text isn't showing in our react-native application, although it is showing correctly using bodymovin.js in a browser.

It would be good to have an example After Effects and exported JSON file that you believe displays text correctly in a react-native application.

**Comment by fentonbutcher** [comment]
@gpeal here's the link to the version we have working online: https://codepen.io/torrens/project/editor/DVvqmo/

Can you access this?

**Comment by fentonbutcher** [comment]
@gpeal Morning. Sorry for all the messages. Do you know why we might be having the issues? We think it might be not being able to find the fonts.

**Comment by gpeal** [comment]
@fentonbutcher 
Yes, it renders fine on Android with React Native. It won't work on iOS though since iOS doesn't support text yet.
You can try it in the sample app from the lottie-react-native repo to test yourself.
![image](https://user-images.githubusercontent.com/1307745/28585521-4ab26fc8-7125-11e7-8fa8-01a90807074e.png)
[Text.json.zip](https://github.com/airbnb/lottie-android/files/1174268/Text.json.zip)

**Comment by fentonbutcher** [comment]
@gpeal thank you - unfortunately we're creating an app for both android and ios

**Comment by gpeal** [comment]
@fentonbutcher Got it. Stay tuned. iOS will get support eventually.

**Comment by hake** [comment]
@gpeal news about ios text and dynamic text support ?

Thanks for the work

**Comment by rotorgames** [comment]
@gpeal Any news about text supporting on ios?

**Comment by gpeal** [comment]
@rotorgames It's not on the immediate roadmap but we have talked about it. You can track updated on lottie-ios.

**Comment by rkcoders** [comment]
val textDelegate = TextDelegate(animationView)
hello when i use TextDelegate my 2 text display and 2 text not display can you tell me what to do

**Comment by amarmuno** [comment]
This also happens to me in Android, although in my case the two texts contained in the lottie disappear.

@gpeal @rkcoders , have you found a solution? Could it be because the text has a custom font?

Thanks.
