### ISSUE TITLE
Can't load a lottie json with image asset in android compose

### ISSUE THREAD

**Issue by DavidIbrahim** [airbnb/lottie-android#1730]
I am new to Lottie and I am using it with android-compose  and I have Lottie JSON that looks like that
`{"v":"5.7.3","fr":60,"ip":0,"op":420,"w":600,"h":500,"nm":"Pan","ddd":0,"assets":[{"id":"image_0","w":1280,"h":621,"u":"images/","p":"image_0.png","e":0}`
and I  can find in the documentation how to easily do it in normal [view system](https://airbnb.io/lottie/#/android?id=setting-your-images) but not in android compose, so any help?

**Comment by oas004** [comment]
You can find information about how to implement lottie in compose [here](https://airbnb.io/lottie/#/android-compose)  😃

**Comment by DavidIbrahim** [comment]
> You can find information about how to implement lottie in compose [here](https://airbnb.io/lottie/#/android-compose) 😃

I already read it and I already can load lottie animations except those that includes assets images like image_0.png which is in the question

**Comment by gpeal** [comment]
I'll need to expose `setImageAssetsFolder` and `setImageAssetsDelegate` in the next release.

**Comment by DavidIbrahim** [comment]
That's great, thanks :D
