### ISSUE TITLE
Size Optimisation Issue

### ISSUE THREAD

**Issue by ravikiran-dream11** [airbnb/lottie-android#1731]
Hey, we are using Lottie for the first time. You guys have done an amazing job with this.

Our animation file(json) is coming out to be 1mb after a lot of optimisation from our design side, reduced it from 8mb to 1mb. It would be great if you could suggest if we are missing anything and if we can optimise this further. It is an animation we want for the onboarding screen of our android and iOS applications, representing 3 primary screens. 
You can find the animation(1.6mb version) here https://lottiefiles.com/share/dmhld1rx 

Below are the notes from our designer.

Steps referred to in the animation are
1. Launch image to Screen
2. Screen 1 transforms to screen2
3. Screen2 transforms to Screeen3

**1st Attempt :** 
Created Test file with no compression.
Step 1 Animation (Launch to screen1 )
Outcome - 5MB

**2nd Attempt :** 
Reduced Image size manually.
Reduced the frame rate from 30fps to 10fps.
Set json compression rate from 100 to 50.
Step 1 Animation 
Outcome - 3 MB

**3rd Attempt :** 
Followed above points with 30fps.
Outcome - 3MB ( same )

**4th Attempt:**
Reduced size of the images manually till 0% reduction.
Decrease art-board size by removing logo and bottom padding.
Removed starting hold between.
2 Step animation
Outcome - 1 MB 

**5th Attempt:**
Break down each step into individual Json files
Step 1 : 406 KB
Step 1 and 2 : 652 KB

**6th Attempt:**
Whole animation with png - 1.6 MB
With .webp - 2MB

**7th Attempt:**
Exported svg files into illustrator and created .ai files.
Tried pop out animation for single step.
Output - 1.7 MB

**Comment by gpeal** [comment]
@ravikiran-dream11 The animation is only 200k without images. You could uncheck embed images in json and provide them yourself with `setImageAssetsFolder` or with an `ImageAssetDelegate`
http://airbnb.io/lottie/#/android?id=images
![image](https://user-images.githubusercontent.com/1307745/105220756-02867200-5b0d-11eb-8526-f0ceeac04975.png)
