### ISSUE TITLE
Compose Snapshots + Versioning

### ISSUE THREAD

**Issue by jossiwolf** [airbnb/lottie-android#1733]
I couldn't find any docs on where the snapshots for `lottie-compose` are published 🙈

How do I include the latest `lottie-compose` library as a dependency?

I also just saw that I didn't update https://github.com/airbnb/lottie-android/blob/master/CHANGELOG_COMPOSE.md with my PR, would it make sense to point out that there won't be numbered releases for every Compose version but rather to look for snapshot builds?

https://github.com/airbnb/lottie/blob/master/android-compose.md also currently points to `lottie-compose` `1.0.0-alpha05`, maybe there could be a badge pointing to the latest snapshot build and how to include it.

Happy to contribute on this with some basic info :)

**Comment by gpeal** [comment]
@jossiwolf The lastest snapshots are [on sonatype](https://oss.sonatype.org/content/repositories/snapshots/com/airbnb/android/lottie-compose/1.0.0-alpha06-SNAPSHOT/lottie-compose-1.0.0-alpha06-20210130.212312-17.pom). Does that work for you? We should add a svg badge for the snapshot as well.

Feel free to update the changelog and readme!

**Comment by jossiwolf** [comment]
Perfect, I couldn't just couldn't find the repo URL😂 Will open a PR in a bit!
