### ISSUE TITLE
Xamarin Forms and EnableMergePathsForKitKatAndAbove

### ISSUE THREAD

**Issue by Sven-Q** [airbnb/lottie-android#1736]
Dear,

In my project I am trying to use some lottie animations. These however are using some merge paths and thus I will have to enable this feature, since it is disabled by default.

I know that you have an option on the `LottieAnimationView`, `EnableMergePathsForKitKatAndAbove()`. I do only find solutions for this when you are working in an android-only project. In my case I have to also support iOS and thus my folder structure is structured by the default Xamarin logic.
* Android project 
- MainActivity.cs

* iOS project
*- ...

* Shared
- MainPage.xaml
- QRScanPage.xaml
- ...

So now I want that when the QRScanPage is visible an animation plays.

I have tried multiple ways to achieve this:
* Made use of MessagingCenter to go from QRScanPage to MainActivity to enable the setting. 
* On initial load setting the setting
* ...

Everytime I just am not able to get the view to get the LottieAnimationView from to set the setting.

In the sample project they make use of a Fragment, but this seems to be overkill for my project to make all that changes to just enable this setting.

Anyone has an idea how to achieve this?

Also I believe the documentation and/or sample project should project this better.

**Comment by gpeal** [comment]
Sorry, this repo is just for the Android library. I have no experience with Xamarin.
