### ISSUE TITLE
How can we check animation is completed?

### ISSUE THREAD

**Issue by mitulghoda** [airbnb/lottie-android#1739]
I need to check whether the animation is complete load one time.
I want to open new screen when animation is completely load single time

**Comment by gpeal** [comment]
You can use LottieCompositionFactory which will return the composition. You can then set the composition on LottieAnimationView directly and use the same listener as the trigger to open a new screen.

You can also pre-cache the composition. If you call one of the LottieCompositionFactory methods at any point while your app is running, it will parse and cache the animation in the background and it will be available immediately when you need it.
