### ISSUE TITLE
freezes LottieImageView with MaterialContainerTransform

### ISSUE THREAD

**Issue by brayanm23** [airbnb/lottie-android#1745]
I am using MaterialContainerTransform to transition from a fragment to an activity, I am setting the transitionName to android.R.id.content. The transition is executed well but in the destination activity I have a lottie and it is frozen.

I tried playAnimation() programmatically, I tried to start the lottie in a new thread, but could never get it to work.

https://user-images.githubusercontent.com/32348263/108260462-20151e80-7141-11eb-9082-67e695aeb6f7.mov

**Comment by gpeal** [comment]
@brayanm23 Android doesn't draw during window transitions so this likely has nothing to do with Lottie. Try a `<ProgressBar />` and see if it does the same thing. I would recommend trying to make this a Fragment transition.

If you think there is an issue, feel free to make a repro in a fork of the issue-repro module in this repository and reopen this issue and I can take another look.
