### ISSUE TITLE
very serious（I don't know what's the problem）：java.lang.IllegalStateException You must set an images folder before loading an image. Set it with LottieComposition#setImagesFolder or LottieDrawable#setImagesFolder com.airbnb.lottie.manager.ImageAssetManager.bitmapForId

### ISSUE THREAD

**Issue by xwbbwx110** [airbnb/lottie-android#1746]
This problem did not appear when we tested it, but it appeared in large numbers in the production environment. There have been 100,000 crashes so far. Please take a look.

1.I combined a view, and then LottieAnimationView is included in it, as shown below:
[<img width="1515" alt="1" src="https://user-images.githubusercontent.com/9714128/108619519-5a8ffb80-7460-11eb-85af-69181298df55.png">
](url)

2.Then I also set imageAssetsFolder when playing the animation
[<img width="1035" alt="2" src="https://user-images.githubusercontent.com/9714128/108619599-d8540700-7460-11eb-9795-650d4b686c4d.png">
](url)

3.LottieAnimationView is used as AppCompatImageView by default. When some data comes, it will call the showLottieAnim method in the above picture to play

4.Our lottie animation file contains json and asset image resources

Here is our lottie:

[<img width="633" alt="3" src="https://user-images.githubusercontent.com/9714128/108619719-94153680-7461-11eb-8716-78e5782a78c0.png">
](url)

**Comment by gpeal** [comment]
I'm sorry to hear that you're getting so many crashes. It's going to be hard for me to help without an explicit way to reproduce this.

Is it possible that your LottieAnimationView is loading your animation on initialization which happens before you get the chance to set the image assets folder?

**Comment by xwbbwx110** [comment]
Our initialization will not play animation (by default, it is set by lottieAnimationView.setImageDrawable() called by a static image). We will play animation after responding through interface data. The image assets folder will be set before playing.

Our scene is in a fragment, and every time we switch to another fragment, all lottieAnimation will be cancelled. Now I set the image assets folder every time before playing the animation

**Comment by xwbbwx110** [comment]
@gpeal 

Thank you very much for receiving your reply。

Our initialization will not play animation (by default, it is set by lottieAnimationView.setImageDrawable() called by a static image). We will play animation after responding through interface data. The image assets folder will be set before playing.

Our scene is in a fragment, and every time we switch to another fragment, all lottieAnimation will be cancelled. Now I set the image assets folder every time before playing the animation

**Comment by xwbbwx110** [comment]
This anomaly is caused by the Online environment, and we can hardly reproduce it during testing.It depends on the situation that this is prone to appear on poorly configured phones，I am not sure if there is some problem with my usage

[![7](https://user-images.githubusercontent.com/9714128/108653224-e0fc1a00-7500-11eb-8ecd-fca34fb4028d.png)
](url)

**Comment by gpeal** [comment]
@xwbbwx110 That must be really frustrating that you're seeing so many crashes from this but thousands of apps are using images without this issue so it may be a configuration issue within your app. However, if it is not and there is an issue with the library, please provide a repro and I'll take a look asap.

**Comment by xwbbwx110** [comment]
@gpeal 
We have reproduced this problem, but not every time.
Prerequisites:
1. The user's mobile phone configuration is very poor, and the ram is 2GB or less
2. Open our application and go directly to a fragment, this fragment uses 6 lottie animations
3. Then put it to run in the background
4. Play other apps
5. Back to our application, this time may cause the entire view to rebuild, and then cause this problem

In our composite control, the ID of each LottieAnimationView object is the same

**Comment by gpeal** [comment]
@xwbbwx110 I'm glad you're beginning to narrow down the issue but until you can help me find a reproduction, I won't be able to help, unfortunately.

**Comment by xwbbwx110** [comment]
@gpeal 
The problem that was finally fixed in this way has been released in the official version. I can't provide our code, but you can refer to it

[
<img width="1409" alt="WX20210303-104318@2x" src="https://user-images.githubusercontent.com/9714128/109744601-899b2f80-7c0d-11eb-8a3c-38f442d4c05b.png">
](url)

**Comment by xwbbwx110** [comment]
Every time a CCLottieAnimationView object is created, its member variable folderUrl will be set, whether it is new or rebuilt

**Comment by kingiis** [comment]
i find a way to fix this
i use the lottie with  only a json.
、、
//this line is required
 lottieView.imageAssetsFolder = "img/"
        Anims.load(context, pageInfo!!.bg_json_url, object : Anims.onLoadListener {
            override fun onSuccess(result: LottieComposition?) {
                context.runOnUiThread {
                    lottieView.setComposition(result!!)
                    lottieView.playAnimation()
                }
            }

            override fun onFail() {
                Logi.i("animbg|加载失败")
                context.runOnUiThread { context.finish() }
            }
        })
//same tiem  you need create a floder which name as img that under assets

**Comment by kingiis** [comment]
I'm too lazy to curse our designers. We can solve it by adding this code.
@xwbbwx110
