### ISSUE TITLE
LottieDrawable as seekbar thumb doesn't work

### ISSUE THREAD

**Issue by jefersonbaixo** [airbnb/lottie-android#1749]
I'm trying to put a lottie animation as thumb of a seekbar but when I drag the thumb itself is not dragged, just the progress of seekbar is changed.
Here is my code:

`class MainActivity : AppCompatActivity() {

    private lateinit var binding: ActivityMainBinding
    private val thumb = LottieDrawable()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)
        val seek = SeekBar(this)
        seek.thumb = thumb
        val lp = ActionBar.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT)
        thumb.scale = 0.3F
        seek.layoutParams = lp
        seek.max = 200
        seek.progress = 100

        LottieCompositionFactory.fromAsset(this, "dot.json").addListener {
            thumb.composition = it
            thumb.repeatCount = LottieDrawable.INFINITE
            thumb.playAnimation()
            binding.root.addView(seek)
        }

    }

}`

**Comment by gpeal** [comment]
LottieDrawable has no way to notify the SeekBar that it needs to redraw, call `thumb.setCallback(seek)` and it should work. You can reopen with a sample project if this doesn't fix it.

**Comment by Jianzhao-Huang** [comment]
I've try calling thumb.setCallback(seek), but it doesn't work! Is there anything wrong? Could you please reopen this issue?
