### ISSUE TITLE
setAnimationFromUrl cause a memory leak

### ISSUE THREAD

**Issue by yushiwo** [airbnb/lottie-android#1753]
LottieTask<LottieComposition> task = cacheComposition ?
        LottieCompositionFactory.fromUrl(getContext(), url) : LottieCompositionFactory.fromUrl(getContext(), url, null);

LottieCompositionFactory use view context，cause leak

**Comment by gpeal** [comment]
Can you be more specific on what the leak is?

**Comment by gpeal** [comment]
Closing due to lack of response. Feel free to reopen with more information and a reproduction case.
