### ISSUE TITLE
Memory not recycle

### ISSUE THREAD

**Issue by ForLovelj** [airbnb/lottie-android#1756]
Lottie did not properly reclaim native memory after exiting the page.
Lottie Version：3.5.0
1. AActivity -> BActivity
2. playAnimtion
3. exit BActivity -> AActivity
4. See memory state

![memory](https://user-images.githubusercontent.com/16838140/110448824-8536b100-80fc-11eb-8c00-a052c2364207.png)
If I use multiple different image animations, the memory will keep increasing.Maybe it will be OOM if it reaches a certain threshold.

**Comment by ForLovelj** [comment]
I use iOS to do the same thing and it works fine.

**Comment by gpeal** [comment]
@ForLovelj Lottie caches compositions by default. This includes any images associated with it. To disable that, add `app:lottie_cacheComposition` to your XML file. If that is not sufficient, please reopen this with a reproduction in a fork of the issue-repro module in this repository.

**Comment by ForLovelj** [comment]
> @ForLovelj Lottie caches compositions by default. This includes any images associated with it. To disable that, add `app:lottie_cacheComposition` to your XML file. If that is not sufficient, please reopen this with a reproduction in a fork of the issue-repro module in this repository.

I tried adding the app:lottie_cacheComposition="false" attribute, which looks just like before,Memory is not recycle.

**Comment by gpeal** [comment]
@ForLovelj Can you reopen this with a project that reproduces this?

**Comment by ForLovelj** [comment]
> Can you reopen this with a project that reproduces this?
here
[TestLottie](https://github.com/ForLovelj/TestLottie)

**Comment by honeykhatri87** [comment]
I dont want yo receive emails from ur site

Sent from Yahoo Mail on Android 
 
  On Thu, 25 Mar 2021 at 7:07 am, ***@***.***> wrote:   



Can you reopen this with a project that reproduces this?


here
TestLottie

**Comment by ForLovelj** [comment]
@gpeal Did you verify the problem?

**Comment by gabrielbezerra81** [comment]
Had this error on two Android 7 devices. Anyone solved?

**Comment by Kingsavage3** [comment]
Stop

**Comment by b1tb1t** [comment]
After the animation ends, directly set a new empty resource
lottieAnimView.setAnimation(R.raw.empty)

**Comment by ForLovelj** [comment]
lottie has no memory leaks, and it works just fine, with the following caveats:

Prior to Android 8.0, memory occupied by Bitmap pixels was allocated in the Java heap

In Android 8.0 and later, memory used by Bitmap pixels is allocated to the Native Heap

Therefore, try not to use frame animation composed of a large number of pictures under Android 8.0
