### ISSUE TITLE
crash  happen when I  use local  zip file ,jpg  not support

### ISSUE THREAD

**Issue by yuerolling** [airbnb/lottie-android#1767]
hi , I  load resource  with a zip file ,  but crash  happen 
I found the code in source file LottieCompositionFactory.java

else if (entryName.contains(".png") || entryName.contains(".webp")) 

but  my image file end with ".jpg " , I wonder ,is this  a bug  or not support other format ?

**Comment by mwshubham** [comment]
I was moving .json to .zip for APK size reduction. And found the same. I am wondering why this was discovered so late.
