### ISSUE TITLE
Support Image from sdcard instead of assets

### ISSUE THREAD

**Issue by EflakeEver** [airbnb/lottie-android#177]
LottieAnimationView only support setImageAssetsFolder method for loading image from assets , but now i have to load image from sdcard , so what is the reason only load image from assets file?

**Comment by gpeal** [comment]
@EflakeEver When used in production (not in the sample app), all images should be bundled with the assets in your apk. Does that make sense?

**Comment by EflakeEver** [comment]
@gpeal , a demand in production environment , such as supporting  an upgradable gift animation in live app, need us to download all keyframe resource from network，including json file and image resources. so that i need a way to using image from sdcard,  can you give me some suggesstion? thanks~

**Comment by gpeal** [comment]
@EflakeEver I just added an asset delegate that would allow you to load and provide the bitmaps yourself. I'm also conveniently cutting 1.5.3 now so it'll be in that.

**Comment by gpeal** [comment]
Let me know if this will work for you! I think it will.

**Comment by EflakeEver** [comment]
@gpeal , I just try your new code, and it works well, hope it may help others, thank you gpeal~

**Comment by AlanCheen** [comment]
This is great!
Thanks!
