### ISSUE TITLE
My json animation is not rendering/working on android devices 

### ISSUE THREAD

**Issue by NickMeloy** [airbnb/lottie-android#1770]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I'm not sure which part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work and i've attached the json file used.

**Describe the bug**
Rendered out this simple loading animation that is working on every device but android. Not really sure what's going on.

**What version of Lottie did you test this on?**
3.5.0

**What version of Android did you test this on?**
11

**Steps To Reproduce**
Steps to reproduce the behavior: open in any android device. we used lottiefiles to test.

Please let me know if there's any other things you need from me. 

Thank you for a really awesome tool!

[circle_spinner_final.aep.zip](https://github.com/airbnb/lottie-android/files/6182908/circle_spinner_final.aep.zip)
[circle_spinner_standard.json.zip](https://github.com/airbnb/lottie-android/files/6182911/circle_spinner_standard.json.zip)

**Comment by gpeal** [comment]
@NickMeloy Can you be more specific? This is what I see. Left is web, right is Android.
![animation](https://user-images.githubusercontent.com/1307745/112093544-d8761e00-8b56-11eb-88b3-848b69768ba4.gif)

**Comment by NickMeloy** [comment]
@gpeal Left is web, right is using an android device.

https://user-images.githubusercontent.com/3473956/112187309-5dede280-8bd8-11eb-8e60-688c2584e46a.mov

**Comment by gpeal** [comment]
@NickMeloy Can you be more specific? Is that using `lottie-android` if so, which version? Are system animations disabled?

**Comment by pbhatter89** [comment]
Lottie version : implementation "com.airbnb.android:lottie:3.5.0"
While doing some research, I found out the issue occurs only on samsung devices and works on other Android physical devices  and emulators- like the Pixel.tried a few other animation jsons too on Samsung none worked 

issues:
1. samsung device note 10 plus(android 11) and samsung s20(android 11) -----no animation is seen when we upload the json in the https://lottiefiles.com/preview and scan the qr code with the lottie test file app 
2. in pixel emulator and the pixel device i have observed the animation is show but its flickering

**Comment by gpeal** [comment]
@pbhatter89 I think this is because you have system animations disabled. I tried this on my Galaxy S20 and it works fine.

If this is the case, you can follow my advice [here](https://github.com/airbnb/lottie-android/issues/1772#issuecomment-804967910)

**Comment by NickMeloy** [comment]
@gpeal Looks like our team solved the issue with your help, thank you so much!

**Comment by pbhatter89** [comment]
@gpeal thank you for your time
