### ISSUE TITLE
export asset - imported json feed data

### ISSUE THREAD

**Issue by mehras1991** [airbnb/lottie-android#1777]
In AE you are able to import a json / feed data as a file. and use the data information. for example link city name to city data in json file.

but lottie/bodymovin doesn't export that json file with the animation. So the sources are not linked to anything.

To help you understand I included a screenshot which explains my test animation. In the exported animation the layer name is shown as the text source, not the actual data.

![Screen Shot 2021-03-26 at 10 27 16 PM](https://user-images.githubusercontent.com/1312954/112683338-75e88f00-8e82-11eb-945b-fc35dc862536.png)

**Comment by gpeal** [comment]
@mehras1991 Expressions are [not supported](http://airbnb.io/lottie/#/supported-features) by Lottie Android.

**Comment by mehras1991** [comment]
What about for demo html? For using the data on the web

**Comment by mehras1991** [comment]
> @mehras1991 Expressions are [not supported](http://airbnb.io/lottie/#/supported-features) by Lottie Android.



> @mehras1991 Expressions are [not supported](http://airbnb.io/lottie/#/supported-features) by Lottie Android.

Maybe you can add support by default for html demo? The data can be used and repurposed on the web

**Comment by gpeal** [comment]
@mehras1991 Not sure I follow.

**Comment by mehras1991** [comment]
> @mehras1991 Not sure I follow.

In After effect you can import a jquery file and reuse it. Let's say the jquery has data for city name. You connect it to the "text.sourceText". So when the jquery file is updated (let's say From Chicago to California) AE also update it without any extra work.

In Bodymovin, when selecting the export option **DEMO** which says _Exports an html for local preview_ . Same Logic as AE does with an imported jquery, if the jquery file is exported while generating .html in bodymovin, Same thing can happen in the .html lottie file. (so on my webapp that specific text can be self updated without human any interaction)

I also attached a zip to my AE project test file. In my project I automated to write the data from API to a jquery file outside of AE.

I hope I could explain what I was trying to say. I'm sure this can be easily done and supported by lottie. I will be glad to show you over a quick video call if my explanation wasn't saying what I am trying to say.
[4-API.zip](https://github.com/airbnb/lottie-android/files/6216185/4-API.zip)

**Comment by gpeal** [comment]
@mehras1991 I'm still not sure I understand but would [dynamic properties](http://airbnb.io/lottie/#/android?id=dynamic-properties) help? That would allow your app to replace text in the animation with arbitrary other text at runtime.

**Comment by mehras1991** [comment]
> @mehras1991 I'm still not sure I understand but would [dynamic properties](http://airbnb.io/lottie/#/android?id=dynamic-properties) help? That would allow your app to replace text in the animation with arbitrary other text at runtime.

Yes and no. in AE you can import json or xml tables to use the data.

In the test project I attached earlier as well
[4-API.zip](https://github.com/airbnb/lottie-android/files/6216211/4-API.zip)
Texts for "city,weather status, temperature"  are being read from an external .json file.

Exporting a .html demo with lottie. It will be nice to have that json file and expression supported.

**Comment by mehras1991** [comment]
> @mehras1991 I'm still not sure I understand but would [dynamic properties](http://airbnb.io/lottie/#/android?id=dynamic-properties) help? That would allow your app to replace text in the animation with arbitrary other text at runtime.

[Here](https://illo.tv/olympics) you can see a case study where a json or xml table (imported to AE) was used to automation of videos for **Olympics Medal Tracker**

I'm just trying to say export and support for that .xml / .json file will be very nice. Since web browsers can handle such task.
