### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError Failed to allocate a 5935116 byte allocation with 2122648 free bytes and 2MB until OOM com.airbnb.lottie.utils.Utils.resizeBitmapIfNeeded

### ISSUE THREAD

**Issue by wangyangkeCeler** [airbnb/lottie-android#1780]
Fatal Exception: java.lang.OutOfMemoryError
Failed to allocate a 5935116 byte allocation with 2122648 free bytes and 2MB until OOM
com.airbnb.lottie.utils.Utils.resizeBitmapIfNeeded
device:android7.1.1:
lottie version:3.5.0
mycode:
<com.airbnb.lottie.LottieAnimationView
        app:lottie_cacheComposition="false"
        android:id="@+id/animation_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:adjustViewBounds="true"
        android:scaleType="centerInside" />
log:
dalvik.system.VMRuntime.newNonMovableArray (VMRuntime.java)
android.graphics.Bitmap.nativeCreate (Bitmap.java)
android.graphics.Bitmap.createBitmap (Bitmap.java:888)
android.graphics.Bitmap.createBitmap (Bitmap.java:865)
android.graphics.Bitmap.createBitmap (Bitmap.java:796)
android.graphics.Bitmap.createScaledBitmap (Bitmap.java:672)
com.airbnb.lottie.utils.Utils.resizeBitmapIfNeeded (Utils.java:280)
com.airbnb.lottie.manager.ImageAssetManager.bitmapForId (ImageAssetManager.java:117)
com.airbnb.lottie.LottieDrawable.getImageAsset (LottieDrawable.java:1071)
com.airbnb.lottie.model.layer.ImageLayer.getBitmap (ImageLayer.java:63)
com.airbnb.lottie.model.layer.ImageLayer.drawLayer (ImageLayer.java:33)
com.airbnb.lottie.model.layer.BaseLayer.draw (BaseLayer.java:239)
com.airbnb.lottie.model.layer.CompositionLayer.drawLayer (CompositionLayer.java:120)
com.airbnb.lottie.model.layer.BaseLayer.draw (BaseLayer.java:239)
com.airbnb.lottie.LottieDrawable.drawWithOriginalAspectRatio (LottieDrawable.java:1255)
com.airbnb.lottie.LottieDrawable.drawInternal (LottieDrawable.java:401)
com.airbnb.lottie.LottieDrawable.draw (LottieDrawable.java:391)
android.widget.ImageView.onDraw (ImageView.java:1316)
android.view.View.draw (View.java:17295)
android.view.View.buildDrawingCacheImpl (View.java:16504)
android.view.View.buildDrawingCache (View.java:16365)
com.airbnb.lottie.LottieAnimationView.buildDrawingCache (LottieAnimationView.java:1046)
android.view.View.updateDisplayListIfDirty (View.java:16178)
android.view.View.draw (View.java:17061)
android.view.ViewGroup.drawChild (ViewGroup.java:3767)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:3553)
android.view.View.draw (View.java:17298)
android.view.View.updateDisplayListIfDirty (View.java:16197)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3751)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3731)
android.view.View.updateDisplayListIfDirty (View.java:16160)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3751)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3731)
android.view.View.updateDisplayListIfDirty (View.java:16160)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3751)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3731)
android.view.View.updateDisplayListIfDirty (View.java:16160)
android.view.ThreadedRenderer.updateViewTreeDisplayList (ThreadedRenderer.java:671)
android.view.ThreadedRenderer.updateRootDisplayList (ThreadedRenderer.java:677)
android.view.ThreadedRenderer.draw (ThreadedRenderer.java:789)
android.view.ViewRootImpl.draw (ViewRootImpl.java:3179)
android.view.ViewRootImpl.performDraw (ViewRootImpl.java:2976)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2582)
android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1593)
android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:7089)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:883)
android.view.Choreographer.doCallbacks (Choreographer.java:689)
android.view.Choreographer.doFrame (Choreographer.java:624)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:869)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:159)
android.app.ActivityThread.main (ActivityThread.java:6385)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1096)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:883)

**Comment by gpeal** [comment]
This issue isn't directly related to Lottie, it just happened to fail here because your application was low on memory. However, the upcoming lottie 5 release will allow you to specify lower resolution bitmaps with dynamic properties and Lottie will draw them at the original animation size if you think that the bitmap size is an issue.
