### ISSUE TITLE
Lottie animation display incomplete in Android phone,but display well in preview page of Lottie

### ISSUE THREAD

**Issue by ignorefei** [airbnb/lottie-android#1784]
Here is my code:
```
 animationView.setAnimation("face_recognize_ing.json");
                animationView.setRepeatCount(LottieDrawable.INFINITE);
                animationView.playAnimation();
```
`<com.airbnb.lottie.LottieAnimationView
        android:id="@+id/animationView"
        android:layout_gravity="center_horizontal"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />`

**Comment by ignorefei** [comment]
[jsons.zip](https://github.com/airbnb/lottie-android/files/6278589/jsons.zip)
Here is my json files

**Comment by medsauce** [comment]
This is the first idea I put on hit and my first contribute to the AIRBnB lottie server. Appreciate it!

**Comment by ignorefei** [comment]
Anybody help......

**Comment by gpeal** [comment]
The issue here has to do with the trim path offsets wrapping around 0. I can look in to it but for now, you could work around the issue but tweaking the trim path start/end/offsets.

**Comment by ignorefei** [comment]
Thanks for your reply,I still confused what to do with this issue,Could you please provide some codes here?
Thank you very much
