### ISSUE TITLE
context may leak here, you may use applicationContext instead.

### ISSUE THREAD

**Issue by wys619** [airbnb/lottie-android#1785]
https://github.com/airbnb/lottie-android/blob/ad6e59192e41ce7a51dfc583bc344504bdf48e30/lottie/src/main/java/com/airbnb/lottie/L.java#L107

**Comment by gpeal** [comment]
@wys619 No references to context are held. It's just used to return the cache dir.

**Comment by wys619** [comment]
Excuse me but I mean code like this may be better:

![Uploading wecom-temp-fce39326d94cab7c75ff4025275df647.png…]()
