### ISSUE TITLE
The special json render abnorma with specific size

### ISSUE THREAD

**Issue by Xigong93** [airbnb/lottie-android#1787]
## Bug Description
The special json render abnorma with specific size.
![image](https://user-images.githubusercontent.com/17515825/114359669-cbbd7680-9ba6-11eb-84ef-f1eba772880c.png)

You can find the 25dp had a white dot on the left bottom of the view. But others don't. 

Lottie  version is 3.7.0 

Test on Android 9 simulator and Android 10 HUAWEI P20.
Android 10 HUAWEI P20 shows a white dot when the size is 24dp.
Android 9 simulator shows a white dot when the size is 25dp.
I don't know why . It makes me confused.
## Reproduce sample
https://github.com/pokercc/LottieBug01

## Assets
Json File [bug.zip](https://github.com/airbnb/lottie-android/files/6294842/bug.zip)

**Comment by gpeal** [comment]
@pokercc This is probably a bug in device-specific hardware rendering. You can set the render mode (`app:lottie_renderMode` or `setRenderMode`) to software if it's an issue with this animation.

**Comment by pokercc** [comment]
It's not working.
![image](https://user-images.githubusercontent.com/17515825/114478972-10422400-9c32-11eb-93d4-c19bd3b705a4.png)

**Comment by pokercc** [comment]
Perhaps you could tell me how to debug the problem.

**Comment by gpeal** [comment]
@pokercc You're welcome to clone the repo and take a look at the code yourself. It might be in StrokeContent or TrimPathContent

**Comment by gpeal** [comment]
Without an ability to reproduce this myself, I'm going to have to close this. It may be impossible to detect and fix this on the Lottie side, as well.
