### ISSUE TITLE
Animations dont show all items in android but it shows on the web/ios players

### ISSUE THREAD

**Issue by Drawiin** [airbnb/lottie-android#1788]
**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Bug description**
Whenever i have a animation that has a list os states _(eg. countdown),_ the last item does not show up in the animation when using android _(eg. in a count that should go  from 0 to 5, it only goes from 0 to 4)_, althoug when i play the same animation on the web preview or in the ios, evething works fine, i have tried to use diferent lottie versions and i even tried to play on the Lottie Files app, and the same problem occurs.
I was able to solve the problem by digging in the animation **raw json file** and find the list that describes this states and adding a dummy state at the end, the animations "works as expected", more details about the problem and the animation files bellow:

**I'm using Lottie 3.5.0, tested in android 10, 9 and 7**

**original slice of the raw json animation(for the propoese of simplicity i just let 2 states)**
```json
{
  "k": [
    {"s": {"s": 16,"f": "Montserrat-Bold","t": "counter: 1","j": 2,"tr": 0,"lh": 19.2,"ls": 0,"fc": [1,1,1]},"t": 13},
    {"s": {"s": 16,"f": "Montserrat-Bold","t": "counter: 1","j": 2,"tr": 0,"lh": 19.2,"ls": 0,"fc": [1,1,1]},"t": 33},
  ]
}
```
**the same json with the workaround**
```json
{
  "k": [
    {"s": {"s": 16,"f": "Montserrat-Bold","t": "counter: 1","j": 2,"tr": 0,"lh": 19.2,"ls": 0,"fc": [1,1,1]},"t": 13},
    {"s": {"s": 16,"f": "Montserrat-Bold","t": "counter: 1","j": 2,"tr": 0,"lh": 19.2,"ls": 0,"fc": [1,1,1]},"t": 33},
    {"s": {"s": 16,"f": "Montserrat-Bold","t": "this will never be shown","j": 2,"tr": 0,"lh": 19.2,"ls": 0,"fc": [1,1,1]},"t": 34}
  ]
}
```
**Here are the original animation and the animations with the workaround**
**I wont put any code bacause can be reproduced using the Lottie Files android app**
[The original animation](https://lottiefiles.com/58048-animations)
_this will feel wrong on the web but in the android looks like its fine_
[Same animation with the workaround](https://lottiefiles.com/58049-animation-with-correction)

**Steps To Reproduce**

1. Go to 'the link'
2. Click on 'play the animations'
3. Play the animation usgin the Lottie Files app(QR CODE)
4. See the diference

**Screenshots**
Wont put any since the web preview are way more acurate.

**Comment by gpeal** [comment]
I just tried this on 4.2.2 and it counted up to 5. Feel free to reopen this if you think it's still an issue.
