### ISSUE TITLE
Render issue with toolbar in Safari Version 14.0.3

### ISSUE THREAD

**Issue by segill** [airbnb/lottie-android#1789]
The issue appears to be directly related to the Toolbar and its use of it in Safari Version 14.0.3 (16610.4.3.1.7). Anytime the Toolbar is visible as a UI element, the animation is jittery and stutters. It's possible that the issue just appeared with an update to the Safari browser. I am uncertain if the bug is on Safari, but the issue is directly related to the Toolbar (play and stop button as well as the timeline). Whenever the Toolbar is removed, the animation plays smoothly. This issue is visible in both desktop and mobile (IOS 14.4.2)

Anytime the Toolbar is visible as a UI element, the animation is jittery and stutters. When the Toolbar is removed, the animation works perfectly.

https://user-images.githubusercontent.com/48763455/114914789-60fb7d80-9de8-11eb-80e9-264edac9a0ce.mov

[RENDER ERROR.zip](https://github.com/airbnb/lottie-android/files/6320167/RENDER.ERROR.zip)

**Comment by gpeal** [comment]
@segill Did you intend to post this in `lottie-android`? You might have meant lottie-ios or lottie-web

**Comment by segill** [comment]
@gpeal, is lottie-web specific to bodymovin? I'll prob. repost there.
