### ISSUE TITLE
LottieDrawable needs public access for APIs

### ISSUE THREAD

**Issue by inemnitable** [airbnb/lottie-android#180]
Several important APIs in LottieDrawable still have package access as of 1.5.3. These include loop(), isLooping(), isAnimating(), and cancelAnimation(). I would like to not have to use reflection in order to use  LottieDrawable.

**Comment by 0legg** [comment]
@inemnitable As a workaround, you can have you "proxy" class inside `com.airbnb.lottie` package, which exposes these methods usage as public.

**Comment by gpeal** [comment]
@inemnitable I'll open these up in the next release.

**Comment by inemnitable** [comment]
cancelAnimation() still has package access.

**Comment by inemnitable** [comment]
Thanks for this!
