### ISSUE TITLE
Starting lottie animation via ViewBinding access doesn't work

### ISSUE THREAD

**Issue by Ynnck123** [airbnb/lottie-android#1801]
I use `ViewBinding` in my Android Project. I am using the version 3.7.0 of the lottie android library. 

My goal is to deactivate auto-play and start the animation programatically when I need it.

The `LottieAnimationView` is contained in a `ConstraintLayout` like the following XML snippet:
```
<androidx.constraintlayout.widget.ConstraintLayout
    ...>
    <com.airbnb.lottie.LottieAnimationView
        android:id="@+id/lottie_animation"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        android:layout_margin="16dp"
        app:lottie_autoPlay="false"
        app:lottie_fileName="lotties/my_lottie_file.json" />

</androidx.constraintlayout.widget.ConstraintLayout>
```

When I access the `LottieAnimationView` from my activity via ViewBinding, I cannot start the animation programatically. But if I access it via  `findViewById<LottieAnimationView>(R.id.lottie_animation).playAnimation()` it starts as expected. 

Isn't ViewBinding supported?

**Comment by gpeal** [comment]
@Ynnck123 You'll have to attach a sample project. I've used Lottie with view binding before.
