### ISSUE TITLE
Rendering bug while using Jetpack Compose LottieAnimation for some animation jsons

### ISSUE THREAD

**Issue by hongwei-bai** [airbnb/lottie-android#1803]
Hey I am using Lottie for long time, and it's awesome. However, I have a few problems recently while migrating my codebase to Jetpack Compose. The Lottie animation is from here: https://lottiefiles.com/14429-tv
It works perfectly on xml layout. But it doesn't while using Jetpack Compose LottieAnimation. Some of the graphs are missing.
For example: the face of the person is missing, similar things happen to a few other elements.
![image](https://user-images.githubusercontent.com/19883889/116957415-2a27d180-acdb-11eb-91c8-a85a7080b9d6.png)

The normal one:
![image](https://user-images.githubusercontent.com/19883889/116957385-18dec500-acdb-11eb-9b19-0d072a81e720.png)

My Lotte-Compose version is 'com.airbnb.android:lottie-compose:1.0.0-beta03-1', and I even tried to downgrade but still not working.
Lottie version is: com.airbnb.android:lottie:3.7.0
Jetpack Compose version: ext.compose_version = "1.0.0-beta05"

1. Using xml layout Lottie animation for: https://lottiefiles.com/14429-tv, it works perfectly!
2. In the same App, using LottieAnimation in Jetpack Compose, it doesn't render correctly.

Hope you get a chance to have a look at.
Much appreciated!
bhw

**Comment by apoehlmann** [comment]
I have the same issue without lottie-compose. We are using the lottie version 3.7.0 and could see the issue only on some devices.

**Comment by gpeal** [comment]
@hongwei-bai try disabling merge paths
@apoehlmann Try using the software render mode (set via XML attr or a method on LottieAnimationView/LottieDrawable)

**Comment by hongwei-bai** [comment]
@gpeal , thanks! disabling merge paths works!
