### ISSUE TITLE
Loading images dynamically for given layers

### ISSUE THREAD

**Issue by Pavel87** [airbnb/lottie-android#1807]
Our Lottie json file is stripped of images and you can imagine it as having an invisible puppet. The goal is to load different body parts(represented by images) for different characters and then play animation defined by markers.

Our Lottie file works great on web and ios(using AnimationSubviews) as is but not sure how to achieve the image loading for each layer using android SDK as I don't see how I can replace/load image to a layer defined by **keypath**.

Here is an example for the layer **head**
```
      "ddd": 0,
      "ind": 12,
      "ty": 2,
      "nm": ".head",
      "cl": "head",
      "parent": 17,
      "refId": "image_5",
      "sr": 1,
```

<img width="374" alt="Screen Shot 2021-05-16 at 6 20 23 PM" src="https://user-images.githubusercontent.com/5558923/118420467-c8b91880-b673-11eb-82bc-33c42a85a6a7.png">

**Comment by gpeal** [comment]
@Pavel87 You want to use an [ImageAssetDelegate](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/ImageAssetDelegate.java). It will achieve what you want rather than with dynamic properties.

**Comment by Pavel87** [comment]
@gpeal ok, thanks. I guess I then can't use the key path but rather the image asset id ... 
from my example above it would be:
`"refId": "image_5",`

**Comment by gpeal** [comment]
@Pavel87 That is correct!
