### ISSUE TITLE
Update jetpack compose to beta07 to fix 'NoSuchMethodError: No interface method startReplaceableGroup'

### ISSUE THREAD

**Issue by Tom-Alphero** [airbnb/lottie-android#1808]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Checklist**

1. Fork this repository into your account.
2. Reproduce your issue in the issue-repro module. Issues without a repro in the issue-repro 
   module may be auto-closed.

**Link to fork with a repro in the issue-repro module**

**Describe the bug**

Jetpack compose is (at time of writing) beta 07.  When updating to beta 07, all dependencies must also update to use it.  Lottie does not appear to have done so yet and so results in the following crash when attempting to use a lottie composable:

    java.lang.NoSuchMethodError: No interface method startReplaceableGroup(ILjava/lang/String;)V in class Landroidx/compose/runtime/Composer; or its super classes (declaration of 'androidx.compose.runtime.Composer' appears in /data/app/com.alphero.bach-gJLQhlnFXyfvM_FIorGBAw==/base.apk)
        at com.airbnb.lottie.compose.LottieAnimationStateKt.rememberLottieAnimationState(Unknown Source:7)

The compose docs give a heads up that this will happen - https://developer.android.com/jetpack/androidx/releases/compose-foundation

![image](https://user-images.githubusercontent.com/82988810/118754461-37d47e00-b8bb-11eb-8645-98a4afbf2d8d.png)

This also happens on the latest snapshot, "com.airbnb.android:lottie-compose:1.0.0-beta04-2-SNAPSHOT"

**Steps To Reproduce**

1. Create jetpack compose project using beta07.
2. Add latest lottie dependency 
3. Put `rememberLottieAnimationState()` somewhere in the composition
4. Run app - it will crash when attempting to render that composition

**Comment by gpeal** [comment]
Will be fixed in https://github.com/airbnb/lottie-android/pull/1793

**Comment by Tom-Alphero** [comment]
@gpeal I see a commit has been made for beta07 - are snapshots generated nightly?

**Comment by gpeal** [comment]
@Tom-Alphero The PR has to be landed first
