### ISSUE TITLE
Deployment failure of beta 07:  Execution failed for task ':lottie-compose:signMavenPublication'.

### ISSUE THREAD

**Issue by thesauri** [airbnb/lottie-android#1811]
Deployment of `compose-1.0.0-beta07-1` seems to fail with the following error:

```
286: FAILURE: Build failed with an exception.

269: * What went wrong:
270: Execution failed for task ':lottie-compose:signMavenPublication'.
271: > Cannot perform signing task ':lottie-compose:signMavenPublication' because it has no configured signatory
```

In practical terms, the latest version with a fix for Jetpack Compose beta 07 isn't available in Sonatype Nexus yet. 

https://github.com/airbnb/lottie-android/runs/2627534892

**Comment by gpeal** [comment]
@thesauri That's just the snapshot auto-deployment. I just updated it to 1.0.0-beta07-2-SNAPSHOT and it should be fine.

The actual version [was already released](https://repo1.maven.org/maven2/com/airbnb/android/lottie-compose/1.0.0-beta07-1/)
