### ISSUE TITLE
Could not resolve com.airbnb.android:lottie:3.7.1-SNAPSHOT

### ISSUE THREAD

**Issue by OAbdullahs** [airbnb/lottie-android#1813]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Checklist**

1. Fork this repository into your account.
2. Reproduce your issue in the issue-repro module. Issues without a repro in the issue-repro 
   module may be auto-closed.

**Link to fork with a repro in the issue-repro module**

**Describe the bug**
When using Lottie beta 7 version the app crash on compile with a log  "Could not resolve com.airbnb.android:lottie:3.7.1-SNAPSHOT"

Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.airbnb.android:lottie:3.7.1-SNAPSHOT.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/airbnb/android/lottie/3.7.1-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/airbnb/android/lottie/3.7.1-SNAPSHOT/lottie-3.7.1-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/airbnb/android/lottie/3.7.1-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/airbnb/android/lottie/3.7.1-SNAPSHOT/lottie-3.7.1-SNAPSHOT.pom
       - https://jcenter.bintray.com/com/airbnb/android/lottie/3.7.1-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/com/airbnb/android/lottie/3.7.1-SNAPSHOT/lottie-3.7.1-SNAPSHOT.pom
     Required by:
         project :app
   > Could not find com.airbnb.android:lottie:3.7.1-SNAPSHOT.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/airbnb/android/lottie/3.7.1-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/airbnb/android/lottie/3.7.1-SNAPSHOT/lottie-3.7.1-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/airbnb/android/lottie/3.7.1-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/airbnb/android/lottie/3.7.1-SNAPSHOT/lottie-3.7.1-SNAPSHOT.pom
       - https://jcenter.bintray.com/com/airbnb/android/lottie/3.7.1-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/com/airbnb/android/lottie/3.7.1-SNAPSHOT/lottie-3.7.1-SNAPSHOT.pom
     Required by:
         project :app > com.airbnb.android:lottie-compose:1.0.0-beta07-1

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
 - 
**Steps To Reproduce**

1 - Create jetpack compose project using beta07.
2 - Add latest lottie dependency
3 - Run app - it will crash at compile time

**Comment by gpeal** [comment]
It [does exist](https://oss.sonatype.org/content/repositories/snapshots/com/airbnb/android/lottie/3.7.1-SNAPSHOT/).

Make sure you have the snapshot repository in your root `build.gradle` file
`https://oss.sonatype.org/content/repositories/snapshots`

**Comment by kyhule** [comment]
I just ran into this issue. I understand the fix for it but why does targeting `com.airbnb.android:lottie-compose:1.0.0-beta07-1` in maven central require to add the sonatype repository? This is the first time I've seen a "stable" artifact having a dependency on snapshots. If this is truly the case, maybe the docs could be clearer since the separation of stable vs snapshot versions is misleading since stable depends on snapshots.

**Comment by brett-eugenelabs** [comment]
I am also getting this issue (same errors as above) in Android Studio Canary using Jetpack Compose.

build.gradle.kts: (Project)
```
buildscript {
    ext {
        compose_version = "1.1.0-alpha01"
        ext.kotlin_version = "1.5.10"
    }
    repositories {
        google()
        mavenCentral()
        maven {
            url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
        }
    }
    ...
```

build.gradle.kts (Module):
```
dependencies {
...
    implementation("com.airbnb.android:lottie-compose:1.0.0-beta07-1")
...
}
```

settings.gradle.kts:
```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
        }
        jcenter() // Warning: this repository is going to shut down soon
    }
}
rootProject.name = "MyApp"
include(":app")
```

Any help would be appreciate.

**Comment by gpeal** [comment]
You want to use 4.0.0

**Comment by brett-eugenelabs** [comment]
Thank you, works perfectly. Am new to Android Studio, Compose, and gradle, but am now getting the hang of the versioning.
