### ISSUE TITLE
fetchBitmap error

### ISSUE THREAD

**Issue by zhengshiteng** [airbnb/lottie-android#1819]
Two LottieAnimationView use one animJson, but ImageAssetDelegate only call by the fisrt one

**Comment by gpeal** [comment]
Lottie caches bitmaps internally. You can clear the cache by calling LottieDrawable.updateBitmap with the id passed to your image asset delegate. If you want two animations to have different bitmaps, use LottieCompositionFactory and create different cache keys for each one or else they will share the same underlying composition and bitmap cache.
