### ISSUE TITLE
Artifacting when using strokes on bezier paths in a shape layer in AE

### ISSUE THREAD

**Issue by sureMOE** [airbnb/lottie-android#182]
So I seem to have finally isolated a weird drawing bug on Android with Lottie and using strokes on paths. If you draw a bezier path in AE and you have some points in the path that have no bezier handles mixed in with points that do have handles, you get a weird draw glitch that I can't fully
 wrap my head around. The only way I know of getting rid of it is giving that point handles, even if they are really small. Pic included below.

![screenshot_20170306-184604](https://cloud.githubusercontent.com/assets/18271665/23679528/1f72e956-033d-11e7-930c-c1eb315244b4.png)

**Comment by sureMOE** [comment]
I can send more examples if needed, thanks!

**Comment by gpeal** [comment]
@sureMOE can you attach an After Effects file that repros this?

**Comment by gpeal** [comment]
@sureMOE bump. I made a path with a vertex without control points and it rendered correctly.

**Comment by sureMOE** [comment]
@gpeal Sorry Gabe! Been busy with some vacation time! :) So, it took me a long time to nail down this one and I kept getting inconsistent behavior so I was trying to figure out what it was. Because I was retrofitting an animation done by someone else, I was copying their masks and dropping them into paths on shape layers in After Effects. A couple things I noticed. If you are using a bezier path and you have some paths with handles and some without, it caused issues like this. Also, if you make a line and you have one handle on a point that's really long and the other point has no handle, it causes a lot of issues. I am going to see if I can develop a AE file that purposely makes these glitches. It took me quite a while to work them out, so hopefully I can undo some of my handy work! Will try and get something back to you today.

**Comment by sureMOE** [comment]
@gpeal Okay man, I got a file for you here. Let me know if you need any more insight.

Notice the lines in either corner and then watch the end of the 3 lines that are stacked on the right, it shows the artifacting issues. 

Thanks for all the hard work! This library has been a life saver and it's the first time in years I have been excited about doing animation for UX! This makes it so much easier. 

[Broken_icon_animation.aep.zip](https://github.com/airbnb/lottie-android/files/834854/Broken_icon_animation.aep.zip)

**Comment by gpeal** [comment]
@sureMOE Thanks for the file. I can see the artifact and I'll look in to it! Thanks for the report and glad you like Lottie!

**Comment by gpeal** [comment]
@sureMOE I just took another look at this for the 2.0 release I'm planning for this week and I'm actually not seeing it anymore. This is what it looks like for me now.
Also, would you like me to bundle this with the sample animations for the Lottie sample app?
![radio](https://cloud.githubusercontent.com/assets/1307745/23829563/f6f9a4b8-06a9-11e7-9db6-4c6408a460d3.gif)

**Comment by gpeal** [comment]
![image](https://cloud.githubusercontent.com/assets/1307745/23829567/1f33314c-06aa-11e7-9599-1ab484bd3c3c.png)

**Comment by sureMOE** [comment]
@gpeal Wow, that's awesome Gabe, looks great now! Good to see it fixed for sure. Thanks for this!

Also, if you want to use it as a sample animation, I would be fine with that. I could send you a better one with a fancy spider animation that really shows off the robustness of all of this. Let me know!

**Comment by gpeal** [comment]
Sure! Just send me the one you want to use.

**Comment by sureMOE** [comment]
Here you go:

[Spider_loader.json.zip](https://github.com/airbnb/lottie-android/files/839502/Spider_loader.json.zip)

Thanks!

**Comment by gpeal** [comment]
@sureMOE Sweet, thanks! Feel free to upload animations to lottiefiles.com too. I'll periodically pick animations from it for the sample app too.
