### ISSUE TITLE
com.airbnb.lottie.network.NetworkFetcher.getResultFromConnection

### ISSUE THREAD

**Issue by salilchhabra** [airbnb/lottie-android#1821]
This crash occurred while I try to set json coming from response using this method
animationView.setAnimationFromUrl(icon)
animationView.playAnimation()

Stack trace:

Caused by java.io.FileNotFoundException
/data/user/0/com.EmasDigi/cache/lottie_network_cache/lottie_cache_httpsmobileappproductions3apsoutheast1amazonawscomgifspluang_cuan_onboarding_card1json.temp.json (No such file or directory)
java.io.FileInputStream.open (FileInputStream.java)
java.io.FileInputStream.<init> (FileInputStream.java:146)
com.airbnb.lottie.network.NetworkFetcher.getResultFromConnection (NetworkFetcher.java:167)
com.airbnb.lottie.network.NetworkFetcher.fetchFromNetworkInternal (NetworkFetcher.java:108)
com.airbnb.lottie.network.NetworkFetcher.fetchFromNetwork (NetworkFetcher.java:86)
com.airbnb.lottie.network.NetworkFetcher.fetchSync (NetworkFetcher.java:52)
com.airbnb.lottie.network.NetworkFetcher.fetchSync (NetworkFetcher.java:31)
com.airbnb.lottie.LottieCompositionFactory$1.call (LottieCompositionFactory.java:91)
com.airbnb.lottie.LottieCompositionFactory$1.call (LottieCompositionFactory.java:88)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:761)

**Comment by gpeal** [comment]
The code in your stack trace has changed significantly in the latest version of Lottie. Please try again with the latest version.
