### ISSUE TITLE
Why lottie cannot support zip

### ISSUE THREAD

**Issue by chanchangxing** [airbnb/lottie-android#1823]
I found that lottie support zip with json and image, Why lottie cannot support zip with json but not image？It can reduce apk size i think

**Comment by gpeal** [comment]
@chanchangxing I'm not sure I understand the question

**Comment by ArtemMikhaylov** [comment]
From the docs it is not obvious how to use json animations from local zip file, or if it is possible at all. In "Loading an animation" section we can see such an option, but it references to Images section. But I have animations with only json files, is it possible to use them from zip file in assets?

**Comment by ArtemMikhaylov** [comment]
Found how to do it, in case someone will be here to get answer for the same question:

in xml in LottieAnimationView just add app:lottie_fileName attribute, and set name of your zip in assets (at least one zip for one json animation works for me)
