### ISSUE TITLE
Cannot access class 'com.airbnb.lottie.ImageAssetDelegate'. Check your module classpath for missing or conflicting dependencies

### ISSUE THREAD

**Issue by tobiraak** [airbnb/lottie-android#1824]
When trying to implement Lottie into my Jetpack Compose project, I can't set the LottieAnimationState because it can't access dependencies.  Is this a known bug or is there something that I am missing? I am using this version: 
com.airbnb.android:lottie-compose:1.0.0-beta07-1

**Comment by gpeal** [comment]
@tobiraak Please attach a sample project that reproduces this.

**Comment by kuramu1108** [comment]
@tobiraak I believe this is due to that `com.airbnb.android:lottie-compose:1.0.0-beta07-1` is using `com.airbnb.android:lottie:3.7.1-SNAPSHOT` and you have to add it as dependency explicitly
