### ISSUE TITLE
Disabling animation clipping

### ISSUE THREAD

**Issue by Pavel87** [airbnb/lottie-android#1825]
Hi team, 

we have an animation which seems to be clipping at the top for some images. I wonder how we can disable clipping and draw out of the rectangle. 

My IOS peer is using `animationView.clipsToBounds = false` which does work pretty well but I am struggling with the clipping in android.

I have tried `android:scaleType="centerInside"` and  `android:scaleType="centerCrop"` on lottieAnimationView and for parent ConstraintLayout:
`android:clipChildren="false"`
`android:clipToPadding="false"`

Is there way how I can avoid the clipping and render out of bounds?

**Screenshots**
![Screen Shot 2021-06-16 at 1 34 44 PM](https://user-images.githubusercontent.com/5558923/122289558-b5ce7980-cea7-11eb-8a19-d400bdba0635.png)
![Screen Shot 2021-06-16 at 1 34 20 PM](https://user-images.githubusercontent.com/5558923/122289564-b6671000-cea7-11eb-996f-3da6d53c2247.png)

**Comment by Pavel87** [comment]
@gpeal any advise on this?

**Comment by Pavel87** [comment]
@gpeal could you please provide any help with this ticket?

**Comment by CherryLover** [comment]
I have same problem. Does any help to fix?

**Comment by Pavel87** [comment]
Still looking for any kind of advice on how to make the animation draw out of bounds. It seems it is getting clipped by bounds defined in JSON and using any of the XML clip parameters does not work.

**Comment by gpeal** [comment]
@Pavel87 It wasn't really feasible until https://github.com/airbnb/lottie-android/pull/1952 landed. With this change, when using hardware acceleration, it might be more feasible.

**Comment by Pavel87** [comment]
I see, it would be greatly appreciated if you could somehow put it on your radar.

**Comment by gpeal** [comment]
Will do!
