### ISSUE TITLE
TextDelegate signature does not match its javadoc 

### ISSUE THREAD

**Issue by menjoo** [airbnb/lottie-android#1828]
**Describe the bug**

**Steps To Reproduce**

1. With Lottie 3.7.0
2. Read javadoc of `TextDelegate`. It states "The only method you should have to override is {@link #getText(String)}."
3. But this method is private and cannot be overriden.

Can `TextDelegate.getText(..)` become public?

**Comment by gpeal** [comment]
[It is public](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/TextDelegate.java#L48)
You can see it used in a test [here](https://github.com/airbnb/lottie-android/blob/master/sample/src/androidTest/java/com/airbnb/lottie/samples/LottieTest.kt#L865)
