### ISSUE TITLE
Android lottie player doesn't allow you to refresh Drive from within the app

### ISSUE THREAD

**Issue by sureMOE** [airbnb/lottie-android#183]
When I export to Drive and try to load it into the Lottie player, it doesn't show the file has updated or the file won't appear if it's a new file. The way I have worked around this is by opening the Drive app, refreshing the folder and then opening the file in the Lottie player. Just wondering if we could get a refresh action in the Drive folders in the Lottie player.

**Comment by gpeal** [comment]
@sureMOE Sorry but that's handled entirely by Drive. All the sample app does is send an intent to launch the bundled file choose which then, itself, delegates to Drive.
