### ISSUE TITLE
How to freeze the last frame in animation after it's done playing?

### ISSUE THREAD

**Issue by rekhagopi18** [airbnb/lottie-android#1833]

**Comment by gpeal** [comment]
@rekhagopi18 Lottie continues to render the last frame when it's done. I'm not sure I understand the question.

**Comment by rekhagopi18** [comment]
@gpeal  Thank you for your response.  We do have a requirement where the animation that was playing through lottie must be stopped/Paused at the last frame similar to the issue mentioned in this https://github.com/airbnb/lottie-web/issues/847 for web.

**Comment by gpeal** [comment]
I'm still not sure what the exact issue is. Can you elaborate?

**Comment by rekhagopi18** [comment]
We were using Lottie animation view to load animation in android 

 <com.airbnb.lottie.LottieAnimationView
            android:id="@+id/ob_start_screen_illustration"
            style="@style/AppJourneyCardIllustration"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:background="?attr/background_secondary"
            app:lottie_rawRes="@raw/welcome"
            app:lottie_loop="true"
            app:lottie_autoPlay="true"
            android:importantForAccessibility="no"
            app:layout_constraintBottom_toTopOf="@+id/guideline_center_vertical"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            tools:srcCompat="@drawable/ic_fte_screen1_illustration"/>

setting **app:lottie_loop to true** caused the app to crash with A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x50 in tid 27557 (RenderThread), pid 18166. 

The app was not crashing with **app:lottie_loop to false** but the animation provided by the designer had the start frame and end frame to be an empty frame. So the designer asked us that if we can pause the animation at the last frame.

**Today with more research** adding the **app:lottie_renderMode="software"** resolved the issue of the crash with **app:lottie_loop="true"**  I got the inforamtion from this issue https://github.com/airbnb/lottie-android/issues/1453. Is this a valid fix.

    const val lottieVersion = "3.7.0"
    Device : Samsung S10+
 Android version: 11

**Comment by gpeal** [comment]
@rekhagopi18 Can you attach the animation that was crashing? Was it crashing 100% of the time?

**Comment by rekhagopi18** [comment]
Thank you for your response. Yes, it was crashing 100% of the time. 
[success.json.zip](https://github.com/airbnb/lottie-android/files/6798450/success.json.zip)

**Comment by gpeal** [comment]
I believe most of these native crash issues will be resolved by https://github.com/airbnb/lottie-android/pull/1952. Let's close this for now and reopen it if it reproduces on 5+
