### ISSUE TITLE
NoSuchMethodError setImageAssetManager on LottieDrawable

### ISSUE THREAD

**Issue by MovementSpeed** [airbnb/lottie-android#1837]
**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Describe the bug**
Using @Composable LottieAnimation leads to a crash:
`java.lang.NoSuchMethodError: No virtual method setImageAssetManager(Lcom/airbnb/lottie/manager/ImageAssetManager;)V in class Lcom/airbnb/lottie/LottieDrawable; or its super classes (declaration of 'com.airbnb.lottie.LottieDrawable' appears in /data/app/~~rC9ACFpKIQB3QFZSSWzMHA==/app.package-KUTAny4ZZcykm71TfCtL4w==/base.apk)
        at com.airbnb.lottie.ImageAssetDelegateSetterKt.setImageAssetManager(ImageAssetDelegateSetter.kt:10)
        at com.airbnb.lottie.compose.LottieAnimationKt$LottieAnimation$3.invoke(LottieAnimation.kt:120)
        at com.airbnb.lottie.compose.LottieAnimationKt$LottieAnimation$3.invoke(LottieAnimation.kt:106)`

Because LottieDrawable does not have the method setImageAssetManager, and ImageAssetDelegateSetter tries to call this method on LottieDrawable, but instead it's just recursive, as showed by the IDE.

**What version of Lottie did you test this on?**
lottie-android 3.7.1-SNAPSHOT and 3.7.0
lottie-compose 1.0.0-beta09-1-SNAPSHOT and 1.0.0-beta07-1

**What version of Android did you test this on?**
Android 12 on Pixel 4a

**Steps To Reproduce**

1. have a @Composable function
2. use LottieAnimation @Composable, passing LottieComposition and progress taken from animateLottieCompositionAsState
3. LottieCompositionSpec is RawRes
4. run, it crashes with NoSuchMethodError when rendering

**Comment by headsvk** [comment]
You beat me to it by 4 minutes 😄 https://github.com/airbnb/lottie-android/issues/1838 I also forked the repo to reproduce the issue.

**Comment by WildOrangutan** [comment]
Did you find any workarounds?

**Comment by gpeal** [comment]
Can you try with `rc01-1-SNAPSHOT`? That API is no longer used since https://github.com/airbnb/lottie-android/pull/1836

**Comment by gpeal** [comment]
The deploy is green now. Can you try again?
https://github.com/airbnb/lottie-android/runs/3002160816?check_suite_focus=true

**Comment by headsvk** [comment]
Nice one @gpeal rc01 doesn't crash anymore. However, the stable beta07 linked in the readme crashes. Maybe it should link to the snapshot instead so that people don't use it.

**Comment by MovementSpeed** [comment]
@gpeal `rc01-1-SNAPSHOT` works fine, thanks

**Comment by gpeal** [comment]
@headsvk Yeah, I'll push a release soon. It's been tricky because I'm in the middle of a major API refactor (mostly complete) but wanted to build out a large set of functionality before releasing but it's in pretty good shape now.
