### ISSUE TITLE
How to manually play animation again when returned from back stack

### ISSUE THREAD

**Issue by darek607** [airbnb/lottie-android#1841]
Thanks for this library!

I encountered a strange bug and spent quite much time to ivestigate the issue. I wanted to play animation manually every time fragment view is loaded (`onViewCreated`).

Steps:
1) Inside onViewCreated of Fragment A, set progress to 0 and call `playAnimation`
2) Navigate to Fragment B with back stack entry and press back in order to return to the A

Expected result:
The animation should play again.

Result: The animation usually don't animate again after navigating back to fragment A. It shows a fully loaded anim immediately.

Tested on 3.7.1 and 3.2.2 versions.

**Comment by darek607** [comment]
It seems that lottie view is saving state incorrectly. The issue is gone after adding
`android:saveEnabled="false"` for the LottieAnimationView.

Previously I though that adding `addLottieOnCompositionLoadedListener` solves the issue, but it solves it only partially - the bug still sometimes happened (in about 1 per 10 Fragment loads).

**Comment by gpeal** [comment]
@darek607 Can you attach a sample project that reproduces this?

**Comment by darek607** [comment]
@gpeal I've created a basic sample demonstrating the issue: https://github.com/darek607/Lottie-Android-Bug 

1. Run the app (animation should play successfully)
2. Click NEXT button to launch another fragment
3. Go back to animation fragment (anim won't play again, but it should)
