### ISSUE TITLE
Inconsistent behaviour between iOS and Android for the same animation  

### ISSUE THREAD

**Issue by alexmx** [airbnb/lottie-android#185]
Hi there. 
My team experiences different behaviour for iOS and Android versions of the library, for the same exported animation.

Please find the animation JSON attached. 
[activity-indicator-animation-dark.json.zip](https://github.com/airbnb/lottie-android/files/833520/activity-indicator-animation-dark.json.zip)

Some screenshots:

iOS 100x100p | iOS 200x200p | Android 240x240dp | Android 480x480dp
------------ | ------------- | ------------- | ------------- 
![iOS](https://cloud.githubusercontent.com/assets/1628901/23790572/9df3915e-0577-11e7-92f5-570e62ed9434.png) | ![img_0993](https://cloud.githubusercontent.com/assets/1628901/23791223/18f6a574-057a-11e7-946b-dd6f1e9498b8.PNG) | ![device-2017-03-10-111316](https://cloud.githubusercontent.com/assets/1628901/23791022/60d9bd1e-0579-11e7-9b17-964ac4b4ee41.png) | ![device-2017-03-10-112629](https://cloud.githubusercontent.com/assets/1628901/23791024/62cc954c-0579-11e7-8c25-82088e323fc8.png)

It seems that stroke width on Android is too bold. iOS behaviour with respect to scaling seems more correct to me.

Thanks.
Alex.

**Comment by gpeal** [comment]
@alexmx I'll be releasing a significant Lottie update next week. This is what your animation looks like with it. Does it seem correct to you?
![recording](https://cloud.githubusercontent.com/assets/1307745/23805195/c2e46214-0571-11e7-8b4c-6b3ac7bf5a40.gif)

**Comment by alexmx** [comment]
@gpeal Yeah, looks awesome. Thanks. Looking forward to try out this new release.
