### ISSUE TITLE
When insert my json file in LottieAnimationView a “error null object reference” occurred (Android)

### ISSUE THREAD

**Issue by nicolettinzia** [airbnb/lottie-android#186]
I guys, i have a problem with this library. I try to insert my personal animation.json in my file project and this is what happened:

http://stackoverflow.com/q/42716105/4360290

**Comment by gpeal** [comment]
@nicolettinzia Can you attach your After Effects file or email it to us at lottie@airbnb.com?

**Comment by gpeal** [comment]
@nicolettinzia any update?

**Comment by gpeal** [comment]
@nicolettinzia feel free to reopen this if you're still having the issue.
