### ISSUE TITLE
Color filter for composables

### ISSUE THREAD

**Issue by randrievskiy** [airbnb/lottie-android#1862]
I cannot apply color filter to whole animation in jetpack compose.
Following code is working nice for the view system.

`addValueCallback(
            KeyPath("**"),
            LottieProperty.COLOR_FILTER,
            { PorterDuffColorFilter(buttonView.currentTextColor, PorterDuff.Mode.SRC_ATOP) }
        )` 

And no luck with the compose. What am I doing wrong?

` val dynamicProperties = rememberLottieDynamicProperties(
        rememberLottieDynamicProperty(
            keyPath = arrayOf("**"),
            property = LottieProperty.COLOR_FILTER,
            callback = {
                PorterDuffColorFilter(color.toArgb(), PorterDuff.Mode.SRC_ATOP)
            }
        )
    )
    LottieAnimation(
        composition = composition,
        iterations = LottieConstants.IterateForever,
        dynamicProperties = dynamicProperties
    )`

**Comment by sergenes** [comment]
Hey @randrievskiy, do you have comments on this issue?

**Comment by sergenes** [comment]
Never mind! I found it works with the `LottieProperty.COLOR` not with the `LottieProperty.COLOR_FILTER`!
