### ISSUE TITLE
Compose runs twice with Lottie-Compose

### ISSUE THREAD

**Issue by josecardoso89** [airbnb/lottie-android#1869]
Hi there,

I'm using lottie-compose latest version (4.0.0) and when I try to run a simple LottieAnimation the Composable always runs twice (runs once and then immediatly after it gets recomposed). Do you know if that's a bug?

`@Composable
fun LoadingScreen() {
    Log.i(TAG, "LoadingScreen")
    val animationSpec = remember { LottieAnimationSpec.RawRes(R.raw.loader) }
    LottieAnimation(
        animationSpec,
        modifier = Modifier.width(56.dp)
    )
}` 

Checking the logs, the LoadingScreen always appears twice.

**Comment by gpeal** [comment]
Do you mean the logcat log runs twice? It's hard to tell because the code you posted isn't value. Lottie 4.0 doesn't have any versions of `LottieAnimation` that take a `LottieCompositionSpec` directly. Also, you don't need to `remember` it because it's an inline class.

**Comment by josecardoso89** [comment]
What I mean is that LoadingScreen composable is called twice and it shouldn't since no value was changed that caused the recomposition of it. And what do you mean with 

> Lottie 4.0 doesn't have any versions of LottieAnimation that take a LottieCompositionSpec directly

You don't have LottieAnimationSpec anymore even though in your documentation it uses it. What should I use then?

Also, I refactored the code to this:

`Log.i(TAG, "LoadingScreen")
    val composition1 by rememberLottieComposition(LottieCompositionSpec.RawRes(R.raw.loader))
    LottieAnimation(
        composition1,
        iterations = IterateForever,
        modifier = Modifier.width(56.dp)
    )`
    
    And it stills calls LoadingScreen twice...

**Comment by gpeal** [comment]
Probably because the composition state is null before parsing and then not null after. This seems expected to me.

**Comment by josecardoso89** [comment]
Hmm, is there any way to prevent that? Because if I assign a viewModel to that loading screen (doing an operation while I show the loading) and it gets recomposed, the viewModel will also be disposed and a new instance will be assigned wasting resources.

**Comment by gpeal** [comment]
@josecardoso89 No it won't, recomposition is designed to happen all the time and should have no effect on object recreation either via `remember` or using something like the `by viewModels()` delegate which will store and retrieve the ViewModel from `LocalViewModelStore.current`.
