### ISSUE TITLE
Animation does not load

### ISSUE THREAD

**Issue by MrIceman** [airbnb/lottie-android#187]
Hi,
I created a simple animation with After Effects CC17 and used bodymovin to get the .json.
When I tried to use that .json file with the lottie-android library it does not load the .json file I put into my assets folder,
do you have any tips? 

[comp.zip](https://github.com/airbnb/lottie-android/files/833696/comp.zip)

```

`    <com.airbnb.lottie.LottieAnimationView
        android:id="@+id/animation_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:lottie_fileName="data.json"
        app:lottie_loop="true"
        app:lottie_autoPlay="true" />
`
```

from my XML view

**Comment by gpeal** [comment]
Unfortunately Lottie doesn't support text (yet). You can track its progress in #173
