### ISSUE TITLE
Frame struggling

### ISSUE THREAD

**Issue by barbozabarb** [airbnb/lottie-android#1870]
Hi i am looking for a function to allows me to know the amout of total frame of the animation, 

I use 
 val animation :LottieAnimationView= findViewById<LottieAnimationView>(R.id.imageTest)

and then tried

animation.totalFrame()

or 

animation.startFrame() or animation.endFrame()

but those functions are not avaible for LottieAnimationView.

I cant figure out how to solve this

Also, is there any way  to make the animation render at an specified frame? i want to make that the animation plays accord to an object position.

Thanks !

**Comment by gpeal** [comment]
These functions are on LottieComposition, not LottieAnimationView. And yes, you can call [setFrame](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L1022)

**Comment by barbozabarb** [comment]
Thank you Gabriel, i am reviewing the documentation and, the issues thread but i cannot find how to load a json to the LottieComposition, i tried to do
       val composition: LottieComposition =LottieCompositionFactory.fromRawRes(this,"percentage.json")

but then it line becomes
       val composition: LottieTask<LottieComposition> =LottieCompositionFactory.fromRawRes(this,"porcentaje.json")

and i can't do much, becuase the val now is a LottieTask

**Comment by gpeal** [comment]
@barbozabarb Use `LottieCompositionSpec.Asset` as outlined [here](http://airbnb.io/lottie/#/android-compose?id=lottiecomposition)

**Comment by barbozabarb** [comment]
Solved by going to
 Tools->Kotlin->Configure Kotlin Plugin Updates and updating

and then changing SDK version
