### ISSUE TITLE
LottieCompositionFactory.fromRawRes is not helping in Composable LottieAnimation 

### ISSUE THREAD

**Issue by atonamy** [airbnb/lottie-android#1880]
I have a  lag at the first time when animation loading on the screen (in android emulator is much more noticeable)
I tried to use 

```
 lifecycleScope.launch {
            withContext(Dispatchers.IO) {
               suspendCoroutine<Unit> { c ->
                    LottieCompositionFactory.fromRawRes(requireContext(), R.raw.lottie_animation).addListener {
                      c.resume(Unit)
                    }
                }
            }
       // Launch my fragment here where composable playing animation of R.raw.lottie_animation
}
```
In  a fragment composable widget responsible for lottie animation looks like this:
```
@Composable
fun lottie() {
   val composition by rememberLottieComposition(LottieCompositionSpec.RawRes(R.raw.lottie_animation))
   val progress by animateLottieCompositionAsState(composition,
                  clipSpec = LottieClipSpec.Progress(prgs.first, prgs.second)
          )
   LottieAnimation(modifier = Modifier.fillMaxWidth(), composition = composition, progress = progress)
}
```

But I still see the lag :( regardless I'm using LottieCompositionFactory.fromRawRes or not. Do you know why is not helping to preload lottie animation and eliminate first loading/initialisation animation lag?

The version I use 
4.1.0 (lottie-compose artifact)

**What version of Android did you test this on?**
Android 10 and 11

**Steps To Reproduce**
Just try code I described above use heavy lottie json to observe lag more clearly (especially if you try on Android emulator or old low performing Android phone)

**Comment by barbozabarb** [comment]
I tried to write the code you put 
@Composable
fun lottie() {
   val composition by rememberLottieComposition(LottieCompositionSpec.RawRes(R.raw.lottie_animation))
   val progress by animateLottieCompositionAsState(composition,
                  clipSpec = LottieClipSpec.Progress(prgs.first, prgs.second)
          )
   LottieAnimation(modifier = Modifier.fillMaxWidth(), composition = composition, progress = progress)
}

but got an error to this line 
val composition by rememberLottieComposition(LottieCompositionSpec.RawRes(R.raw.lottie_animation))
it says 
Create extension function "LottieCompositionResults.getValue" how do you solve it?
Also how much heavy is the animation and how much ram does the android phone have it?

**Comment by atonamy** [comment]
> .getValue

Make sure you you imported `getValue` from compose runtime
` import androidx.compose.runtime.getValue`
 
 try to play around with this two lottie animations
 [first one](https://lottiefiles.com/71308-artificial-intelligence-lottie-animation) and 
 [second](https://lottiefiles.com/66653-cool-stare) 
 Show this animations at the same time and sequentially  
 put `CircularProgressIndicator() `in the screen as well to see the lag while lottie animation preloading for the first time
 Use Android emulator instead  with Android version 11 (SDK30)

**Comment by gpeal** [comment]
The above answer is correct and currently, Android Studio doesn't do a great job with importing Compose state delegate imports by default but that's a general Android Studio/Compose issue and has nothing to do with Lottie.

**Comment by atonamy** [comment]
> The above answer is correct and currently, Android Studio doesn't do a great job with importing Compose state delegate imports by default but that's a general Android Studio/Compose issue and has nothing to do with Lottie.

So what is workaround about lag I have experience on the first LottieAnimation and LottieCompositionSpec render initialisation?
