### ISSUE TITLE
Duplicate class error in jetpack compose project

### ISSUE THREAD

**Issue by o2e** [airbnb/lottie-android#1881]
**Describe the bug**
I am only using jetpack compose to develop my project. When I import lottie and run the project I get a lot of Duplicate class errors, I think this error may be caused by the fact that the appcompat version built into lottie is too old (only 1.0.0) and that my project does not use the appcompat dependency library. I have improved the problem by excluding appcompat from lottie via gradle exclude, but I don't know if this is causing unknown errors.

I now have a doubt that when I use compose to develop a project, appcompat may not be used and it will increase the size of the apk. Do we have a clean lottie dependency library?

```
Duplicate class androidx.appcompat.content.res.AppCompatResources found in modules appcompat-1.0.0-runtime (androidx.appcompat:appcompat:1.0.0) and jetified-appcompat-resources-1.3.1-runtime (androidx.appcompat:appcompat-resources:1.3.1)
```

![image](https://user-images.githubusercontent.com/24642961/131258388-d04488ef-092d-4cf3-95a1-22258f29ff6a.png)
![image](https://user-images.githubusercontent.com/24642961/131258395-b018c0a1-05fd-4300-a463-cef0233f7c52.png)
![image](https://user-images.githubusercontent.com/24642961/131258416-e22bda00-84cc-4393-81a6-fba069c09da3.png)

**Comment by gpeal** [comment]
@o2e Can you attach a sample project that reproduces this?

**Comment by o2e** [comment]
> @o2e Can you attach a sample project that reproduces this?

https://github.com/o2e/errorTest

I'm very sorry for submitting the error feedback to you without rigorous testing. when creating the demo, I found ```(coil + lottie) - appcompat = Duplicate class error```. because ```coil``` built-in ```androidx.appcompat:appcompat- resources:1.3.1``` and ```lottie``` ```appcompat``` are causing the problem, and as a simple ```compose``` project I probably can't accept the existence of ```appcompat``` because it's too big and useless. So should I ```exclude``` ```appcompat``` from ```lottie``` or wait for ```lottie``` to provide a ```compose``` version without ```appcompat```?

**Comment by o2e** [comment]
Android Studio Arctic Fox | 2020.3.1 Patch 1
内部版本号 #AI-203.7717.56.2031.7621141，August 8, 2021 构建
运行时版本: 11.0.10+0-b96-7281165 x86_64
VM: OpenJDK 64-Bit Server VM，JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: Gradle View, com.dengzii.plugin.adb, com.intellij.zh, com.thoughtworks.gauge, cn.yiiguxing.plugin.translate, org.intellij.plugins.markdown

**Comment by o2e** [comment]
I've had a brief look at the lottie codebase and I see that the project only uses the sub library ``appcompat-resource`` from appcompat and an ```AppCompatImageView ```. I think you can just import ```androidx.appcompat:appcompat-resources:1.3.1``` in the project, you don't need to import a huge appcompat library. But you may need to change the ```AppCompatImageView``` inside the  [LottieAnimationView](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java) to an ```ImageView```.

**Comment by gpeal** [comment]
@o2e Nearly 100% of Android apps should already have appcompat so adding it as a dependency shouldn't be an issue. People also use LottieAnimationViews as normal ImageViews sometimes and changing this to a normal ImageView could break many apps in subtle ways.

I was able to reproduce the duplicate class error and found that it no longer reproduces after we upgraded the dependencies [here](https://github.com/airbnb/lottie-android/commit/677430275580cb2ff8cea07bf082f74a38849a5e). I'm about to publish a new release so you can use that or the latest SNAPSHOT.

**Comment by o2e** [comment]
@gpeal   I understand. For a pure compose project, is there any adverse consequence of excluding appcompat if I don't use LottieAnimationView? I haven't found any problems for now when I tested using it.
