### ISSUE TITLE
Allow synchronised loading of animations for tests

### ISSUE THREAD

**Issue by crysxd** [airbnb/lottie-android#1883]
**Is your feature request related to a problem? Please describe.**
We use Screenshot tests for all our custom views. We recently started using LottiAnimationView in some of our custom views. In the screenshot tests the animations are not visible and the animation size is not reflected in the layout.

**Describe the solution you'd like**
Similar to when `isInEditMode()`, we'd need to have the first frame of the animation rendered right away. This could either be achieved by a (static?) flag like `loadAnimationsAsync=false` or linked to the global animation scale as described below. 

**Describe alternatives you've considered**
We work around this issue with a extension function:

```
fun LottieAnimationView.setAnimationWithTestCompatibility(@RawRes res: Int) {
    if (AnimationTestUtils.animationsDisabled) {
        setComposition(
            LottieCompositionFactory.fromRawResSync(
                context,
                res
            ).value!!
        )
    } else {
        setAnimation(res)
    }
}
```

`AnimationTestUtils.animationsDisabled` is linked to the developer settings for the animation scale:

```
object AnimationTestUtils {

    val globalAnimationScale
        get() = Settings.Global.getFloat(
            CommonInjector.get().context().contentResolver,
            Settings.Global.ANIMATOR_DURATION_SCALE,
            1.0f
        )

    val animationsDisabled
        get() = globalAnimationScale == 0f
}
```

**Additional context**
This would also be beneficial if animations are disabled for accessibility reasons. The first frame is still shown preserving the overall look of the app while honouring the users preference for no animations.

**Comment by gpeal** [comment]
@crysxd You can add an `LottieOnCompositionLoadedListener` and suspend your tests until it returns.

**Comment by gpeal** [comment]
I'm going to close this for now per my previous comment.
