### ISSUE TITLE
Wrong parameter in Lottie-Compose docs (LottieAnimationSpec)

### ISSUE THREAD

**Issue by kypeli** [airbnb/lottie-android#1887]
The Lottie-Compose "Basic usage" instructions here http://airbnb.io/lottie/#/android-compose?id=basic-usage instructs to use LottieAnimationSpec to load the animation file. The correct parameter to use is LottieCompositionSpec.

**Comment by gpeal** [comment]
Already fixed there. You can put up PRs to the markdown at https://github.com/airbnb/lottie directly.
