### ISSUE TITLE
.setFrame its missing in LottieAnimationView and also lottieDrawable

### ISSUE THREAD

**Issue by barbozabarb** [airbnb/lottie-android#1898]
Hi, I am trying to use .setframe as @gpeal have told me but when I am trying to implement it, it does not appear only 

frame (from getFrame()/setFrame()) 
 ----->Get the currently rendered frame

I've tried 
 val lottieAnimation2 :LottieAnimationView= findViewById(R.id.anima)
      lottieAnimation2.setAnimation(R.raw.percentage)
      lottieAnimation2.setFrame....

I just want it to display in screen that certain frame buy I could not figure it how

**Comment by gpeal** [comment]
I'm not sure I understand. It is here
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L1022
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java#L784

**Comment by barbozabarb** [comment]
Maybe I explained myself wrong, Gabriel, what I mean is that i get this

 [https://imgur.com/a/RlBaFdY](url) 

"frame" is the only method available

**Comment by gpeal** [comment]
@barbozabarb That's just [Kotlin's Java interop](https://kotlinlang.org/docs/java-interop.html#getters-and-setters). Call `frame = ` from Kotlin and it'll do the same thing as calling `setFrame(...)` in Java.

**Comment by barbozabarb** [comment]
Thank you Gabriel, I've misunderstood the function and I though that the method could be frame(x)
