### ISSUE TITLE
Embedding or .json issue (Xamarin)?

### ISSUE THREAD

**Issue by hringstrom** [airbnb/lottie-android#1902]
Dear Lottie community,

I’m very impressed by the underlying technology behind .json and Lottie implementations, enabling smooth motions on even the oldest of smartphones. However, it seems my team has an integration or .json design issue. Please find how the animation and background should look when correct below (Currently on a Huawei P20 Pro and same on new phone models):

[https://ibb.co/bFZZ0Jp](https://ibb.co/VCb6RZk)

Please note the application is made in Xamarin, with Android native implementation on the splash screen using com.airbnb.lottie [One in the picture].

However, this is how it appears on OnePlus 3 (Android 8). Interferance in background and multiple copies of the animation (all in wrong places):

[https://ibb.co/rQ5dHFT](https://ibb.co/VCb6RZk)

This is how it appears on Infinix Note 9 (Android 9). Wrong color background, and multiple instances of the animation in the same place:

[https://ibb.co/9ZZdNhq](https://ibb.co/VCb6RZk)

Lastly, this is how it turns up in Samsung J4+ (Android 9). Wrong background color, else correct:

[https://ibb.co/VCb6RZk](https://ibb.co/VCb6RZk)

I would very much appreciate any suggestions of what why this could be, either due to design or embedding issues. Has anyone come across similar and do anyone have experience with Xamarin lottie integrations?

Thanks in advance,
Henrik

**Comment by hringstrom** [comment]
Just wanted to revert or "bump" the topic, as we still haven't been able to recognize the issue. Please do mention if anyone needs more information or the file itself to stipulate a potential response.

Kind Regards,
Henrik

**Comment by gpeal** [comment]
@hringstrom Hi there. Just FYI, I am the sole maintainer of this project on my nights and weekends. I can't get to all issues right away and prioritize issues from sponsors as a result. I will take a look at this but I can't promise exactly when.

**Comment by hringstrom** [comment]
@gpeal Thank you for your kind response.
Of course! Fully understand. 

Thanks for your dedication.

//Henrik

**Comment by gpeal** [comment]
@hringstrom I suggest trying 2 things:
1) Try calling `setRenderMode(RenderMode.Software)`
2) If that doesn't work, please attach a sample project that I can test with. It will be hard to debug this without one.
