### ISSUE TITLE
Jetpack Compose tests with Lottie & infinite animations

### ISSUE THREAD

**Issue by krzdabrowski** [airbnb/lottie-android#1907]
**Is your feature request related to a problem? Please describe.**
I have a `Composable` that will iterate continuously by using `LottieConstants.IterateForever`. I would like to be able to test it but as [Compose Testing codelab](https://developer.android.com/codelabs/jetpack-compose-testing#5) suggests, there might be a need for special animation API like `InfiniteTransition`:

```
In Compose, the animation APIs were designed with testability in mind, so the problem can be fixed by using the correct API. Instead of restarting the animateDpAsState animation, we can use infinite animations.

Infinite animations are a special case that Compose tests understand so they're not going to keep the test busy.
```

**Describe the solution you'd like**
To find a way (new API method in Lottie?) to test infinite Compose Lottie animations.

**Describe alternatives you've considered**
I haven't found a way to combine existing Lottie API along with InfiniteTransition API.

**Additional context**
When I'm using Lottie's standard API, I'm currently receiving same error message as defined in codelab linked above: `Idling resource timed out: possibly due to compose being busy.`

Any input would be appreciated.

**Comment by alorma** [comment]
I've found a way for this:

Create a

```
val LocalLottieIterations = compositionLocalOf { IterateForever }
```

And on test set it to *1*

**Comment by timusus** [comment]
Another possible solution is to just take control of the compose clock yourself:

```
composeTestRule.mainClock.autoAdvance = false
composeTestRule.mainClock.advanceTimeBy(1000)
```
