### ISSUE TITLE
Possible bug while loading via Java code

### ISSUE THREAD

**Issue by pensokha** [airbnb/lottie-android#191]
Dear All,

I have try sample to load via xml , are working fine but when load through code it does not work, here is my code

@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
 //       setContentView(R.layout.activity_main);

        Button myButton = new Button(this);
        myButton.setText("Press me");
        myButton.setBackgroundColor(Color.YELLOW);
        LottieAnimationView animationView = new LottieAnimationView(this);
        animationView.setAnimation("camera.json");
        animationView.loop(true);
        RelativeLayout myLayout = new RelativeLayout(this);
        myLayout.setBackgroundColor(Color.BLUE);
        myLayout.addView(animationView);
        myLayout.addView(myButton);
        setContentView(myLayout);

        setContentView(myLayout);

    }

Regards,

**Comment by pensokha** [comment]
need to call playAnimation to make it work 
animationView.playAnimation();

**Comment by AndroidDeveloperLB** [comment]
@pensokha Why is it needed to call `playAnimation` , even if the `lottie_autoPlay` is set to true?
