### ISSUE TITLE
support of full screen animation?

### ISSUE THREAD

**Issue by nick1Jian** [airbnb/lottie-android#192]
Is there a way to implement a splash animation(i.e. to match_parent )? 

I tried to use a full screen lottie player, but the issue is the json file do specify size and a fixed size won't fit on every devices.

**Comment by gpeal** [comment]
@nick1Jian Set your LottieAnimationView to match_parent and the scaleType to centerCrop. That should work.

**Comment by hendrawd** [comment]
can't it be stretched instead based on the screen width?

**Comment by bukenov** [comment]
How to play animation over status bar?
