### ISSUE TITLE
If it is an animation with images, it does not play until the last frame

### ISSUE THREAD

**Issue by wuwuhuai** [airbnb/lottie-android#1920]
If it is an animation with pictures, it does not play until the last frame

**Comment by wuwuhuai** [comment]
> @wuwuhuai Can you attach a sample project that reproduces this?

sure. this a my sample :https://github.com/wuwuhuai/LottieDemoMy/tree/master

**Comment by gpeal** [comment]
@wuwuhuai your project doesn't exist or isn't public
