### ISSUE TITLE
Start another activity After lottie  effect is Finish! 

### ISSUE THREAD

**Issue by Kayuemkhan** [airbnb/lottie-android#1922]
I used lottie Animations in ### SplashScreen. But, I want to **change the activity** when the lottie animations are finished !

**Comment by klaus19** [comment]
Why don't you use Intent to go to another activity?

**Comment by Kayuemkhan** [comment]
> Why don't you use Intent to go to another activity?

Yes. But, When I need to use the intent ! That was unknown to me. Thanks @gpeal !

**Comment by klaus19** [comment]
> 
> 
> Yes, use an intent with an [animator listener](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L798)

@gpeal One Shouldn't use Coroutines when displaying Lottie as a Splashscreen, it has high initialisation cost compared to Handler and Executor.
