### ISSUE TITLE
Star Shape inconsistencies

### ISSUE THREAD

**Issue by mbasaglia** [airbnb/lottie-android#1925]
**Describe the bug**
I was testing the star shape (`"ty": "sr"`) It looks like the angle is handled inconsistently across lottie players

**What version of Lottie did you test this on?**
5.5.7

**What version of Android did you test this on?**
I could reproduce on Telegram android, which uses lottie-android. Not sure if there's an easy way of testing lottie-android myself

**Steps To Reproduce**

1. Load the json from [star.zip](https://github.com/airbnb/lottie-android/files/7359522/star.zip) (zipped so I could attach it)
2. Check the stars, there's a blue star object and a black path behind it which should line up

**Screenshots**
This is how lottie web renders the provided json:

![Screenshot_20211017_105408](https://user-images.githubusercontent.com/2465791/137620570-7a63faec-1a41-4e2f-80e9-f42194786fab.png)

This is how lottie-android renders it:

![Screenshot_20211017_105454](https://user-images.githubusercontent.com/2465791/137620592-b153d0fa-edf3-4f9b-9c0d-9cacfdb9b9a7.png)

**Comment by gpeal** [comment]
I just tested your animation and this is how lottie-android renders it which looks correct.
![image](https://user-images.githubusercontent.com/1307745/140014046-52477421-5fc8-42b2-997b-6acb99df1f17.png)
