### ISSUE TITLE
LottieAnimationView with autoplay and loop=true consume memory when activity destroyed

### ISSUE THREAD

**Issue by FabioCappelliSpot** [airbnb/lottie-android#193]
Hi, I'm using "Lottie" library to make an animation in my app.

```
<com.airbnb.lottie.LottieAnimationView
        android:id="@+id/img_lottie"
        android:layout_width="100dp"
        android:layout_height="120dp"
        android:layout_centerInParent="true"
        app:lottie_autoPlay="true"
        app:lottie_fileName="file.json"
        app:lottie_loop="true"
        />

```

My activity is:

```
public class DemoLottieActivity extends Activity {

    private LottieAnimationView mImgTemp;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.demo_activity_lottie);
        mImgTemp =  (LottieAnimationView) findViewById(R.id.img_lottie);
    }


    @Override
    protected void onPause() {
        super.onPause();
        finish();
    }

    // @Override
    // public void onStop() {
    //     super.onStop();
    //     mImgTemp.cancelAnimation();
    // }

}
```

If I don't call cancelAnimation() on onStop methods I note in Android Monitor that memory consumption decreases slowly.  
I need call method cancelAnimation();. 

I notice that the LottieDrawable constructor registers animator.addUpdateListener() and if I don't cancel animation the listener remain alive.

I suggest to resolve it.

Thanks in advanced.

**Comment by gpeal** [comment]
@FabioCappelliSpot Can you attach a sample project that repros this?

**Comment by FabioCappelliSpot** [comment]
Thanks Gabriel.
I had no time for attach sample, but I saw the resolution. 
In the description I meant that the memory was increasing slowly, I was wrong.
