### ISSUE TITLE
Use Lottie with No Code on MIT Appinventor

### ISSUE THREAD

**Issue by ansh2166** [airbnb/lottie-android#1935]
MIT App Inventor is a web application integrated development environment originally provided by Google, and now maintained by the Massachusetts Institute of Technology and is used for Android Development.

https://community.appinventor.mit.edu/t/lottie-animations-add-cool-animations-to-your-apps/44483

![image](https://user-images.githubusercontent.com/72782632/139285403-76a732a7-7215-469b-b5ed-cdb9e6244079.png)
![image](https://user-images.githubusercontent.com/72782632/139285428-74e17350-bdb9-4200-9162-b0848856c326.png)
![image](https://user-images.githubusercontent.com/72782632/139285455-4126e6ef-b462-402f-bcb7-d69c6b6ec33a.png)
![image](https://user-images.githubusercontent.com/72782632/139285483-359fe141-53fa-4521-84e6-7daeea30aa42.png)

You may mention it in available Platforms, 

After this plugin, people can use lottie in their apps without coding, just visual Programming

# Output Video
https://user-images.githubusercontent.com/72782632/139287846-7777d71e-e488-4784-96e2-91b998423ad0.mp4

You may mention MIT Appinventor in available Platforms or readme :)

**Comment by gpeal** [comment]
The documentation is hosted at https://github.com/airbnb/lottie
Feel free to put up a PR there. All you have to do is propose a change to the markdown file 😄
