### ISSUE TITLE
Compose missing parameter imageAssetDelegate

### ISSUE THREAD

**Issue by rostopira** [airbnb/lottie-android#1941]
As per docs
```
Manually returned via an ImageAssetDelegate and set as the imageAssetDelegate parameter on your LottieAnimation composable.
```
However, LottieAnimation composable doesn't have such parameter.
I'm using version 4.2.0, but I've looked into master branch, it doesn't have this parameter as well

**Comment by gpeal** [comment]
With Lottie Compose, you use [dynamic properties](http://airbnb.io/lottie/#/android-compose?id=dynamic-properties) with `LottieProperty.BITMAP`
