### ISSUE TITLE
LottieAnimationView not animating image scaling effect in android, but working good on lotti files

### ISSUE THREAD

**Issue by developer5167** [airbnb/lottie-android#1944]
I'm working on android application where I can animate image using LottieAnimationView, So my problem is, image is not animating as shown [here ](https://lottiefiles.com/share/dumad4tv), I just downloaded the json file (animation.json) and gave as an input to LottieAnimationView but image is not animating on my android device , please help me where I'm going wrong.

tested on android 11 oneplus 7 pro

here is my layout:

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:app="http://schemas.android.com/apk/res-auto"
xmlns:tools="http://schemas.android.com/tools"
android:layout_width="match_parent"
android:layout_height="match_parent"
tools:context=".Splash">

<com.airbnb.lottie.LottieAnimationView
    android:id="@+id/lottie"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_centerInParent="true"
    app:lottie_autoPlay="true"
    app:lottie_loop="true"
    app:lottie_rawRes="@raw/animation" />

</RelativeLayout>


```
here is my [output ](https://i.stack.imgur.com/C7jhY.jpg), please help me to solve this problem, thanks in advance

**Comment by gpeal** [comment]
@developer5167 Try adding `android:scaleType="centerCrop"` 
Let me know if that works.
