### ISSUE TITLE
Lottie animation restart automatically

### ISSUE THREAD

**Issue by GirlLoveSunny** [airbnb/lottie-android#1946]
## Here is the log:
BannerView-------: startScaleShowAnim-**create** Animation
BannerView-------: startScaleShowAnim-onAnimation**Start**
BannerView-------: startScaleShowAnim-onAnimation**Cancel**
BannerView-------: startScaleShowAnim-onAnimation**Start**
BannerView-------: startScaleShowAnim-onAnimation**Cancel**
BannerView-------: startScaleShowAnim-onAnimation**Start**
BannerView-------: startScaleShowAnim-onAnimation**Cancel**
BannerView-------: startScaleShowAnim-onAnimation**Start**
BannerView-------: startScaleShowAnim-onAnimation**End**
BannerView-------: -----------------------------------

### Here is my code:
`
<com.airbnb.lottie.LottieAnimationView
        android:id="@+id/la_default"
        android:layout_width="@dimen/margin_69"
        android:layout_height="@dimen/margin_21"
        app:lottie_autoPlay="false"
        app:lottie_loop="false"
        app:lottie_renderMode="software" />`

`            mBaseContainer?.setOnPageChangeListener(object : ViewPager.OnPageChangeListener {
                var mCurrentPage = 0
                override fun onPageScrolled(position: Int, positionOffset: Float, positionOffsetPixels: Int) {
                    if (positionOffsetPixels > 10) {
                        (cells[mCurrentPage] as bannerCell).startScaleOutAnim()
                    }
                }

                override fun onPageSelected(position: Int) {
                    mCurrentPage = position
                }

                override fun onPageScrollStateChanged(state: Int) {
                    if (state == 0) {
                        (cells[mCurrentPage] as bannerCell).startScaleInAnim()
                    }
                }
            })
`

### Android kotlin
`    var isHide = true
    var isShowIng = false
    var isDisappearIng = false
    fun startScaleShowAnim() {
        if (isShowIng || !isHide) return
        isHide = false
        this.postDelayed({
            if (!la_default.isAnimating) {
                la_default.cancelAnimation()
                la_default.removeAllAnimatorListeners()
                la_default.setAnimation("current_car_font_show.zip")
                Log.v("BannerView-------", "startScaleShowAnim-create Animation")
                la_default.addAnimatorListener(object : Animator.AnimatorListener {
                    override fun onAnimationStart(animation: Animator?) {
                        Log.v("BannerView-------", "startScaleShowAnim-onAnimationStart")
                        isShowIng = true
                    }
                    override fun onAnimationCancel(animation: Animator?) {
                        Log.v("BannerView-------", "startScaleShowAnim-onAnimationCancel")
                        isShowIng = false
                    }
                    override fun onAnimationRepeat(animation: Animator?) {
                    }
                    override fun onAnimationEnd(animation: Animator?) {
                        Log.v("BannerView-------", "startScaleShowAnim-onAnimationEnd")
                        Log.v("BannerView-------", "-----------------------------------")
                        isShowIng = false
                    }
                })
                la_default.playAnimation()
            }
        }, 200)
    }`

**Comment by gpeal** [comment]
Can you provide a description of your problem?

**Comment by GirlLoveSunny** [comment]
I just want the animation which name is current_car_font_show.zip to be played only once when switching the banner,  so I set the value of lottie_loop to false, but when I run my project, the animation always plays many times, like the Log, the animation loop executes the onAnimationStart function and the onAnimationCancel function. If I replace the lottie animation with normal animation, the animation will be played only once.

**Comment by gpeal** [comment]
Please attach a sample project that reproduces this.

**Comment by gpeal** [comment]
Closing without a repro project.
