### ISSUE TITLE
AAPT: error: file failed to compile using com.airbnb.lottie.LottieAnimationView prop lottie_rawRes

### ISSUE THREAD

**Issue by Jonathansoufer** [airbnb/lottie-android#1949]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Describe the bug**
The bug occurs when trying to use com.airbnb.lottie.LottieAnimationView on layout/launch_screen.xml file. Tried to use different JSON file animations with no success. 

`<com.airbnb.lottie.LottieAnimationView
        android:id="@+id/animation_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:lottie_rawRes="@raw/swipe"
        app:lottie_loop="true"
        app:lottie_autoPlay="true" />`

**What version of Lottie did you test this on?**
4.2.1

**What version of Android did you test this on?**
compileSdkVersion: 30

**Steps To Reproduce**
Copy and past the snippet above using any animation. 

**Screenshots**
N/A

**Comment by gpeal** [comment]
Please attach a sample project. This is a likely an issue with your specific project.
