### ISSUE TITLE
Why cant I open .json in Phone ? FileNotFoundException 

### ISSUE THREAD

**Issue by Pingsh** [airbnb/lottie-android#196]
Send  a .json file into my phone, likes EmojiWink.json, but...FileNotFoundException. Which formats can be used ? By the way, phone ZTE A2017 and Meizu MX4

private void onFileLoaded(final Uri uri) {
    InputStream fis;

    try {
      switch (uri.getScheme()) {
        case "file":
          **fis = new FileInputStream(uri.getPath());**
          break;
        case "content":
          fis = getContext().getContentResolver().openInputStream(uri);
          break;
        default:
          onLoadError();
          return;
      }
    } catch (FileNotFoundException e) {
      **onLoadError();**
      return;
    }

**Comment by Pingsh** [comment]
Storage Permission !!!

**Comment by gpeal** [comment]
@Pingsh Are you saying you didn't have the storage permission and it worked when you granted permission?

**Comment by Pingsh** [comment]
@gpeal Yes...The system didn't prompt to give permission, the exception wasn't mentioned, too

**Comment by gpeal** [comment]
@Pingsh I'm not sure if this is the problem. Can you capture the stack trace in the error there? I'm able to use the file picker on my Marshmallow/Nougat phones with no issue. Nobody else has reported this either.
