### ISSUE TITLE
Publish license in POM artifact

### ISSUE THREAD

**Issue by inktomi** [airbnb/lottie-android#1960]
**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Is your feature request related to a problem? Please describe.**
I'd like to use Licensee (https://github.com/cashapp/licensee) but version 3.7.0 of Lottie does not publish it's license information in the POM. 

**Describe the solution you'd like**
Please include the Apache 2.0 license in the POM file. 
https://github.com/airbnb/lottie-android/blob/master/LICENSE

This could be as simple as including the following in gradle.properties

```
POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo
```

(more info: https://github.com/vanniktech/gradle-maven-publish-plugin/#setting-properties)

**Describe alternatives you've considered**
The workaround is currently having Licensee ignore Lottie, which is not ideal. 

**Additional context**
Happy to answer any questions, but should be a very simple fix.

**Comment by gpeal** [comment]
Newer versions of Lottie do. I suggest upgrading your library if possiblehttps://repo1.maven.org/maven2/com/airbnb/android/lottie/4.2.2/lottie-4.2.2.pom
