### ISSUE TITLE
LottieCompositionFactory.taskCache memory leak

### ISSUE THREAD

**Issue by chenzhong13** [airbnb/lottie-android#1971]
**Library verision: Android 4.2.2**

**Issue:**
LottieCompositionFactory.taskCache caused memory leak

**Here is the code in class 'LottieCompositionFactory':**

    private static LottieTask<LottieComposition> cache(@Nullable final String cacheKey, 
    Callable<LottieResult<LottieComposition>> callable) {
        final LottieComposition cachedComposition = cacheKey == null ? null : 
        LottieCompositionCache.getInstance().get(cacheKey);
        if (cachedComposition != null) {
            return new LottieTask(new Callable<LottieResult<LottieComposition>>() {
                public LottieResult<LottieComposition> call() {
                    return new LottieResult(cachedComposition);
                }
            });
        } else if (cacheKey != null && taskCache.containsKey(cacheKey)) {
            return (LottieTask)taskCache.get(cacheKey);
        } else {
            

            // problem is here!
            LottieTask<LottieComposition> task = new LottieTask(callable);
            // LottieTask may has been executed, because its constructor send it to a Executor
            
            if (cacheKey != null) {
                // listener callback will not be called, because before it was added to LottieTask, LottieTask has been executed
                
               task.addListener(new LottieListener<LottieComposition>() {
                    public void onResult(LottieComposition result) {
                        LottieCompositionFactory.taskCache.remove(cacheKey);
                    }
                });
                task.addFailureListener(new LottieListener<Throwable>() {
                    public void onResult(Throwable result) {
                        LottieCompositionFactory.taskCache.remove(cacheKey);
                    }
                });
                taskCache.put(cacheKey, task);
            }

            return task;
        }
    }

LottieTask maybe executed before 'task.addListener()' because LottieTask will be executed in its constructor method. Sometimes our ui thread will be blocked，and this problem occurs

**Comment by gpeal** [comment]
@chenzhong13 Are you sure? LottieTask should bring listeners up to date by calling onResult immediately if it is complete when the listener is added
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieTask.java#L80

**Comment by chenzhong13** [comment]
> @chenzhong13 Are you sure? LottieTask should bring listeners up to date by calling onResult immediately if it is complete when the listener is added https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieTask.java#L80
> 
> What is the memory leak, too?

Yes， onResult will be called immediately，but when onResult is called, LottieTask has not been put into LottieCompositionFactory#taskCache
called on: https://github.com/airbnb/lottie-android/blob/fbea07d24136d75e45981db4345f7cc5a9d6b6e4/lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java#L539
put into: https://github.com/airbnb/lottie-android/blob/fbea07d24136d75e45981db4345f7cc5a9d6b6e4/lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java#L548
