### ISSUE TITLE
LottieCompositionSpec.File throwing FileNotFoundException for files saved locally

### ISSUE THREAD

**Issue by rddsantos** [airbnb/lottie-android#1978]
I'm using rememberLottieComposition and LottieCompositionSpec.File with a local fileName and it's throwing a FileNotFoundException when it tries to create the FileInputStream. Please check the code bellow:

**code on fragment:**
 rememberLottieComposition(
    spec = LottieCompositionSpec.File("content://com.test.example.staging.share_provider/share/example.json"),
    onRetry = { _, error -> false }
)

**FileNotFoundException thrown on FileInputStream creation:**
...
} else {
    val fis = FileInputStream(spec.fileName)
    when {
        spec.fileName.endsWith("zip") -> LottieCompositionFactory.fromZipStream(
            ZipInputStream(fis),
            spec.fileName.takeIf { cacheKey != null },
        )
        else -> LottieCompositionFactory.fromJsonInputStream(fis, spec.fileName.takeIf { cacheKey != null })
    }
}

This issue is happening on lottie compose 4.2.0.

**Comment by gpeal** [comment]
@rddsantos That isn't a file path. That's a content provider path.

**Comment by rddsantos** [comment]
yes you're right @gpeal , thanks for the quick reply. Do you know if there is any way of using this content provider path on lottie compose to play the animation? On LottiAnimationView we have the setAnimation function which accepts an InputStream, so I could use it but on lottie compose I can't find anything similar.

**Comment by gpeal** [comment]
@rddsantos I'd have to look into it a bit, to be honest. Feel free to poke around as well.

**Comment by rddsantos** [comment]
Hey @gpeal thanks for looking into this! Do you know when will be the next release?

**Comment by gpeal** [comment]
@rddsantos The next release is rather large so it maybe several weeks. If this is urgent, you can use the SNAPSHOT release or wrap `LottieAnimationView` with a `ComposeView` or use `LottieCompositionFactory` to generate the composition instead of `rembmerLottieComposition`.
