### ISSUE TITLE
isAnimating() still true when pausing animation

### ISSUE THREAD

**Issue by m1ga** [airbnb/lottie-android#198]
Is it correct that `lottieView.isAnimating()` if you call `pauseAnimation()`?
The `onAnimationUpdate` is still fired when I call `pauseAnimation()` and I have to set a custom `isPaused` bool value to check if the animation is paused. It would be better I think if `isAnimating()` would be false

**Comment by gpeal** [comment]
@m1ga The issue is that onAnimationUpdate isn't called after pause since the progress doesn't change after pause. You can use an AnimationListener and check for onAnimationCancel though. Would that work for you?

**Comment by m1ga** [comment]
In my case `onAnimationUpdate` was still called even my animation was paused. That's why I wanted to check `isAnimating()` to see if its actually still running. I have a workaround at the moment but I thought `isAnimating()` should represent the current state (false when paused).

**Comment by gpeal** [comment]
@m1ga Can you attach a sample project where onAnimationUpdate is called after pauseAnimation? I just did a test and the order was:
onAnimationUpdate (running = true)
pauseAnimation
onAnimationCancel

**Comment by m1ga** [comment]
Ok, I've added some more logging and you are right! `onAnimationUpdate` isn't called but `onAnimationCancel` is called the whole time while it is paused and I thought it was called only once and not all over. And that was calling my update-callback which shouldn't be the case! Thanks

**Comment by gpeal** [comment]
Great! Glad you got it sorted out.
