### ISSUE TITLE
Getter for name field of Marker class

### ISSUE THREAD

**Issue by ArtemMikhaylov** [airbnb/lottie-android#1990]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**Is your feature request related to a problem? Please describe.**
I have an animation with many markers. And I want to play it from current marker + 1 to current marker + 2 always (as result of user input). For example: currentMarkerIndex = 0, then I want to play from marker at index 1 to marker at index 2; currentMarkerIndex = 2, then I want to lay from marker at index 3 to marker at index 4.

To achieve this, I use `setMinFrame(String markerName)` , `setMaxFrame(String markerName)` methods of `LottieAnimationView`.  

I found out that I can get List of markers using `List<Marker> getMarkers()` method of `LottieComposition`. So I thought I don't really need to have markers names in my app, I can use them from List of markers. E.g. if currentMarker index = 0, I just get minFrame marker name by getting marker at index 1, and max Frame at index 2. And then use  `setMinFrame(String markerName)` and `setMaxFrame(String markerName)`.

Problem is, I can't get name from `Marker`. `Marker` has field `private final String name;` , but there's no way to get it.

**Describe the solution you'd like**
It would be nice to have a public method `String getName` in `Marker`

**Describe alternatives you've considered**
I just declared my own list of marker names inside app. Not a big deal, but it would be nice to have possibility to get name from `Marker`

**Additional context**
N/A

**Comment by MohitMandalia** [comment]
If this is to be implemented then please let me know if it is open for contribution.

Thanks
