### ISSUE TITLE
I got Error

### ISSUE THREAD

**Issue by PartapSBimrah** [airbnb/lottie-android#1991]
I got an error after updating the latest dependency like this. Please check it out and let me know.

`implementation 'com.airbnb.android:lottie:4.2.2`

Also, check the screenshot down below

![1](https://user-images.githubusercontent.com/39325207/149347304-45a9bca9-4bba-45d3-bcdd-1c1d471fbaf6.png)

**Comment by gpeal** [comment]
The API is `setRenderMode(RenderMode.HARDWARE)`
