### ISSUE TITLE
Compound paths rendering as solid rectangles in Lottie animation

### ISSUE THREAD

**Issue by bear-r** [airbnb/lottie-android#200]
Hello, Lottie community!

When our app dev team discovered Lottie, we were all super excited at the prospect of being able to integrate some sweet animations in our app. I am a designer, and while I'm still pretty green using AE, I've been eager for this opportunity to get more familiar with it. :)

I created a fairly simple animation to illustrate a "tap to pair" feature of our product, and our Android dev has been testing it out for me as I go along. The phone and our product icons are both composed of compound paths I created in AI, then created shape layers from after importing to AE. An earlier test of this animation worked pretty well minus a couple weird spots where a few anchor points were not joined in the original AI file. It's been a few iterations of the animation since correcting that (and I don't have them anymore). I'm not sure what went wrong, but now both of those shapes render as solid white rectangles when implemented with Lottie, despite looking correct in AE and when exported as a .mov file from AE.

This might be a super dumb mistake that I can't figure out, but I deeply appreciate the help!

This is the expected results:
![expected-results](https://cloud.githubusercontent.com/assets/20459690/24003552/2a8ddb1c-0a3a-11e7-9ae6-09cdfc27d072.gif)

This is how it appears in the Lottie test app:
![actual-results](https://cloud.githubusercontent.com/assets/20459690/24003872/0a485d9a-0a3b-11e7-9ab6-4833fc2091a1.gif)

And here is my AE file:
[tap-to-pair.aep.zip](https://github.com/airbnb/lottie-android/files/848172/tap-to-pair.aep.zip)

**Comment by gpeal** [comment]
@bear-r I'm glad you're excited about Lottie! Thanks for attaching the AE file. Unfortunately, merge paths aren't supported yet. We are looking in to it though. it should be possible to build the animation without merge paths though.

**Comment by gpeal** [comment]
@bear-r as of https://github.com/airbnb/lottie-android/commit/2807b1124eb8732f3f92b3174adce9520664b2f0, you can explicitly enable merge paths. I've confirmed that they work with your animation. However, it only works on KitKat and above. In general, I'd recommend avoid using merge paths if you can but at least you have this options now (when 2.0 is released).
