### ISSUE TITLE
Lottie Animation(Android) : White Strokes are visible in the background of the image

### ISSUE THREAD

**Issue by prarthanaash** [airbnb/lottie-android#2011]
Hi,

I am new to Lottie integration and we have a requirement to integrate a Lottie file in the Android application. In Lottie previewer and in the application, there are some extra white strokes visible in the background of the image.

code snippet used for animation:
<com.airbnb.lottie.LottieAnimationView
android:id="@+id/animation_view"
android:layout_width=“match_parent”
android:layout_height=“match_parent”
app:lottie_rawRes="@raw/splash"
app:lottie_autoPlay=“true”
android:scaleType=“centerCrop”
app:lottie_loop=“false”
/>
animationView.setAnimation(R.raw.splash)
animationView.playAnimation()
animationView.loop(false)

Do I need to include any fonts, images from adobe after effects in code?
Your help is much appreciated.

output - 

![1643363033618](https://user-images.githubusercontent.com/98578121/151799078-85d106cb-0248-4759-a050-7096f9198b5c.JPEG)
 

Thank you.

**Comment by gpeal** [comment]
@prarthanaash You'll have to attach your animation if you want me to take a look.

**Comment by prarthanaash** [comment]
> @prarthanaash You'll have to attach your animation if you want me to take a look.
![1643363033618](https://user-images.githubusercontent.com/98578121/151799186-66598b12-aa85-4ad6-916b-9a77068d1097.JPEG)

**Comment by gpeal** [comment]
@prarthanaash Please attach an aep or json file.

**Comment by gpeal** [comment]
Can you also try `setApplyingOpacityToLayersEnabled(true)`?

**Comment by prarthanaash** [comment]
@gpeal  Im not able to attach the .json file.

**Comment by gpeal** [comment]
@prarthanaash Unfortunately, I won't be able to assist then. If your designer can create a simplified/modified version of this that repros the same issue, feel free to reopen this.
You can also go in and hand-remove layers from the json file. Whether or not it will still work depends on the specific structure of your animation so you may have to do some trial and error.
