### ISSUE TITLE
Crash with proguard

### ISSUE THREAD

**Issue by Ibernato93** [airbnb/lottie-android#2013]
**Describe the bug**
I have an obfuscated library with allatori that uses lottie-animation. I have integrated this library into my app. My app obfuscates it with proguard, but when I start the activity of the library that has to create the animation "setAnimationFromJSON (animationPath, false)", the application crashes with this error

java.lang.NullPointerException: Attempt to invoke interface method 'com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation com.airbnb.lottie.model.animatable.AnimatableValue.createAnimation()' on a null object reference
at com.airbnb.lottie.animation.content.RectangleContent.<init>(RectangleContent.java:8)
at com.airbnb.lottie.model.content.RectangleShape.toContent(RectangleShape.java:1)

**What version of Lottie did you test this on?**
4.2.2

**What version of Android did you test this on?**
Android 12

**Steps To Reproduce**
1) import animation into assets folder
2) obfuscate with proguard
3) impossible load animation 
 animationView.setAnimationFromJson(json, null);
 animationView.setImageAssetsFolder("");
  animationView.setRepeatMode(LottieDrawable.RESTART);
  animationView.setRepeatCount(LottieDrawable.INFINITE);
   animationView.playAnimation();

in the proguard file I have excluded lottie and my libraries obfuscated with allatori

-dontwarn com.airbnb.lottie. **
-keep class com.airbnb.lottie. ** {*; }
-keep interface com.airbnb.lottie. ** {*; }
-keep enum com.airbnb.lottie. ** {*; }

**Comment by gpeal** [comment]
Can you attach a repro project?

**Comment by Ibernato93** [comment]
> Can you attach a repro project?

I can't, it's a work project and I can't share it.
I can add this information to you.
In our library obfuscated with allatori, animations with lottie are instantiate programmatically with "setAnimationFromJSON (animationPath, false)"
The flutter application that uses our library, without the active proguard, everything works correctly. When they build for the release and activate the proguard, the animations created programmatically in our library with allatori cause the crash. On the other hand, if I create the animation via xml (always in our library with allatori) and use "@ raw/animation.json", everything works fine.

Any idea?
It is important

**Comment by gpeal** [comment]
Unfortunately, I won't be able to help without a repro project.

Many apps (including my work project use proguard with Lottie). I suggest toying with your proguard config and then checking the generated apk/dex files with the Android Studio APK Analyzer.
