### ISSUE TITLE
Gradient export for AVD format isn't working

### ISSUE THREAD

**Issue by davidjhammer** [airbnb/lottie-android#2018]
I'm trying to export an AE animation to AVD format, and some of the objects have gradients.  They aren't showing in Android Studio when I bring in the .xml file.  It's really hard to find a list of After Effects features that the AVD export supports.  Should gradients be exporting properly to .XML/AVD ?  Not sure if it's a bug, or if it's an unsupported feature?

**Steps To Reproduce**

1. Create a couple of shape layers with gradients applied in AE
2. Export with the AVD format checked
3. Open the output .xml file in Android Studio to preview
4. See that objects don't render.

**Comment by gpeal** [comment]
This is just for the Lottie Android. If this is for the AVD exporter, you'll want to post this on https://github.com/airbnb/lottie-web/

**Comment by davidjhammer** [comment]
Ah, cool, thanks!
