### ISSUE TITLE
Using LottieAnimationView in listview

### ISSUE THREAD

**Issue by chengzheustc** [airbnb/lottie-android#202]
`  @Override
  protected void onAttachedToWindow() {
    super.onAttachedToWindow();
    if (wasAnimatingWhenDetached) {
      playAnimation();
    }
  }`

Hello, when I use the LottieAnimationView in listview item, I think the above code is not suitable. For I see the animation is played automatically.

Thanks for your time!

**Comment by gpeal** [comment]
@chengyin I'll update this so that it only resumes when autoPlay is set to true
