### ISSUE TITLE
Request: for LottieAnimationView, add flag to ignore animation speed of the system settings

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [airbnb/lottie-android#2020]
**Is your feature request related to a problem? Please describe.**
Yes. When using addAnimatorListener, it will get called right away in case the OS has animations disabled, which can cause issues if we have a call there to play the animation again.
This was written here:
https://github.com/airbnb/lottie-android/issues/1534

**Describe the solution you'd like**
Add a flag (available in XML and code) to ignore the system setting of animation speed.
After all, Lottie is more like a player of videos (yet of vectorized animation) than a general animation of View, and the system setting is mostly about View animation (alpha, movement, scaling...).
This flag would only affect the playback of the animation. Not anything else that is related to View. 

Maybe even set this flag to true by default, so that this issue will never occur, and that the animation will be played like VideoView, meaning it won't be affected by the OS's setting of animation speed.
This is fine, because this OS setting is set only when developer options is enabled.

**Describe alternatives you've considered**
I tried to find a way to disable it for View (hence affecting LottieAnimationView), but I couldn't find it.

**Additional context**
Sample code to trigger this issue:

```
binding.lottieView.addAnimatorListener(object : Animator.AnimatorListener {
    override fun onAnimationEnd(animation: Animator?) {
        // some code that's not relevant to Lottie  
        binding.lottieView.playAnimation()
    }
    ...
})
```

**Comment by gpeal** [comment]
Does this API work for you?
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L327

**Comment by AndroidDeveloperLB** [comment]
@gpeal You mean "setIgnoreDisabledSystemAnimations" (the line doesn't quite point there) ? 
Why didn't you mention it on the post that I've mentioned?

Also, why don't you set it to true by default? Users aren't supposed to reach developer options, and even if they do, Lottie is a player of content (animation, which is similar to video), so content shouldn't be affected by this setting by default.
