### ISSUE TITLE
[Question] How to make LottieAnimation scale to parent size in Compose?

### ISSUE THREAD

**Issue by clhols** [airbnb/lottie-android#2022]
With Lottie 4.1.0 we are using IntrinsicSize.Min to make the LottieAnimation scale to the content size like this:

```
        Box(modifier = Modifier.height(IntrinsicSize.Min)) {
          LottieAnimation(
            composition = composition,
            iterations = LottieConstants.IterateForever,
            contentScale = ContentScale.FillBounds,
          )
          content()
        }
```

The composable function content() dictates the size of the Box and LottieAnimation scales to it.
This doesn't work anymore with Lottie version 4.2.2 due to #1892.

I have tried to add fillMaxSize() and widthIn() on LottieAnimation but I have been unable to make it behave as before.
Any pointer on how to accomplish this?

**Comment by gpeal** [comment]
@clhols What, exactly, are you trying to accomplish and what is the delta between what you expect and what is happening?

**Comment by clhols** [comment]
Googles example on intrinsic explains it well. Just replace Divider with LottieAnimation:
https://developer.android.com/jetpack/compose/layouts/intrinsic-measurements#intrinsics-in-action

LottieAnimation in 4.1.0 worked just like Divider does in this example. You had fillMaxSize and the min intrinsic size for LottieAnimation was 0 width and 0 height. I believe that the change in #1891 now set the min intrinsic size to the composition size and then it doesn't behave like Divider in the example anymore. Maybe it is possible to use MeasurePolicy as mentioned in the docs to set min intrinsic size for LottieAnimation to 0?

**Comment by gpeal** [comment]
@clhols I'm still not sure I follow. The min intrinsic size for Lottie isn't 0, it's the size of the composition similar to how an image would behave.

**Comment by clhols** [comment]
@gpeal Did you have a chance to look at the example project? Is it clear what I am trying to achieve?

**Comment by gpeal** [comment]
@clhols I haven't had a chance to yet.

**Comment by slikasgiedrius** [comment]
I do face the same issue. Any updates?

**Comment by melanu1991** [comment]
The same issue for me.

**Comment by gpeal** [comment]
If you add `fillMaxWidth()` on the parent box and add `matchParentSize()` on `LottieAnimation` it renders as you'd like it to. Does that solve your problem?

**Comment by clhols** [comment]
@gpeal  You are absolutely right. It does work. I can even remove the IntrinsicSize.Min. Thanks a lot!
