### ISSUE TITLE
In previen Lottie animation look as exception but when run on app it does not show the color change effect 

### ISSUE THREAD

**Issue by baseplate77** [airbnb/lottie-android#2031]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**Describe the bug**
I have created this animation in after effect 2021 and rendered its JSON file. in preview, everything looks good with color change from inactive to active. For which I have used the Fill effect in after effects

But when I run this animation in the FLutter app using [Lottie package](https://pub.dev/packages/lottie) for some reason it does not show the color change remain in active state only

[animation link](https://lottiefiles.com/98085-teddy)

if anyone known anything please let me know.

![animation_500_l0aqroz9](https://user-images.githubusercontent.com/49200489/156535046-fa973e78-4df9-4081-8b14-f3b9414dd312.gif)

**What version of Lottie did you test this on?**
5.0.2

**What version of Android did you test this on?**
Pixel 4 emulator API 30

**Steps To Reproduce**

1. Go to [Animation link](https://lottiefiles.com/98085-teddy)
2. Click on Copy aniamtion URL
3. create a lottie class with this animation
4. run it on app

After effect  project 
[teddy animation.zip](https://github.com/airbnb/lottie-android/files/8176652/teddy.animation.zip)

**Screenshots**

![teddy animation issue](https://user-images.githubusercontent.com/49200489/156535626-c2b9485c-7269-4069-88d1-c6fe9aba51b4.gif)

**Comment by gpeal** [comment]
Lottie for Flutter is a different library entirely. I recommend posting this there.

**Comment by baseplate77** [comment]
@gpeal  I have posted there [#200](https://github.com/xvrh/lottie-flutter/issues/200)

**Comment by baseplate77** [comment]
The reason for posting here is I want to know that is there anything wrong from my end. any mistake in after effect file

**Comment by gpeal** [comment]
@baseplate77 https://github.com/airbnb/lottie-web is the right repo for that.
You can also test your animation by dragging it over https://lottiefiles.com/ if it works there then it's a Flutter specific issue.

**Comment by baseplate77** [comment]
@gpeal I have published the animation [link](https://lottiefiles.com/98085-teddy) it happen to preview as excepted.
