### ISSUE TITLE
The loaded animation is using a different size

### ISSUE THREAD

**Issue by Glennmen** [airbnb/lottie-android#2032]
**Describe the bug**
I am loading a LottieDrawable into a Canvas as a Live Wallpaper.
The Canavs and lottie file are both in 1920/1080 but the lottie drawable is loaded using a different size.

Logging `lottieDrawable.intrinsicWidth` returns `2880` and `lottieDrawable.intrinsicHeight` returns `1620`.
After debugging I noticed that `LottieCompositionMoshiParser.parse` uses `Utils.dpScale()` and this returns 1.5 and this messes up the size of the composition.

Not sure if I am missing anything 🤔

**What version of Lottie did you test this on?**
Lottie 4.2.1

**What version of Android did you test this on?**
Android 8

**Steps To Reproduce**

Not sure what to write here, I load the composition into a lottie drawable and render it on a canvas.

**Screenshots**
![CleanShot 2022-03-04 at 13 01 46](https://user-images.githubusercontent.com/11406433/156760018-5f2caa73-efcc-4020-a75e-81bdc956d97c.png)

Animation loading correctly in LottieFiles: https://lottiefiles.com/share/j9noozke

**Comment by Glennmen** [comment]
I was able to get it working but not sure if this is the correct solution.
I manually changed the scaling (`width` is the size of the view), this removes the 1,5 scaling from `LottieCompositionMoshiParser`.

```kotlin
lottieDrawable.apply {
	composition = lottieComposition
	scale = (width.toFloat() / composition.bounds.width())
}
```

**Comment by gpeal** [comment]
@Glennmen After Effects sizes are converted to dps. You can try calling setBounds on your drawable. Do you have access to an ImageView? If so, you can use scaleType.

**Comment by Glennmen** [comment]
@gpeal I did try setBounds but that didn't help and even made it worse.
Also it is an Android Live Wallpaper so the only thing I can use is a canvas, no other components.

**Comment by gpeal** [comment]
Could you create a sample project?

**Comment by Glennmen** [comment]
@gpeal I will see what I can do. 🤔

**Comment by gpeal** [comment]
@Glennmen Any update?

**Comment by Glennmen** [comment]
Sorry @gpeal I didn't have time to setup a sample project yet.

I did notice last week that there was a new major version and in the release notes it mentioned changes to scaling.
After updating it "broke" my animation again, but that was to be expected.
After working out the changes I ended up with this.
```kotlin
lottieDrawable.apply {
    val scale = (canvas.width.toFloat() / composition.bounds.width())
    canvas.scale(scale, scale)
    draw(canvas)
}
```

Does this look correct?

**Comment by Glennmen** [comment]
Fine by me 😀 closing ticket.
