### ISSUE TITLE
Is "app:lottie_scale" deleted??

### ISSUE THREAD

**Issue by Jay-lol** [airbnb/lottie-android#2035]
I was using version 3.x, but this time I upgraded to version 5.
However, in the xml file, it says that "lottie_scale" is an attribute that cannot be found. 
Has this been deleted??

**Comment by gpeal** [comment]
Yes, it's in the changelog
https://github.com/airbnb/lottie-android/releases/tag/v5.0.1

**Comment by Jay-lol** [comment]
> Yes, it's in the changelog https://github.com/airbnb/lottie-android/releases/tag/v5.0.1

Thank you. It was updated 14 days ago, so there is not much information in google search result 😂
