### ISSUE TITLE
Performance regression in v. 5.0.3

### ISSUE THREAD

**Issue by LudoFarkas** [airbnb/lottie-android#2039]
**Describe the bug**
Hi,

we have a quite complex animation in our app with confetti falling from the top of the screen. We have recently upgraded Lottie from v. 3.7.2 to 5.0.3. The animation was buttery smooth in 3.7.2. However, now in 5.0.3 it is quite choppy, with dropped frames. A simplified version of the animation is attached.

The animation is loaded from a file:

```
      val composition = File(mediaType.path).inputStream().use { fileIs ->
          LottieCompositionFactory.fromJsonInputStreamSync(fileIs, mediaType.path).value
      } ?: return
      
      lottieView.repeatCount = LottieDrawable.INFINITE
      lottieView.repeatMode = LottieDrawable.RESTART
      lottieView.setComposition(composition)
      lottieView.playAnimation()
```

**What version of Lottie did you test this on?**
3.7.2, 5.0.3

**What version of Android did you test this on?**
11, 12

**Simplified animation json**
[Confetti.json.zip](https://github.com/airbnb/lottie-android/files/8246276/Confetti.json.zip)

**Comment by LudoFarkas** [comment]
Hi. Yes, but it didn't help.

**Comment by gpeal** [comment]
I just took a look at your animation and the change was from 4.1.0 when support for blurs was added. Blurring with software rendering is extremely slow. I don't think the render mode you set was applied because, with blurs, the per-frame duration went from 120ms to 4ms on my emulator.

**Comment by ursusursus** [comment]
Im seeing this as well 😔

**Comment by LudoFarkas** [comment]
@gpeal thanks for looking into it. 
The render mode was indeed set to HW. And you are right that SW rendering was multiple times slower than HW rendering.
However, on our real device (Xiaomi Mi 9, MIUI Global 12.5.1, Android 11) the performance of HW rendering degraded significantly between Lottie ver. 3.7.2 and Lottie ver. 5.0.3.
The per frame duration on said device went with HW rendering from approx. 6ms to approx. 42ms in systrace. And the confetti animation is janky.
We see a similar degradation also on a Pixel 5.

See please the attached screenshots of the same animation with HWUI rendering on. The smooth is with ver. 3.7.2 and the janky with ver. 5.0.3.

![confetti_lottie_3 7 2](https://user-images.githubusercontent.com/45174293/161923178-dc0d9a67-abe8-4970-b431-15eea5a2233b.jpg)

![confetti_lottie_5 0 3](https://user-images.githubusercontent.com/45174293/161923187-b0296c1e-4dc3-45be-bb59-06b42cbd54aa.jpg)

**Comment by LudoFarkas** [comment]
OK, now I understand. Thank you for the explanation.
