### ISSUE TITLE
Animation doesn't play using Lottie-Compose

### ISSUE THREAD

**Issue by chummy-ch** [airbnb/lottie-android#2045]
Describe the bug
With Lottie-Compose, the animation doesn't play. Some other animations are playing and anothers playing wrong.

What version of Lottie did you test this on?
Lottie-Compose 5.0.3
Jetpack Compose 1.0.5.

Steps To Reproduce

Use the attached planes.json file in the zip (this is from [link](https://lottiefiles.com/70369-planes)) 
[planes.json.zip](https://github.com/airbnb/lottie-android/files/8352155/planes.json.zip)

Use LottieComposition to display the animation
```
val composition by rememberLottieComposition(LottieCompositionSpec.RawRes(rawRes))
val progress by animateLottieCompositionAsState(
           composition = composition,
      	  iterations = LottieConstants.IterateForever
    )
LottieAnimation(
        composition = composition,
        modifier = modifier,
        progress = progress,
   )
```

https://user-images.githubusercontent.com/57348590/160158485-877890de-e37e-4ec4-86da-7e666e702caa.mp4

**Comment by gpeal** [comment]
Lottie doesn't support expressions or the trace path effect
http://airbnb.io/lottie/#/supported-features

**Comment by MohanOnsurity** [comment]
Lottie is not working in MI A3, what is the issue?


val composition by rememberLottieComposition(
        LottieCompositionSpec.Url(
            responseFestiveData?.lottieUrl ?: ""
        )
    )

    val progress by animateLottieCompositionAsState(
        composition = composition,
        iterations = LottieConstants.IterateForever,
    )

    LottieAnimation(
        modifier = modifier
            .fillMaxWidth()
            .height(OnsurityTheme.dimension.dp245),
        composition = composition,
        progress = { progress },
    )
