### ISSUE TITLE
[Android] Lottie Animation not working after onPause

### ISSUE THREAD

**Issue by zenyagami** [airbnb/lottie-android#2053]
Using lottie for Android `com.airbnb.android:lottie:5.0.3',` the animation is not working after `onPause` is called,  even using `playAnimation()` will not have any effect.
however using the version `"com.airbnb.android:lottie:4.2.1"` . the animation works correctly after onPause, I'm not sure if is Android version related, but this is happening in Pixel 5/6 Pro  with Android 12.

steps:
1. implement lottie in XML
```xml
  <com.airbnb.lottie.LottieAnimationView
        android:layout_width="300dp"
        android:layout_height="300dp"
        app:lottie_autoPlay="true"
      app:lottie_rawRes="@raw/android_12_animation"
        app:lottie_repeatCount="-1"
        />
```
2. In the Fragment just go to background and resume, nothing will happen, alternative I tried overriding ` onPause` and `onResume`. to manually pause or just start the animation and does not work,
calling the view from the fragmen `lottieView.isAnimating` returns true after onResume

**Comment by gpeal** [comment]
@zenyagami Can you attach a sample project?
