### ISSUE TITLE
Spanned/SpannableString not affected by overlayed Lottie animation

### ISSUE THREAD

**Issue by niall8z** [airbnb/lottie-android#2060]
I have an entire animation view which simulates a dimming affect when the user is inactive. On the overall view is made up of several several Layouts which also contain TextViews, some of the text in one of the TextViews is coloured using SpannableString, ForegroundColourSpan or Html.fromHtml. However, the dimming affect is not applied to the part of the text view that is overlayed with the LottieAnimationView.

`        val styledText = "$temperature<font color='#84969C'>${WeatherConfig.DEGREE_SYMBOL}</font>"
        return Html.fromHtml(styledText, HtmlCompat.FROM_HTML_MODE_LEGACY)`

and in the parent view the xml is declared as normal and the usual animations are applied.

**Comment by gpeal** [comment]
Can you attach a repro project?

**Comment by gpeal** [comment]
Closing due to lack of acivity. Feel free to reopen with a sample project.
