### ISSUE TITLE
Application updates on Google Play - old version in the store

### ISSUE THREAD

**Issue by olekstomek** [airbnb/lottie-android#2070]
The latest version [ 5.1.1 on GitHub is April 24th](https://github.com/airbnb/lottie-android/releases/tag/v5.1.1) (for now).
The latest version[ 5.0.1 on Google Play is February 21th](https://play.google.com/store/apps/details?id=com.airbnb.lottie) (for now).
The difference is several versions (including the minor version level). Why?

**Comment by gpeal** [comment]
@olekstomek Because I don't work at Airbnb anymore and have to jump through a few hoops to keep it up to date 😄

**Comment by olekstomek** [comment]
OK I understand. I hope it will be easier one day... :)
