### ISSUE TITLE
Lottie animation is not playing  when it comes from a Remote URL

### ISSUE THREAD

**Issue by armagancivelek** [airbnb/lottie-android#2074]
Hi, I would like to use remote json from a url . but it is not working to me.

I have a code something like that:
lottieAnimationView.setAnimationFromUrl("https://assets9.lottiefiles.com/packages/lf20_fHel3A.json")
        lottieAnimationView.playAnimation()

There is not error also no result, what is the point that I missed

**Comment by gpeal** [comment]
Can you attach a sample project? Did you add the INTERNET permission to your app?

**Comment by armagancivelek** [comment]
Here it is . it is so simple project for to try loading the lottie animation from url but i think I'm missing a point maybe you can help me 
[CustomView.zip](https://github.com/airbnb/lottie-android/files/8682698/CustomView.zip)

thanks in advance

**Comment by gpeal** [comment]
You are missing the http protocol. I added `https://` in front of the URL and it worked fine.

**Comment by venukapavarapu** [comment]
> You are missing the http protocol. I added `https://` in front of the URL and it worked fine.

I am tried the same but it is not working.did you add anything apart from that url
