### ISSUE TITLE
NetworkFetcher.java line 85 :: com.airbnb.lottie.network.NetworkFetcher.fetchFromNetwork Error

### ISSUE THREAD

**Issue by vivekojha1108** [airbnb/lottie-android#2075]
It is crashing all the time and showing me is Crashlytics. It seems some internal package issue. Please solve it or show some way how to resolve it.

**Fatal Exception: java.lang.IllegalStateException
Unable to parse composition**

- com.airbnb.lottie.LottieAnimationView.lambda$static$0 (LottieAnimationView.java:72)
- com.airbnb.lottie.LottieAnimationView.$r8$lambda$AW1943Wq77PiX8nINFaTdc7Xm9s (LottieAnimationView.java)
- com.airbnb.lottie.LottieAnimationView$$InternalSyntheticLambda$0$be4b3973569454891843682fd2baa5cb678ed6c3ae63f3ea26f9257999d31d7f$0.onResult (LottieAnimationView.java:2)
- com.airbnb.lottie.LottieAnimationView$1.onResult (LottieAnimationView.java:84)
- com.airbnb.lottie.LottieAnimationView$1.onResult (LottieAnimationView.java:77)
- com.airbnb.lottie.LottieTask.notifyFailureListeners (LottieTask.java:162)
- com.airbnb.lottie.LottieTask.lambda$notifyListeners$0 (LottieTask.java:138)
- com.airbnb.lottie.LottieTask.$r8$lambda$Rpnx63cLRLCF9DbgjiFM7rp0Vik (LottieTask.java)
-com.airbnb.lottie.LottieTask$$InternalSyntheticLambda$0$96a344ffc28df59816d87e2ec1f248fd91043cf6d7a61d932bfe48316715ddf9$0.run (LottieTask.java:2)
- android.os.Handler.handleCallback (Handler.java:873)
- android.os.Handler.dispatchMessage (Handler.java:99)
- android.os.Looper.loop (Looper.java:201)
- android.app.ActivityThread.main (ActivityThread.java:6810)
- java.lang.reflect.Method.invoke (Method.java)
- com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:547)
- com.android.internal.os.ZygoteInit.main (ZygoteInit.java:873)

-------

**Caused by java.lang.IllegalArgumentException
Read error: ssl=0x753c382808: Failure in SSL library, usually a protocol error error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE (external/boringssl/src/ssl/ssl_lib.cc:988 0x7539278f3f:0x00000000)**

- **com.airbnb.lottie.network.NetworkFetcher.fetchFromNetwork (NetworkFetcher.java:85)**
- com.airbnb.lottie.network.NetworkFetcher.fetchSync (NetworkFetcher.java:42)
- com.airbnb.lottie.LottieCompositionFactory.lambda$fromUrl$0 (LottieCompositionFactory.java:97)
- com.airbnb.lottie.LottieCompositionFactory.$r8$lambda$ryfz4DLJCh-ExlYZuhvFFPFbE2w (LottieCompositionFactory.java)
- com.airbnb.lottie.LottieCompositionFactory$$InternalSyntheticLambda$0$4cfce70023bb417caa94a06717e90c56bbece265c6d49c204308601d27a01c12$0.call$bridge (LottieCompositionFactory.java:12)
- java.util.concurrent.FutureTask.run (FutureTask.java:266)
- java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
- java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
- java.lang.Thread.run (Thread.java:764)

-----
Please give some solution.

**Comment by gpeal** [comment]
You'll want to add a failure listener on your LottieAnimationView to handle network failures. Alternatively, you can replace the built in networking pipeline (which is basic, at best) with your own LottieConfig set [here](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/Lottie.java#L19)

**Comment by gopalawasthi123** [comment]
@gpeal Add failure listener still this issue persists

`animationView.setFailureListener{
        it.logThrowableException()
    }`

**Comment by HeroOussama** [comment]
is this still not fixed ? am facing the same crash at com.airbnb.lottie.network.NetworkFetcher.fetchFromNetwork (NetworkFetcher.java:98)
