### ISSUE TITLE
Android animating only certain layers

### ISSUE THREAD

**Issue by Maneneco** [airbnb/lottie-android#2079]
I have a splashScreen using lottie, and when I upload the json file to lottie files it shows corretly, 
like this: https://lottiefiles.com/share/ezjbwdg1

But when I upload it to android in the middle of the animation certain layers stop working, like the person stop waving and the wheels stop rotating. Like this

https://user-images.githubusercontent.com/61877154/169653849-ade506c0-3bf5-49c3-bb73-7d2973f09eda.mp4

I am using version 5.1.1

**Comment by Maneneco** [comment]
It might be because I am using a looping function to apply a loop to the objects movment, if so have any solution? I have tried a lot of diferent exports, but they all seem to have the same problem

**Comment by Maneneco** [comment]
Yep thats the problem, he does not seem to work with the loop out using aftereffects on json, repating the keybframes one by one without looping works. Not practical but it works

**Comment by gpeal** [comment]
Your animation uses expressions which Lottie Android doesn't support.
You can refer to [the docs](http://airbnb.io/lottie/#/supported-features) for what is and isn't supported.
