### ISSUE TITLE
Json filw is working in  ios and lottie website but not working in android

### ISSUE THREAD

**Issue by mobilecoderztech** [airbnb/lottie-android#2093]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Checklist**

1. My json animation is not working. 

**Describe the bug**
 Json file is working perfectly on ios and lottie webiste but not working in android platform.

**What version of Lottie did you test this on?**
  3.5.0
**What version of Android did you test this on?**

**Steps To Reproduce**

1. Go to andorid sample project
2. Add this json file in assets
3. run the app
4. this file will not work
[json.txt](https://github.com/airbnb/lottie-android/files/8928309/json.txt)

**Screenshots*
![image_2022_06_17T06_30_31_516Z](https://user-images.githubusercontent.com/49387902/174315820-7f8bf6bc-d266-46b2-a7d2-280a117683c8.png)
*

**Comment by gpeal** [comment]
The attached text file seems to be some variant of json. Can you attach your original json animation so that I can look into this?
