### ISSUE TITLE
Cannot release memory

### ISSUE THREAD

**Issue by Semedaki** [airbnb/lottie-android#2095]
I have a some videos I want to play, one after the other. The videos contain raster images, I basicaly converted png sequences to lotties in after effects, and checked the option "include rasterized images encoded in json".
The videos play inside the same lottie view. When one finishes the next will be loaded and start playing.

**The problem:**
 When each video starts playing it causes a big spike in memory usage. This memory is not released when the previous video is replaced and each video increases memory usage even more. The memory is not released even when the activity gets destroyed.

Things I tried without success:
- calling LottieCompositionCache.getInstance().clear() (with restricted api annotation)
- calling System.gc()
- making the lottie view null before loading the next video
- calling setCacheComposition(false) before each video starts
- calling LottieCompositionFactory.clearCache(this)

Is there anything that could help?

![memory_problem](https://user-images.githubusercontent.com/107938867/174835392-04f72a6f-27f1-4efd-a419-18588209f9a6.jpg)

**Comment by gpeal** [comment]
Makes sense. The xml attr would only have an effect if you use the other attrs to load the composition. If you're using the factory yourself, you need to set the cacheKey to null on parse or clear it.

**Comment by Semedaki** [comment]
I tried calling LottieCompositionFactory.clearCache before, but it didn't work. I think it was because I initially loaded all compositions and put them in an array, so I would avoid the loading delay when I played the videos. 
When I don't keep the compositions in variables, clearCache works fine.

**Comment by b1tb1t** [comment]
After the animation ends, directly set a new empty resource
lottieAnimView.setAnimation(R.raw.empty)
