### ISSUE TITLE
LottieDrawable as seekbar thumb doesn't work

### ISSUE THREAD

**Issue by Jianzhao-Huang** [airbnb/lottie-android#2098]
I'm trying to put a lottie animation as thumb of a seekbar but when I drag the thumb itself is not dragged, just the progress of seekbar is changed.

I've considered issue#1749, and try the solution that you gave in that issue. However, it doesn't work.

Here is my code. As you see, I just added `thumb.callback = seek` to the code published in issue#1749.
```
class MainActivity : AppCompatActivity() {

    private lateinit var binding: ActivityMainBinding
    private val thumb = LottieDrawable()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)
        val seek = SeekBar(this)
        seek.thumb = thumb
        val lp = ActionBar.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT)
        thumb.scale = 0.3F
        seek.layoutParams = lp
        seek.max = 200
        seek.progress = 100

        LottieCompositionFactory.fromAsset(this, "dot.json").addListener {
            thumb.composition = it
            thumb.repeatCount = LottieDrawable.INFINITE
            thumb.playAnimation()
            thumb.callback = seek
            binding.root.addView(seek)
        }
    }
}
```

**Comment by Jianzhao-Huang** [comment]
Actually, I found that the LottieDrawable moved, but only the bottom layer of it moved, the other layer of  the LottieDrawable are still in origin place.

**Comment by gpeal** [comment]
Could you attach a sample project that reproduces this?

**Comment by Jianzhao-Huang** [comment]
`class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val lottieDrawable = LottieDrawable()
        LottieCompositionFactory.fromRawRes(this, R.raw.swimming).addListener{ //R.raw.swimming is a lottie json file
            lottieDrawable.composition = it
        }
        lottieDrawable.scale = 0.2f

        val seekBar = findViewById<SeekBar>(R.id.seek_bar)

        val button1 = findViewById<Button>(R.id.button1)
        button1.setOnClickListener{
            seekBar.thumb = lottieDrawable
            lottieDrawable.callback = seekBar
        }

        val button2 = findViewById<Button>(R.id.button2)
        button2.setOnClickListener{
            lottieDrawable.apply {
                setBounds(bounds.left+50, bounds.top, bounds.right+50, bounds.bottom)
            }
        }
    }
}`
Here is my code.

I want a customized SeekBar, which's thumb is a LottieDrawable that can perform animation.

In this sample, I click button1, and then, the thumb of seekbar change. But the problem is, the LottieDrawable is always shown at the left of seekbar. When I drag the thumb, the blank move. But the "swimming image", the content of LottieDrawable, is still at the origin place.

When I click button2, the blank move, but the "swimming image" still don't move.

These look like, LottieDrawable moved, but only the bottom layer of it moved, the other layer of the LottieDrawable are still in origin place.

By the way, the version I use is 4.2.2, which is the last version that LottieDrawable.scale() can be used.

**Comment by gpeal** [comment]
This is not a sample app. Please attach an actual app as a zip file or via another GitHub repo/fork. You can fork this repo and use the `issue-repro` app if you'd like.

**Comment by Jianzhao-Huang** [comment]
This is the sample app that has problem
[issue-sampe.zip](https://github.com/airbnb/lottie-android/files/8997947/issue-sampe.zip)

This is the version that have been corrected.
[correct.zip](https://github.com/airbnb/lottie-android/files/8997960/correct.zip)

Please check it out.

The bounds of LottieDrawable have no effect in drawing itself. If this is not the expected behavior, please fix it.
