### ISSUE TITLE
KMM Desktop Support 

### ISSUE THREAD

**Issue by gulabsagevadiya** [airbnb/lottie-android#2099]
Can we use this lib for KMM Desktop with Compose ?

**Comment by gpeal** [comment]
Nope. lottie-android leverages the Android platform and SDK for its rendering APIs. Compose doesn't have the necessary multiplatform APIs to accomplish Lottie. Something like [skottie](https://skia.org/docs/user/modules/skottie/) might work but I've never tried it.
