### ISSUE TITLE
LottieAnimationView with fade in

### ISSUE THREAD

**Issue by mr-shitou** [airbnb/lottie-android#2100]
Hi, I am use Lottie to render animation.The rendering of the animation is normal but when I want to add a fade effect to the view by property animator.
It seems like each layer does a change in transparency instead of the overall change, is this not support?
version is 5.2.0

Please help me and thank you very much.

**Comment by gpeal** [comment]
You can set an alpha on the LottieAnimationView itself or any layer/property via [dynamic properties](http://airbnb.io/lottie/#/android?id=dynamic-properties). For further help, StackOverflow may be helpful!

**Comment by mr-shitou** [comment]
I did not understand that. Is this [How to add a color overlay to an animation in Lottie?](https://stackoverflow.com/questions/43376316/how-to-add-a-color-overlay-to-an-animation-in-lottie) ,can you be more detailed? Thank you very much!
What i want to do is just like this, set a fade in animation,but not worked. I had read official docs and search some question but not found correct one
`                    Interpolator interpolator = new PathInterpolator(0.30f, 0.00f, 0.67f, 1.00f);
                   mAnimationView.animate().alpha(1).setDuration(300).setInterpolator(interpolator);`
