### ISSUE TITLE
use generic on Float cause too many auto-boxing/auto-unboxing

### ISSUE THREAD

**Issue by shifujun** [airbnb/lottie-android#211]
When I test my animation, I found  Memory Churn. So I did some analysis roughly.And I found lottie use too many generic on Float. It cause auto-boxing/auto-unboxing frequently.

I think it is the top performance problem. I will try to solve it ,and hope author will fix it more gracefully.

![2017-03-21 11 27 58](https://cloud.githubusercontent.com/assets/3535204/24131443/b60d73c6-0e29-11e7-82af-5eb2bbf3ac88.png)
![2017-03-21 11 27 41](https://cloud.githubusercontent.com/assets/3535204/24131444/b60e93c8-0e29-11e7-8546-46d1bd544a70.png)

**Comment by gpeal** [comment]
@shifujun This is something I've looked in to before. I wouldn't say it's a top memory problem because the GC can clean up after it quite easily. However, it would be a nice to have to eliminate.

**Comment by gpeal** [comment]
No need to close this. I'll look in to it :)

**Comment by yumauesaka** [comment]
![image](https://user-images.githubusercontent.com/26464685/26902345-00c237b6-4ba7-11e7-82dd-f2f31d54ce04.png)

I am seeing that with other primitives as well as (Integer for example, see above) 
I'm bumping this issue: @gpeal have you looked into resolving this?

**Comment by Curwer** [comment]
@gpeal Any news on this issue?

**Comment by gpeal** [comment]
@Curwer This hasn't been a high priority issue for me. ART is pretty good at dealing with cleaning up autoboxing. Is this causing a significant performance hit for you?

**Comment by gpeal** [comment]
I haven't found this to add significant performance or memory overhead nor has it seemed to be an issue for anybody in production. If this is definitely an issue, I can spend some more time on it.
