### ISSUE TITLE
Support custom font resolution in Compose

### ISSUE THREAD

**Issue by drewhamilton** [airbnb/lottie-android#2119]
**Is your feature request related to a problem? Please describe.**
In non-Compose UI, we use `FontAssetDelegate` to load our fonts from resources (rather than assets). In Compose UI, we currently cannot load our fonts from resources. So we stick with wrapping non-Compose Lottie in `AndroidView` for now.

**Describe the solution you'd like**
An API in lottie-compose that allows for alternative font loading. I envision this as a new `rememberLottieComposition` overload with a `Map<String, androidx.compose.ui.text.font.Font>` param, which maps font names in the Lottie file to loaded Compose Fonts.

**Describe alternatives you've considered**
1. Something similar to `FontDelegate`: some callback API that allows you to load Compose Font based on some input(s)
2. A new `rememberLottieComposition` overload with a map of Lottie font names to `@FontRes` IDs that internally loads the font resources.
3. Make the `Map` described in my preferred solution a composition local consumed by Lottie internals. I'm hesitant to suggest composition locals because they're often considered a footgun. But given that apps often want to reuse the same few fonts throughout, it might make sense in this case?

Option 2 seems the least flexible. My proposed solution, option 1, and option 3 are all flexible equally flexible I think.

**Additional context**
I notice that the KDocs for `rememberLottieComposition` param [`fontAssetsFolder`](https://github.com/airbnb/lottie-android/blob/master/lottie-compose/src/main/java/com/airbnb/lottie/compose/rememberLottieComposition.kt#L59-L60) states "Missing fonts will be skipped and should be set via fontRemapping or via dynamic properties." I can't find any other mentions of `fontRemapping` in the project, nor any dynamic properties for fonts. But perhaps this indicates you already have an API design in mind?

**Comment by drewhamilton** [comment]
Great, it's working as expected in the SNAPSHOT version. Thanks!

**Comment by MarcLFJ** [comment]
@drewhamilton Do you have a snippet of a working example using `fontMap`?

**Comment by MarcLFJ** [comment]
Thanks! 🙌

**Comment by drewhamilton** [comment]
@gpeal Is there a planned date for cutting a release with this?

**Comment by gpeal** [comment]
@drewhamilton @MarcLFJ  Yes, the release was held up because Airbnb stopped funding my Lottie work (which is entirely done on nights and weekends) through Open Collective and I was unable to reach them (despite trying) for an extended period of time. I was finally able to get a response this week and we have, at least, a short term plan that works for both of us so I'm going to wrap up this release and publish it soon.
