### ISSUE TITLE
Render Graph for Lottie Compose 

### ISSUE THREAD

**Issue by eric-ampire** [airbnb/lottie-android#2120]
Hey folks, what's the equivalent of `LottieAnimationView.performanceTracker` in Jetpack Compose  in order to be able to display the render graph ?

![Screenshot_20220822-093221_Lottie.jpg](https://user-images.githubusercontent.com/32017617/185865064-601903bd-7f0e-4a2d-b60c-3b7c4e2a0baa.jpg)

**Comment by gpeal** [comment]
PerformanceTracker is available directly from LottieComposition. I may not recreate the graph but you can access the same data like this:
```
    @Composable
    fun Content() {
        val composition by rememberLottieComposition(LottieCompositionSpec.RawRes(R.raw.heart))
        composition?.setPerformanceTrackingEnabled(true)
        val state = animateLottieCompositionAsState(composition, iterations = LottieConstants.IterateForever)
        LaunchedEffect(state.iteration) {
            if (composition?.performanceTracker == null) {
                return@LaunchedEffect
            }
            composition?.performanceTracker?.logRenderTimes()
        }
        LottieAnimation(composition, { state.progress })
    }
```
