### ISSUE TITLE
A double value for layer "w" property causes a JsonDataException

### ISSUE THREAD

**Issue by jasonctoms** [airbnb/lottie-android#2121]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Describe the bug**
I have an animation that has base64 images with rounded corners.  Here is what the animation should look like: https://app.lottiefiles.com/share/5d20e06b-8f34-4009-8643-231ee173c447. It displays fine on LottieFiles and in iOS, but on Android I get a few `JsonDataExceptions` always for the same field.

In `LayerParser.java` on line 239 the parser only accepts an int, but in my animation (json attached) these fields are floating point values.  I was going to attempt a PR, but the `preCompWidth` is eventually used in a `Rect()` which needs an integer, and I am not familiar enough with the Lottie rendering pipeline to think of a good solution...
[problem_animation.json.zip](https://github.com/airbnb/lottie-android/files/9436147/problem_animation.json.zip)

When I round these values to integers, the images in my animation appear as below, in the screenshot section.

**What version of Lottie did you test this on?**
 5.2.0 and 5.2.1-SNAPSHOT (lottie-compose)

**What version of Android did you test this on?**
Android 13 Emulator
Compose 1.2.1

**Steps To Reproduce**

1. Try to load composition of attached json file
2. Get error `Error is com.airbnb.lottie.parser.moshi.JsonDataException: Expected an int but was 25.7358 at path $.assets[9].layers[0].w`

**Screenshots**
<img width="206" alt="Screen Shot 2022-08-26 at 22 09 22" src="https://user-images.githubusercontent.com/17356172/186983549-2754bd9d-d02a-4770-8e87-80ed7a6da9ab.png">

**Comment by jasonctoms** [comment]
After trying the animation from my issue with 5.2.1-SNAPSHOT, the error is fixed!  But it still renders like the screenshot I attached, and not like on lottiefiles and iOS

**Comment by jasonctoms** [comment]
Something seems to have fixed the bug with rounded corners very recently, possibly #2165?

**Comment by gpeal** [comment]
@jasonctoms Perfect, happy to hear that!
