### ISSUE TITLE
Content is always in center, how to change the LottieAnimationView gravity?

### ISSUE THREAD

**Issue by ArcherEmiya05** [airbnb/lottie-android#2122]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Describe the bug**
Content is always display on center, how to change the gravity?

**What version of Lottie did you test this on?**
5.2.0

**What version of Android did you test this on?**
Android 21

**Steps To Reproduce**

1. Add Lottie SDK for Android
2. Use this [asset](https://github.com/airbnb/lottie-android/files/9437165/lower_bg.zip)
3. Add it to XML layout
```
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.airbnb.lottie.LottieAnimationView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:lottie_rawRes="@raw/lower_bg"
        app:lottie_autoPlay="true"
        app:lottie_loop="true" />

</FrameLayout>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/38008900/187010768-de7664c0-f4c1-4968-9401-6e3aff70b0d9.png)

**Comment by gpeal** [comment]
I was able to achieve what you're looking for with
```
    <com.airbnb.lottie.LottieAnimationView
        android:id="@+id/animation_view"
        android:layout_width="match_parent"
        android:layout_height="300dp"
        android:scaleType="fitEnd"
        android:layout_gravity="bottom"
        app:lottie_rawRes="@raw/lower_bg"
        app:lottie_autoPlay="true"
        app:lottie_loop="true" />
```
