### ISSUE TITLE
vivo 8.1，lottie 5.2.0，SIGSEGV(SEGV_MAPERR)   libskia.so

### ISSUE THREAD

**Issue by LiamU** [airbnb/lottie-android#2123]
lottie version ：5.2.0
device model：vivo
api level：27（8.1）

#00 pc 00000000002687f0 /system/lib64/libskia.so (SkTHashTable<SkTHashMap<sk_sp<SkImage>, sk_sp<SkImage>, SkGoodHash>::Pair, sk_sp<SkImage>, SkTHashMap<sk_sp<SkImage>, sk_sp<SkImage>, SkGoodHash>::Pair>::resize(int)+172) (BuildId: 4052163cb64a0718b4eac7fddd756a65)
#01 pc 0000000000268638 /system/lib64/libskia.so (SkTHashMap<sk_sp<SkImage>, sk_sp<SkImage>, SkGoodHash>::set(sk_sp<SkImage>, sk_sp<SkImage>)+100) (BuildId: 4052163cb64a0718b4eac7fddd756a65)
#02 pc 0000000000267474 /system/lib64/libskia.so (sk_sp<SkImage> SkColorSpaceXformer::cachedApply<SkImage>(SkImage const*, SkTHashMap<sk_sp<SkImage>, sk_sp<SkImage>, SkGoodHash>*, sk_sp<SkImage> (*)(SkImage const*, SkColorSpaceXformer*))+288) (BuildId: 4052163cb64a0718b4eac7fddd756a65)
#03 pc 00000000002672d0 /system/lib64/libskia.so (SkColorSpaceXformer::apply(SkImage const*)+40) (BuildId: 4052163cb64a0718b4eac7fddd756a65)
#04 pc 0000000000263d10 /system/lib64/libskia.so (SkColorSpaceXformCanvas::onDrawImageRect(SkImage const*, SkRect const*, SkRect const&, SkPaint const*, SkCanvas::SrcRectConstraint)+80) (BuildId: 4052163cb64a0718b4eac7fddd756a65)
#05 pc 00000000000b2d30 /system/lib64/libhwui.so (android::SkiaCanvas::drawBitmap(android::Bitmap&, float, float, float, float, float, float, float, float, SkPaint const*)+92) (BuildId: 37d3667bcb4c4ec7c519c49b044afde5)
#06 pc 00000000001273f0 /system/lib64/libandroid_runtime.so (android::CanvasJNI::drawBitmapRect(_JNIEnv*, _jobject*, long, _jobject*, float, float, float, float, float, float, float, float, long, int, int)+284) (BuildId: a68d109aefdd1df629a8ca7e52280fae)
#07 pc 0000000000b59b2c /system/framework/arm64/boot-framework.oat (android.graphics.BaseCanvas.nDrawBitmap+268) (BuildId: 741c776e0c6c1ed368aad52a8c4210e4)
#08 pc 0000000000b5bd3c /system/framework/arm64/boot-framework.oat (android.graphics.BaseCanvas.drawBitmap+524) (BuildId: 741c776e0c6c1ed368aad52a8c4210e4)
#09 pc 0000000000113940 /dev/ashmem/dalvik-jit-code-cache (deleted)
at android.graphics.BaseCanvas.nDrawBitmap(Native method)
at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:136)
at android.graphics.Canvas.drawBitmap(Canvas.java:1434)
at com.airbnb.lottie.model.layer.c.b(ImageLayer.java:57)
at com.airbnb.lottie.model.layer.a.a(BaseLayer.java:250)
at com.airbnb.lottie.model.layer.b.b(CompositionLayer.java:128)
at com.airbnb.lottie.model.layer.a.a(BaseLayer.java:250)
at com.airbnb.lottie.model.layer.b.b(CompositionLayer.java:128)
at com.airbnb.lottie.model.layer.a.a(BaseLayer.java:250)
at com.airbnb.lottie.LottieDrawable.a(LottieDrawable.java:1418)
at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:506)
at android.widget.ImageView.onDraw(ImageView.java:1370)

setRenderMode(RenderMode.SOFTWARE) has been called,
also called setSafeMode(true)

Thanks.

**Comment by LiamU** [comment]
More information

signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
Cause: null pointer dereference
x0 0000007282a26ec8 x1 0000000000000000 x2 0000007ff0e6be88 x3 0000000000000270
x4 00000072660240a0 x5 0000000000000000 x6 000000732ad21cc0 x7 0000000000000831
x8 0000000000000000 x9 fa7080bebe47c73e x10 00000072aa60d7c0 x11 0000000000000000
x12 00000072aa60d7c8 x13 0000000000000004 x14 00000000e6546b64 x15 0000000000000000
x16 000000732c3abcb0 x17 000000732c348900 x18 000000001e702e12 x19 000000724656d740
x20 000000732feb4a40 x21 0000000000000004 x22 0000000000000010 x23 0000000000000001
x24 000000732feb4a40 x25 0000007ff0e6c088 x26 0000007282a26c90 x27 000000732feb4a40
x28 000000006fb17fd0 x29 0000007ff0e6be30
lr 000000732ad267b0 sp 0000007ff0e6bdf0 pc 000000732ad267f0 pst 0000000020000000

backtrace:
#00 pc 00000000002687f0 /system/lib64/libskia.so (SkTHashTable<SkTHashMap<sk_sp<SkImage>, sk_sp<SkImage>, SkGoodHash>::Pair, sk_sp<SkImage>, SkTHashMap<sk_sp<SkImage>, sk_sp<SkImage>, SkGoodHash>::Pair>::resize(int)+172) (BuildId: 4052163cb64a0718b4eac7fddd756a65)
#01 pc 0000000000268638 /system/lib64/libskia.so (SkTHashMap<sk_sp<SkImage>, sk_sp<SkImage>, SkGoodHash>::set(sk_sp<SkImage>, sk_sp<SkImage>)+100) (BuildId: 4052163cb64a0718b4eac7fddd756a65)
#02 pc 0000000000267474 /system/lib64/libskia.so (sk_sp<SkImage> SkColorSpaceXformer::cachedApply<SkImage>(SkImage const*, SkTHashMap<sk_sp<SkImage>, sk_sp<SkImage>, SkGoodHash>*, sk_sp<SkImage> (*)(SkImage const*, SkColorSpaceXformer*))+288) (BuildId: 4052163cb64a0718b4eac7fddd756a65)
#03 pc 00000000002672d0 /system/lib64/libskia.so (SkColorSpaceXformer::apply(SkImage const*)+40) (BuildId: 4052163cb64a0718b4eac7fddd756a65)
#04 pc 0000000000263d10 /system/lib64/libskia.so (SkColorSpaceXformCanvas::onDrawImageRect(SkImage const*, SkRect const*, SkRect const&, SkPaint const*, SkCanvas::SrcRectConstraint)+80) (BuildId: 4052163cb64a0718b4eac7fddd756a65)
#05 pc 00000000000b2d30 /system/lib64/libhwui.so (android::SkiaCanvas::drawBitmap(android::Bitmap&, float, float, float, float, float, float, float, float, SkPaint const*)+92) (BuildId: 37d3667bcb4c4ec7c519c49b044afde5)
#06 pc 00000000001273f0 /system/lib64/libandroid_runtime.so (android::CanvasJNI::drawBitmapRect(_JNIEnv*, _jobject*, long, _jobject*, float, float, float, float, float, float, float, float, long, int, int)+284) (BuildId: a68d109aefdd1df629a8ca7e52280fae)
#07 pc 0000000000b59b2c /system/framework/arm64/boot-framework.oat (android.graphics.BaseCanvas.nDrawBitmap+268) (BuildId: 741c776e0c6c1ed368aad52a8c4210e4)
#08 pc 0000000000b5bd3c /system/framework/arm64/boot-framework.oat (android.graphics.BaseCanvas.drawBitmap+524) (BuildId: 741c776e0c6c1ed368aad52a8c4210e4)
#09 pc 0000000000113940 /dev/ashmem/dalvik-jit-code-cache (deleted)

**Comment by gpeal** [comment]
Is this crash only on Vivo 8.1 or does it happen on any other devices? Does it happen 100% of the time or only sometimes?

**Comment by LiamU** [comment]
> Is this crash only on Vivo 8.1 or does it happen on any other devices? Does it happen 100% of the time or only sometimes?

Yes, it only happens on vivo 8.1, it happens sometimes, not always. thanks.

**Comment by gpeal** [comment]
I would add a condition to use render mode software specifically for these devices for this animation. It sounds like a vendor bug that I'll unlikely be able to work around.

**Comment by FioneraGH** [comment]
Same here. Vivo 8.1 only

**Comment by gpeal** [comment]
If you can attach your animation and a specific model, I can try and repro but my recommendation will remain to be changing the render mode to software for those specific devices.

**Comment by gpeal** [comment]
I'm going to close this with the recommendation to use software rendering for animations/devices that are affected here.
