### ISSUE TITLE
Failed to play JSON correctly on Android 12

### ISSUE THREAD

**Issue by PinLeung** [airbnb/lottie-android#2124]
**Describe the bug**

I tried to load the JSON image on the Android 12 mobile phone, but only the first frame of the image was loaded, and it was not automatically played. The same code does not appear in versions below Android 12.

**What version of Lottie did you test this on?**
v5.2.0

**What version of Android did you test this on?**
Many Android 12 mobile phones including Xiaomi、Huawei、vivo and oppo。

**Steps To Reproduce**

Load any JSON animation on Android 12

**Comment by PinLeung** [comment]
I used issue-repro-comoose in the demo,copy loading.json from sample-compose to issue-repro-compose。Failed to play。

**Comment by gpeal** [comment]
You likely had battery saver on or set the system animation scale to 0.
