### ISSUE TITLE
Run lottieAnimation in Presentation, the animation flickering

### ISSUE THREAD

**Issue by Leizxy** [airbnb/lottie-android#2126]
I use a lottie resource in Presentation on Android T, the animation flickering. 
But I use it in Activity, it runs normally. And I use it in Presentation on Android R, it runs normally too.
Is there any difference on Android R and T?

**Comment by gpeal** [comment]
I haven't been able to reproduce this behavior in T. If you are able to produce a reproduction, I'll take a look.
