### ISSUE TITLE
Masks and strokes

### ISSUE THREAD

**Issue by podrivo** [airbnb/lottie-android#213]
Hello,

I've made some small isolated tests to understand the limits and I had some issues with strokes and masks. I'm almost sure the problem comes from "Create shapes from vector layer", but I'm not sure why or how to fix it.

I'm using version 1.5.3.
And this is my workflow:

- Build shapes in Illustrator
- Import .ai file into After Effects
- "Create shapes from vector layer"
- Animate them
- Bodymovin JSON -> Lottie

Here's a ZIP containing: .aep, .ai, .html, .json and .mp4: [lottie.zip](https://github.com/airbnb/lottie-android/files/859689/lottie.zip)

Here's the expected:
<img width="660" alt="screen shot 2017-03-21 at 8 07 00 pm" src="https://cloud.githubusercontent.com/assets/546221/24174893/0f05e060-0e72-11e7-8ae8-ffcaba0be9ad.png">

Bodymovin's version:
<img width="574" alt="screen shot 2017-03-21 at 8 08 33 pm" src="https://cloud.githubusercontent.com/assets/546221/24174915/369e4626-0e72-11e7-9632-1113da3de16d.png">

Lottie's version:
<img width="411" alt="screen shot 2017-03-21 at 8 09 09 pm" src="https://cloud.githubusercontent.com/assets/546221/24174929/4f100f82-0e72-11e7-99fe-eb42ee75132c.png">

**Comment by gpeal** [comment]
Well here's what they look like in 2.0.0-beta2 :)
![image](https://cloud.githubusercontent.com/assets/1307745/24185988/500896c2-0e93-11e7-8170-a0c4faba2cd3.png)
Enjoy!

And what they look like with merge paths enabled (KitKat and above only):
![image](https://cloud.githubusercontent.com/assets/1307745/24186012/6dd8cb9a-0e93-11e7-975f-982e4ba0dbc4.png)

**Comment by podrivo** [comment]
Marvelous! (:
