### ISSUE TITLE
On Redmi k30 Pro, json animation does not work properly

### ISSUE THREAD

**Issue by TimberBug** [airbnb/lottie-android#2133]
**On the Redmi k30 Pro device, the json animation does not work properly. After calling playAnimation(), the onAnimationEnd() is directly called back in the animation listener addAnimatorListener, causing the animation to not execute normally, but it works normally on other devices**

**Lottie version: 5.2.0**

**The contents of the json animation file are as follows**
{"v":"5.9.0","fr":60,"ip":0,"op":97,"w":1000,"h":1000,"nm":"Springy Blocks Loader","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":3,"nm":"Jump Null","parent":2,"sr":1,"ks":{"o":{"a":0,"k":0,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"s":true,"x":{"a":0,"k":38.1,"ix":3},"y":{"a":1,"k":[{"i":{"x":[0.46],"y":[1]},"o":{"x":[0.167],"y":[0.167]},"t":21,"s":[-90]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.54],"y":[0]},"t":35,"s":[-114.8]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":45,"s":[-90]},{"i":{"x":[0.46],"y":[1]},"o":{"x":[0.167],"y":[0.167]},"t":53,"s":[-90]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.54],"y":[0]},"t":61,"s":[-115.6]},{"t":73,"s":[-90]}],"ix":4}},"a":{"a":0,"k":[0,0,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"ip":0,"op":97,"st":0,"bm":0},{"ddd":0,"ind":2,"ty":3,"nm":"Position","sr":1,"ks":{"o":{"a":0,"k":0,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"s":true,"x":{"a":1,"k":[{"i":{"x":[0.24],"y":[1]},"o":{"x":[0.096],"y":[0.226]},"t":0,"s":[561.9]},{"t":40,"s":[461.9]}],"ix":3},"y":{"a":0,"k":590,"ix":4}},"a":{"a":0,"k":[0,0,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"ip":0,"op":97,"st":0,"bm":0},{"ddd":0,"ind":3,"ty":3,"nm":"Rotate_03","parent":1,"sr":1,"ks":{"o":{"a":0,"k":0,"ix":11},"r":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.67],"y":[0]},"t":72,"s":[0]},{"t":97,"s":[180]}],"ix":10},"p":{"a":0,"k":[149.9,-50,0],"ix":2,"l":2},"a":{"a":0,"k":[0,0,0],"ix":1,"l":2},"s":{"a":0,"k":[50,50,100],"ix":6,"l":2}},"ao":0,"ip":0,"op":97,"st":0,"bm":0},{"ddd":0,"ind":4,"ty":3,"nm":"Rotate_02","parent":3,"sr":1,"ks":{"o":{"a":0,"k":0,"ix":11},"r":{"a":1,"k":[{"i":{"x":[0.775],"y":[0.585]},"o":{"x":[0.468],"y":[0]},"t":45,"s":[0]},{"t":70,"s":[90]}],"ix":10},"p":{"a":0,"k":[-200,0,0],"ix":2,"l":2},"a":{"a":0,"k":[0,0,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"ip":0,"op":97,"st":0,"bm":0},{"ddd":0,"ind":5,"ty":3,"nm":"Rotate_01","parent":4,"sr":1,"ks":{"o":{"a":0,"k":0,"ix":11},"r":{"a":1,"k":[{"i":{"x":[0.809],"y":[0.637]},"o":{"x":[0.494],"y":[0]},"t":18,"s":[0]},{"t":43,"s":[90]}],"ix":10},"p":{"a":0,"k":[-200,0,0],"ix":2,"l":2},"a":{"a":0,"k":[0,0,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"ip":0,"op":97,"st":0,"bm":0},{"ddd":0,"ind":6,"ty":4,"nm":"Bouncy Square","parent":5,"sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":0,"s":[0]},{"t":16,"s":[180]}],"ix":10},"p":{"s":true,"x":{"a":1,"k":[{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":41,"s":[-200]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":46,"s":[-107.3]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":55,"s":[-210.1]},{"t":61,"s":[-200]}],"ix":3},"y":{"a":1,"k":[{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":15,"s":[0]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.468],"y":[0]},"t":19,"s":[92.9]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.167],"y":[0]},"t":28,"s":[-2.3]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.167],"y":[0]},"t":34,"s":[-2.3]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":68,"s":[-2.3]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":73,"s":[-96]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":82,"s":[10.9]},{"t":88,"s":[-2.3]}],"ix":4}},"a":{"a":0,"k":[50,-50,0],"ix":1,"l":2},"s":{"a":0,"k":[200,200,100],"ix":6,"l":2}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":1,"k":[{"i":{"x":0.15,"y":1},"o":{"x":0.333,"y":0},"t":0,"s":[{"i":[[0,0],[0,-16.833],[0,0],[17.3,0],[0,0],[0,18.833],[0,0],[-17.367,0]],"o":[[0,0],[0,16.5],[0,0],[-16.033,0],[0,0],[0,-14.5],[0,0],[15.967,0]],"v":[[50,-50],[50,0.5],[50,50],[-1.9,50],[-50,50],[-50,-6.5],[-50,-50],[2.1,-50]],"c":true}]},{"i":{"x":0.21,"y":1},"o":{"x":0.57,"y":0},"t":15,"s":[{"i":[[0,0],[-5.202,-16.957],[0,0],[13.429,-7.41],[0,0],[10.237,37.488],[0,0],[-15.397,0]],"o":[[0,0],[5.365,17.487],[0,0],[-12.446,6.868],[0,0],[-8.705,-31.879],[0,0],[14.156,0]],"v":[[50,-50],[52.997,-8.403],[75.679,26.121],[30.144,51.248],[-11.875,74.435],[-45.338,13.256],[-50,-50],[2.219,-50]],"c":true}]},{"i":{"x":0.375,"y":1},"o":{"x":0.446,"y":0},"t":19,"s":[{"i":[[0,0],[3.675,-26.899],[0,0],[17.095,2.634],[0,0],[-2.872,18.129],[0,0],[-17.367,0]],"o":[[0,0],[-2.177,15.933],[0,0],[-15.844,-2.441],[0,0],[2.211,-13.958],[0,0],[15.967,0]],"v":[[50,-50],[56.842,0.714],[39.562,38.419],[-11.724,30.518],[-59.255,23.194],[-64.484,-15.533],[-50,-50],[2.1,-50]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.333,"y":0},"t":34,"s":[{"i":[[0,0],[-0.684,-17.777],[0,0],[16.044,-0.801],[0,0],[0.765,19.889],[0,0],[-16.121,0]],"o":[[0,0],[0.671,17.425],[0,0],[-14.869,0.742],[0,0],[-0.589,-15.313],[0,0],[14.822,0]],"v":[[46.484,-50],[46.764,0.483],[48.776,52.759],[0.644,55.161],[-43.964,57.387],[-46.26,-2.282],[-46.346,-50],[2.018,-50]],"c":true}]},{"i":{"x":0.299,"y":1},"o":{"x":0.167,"y":0.167},"t":42,"s":[{"i":[[0,0],[-4.905,-16.103],[0,0],[24.078,-2.864],[0,0],[-0.016,18.833],[0,0],[-17.251,1.999]],"o":[[0,0],[4.808,15.784],[0,0],[-32,3.807],[0,0],[0.013,-14.5],[0,0],[21.68,-2.512]],"v":[[30.903,-65.642],[45.668,-17.311],[60.008,29.917],[7.615,46.507],[-50.086,49.807],[-49.993,-6.551],[-50,-50],[-8.782,-52.07]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.67,"y":0},"t":46,"s":[{"i":[[0,0],[1.938,-17.271],[0,0],[16.214,2.043],[0,0],[0,18.833],[0,0],[-22.057,-2.365]],"o":[[0,0],[-1.9,16.929],[0,0],[-15.027,-1.893],[0,0],[0,-14.5],[0,0],[19.064,2.044]],"v":[[38.697,-43.747],[32.882,8.065],[27.182,58.851],[-16.341,59.962],[-50,50],[-50,-6.5],[-50,-50],[-3.553,-58.91]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.333,"y":0},"t":57,"s":[{"i":[[0,0],[-1.342,-16.385],[0,0],[18.029,0],[0,0],[0,18.386],[0,0],[-18.098,0]],"o":[[0,0],[1.496,18.269],[0,0],[-16.709,0],[0,0],[0,-14.156],[0,0],[16.639,0]],"v":[[54.214,-48.795],[56.077,2.194],[59.712,48.744],[-1.364,50.274],[-50,48.83],[-50,-6.328],[-50,-48.795],[2.995,-47.906]],"c":true}]},{"i":{"x":0.299,"y":1},"o":{"x":0.167,"y":0.167},"t":69,"s":[{"i":[[0,0],[-7.388,-32.006],[0,0],[15.15,0],[0,0],[3.5,18.735],[0,0],[-14.224,5.381]],"o":[[0,0],[7.676,33.254],[0,0],[-14.04,0],[0,0],[-3.52,-18.841],[0,0],[13.077,-4.947]],"v":[[23.186,-65.006],[44.108,-10.533],[50,50],[-2.018,50],[-50,50],[-53.565,10.289],[-70.345,-29.623],[-21.494,-48.103]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":73,"s":[{"i":[[0,0],[3.951,-18.969],[0,0],[17.3,0],[0,0],[-2.102,19.432],[0,0],[-17.073,-2.922]],"o":[[0,0],[-3.829,18.384],[0,0],[-16.033,0],[0,0],[2.572,-23.776],[0,0],[15.696,2.687]],"v":[[58.744,-21.388],[62.923,18.69],[50,50],[-1.9,50],[-50,50],[-54.54,1.842],[-39.563,-38.214],[11.655,-29.448]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.701,"y":0},"t":82,"s":[{"i":[[0,0],[0,-16.833],[0,0],[17.3,0],[0,0],[0,18.833],[0,0],[-17.367,0]],"o":[[0,0],[0,16.5],[0,0],[-16.033,0],[0,0],[0,-14.5],[0,0],[15.967,0]],"v":[[50,-50],[50,0.5],[50,50],[-1.9,50],[-50,50],[-50,-6.5],[-50,-50],[2.1,-50]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":92,"s":[{"i":[[0,0],[0,-11.366],[0,0],[11.44,-2.361],[0,0],[5.965,11.23],[0,0],[-38.872,11.586]],"o":[[0,0],[0,11.141],[0,0],[-24.435,5.042],[0,0],[-4.592,-8.646],[0,0],[30.857,-9.197]],"v":[[50,-50],[50,0.581],[50,50],[15.694,53.688],[-24.95,73.914],[-49.984,25.634],[-69.902,-11.867],[-13.932,-44.403]],"c":true}]},{"i":{"x":0.04,"y":1},"o":{"x":0.167,"y":0.167},"t":97,"s":[{"i":[[0,0],[0,-16.917],[0,0],[17.616,0],[0,0],[0,19.898],[0,0],[-17.716,0]],"o":[[0,0],[0,16.417],[0,0],[-15.717,0],[0,0],[0,-13.435],[0,0],[15.617,0]],"v":[[50,-50],[50,0.75],[50,50],[-0.349,50],[-50,50],[-49.9,-1.695],[-50,-50],[-0.352,-50]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":1,"y":0},"t":117,"s":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[50,-50],[50,0.75],[50,50],[-214.93,50],[-451.299,50],[-451.299,-9.695],[-451.299,-50],[-184.868,-50]],"c":true}]},{"t":144,"s":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[50,-50],[50,0.75],[50,50],[-2.849,50],[-50,50],[-50,-9.695],[-50,-50],[3.148,-50]],"c":true}]}],"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[0.809747912837,0.28679968142,1,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[89.9,89.9],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"Rectangle 1","np":2,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":97,"st":0,"bm":0},{"ddd":0,"ind":7,"ty":4,"nm":"Static Square_03","parent":2,"sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"s":true,"x":{"a":0,"k":188,"ix":3},"y":{"a":1,"k":[{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.167],"y":[0.167]},"t":0,"s":[-37.915]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.167],"y":[0]},"t":4,"s":[-40]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":69,"s":[-40]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":73,"s":[-10.7]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":82,"s":[-50]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":91,"s":[-35]},{"t":100,"s":[-40]}],"ix":4}},"a":{"a":0,"k":[50,50,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":1,"k":[{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":69,"s":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[45,-45],[45,-5.117],[45,45],[-45,45],[-45,-8.498],[-45,-45]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":73,"s":[{"i":[[0,0],[0,-18],[0,0],[0,0],[0,18.5],[0,0]],"o":[[0,0],[0,18],[0,0],[0,0],[0,-18.5],[0,0]],"v":[[45.107,-34],[50.558,3.5],[45,45],[-45,45],[-52.44,3.5],[-44.893,-34]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":82,"s":[{"i":[[0,0],[0,-13.655],[0,0],[0,0],[0,18.317],[0,0]],"o":[[0,0],[0,17.16],[0,0],[0,0],[0,-12.498],[0,0]],"v":[[43.402,-49.5],[40.902,-5.452],[43.308,45],[-43.304,45],[-40.899,-4.816],[-43.21,-49.5]],"c":true}]},{"t":91,"s":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[45,-45],[45,-5.117],[45,45],[-45,45],[-45,-8.498],[-45,-45]],"c":true}]}],"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[0.318425496419,0,1,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"Rectangle 1","np":2,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":97,"st":0,"bm":0},{"ddd":0,"ind":8,"ty":4,"nm":"Static Square_02","parent":2,"sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"s":true,"x":{"a":0,"k":-12,"ix":3},"y":{"a":1,"k":[{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":42,"s":[-90]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":46,"s":[-60.7]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":55,"s":[-100]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":64,"s":[-85]},{"t":73,"s":[-90]}],"ix":4}},"a":{"a":0,"k":[-50,0,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":1,"k":[{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":42,"s":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[45,-45],[45,-5.117],[45,45],[-45,45],[-45,-8.498],[-45,-45]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":46,"s":[{"i":[[0,0],[0,-18],[0,0],[0,0],[0,18.5],[0,0]],"o":[[0,0],[0,18],[0,0],[0,0],[0,-18.5],[0,0]],"v":[[45.107,-34],[50.558,3.5],[45,45],[-45,45],[-52.44,3.5],[-44.893,-34]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":55,"s":[{"i":[[0,0],[0,-13.655],[0,0],[0,0],[0,18.317],[0,0]],"o":[[0,0],[0,17.16],[0,0],[0,0],[0,-12.498],[0,0]],"v":[[43.402,-49.5],[40.902,-5.452],[43.308,45],[-43.304,45],[-40.899,-4.816],[-43.21,-49.5]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":64,"s":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[45,-45],[45,-5.117],[45,45],[-45,45],[-45,-8.498],[-45,-45]],"c":true}]},{"t":73,"s":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[45,-45],[45,-5.117],[45,45],[-45,45],[-45,-8.498],[-45,-45]],"c":true}]}],"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[0.440642293294,0,1,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"Rectangle 1","np":2,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"ty":"rc","d":1,"s":{"a":0,"k":[95,95],"ix":2},"p":{"a":0,"k":[0,0],"ix":3},"r":{"a":0,"k":0,"ix":4},"nm":"Rectangle Path 1","mn":"ADBE Vector Shape - Rect","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"Group 1","np":1,"cix":2,"bm":0,"ix":2,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":97,"st":0,"bm":0},{"ddd":0,"ind":9,"ty":4,"nm":"Static Square_01","parent":2,"sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"s":true,"x":{"a":0,"k":-112,"ix":3},"y":{"a":1,"k":[{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":15,"s":[-90]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":19,"s":[-60.7]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":28,"s":[-100]},{"i":{"x":[0.667],"y":[1]},"o":{"x":[0.333],"y":[0]},"t":37,"s":[-85]},{"t":46,"s":[-90]}],"ix":4}},"a":{"a":0,"k":[-50,0,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":1,"k":[{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":15,"s":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[45,-45],[45,-5.117],[45,45],[-45,45],[-45,-8.498],[-45,-45]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":19,"s":[{"i":[[0,0],[0,-18],[0,0],[0,0],[0,18.5],[0,0]],"o":[[0,0],[0,18],[0,0],[0,0],[0,-18.5],[0,0]],"v":[[45.107,-34],[50.558,3.5],[45,45],[-45,45],[-52.44,3.5],[-44.893,-34]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":28,"s":[{"i":[[0,0],[0,-13.655],[0,0],[0,0],[0,18.317],[0,0]],"o":[[0,0],[0,17.16],[0,0],[0,0],[0,-12.498],[0,0]],"v":[[43.402,-49.5],[40.902,-5.452],[43.308,45],[-43.304,45],[-40.899,-4.816],[-43.21,-49.5]],"c":true}]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"t":37,"s":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[45,-45],[45,-5.117],[45,45],[-45,45],[-45,-8.498],[-45,-45]],"c":true}]},{"t":46,"s":[{"i":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[45,-45],[45,-5.117],[45,45],[-45,45],[-45,-8.498],[-45,-45]],"c":true}]}],"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[0.58212890625,0,1,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"Rectangle 1","np":2,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":97,"st":0,"bm":0}],"markers":[]}

**Comment by gpeal** [comment]
Are animations disabled? Sometimes this also happens if battery saver is on.

**Comment by gpeal** [comment]
It plays fine on my emulator. Closing per my comment above.
