### ISSUE TITLE
Text not rendering correctly in Hindi,and text did not fit center

### ISSUE THREAD

**Issue by ZimmerZhou** [airbnb/lottie-android#2135]
why
<img width="140" alt="image" src="https://user-images.githubusercontent.com/19164769/192984896-483fce61-edfa-4683-a002-974a0523ccdf.png">
became
<img width="100" alt="image" src="https://user-images.githubusercontent.com/19164769/192985089-cee31af7-1899-4604-8b83-5b36074b55f3.png">

**Comment by gpeal** [comment]
This will probably be fixed by #2162 but without a sample animation, I won't be able to verify.
