### ISSUE TITLE
NullPointerException Attempt to invoke interface method 'int java.util.List.size()' on a null object reference

### ISSUE THREAD

**Issue by dhirajuchil-dunzo** [airbnb/lottie-android#2140]
**Describe the bug**
We use a URL to display Lottie. The URL seems to work most of the time but It gives NullPointerException sometimes
here are the logs:

Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'int java.util.List.size()' on a null object reference

com.airbnb.lottie.model.layer.CompositionLayer.<init> (CompositionLayer.java:56)
com.airbnb.lottie.model.layer.BaseLayer.forModel (BaseLayer.java:61)
com.airbnb.lottie.model.layer.CompositionLayer.<init> (CompositionLayer.java:58)
com.airbnb.lottie.LottieDrawable.buildCompositionLayer (LottieDrawable.java:433)
com.airbnb.lottie.LottieDrawable.setComposition (LottieDrawable.java:298)
com.airbnb.lottie.LottieAnimationView.setComposition (LottieAnimationView.java:550)
com.airbnb.lottie.LottieAnimationView$$InternalSyntheticLambda$0$594cc63ff1b406d16540545a760588289c318f036d2901c2c872eaa5130e170a$0.onResult (LottieAnimationView.java:4)
com.airbnb.lottie.LottieTask.notifySuccessListeners (LottieTask.java:148)
com.airbnb.lottie.LottieTask.lambda$notifyListeners$0 (LottieTask.java:136)
com.airbnb.lottie.LottieTask.$r8$lambda$Rpnx63cLRLCF9DbgjiFM7rp0Vik (LottieTask.java)
com.airbnb.lottie.LottieTask$$InternalSyntheticLambda$1$96a344ffc28df59816d87e2ec1f248fd91043cf6d7a61d932bfe48316715ddf9$0.run (LottieTask.java:2)
android.os.Handler.handleCallback (Handler.java:942)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loopOnce (Looper.java:201)
android.os.Looper.loop (Looper.java:288)
android.app.ActivityThread.main (ActivityThread.java:7898)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:936)

**What version of Lottie did you test this on?**
5.2.0

**What version of Android did you test this on?**
The issue seems to occur on Android 10,11,12, and 13

**Steps To Reproduce**

Was unable to reproduce the issue. Found crash in Crashlytics

Any input will be appreciated.

**Comment by gpeal** [comment]
Can you attach the animation that isn't working here? From this crash, it seems as if the referenced precomp layers were removed from the json file.

I'm going to close this as it's _likely_ an issue with hand-modified json but feel free to reopen this if you have more clear reproduction steps.
