### ISSUE TITLE
Effective way to draw many LottieDrawables on only one Canvas

### ISSUE THREAD

**Issue by andj207** [airbnb/lottie-android#2142]
I'm trying to draw multiple LottieDrawable on the same canvas I got but don't know how.
For example, I've got a Canvas and want to draw lottieDrawableBg, lottieDrawablePersonA, lottieDrawablePersonB, lottieDrawablePersonC, lottieDrawableDog, lottieDrawableTree, lottieDrawableSun, lottieDrawableCloud.... at once on the canvas.

I can do with a single one lottie drawable as below:

    //Create lottie drawable and set things up
    lottieDrawable.enableMergePathsForKitKatAndAbove(true)
    lottieDrawable.repeatCount = INFINITE
    lottieDrawable.addAnimatorUpdateListener {
        drawFrame()
    }
    lottieDrawable.composition = LottieCompositionFactory.fromRawResSync(context, layoutId).value

     //Draw frame function
     private fun drawFrame()
                val holder: SurfaceHolder = surfaceHolder
                var canvas: Canvas? = null

                try {
                    canvas = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                        holder.lockHardwareCanvas()
                    } else {
                        holder.lockCanvas()
                    }
                    if (canvas != null) {
                        val cWidth = canvas.width.toFloat()
                        val cHeight = canvas.height.toFloat()

                        if (backgroundBitmap != null) {
                            backgroundBitmap?.let {
                                canvas.drawBitmap(
                                    it,
                                    null,
                                    RectF(0f, 0f, cWidth, cHeight),
                                    null
                                )
                            }
                        } else {
                            val bgColor: Int = Color.BLACK
                            canvas.drawColor(bgColor)
                        }

                        lottieDrawable.apply {
                            if (cWidth < cHeight) {
                                canvas.translate(0f, (cHeight - cWidth) * 0.5f)
                                val scale = (cWidth / composition.bounds.width())
                                canvas.scale(scale, scale)
                            } else {
                                canvas.translate((cWidth - cHeight) * 0.5f, 0f)
                                val scale = (cHeight / composition.bounds.height())
                                canvas.scale(scale, scale)
                            }
                            draw(canvas)
                        }
                    } else {
                        Timber.e("Lottie Wallpaper Engine drawing frame canvas is null")
                    }
                } catch (e: Throwable) {
                    Timber.e(e)
                } finally {
                    if (canvas != null) {
                        holder.unlockCanvasAndPost(canvas)
                    }
                }
      }

If I do with each one like above, it is ineffective for the canvas to lock and unlock several times I guess.

**Comment by paul726** [comment]
I think you can render all drawables on a Bitmap, and then rendering this bitmap

**Comment by gpeal** [comment]
No need to do anything fancy (like locking). Just create a LottieDrawable and call `draw` with your canvas.
