### ISSUE TITLE
android 12 

### ISSUE THREAD

**Issue by pigpan1314** [airbnb/lottie-android#2146]
I tried to load the JSON image on the Android 12 mobile phone, but only the first frame of the image was loaded, and it was not automatically played. The same code does not appear in versions below Android 12.

v5.2.0

Many Android 12 mobile phones including Xiaomi、Huawei、vivo and oppo。
Load any JSON animation on Android 12

**Comment by gpeal** [comment]
Did you have battery saver on or system animations disabled or anything else that set the animation scale to 0?

**Comment by pigpan1314** [comment]
All settings can be played normally under Android 11.

No special treatment

**Comment by pigpan1314** [comment]
Android demo on github can't play animation on Android 12 normally

**Comment by gpeal** [comment]
I've tried on several Android 12 devices and it's playing fine. Lottie is also use widely so there would have been other reports if this was a blanket issue for Android 12. Are you able to provide something that reproduces this?
