### ISSUE TITLE
App sometimes crashing when loading image from a remote url

### ISSUE THREAD

**Issue by MiriamCordes** [airbnb/lottie-android#2147]
Hi dear Lottie team, 

we are currently implementing Lottie animations with remote images into our app. While testing we noticed that the app sometimes crashes:

> java.lang.IllegalStateException: You must set an images folder before loading an image. Set it with LottieComposition#setImagesFolder or LottieDrawable#setImagesFolder

We are completely aware that we have to tell Lottie where to find images that are bundled in our app but do we also have to specify an image asset folder when loading the images from a remote url?

We tried removing `"u": "images/"` from the Lottie JSON (see further down) as we thought that maybe the crash happened because there was a folder defined in the JSON but no `app:lottie_imageAssetsFolder` attribute in our XML but it didn't make a difference.

The crash is fairly reproducible on a tablet emulator (Pixel C, Android 11) but not on a real device (Pixel 6, Android 13). 

Our code looks like this: 

**XML layout**
```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
   xmlns:app="http://schemas.android.com/apk/res-auto"
   android:layout_height="match_parent"
   android:layout_width="match_parent">

   <com.airbnb.lottie.LottieAnimationView
      android:id="@+id/animationView"
      android:layout_height="match_parent"
      android:layout_width="match_parent"
      android:scaleType="centerCrop"
      app:lottie_autoPlay="true"
      app:lottie_rawRes="@raw/data" />
</FrameLayout>
```

**Loading of remote image**
```
Glide
   .with(this)
   .asBitmap()
   .load(url)
   .into(object : CustomTarget<Bitmap>() {
      override fun onResourceReady(resource: Bitmap, transition: Transition<in Bitmap>?) {
         animationView.addLottieOnCompositionLoadedListener {
            animationView.updateBitmap("image_0", resource)
         }
      }

      override fun onLoadCleared(placeholder: Drawable?) {
      }
   })
```

**Asset definition in Lottie animation JSON**
```
 "assets": [
    {
      "id": "image_0",
      "w": 596,
      "h": 527,
      "u": "images/",
      "p": "https://our-custom-url",
      "e": 0
    }
]
```

Thank you for your help! Cheers!

**Comment by gpeal** [comment]
It seems like you have a race condition between Glide and Lottie. If Lottie loads the animation before Glide (which is possible because Lottie caches animations) then it'll try to render the bitmap before Glide sets it. What I'd recommend is using `LottieCompositionFactory` directly so that you wind up with a LottieComposition instance. You can then set the composition and update the bitmap at the same time to ensure there is no race condition.
