### ISSUE TITLE
Lotties containing bitmaps consume a lot of memory.

### ISSUE THREAD

**Issue by Semedaki** [airbnb/lottie-android#2148]
Hello,
This is sort of a continuation of [this](https://github.com/airbnb/lottie-android/issues/2095) issue.

**The problem:**
I have lottie videos made from png sequences. When the lottie is playing it can consume a lot of memory, which is problematic in low memory devices. 

Is there anything I can do to reduce the memory consumption? I have already tried setCacheComposition(false).

![lottie_ball_example_profiler](https://user-images.githubusercontent.com/107938867/198052020-30ea991b-3584-4238-b295-fe07b6574a17.jpg)

[Here](https://github.com/Semedaki/lottie-android) is the fork with a repro in the issue-repro module.

**Steps To Reproduce:**
1. click "start video"
2. see memory consumption in profiler

**Comment by gpeal** [comment]
Bitmaps use memory. There isn't much you can do about that. Lottie really wasn't designed to play a series of pngs though. Lottie was designed to play vector animations that occasionally have one or a small number of bitmaps.
I would suggest:
1. Making your animation a vector animation
2. Not using Lottie if you can't use 1
3. Taking the memory hit. There isn't much Lottie can do when all of the memory increase you're seeing is the raw bitmaps.

**Comment by b1tb1t** [comment]
After the animation ends, directly set a new empty resource
lottieAnimView.setAnimation(R.raw.empty)
