### ISSUE TITLE
Animation rendering issue on bazier curves once rotated

### ISSUE THREAD

**Issue by StefanoBozzoni** [airbnb/lottie-android#2149]
The animation of a circle with an exclamation mark inside it was working on version 4.21 but not after that, actually version 5.2.0 is still not working. What happens is that the circle surrounding the exlamation mark becomes a rhombus on Android device.

I have digged a little more inside the issue and it seems, but i am not a lottie expert, that when the layer that contains the circle rotates its content by 90 degrees to change the animation starting point,  this rotation have an effect on the bezier curves that form the circle, changing its shape. This doesn't happen on similar animations that doesn't use this rotation. It is only a supposition.

To reproduce the issue just play the icona_ko animation, that i have attacched here, on an android device and you will see the difference with the lottie online player.
I have attacched also a similar animation that instead works correctly, it's name is icona_ko_working.
[animations.zip](https://github.com/airbnb/lottie-android/files/9877290/animations.zip)

**Comment by gpeal** [comment]
I fixed the underlying issue here but FWIW, it was caused because there was a rounded corners modifier that was applied to a shape that didn't actually have any corners to round (the shape itself had rounded corners).

**Comment by StefanoBozzoni** [comment]
thank you so much !

Il giorno lun 14 nov 2022 alle ore 06:52 Gabriel Peal <
***@***.***> ha scritto:

**Comment by oooooo99999** [comment]
> The animation of a circle with an exclamation mark inside it was working on version 4.21 but not after that, actually version 5.2.0 is still not working. What happens is that the circle surrounding the exlamation mark becomes a rhombus on Android device.
> 
> I have digged a little more inside the issue and it seems, but i am not a lottie expert, that when the layer that contains the circle rotates its content by 90 degrees to change the animation starting point,  this rotation have an effect on the bezier curves that form the circle, changing its shape. This doesn't happen on similar animations that doesn't use this rotation. It is only a supposition.
> 
> To reproduce the issue just play the icona_ko animation, that i have attacched here, on an android device and you will see the difference with the lottie online player.
> I have attacched also a similar animation that instead works correctly, it's name is icona_ko_working.
> [animations.zip](https://github.com/airbnb/lottie-android/files/9877290/animations.zip)
> 
> 
>
