### ISSUE TITLE
Animation speed/duration/velocity

### ISSUE THREAD

**Issue by podrivo** [airbnb/lottie-android#215]
Hello, I'm having an issue with the speed/duration/velocity on Android 7.0
It's faster on Android 7.0. It's almost twice as faster.

Here's a video: https://youtu.be/ZUXPNpHvKnA
Android 7 is the right one.

I'm using version 2.0.0-beta2.
ZIP with .aep and .json: [Archive.zip](https://github.com/airbnb/lottie-android/files/861798/Archive.zip)

**Comment by gpeal** [comment]
@podrivo Do you have the animator duration speed modified in developer settings?

**Comment by podrivo** [comment]
@gpeal hmm, no I don't. It's the default settings.

**Comment by gpeal** [comment]
@podrivo That's strange. Lottie just relies on the platform Animator class for timing. The only things that come to mind are that you have an animation duration scale set differently or you are using different animation. I just did a test with 6.0 next to 7.0 and they are the same on my test devices. Nobody else has reported this issue either.

**Comment by podrivo** [comment]
@gpeal Indeed it is. It's the exact same thing for both devices. Just unplugged one and plugged the other. Same code, same json file, same everything.

I'm not familiar with Java nor Android Studio. A friend of mine set everything for me to test the animations. Is there something I could try? Maybe something in the device?

I'll try to find more devices to test.

Here's a screenshot of the code:
![screen shot 2017-03-22 at 6 08 00 pm](https://cloud.githubusercontent.com/assets/546221/24221093/b40d569c-0f2b-11e7-9e53-6092b3dca6f6.png)

**Comment by podrivo** [comment]
I've tested in a different device with Android 7.0 and it works like a charm.
I'll try to dig more about this, but for now it's ok to close the issue.
Thanks! (:

**Comment by podrivo** [comment]
Just in case, the device I detected the error, was a Moto G4 Plus.

**Comment by anujpant08** [comment]
I had the same problem..I just forgot that I changed my animator scale to .5x in developer options!!Worked for me.
