### ISSUE TITLE
Is it possible to retrieve the x,y coordinate of a Lottie animation on Android

### ISSUE THREAD

**Issue by Gwy** [airbnb/lottie-android#2150]
I have 2 lottie animations which I'd like to attach one of the animation to the end of another animation. To do this, I need to know the position of the first animation. Is this possible in Android Lottie? And how can I do that? I tried following https://github.com/airbnb/lottie-android/issues/879 but it didn't work for me.

**Comment by gpeal** [comment]
I don't have plans to add this API directly but you could do something like this
1. Create a LottieDrawable instance and set the same LottieComposition on it.
2. Set a value callback like I mentioned in the linked PR
3. Create a Canvas object that you don't plan on doing anything with and call LottieDrawable's onDraw with it
4. Your callback will be called and even though the animation will be "rendered" to your canvas, you don't need to draw it anywhere.
