### ISSUE TITLE
How does setScale() convert to Canvas?

### ISSUE THREAD

**Issue by liuliu-imemachine** [airbnb/lottie-android#2153]
![Uploading image.png…]()
How does setScale() convert to Canvas?

**Comment by liuliu-imemachine** [comment]
[Removed API] Removed the setScale(float) APIs from LottieAnimationView and LottieDrawable. The expected behavior was highly ambiguous when paired with other scale types and canvas transformations. For the vast majority of cases, ImageView.ScaleType should be sufficient. For remaining cases, you may apply transformations to Canvas and use LottieDrawable#draw directly.

**Comment by gpeal** [comment]
https://developer.android.com/reference/android/graphics/Canvas#scale(float,%20float,%20float,%20float)
