### ISSUE TITLE
Memory leak with animations containing images

### ISSUE THREAD

**Issue by TomBell-Trove** [airbnb/lottie-android#2155]
**Link to fork with a repro in the issue-repro module**
Just unzip and drop this file into the issue-repro or issue-repro-compose module, replacing `heart`: [sparkles.json.zip](https://github.com/airbnb/lottie-android/files/9914412/sparkles.json.zip)

**Describe the bug**
The attached lottie contains three pngs (sparkles) which are rendered as a sparkling sky in a loop. 

The animation itself runs and plays without issue on Android, iOS and web.  However after about a minute on Android the app will crash due to an out of memory error.

```
11:49:49.667  6411-6431  Adreno-GSL               W  <sharedmem_gpuobj_alloc:2742>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
11:49:49.667  6411-6431  Adreno-GSL               E  <gsl_memory_alloc_pure:2583>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
11:50:13.043  6411-6417  b.lottie.issue           I  Thread[6,tid=6417,WaitingInMainSignalCatcherLoop,Thread*=0x7d60737c50,peer=0x13540000,"Signal Catcher"]: reacting to signal 3
11:50:13.043  6411-6417  b.lottie.issue           I  
11:50:13.046  6411-6417  libc                     W  malloc(84552) failed: returning null pointer
11:50:13.076  6411-6417  libc                     W  malloc(266240) failed: returning null pointer
11:50:13.082  6411-6417  libc++abi                E  terminating with uncaught exception of type St9bad_alloc: std::bad_alloc
11:50:13.083  6411-6417  libc                     A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 6417 (Signal Catcher), pid 6411 (b.lottie.issues)
11:50:13.786  6516-6516  DEBUG                    A  Cmdline: com.airbnb.lottie.issues
11:50:13.786  6516-6516  DEBUG                    A  pid: 6411, tid: 6417, name: Signal Catcher  >>> com.airbnb.lottie.issues <<<
```
Occurs in both vanilla lottie and compose lottie.

**Steps To Reproduce**

Run the attached .json animation in an infinite loop on a device running Android 13.  Easiest way is to just drop it into issue-repro or issue-repro-compose to replace `heart`.  After about a minute it will crash with an out of memory error.

Note: I wasn't able to repro on an Android 8 device, or an emulator - I'm not sure what the OS version cut off is, if any.  Crashes on a Pixel 3 running Android 12, Pixel 4 running Android 13.

**Comment by gpeal** [comment]
I just spent some heap dumps for this. Using the Android Studio memory profiler and heap dumps, I can see that the native memory does grow for some time but it levels out. The leveling out is bizarre because it's an indication that it's not just a leak. In your case, the app may have OOM'd prior to leveling out but it did level out on my emulator.

Analysis of the heap dump doesn't show anything particularly unusual either... My gut says that it has something to do with Android caching radial gradient shaders under the hood but I'm not entirely sure. Feel free to take a look using standard profiling tools.

**Comment by TomBell-Trove** [comment]
Yeah I wasn't able to repro it on my emulator.  I had to do it on actual devices.

**Comment by gpeal** [comment]
Does it happen if you set the render mode to software?

**Comment by TomBell-Trove** [comment]
Yes unfortunately

**Comment by oooooo99999** [comment]
> **Link to fork with a repro in the issue-repro module**
> Just unzip and drop this file into the issue-repro or issue-repro-compose module, replacing `heart`: [sparkles.json.zip](https://github.com/airbnb/lottie-android/files/9914412/sparkles.json.zip)
> 
> 
> **Describe the bug**
> The attached lottie contains three pngs (sparkles) which are rendered as a sparkling sky in a loop. 
> 
> The animation itself runs and plays without issue on Android, iOS and web.  However after about a minute on Android the app will crash due to an out of memory error.
> 
> ```
> 11:49:49.667  6411-6431  Adreno-GSL               W  <sharedmem_gpuobj_alloc:2742>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
> 11:49:49.667  6411-6431  Adreno-GSL               E  <gsl_memory_alloc_pure:2583>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
> 11:50:13.043  6411-6417  b.lottie.issue           I  Thread[6,tid=6417,WaitingInMainSignalCatcherLoop,Thread*=0x7d60737c50,peer=0x13540000,"Signal Catcher"]: reacting to signal 3
> 11:50:13.043  6411-6417  b.lottie.issue           I  
> 11:50:13.046  6411-6417  libc                     W  malloc(84552) failed: returning null pointer
> 11:50:13.076  6411-6417  libc                     W  malloc(266240) failed: returning null pointer
> 11:50:13.082  6411-6417  libc++abi                E  terminating with uncaught exception of type St9bad_alloc: std::bad_alloc
> 11:50:13.083  6411-6417  libc                     A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 6417 (Signal Catcher), pid 6411 (b.lottie.issues)
> 11:50:13.786  6516-6516  DEBUG                    A  Cmdline: com.airbnb.lottie.issues
> 11:50:13.786  6516-6516  DEBUG                    A  pid: 6411, tid: 6417, name: Signal Catcher  >>> com.airbnb.lottie.issues <<<
> ```
> Occurs in both vanilla lottie and compose lottie.
> 
> **Steps To Reproduce**
> 
> Run the attached .json animation in an infinite loop on a device running Android 13.  Easiest way is to just drop it into issue-repro or issue-repro-compose to replace `heart`.  After about a minute it will crash with an out of memory error.
> 
> Note: I wasn't able to repro on an Android 8 device, or an emulator - I'm not sure what the OS version cut off is, if any.  Crashes on a Pixel 3 running Android 12, Pixel 4 running Android 13.
>

**Comment by gpeal** [comment]
Closing this for now since you have a workaround working for you. If others report similar issues, I'll take another look but I haven't heard of anything yet.

**Comment by ticmaisdev** [comment]
![image](https://github.com/airbnb/lottie-android/assets/128381407/5f73d8e9-126b-4ae9-ba65-e2d63e67eb3c)

should this be considered an evidence? (honest question)
