### ISSUE TITLE
LottieClipSpec.Progress from higher to lower progress

### ISSUE THREAD

**Issue by jzeferino** [airbnb/lottie-android#2157]
**Describe the bug**
when using LottieClipSpec.Progress(0.5f, 0.2f) animation get stuck and whole UI gets blocked.

**What version of Lottie did you test this on?**
5.2.0
**What version of Android did you test this on?**
12

**Steps To Reproduce**

use this:

val composition by rememberLottieComposition(LottieCompositionSpec.RawRes(R.raw.progress))

        LottieAnimation(
            composition = composition,
            clipSpec = LottieClipSpec.Progress(0.5f, 0.2f)
        )

it should play the animation from progress 0.5 to 0.2 but that won't happen

**Comment by gpeal** [comment]
Use 0.2,0.5 with speed -1 instead
