### ISSUE TITLE
add support for puppet tool

### ISSUE THREAD

**Issue by chengzheustc** [airbnb/lottie-android#216]
Hi, can lottie support puppet tool? Every motion I created by puppet is all missed.

Thanks for your time!

**Comment by bigxixi** [comment]
bodymovin本身就不支持puppet，如果是行走动画，可以试试rubberhose 2.0。
puppet tool is not supported by bodymovin, in some cases, you can try rubberhose 2.0.

https://github.com/bodymovin/bodymovin/issues/21
http://www.battleaxe.co/rh2-bodymovin/

**Comment by gpeal** [comment]
Since Lottie is built on top of bodymovin, the we won't be able to support it either. Rubberhose is on the road map though
