### ISSUE TITLE
intial load even when without animation loading takes few seconds /there is a significant delay when i load with other menu items

### ISSUE THREAD

**Issue by nikitamarysolomanpvt** [airbnb/lottie-android#2171]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Describe the bug**
During intial load, even when without animation, loading takes few seconds, there is a significant delay when i load with other menu items.(This happens only when iam using JSON file for animation)

**What version of Lottie did you test this on?**
using the latest version([5.2.0](https://github.com/airbnb/lottie-android/releases/tag/v5.2.0)) even it works the same way in some other lower versions i checked
**What version of Android did you test this on?**
Pixel 3a API 33
**Steps To Reproduce**

1. add lottieanimationview for one of the menu item
2. launch app . the menu with lottieanimationview will load after a few seconds of other items load.

**Screenshots**
<img width="300" alt="small" src="https://user-images.githubusercontent.com/54615666/202633335-3fff8ede-9358-41e6-9ec3-0eb6561da9c5.gif">
[animation6.webm](https://user-images.githubusercontent.com/54615666/202632765-f41f5504-c10e-4b25-bd4d-1825b6f5ea0b.webm)

**Comment by gpeal** [comment]
You can preload an animation by calling `LottieCompositionFactory.from*(…)`. Whenever your real screen accesses the same animation, it'll either join the in-progress parse or reuse the parsed composition. You can decide whenever you want to call that based on what makes sense for your app.
