### ISSUE TITLE
animation is not working on Xiaomi Redmi Note 7

### ISSUE THREAD

**Issue by talfsaverone** [airbnb/lottie-android#2176]
The animation is not working on Xiaomi Redmi Note 7

On Xiaomi Redmi Note 7 download the Lottie app from the google play store and try to see an animation.

The animation is stuck as an image and not running- this is the same issue I am having in my application when I implemented a LottieAnimationView

**Comment by gpeal** [comment]
Closing as this is likely the cause. Feel free to reopen if this is not the case.

**Comment by Ella-Y** [comment]
I faced this issue, and found that the _Animator duration scale_ was set to off. If that changes, the problem is solved.
You can change it in developer settings

Device: Redmi Note 10 Pro
MIUI version 14.0.6

**Comment by Rahul-dasila** [comment]
@gpeal  thnx a lot for solution i was just wandering here and there because of this problem in android studio and ur solution worked nd as u said the animation scale was off after fixing it the animation started runnning thnxx  a lottt again
