### ISSUE TITLE
About ReplacementSpan & LottieAnimationView

### ISSUE THREAD

**Issue by 1748995976** [airbnb/lottie-android#2192]
Hello, I want to play lottie-animation in ReplacementSpan. It can be achieved by using the LottieDrawable.But I want to implement a more general function. The code:
**************************************************************************************
    class ViewSpan(private val view: View) : ReplacementSpan() {

        init {
            view.layoutParams = ViewGroup.LayoutParams(
                ViewGroup.LayoutParams.WRAP_CONTENT,
                ViewGroup.LayoutParams.WRAP_CONTENT
            )
        }

        override fun getSize(
            paint: Paint,
            text: CharSequence?,
            start: Int,
            end: Int,
            fm: Paint.FontMetricsInt?
        ): Int {
            val widthSpec = View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED)
            val heightSpec = View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED)
            view.measure(widthSpec, heightSpec)
            view.layout(0, 0, view.measuredWidth, view.measuredHeight)

            if (fm != null) {
                val height = view.measuredHeight
                fm.ascent = -height / 2
                fm.top = -height / 2
                fm.descent = height / 2
                fm.bottom = height / 2
            }
            return view.right
        }

        override fun draw(
            canvas: Canvas,
            text: CharSequence?,
            start: Int,
            end: Int,
            x: Float,
            top: Int,
            y: Int,
            bottom: Int,
            paint: Paint
        ) {
            val fm = paint.fontMetricsInt
            val transY = (y + fm.descent + y + fm.ascent) / 2 - view.measuredHeight / 2 //计算y方向的位移

            canvas.save()
            canvas.translate(x, transY.toFloat())
            view.draw(canvas)
            canvas.restore()
        }
    }
**************************************************************************************
I can use like this:

**************************************************************************************
    class TestLottieAnimationView @JvmOverloads constructor(
        context: Context,
        attrs: AttributeSet? = null,
        defStyleAttr: Int = 0
    ) : LottieAnimationView(context, attrs, defStyleAttr) {
        var invalidateDrawableCallback: (() -> Unit)? = null

        override fun invalidateDrawable(dr: Drawable) {
            super.invalidateDrawable(dr)
            invalidateDrawableCallback?.invoke()
        }
    }

    ......
    ......

    val voc = "suddenly"
    val testLottieAnimationView = TestLottieAnimationView(context)
    val vocTv = findViewById<TextView>(R.id.vocTv)
    testLottieAnimationView.setDrawableCallBack {
        vocTv.invalidate()
    }
    ...
    ...
    ...
    val builder = SpannableStringBuilder()
    builder.append(voc)
    builder.append("@")
    builder.safeSetSpan(
        ViewSpan(testLottieAnimationView),
        voc.length,
        voc.length + 1,
        Spanned.SPAN_INCLUSIVE_EXCLUSIVE
    )
    vocTv.text = builder
    testLottieAnimationView.playAnimation()
**************************************************************************************
But I find testLottieAnimationView.isShown() always false.So it can not play.
**************************************************************************************
    /**
     * Plays the animation from the beginning. If speed is < 0, it will start at the end
     * and play towards the beginning
    */
    @MainThread
    public void playAnimation() {
        if (isShown()) {
            lottieDrawable.playAnimation();
            enableOrDisableHardwareLayer();
        } else {
            playAnimationWhenShown = true;
        }
    }
**************************************************************************************
Why this restriction "isShown() == true" was added? Is there a way to solve without using LottieDrawable? Thank you! 
Best wishes to you.

**Comment by gpeal** [comment]
What is wrong with using LottieDrawable? `isShown()` is necessary to makes sure that Lottie doesn't animate and use battery life when it's not being shown.

**Comment by 1748995976** [comment]
No problem using LottieDrawable. Thank you for your reply. 👍
