### ISSUE TITLE
Is there a FOSS collection of animation files that can be used with this?

### ISSUE THREAD

**Issue by AdityaAnand1** [airbnb/lottie-android#220]
Not really an 'issue' but I was just wondering if there was a popular collection of free animations somewhere that non-after effects users might find useful :)

**Comment by m1ga** [comment]
there is http://www.lottiefiles.com/
Some even include the AE files!

**Comment by gpeal** [comment]
@AdityaAnand1 Yup, http://www.lottiefiles.com/ is your answer and is maintained by the community! We'll be announcing a second partnership soon too so stay tuned :)
