### ISSUE TITLE
After the lottie upgrade, the related animation icon displays abnormally

### ISSUE THREAD

**Issue by Wuyuan1016** [airbnb/lottie-android#2208]
When I upgraded the Lotties- android version to 5.2.0, I found that the icon display of our use lottie animation has been reduced. I traced it back with the lottie version and found that it began to be abnormal when lottie5.0.1.

**Comment by gpeal** [comment]
Can you try on 5.3.0-SNAPSHOT? Can you attach your animation and a screenshot of what broke?

**Comment by gpeal** [comment]
Feel free to reopen with a repro.
