### ISSUE TITLE
There are some white dots twinkling when the width/height of AnimationView is small.

### ISSUE THREAD

**Issue by Yellow5A5** [airbnb/lottie-android#221]
Has anyone ever had this problem?

There are white dots on canvas on the left.

<img src="https://s14.mogucdn.com/new1/v1/bmisc/f898e175d37275f2eb574bbe611a683b/bec24cb00f684898acdda6fcb30ae14f.png" width="300"/>  <img src="https://s14.mogucdn.com/new1/v1/bmisc/d29accb510f928d3e9129d9efab6fe3b/0f573071f52f43bf833c5deead7f4796.png" width="200"/>

**Comment by gpeal** [comment]
@Yellow5A5 Can you attach the json or a sample project? You're also getting some really nasty aliasing which shouldn't be happening.
Can you try it on 2.0.0-beta3 too?

**Comment by gpeal** [comment]
@Yellow5A5 bump

**Comment by Yellow5A5** [comment]
There are some other problems.
The Animation is cut by the border.

```
        LottieComposition.Factory.fromAssetFileName(this, "likepop_comp.json", new OnCompositionLoadedListener() {
            @Override
            public void onCompositionLoaded(LottieComposition composition) {
                for (int i = 0; i < 20; i++) {
                    LottieAnimationView animationItem = new LottieAnimationView(SampleFirActivity.this);
                    animationItem.setLayoutParams(new ViewGroup.LayoutParams(200,200));
                    animationItem.setComposition(composition);
                    animationItem.loop(true);
                    animationItem.playAnimation();
                    LinearLayout container = (LinearLayout) findViewById(R.id.anim_container);
                    container.addView(animationItem, -1);
                }
            }
        });
```

### release

<img src="https://camo.githubusercontent.com/6efc319f63a242a7d6ef1d9569e40ebb6bd644e8/68747470733a2f2f7331342e6d6f677563646e2e636f6d2f6e6577312f76312f626d6973632f66383938653137356433373237356632656235373462626536313161363833622f62656332346362303066363834383938616364646136666362333061653134662e706e67" width="300"/>

### 2.0.0-beta3

<img src="https://s14.mogucdn.com/new1/v1/bmisc/b0864b76c1282d039ce848a8e01fd99c/8d8ec6ab5dab4e3898042a3f7630d264.jpeg" width="300"/>

**Comment by gpeal** [comment]
@Yellow5A5 Try calling `setScaleType(ImageView.CENTER_INSIDE)`

**Comment by Yellow5A5** [comment]
setScaleType(ImageView.ScaleType.CENTER_INSIDE)
it is not works.
The problems still exist...

**Comment by isrinath** [comment]
Hi Yellow5A5,

Can you share the application?

**Comment by gpeal** [comment]
@Yellow5A5 I'm unable to repro this. I tried setting a LottieAnimationView to a very small size then using centerInside and the animation scaled down cleanly. Can you attach a sample project that repros this?

This PR may also be of interest: https://github.com/airbnb/lottie-android/pull/241

**Comment by gpeal** [comment]
@Yellow5A5 Can you create a sample project that repros this?

**Comment by Yellow5A5** [comment]
ok, I will send the email for you.
