### ISSUE TITLE
lottie-android and lottie-web has different behavior.

### ISSUE THREAD

**Issue by Hawk-Song** [airbnb/lottie-android#2211]
I am using this json file as input:
https://www.gstatic.com/quartz/broadcast/animations/DEFAULT/phase2.json

This animation has several sub animations, let's say they are A, B, C.  A has 60s, B and C has 20s.
On android, the B and C will stop after 20s, and A will continue to play until 60s. then they will repeat again.
On web, the B and C will repeat immediately after 20s.

the android code:
```
    <com.airbnb.lottie.LottieAnimationView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:lottie_rawRes="@raw/phase2"
        app:lottie_loop="true"
        app:lottie_autoPlay="true" />
```
the web code:
```
<div style="width:1067px;height:600px" id="lottie"></div>
<script>
  var animation = bodymovin.loadAnimation({
    container: document.getElementById('lottie'), 
    path: 'https://www.gstatic.com/quartz/broadcast/animations/DEFAULT/phase2.json', 
    renderer: 'html', 
    loop: true, 
    autoplay: true, 
    name: "Hello World", 
  })
</script>
```

How could I solve this problem ?
Any response will be greatly appreciated! Thank you!

**Comment by gpeal** [comment]
@Hawk-Song This uses a `loopOut()` expression. Expressions aren't supported on Android.

**Comment by Hawk-Song** [comment]
Thank you!
