### ISSUE TITLE
Animation with Adobe After Effects files that consist of png images does not support system scale changes

### ISSUE THREAD

**Issue by AndreyBro48** [airbnb/lottie-android#2216]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Describe the bug**

Any animations with Adobe After Effects files that consist of png images do not support system scaling

**What version of Lottie did you test this on?**

lottie-compose:5.2.0

**What version of Android did you test this on?**

Android 10/13, but I think it doesn't depend on the Android version

**Steps To Reproduce**

1. Run any animation with Adobe After Effects files that consist of png images (ex: https://lottiefiles.com/131823-investment) [screenshot 1](https://user-images.githubusercontent.com/55762873/209637168-f8dcdb03-7bb9-45cf-940b-736a895402ac.png)
2. Go to system settings and change the scale settings of user interface [screenshot 2](https://user-images.githubusercontent.com/55762873/209637172-96ea23e8-506f-4694-a7c1-23c5ea5e6b94.png)
3. Go back to app [screenshot 3](https://user-images.githubusercontent.com/55762873/209637173-cf290e84-50bc-4cd4-ba5c-90bc999114ae.png)

**Code**
```
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val animation = "https://assets9.lottiefiles.com/packages/lf20_dnGoCmSHJx.json"
        setContent {
            LottieTestTheme {
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colors.background
                ) {
                    val composition by rememberLottieComposition(
                        spec = LottieCompositionSpec.Url(animation)
                    )
                    LottieAnimation(
                        composition = composition,
                        iterations = LottieConstants.IterateForever,
                        contentScale = ContentScale.FillWidth,
                        alignment = Alignment.TopCenter,
                        modifier = Modifier.fillMaxSize()
                    )
                }
            }
        }
    }
}
```

**Comment by Hooooong** [comment]
I'm experiencing the same issue. I'm using version 6.2.0, and after changing the system scale, there's a rendering issue, but force-quitting the app and relaunching it makes it work normally.

**Comment by Hooooong** [comment]
@gpeal 

It is the same even if you upgrade to 6.3.0.

My code is like this, and the video is attached.

```
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val animation = "https://lottie.host/8eda8418-db8e-42a7-be06-c6208ffb03b4/3yH617QvMP.json"
        setContent {
            LottieTestTheme {
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colors.background
                ) {
                    val composition by rememberLottieComposition(
                        spec = LottieCompositionSpec.Url(animation)
                    )
                    LottieAnimation(
                        composition = composition,
                        iterations = LottieConstants.IterateForever,
                        contentScale = ContentScale.FillWidth,
                        alignment = Alignment.TopCenter,
                        modifier = Modifier.fillMaxSize()
                    )
                }
            }
        }
    }
}
```

|SAMPLE 1|SAMPLE 2|
:-:|:-:
<img src="https://github.com/airbnb/lottie-android/assets/31605798/7e83391a-b6b0-4ee6-b003-6bb51044930d" width="250"/>|<img src="https://github.com/airbnb/lottie-android/assets/31605798/67145f76-002f-4329-9ef8-d374319659d9" width="250"/>

**Comment by Hooooong** [comment]
@gpeal 

Hello. I am leaving a comment here as it seems to be the same issue.
The problem was resolved when using a single LottieAnimation, but when using multiple specs with the same URL, there seems to be a bouncing issue.

In the sample below, it works correctly if I give a different cacheKey for rememberLottieComposition, but I’m wondering if this is the recommended approach.

The version is 6.5.2, and I am providing the sample code and video below.

```
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            LottieTestTheme {
                val animation = "https://assets9.lottiefiles.com/packages/lf20_dnGoCmSHJx.json"

                Surface(
                    modifier = Modifier.fillMaxSize()
                ) {
                    val composition1 by rememberLottieComposition(spec = LottieCompositionSpec.Url(animation))
                    val composition2 by rememberLottieComposition(spec = LottieCompositionSpec.Url(animation))

                    Column(
                      verticalArrangement = Arrangement.spacedBy(16.dp)
                    ){
                        LottieAnimation(
                            composition = composition1,
                            iterations = LottieConstants.IterateForever,
                            contentScale = ContentScale.FillWidth,
                            alignment = Alignment.TopCenter,
                            modifier = Modifier.fillMaxWidth()
                        )

                        LottieAnimation(
                            composition = composition2,
                            iterations = LottieConstants.IterateForever,
                            contentScale = ContentScale.FillWidth,
                            alignment = Alignment.TopCenter,
                            modifier = Modifier.fillMaxWidth()
                        )
                    }
                }
            }
        }
    }
}
```

|SAMPLE 1|
:-:
<img src="https://github.com/user-attachments/assets/e88820bc-cc42-4e91-a31b-8398063a5a94" width="250"/>|

**Comment by gpeal** [comment]
> @gpeal
> 
> Hello. I am leaving a comment here as it seems to be the same issue. The problem was resolved when using a single LottieAnimation, but when using multiple specs with the same URL, there seems to be a bouncing issue.
> 
> In the sample below, it works correctly if I give a different cacheKey for rememberLottieComposition, but I’m wondering if this is the recommended approach.
> 
> The version is 6.5.2, and I am providing the sample code and video below.
> 
> ```
> class MainActivity : ComponentActivity() {
>     override fun onCreate(savedInstanceState: Bundle?) {
>         super.onCreate(savedInstanceState)
>         setContent {
>             LottieTestTheme {
>                 val animation = "https://assets9.lottiefiles.com/packages/lf20_dnGoCmSHJx.json"
> 
>                 Surface(
>                     modifier = Modifier.fillMaxSize()
>                 ) {
>                     val composition1 by rememberLottieComposition(spec = LottieCompositionSpec.Url(animation))
>                     val composition2 by rememberLottieComposition(spec = LottieCompositionSpec.Url(animation))
> 
>                     Column(
>                       verticalArrangement = Arrangement.spacedBy(16.dp)
>                     ){
>                         LottieAnimation(
>                             composition = composition1,
>                             iterations = LottieConstants.IterateForever,
>                             contentScale = ContentScale.FillWidth,
>                             alignment = Alignment.TopCenter,
>                             modifier = Modifier.fillMaxWidth()
>                         )
> 
>                         LottieAnimation(
>                             composition = composition2,
>                             iterations = LottieConstants.IterateForever,
>                             contentScale = ContentScale.FillWidth,
>                             alignment = Alignment.TopCenter,
>                             modifier = Modifier.fillMaxWidth()
>                         )
>                     }
>                 }
>             }
>         }
>     }
> }
> ```
> 
> SAMPLE 1
> <img alt="" width="250" src="https://github.com/user-attachments/assets/e88820bc-cc42-4e91-a31b-8398063a5a94">

Yes, I would use a different cacheKey so that the two compositions can be differentiated.
