### ISSUE TITLE
lottieAnimationView.cancelAnimation() is cancelling the animation with distorted image.

### ISSUE THREAD

**Issue by passiondroid** [airbnb/lottie-android#222]
I used this file - http://www.lottiefiles.com/100-check-pop

![](https://media.giphy.com/media/uDuFXSIJgf8cg/giphy.gif)

It was playing nicely but when i execute cancel animation on it.
It get distorted - 

![screen shot 2017-03-26 at 2 15 06 pm](https://cloud.githubusercontent.com/assets/1834030/24329800/b4212464-122e-11e7-9ddc-06b7d4343327.png)

Please check and help

**Comment by gpeal** [comment]
@passiondroid I can't repro this. Can you attach a sample project if it's still happening. Also make sure to try it on 2.0.0-beta3

**Comment by gpeal** [comment]
@passiondroid Please reopen this if it's still an issue. This may be a duplicate f #221 which I can't reproduce. If possible, can you attach a sample project that repros it?
