### ISSUE TITLE
The effect of Android text wrapping is different from iOS

### ISSUE THREAD

**Issue by wlqjj0** [airbnb/lottie-android#2220]
The effect of Android text wrapping is different from iOS
Usually Android is not displayed correctly
Mainly in the upper line margin

**Comment by gpeal** [comment]
Can you try with 5.3.0-SNAPSHOT?

**Comment by wlqjj0** [comment]
Thank you very much, perfect
When is the official version?

**Comment by gpeal** [comment]
It should be soon, I'm waiting on something from Airbnb before publishing it.
