### ISSUE TITLE
LottieAnimation does not work on v.5.x.x

### ISSUE THREAD

**Issue by joaodevsantos** [airbnb/lottie-android#2221]
**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Describe the bug**

`LottieAnimation` composable with iterations as `LottieConstants.IterateForever` doesn't start animation. I'm starting a project that already has multiple dependencies and I was thinking that this could be happening due to some dependencies conflicts but I have created a new blank project and this problem still occurs.

I have the following code:

```
class MainActivity : ComponentActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContent {
      val composition by rememberLottieComposition(
        LottieCompositionSpec.RawRes(
          resId = R.raw.loading
        )
      )

      LottieAnimation(
        composition = composition,
        iterations = LottieConstants.IterateForever,
      )
    }
  }
}
```

And the **animation works with the library version 4.2.2** but **doesn't work with versions 5.x.x.**. I have tried several different things even managing the progress using the lambda function and ``animateLottieCompositionAsState`` but nothing works.

I have also considered this to be a problem with the JSON file but it works with the older library version so I don't think so.

**What version of Lottie did you test this on?**

- `com.airbnb.android:lottie-compose:4.2.2`
- `com.airbnb.android:lottie-compose:5.0.0`
- `com.airbnb.android:lottie-compose:5.1.0`
- `com.airbnb.android:lottie-compose:5.2.0`

**Steps To Reproduce**

Add a `LottieAnimation` composable using lottie-compose library version 5.x and this animation - [loading.zip](https://github.com/airbnb/lottie-android/files/10392100/loading.zip).

_Note_: I have tested using a Samsung Galaxy Note 20 Ultra 5G with Android 13.

**Screenshots**

The animation looks like frozen as we can see on the screenshot below. It keeps showing this static "image" all the time and doesn't start animating.

<img width="390" alt="Test" src="https://user-images.githubusercontent.com/43722840/211802218-9281e650-d6b5-4ce2-b270-a884fa1630e2.png">

**Comment by gpeal** [comment]
Do you have battery saver mode on or animation scale set to 0 in developer options?

**Comment by joaodevsantos** [comment]
> 

You're right, what a stupid mistake! I had the animation scale set to 0. 

However, why does it work with Lottie v.4.x but not with v.5.x?

**Comment by gpeal** [comment]
It may not have been implemented yet. You can override this behavior [here](https://github.com/airbnb/lottie-android/blob/master/lottie-compose/src/main/java/com/airbnb/lottie/compose/animateLottieCompositionAsState.kt#L53)
