### ISSUE TITLE
Animatable Repeater - Position Control

### ISSUE THREAD

**Issue by schultheiscj** [airbnb/lottie-android#2222]
I'm looking to create a long shadow effect on a shape layer with **repeater**. I'd like to use the transform X,Y position of the repeater as an animatable property but that is not currently supported. It looks like only **offset**, **copies** and **opacity** are supported at this time.

In short, hoping animatable support for repeater position is a feature that could be implemented.

I've explored other alternatives with duplicating the same layer multiple times and repositioning manually, as well as drop shadows but I have not cracked a solution for something that can be used and animated in code a bit more dynamically.

**Comment by gpeal** [comment]
It has been a while since I looked at this but can you use the [TRANSFORM_*](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieProperty.java#L84) properties?

**Comment by schultheiscj** [comment]
I can see the overall Transform properties of the layer when exporting the .JSON but I would like to expose and control the Repeater Transform properties to create a real-time slider interaction / controllable shadow effect on Android.

![Example1_Repeater](https://user-images.githubusercontent.com/120065601/212184337-0a481990-ea7e-4e03-85e6-d6a913febba2.jpg)
![Example2_Repeater](https://user-images.githubusercontent.com/120065601/212184339-feb79722-e25c-45dd-8b3c-ab5b9592e3e5.jpg)

**Comment by gpeal** [comment]
REPEATER_COPIES and REPEATER_OFFSET are also valid dynamic properties in addition to the TRANSFORM_ properties I mentioned above. If those don't suit your needs, can you be more clear with what you want?
