### ISSUE TITLE
LottieDrawable is not playing the animation in GraphicOverlay.Graphic 

### ISSUE THREAD

**Issue by Srin01** [airbnb/lottie-android#2223]
I am trying to use lottieDrawable to draw a simple animation. But the animation is not played.

I saw in old issues that you need to call mLottieDrawable.setCallBack(this)
But since am inside GraphicOverlay.Graphic I don't know what should I use inside setcallBack()

Below is the code I have used ->

`
public class PoseGraphic extends GraphicOverlay.Graphic {
    LottieDrawable mLottieDrawable;

    public PoseGraphic() {
        
        mLottieDrawable = new LottieDrawable();
        mLottieDrawable.enableMergePathsForKitKatAndAbove(true);
        LottieResult<LottieComposition> result = LottieCompositionFactory.fromRawResSync(context, R.raw.heart);
        mLottieDrawable.setComposition(result.getValue());
        mLottieDrawable.setRepeatCount(LottieDrawable.INFINITE);
        mLottieDrawable.start();
        }

    @Override
    public void draw(Canvas canvas) {
        mLottieDrawable.draw(canvas);
    }
`

Version of Lottie - 
5.2.0

Version of Android -
Android 12

![WhatsApp Image 2023-01-14 at 3 24 09 PM](https://user-images.githubusercontent.com/64426998/212466324-76bf9a34-6097-44d0-9ab6-c551f1290f90.jpeg)

**Comment by gpeal** [comment]
I've never used GraphicOverlay but it looks like it's from [android-vision](https://github.com/googlesamples/android-vision/blob/master/visionSamples/FaceTracker/app/src/main/java/com/google/android/gms/samples/vision/face/facetracker/ui/camera/GraphicOverlay.java#L61). It looks like GraphicOverlay is just a view and Graphic is a sub class that gets the view as a constructor parameter. My guess is that you'd extend Graphic, save GrapicOverlay to a field, and then set it as the callback. However, that seems to be library specific and not an issue with Lottie. Ultimately, Lottie just needs a way to notify its parent that it needs to be redrawn. StackOverflow may be a better resource for help with that library.
