### ISSUE TITLE
Animation does not restart

### ISSUE THREAD

**Issue by vanniktech** [airbnb/lottie-android#2228]
Public reproducer: https://github.com/vanniktech/playground/pull/76

1. Open the app
2. Animation starts once

Expected behavior: Once done it should start again.
Actual behavior: It only plays once.

**Comment by gpeal** [comment]
You only set the mode but you have to set loop to true
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/res/values/attrs.xml#L11

**Comment by vanniktech** [comment]
Thanks!
