### ISSUE TITLE
ui bloked when drawToBitmap()

### ISSUE THREAD

**Issue by emergingcoders2** [airbnb/lottie-android#2229]
in lottie animation frame is not set in background and bitmap is not create in main thread so how to make each frame to convert bitmap ? and if perform all in main thread than ui is bocked so how to resolve this issue ?

**Comment by gpeal** [comment]
Sorry, can you clarify?

**Comment by emergingcoders2** [comment]
yes , i want to make video from lottie in that making each frame and convert into bitmap .in this method i used mediamuxer for making video and my code is 


 val max = lottieAnimationView.maxFrame.toInt()
  CoroutineScope(Dispatchers.Default).launch {
        for (i in 0 until max) {
            try {
                    lottieAnimationView.frame = i
                    var bitmap = lottieAnimationView.drawToBitmap()
                    frameBuilder.createFrame(bitmap , i)
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }}

Only the original thread that created a view hierarchy can touch its views. in that line  lottieAnimationView.frame = i and set outside of  CoroutineScope then not generate proper video every time set last frame so video is not perfect frame by frame .and apply this all is main thread then all worked but ui is block. how to solve this ?

**Comment by gpeal** [comment]
What is drawToBitmap() doing? You can also create a LottieDrawable and call draw on that from any frame.

**Comment by emergingcoders2** [comment]
yes , i solved this issue using Lottie Drawable , Thank you
