### ISSUE TITLE
Opacity applied to individual elements

### ISSUE THREAD

**Issue by podrivo** [airbnb/lottie-android#223]
Opacity is being applied to individual elements, so during the transition you can see each element, instead of seeing as a group.

So for instance, take this screenshot from After Effects of a hand being transitioned.

The hand is formed of different elements, that fade as group.
<img width="551" alt="screen shot 2017-03-26 at 1 14 28 pm" src="https://cloud.githubusercontent.com/assets/546221/24332966/2a38ee88-1226-11e7-9da4-4a314ce21ff7.png">

Same happens in Bodymovin:
<img width="1440" alt="screen shot 2017-03-26 at 1 15 49 pm" src="https://cloud.githubusercontent.com/assets/546221/24332976/674224c0-1226-11e7-86ee-9b524118b14a.png">

But this is the result from Lottie:
<img width="471" alt="screen shot 2017-03-26 at 1 23 16 pm" src="https://cloud.githubusercontent.com/assets/546221/24333029/6d6b0758-1227-11e7-8e1e-2561dc64575d.png">

Using beta3.
Here's the .aep and .json: [opacity.zip](https://github.com/airbnb/lottie-android/files/870878/opacity.zip)

**Comment by gpeal** [comment]
Unfortunately, achieving this will incur a pretty heave performance penalty so I'd try alternative ways of achieving this. Precomps maybe?

**Comment by gpeal** [comment]
@podrivo 3.1.0 will have a new API `setApplyingOpacityToLayersEnabled` where you can manually enable this to render correctly. It isn't on by default because there is a performance overhead in doing so.
