### ISSUE TITLE
Questions about the library

### ISSUE THREAD

**Issue by Arashvscode** [airbnb/lottie-android#2232]
Hello, first, thank you for the excellent library. Second, I wanted to know what format this library supports. Third, I need a piece of Java code. If the file is corrupted at any time or under any circumstances, a default file that I defined myself should run, something like try and catch, if you can help me.  Thank

**Comment by gpeal** [comment]
Thank you!
You can use `lottie_fallbackRes` on your LottieAnimationView (XML)
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/res/values/attrs.xml#L9
