### ISSUE TITLE
LottieClipSpec.Marker and LottieClipSpec.Markers don't work

### ISSUE THREAD

**Issue by mchiasson-youi** [airbnb/lottie-android#2242]
Using Bodymovin v5.10.2 and Lottie v5.2.0

I followed these instructions here: https://lottiefiles.com/blog/tips-and-tutorials/how-to-setup-named-markers-in-lottie-animations

Here is my JSON
```JSON
{"v":"5.10.2","fr":29.9700012207031,"ip":0,"op":241.000009816131,"w":400,"h":400,"nm":"TestComp","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":1,"nm":"Deep Red Solid 1","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":0,"s":[0]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":119,"s":[360]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":120,"s":[360]},{"t":240.0000097754,"s":[0]}],"ix":10},"p":{"a":0,"k":[200,200,0],"ix":2,"l":2},"a":{"a":0,"k":[50,50,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"sw":100,"sh":100,"sc":"#b72929","ip":0,"op":900.000036657751,"st":0,"bm":0}],"markers":[{"tm":0,"cm":"{\r\"name\":\"cw\"\r}","dr":120.0000048877},{"tm":120.0000048877,"cm":"{\r\"name\":\"ccw\"\r}","dr":120.0000048877}]}
```

It has two consecutive markers: `cw` and `ccw`

This does not work. clipSpec is ignored and animates everything
```Kotlin
@Composable
fun lottieExample() {

    val mainComp by rememberLottieComposition(
        spec = LottieCompositionSpec.Asset("TestComp.json")
    )

    LottieAnimation(
        composition = mainComp,
        clipSpec = LottieClipSpec.Marker("cw"),
        iterations = LottieConstants.IterateForever
    )
}
```

This also does not work. clipSpec is ignored and animates everything
```Kotlin
@Composable
fun lottieExample() {

    val mainComp by rememberLottieComposition(
        spec = LottieCompositionSpec.Asset("TestComp.json")
    )

    LottieAnimation(
        composition = mainComp,
        clipSpec = LottieClipSpec.Markers("cw", "ccw"),
        iterations = LottieConstants.IterateForever
    )
}
```

But this works. clipSpec is not ignored and animates the correct range indefinitely.
```Kotlin
@Composable
fun lottieExample() {

    val mainComp by rememberLottieComposition(
        spec = LottieCompositionSpec.Asset("TestComp.json")
    )

    LottieAnimation(
        composition = mainComp,
        clipSpec = LottieClipSpec.Frame(0, 120),
        iterations = LottieConstants.IterateForever
    )
}
```

Any idea? Thanks!

**Comment by mchiasson-youi** [comment]
After looking at the source code, it looks like lottie/src/main/java/com/airbnb/lottie/model/Marker.java receives the comment, but does not parse the JSON string and uses JSON string as a marker name...
```Java
markers.add(new Marker(comment, frame, durationFrames));
```

**Comment by gpeal** [comment]
I wasn't aware that lottie-web allows [3 different formats](https://github.com/airbnb/lottie-web/wiki/Markers#markers-are-now-supported-by-the-gotoandstop-and-gotoandplay-methods) for markers. This is largely an artifact of it being written in JavaScript, however. On other platforms (like Android), we need to abide by stricter types for performance and interoperability reasons so my recommendation is to use option 3 in the lottie-web docs which is just to put the name alone in the marker box.
