### ISSUE TITLE
Re-calling `Lottie.initialize` leads to inconsistent state

### ISSUE THREAD

**Issue by drewhamilton** [airbnb/lottie-android#2245]
[**Link to fork with a repro in the issue-repro module**](https://github.com/drewhamilton/lottie-android/tree/drew/double-initialize-bug)

**Describe the bug**
`Lottie.initialize` can be called multiple times without throwing an error, but subsequent calls do not change the `networkCache` and `networkFetcher` used internally in the `L` class.

**Steps To Reproduce**
Run `./gradlew :issue-repro:recordPaparazziDebug` on my branch linked above. Note that `heartUrl2` test fails.

The test class sets a `TemporaryFolder` as Lottie's network cache directory `@Before` each test. The `TemporaryFolder` is deleted after each test.

The first test, `heartUrl`, works as expected, generating a screenshot with a heart image loaded from the provided URL.

The second test, `heartUrl2`, fails. Reading down the stacktrace you can see that the cache directory is not a directory. This is because the directory no longer exists; it was deleted after the first test. Lottie is still holding and using a reference to the cache dir from the first `initialize` call, rather than the one from the second `initialize` call.

**Possible fixes**
One approach would be to throw an exception on subsequent calls to `initialize`. But this would make my use-case linked above—re-initializing Lottie for each Paparazzi JUnit test—impossible. To support my use-case, a `Lottie.reset` API could be added to clear previously-initialized settings. This could be `@VisibleForTesting` if you want to discourage its use in production code.

Another approach would be to decide that it is not an error to call `initialize` multiple times, and silently replace any old configuration with each call to `initialize`.

I'd love to submit a PR implementing whatever solution is preferred.

**Comment by gpeal** [comment]
Let's go for the option to silently update the fetcher and cache. I'd happily accept a PR for that.
