### ISSUE TITLE
How to drag and drop object in LottieAnimationView ?

### ISSUE THREAD

**Issue by tuanhs0606** [airbnb/lottie-android#2247]
I want drop and drap object in LottieAnimationView and need know postion(x, y) and size(width, height)
Could you help me this?
Thank you!

**Comment by gpeal** [comment]
You could add a value callback for the layer you want to target. The callback will contain coordinates of the object. You can then store that and use it however you want.
https://airbnb.io/lottie/#/android?id=dynamic-properties

**Comment by tuanhs0606** [comment]
@gpeal Ok bro. Let us check your link. If you have sample for this, please share for me :) Thank you so much!
