### ISSUE TITLE
Request of Memory of different composition size

### ISSUE THREAD

**Issue by Vensent** [airbnb/lottie-android#2249]
I know Lottie handle the width and height in Json as 'dp', not 'px'.

For example, my LottieAnimationView is fixed 100dp x 100dp, and the density of my Phone is 3.

Here are two lottie files with the same content but different sizes. First is 100x100, and the second one is 300x300.

When loading in the LottieAnimationView above respectively, I can see the first one gets a 300x300(px) LottieDrawable. And the second one gets a 900x900(px) LottieDrawable.

My question is: Do these two LottieDrawable use the same memory or not? And Why?

Thanks.

**Comment by gpeal** [comment]
The exact amount will vary between whether it's using software or hardware rendering and may also vary across Android versions and OEMs. The best way to find out is to use the [Android Studio memory profiler](https://developer.android.com/studio/profile/memory-profiler). Attach it to your app before the animation is visible then set up something like a click listener which makes the animation visible and observe the difference.
