### ISSUE TITLE
Lottie animation is getting hanged sometime 

### ISSUE THREAD

**Issue by Pranesh111** [airbnb/lottie-android#2251]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Checklist**

1. Fork this repository into your account.
2. Reproduce your issue in the issue-repro module. Issues without a repro in the issue-repro 
   module may be auto-closed.

**[Link to fork with a repro in the issue-repro module](https://github.com/Pranesh111/lottie-android)**

**Describe the bug**
Lottie animation is getting hanged completely for 4-5 seconds & then gets resumed. 

**Steps To Reproduce**

1. Programmatically changing the lottie assets:
`   public void startAnim(String fileName) {
        LottieCompositionFactory.fromAsset(mContext, fileName).addListener(lottieListener);
    `}

` private final LottieListener<LottieComposition>
            lottieListener = new LottieListener<LottieComposition>() {
        @Override
        public void onResult(LottieComposition lottieComposition) {
            mLottieView.setComposition(lottieComposition);
            mLottieView.playAnimation();
        }
    };`
  
2. Invoking startAnim method with differenct filename from res/asset folder

**Comment by KnotDaone** [comment]
How do I do that please give me steps to take starting from one On Feb 25, 2023 4:05 PM, Pranesh111 ***@***.***> wrote:
Lottie is supported and developed on nights and weekends. Issues from Lottie sponsors will be prioritized.
If you don't use this template, your issue will be closed. Delete this text once completed.
Checklist
Fork this repository into your account.Reproduce your issue in the issue-repro module. Issues without a repro in the issue-repro
module may be auto-closed.
Link to fork with a repro in the issue-repro module
Describe the bug
Lottie animation is getting hanged completely for 4-5 seconds & then gets resumed.
Steps To Reproduce
Steps to reproduce the behavior:
Programmatically changing the lottie assets:
  public void startAnim(String fileName) { LottieCompositionFactory.fromAsset(mContext, fileName).addListener(lottieListener);}
 private final LottieListener<LottieComposition> lottieListener = new LottieListener<LottieComposition>() { @Override public void onResult(LottieComposition lottieComposition) { mLottieView.setComposition(lottieComposition); mLottieView.playAnimation(); } };
Invoking startAnim method with differenct filename from res/asset folder

**Comment by Pranesh111** [comment]
1. Keep 3-4 assets under assets
2. Try to change the animation asset programmatically by invoking above startAnim() with a some duration.
3. Let it play  for 10 to 15 mins & perform animation switch in between randomly

**Comment by gpeal** [comment]
@Pranesh111 Did you intend to push changes to you fork? I don't see anything that you have added there.
