### ISSUE TITLE
Request LottieCompositionFactory fromXXXInputStream close param to be public.

### ISSUE THREAD

**Issue by peerless2012** [airbnb/lottie-android#2252]
I use `Lottie` in `Glide`, and decode it in `ResourceDecoder` which has `InputStream`, when I use `LottieCompositionFactory.fromJsonInputStreamSync` and `LottieCompositionFactory.fromZipStreamSync`, they all close the `InputStream`, but I don't want `LottieCompositionFactory` close the `InputStream`.

I think, make the private `LottieCompositionFactory.fromJsonReaderSyncInternal` and `LottieCompositionFactory.fromZipStreamSyncInternal` to be public will be better.

**Comment by gpeal** [comment]
Reopening to add support for zipinputstream

**Comment by peerless2012** [comment]
When will publish this feature ?

**Comment by gpeal** [comment]
I'll probably publish 6.1.0 soon
