### ISSUE TITLE
Can't play lottie animation with only basic elements properly

### ISSUE THREAD

**Issue by yinmengixn** [airbnb/lottie-android#2257]
Barely playable，My playback effect is like this
[https://youtube.com/shorts/E-yYF1oRaNw?feature=share](url)

lottie-android version：6.0.0

This is the exported json file
[bg_new.json.zip](https://github.com/airbnb/lottie-android/files/10918859/bg_new.json.zip)

The ideal effect is like this
[https://youtube.com/shorts/QdIOCYy7bAs](url)

**Comment by gpeal** [comment]
Your animation has expressions which Lottie doesn't support on Android.

https://github.com/airbnb/lottie/blob/master/supported-features.md

**Comment by yinmengixn** [comment]
> Your animation has expressions which Lottie doesn't support on Android.
> 
> https://github.com/airbnb/lottie/blob/master/supported-features.md

Will these expressions be supported in the future？

**Comment by gpeal** [comment]
All expressions are not supported and there are no plans to add support. Expressions are javascript which cannot natively run on Android so there isn't currently a good path to get them working.
