### ISSUE TITLE
Lottie Animation lags on transition between activities

### ISSUE THREAD

**Issue by DmytroTols** [airbnb/lottie-android#2258]
#1312 this is the issue I faced.Issue still exist in version 4.2.2,when starting new activity Lottie freezes and then start playing again when transition from activities happens,is there a way to make animation keep playing?

**Comment by Gerizard** [comment]
Is there any workaround to get this fixed, its not aesthetically pleasung when it lags between activities😅

**Comment by DmytroTols** [comment]
@Gerizard What i did is put everything in another Coroutine Scope and then when i needed to change smth for animation i used withContext(Main)
