### ISSUE TITLE
Lottie Animation lags on transition between activities

### ISSUE THREAD

**Issue by DmytroTols** [airbnb/lottie-android#2259]
#1312  this is the issue I faced.Issue still exist in version 4.2.2,when starting new activity Lottie freezes and then start playing again when transition from activities happens,is there a way to make animation keep playing?

**Comment by gpeal** [comment]
@DmytroTols The latest version in 6.0. Can you create a project with 6.0 that reproduces this?

**Comment by gpeal** [comment]
I haven't had time to look into this but from my recollection, Android freezes windows from rendering during window animations between Activities which means that Lottie wouldn't be able to render in that case. Can you try an AVD or something and see if the same thing happens?

**Comment by DmytroTols** [comment]
I tried it with an emulator Pixel 4 api 30, issue still remains,I'm doing some work on the background and with animation in starts freezes. The issue probably is that I'm doing background process + animation + navigation which causes lags, I'm just wondering if there is any workaround

**Comment by DmytroTols** [comment]
I tried it with default loading spinner (progress bar) and it worked just fine. 
Here is new demo with Lottie Animation on top and a Progress bar on the bottom, in case you wanna see how other loading spinner reacts
[AnimationLag.zip](https://github.com/airbnb/lottie-android/files/11725599/AnimationLag.zip)

**Comment by gpeal** [comment]
I just tried this with window animations slowed down so I could see what's happening and it appears to continue rendering without issue. I'm not sure if this issue is actionable.

https://github.com/airbnb/lottie-android/assets/1307745/fcf9fafa-543b-48e1-ae09-df3de37384e3

**Comment by DmytroTols** [comment]
For some reason the same code that you run was very laggy for me, but I found a work around by making calculations instead of lifecycleScope.launch() in lifecycleScope.launch(Default) or CoroutineScope(Default).launch
