### ISSUE TITLE
Animation working on iOS doesn't work as expected on Android

### ISSUE THREAD

**Issue by benlacey** [airbnb/lottie-android#226]
I've got an animation that works as expected on iOS, but doesn't on Android - see the screenshot below for the difference at roughly the same point in the animation:

![image](https://cloud.githubusercontent.com/assets/5020620/24359972/cf9867aa-12fd-11e7-837d-32325928f310.png)

Would you expect the attached AE file or json to work in Lottie Android?

[spinner.aep.zip](https://github.com/airbnb/lottie-android/files/872641/spinner.aep.zip)
[spinner.json.zip](https://github.com/airbnb/lottie-android/files/872652/spinner.json.zip)

I've not got any experience in After Effects, so I'm not sure what features the designer who created this animation has used and whether they're supported, but if you've got any advice on how to get the desired effect working I'd be very grateful!

**Comment by bmc08gt** [comment]
What lottie version are you using on Android?

**Comment by benlacey** [comment]
@bmc08gt 1.5.3, I believe.  The screenshot was from the current example apps from master branch.

**Comment by gpeal** [comment]
@bmc08gt please try 2.0.0-beta3

**Comment by bmc08gt** [comment]
@benlacey @gpeal Please try 2.0.0-beta3

**Comment by gpeal** [comment]
@benlacey There does seem to me an issue with it. I'll take a look

**Comment by gpeal** [comment]
Tracking last remaining issue in #249
