### ISSUE TITLE
LottieCompositionCache cache memory

### ISSUE THREAD

**Issue by zijinzhiyun** [airbnb/lottie-android#2260]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**Describe alternatives you've considered**
LottieCompositionCache cache 20, but the size of each LottieComposition is different.In the gift scenario, the size of LottieCompositionCache may be 50M. The number of caches is not a good solution

**Comment by gpeal** [comment]
@zijinzhiyun Is there an alternative you'd like to propose? What's wrong with the current implementation for your use cases? 20 refers to the number of items, not the number of mb.

**Comment by FeanCheng** [comment]
yep，If we know how to calculate memory size correctly，we can try to limit the memory

**Comment by FeanCheng** [comment]
In my project, a single Lottie may take up to 200Mb of memory

**Comment by FeanCheng** [comment]
Perhaps, we can manually remove the cache or disable cache

**Comment by FeanCheng** [comment]
@gpeal  look here

**Comment by zijinzhiyun** [comment]
> @zijinzhiyun Is there an alternative you'd like to propose? What's wrong with the current implementation for your use cases? 20 refers to the number of items, not the number of mb.

Sorry, we didn't reply in time. Calculate the size of each object in the LottieComposition class, plus the memory of bitmap. In using svga libraries like lottie, I use this method. The problem with this solution is that the calculated memory value is not accurate enough. I don't know if you have a better solution.

**Comment by gpeal** [comment]
You can call `LottieCompositionFactory.clearCache(context)` if you need to clear the cache for your own app's use cases. For now, I think I'm going to leave it up to individual apps to call this unless there is a general solution that works better.
