### ISSUE TITLE
Dynamicly change multiple fill color

### ISSUE THREAD

**Issue by Vensent** [airbnb/lottie-android#2263]
Hi folks. I know there is a method to dynamicly change the color of a path like this:

``
addValueCallback(
    KeyPath("Color_Change", "**"),
    EffectiveAnimationProperty.COLOR_FILTER
) { SimpleColorFilter(colorFilter) }
``

But my question is: how to handle a path with **multiple colors** like this below:
![image](https://user-images.githubusercontent.com/7401921/224987089-466c55d8-b65d-462d-a196-73b576234c55.png)

Here is my lottie file: [http://i.mxzlian.com/18323321629/](url)

**Comment by gpeal** [comment]
You need to find the path for each fill that you want to dynamically change. If you don't know what they are, you can list them all with `lottieDrawable.resolveKeyPath(KeyPath("**"))` and see what it returns.
