### ISSUE TITLE
Height not calculated based on screen width in Jetpack Compose

### ISSUE THREAD

**Issue by sergey-shevtsov** [airbnb/lottie-android#2264]
**Link to fork with a repro in the issue-repro module**
https://github.com/sergey-shevtsov/lottie-android/tree/compose-width-issue/issue-repro-compose

**Describe the bug**
I have an animation that is wider than the screen width. I need to display it in a scrollable column. The animation should fill the screen width and i expect the height to be calculated in the correct ratio. Actually, the animation is displayed correctly, but takes a height equal to the height specified in the json file.
The reason for this is probably that the Canvas in the LottieAnimation component uses `composition.bounds.height()` and `composition.bounds.width()` without any calculation depending on the allowed max width.
```
Canvas(
  modifier = modifier
    .size((composition.bounds.width() / dpScale).dp, (composition.bounds.height() / dpScale).dp)
) {
...
```

**Steps To Reproduce**
1. Add a raw animation json resource with a size larger than the screen size
2. Create a `Column` with `verticalScroll` modifier
3. Put a `LottieAnimation` component with `ContentScale.FillWidth` on the created column

Expected result:
<img src="https://user-images.githubusercontent.com/28695957/225307827-ac482bd8-dce3-443c-a13f-4ff786d7877c.jpg" width="350px">

Actual result:
<img src="https://user-images.githubusercontent.com/28695957/225307871-36ee095e-00b2-433f-b5b7-172bc85808a5.jpg" width="350px">

**Comment by aDragovcic** [comment]
Issue is still present.
