### ISSUE TITLE
Lottie compose: broken binary compatibility between 5.2.0 & 6.0.0

### ISSUE THREAD

**Issue by efemoney** [airbnb/lottie-android#2266]
**Is your feature request related to a problem? Please describe.**
Lottie compose added new parameters to `LottieAnimation` etc which breaks binary compatibility for apps/libraries that depend on **other libraries** compiled against 5.2.0.

**Describe the solution you'd like**
I know its a major version bump but it would've been a lot better for Lottie to maintain the binary compat as much as was possible for a subset of the API (most notably the Compose API) more so if the required effort was minimal.

**Comment by gpeal** [comment]
Can you help me understand what broke? `fontMap` was added as an optional parameter last in the list so whether you were using named or ordered parameters, I don't think any existing calls should have broken. Maybe I'm missing something on the second order effects of libraries though.

**Comment by efemoney** [comment]
So source compatibility is maintained, for anyone that updates, nothing needs to change for compilation.

Binary compatibility however breaks for upgraded users that depend on other libraries that are already compiled against 5.2. 

Because of how kotlin compiles functions, the function signature libraries compile against in 5.2 is `LottieAnimation(a,b,c, defaultMarker)`, from 6.0 the function signature available at runtime is now `LottieAnimation(a,b,c,D, defaultMarker)` so for a user that is upgraded to 6.0, which would cause transitive its dependencies that are pointing to version 5.2 to be upgraded to version 6.0, the latter method will be available at runtime but the already compiled dependencies will be "looking for" the former method signature.

**Comment by gpeal** [comment]
Got it. I think adding `@JvmOverloads` here would generate the necessary backwards compatible bytecode. Is that correct?

**Comment by gpeal** [comment]
@efemoney Can you confirm if `@JvmOverloads` would solve this issue?

**Comment by efemoney** [comment]
`@JvmOverloads` depends. It would work if the previous order was somehow maintained when the new parameters were added. but its less useful for example if a parameter was added  somewhere in the middle of the arguments list. 
For methods with a lot of default parameters it'll also generate a ton of (most likely unused) overloads.

**Comment by gpeal** [comment]
I always add new parameters as optional and at the end for this reason. Considering that most large apps have multidex and use r8, the extra methods should be stripped out of release builds.
