### ISSUE TITLE
Putting LottieLoader in Animated visibility destroys the compose tree

### ISSUE THREAD

**Issue by SharifMrCreed** [airbnb/lottie-android#2267]
**Describe the bug**
When you put the Lottie loader in an animated visibility composable the entire compose tree is rendered for a split second then it disappears

**What version of Lottie did you test this on?**
6.0.0

**What version of Android did you test this on?**
12, 13

**Steps To Reproduce**

1. Create a composable function
2. Add Animated visibility composable
3. Add the Lottie animation composable
4. test it on an emulator

**Screenshots**
![2023-03-25](https://user-images.githubusercontent.com/55756783/227739418-6695c998-520d-4825-a115-9a36b69b3a10.png)

**Comment by gpeal** [comment]
Could you attach a project that reproduces this?

**Comment by gpeal** [comment]
Seems to work for me. Feel free to reopen with a project that reproduces this if you think there is still an issue.

```
    @Composable
    fun Content() {
        val composition by rememberLottieComposition(LottieCompositionSpec.RawRes(R.raw.heart))
        val progress by animateLottieCompositionAsState(composition, iterations = LottieConstants.IterateForever)
        var visible by remember { mutableStateOf(true) }
        Column {
            AnimatedVisibility(visible = visible) {
                LottieAnimation(composition, { progress })
            }
            Button(
                onClick = { visible = !visible }
            ) {
                Text("Toggle")
            }
        }
    }
```

https://user-images.githubusercontent.com/1307745/236696302-aa23b2a8-4752-49c1-b117-695145a7782c.mp4
