### ISSUE TITLE
Something strange on Api 16

### ISSUE THREAD

**Issue by hasdfa** [airbnb/lottie-android#227]
I used example file: EmptyState.jsoun (Like in example).
And, when I run my app at android 4.1.1 (Api 16), watermelon eyes somewhere went)
Api 16:
<img width="250" alt="2017-03-27 17 36 19" src="https://cloud.githubusercontent.com/assets/12295460/24361929/f093a62a-1313-11e7-8fe3-143586aed55f.png">
Api 23 (android 6.0):
<img width="257" alt="2017-03-27 17 36 24" src="https://cloud.githubusercontent.com/assets/12295460/24361931/f29fd678-1313-11e7-808a-66f4402985bb.png">

json file:
[https://drive.google.com/open?id=0B43JPcKqUboZcG1HZko5ejd5bUE](https://drive.google.com/open?id=0B43JPcKqUboZcG1HZko5ejd5bUE)

**Comment by Clarence-Yang** [comment]
I also have the same problem。Is there a solution?

**Comment by gpeal** [comment]
I'm investigating
