### ISSUE TITLE
Smooth timeline forward like in Webflow

### ISSUE THREAD

**Issue by ofmarconi** [airbnb/lottie-android#2270]
**Is your feature request related to a problem? Please describe.**
When the page scrolls very fast the animation also advances super fast, in Webflow this is solved with a smoothness value.

**Describe the solution you'd like**
We need to have a mathematical function that smooths this advance as the scroll happens.

**Describe alternatives you've considered**
Webflow but I want to do this in Elementor Pro.

**Additional context**
How it works in Webflow:
https://www.loom.com/share/0da0e67df4cc43fea4ee50602179d488

**Comment by ofmarconi** [comment]
Where could I intercept the scroll information to put an EASE on the values before getting to the lottie? I think that's what webflow does, for Lottie the scroll is delayed...

**Comment by gpeal** [comment]
You can manually set the progress to whatever you want so you can replace the internal animator with your own. Would that work?

**Comment by ofmarconi** [comment]
@gpeal thanks for the reply! I confess that I did not understand very well, but it seems to be something interesting.

Correct me if I'm wrong:

Is it possible to define the progress in a custom way? instead of being directly related to Scroll or Mouse, would it be related to a **var** ?

Then update how I wanted this variable?

**Comment by gpeal** [comment]
Yes, you can call `setProgress` on LottieDrawable/LottieAnimationView with whatever you want so you can create your own animator or tie it to events like scroll or click events.

**Comment by ofmarconi** [comment]
Thank you, it's a way, I'll study it, it's not so explicit in the documentation...
