### ISSUE TITLE
Animation not play

### ISSUE THREAD

**Issue by SagarArshikweb** [airbnb/lottie-android#2280]
Animation does not play in Samsung S23 Ultra (Android 13). just display as an image, not animation play. in some other devices working fine. It only issues in one device. can anyone help me with this.

**Comment by OtherSun** [comment]
may be animation does not work in android13.Who fixed this?

**Comment by gpeal** [comment]
Are animations disabled via a system setting or battery saver?

**Comment by OtherSun** [comment]
this is my way to fix this question. target sdk v3.7.0

    public static void doAutoPlayAnim(@NonNull ImageView iv, @NonNull String animPath) {
        LottieDrawable drawable = new LottieDrawable();
        LottieResult<LottieComposition> lottieResult = LottieCompositionFactory.fromAssetSync(iv.getContext(), animPath);
        LottieComposition value = lottieResult.getValue();
        drawable.setComposition(value);
        drawable.setFrame(0);
        drawable.setProgress(0f);
        drawable.setRepeatCount(-1);
        Drawable.ConstantState state = drawable.getConstantState();
        iv.setImageDrawable(DrawableCompat.wrap(state == null ? drawable : state.newDrawable()).mutate());

        if (drawable.isRunning()) {
            drawable.stop();
        }
        drawable.playAnimation();
    }

**Comment by SagarArshikweb** [comment]
> Are animations disabled via a system setting or battery saver?

The animator duration scale was off. When I set the scale to 1x working fine for me. Thanks @gpeal

**Comment by SagarArshikweb** [comment]
> this is my way to fix this question. target sdk v3.7.0
> 
> ```
> public static void doAutoPlayAnim(@NonNull ImageView iv, @NonNull String animPath) {
>     LottieDrawable drawable = new LottieDrawable();
>     LottieResult<LottieComposition> lottieResult = LottieCompositionFactory.fromAssetSync(iv.getContext(), animPath);
>     LottieComposition value = lottieResult.getValue();
>     drawable.setComposition(value);
>     drawable.setFrame(0);
>     drawable.setProgress(0f);
>     drawable.setRepeatCount(-1);
>     Drawable.ConstantState state = drawable.getConstantState();
>     iv.setImageDrawable(DrawableCompat.wrap(state == null ? drawable : state.newDrawable()).mutate());
> 
>     if (drawable.isRunning()) {
>         drawable.stop();
>     }
>     drawable.playAnimation();
> }
> ```

Its Animator setting issues in the particular device. solved now. Thanks @OtherSun

**Comment by keechan-kurly** [comment]
> > Are animations disabled via a system setting or battery saver?
> 
> The animator duration scale was off. When I set the scale to 1x working fine for me. Thanks @gpeal

What is a "**duration scale**"? How to set it up?
