### ISSUE TITLE
Load too many json files --> Out Of Memory

### ISSUE THREAD

**Issue by tuanhs0606** [airbnb/lottie-android#2281]
Dear,

Currently I am facing the following problem:
I have about 30 json files, and currently if I need to display all 30 json files I need 30 LottieAnimationView to display 30 json files and use setRepeatCount(LottieDrawable.INFINITE). This leads to Out Of Memory problem
With this case could you suggest me how to solve Out Of Memory problem or is there a way to use 30 json files displayed on 1 LottieAnimationView?

Reguards,
Thank you so much!

**Comment by gpeal** [comment]
Can you do some profiling to determine what is using the memory? Do you have bitmaps in your animations? Lottie itself doesn't use very much memory.

**Comment by tuanhs0606** [comment]
1. Do you have bitmaps in your animations
==> yes
2. please help me check one in them(json file)
https://drive.google.com/file/d/1FFVOuew9Ryv4_TnTPJ0Wviqpynb8hamF/view?usp=sharing

**Comment by gpeal** [comment]
@tuanhs0606 I don't have time to look at your animation right now but, most likely, this has less to do with Lottie and more to do with bitmaps. I'd recommend using the Android Studio memory profiler to see where the memory is being used.

**Comment by tuanhs0606** [comment]
1. >>I'd recommend using the Android Studio memory profiler to see where the memory is being used.
==> sorry because i don't know use this

2. Please check log cat when happen Out Of memory:
java.lang.OutOfMemoryError
        at android.graphics.Bitmap.nativeCreate(Native Method)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1095)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1041)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:991)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:952)
        at com.airbnb.lottie.LottieDrawable.ensureSoftwareRenderingBitmap(LottieDrawable.java:1533)
        at com.airbnb.lottie.LottieDrawable.renderAndDrawAsBitmap(LottieDrawable.java:1486)
        at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:525)
        at android.widget.ImageView.onDraw(ImageView.java:1360)
        at android.view.View.draw(View.java:21868)
        at android.view.View.updateDisplayListIfDirty(View.java:20741)

![image](https://user-images.githubusercontent.com/8426489/235287480-c8dbf093-d383-4cb3-b20d-c394578f224b.png)

**Comment by gpeal** [comment]
Can you set the render mode to hardware?

**Comment by tuanhs0606** [comment]
@gpeal 
Sorry I haven't been able to go online and reply to you for the past few days

>Can you set the render mode to hardware?
==> Yes, I also tried with this setting
animationView.setRenderMode(RenderMode.HARDWARE);

Please check the json file with more size than I am using(About 14Mb):
https://drive.google.com/file/d/1XhUESPey7IjGq5xfTF59ofpZaPvJ81nb/view?usp=sharing

. Thank you!

**Comment by tuanhs0606** [comment]
@gpeal Could you help me about my problem above?

**Comment by snehilrx** [comment]
@tuanhs0606 Can you share the preview of screen that you are trying to build  using layout inspector. I think this issue maybe due to not using recyclerview or not using recyclerview properly (recyclerview with wrap content inside nested scrollview)

**Comment by gpeal** [comment]
I fixed a likely unrelated bug I discovered while taking a look at your animation. However, you have 181 720p bitmaps in your animation. Lottie is meant to be a vector renderer. If you're going to load effectively png sequences, you're likely better off with something else.

**Comment by tuanhs0606** [comment]
@gpeal Thanks for your support. I check memory in app by use Profiler tool. I see the following:
- use clear cache but not work:
LottieCompositionFactory.clearCache();

- But using these lines of code it can see clear memory:
>animationViewEffect.setCacheComposition(true);
animationViewEffect.setRenderMode(RenderMode.SOFTWARE);
animationViewEffect.enableMergePathsForKitKatAndAbove(true);
animationViewEffect.setRepeatCount(LottieDrawable.INFINITE);
animationViewEffect.setAnimationFromJson(lottieJsonEffect, pathLottieJson);
(Not set play for animationViewEffect)

Can you help me explain?

**Comment by tuanhs0606** [comment]
@gpeal Thank you. Could you help me suggest me how to optimize the display like lottie view and set the background color to be transparent?

**Comment by b1tb1t** [comment]
I have same issue, native bitmap memory 200MB, I use reflect call LottieImageAsset bitmap recycle

**Comment by OhPeterPan** [comment]
> 我有同样的问题，本机位图内存 200MB，我使用反射调用 LottieImageAsset 位图回收 或 动画结束后直接设置一个新的空资源 lottieAnimView.setAnimation(R.raw.empty)

What is the Empty file format? I created a.json file, but it directly triggered the crash

**Comment by b1tb1t** [comment]
> > 我有同样的问题，本机位图内存 200MB，我使用反射调用 LottieImageAsset 位图回收 或 动画结束后直接设置一个新的空资源 lottieAnimView.setAnimation(R.raw.empty)
> 
> What is the Empty file format? I created a.json file, but it directly triggered the crash

"{}"
