### ISSUE TITLE
JVM Artifact for validating Lottie JSON strings

### ISSUE THREAD

**Issue by vanniktech** [airbnb/lottie-android#2283]
**Is your feature request related to a problem? Please describe.**

I'm adding a feature where you can change the lottie animations from the frontend clients by sending the JSON to the backend which then distributes it to all affected users. 

I'd like to have a way on the backend servers to somehow validate that the JSON is somewhat of a valid lottie file.

**Describe the solution you'd like**

A JVM only artifact, with which I could try parsing the response and if it fails throw an error.

**Describe alternatives you've considered**

-

**Additional context**

-

**Comment by vanniktech** [comment]
Not exactly, since my backend is completely written in Kotlin and has no frontend web application.

**Comment by gpeal** [comment]
Realistically, this would be fairly low on my priority list for Lottie (although I do prioritize feature requests from sponsors).

You could fork the repo and manually create this though. That code doesn't change very often.

**Comment by vanniktech** [comment]
Understandable. `LottieCompositionMoshiParser` is a good starting point although `LottieComposition` contains some references to Android so it's not that easy to pull out.

**Comment by gpeal** [comment]
I think that's right. I'm likely going to close this as something that won't be supported in the core library but you could try to do the work above to create a JVM artifact on your own if you'd like.
