### ISSUE TITLE
After converting to json format, the animation is not displayed in the android project！

### ISSUE THREAD

**Issue by ruijindp** [airbnb/lottie-android#229]
When using the bodymovin plugin to convert the aep file to json, then put the json file into the android project, the result does not show the animation effect, the bodymovin plugin uses the latest version, lottie relies on the 2.0.0-beta3 version.

**Comment by gpeal** [comment]
@ruijndp can you attach the aep file?

**Comment by ruijindp** [comment]
the aep file :   [http://7xpl2d.com1.z0.glb.clouddn.com/num.aep](http://7xpl2d.com1.z0.glb.clouddn.com/num.aep)
Converted json file：[http://7xpl2d.com1.z0.glb.clouddn.com/num.json](http://7xpl2d.com1.z0.glb.clouddn.com/num.json)

Thank you very mach!

**Comment by gpeal** [comment]
Lottie doesn't support Text yet. Can you create your animation using shapes instead?

**Comment by ruijindp** [comment]
We do with the shape of the way to do, use the mask and the path to do, but still do not show.

The aep file: [http://onpl11ugz.bkt.clouddn.com/three.aep](http://onpl11ugz.bkt.clouddn.com/three.aep)
