### ISSUE TITLE
Compose Lottie with Cavans in scrolling component problem

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [airbnb/lottie-android#2291]
``When I use Lottie (Lottie loop animation) and Cavans at the same time in Compose scrolling component, it will lead to infinite reorganization inside Cavans, but outside is no problem, I remove Lottie and replace it with static image or Lottie set to play only once, also no problem. The sample code is as follows:

```kotlin
Column(modifier = Modifier.fillMaxWidth().horizontalScroll(scrollState)) {
Row( ){
list.forEach {
            LottieAnimation(
                composition,
                iterations = LottieConstants.IterateForever,
                modifier = Modifier.size(itemWidth)
            )
}
  Canvas(modifier = Modifier.size(list.size * itemWidth, 124.dp)) {
            Log.d("test", "onDraw")
}
}
}
```

**Comment by gpeal** [comment]
What do you mean by "infinite reorganization"?

**Comment by AndroidJohnsonWang** [comment]
@gpeal Log will print in an infinite loop

**Comment by gpeal** [comment]
Compose can recompose only parts of the tree but Android redraws the entire screen on every frame. If there is a Lottie animation playing then anything that draws will need to redraw. This will be true if anything that is rendering an animation.

**Comment by AndroidJohnsonWang** [comment]
Maybe I didn't express myself clearly, I think this is a bug, because the scroll modifier horizontalScroll is removed or they are not placed under the same Column there will be no problem

**Comment by gpeal** [comment]
You may have to provide more info here. I just ran your sample code and the Log prints on every frame but it doesn't recompose. You can see in the video that despite the logs, Compose isn't recomposing.

What is happening is that Android draws the entire frame every time by default. If you would like to render Lottie to a separate graphics layer that is used instead, you can add the `graphicsLayer()` modifier to `LottieAnimation`.

https://github.com/airbnb/lottie-android/assets/1307745/be25e802-8591-4099-9c50-e7794de8c3ce
