### ISSUE TITLE
Alpha behaves differently on Android than iOS

### ISSUE THREAD

**Issue by vanniktech** [airbnb/lottie-android#2295]
This is my Android code:

```
private fun LottieTask<LottieComposition>.asDrawable(
  alpha: Float,
): Drawable {
  val lottieDrawable = LottieDrawable()
  lottieDrawable.alpha = (alpha * 255f).roundToInt()

  addListener {
    lottieDrawable.composition = it
    lottieDrawable.start()
  }

  addFailureListener {
    Timber.tag("Lottie").w(it)
  }
  lottieDrawable.repeatCount = ValueAnimator.INFINITE
  lottieDrawable.speed = 1f
  return lottieDrawable
}
```

Using the following animation: https://app.lottiefiles.com/share/7088733f-7546-41b4-be5f-59f79cb97955 and an alpha value of 0.5, I get two different results on Android (left side) vs iOS (right side):

![lottie](https://github.com/airbnb/lottie-android/assets/5759366/1ef4aab7-05f7-43f0-b128-8cc5e47a11c1)

I personally would have expected the behavior from iOS. That the elements are using alpha values, but you can't actually see through them.

Unwanted behavior on Android:

<img width="87" alt="Screenshot 2023-05-13 at 00 44 47" src="https://github.com/airbnb/lottie-android/assets/5759366/50a183b2-71f2-46e1-8d3a-fb2a7d6f935c">

vs my desired behavior:

<img width="94" alt="Screenshot 2023-05-13 at 00 45 17" src="https://github.com/airbnb/lottie-android/assets/5759366/07a98bd1-4493-4654-93fe-e66b8992059e">

Is this behavior expected / desired on Android?

**Comment by gpeal** [comment]
Can you try with [applyOpacityToLayers](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L1191)?

**Comment by vanniktech** [comment]
Indeed, that's the thing I need. The name is a bit unfortunate though. I was looking for flag like this but only searched for `alpha` not for `opacity`. Thanks!
