### ISSUE TITLE
Blur Effect does not work on Android 8

### ISSUE THREAD

**Issue by ConCaRo** [airbnb/lottie-android#2296]
I am trying to apply the Lottie animation with Blur Effect. Most of devices works well, except Android Devices run Android 8.
 
<img width="497" alt="Screenshot 2023-05-18 at 10 10 24" src="https://github.com/xvrh/lottie-flutter/assets/13360030/14c9ad77-de29-43e6-8247-e3989607368c">

The left device of above image does not apply the blur effect (the right device applied)
I try to search but not found the solution. As I checked here http://airbnb.io/lottie/#/supported-features, it seems that  the Blur Effect is supported from 4.1.

**Comment by gpeal** [comment]
Lottie Flutter is an entirely separately library so you'll have to continue this conversation in your original issue.
