### ISSUE TITLE
Crash in GradientColor.lerp in 5.2 and later

### ISSUE THREAD

**Issue by imbryk** [airbnb/lottie-android#2298]
**Describe the bug**
After https://github.com/airbnb/lottie-android/pull/2081 has been merged, certain animations with gradient trasforms are crashing.

The issue is that here:
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/parser/GradientColorParser.java#L148
the length of steps for GradientColor can change, and this can result in 
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/animation/keyframe/GradientColorKeyframeAnimation.java 
receiving GradientColors of different lengths.

This eventually leads to crash in this line:
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/model/content/GradientColor.java#L37
with 
`java.lang.ArrayIndexOutOfBoundsException`

**What version of Lottie did you test this on?**
versions `5.2` and `6.0` experience the crash
version `5.1.1` works fine (it's before the mentioned PR has been merged)

**What version of Android did you test this on?**
Android version makes no difference - the crash is related to library code and specific lottie files

**Steps To Reproduce**
I've provided the crasshing lottie files to @gpeal 
Every attempt to display the animation ends with `ArrayIndexOutOfBoundsException`

**Screenshots**
the app just crashes

**Comment by gpeal** [comment]
Could you provide an animation (preferably an AEP file) that crashes?

**Comment by fadi-quader-mox** [comment]
My app crash with same exact error. It used to work before i bumped to latest version.
<img width="985" alt="image" src="https://github.com/airbnb/lottie-android/assets/102506966/52db89fb-0814-4656-98dc-c15e0fb92606">

**Comment by gpeal** [comment]
Can you attach an animation that causes the crash? It'll be hard to debug or fix this without it.

**Comment by fadi-quader-mox** [comment]
@gpeal Could you please share with me how I can contact you or where I can send the files?
Feel free to reach me out via LinkedIn https://www.linkedin.com/in/fadi-quader-268837119/

**Comment by gpeal** [comment]
You can send it to lottietestapps [at] gmail

**Comment by MSchmidt** [comment]
@gpeal I've sent you another animation that crashes with `java.lang.ArrayIndexOutOfBoundsException`. Hope it helps.
