### ISSUE TITLE
Inquiry about the stability of DotLottie since the last release was in 2021

### ISSUE THREAD

**Issue by PiyushZomato** [airbnb/lottie-android#2299]
I'm writing to inquire about the stability of the [DotLottie](https://github.com/dotlottie/dotlottieloader-android) loader in Android since its last release in 2021. As an avid user of your libraries, I'm considering integrating it into my project, but I wanted to gather more information about their current stability before proceeding.

I noticed that the last release was in 2021, and I'm curious to know if there have been any significant updates, bug fixes, or improvements since then. Could you kindly provide some insight into the following questions:

1. Have any significant stability issues been reported or resolved since the last release?
2. Are there any known limitations or compatibility issues that I should be aware of?

Understanding the current state of it would be greatly helpful in making an informed decision for my project.

Thank you for your time and attention to this matter.

**Comment by gpeal** [comment]
I'm not sure I follow the question. dotLottie is just a zip file and the android player doesn't do anything special with them. They "just work". I'm also not familiar with that particular library so you'll have to ask the author there if you have any specific questions.
