### ISSUE TITLE
Incorrect documentation in LottieProperty

### ISSUE THREAD

**Issue by andrewzeng** [airbnb/lottie-android#2301]
**Link to fork with a repro in the issue-repro module**: https://github.com/andrewzeng/lottie-android-documentation-stroke

**Describe the bug**: LottieProperty documentation for non gradient Stroke seems wrong. `StrokeContent` only supports `STROKE_COLOR` and `COLOR_FILTER` not `COLOR` (ignoring properties from `BaseStrokeContent`, which doesn't contain either `COLOR` or `STROKE_COLOR`)

**Steps To Reproduce**

1. Run activity in issue-repro
2. Look for blue "explode" particles on the heart animation (which should be using stroke). Comment out the repro case not currently being tested (working vs not working)

**Comment by gpeal** [comment]
Updated
https://github.com/airbnb/lottie/commit/8e4ef6ea261e427854271a40e1fef67ec198d6d4
