### ISSUE TITLE
Rounded edges become distorted after stretching 

### ISSUE THREAD

**Issue by mialkan** [airbnb/lottie-android#2307]
**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features). ✅
3. I know what part of my animation doesn't work. ✅
4. I have created a simplified version of my animation ✅
5. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work. ✅

[AEP file ](https://sdui.s3.eu-west-1.amazonaws.com/progressbar_v1.zip)
[Animation JSON](https://sdui.s3.eu-west-1.amazonaws.com/pb_report_v1.json)
[Example Android Project ](https://github.com/mialkan/LottieProgressCornerRadius)

**Describe the bug**
When cornered progress bar stretched rounded edges become distorted. 

Is there a workaround without applying corner radius to LottieView? 

Or what can be done within AEP? 

**What version of Lottie did you test this on?**
6.0.0

**What version of Android did you test this on?**
API level 32

**Steps To Reproduce**
Rotate device to landscape while having full width progress bar.

**Screenshots**

![Screenshot_1686059552](https://github.com/airbnb/lottie-android/assets/2021635/e1ef27c0-31a8-4850-9c12-5c1d155be7e2)

**Comment by gpeal** [comment]
Unfortunately, this would be tricky to do with Lottie. Lottie is designed to render animations that have predefined aspect ratios. It has the content fill property but that will distort the aspect ratio as you have seen.

You can try to do this with dynamic properties but I'm not sure if there is a great out of the box solution here.
