### ISSUE TITLE
Unzip files with a different extension(like Telegram's tgs)

### ISSUE THREAD

**Issue by Fra078** [airbnb/lottie-android#2313]
**Is your feature request related to a problem? Please describe.**
It's not possible to force lottie to read a zipped file with a different extension. I'm developing a telegram client, but telegram stickers are lottie files with images zipped into a **.tgs** file.

**Describe the solution you'd like**
I think that on Lottie Compose should be in the class LottieCompositionSpec.File a boolean argument that when is true will force lottie to ignore extension and try to unzip anyway (Throwing an error if the file is not a zip) 

**Describe alternatives you've considered**
Add tgs as file format supported because Telegram is open source, so a lot of developers can have this issue

**Comment by kudanai** [comment]
Adding some additional context here:

1. `lottie-android` should be able to pick up a zip file regardless of the file extension, as it relies on the header for identification (if it's coming from assets/raw)
2. `tgs` is not a zip file, it's actually gzip which is quite different. gzip is not (afaik) natively supported on java/android and will likely require additional dependencies
