### ISSUE TITLE
Request: have a function to decide if the given file (.json, .lottie...) is a valid Lottie animation file that can be played on Android

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [airbnb/lottie-android#2314]
**Is your feature request related to a problem? Please describe.**
Given a list of files, some with "json" extensions (which can happen) for example, I want to be able to filter them so that I could see which are valid Lottie files and which aren't.

**Describe the solution you'd like**
A function that returns true/false, if the library could show the file.
The parameter of the function could be Uri/Url/file-path. Maybe others too, but I think these should be fine.

**Describe alternatives you've considered**
I could call the parsing of the file and use try-catch.
But I don't want to waste memory and time of the device for this operation.

**Additional context**
I couldn't find this function.

**Comment by gpeal** [comment]
I would recommend using `LottieCompositionFactory` and adding a listener/failure listener to create your own wrapper that returns true/false if it succeeds or fails.

**Comment by AndroidDeveloperLB** [comment]
@gpeal But doesn't it mean that it saves stuff to memory and wastes CPU time on preparing everything?
For various file formats, it's enough to parse the headers, no?
Here it's quite different, as it's JSON.
Not sure about the binary format of ".lottie", though.
Do you know perhaps how ".lottie" files are formatted? Is it just like JSON, but in binary form instead of textual?

**Comment by AndroidDeveloperLB** [comment]
@gpeal Thank you very much for the full explanation!

I wish I had such an experience with Google support (especially Play policy team).
