### ISSUE TITLE
Rendering problem

### ISSUE THREAD

**Issue by xgear-public** [airbnb/lottie-android#232]
Hello!
I have issue with animation rendering (Trim Paths presumably). Designer [made animation](http://image.prntscr.com/image/2e18a186e27f4b8ab8affc1d9389f76c.png) of 1 frame and 4 circles. frame and 2 circles has path animation clockwise, 2 other circles animates counter clockwise. So on the end of animation those elements which animated CW - disappear on device. If i run html in browser (bodymoving created file) with animation - it behaves as expected. The issue is that it works different on browser and on device, and on device animation works not as expected.

I [uploaded](https://drive.google.com/drive/folders/0B28j7WrdT7o2d1g1bFBZSGxza1U?usp=sharing) .aep json html and test android project.

Is it rendering problem or designer mistake?

**Comment by gpeal** [comment]
This will be fixed in beta4

**Comment by xgear-public** [comment]
Problem still exist after updating library version to [2.0.0-beta4](https://github.com/airbnb/lottie-android/milestone/4)
