### ISSUE TITLE
Animation contains merge path warnings

### ISSUE THREAD

**Issue by ketanMuttha** [airbnb/lottie-android#2321]
**Describe the bug**

**What version of Lottie did you test this on?** 6.0

**What version of Android did you test this on?** Google Pixel 6, android 13.

**Steps To Reproduce**

I am getting a warning saying "Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling **enableMergePathsforKitKatAndAbove**()"

I used **enableMergePathsforKitKatAndAbove**(true) though, I can see still see the warnings.

Also, How to fix this warning while generating a lottie file?

**Comment by gpeal** [comment]
The warnings are static and aren't designed to go away when you enable/disable APIs.
