### ISSUE TITLE
Release notes and tag for 6.0.1 doesn't exist

### ISSUE THREAD

**Issue by vitoksmile** [airbnb/lottie-android#2322]
There is a new version [6.0.1 in maven](https://mvnrepository.com/artifact/com.airbnb.android/lottie/6.0.1), but no release notes or tags are created.
In "Releases" we have only 6.0.0 as latest release.

**Comment by gpeal** [comment]
Done

https://github.com/airbnb/lottie-android/releases/tag/v6.0.1
