### ISSUE TITLE
When I set a different size, the animation flashes

### ISSUE THREAD

**Issue by zhangzhuo1024** [airbnb/lottie-android#2329]
**What version of Lottie did you test this on?**
implementation 'com.airbnb.android:lottie:6.0.0'

**What version of Android did you test this on?**
android11

The same json file, when I set the LottieAnimationView to a smaller size, the animation worked fine; When I set the LottieAnimationView to a larger size, the animation flashes

    <com.airbnb.lottie.LottieAnimationView
        android:layout_width="match_parent"
        android:layout_height="500dp"
        app:lottie_autoPlay="true"
        app:lottie_fileName="91502-waves.json"
        app:lottie_loop="true"
        app:lottie_speed="1" />
    <com.airbnb.lottie.LottieAnimationView
        android:layout_width="180dp"
        android:layout_height="180dp"
        app:lottie_autoPlay="true"
        app:lottie_fileName="91502-waves.json"
        app:lottie_loop="true"
        app:lottie_speed="1" />

![videotogif_20230704_163943](https://github.com/airbnb/lottie-android/assets/23216091/75724ea9-ed0a-4692-b94d-e1d466ed0199)

**Comment by zhangzhuo1024** [comment]
The same results were found on the simulator

**Comment by gpeal** [comment]
Can you attach your animation? Does this happen when you set renderMode to both software and hardware?

**Comment by zhangzhuo1024** [comment]
[mywaves.zip](https://github.com/airbnb/lottie-android/files/12066369/mywaves.zip)

Adding Android: hardwareAccelerated="true" to the activity also has no effect
