### ISSUE TITLE
LottieProperty.TEXT not working properly on Compose

### ISSUE THREAD

**Issue by vaibhav30699** [airbnb/lottie-android#2330]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Describe the bug**
I tried using LottieProperty.TEXT on one of my animations and the text is partially shown and that too characters from in between.

**What version of Lottie did you test this on?**
Latest version. Like I added the following dependency in my android project

```implementation("com.airbnb.android:lottie-compose:_")```

**What version of Android did you test this on?**

Android 13 (API 33)

**Steps To Reproduce**

1. Add LottieProperty.TEXT as one of the dynamic properties for the animation
2. Only partial text will be shown on the animation and full text is not there.

**Screenshots**

![Screenshot_20230705-121412](https://github.com/airbnb/lottie-android/assets/89007423/b974e3d8-38b1-47cf-bbd0-b012653ce61d)

<img width="787" alt="Screenshot 2023-07-05 at 12 14 02 PM" src="https://github.com/airbnb/lottie-android/assets/89007423/11a1d978-0238-4b9c-a8d8-8d452f750a9e">

**Comment by ArthurVimond** [comment]
Hi @vaibhav30699,
I didn't see your Lottie JSON file but I'm pretty sure that's the same reason as this issue: https://github.com/airbnb/lottie-android/issues/2324. To be confirmed though.

**Comment by vaibhav30699** [comment]
Hi @ArthurVimond,
Because of confidential data, I can't upload the JSON here. But, thank you for referencing to the issue. Let me check and reply on this thread.

**Comment by gpeal** [comment]
@ArthurVimond is correct here, thanks for explaining this to them! This is not related to Compose though, Compose and Views share the same code path here.
