### ISSUE TITLE
App crashing when using 2 different versions of lottie

### ISSUE THREAD

**Issue by hiteshchopra11** [airbnb/lottie-android#2331]
Hi lottie team, I am facing a crash related to lottie when using 2 different versions of lottie.

I have two modules in my app module A and module B

Module A -: Lottie version 4.1.0
Module B -: Lottie version 6.0.1

Module A has a dependency of Module B, and when I call a Composable function from Module B that uses Lottie version 4.1.0), inside Module A (that uses lottie version 6.0.1), the app crashes, here are the logs -:

https://hastebin.com/share/wusequfibo.wasm

Sample project to reproduce the issue -:
https://github.com/hiteshchopra11/lottie-issue

There is an "app" module in the app that has a dependency on the "data" module. The data module contains lottie version 4.1.0, however the app module uses version 6.0.1. A composable function named **_OldLottieUrlAnimationView_** is present inside the data module, which is called from the app module in _**MainActivity**_

Steps to reproduce the issue -:
Open the app and the app crashes

APK for the above issue -:
https://github.com/hiteshchopra11/lottie-issue/blob/main/app-debug.apk

**Comment by gpeal** [comment]
You should not expect shipping two versions of the same library to work. You'll need to resolve the version conflicts within your app.
