### ISSUE TITLE
The actual length of time the Lottie animation executes

### ISSUE THREAD

**Issue by zcliyiran** [airbnb/lottie-android#2340]
val lottieListener = object : Animator.AnimatorListener {
            override fun onAnimationStart(animation: Animator) {
     

            }

            override fun onAnimationEnd(animation: Animator) {
  
              mPostHandler.sendEmptyMessage(onLottieEnd )
            }

            override fun onAnimationCancel(animation: Animator) {

            }

            override fun onAnimationRepeat(animation: Animator) {
       
        
            }
        }
       loadingLottie?.addAnimatorListener(lottieListener)
       mPostHandler.sendEmptyMessageDelayed(onMaxLottie, 5000 )
       loadingLottie.playAnimation()

Assuming that my LottieAnimationView animation is 3s, is it possible that my onMaxLottie message is received earlier than my onLottieEnd message on a poorly performing phone

**Comment by gpeal** [comment]
@zcliyiran No, the animation should continue at the correct speed regardless of whether or not there were dropped frames.
