### ISSUE TITLE
Need to play lottie animation on last frame directly, but LottieClipSpec.Frame(endFrame?.toInt(),endFrame?.toInt())

### ISSUE THREAD

**Issue by naginder14** [airbnb/lottie-android#2343]
Hi Team, 
**Issue**: Trying to play Lottie animation on last frame only, but  it show a fraction of second "**start**" animation also.... which causing it seem like  a flickering issue.
Below are the trials below:
1)val progress by animateLottieCompositionAsState(
                                    composition,
                                    iterations = 1,
                                    isPlaying = true,
                                    speed = 1f,
                                    clipSpec = LottieClipSpec.Frame(endFrame?.toInt(),endFrame?.toInt())
                                ) 
2) val progress by animateLottieCompositionAsState(
    composition,
    iterations = 1,
    isPlaying = true,
    speed = 1f,
    clipSpec = LottieClipSpec.Progress(1f,1f))
    
  Above are the trials to fix this issue but not works for me.

**Comment by gpeal** [comment]
Can you attach a full project that reproduces this?

**Comment by naginder14** [comment]
> Can you attach a full project that reproduces this?

Thanks for the response.
Is the above details not enough for this query? 

>

**Comment by gpeal** [comment]
I prioritize issues from sponsors and with full projects because they are easier for me to guarantee a repro. This allows me to spend more time working on improvements instead of reproing issues.

**Comment by MotionScript-K** [comment]
> I prioritize issues from sponsors and with full projects because they are easier for me to guarantee a repro. This allows me to spend more time working on improvements instead of reproing issues.

I have a similar problem. I'm trying to start the first part of the animation and when clicked again, start the second part.
Please help me. I'm a beginner
@Composable
fun CatThreeState() {

    val composition by rememberLottieComposition(
        spec = LottieCompositionSpec.RawRes(resId = R.raw.cattwostate)
    )
    var startEnd by remember {
        mutableStateOf(false)
    }
    var appLaunchedFirstTime by remember {
        mutableStateOf(true)
    }
    var isPlaying by remember {
        mutableStateOf(false)
    }

    val progressOne by animateLottieCompositionAsState(
        composition = composition,
        isPlaying = isPlaying,
        clipSpec = LottieClipSpec.Progress(0f, 0.5f),
        iterations = 1,

    )
    LaunchedEffect(key1 = progressOne) {
        if (!appLaunchedFirstTime) {

            if (progressOne == 0f) {
                isPlaying = true
            }

            if (progressOne == 0.5f) {
                isPlaying = false
            }
        }
    }

    val progressTwo by animateLottieCompositionAsState(
        composition = composition,
        isPlaying = isPlaying,
        clipSpec = LottieClipSpec.Progress(0.5f, 1f),
        iterations = 1,

    )
    LaunchedEffect(key1 = progressTwo) {
        if (!appLaunchedFirstTime) {

            if (progressTwo == 0.5f) {
                isPlaying = true
            }

            if (progressTwo == 1f) {
                isPlaying = false
            }
        }
    }

    LottieAnimation(
        progress = {
            if (startEnd) {
                progressOne
            } else {
                progressTwo
            }
        },
        modifier = Modifier
            .size(size = 200.dp)
            .clickable(
                interactionSource = remember { MutableInteractionSource() },
                indication = null
            ) {
                appLaunchedFirstTime = false
                startEnd = (!startEnd)
                isPlaying = true
            },
        composition = composition,
    )
}

**Comment by MotionScript-K** [comment]
maybe it will also be useful to know that this code works without errors if I put an animation of 20 frames. 1 frame jumps between state changes in 0.5 when I use a lottie with a duration of 60 frames

**Comment by gpeal** [comment]
@MotionScript-K I believe this is a simpler version of what you want:

```
val composition by rememberLottieComposition(spec = LottieCompositionSpec.RawRes(resId = R.raw.heart))
var clicks by remember { mutableIntStateOf(0) }

val progress by animateLottieCompositionAsState(
    composition = composition,
    isPlaying = clicks >= 1,
    clipSpec = if (clicks <= 1) LottieClipSpec.Progress(0f, 0.5f) else LottieClipSpec.Progress(0.5f, 1f),
    iterations = 1,
)
LottieAnimation(
    composition,
    progress = { progress },
    modifier = Modifier
        .size(size = 200.dp)
        .clickable(
            interactionSource = remember { MutableInteractionSource() },
            indication = null,
        ) { clicks++ },
)
}
```

@naginder14 I don't understand your issue from what you have provided. Feel free to open with a sample project or more information if you need help.
