### ISSUE TITLE
Sample app is not using recent Lottie release

### ISSUE THREAD

**Issue by lwasyl** [airbnb/lottie-android#2349]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**Is your feature request related to a problem? Please describe.**
It's unclear whether https://play.google.com/store/apps/details?id=com.airbnb.lottie can be reliably used to test lottie files:
 - ~there's no indication which Lottie version is used in the app~ there is when running the animation, I missed that initially
 - the app seems to be last updated in February 2022, and uses Lottie 5.0.1 version that might not reflect current behavior

**Describe the solution you'd like**
https://play.google.com/store/apps/details?id=com.airbnb.lottie is regularly updated with the current Lottie version, so it can be used as a reference 

**Describe alternatives you've considered**
Building sample app myself. Such app would have to be distributed manually, whereas the sample app is easily installable from Google Play

**Additional context**
None

**Comment by gpeal** [comment]
It should be much more recent now.
