### ISSUE TITLE
There's a Exception to load json file, I provide the json

### ISSUE THREAD

**Issue by SwayChen** [airbnb/lottie-android#235]
I don't know if the something wrong with json, but it was exported by AE. Please spend some time, Thanks very much!

I found something wrong in codes. If json contains ".png", must provide the images folder. I use AI and then Export into AE, it has no png images! @seanfchan 

[failed_anim.json.zip](https://github.com/airbnb/lottie-android/files/880899/failed_anim.json.zip)

```
java.lang.IllegalStateException: 
You must set an images folder before loading an image. Set it with LottieComposition#setImagesFolder or LottieDrawable#setImagesFolder                                                           
at com.airbnb.lottie.ImageAssetBitmapManager.bitmapForId(ImageAssetBitmapManager.java:70)
```

**Comment by SwayChen** [comment]
I found something wrong in codes. If json contains ".png", must provide the images folder. I use AI and then Export into AE, it has no png images!

**Comment by seanfchan** [comment]
@SwayChen not exactly sure what the problem is, but here a few thing to try.

1. Some data json generated by bodymovin is also accompanied by an image, did you try putting the image in the asset folder as well?
2. You can try calling LottieAnimationView#setImageAssetsFolder to set which folder Lottie should try to search for assets

@gpeal any other thoughts?

**Comment by gpeal** [comment]
@SwayChen When you import an Illustrator layer, convert your AI layer to a shape layer or else bodymovin will export it as a png.
https://helpx.adobe.com/after-effects/atv/cs6-tutorials/converting-imported-vector-graphics-from-illustrator-to-shape-la.html

**Comment by SwayChen** [comment]
Thanks for your reply, I will try it!

**Comment by fdnhkj** [comment]
I just found the documentation about AI layers and the tip about converting them to shapes in bodymovin wiki [bodymovin/bodymovin/wiki/Shapes#illustrator-layers](https://github.com/bodymovin/bodymovin/wiki/Shapes#illustrator-layers)

**Comment by SwayChen** [comment]
@fdnhkj Thanks a lot! I just send the wiki page to our designer :)
