### ISSUE TITLE
Large memory footprint

### ISSUE THREAD

**Issue by zj-zhenglinfei** [airbnb/lottie-android#2352]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**Is your feature request related to a problem? Please describe.**
I open android studio profiler,I found a variable cost 33M memory which  name is EmojiCompat
![image](https://github.com/airbnb/lottie-android/assets/135192027/1eb3db2e-0945-4cda-a0b4-a302cdecb54d)
I didn't use EmojiCompat other places

**Describe the solution you'd like**
remove this memory cost or the reason why can't remove

**Describe alternatives you've considered**
I have no idea

**Additional context**
no anymore,thanks

**Comment by mgungorchamp** [comment]
Have you found the solution I have the same issue.  What was it causing?
