### ISSUE TITLE
[Compose] Loading from Url and RawRes renders differently

### ISSUE THREAD

**Issue by LaurynasM-iproyal** [airbnb/lottie-android#2357]
**Description:**
There is an issue with scaling when loading lottie from URL and loading same lottie from raw .json file from resources. Some devices do not scale correctly. Tested on various emulator screen size and on Samsung A13 and it seems to work fine both ways. While Xiaomi Poco F3 and Samsung S23+ make Lotties way bigger than it supposed to be. Although loading lotties from Raw works as expected.

**What version of Lottie did you test this on?**

1. 6.1.0
2. 6.0.0
3. 5.0.1

**What version of Android did you test this on?**

1. Emulators - Android 6 and 13
2. Samsung Galaxy A13 - Android 13
3. Xiaomi Poco F3 - Android 13
4. Samsung S23+ -Android 13

**Steps To Reproduce**

@Preview
@Composable
private fun Test() {
    val composition: LottieComposition? by rememberLottieComposition(spec = LottieCompositionSpec.Url(storedLottieInUrl))
//                val composition: LottieComposition? by rememberLottieComposition(spec = LottieCompositionSpec.RawRes(R.raw.test))
    Box(modifier = Modifier.fillMaxSize()) {
        LottieAnimation(
            modifier = Modifier.background(Color.Red),
            composition = composition,
            iterations = LottieConstants.IterateForever,
        )
    }
}

**Screenshots**
Screenshots taken on Xiaomi Poco F3, where larger lottie (RED) is loaded from Url and smaller (RED) loaded from RawRes
![image](https://github.com/airbnb/lottie-android/assets/133742156/52ffa8ea-fc51-47ed-992f-bc21738d2fe7)
![image](https://github.com/airbnb/lottie-android/assets/133742156/bf0d678f-2f09-4d08-814a-e5468e10b56e)

**Comment by gpeal** [comment]
Can you attach an animation that does this? I can't help you without a repro.
