### ISSUE TITLE
IllegalArgumentException:Invalid Layer Save Flag - only ALL_SAVE_FLAGS is allowed

### ISSUE THREAD

**Issue by obamakang** [airbnb/lottie-android#2358]
Caused by:
5
java.lang.IllegalArgumentException:Invalid Layer Save Flag - only ALL_SAVE_FLAGS is allowed
6
android.graphics.Canvas.checkValidSaveFlags(Canvas.java:378)
7
android.graphics.Canvas.saveLayer(Canvas.java:455)
8
com.airbnb.lottie.utils.Utils.void saveLayerCompat(android.graphics.Canvas,android.graphics.RectF,android.graphics.Paint,int)(Utils.java:298)
9
com.airbnb.lottie.model.layer.BaseLayer.void draw(android.graphics.Canvas,android.graphics.Matrix,int)(BaseLayer.java:311)
10
com.airbnb.lottie.model.layer.CompositionLayer.void drawLayer(android.graphics.Canvas,android.graphics.Matrix,int)(CompositionLayer.java:128)
11
com.airbnb.lottie.model.layer.BaseLayer.void draw(android.graphics.Canvas,android.graphics.Matrix,int)(BaseLayer.java:259)

**Comment by obamakang** [comment]
how to solve this problem?

**Comment by obamakang** [comment]
This bug occurs very frequently. Please raise its priority and solve it as soon as possible. Thank you!

**Comment by gpeal** [comment]
Can you provide more information? An animation or device? The only way I can see this being thrown is for a device that claims to be API level 21 or lower but is actually 28 or higher.
