### ISSUE TITLE
Particular animation crashes 2.0.0

### ISSUE THREAD

**Issue by iggyfisk** [airbnb/lottie-android#236]
Attached is an animation JSON with a winking smiley face. On v1.5.3 it works fine, with v2.0.0-beta3 it crashes immediately when loading. Easy to reproduce, just put the JSON into the LottieSample app in this repo. I've only been able to test Android 6.0.0 and 6.0.1 so far but they both crash.

[wink_crash.json.zip](https://github.com/airbnb/lottie-android/files/882923/wink_crash.json.zip)

**Comment by gpeal** [comment]
@iggyfisk Can you attach the After Effects file? The gradient is formatted strangely.
Unlink most properties, you have to explicitly save your AE file before exporting your composition for it to pick up your gradient changes. Is it possible that you didn't do that?

**Comment by ptomasroos** [comment]
There are some hidden layers which was during the trial, dont mind them.
Thanks for looking into it @gpeal 
[flirt.aep.zip](https://github.com/airbnb/lottie-android/files/883602/flirt.aep.zip)

**Comment by iggyfisk** [comment]
As of https://github.com/airbnb/lottie-android/commit/ebb61868874554717b1fedd96cb34edf28105293 the animation now loads and plays without crashing, thanks @gpeal ! But with a different appearance than expected, different than lottie-ios and v.1.5.3 of this project. A comparison of the 0.0 frame:

lottie-android 1.5.3
<img width="236" alt="android 1 5 3" src="https://cloud.githubusercontent.com/assets/6059552/24547101/86c75798-160e-11e7-9afb-bd860369c0c1.png">

lottie-android https://github.com/airbnb/lottie-android/commit/ebb61868874554717b1fedd96cb34edf28105293:
<img width="230" alt="android 2 0 0" src="https://cloud.githubusercontent.com/assets/6059552/24547121/9369d926-160e-11e7-895d-292b33a8347f.png">

lottie-ios 1.5.1:
<img width="303" alt="ios 1 5 1" src="https://cloud.githubusercontent.com/assets/6059552/24547126/98c996fe-160e-11e7-91da-191fde266b2a.png">

If you say there's something funky with our gradients I'm sure there is, and if you consider this issue resolved then we'll fix it somehow. But I thought maybe you were interested in the discrepancy. Thanks again!
