### ISSUE TITLE
Only the defaultColor from ColorStateList is used as a color filter

### ISSUE THREAD

**Issue by vorobyov-denis** [airbnb/lottie-android#2369]
**Is your feature request related to a problem? Please describe.**
I ran into an issue that when specifying `lottie_colorFilter` parameter with `ColorStateList` value, only `defaultColor` from this state list is used. Are there any plans to add support for changing colors depending on the view state? That is, for example, if the default color is used for the default state, another state specified in the `ColorStateList` is used for `isEnabled=true`?

**Describe the solution you'd like**
It would be great if `ColorStateList` values were used for different view states as color filter

**Comment by gpeal** [comment]
Unfortunately, the foundation of Lottie is a drawable which doesn't have such states. I would recommend using dynamic properties to load from a ColorStateList or manually set whatever colors are applicable for different states.
