### ISSUE TITLE
File working in demo - excluding features in JSON file

### ISSUE THREAD

**Issue by mlmaloney** [airbnb/lottie-android#237]
Hey there - We are working on an animation for an app and we have the animation working and rendering correctly. We have tested it in the demo and see it all loading, however when we pass it over to the developer it is cutting out a certain layer. The logo isn't fully loading and missing two features, an eye and a beak on the store front. I've attached the zip file of the After Effects file and the screenshot of what our developer sends back.

We believe there is an issue with layer and failing with the Lottie plug-in: CFA logo/Drive-Thru Illo Outlines 2

Can someone please take a look and let us know what issue we are having? Thank you!

<img width="341" alt="screen shot 2017-03-30 at 7 54 28 pm" src="https://cloud.githubusercontent.com/assets/26796706/24532073/3937abee-1583-11e7-9202-7c90f8803772.png">
[CFA.AEP.and.Screenshot.zip](https://github.com/airbnb/lottie-android/files/884191/CFA.AEP.and.Screenshot.zip)

**Comment by gpeal** [comment]
@mlmaloney Can you makes sure he is on 2.0.0-beta3 (soon to be beta4)?
You can always find the latest version in the bottom of the same app animation screen or on the github readme

**Comment by mlmaloney** [comment]
Hey @gpeal confirmed he is using the latest version on the `master` branch

**Comment by gpeal** [comment]
The iOS version doesn't yet support all of the features that Android does including fill types which I assume is why the beak is gone. You can file iOS issues on the lottie-ios repo. Has your Android developer experienced any issues?

**Comment by gpeal** [comment]
@mlmaloney bump
