### ISSUE TITLE
Lottie animation is not working in android app.

### ISSUE THREAD

**Issue by Babuhassan** [airbnb/lottie-android#2371]
Hi, 
I am not a developer. I just created a Lottie animation for my client, It was created by After Effect cc 2022 and rendered in Bodymovin, his developer said it's not working in a mobile app and also said it has an asset that is not included(some images or something) but I created the Lottie from Adobe Illustrator Graphics which is vector so there is no image file. 
As I am not a developer can anyone give me a solution?

**Comment by gpeal** [comment]
I think you forgot to attach your animation

**Comment by gpeal** [comment]
I'm going to close this because of the missing animation but feel free to repoen if you are able to attach one.
