### ISSUE TITLE
Discrepancy between lottie animation in Jetpack Compose and Lottie Preview

### ISSUE THREAD

**Issue by NicolaiNisbeth** [airbnb/lottie-android#2375]
**Description**:
There is an issue where the [lottie animation](https://github.com/airbnb/lottie-android/files/12485765/lottie.zip) does not match the [animation preview](https://app.lottiefiles.com/preview). However, it works as expected on iOS.

**What version of Lottie did you test this on?**
6.1.0
6.0.0
5.2.0

**What version of Android did you test this on?**
Emulator - Android 13
Oneplus Nord - Android 12

**Steps to reproduce the behavior:**
```
var selected by remember { mutableStateOf(false) }
val lottieComposition by rememberLottieComposition(LottieCompositionSpec.RawRes(R.raw.lottie))
val lottieAnimatable = rememberLottieAnimatable()

LaunchedEffect(lottieComposition, lottieAnimatable, selected) {
    if (selected) lottieAnimatable.animate(lottieComposition)
    else lottieAnimatable.resetToBeginning()
}

Button(onClick = { selected = !selected }) {
    LottieAnimation(
        composition = lottieComposition,
        progress = lottieAnimatable::progress
    )
}
```

**Additional info:**
The issue still remains when using the xml way of doing lottie animations, and the file doesn't seem to use any unsupported features according to the [supported feature list](https://lottiefiles.com/supported-features).

Thanks in advance for your help.

**Comment by gpeal** [comment]
Lottie doesn't support 3D on Android, unfortunately. I've spent some time on it but the underlying Android graphics APIs are 2D so supporting 3D isn't trivial.
