### ISSUE TITLE
Resource attributes are duplicated across lottie and lottie-compose libraries

### ISSUE THREAD

**Issue by krishnasajja** [airbnb/lottie-android#2376]
I tried adding lottie-compose dependency to a project which already uses lottie. It seems that the below attributes are duplicated across the two libraries which caused build failures during 'android-res-merge'.

- lottieAnimationViewStyle (attr)
- lottie_cacheComposition (attr)
- lottie_clipToCompositionBounds (attr)
- lottie_defaultFontFileExtension (attr)
- lottie_fallbackRes (attr)
- lottie_ignoreDisabledSystemAnimations (attr)
- lottie_useCompositionFrameRate (attr)

Library versions being used - 
        lottie               : "com.airbnb.android:lottie:6.0.0",
        lottieCompose        : "com.airbnb.android:lottie-compose:6.0.0",

**Comment by gpeal** [comment]
There is likely an issue with your specific setup that isn't specifically related to Lottie. Can you make a repro project?

**Comment by gpeal** [comment]
I'm going to close this since it's likely not an issue with Lottie but if you can create a repro project, feel free to repoen.

**Comment by krishnasajja** [comment]
@gpeal You are right, this is specific to my project setup. Was able to fix it internally. Sorry for the noise!
