### ISSUE TITLE
Compose Multiplatform Support

### ISSUE THREAD

**Issue by JamshedAlamQaderi** [airbnb/lottie-android#2388]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**Is your feature request related to a problem? Please describe.**
Every developer love lottie. So, there are developers who want to use lottie animation easily on compose multiplatform project. My request would be to support compose multiplatform ASAP

Thank You All!

**Comment by gpeal** [comment]
Lottie Android is very tied to the Android platform. Supporting multiplatform is out of scope for this but maybe somebody else could make a Compose multiplatform library that wrapped that other renderers.

**Comment by ismai117** [comment]
hi guys, I've created a Kotlin Multiplatform animation library, which uses Lottie for the android side and skia for iOS and desktop. version 1 is out now https://github.com/ismai117/kottie/blob/main/README.md

I'm now working on releasing a new version which will target Web and others!!

**Comment by ismai117** [comment]
the library works in most scenarios, do you know how I can handle base64/PNG embedded images?

**Comment by simonjia00** [comment]
> hi guys, I've created a Kotlin Multiplatform animation library, which uses Lottie for android and iOS, Skia for the other targets https://github.com/ismai117/kottie/blob/main/README.md

I find that there is white background when show the animation in iOS . Can you tell me how to solve it ?

**Comment by tipapro** [comment]
> > hi guys, I've created a Kotlin Multiplatform animation library, which uses Lottie for android and iOS, Skia for the other targets https://github.com/ismai117/kottie/blob/main/README.md
> 
> I find that there is white background when show the animation in iOS . Can you tell me how to solve it ?

Compottie could potentially solve this problem, as it uses a custom rendering engine for all platforms.
https://github.com/alexzhirkevich/compottie
