### ISSUE TITLE
Include a consumer-rules.pro file

### ISSUE THREAD

**Issue by michael-winkler** [airbnb/lottie-android#2391]
It would be really nice if lottie will add proguard rules automatic with the help of a consumer-rules.pro file.
See this example from OneSignal:
https://github.com/OneSignal/OneSignal-Android-SDK/blob/bce0f2fba975a215e734fd1d12a55d52cffdaa03/OneSignalSDK/onesignal/notifications/consumer-rules.pro

**Comment by gpeal** [comment]
Lottie doesn't use any reflection, binders, private APIs or anything like that. Is there something you think should be in a consumer proguard file?
