### ISSUE TITLE
Unable to parse composition

### ISSUE THREAD

**Issue by martinartime** [airbnb/lottie-android#2401]
Hi, I'm trying to display a lottie in an Android app but it crashes with IllegalStateException (Unable to parse composition).

I tested with different versions, such as: 3.0.7, 4.2.1, 5.0.1 and 6.1.0, all with the same error logs.

First I tried to include the lottie in the normal app I am using, but I get the following stacktrace:
![customAppError](https://github.com/airbnb/lottie-android/assets/21065252/7419e478-4086-4852-917a-7418c9e55638)

On the other hand, I made a simple app from scratch in Android, included the lottie dependency and raw json file and tried to see if it rendered, and it crashes too, but with a slightly different error (although from the same type), here is the stacktrace:
![simpleAppError](https://github.com/airbnb/lottie-android/assets/21065252/9e224563-30f7-4576-9953-5cb91b256a9f)

The json file with the lottie that generates this issues is:
[animation_sin_logo.json](https://github.com/airbnb/lottie-android/files/13079313/animation_sin_logo.json)

Please let me know if there is anything else I can do to help diagnose the issue.

Thanks in advance,
Martin

**Comment by gpeal** [comment]
Your animation has a stroke color of `#000f63.051eb85` which seems to be from the LottieFiles Figma plugin and is a non-standard way to represent a color. It appears to be two colors concatenated together and isn't something I've seen before.

I'll run this by the LottieFIles team but in the meantime, can you work backwards from your Figma file to understand why it would be exporting two stroke colors like that?

**Comment by CrimsonBraixen** [comment]
I just sent the response to the corresponding team to see why they try to represent colors that way.
I await the response from the LottieFiles team to help understand better the issue.
Thanks a lot for the answer.

**Comment by kudanai** [comment]
Hello @martinartime,

Naail from LottieFiles here. We've identified the issue on our end with exporting these. Thank you for the report. We'll release an update for our plugins with the fix asap.

I think we can close the issue here as it's unrelated to lottie-android

**Comment by martinartime** [comment]
That's great! Thanks for the update, we'll wait for the new release. 

I'll close this issue.

**Comment by jvgeee** [comment]
@kudanai @gpeal  Can you please update here with a comment when this has been fixed in Lottiefiles/Figma? This is still an issue for me and is currently crashing Android

**Comment by kudanai** [comment]
Hi @jvgeee.

We've fixed the issue in the pipeline. The plugin release should come early next week along with some other fixes.

**Comment by kudanai** [comment]
@jvgeee done ✅
