### ISSUE TITLE
Incorrect animation loads when gradle version is updated

### ISSUE THREAD

**Issue by nawanirakshit** [airbnb/lottie-android#2403]
The animation breaks when updating the Gradle version from 3.6.0 to the latest version(6.1.0).

I've attached a screenshot of the animation with the old and new versions.

<img width="691" alt="Screenshot 2023-10-26 at 11 44 24 AM" src="https://github.com/airbnb/lottie-android/assets/12641430/c227b9d3-c8f0-4676-88b4-655fbe6c2040">

Strangely, the animation code to display the animation is identical for both versions, but just updating and running the code gives broken animation.

Sample JSON can be viewed from following
https://mp13017261cad0e033b7.free.beeceptor.com/data

Currently, I am setting animation with the following code.

`lottieAnimationView.setAnimationFromJson("JSON_HERE", null);`

And the Lottie view looks like below 

```

<com.airbnb.lottie.LottieAnimationView

            android:id="@+id/animation"

            android:layout_width="255dp"

            android:layout_height="255dp"

            android:layout_gravity="center"

            app:lottie_autoPlay="true"

            app:lottie_loop="true"
 />

```

**Comment by nawanirakshit** [comment]
Hi @gpeal whats the gradle version we should use for this fix?
Thanks

**Comment by gpeal** [comment]
It will be in the next release. Should be in the next week or two.
