### ISSUE TITLE
Support setter for Layer.hidden

### ISSUE THREAD

**Issue by MagymD** [airbnb/lottie-android#2419]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to use java reflection to set `Layer.hidden` value.

**Describe the solution you'd like**
Make `Layer.hidden` value setter is public.

**Describe alternatives you've considered**
Somehow create the ability to change the visibility of the layer. Maybe create an api similar to TextDelegate.

**Additional context**
This is an analogue of the `setNodeIsEnabled` function in iOS.

**Comment by gpeal** [comment]
Could you use a dynamic property to set the opacity to 0?

**Comment by MagymD** [comment]
Yes, I saw it, I can, thank you. But of course it's not as convenient as just changing visibility
