### ISSUE TITLE
Strange lines on rounded rectangle shape

### ISSUE THREAD

**Issue by edubovik** [airbnb/lottie-android#242]
Hello,

I've got strange lines while playing simple animation.
btw The IOS library works fine.
The animation file.
[data.json.zip](https://github.com/airbnb/lottie-android/files/902701/data.json.zip)
Screenshots
![1](https://cloud.githubusercontent.com/assets/6649016/24757276/6c49a79e-1ae7-11e7-8cce-2c12055a5a4a.png)
![3](https://cloud.githubusercontent.com/assets/6649016/24757277/6c67828c-1ae7-11e7-861a-769aeeaa758f.png)

**Comment by gpeal** [comment]
@edubovik Can you attach the AE file?

**Comment by edubovik** [comment]
@gpeal Sure. See attachments please.
[test.aep.zip](https://github.com/airbnb/lottie-android/files/904766/test.aep.zip)

**Comment by edubovik** [comment]
I've made a fixes for RectangleContent in two formulas and this fixes the issue.

`package com.airbnb.lottie;

import android.graphics.Path;
import android.graphics.PointF;
import android.graphics.RectF;
import android.support.annotation.Nullable;

import java.util.List;

class RectangleContent implements PathContent, BaseKeyframeAnimation.AnimationListener {
    private final Path path = new Path();
    private final RectF rect = new RectF();

    private final String name;
    private final LottieDrawable lottieDrawable;
    private final BaseKeyframeAnimation<?, PointF> positionAnimation;
    private final BaseKeyframeAnimation<?, PointF> sizeAnimation;
    private final BaseKeyframeAnimation<?, Float> cornerRadiusAnimation;

    @Nullable
    private TrimPathContent trimPath;
    private boolean isPathValid;

    RectangleContent(LottieDrawable lottieDrawable, BaseLayer layer, RectangleShape rectShape) {
        name = rectShape.getName();
        this.lottieDrawable = lottieDrawable;
        positionAnimation = rectShape.getPosition().createAnimation();
        sizeAnimation = rectShape.getSize().createAnimation();
        cornerRadiusAnimation = rectShape.getCornerRadius().createAnimation();

        layer.addAnimation(positionAnimation);
        layer.addAnimation(sizeAnimation);
        layer.addAnimation(cornerRadiusAnimation);

        positionAnimation.addUpdateListener(this);
        sizeAnimation.addUpdateListener(this);
        cornerRadiusAnimation.addUpdateListener(this);
    }

    @Override
    public String getName() {
        return name;
    }

    @Override
    public void onValueChanged() {
        invalidate();
    }

    private void invalidate() {
        isPathValid = false;
        lottieDrawable.invalidateSelf();
    }

    @Override
    public void setContents(List<Content> contentsBefore, List<Content> contentsAfter) {
        for (int i = 0; i < contentsBefore.size(); i++) {
            Content content = contentsBefore.get(i);
            if (content instanceof TrimPathContent &&
                    ((TrimPathContent) content).getType() == ShapeTrimPath.Type.Simultaneously) {
                trimPath = (TrimPathContent) content;
                trimPath.addListener(this);
            }
        }
    }

    @Override
    public Path getPath() {
        if (isPathValid) {
            return path;
        }

        path.reset();

        PointF size = sizeAnimation.getValue();
        float halfWidth = size.x / 2f;
        float halfHeight = size.y / 2f;
        float radius = cornerRadiusAnimation == null ? 0f : cornerRadiusAnimation.getValue();
        float maxRadius = Math.min(halfWidth, halfHeight);
        if (radius > maxRadius) {
            radius = maxRadius;
        }

        // Draw the rectangle top right to bottom left.
        PointF position = positionAnimation.getValue();

        path.moveTo(position.x + halfWidth, position.y - halfHeight + radius);

        path.lineTo(position.x + halfWidth, position.y + halfHeight - radius);

        if (radius > 0) {
            rect.set(position.x + halfWidth - 2 * radius,
                    position.y + halfHeight - 2 * radius,
                    position.x + halfWidth,
                    position.y + halfHeight);
            path.arcTo(rect, 0, 90, false);
        }

        path.lineTo(position.x - halfWidth + radius, position.y + halfHeight);

        if (radius > 0) {
            rect.set(position.x - halfWidth,
                    position.y + halfHeight - 2 * radius,
                    position.x - halfWidth + 2 * radius,
                    position.y + halfHeight);
            path.arcTo(rect, 90, 90, false);
        }
        //Fixed
        path.lineTo(position.x - halfWidth, position.y - halfHeight * 2 + 2 * radius);

        if (radius > 0) {
            rect.set(position.x - halfWidth,
                    position.y - halfHeight,
                    position.x - halfWidth + 2 * radius,
                    position.y - halfHeight + 2 * radius);
            path.arcTo(rect, 180, 90, false);
        }

        //Fixed
        path.lineTo(position.x + halfWidth - radius, position.y - halfHeight);

        if (radius > 0) {
            rect.set(position.x + halfWidth - 2 * radius,
                    position.y - halfHeight,
                    position.x + halfWidth,
                    position.y - halfHeight + 2 * radius);
            path.arcTo(rect, 270, 90, false);
        }
        path.close();

        Utils.applyTrimPathIfNeeded(path, trimPath);

        isPathValid = true;
        return path;
    }
}`

**Comment by edubovik** [comment]
I've added new pull request but I couldn't add @gpeal to reviewers.

**Comment by edubovik** [comment]
@gpeal Thanks a lot!
