### ISSUE TITLE
software rendering problem

### ISSUE THREAD

**Issue by jeongsu816** [airbnb/lottie-android#2423]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Describe the bug**

LottieDrawable has software rendering problem. When givn canvas has a matrix that with translate and scale, and lottie content has big intrinsic size, software rendering render only cross area of target area and a rectangle from (0, 0)

**What version of Lottie did you test this on?**
I can reproduce this from the latest commit

**What version of Android did you test this on?**

**Steps To Reproduce**

I made a some patch to demostrate this problem.
Please check this commit: 
https://github.com/jeongsu816/lottie-android/commit/47d38a939e4b789b4733f93dd6a3f82fb8dc6654

I made a lottie content that has yellow background and blue circle. And I changed clear color of software rendering bitmap to Red to how software rendering works. Please check attached video.

**Screenshots**

https://github.com/airbnb/lottie-android/assets/23135075/6c4290bc-2ad9-45a9-8d35-7cef09c76532

**Comment by gpeal** [comment]
Can I ask what you're trying to accomplish? Your example of manually setting bounds, scale, and translation seems somewhat contrived. Maybe with a more use case, we can figure out if there is a better way to accomplish what you want or if there is an actual bug that should be fixed.

**Comment by jeongsu816** [comment]
Hello.

I want to play lottie animation from an WallpaperService. So I use LottieDrawable directly to draw. My test code is just to share what is the problem when using LottieDrawable directly.

**Comment by gpeal** [comment]
@jeongsu816 LottieDrawable is frequently used alone without issue. Could you try creating a LottieAnimationView and call draw on it directly instead of on the drawable.

**Comment by gpeal** [comment]
Closing due to lack of response.
