### ISSUE TITLE
Support for audio layers in the animation json

### ISSUE THREAD

**Issue by suraj-raj-pi** [airbnb/lottie-android#2424]
**Is your feature request related to a problem? Please describe.**
lottie-web provides options to use audio layers by adding a 3rd party library as described here - https://github.com/airbnb/lottie-web/wiki/Audio. Looking for a similar support on lottie-android.

**Describe the solution you'd like**
Any updates on if a similar support is exposed or planned for lottie-android.

**Comment by gpeal** [comment]
There are no plans to add audio to the core library. However, if you would like to build your own that uses an animation listener or something to synchronize audio with a composition, you are welcome to do that.
