### ISSUE TITLE
Placeholder Support while Lottie is being fetched / rendered

### ISSUE THREAD

**Issue by ShivamGoyal1899** [airbnb/lottie-android#2436]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**Is your feature request related to a problem? Please describe.**
While Lottie is being fetched over the internet or rendered, there is no visual cue for the user to know that it's being fetched or rendered.

**Describe the solution you'd like**
A placeholder option [similar to Glide](https://bumptech.github.io/glide/doc/placeholders.html) will be helpful. I'm specifically looking to be able to add a Vector Drawable in such cases.

**Describe alternatives you've considered**
No alternatives were found.

**Comment by gpeal** [comment]
LottieAnimationView is just an ImageView. Whenever you call `setAnimationFromUrl`, you can also call `setImageDrawable` at the same time and then Lottie will re-set it to the animation when it loads or fails.

This should work but feel free to reopen this if it doesn't.

**Comment by UKMIITB** [comment]
@gpeal 
What about when using it in compose ?
