### ISSUE TITLE
cann't install the app

### ISSUE THREAD

**Issue by clq123clq** [airbnb/lottie-android#244]
when I import the project into the Android Studio,run,But cann't insall

show below message:
Installation failed with message INSTALL_FAILED_TEST_ONLY.
It is possible that this issue is resolved by uninstalling an existing version of the apk if it is present, and then re-installing.

WARNING: Uninstalling will remove the application data!

Do you want to uninstall the existing application?

and below error:
$ adb shell pm install -r "/data/local/tmp/com.airbnb.lottie"
	pkg: /data/local/tmp/com.airbnb.lottie
Failure [INSTALL_FAILED_TEST_ONLY]

$ adb shell pm uninstall com.airbnb.lottie
DELETE_FAILED_INTERNAL_ERROR
Error while Installing APK

**Comment by gpeal** [comment]
There seems to be some issue with your emulator or compilation but I don't think this is a Lottie issue.

**Comment by nAkhmedov** [comment]
The same issue on me :(

**Comment by nAkhmedov** [comment]
04/08 00:42:42: Launching LottieSample
$ adb install-multiple -r /Users/navruz/a_work/Android/lottie-android/LottieSample/build/intermediates/split-apk/debug/dep/dependencies.apk /Users/navruz/a_work/Android/lottie-android/LottieSample/build/outputs/apk/LottieSample-debug.apk /Users/navruz/a_work/Android/lottie-android/LottieSample/build/intermediates/split-apk/debug/slices/slice_5.apk /Users/navruz/a_work/Android/lottie-android/LottieSample/build/intermediates/split-apk/debug/slices/slice_0.apk /Users/navruz/a_work/Android/lottie-android/LottieSample/build/intermediates/split-apk/debug/slices/slice_1.apk /Users/navruz/a_work/Android/lottie-android/LottieSample/build/intermediates/split-apk/debug/slices/slice_6.apk /Users/navruz/a_work/Android/lottie-android/LottieSample/build/intermediates/split-apk/debug/slices/slice_3.apk /Users/navruz/a_work/Android/lottie-android/LottieSample/build/intermediates/split-apk/debug/slices/slice_4.apk /Users/navruz/a_work/Android/lottie-android/LottieSample/build/intermediates/split-apk/debug/slices/slice_2.apk /Users/navruz/a_work/Android/lottie-android/LottieSample/build/intermediates/split-apk/debug/slices/slice_7.apk /Users/navruz/a_work/Android/lottie-android/LottieSample/build/intermediates/split-apk/debug/slices/slice_8.apk /Users/navruz/a_work/Android/lottie-android/LottieSample/build/intermediates/split-apk/debug/slices/slice_9.apk 
$ adb shell pm uninstall com.airbnb.lottie
DELETE_FAILED_INTERNAL_ERROR
Error while Installing APKs
```

**Comment by gpeal** [comment]
Can you try with Android Studio 2.4 and instant run off?
