### ISSUE TITLE
Don't export Logger

### ISSUE THREAD

**Issue by pm-nchain** [airbnb/lottie-android#2447]
Would it be possible to not expose `Logger` class, so it's not visible to library consumers? 

Like making it `internal` in kotlin?

**Comment by gpeal** [comment]
Unfortunately not because it's Java. You can exclude it from being suggested as an import in your IDE though.

https://www.jetbrains.com/guide/go/tips/exclude-from-imports-and-completion/

**Comment by gpeal** [comment]
Actually, I'll reopen this to rename it.

**Comment by gpeal** [comment]
Actually, `Logger.setInstance` is a public API and renaming it would break consumers. I agree that the naming here is not ideal and I would change it if I could do it again. As a result, telling Android Studio to exclude it from auto-import would be the ideal solution here.
