### ISSUE TITLE
LottieTask listener triggers twice if a cached url is retrieved a second time

### ISSUE THREAD

**Issue by awenger** [airbnb/lottie-android#2449]
#### Case 1
**Steps To Reproduce**

- Click on the "Click me a" Button
- Click on the "Click me a" Button (second time)
- Click on the "Click me a" Button (third time)
- Resulting logs:
```
18:01:46.059  D  Click me a clicked
18:01:46.373  D  onResult 0
18:01:48.504  D  Click me a clicked
18:01:48.505  D  onResult 1
18:01:48.534  D  onResult 1 // second/duplicate invocation of the callback
18:02:29.887  D  Click me a clicked
18:02:29.888  D  onResult 2
18:02:29.899  D  onResult 2 // second/duplicate invocation of the callback
```
#### Case 2

This behaviour becomes a problem if the callback is wrapped within a `suspendCancellableCoroutine` ([here](https://github.com/airbnb/lottie-android/compare/master...awenger:lottie-android:listener-triggered-twice-repro?expand=1#diff-45ce4872230400baf686c8fb7430cc5c35f899bb2a1efb1383ef60fa5513c417R64-R75))
- Click on the "Click me b" Button
- App crashes because the continuation is resumed twice
- Resulting logs:
```
18:03:31.383  D  Click me b clicked
18:03:31.411  D  Shutting down VM
18:03:31.415  E  FATAL EXCEPTION: main
                 Process: com.airbnb.lottie.issues.compose, PID: 28440
                 java.lang.IllegalStateException: Already resumed, but proposed with update LottieComposition:
                 	Layer 6 Outlines
                 		Shapes:
```

**Comment by Leelion96** [comment]
val task = if ((data.startsWith("http://") || data.startsWith("https://"))) {
            LottieCompositionFactory.fromUrl(lottieView.context, data)
        } else {
            LottieCompositionFactory.fromAsset(lottieView.context, data)
        }
        val loadResultListener = LottieListener<LottieComposition> { composition ->
            log("Lottie onLoadSuccess")
        }
        val loadFailureListener = LottieListener<Throwable> { exception ->
            log("Lottie onLoadFail: $exception")
        }
        task.result?.value?.let {
            loadResultListener.onResult(it)
            return
        }
        task.result?.exception?.let {
            loadFailureListener.onResult(it)
            return
        }
        task.addListener(loadResultListener).addFailureListener(loadFailureListener)
