### ISSUE TITLE
No log message when json file not found. 

### ISSUE THREAD

**Issue by lighterletter** [airbnb/lottie-android#247]
So I spent around 20 mins trying to figure out why an animation would crash my app when another one wouldn't, even though everything stayed the same except the file name. Until I found I misspelled something. I know, silly me. Would be nice however if there was log-cat output for when the filename passed in to the lottie view is null, or not within the assets recognized. As it stands the library fails silently.

**Comment by gpeal** [comment]
@lighterletter Didn't you say it crashed your app? Crashing would be the expected behavior in which case the stack should indicate that the file was not found.

**Comment by lighterletter** [comment]
That's what I mean when I mentioned it failed silently, I didn't see any error output when the file wasn't found. The crash presented in the logcat indicated a state failure which was odd in the given circumstances since the state I was managing had little to do with the animation-view; which happened to work perfectly given a proper file name.

**Comment by lighterletter** [comment]
I can look for it and make a pull request tomorrow :laughing: It'll make for a funny tweet if I get a merge from airbnb for something so silly as misspelling a filename.

**Comment by gpeal** [comment]
Go for it :)

**Comment by lighterletter** [comment]
Nvm. I are big dum dum hed. I found the log, the library is throwing the error correctly. l must have missed it during my debugging. Sorry about that, thanks Gabriel.
