### ISSUE TITLE
Lottie-compose feature parity

### ISSUE THREAD

**Issue by Fra078** [airbnb/lottie-android#2477]
Lottie recently added support for .tgs files, however lottie-compose was not updated so this branch doesn't support these files!

**Comment by gpeal** [comment]
Which CompositionSpec are you referring to?

**Comment by Fra078** [comment]
Sorry, I misunderstood code. So compositionSpec.File doesn't support tgs and gzip. But why can't you add a compositionSpec.GZipFile so if the developer is sure that the file is a gzip can Simply load it without lots of boilerplate code
