### ISSUE TITLE
LottieAnimationView.duration returns 0

### ISSUE THREAD

**Issue by u13** [airbnb/lottie-android#2481]
```
binding.lottieAnimation.setAnimation(fileName)
val animationDuration = binding.lottieAnimation.duration

// animationDuration == 0
```

If we go inside of `LottieAnimationView`, we see that:

```
  public long getDuration() {
    LottieComposition composition = getComposition(); // composition == null
    return composition != null ? (long) composition.getDuration() : 0;
  }
```

and `composition == null` because:

```
  @Nullable public LottieComposition getComposition() {
    return getDrawable() == lottieDrawable ? lottieDrawable.getComposition() : null; // getDrawable() == null
  }
```

Most probably this bug appeared after merging this PR #2468

**Comment by gpeal** [comment]
Did you set your own drawable on LottieAnimationView (like your own resource or something)?

**Comment by gpeal** [comment]
Lottie parses compositions synchronously. If you are setting an animation for the first time, the duration won't be synchronously available. I just did a test where I logged the duration in the callback for `LottieAnimationView.addLottieOnCompositionLoadedListener` and it returned the correct duration.
