### ISSUE TITLE
6.4.0 Delete the setScale API. Are there any other alternative APIs that do the same thing as the setScale API?

### ISSUE THREAD

**Issue by chenyukotlin** [airbnb/lottie-android#2492]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gpeal** [comment]
Yes, view/composable size + scaleType for views and ContentScale and Alignment for compose
