### ISSUE TITLE
Cannot render when using LottieDrawable without setting bounds on devices < Android Oreo with SOFTWARE rendering

### ISSUE THREAD

**Issue by CodeReadOnlyUser** [airbnb/lottie-android#2495]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**Describe the bug**

When using ```RenderMode.SOFTWARE``` or renderMode not specified. LottieDrawable without setting bounds before ```resumeAnimation()``` cannot be rendered using ```lottieDrawable.draw(canvas)``` on devices with Android version < Oreo (API 26)

When using ```RenderMode.HARDWARE``` or devices with Android version >= Oreo (API 26). LottieDrawable without setting bounds before ```resumeAnimation()``` will be rendered. The bounds will be ```lottieDrawable.composition.bounds```

**What version of Lottie did you test this on?**
```implementation("com.airbnb.android:lottie:6.4.0")``` and some older versions.

**What version of Android did you test this on?**
Android API 23, API 25, API 26, API 32, API 34

**Steps To Reproduce**

Custom drawable with lottie example:

```kotlin
class CustomLottieDrawable(val view: View) : Drawable() {

    //constants
    private val size = 600
    private val lottieAssetName = "Lottie Logo 1.json"

    private val lottieDrawable: LottieDrawable = initLottieDrawable()

    //keep reference here, or callback will be recycled
    private var refreshCallback: Callback? = null


    init {
        this.bounds = Rect(0, 0, size, size)
        //⚠️
        //lottieDrawable.bounds = Rect(0, 0, size, size)
        lottieDrawable.resumeAnimation()
    }

    override fun draw(canvas: Canvas) {
        lottieDrawable.draw(canvas)
    }

    override fun setAlpha(alpha: Int) {}

    override fun setColorFilter(colorFilter: ColorFilter?) {}

    override fun getOpacity(): Int = PixelFormat.TRANSLUCENT

    private fun initLottieDrawable(): LottieDrawable {
        val lottieDrawable = LottieDrawable()
        this.refreshCallback = object : Callback {
            override fun invalidateDrawable(who: Drawable) {
                view.invalidate()
            }

            override fun scheduleDrawable(who: Drawable, what: Runnable, `when`: Long) {}
            override fun unscheduleDrawable(who: Drawable, what: Runnable) {}
        }
        lottieDrawable.callback = this.refreshCallback
        val result = LottieCompositionFactory.fromAssetSync(view.context, lottieAssetName).value
        lottieDrawable.composition = result
        lottieDrawable.repeatCount = LottieDrawable.INFINITE
        //⚠️
        //lottieDrawable.renderMode = RenderMode.HARDWARE
        return lottieDrawable
    }


}
```

Then, setting this CustomLottieDrawable as some view's background.

Uncomment any lines with ⚠️ comment to render properly on pre Android Oreo devices.

**Additional information:**

When debugging using ```lottieDrawable.toBitmap(,,)```, the bitmap is the correct rendered image. So I am wondering why renderMode and Android version can cause different render result.

**Solution**
Set ```lottieDrawable.bounds``` before calling ```lottieDrawable.resumeAnimation()```

**Screenshots**
Nothing visible

**Comment by gpeal** [comment]
This is not surprising because with render mode software, the canvas is backed by a bitmap which inherently has bounds due to the bitmap and there is nothing Lottie can do to render beyond that.

**Comment by CodeReadOnlyUser** [comment]
> with render mode software

I tested again on devices with Android >= 8.0. If SOFTWARE rendering is manually enabled, nothing is rendered. So the real behavior is LottieDrawable without setting bounds will not be visible in SOFTWARE rendering mode.

And the reason why HARDWARE rendering is used starting from Android Oreo can be found here.
https://github.com/airbnb/lottie-android/blob/aebf9bc07bc54979633f3355ada3d3e6e12986a3/lottie/src/main/java/com/airbnb/lottie/RenderMode.java#L38

Thanks for your answer🙏

**Comment by gpeal** [comment]
@CodeReadOnlyUser It not being visible doesn't sound right. Can you create a project that repros this?

**Comment by 1970633640** [comment]
https://github.com/1970633640/Lottietest

change this line to HARDWARE to render visible animations:
https://github.com/1970633640/Lottietest/blob/fc1fe639e8537101dab38de186558f4b61035b75/app/src/main/java/com/example/lottietest/CustomLottieDrawable.kt#L57
