### ISSUE TITLE
Execution failed for task ':app:mergeExtDexDebug'

### ISSUE THREAD

**Issue by ahmed2146** [airbnb/lottie-android#2496]
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform lottie-compose-6.3.0.aar (com.airbnb.android:lottie-compose:6.3.0) to match attributes {artifactType=android-dex, asm-transformed-variant=debug, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=24, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AsmClassesTransform: /Users/muhammadahmed/.gradle/caches/transforms-3/fc8970f16c14f13af16a06c806462f84/transformed/lottie-compose-6.3.0-runtime.jar.
         > PermittedSubclasses requires ASM9
         
         
         please help to resolve this issue, only came with android version 24 and 23

**Comment by gpeal** [comment]
This is like a local build cache issue or something unrelated to Lottie itself.

**Comment by Kola-Chao** [comment]
fix by disabled the "Enable additional support for older devices (API level < 26)" option
