### ISSUE TITLE
Switch source in animator listener: animation freezes

### ISSUE THREAD

**Issue by dcow** [airbnb/lottie-android#250]
What's the best way to stitch a series of animations together? I have a set of 3, intro, loop, outro. I'm canceling the first animation onAnimationEnd, removing the old listener, setting a new listener, setting a new animation, and playing it. Something like:

    val introListener = object : Animator.AnimatorListener {
        override fun onAnimationEnd(animation: Animator?) {
            // content is the LottieAnimationView
            content.cancelAnimation() // should I use clearAnimation()?
            content.removeAnimatorListener(this)
            content.addAnimatorListener(loopListener) // monitors some condition and plays 
            content.setAnimation("Step_02.json")      // the outro when it's met
            content.loop(true)
            content.playAnimation()
        }
        override fun onAnimationRepeat(animation: Animator?) {}
        override fun onAnimationCancel(animation: Animator?) {}
        override fun onAnimationStart(animation: Animator?) {}
    }

The animation freezes when I try to play the second in the series. However, in other spots I've been able to do this just fine. Are there any best practices with respect to reusing a LottieAnimationView across multiple animations? Does anything come to mind that might be the culprit? I'm doing all this from the main thread, however I haven't worked with Animators a lot before so I'm not sure if it's okay to, for example, start a new animation onAnimationEnd.

That said, posting `content.playAnimation()` resolves the issue:

    view.post { content.playAnimation() }

Considering that playing the animation directly from the animator listener works in some cases, and not others, it feels like there might be a race condition or some sort (to clarify, it's 100% reproducible in the cases it does not work, and 100% fine in cases where it does, and I'm on the main thread when I play it). I'm using `Lottie 1.5.3` because there were issues rendering circles in 2.0-beta last I tried.

**Comment by gpeal** [comment]
```
    final Animator.AnimatorListener loopListener = new AnimatorListenerAdapter() {
      @Override public void onAnimationRepeat(Animator animation) {
        loopCount++;
        if (loopCount == 1) {
          animationView.setAnimation("HamburgerArrow.json");
          animationView.setProgress(0);
          animationView.playAnimation();
        } else if (loopCount == 3) {
          animationView.setAnimation("PinJump.json");
          animationView.loop(false);
          animationView.setProgress(0);
          animationView.playAnimation();
        }
      }
    };
    animationView.setAnimation("TwitterHeart.json");
    animationView.loop(true);
    animationView.addAnimatorListener(loopListener);
    animationView.playAnimation();
```

This works for me.

It's not super straightforward and I'll try and think of a simpler way to handle this since it seems like a relatively common pattern but for now, this will work.

The reason yours doesn't work is because the onAnimationEnd callback occurs before an animator internally calls `mRunning` and `mStarted` to false which is why you had to post it when you used on AnimationEnd. This is not an issue if you set it to loop from the beginning. However, setAnimation cancels the current one so you have to call play again.

**Comment by gpeal** [comment]
@dcow ^

**Comment by dcow** [comment]
@gpeal thanks for looking into this. I saw your commentary. I've drafted a version using my own valueAnimator and scrubbing progress which I feel is a cleaner solution overall (although the actual file can take longer to load since it's not chopped up). I most wanted to report this to make sure it is on the radar and either fixed or not a bug (=
