### ISSUE TITLE
`LottieOnCompositionLoadedListener` is not called when the animation is loaded again

### ISSUE THREAD

**Issue by linkaipeng** [airbnb/lottie-android#2505]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Checklist**

1. Fork this repository into your account.  ✅
2. Reproduce your issue in the issue-repro module. Issues without a repro in the issue-repro 
   module may be auto-closed.  ✅

**Link to fork with a repro in the issue-repro module**

https://github.com/linkaipeng/lottie-android/tree/master/issue-repro

**Describe the bug**

**Steps To Reproduce**

1. Call binding.animationView.playAnimation() within the addLottieOnCompositionLoadedListener `onCompositionLoaded`.
2. Click loadButton, call setAnimation(R.raw.heart), it's work.
3. Click cancelButton, call cancelAnimation()
4. Click loadButton again, it's not work. Reproduce. However, the issue did not exist in the version 6.0.0. 

**I've reviewed the source code and analyzed the differences with version 6.0.0. I would like to know why these changes were made?**

- The `setCompositionTask` method in `LottieAnimationView` checks three conditions, and if they are the `true`, it will return and will not execute the `addListener` below.
![WX20240528-153916](https://github.com/airbnb/lottie-android/assets/5371228/79595b59-3930-4003-8d05-3f31fef7f564)

- In the `cache` method of `LottieCompositionFactory`, a new `LottieTask` is recreated, but the `successListeners` within it are empty. Therefore, the `onResult` inside `notifySuccessListeners` will not be called.
![1716884472741](https://github.com/airbnb/lottie-android/assets/5371228/6afebdc2-5865-42e9-8d04-d4b1399c6e15)

**Comment by gpeal** [comment]
This is actually the expected behavior here. `cancelAnimation()` cancels the animator so that if you call `playAnimation()` again, it'll restart from the beginning but you aren't actually "loading" it again after that.
If you call `binding.animationView.setImageDrawable(null)` and _then_ all `setAnimation(…)` again then the callback _will_ get called because it's actually updating the drawable on LottieAnimationView.
