### ISSUE TITLE
Paused Lottie Animation Doesn't show the right progression

### ISSUE THREAD

**Issue by clemlkc** [airbnb/lottie-android#2506]
Context : We want to preserve the animation progress and playing state (pause or play) of a Lottie animation when the user rotates the screen. We then save the progression, and use ClipSpec to set the right progression, after it recomposed.

Bug : When animation is on pause, and user rotates the screen, the animation is re loaded with right progress, but until we set it back to Playing, the animation shows the frame like its 0% progression. When we start playing it again, then the animation starts as expected at the progression we saved. -> It seems that the animation isn't taking the ClipSpec argument into account until it starts playing.

**Comment by gpeal** [comment]
You shouldn't need to do this yourself. If your view has an id and you call `saveEnabled` (the Android API), lottie will handle this for you.

Regardless, clipSpec probably isn't what you want here. You probably want to call setProgress with whatever initial progress you want. However, I would try what I mentioned above to get the out of the box behavior for free.
