### ISSUE TITLE
Lottie rendering incorrectly on Android

### ISSUE THREAD

**Issue by gitercn** [airbnb/lottie-android#2508]
We are experiencing issues with Lottie animations displaying incorrectly on Android, while they appear fine on desktop. I recently opened an issue on iOS here: https://github.com/airbnb/lottie-ios/issues/2417, and it was suggested that my issue might be similar to this one: https://github.com/airbnb/lottie-ios/issues/2345, advising me to follow and track that issue. However, since I'm encountering a similar problem on Android as well, I'm opening an issue here too, hoping for a fix on both mobile platforms.

**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features). - Checked through lottiefiles.com and it tells me the no issues with the features used
2. I know what part of my animation doesn't work. - Yes
3. I have created a simplified version of my animation - Yes
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work. - Yes

**Describe the bug**
The animation displaying incorrectly on Android

**What version of Lottie did you test this on?**
Tested with latest version of lottie-web 5.12.2, this looks good on desktop
Tested with the latest Lottie App on Google Play, 5.0.1, this looks incorrect
Tested with the latest LottieFiles App on Google Play, 2.9.49, this looks incorrect as well

**What version of Android did you test this on?**
5.0.1

**Steps To Reproduce**

1. Go to 'LottieFiles Android App'
2. Upload the demo.json Lottie Animation
3. See error

**Screenshots**
Looks good on desktop - Expected:
![Expected](https://github.com/airbnb/lottie-android/assets/53464166/5cdb3fbb-b501-4a7b-8e08-38901027a162)

Looks incorrect on Lottie 5.0.1:
![Screenshot_20240522-182845_Lottie](https://github.com/airbnb/lottie-android/assets/53464166/0c28d201-f806-4984-bd7f-d0ba2c43187c)

Looks incorrect on LottieFiles 2.9.49:
![Screenshot_2024-06-04-08-57-08-336_com lottiefiles LottiePreview](https://github.com/airbnb/lottie-android/assets/53464166/9ebbda0f-0d9d-4e23-b668-797d9100807b)

The zipped lottie json file
[ziped-Lottie-demo.zip](https://github.com/user-attachments/files/15541309/ziped-Lottie-demo.zip)

**Comment by kudanai** [comment]
hello @gitercn 

Can I quickly confirm two things:
* If exporting from AfterEffects (bodymovin?) works as expected?
* If the broken Lottie came through the LottieFiles pipeline (editor/workflow etc)?

Looking demo attached, I can see a bunch of `"_render": True` keys appearing in the Lottie, which is indicative of an incorrect export. This seems to have been a regression on LottieFiles for a minute there. 

We've deployed a patch across the platform as well, so do give it another go now and see if the problem still persists.

**Comment by LZRight123** [comment]
我也遇到这个问题 使用的是 lottie-compose
