### ISSUE TITLE
Wrong indexer in an inner loop

### ISSUE THREAD

**Issue by lifove** [airbnb/lottie-android#252]
Hi

In a recent snapshot, I've found a following suspicious code in lottie/src/main/java/com/airbnb/lottie/BaseStrokeContent.java

```
203     for (int i = 0; i < pathGroups.size(); i++) {
204       PathGroup pathGroup = pathGroups.get(i);
205       for (int j = 0; j < pathGroup.paths.size(); j++) {
206         path.addPath(pathGroup.paths.get(i).getPath(), parentMatrix);
207       }
208     }
```
In Line 206, should the indexer of pathGroup.paths.get(i) be j? This might be a trivial thing but just wanted to report just in case.

Thanks!

**Comment by gpeal** [comment]
Thanks, good catch :)
