### ISSUE TITLE
Docs not updated properly for setScale removal

### ISSUE THREAD

**Issue by TheKeeperOfPie** [airbnb/lottie-android#2520]
I deleted the template, filing this bug here in instead of https://github.com/airbnb/lottie because issues aren't enabled there.

It looks like in [this change](https://github.com/airbnb/lottie/commit/a22955fa6084f4bfcf179ffe76556d8002ed4c56#diff-6fe7e25aab7efeeb5df92b3eb5025c0d8016071dc491e0368ca3bcc1c075c043L136-L146) the scaling API section was removed since the `setScale` API was removed in 5.0, but the doc now has a lingering sentence:

> However, if your animation isn't the perfect size, you have two options:

with no follow up, which had me confused trying to read through the docs.

Unfortunately I haven't actually used the library so I don't know what the right update would be, but from https://github.com/airbnb/lottie-android/issues/2153, it seems either Canvas or some other Drawable scaling mechanism should be used?

You can see this trailing sentence on the live page at https://airbnb.io/lottie/#/android?id=animation-size-px-vs-dp

**Comment by gpeal** [comment]
For views, use `scaleType` and for compose use `contentScale` and `alignment` plus `graphicsLayer` (which is part of stock compose) if you need to do more transforms on top of that.
