### ISSUE TITLE
[not bug]The bounds obtained through BaseLayer.getBounds() are not accurate.

### ISSUE THREAD

**Issue by UI-Animation-Chen** [airbnb/lottie-android#2526]
**Firstly, this is NOT a bug.**

Hello, Lottie team, thanks a lot for your great lottie library. I now want to add the click event capability to the animation elements in Lottie. The implementation principle is to obtain the bounds of the BaseLayer, then convert it back to the bounds in the coordinate system of the screen, and judge whether the layer is clicked through the x and y in the MotionEvent.

1. The conversion of the obtained bounds to the bounds in the screen coordinates is implemented as follows:

        RectF layerTransformedRect = new RectF();
        layer.getBounds(layerTransformedRect, null, false); // get the transformed bounds

        RectF layerOriginRect = new RectF();

        float viewW = getWidth(); // LottieAnimationView's width
        float viewH = getHeight(); // LottieAnimationView's height

        float lottieW = lottieDrawable.getBounds().width();
        float lottieH = lottieDrawable.getBounds().height();

        if (viewW == 0 || viewH == 0 || lottieW == 0 || lottieH == 0) {
            return;
        }

        // just for ScaleType.CenterCrop
        Matrix m = new Matrix();
        float scale;
        if ((lottieW / lottieH) >= (viewW / viewH)) {
            // height fill up，width crop
            scale = viewH / lottieH;
            m.preScale(scale, scale);
            m.postTranslate(-((lottieW * scale - viewW) / 2), 0);
        } else {
            // width fill up，height crop
            scale = viewW / lottieW;
            m.preScale(scale, scale);
            m.postTranslate(0, -((lottieH * scale - viewH) / 2));
        }
        m.mapRect(layerOriginRect, layerTransformedRect);

2. Then it was found that the bounds of some Layers were accurate, but there were some offsets for the layers under the CompositionLayer, like image below. I would like to ask, why are there offsets for the layers under the CompositionLayer? Do different layers need special handling when obtaining the bounds? Looking forward to your reply. Thank you :)

<img width="631" alt="image" src="https://github.com/user-attachments/assets/f9e321ad-a30c-4a3c-8a62-410764f03dc3">

**Comment by gpeal** [comment]
Could you attach a repro?

**Comment by UI-Animation-Chen** [comment]
The solution has been found. When obtaining the bounds through layer.getBounds(outRect, parentMatrix, true), the second and third parameters need to pass in parentMatrix and true, instead of null and false. Thanks to the excellent lottie library.
