### ISSUE TITLE
Allow adding color filter to the whole animation in XML

### ISSUE THREAD

**Issue by ramonaharrison** [airbnb/lottie-android#253]
I'd like to be able to add a color filter to a `LottieAnimationView` in XML, similar to the `tint` attribute for `ImageView`. This would simplify setup for assets that require different tints throughout the app, or those that have color changes based on day/night mode.

I think this could be done by declaring an attribute `lottie_colorFilter` for `R.styleable.LottieAnimationView`. 

This would take a color value in #rrggbb form which could be applied programmatically with `addColorFilter(colorFilter)` using `SRC_ATOP` mode, in `LottieAnimationView#init(AttributeSet attrs)` .

If there is interest in this feature, this is something that I could work to implement.

**Comment by gpeal** [comment]
Fixed by #256

**Comment by jordansilva** [comment]
Is there some way to change color filter programmatically?

**Comment by jordansilva** [comment]
Looking through the LottieAnimationView I found a way to change color filter programmatically but I don't think it's the best way to do it.
`val filter = SimpleColorFilter(Color.parseColor("#fe3144"))
val keyPath = KeyPath("**")
val callback = LottieValueCallback<ColorFilter>(filter)
lottieAnimationView.addValueCallback<ColorFilter>(keyPath, LottieProperty.COLOR_FILTER, callback)`

**Comment by AndroidDeveloperLB** [comment]
How can I set the color to a specific part of the animation?

**Comment by gpeal** [comment]
@AndroidDeveloperLB With a `KeyPath`

**Comment by AndroidDeveloperLB** [comment]
@gpeal Can you please provide a sample for this?

**Comment by gpeal** [comment]
@AndroidDeveloperLB https://github.com/airbnb/lottie-android/blob/master/LottieSample/src/main/kotlin/com/airbnb/lottie/samples/DynamicActivity.kt

**Comment by AndroidDeveloperLB** [comment]
@gpeal Thank you. I've actually found this too:
https://github.com/SolveSoul/lottie-android-colorfilter-sample
