### ISSUE TITLE
Official Lottie Specs available for review

### ISSUE THREAD

**Issue by mbasaglia** [airbnb/lottie-android#2534]
I'm sorry if this doesn't follow the template but it isn't really a bug nor a feature request.

The Lottie Animation Community has [released a draft for the official Lottie v1.0 format specifications](https://lottie.github.io/news/lottie-1.0-draft-review/).

We would greatly appreciate your review and feedback on:
* Any missing features that should be included.
* Features that are implemented in ways incompatible with this draft.
For any issues or suggestions, please use our issue tracker: https://github.com/lottie/lottie-spec/issues

**Comment by gpeal** [comment]
The spec LGTM! Thanks for putting in so much effort to formalize the spec and get us here! This is a huge milestone for Lottie.
