### ISSUE TITLE
2.0beta setLayerType(LAYER_TYPE_HARDWARE) may cause gpu-memory leak

### ISSUE THREAD

**Issue by lizhe-tech** [airbnb/lottie-android#255]
I see in your latest beta version, there's a method not always to use software layer:
@SuppressWarnings({"WeakerAccess", "unused"}) public void useExperimentalHardwareAcceleration() {
    setLayerType(LAYER_TYPE_HARDWARE, null);
  }

In my point, you guys should use LAYER_TYPE_NONE, you needn't use something like hardware layer, but the feature of hardware acceleration. More over, anytime you've set a view with LAYER_TYPE_HARDWARE, you should set to LAYER_TYPE_NONE after animation end, to release the hardware layer. Otherwise, something like 
Fatal Exception: java.lang.IllegalStateException: Unable to create layer for ***
would occur in the future.

**Comment by 2666fff** [comment]
same issue here :(
