### ISSUE TITLE
DynamicProperty color with wildcard doesn't apply to all elements of the animation

### ISSUE THREAD

**Issue by s-faychatelard** [airbnb/lottie-android#2554]
**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Describe the bug**
Applying a color to a wildcard KeyPath doesn't apply to all elements of the animations. This same wildcard applies properly to all the elements of the animation on iOS.
```
val tintColor = Color.Red.toArgb()
val dynamicProperties = rememberLottieDynamicProperties(
  rememberLottieDynamicProperty(
    keyPath = arrayOf("**"),
    property = LottieProperty.COLOR,
    value = tintColor,
  ),
)
```

**What version of Lottie did you test this on?**
6.5.2

**What version of Android did you test this on?**
14

**Steps To Reproduce**
Attached is the animation I'm running. As you can see on the screenshot below, most of the elements are properly applying the color but the outer frame isn't.
[intro_smile_amovens_con_gomore.json](https://github.com/user-attachments/files/17165911/intro_smile_amovens_con_gomore.json)

**Screenshots**
![Screenshot_20240927_164833](https://github.com/user-attachments/assets/14d232bf-8128-4c91-acc0-4174e090dc3a)

**Comment by gpeal** [comment]
You need to set `LottieProperty.STROKE_COLOR` in addition to COLOR. COLOR just does fills.
