### ISSUE TITLE
lottie 5.0.2 crash

### ISSUE THREAD

**Issue by tianshaokai** [airbnb/lottie-android#2572]
java.lang.IllegalStateException:Unable to parse composition
2
com.airbnb.lottie.LottieAnimationView.lambda$static$0(SourceFile:3)
3
......
4
Caused by:
5
java.lang.NullPointerException:Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference
6
com.airbnb.lottie.LottieCompositionFactory.fromAssetSync(SourceFile:3)
7
com.airbnb.lottie.LottieCompositionFactory.lambda$fromAsset$1(SourceFile:1)
8
com.airbnb.lottie.LottieCompositionFactory.c(Unknown Source:0)
9
com.airbnb.lottie.h.call(Unknown Source:6)
10
java.util.concurrent.FutureTask.run(FutureTask.java:264)
11
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
12
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
13
java.lang.Thread.run(Thread.java:1012)

**Comment by gpeal** [comment]
This is an issue with your animation json

**Comment by tianshaokai** [comment]
Hello, where exactly is the problem? Our animation teacher didn't see any issues.
