### ISSUE TITLE
Access to UserMetadata for an animation

### ISSUE THREAD

**Issue by jlw8ke** [airbnb/lottie-android#2574]
**Is your feature request related to a problem? Please describe.**
The lottie animation files have an optional [User Metadata](https://lottiefiles.github.io/lottie-docs/animation/#user-metadata) field that could be used to provide custom properties for an animation.  Currently, there is not a built-in way to access this metadata field from the Lottie library.

**Describe the solution you'd like**
Access to the UserMetadata field from a `LottieComposition`.  If the lottie [parser](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/parser/LottieCompositionMoshiParser.java) examined the metadata field and included the customProps from the metadata in the composition, users would then be able to access the metadata and parse it using whatever method is applicable.

**Describe alternatives you've considered**
Using a separate configuration file to associate a lottie animation with metadata.  This seems like workarounds though, since a metadata field is supported in the lottie format.

**Comment by gpeal** [comment]
I think you meant to post this on [lottie-web](https://github.com/airbnb/lottie-web)
