### ISSUE TITLE
Do you have a plan to support KMP?

### ISSUE THREAD

**Issue by BurningDroid** [airbnb/lottie-android#2576]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gpeal** [comment]
No plans as part of this library. The renderer is tightly coupled to the Android Canvas APIs.

https://github.com/alexzhirkevich/compottie exists but I have no connection to it and am not sure what its status us.
