### ISSUE TITLE
Lottie animation rendering issue after coming back from juspay sdk page

### ISSUE THREAD

**Issue by chaithu917** [airbnb/lottie-android#2579]
*Lottie is supported and developed on nights and weekends. Issues from [Lottie sponsors](https://github.com/users/gpeal/sponsorship) will be prioritized.*

**If you don't use this template, your issue will be closed. Delete this text once completed.**

**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Describe the bug**
We have a banners on our home page in a view pager and the banners will load from url's, it is a combination of images and lotties, and the view pager is working fine, Issue comes in the following steps and also attached reference video.

From home screen we are launching a juspay sdk page to process the payments, post returning from juspay sdk page view pager lottie animations are not rendering properly.

I have tried following but nothing worked
1.⁠ ⁠Clearing cache of lottie view
2.⁠ ⁠⁠Setting render mode for lottie view as HARDWARE or SOFTWARE both
3.⁠ ⁠⁠Setting flag for the window as FLAG_HARDWARE_ACCELERATED
4.⁠ ⁠⁠also added the tag in Android Manifest(android:hardwareAccelerated="true")
5.⁠ ⁠⁠Even tried moving the juspay loading to a different activity to make sure juspay SDK won’t override the rendering activities of my home activity

**What version of Lottie did you test this on?**
Lottie: 6.6.0
Juspay: 2.1.33

**What version of Android did you test this on?**

**Steps To Reproduce**

**Screenshots**
https://github.com/user-attachments/assets/78716da7-c567-404d-989d-96f7064f3a59

**Comment by gpeal** [comment]
Can you attach a sample project that reproduces this?

**Comment by chaithu917** [comment]
I am pasting the apk here.
https://drive.google.com/file/d/1RzXjUB8Y0gjZy61ifpAu9L39smuVPGcg/view?usp=drive_link
Steps to reproduce
1. Enter mobile number & OTP to register
2. you can see banners on the home screen(3 & 4 are the lottie animations)
3. click on wallet at bottom navigation bar
4. select amount and click on paynow, it will open juspay SDK page
5. select test wallet and do a success payment
6. on returning back from juspay you will land on the home screen and check the lottie animations.

**Comment by gpeal** [comment]
@chaithu917 An APK isn't helpful here, I need a project with sample code.

**Comment by gpeal** [comment]
@chaithu917 I'm going to close this out without sample code for now. Feel free to reopen this if you can provide sample code.
