### ISSUE TITLE
isAtEnd is incorrectly true

### ISSUE THREAD

**Issue by NinoDLC** [airbnb/lottie-android#2581]
**Link to fork with a repro in the issue-repro module**
https://github.com/NinoDLC/lottie-android/commit/1cb3d890

**Describe the bug**
`LottieAnimationState.isAtEnd` is incorrectly `true`, making listening to end of animation impossible.

**Steps To Reproduce**

1. Launch the provided code
2. Check Logs to see this incorrect behavior: 
```
13:33:28.043 isAtEnd 0
[...]
13:33:28.267 LaunchedEffect.isAtEnd 1
13:33:28.710 isAtEnd 2
13:33:30.799 isAtEnd 3
13:33:30.809 LaunchedEffect.isAtEnd 4
```

**Comment by JohannesPtaszyk** [comment]
We also encounter this with version: 6.6.0

The initial value of isAtEnd is always true. 
But also trying to use progress == 1f is not working.

``` kotlin
        var clipSpec: LottieClipSpec? by remember { mutableStateOf(null) }

        val composition by rememberLottieComposition(
            LottieCompositionSpec.RawRes(com.example.app.design.icons.R.raw.lottie_animation) // <- this is a .lottie file
        )

        val animationState = animateLottieCompositionAsState(
            composition = composition,
            iterations = LottieConstants.IterateForever,
            clipSpec = clipSpec,
        )

        LaunchedEffect(animationState.progress) {
            // Workaround for https://github.com/airbnb/lottie-android/issues/2581
            // animationState.isAtEnd is always true as first value.
            if (animationState.progress > 0.9f) {
                clipSpec = LottieClipSpec.Frame(48, 282)
            }
        }

        LottieAnimation(
            composition = composition,
            progress = { animationState.progress },
            enableMergePaths = true,
            modifier = Modifier
                .fillMaxWidth()
                .heightIn(min = 160.dp)
        )
```

**Comment by gpeal** [comment]
I think the issue you are both experiencing comes from the fact that Lottie compositions are parsed asynchronously. While the composition is parsing (and LottieAnimation is getting `null` as its composition), `isAtEnd` is true because it's technically at the end of nothing.

For both of your cases, I believe checking for `isAtEnd && composition != null` would work.

If that isn't the case, feel free to reopen this with a more specific example.

**Comment by JohannesPtaszyk** [comment]
I tried this, but it is not helping. 
Seems like isAtEnd is still true, while first time composition is != null.

**Comment by JohannesPtaszyk** [comment]
Hey, I tried this out, but it does not seem to be working. However, maybe you can double check, if i missed something in the code:

``` kotlin
    var clipSpec: LottieClipSpec by remember {
        mutableStateOf(LottieClipSpec.Frame(INITIAL_MIN_FRAME))
    }

    val composition by rememberLottieComposition(
        LottieCompositionSpec.RawRes(com.example.app.design.icons.R.raw.lottie_animation)
    )

    val animationState = animateLottieCompositionAsState(
        composition = composition,
        iterations = LottieConstants.IterateForever,
        clipSpec = clipSpec,
    )

    LaunchedEffect(animationState.isAtEnd, composition) {
        if (animationState.isAtEnd && composition != null) {
            clipSpec = LottieClipSpec.Frame(LOPPING_MIN_FRAME)
        }
    }
```

**Comment by gpeal** [comment]
@JohannesPtaszyk Can you describe what you're trying to achieve?

**Comment by JohannesPtaszyk** [comment]
Basically I want to run 1 full animation circle and after that clip between specific frames :)

**Comment by gpeal** [comment]
> Basically I want to run 1 full animation circle and after that clip between specific frames :)

You may be better off with the animatable API

```
    @Composable
    fun Content() {
        val composition by rememberLottieComposition(LottieCompositionSpec.RawRes(R.raw.heart))
        val animatable = remember { LottieAnimatable() }

        LaunchedEffect(composition, animatable) {
            composition ?: return@LaunchedEffect
            animatable.animate(composition)
            while (true) {
                animatable.animate(composition, clipSpec = LottieClipSpec.Frame(LOOPING_MIN_FRAME))
            }
        }

        LottieAnimation(composition, { animatable.progress })
    }
```

**Comment by gpeal** [comment]
> Will look into it :) However it seems like isAtEnd behavior might be worth discussing? 🤔

Can you isolate if there is an issue with isAtEnd other than it being true when the composition is still null?

**Comment by JohannesPtaszyk** [comment]
I feel like it being true when composition is null, is unexpected. 
The question I was asking myself was "If something is not there, can the animation be at the end or did it never start?". My intuitive thought was: No if its not there it never started, so I expect isAtEnd to return false in that case. 

But not sure if its just me or if others could face the issue as well. Just some quick thought on that :)

**Comment by NinoDLC** [comment]
Same reasoning here, I was very confused. `isAtEnd` "oscillating" between `true`, `false` and then `true` makes no sense to me when using a non-repeated LottieAnimation. 

Maybe rename the boolean ? Something like `hasStartedAtLeastOnceAndIsAtEnd` ? :troll:
