### ISSUE TITLE
Unable to Render .lottie Files Due to Incorrect File Type Parsing from Metro Bundler URLs

### ISSUE THREAD

**Issue by aminerol** [airbnb/lottie-android#2595]
**Checklist**  
1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features). ✅  
2. I know what part of my animation doesn't work. ✅  
   - **Details**: The `.lottie` file fails to render because the `fromInputStream` function can't determine the file type from Metro Bundler's URL.
3. I have created a simplified version of my animation. ✅  
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work. ❌  

---

**Describe the bug**  

I am using Lottie for React Native, where assets are served as URLs via Metro Bundler. In this setup, Metro Bundler generates URLs for Lottie files, but these URLs do not make it through the https://github.com/airbnb/lottie-android/blob/7b89be69ff01a5665d8d722de56e1554f65177fd/lottie/src/main/java/com/airbnb/lottie/network/NetworkFetcher.java#L126 function correctly to determine the file type. This occurs because Metro Bundler itself does not assign the correct content type for `.lottie` files.

As a result, the `.lottie` file fails to render, as the function cannot reliably parse the file type from the URL. 

For better handling, it would be ideal if the file extension could be extracted directly from the URL using a standard URL library instead of relying on simple regex. or verify if the content-type contains `application/zip+dotlottie`
This approach would cover more cases and avoid such issues.

**Example URL from Metro Bundler**  
An example of a Lottie URL produced by Metro Bundler:  
`http://192.168.11.101:8081/assets/?unstable_path=.%2Fsrc%2Fshared%2Fassets%2Flottie%2Fanimation.lottie&platform=android&hash=f57e0ca1f6a44dbc0812204bc0eaa0e5`

---

**What version of Lottie did you test this on?**  
`6.6.1`

---

**What version of Android did you test this on?**  
`API 35`

---

**Steps To Reproduce**  
1. Any lottie from remote server that matches the example above
2. Attempt to render the animation.  
3. Observe that the animation does not display correctly and fails with a parsing exception.  

---

**Screenshots/Additional Info**  
N/A

**Comment by gpeal** [comment]
For this, I would recommend implementing your own NetworkFetcher [here](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieConfig.java#L57)
