### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by adamhairfield** [airbnb/lottie-android#260]
I am having issues with rendering json animation through Lottie. Everything we have done so far for iOS works fine but for some reason bits and pieces are missing randomly from animations in Android. 

For example, the attached file renders with a missing bottom tongue. Can't figure out what I am doing wrong.

Should look like this:
![screen shot 2017-04-20 at 11 07 31 am](https://cloud.githubusercontent.com/assets/6201314/25240855/a675256a-25b9-11e7-86a5-a2dfc6577604.png)

But shows up like this in Android:
![screen shot 2017-04-20 at 11 07 44 am](https://cloud.githubusercontent.com/assets/6201314/25240866/afe19cc8-25b9-11e7-82b4-d3cdf9e972db.png)

[surprise-emoji.zip](https://github.com/airbnb/lottie-android/files/944348/surprise-emoji.zip)

**Comment by gpeal** [comment]
@adamhairfield What version of Lottie are you using? Mine looks like this with 2.0.0-beta4
![image](https://cloud.githubusercontent.com/assets/1307745/25244275/9f1a888a-25c5-11e7-9262-0d270812fd4b.png)

**Comment by sonaye** [comment]
I am having a similar problem, using lottie-react-native 1.1.1

ios
<img width="167" alt="screen shot 2017-04-26 at 1 21 51 am" src="https://cloud.githubusercontent.com/assets/23000873/25410349/cf9675f2-2a1e-11e7-918a-f389ab2d053b.png">

android
<img width="189" alt="screen shot 2017-04-26 at 1 20 00 am" src="https://cloud.githubusercontent.com/assets/23000873/25410353/d614f566-2a1e-11e7-9467-72d960525609.png">

**Comment by sonaye** [comment]
1.1.1 uses 2.0.0-beta3, was this addressed in beta4 or after it?

**Comment by gpeal** [comment]
@sonaye can you attach the aep file?

**Comment by sonaye** [comment]
@gpeal can't share the same animation, but i can share another one which suffers from the same issue, actually most of the animations that i have (around 30) suffer from renderrig issues on android while working perfectly on ios.

<img width="473" alt="screen shot 2017-04-26 at 1 58 10 am" src="https://cloud.githubusercontent.com/assets/23000873/25411233/3d7f8dce-2a24-11e7-8c77-d5dc1a458e2f.png">

left: ios, right: android

[disabled.zip](https://github.com/airbnb/lottie-android/files/956781/disabled.zip)

**Comment by gpeal** [comment]
@sonaye This is what it looks like for me. Try scanning this qr code from the lottie sample app in the play store. It should load your animation:

![image](https://cloud.githubusercontent.com/assets/1307745/25413006/c5341328-29db-11e7-9445-9e6f13a4b1b9.png)

![image](https://cloud.githubusercontent.com/assets/1307745/25412965/9f170830-29db-11e7-89f7-a5445c2ec5c0.png)

**Comment by zokipirlo** [comment]
[This animation](http://www.lottiefiles.com/124-download) from LottieFiles is broken in Lottie Preview application.

**Comment by sonaye** [comment]
@gpeal can you try it on beta3 to confirm wether this issue is specific to that version? what version did you test it on?

**Comment by zhangsn** [comment]
I have similar problem when running the demo 'LottieLogo1.json' on Android 4.4.4. A lot of lines are missing. Other demo also have same problem.
![device-2017-04-27-195456](https://cloud.githubusercontent.com/assets/1401172/25482237/7e1b70f4-2b83-11e7-9d1a-4ae5a11055b0.png)

**Comment by sonaye** [comment]
@gpeal what version did you use to test the animation, beta4? can we get a confirmation? we are trying to get this patched in expo.

**Comment by gpeal** [comment]
@zhangsn What device is that? I am unable to repro this on any of mine.

@sonaye I don't understand your question

**Comment by sonaye** [comment]
@gpeal what lottie-android version did you use to test here https://github.com/airbnb/lottie-android/issues/260#issuecomment-297202473, beta4?

**Comment by zhangsn** [comment]
@gpeal Thanks for the reply
Redmi 2A and a Meizu M1
![image](https://cloud.githubusercontent.com/assets/1401172/25646861/2ca27324-2fef-11e7-9741-d86b06d49cff.png)

![image](https://cloud.githubusercontent.com/assets/1401172/25646851/113f6f38-2fef-11e7-9f77-7ed90595d4e3.png)

They all render like this gif
![ezgif-1-92e4e9d468](https://cloud.githubusercontent.com/assets/1401172/25646871/41c158e2-2fef-11e7-838b-4535379f36c9.gif)

**Comment by vbe** [comment]
Same issue here, it looks like for versions under Lollipop the animation is missing quite a few lines.

**Comment by gpeal** [comment]
@sonaye I think your issue will be fixed by this: https://github.com/airbnb/lottie-react-native/pull/129

**Comment by sonaye** [comment]
@gpeal it completely make sense that having no decimals would cause these glitches in the drawings.
