### ISSUE TITLE
ColorFilter doesn't work for layers used in secondary compositions

### ISSUE THREAD

**Issue by asdfg17** [airbnb/lottie-android#261]
Android 6.0.1
Lottie Version 2.0.0-beta4
I have a JSON in witch all layers are shape type. Some of them are included in secondary compositions. For this ones I can't add a color filter. From what I sow, this happens partially because layers from assets are not taken in consideration. Even after I included them, this didn't solve the problem. Should this cases be covered or for now , in order to add a color filter all layers should be used in the main composition? Thanks:)

**Comment by gpeal** [comment]
@seanfchan Fyi.

This makes sense to me. Sean, do you want to take a look or do you want me to?

**Comment by gpeal** [comment]
@asdfg17 I just tried this and it worked. Precomps are added to the main composition during deserialization. Maybe you're not using the right layer/content name?
If you can't get it to work, attach a sample AE file that's broken.
