### ISSUE TITLE
GradientFillContent does not consider the transforms on gradient shader 

### ISSUE THREAD

**Issue by kswlee** [airbnb/lottie-android#262]
If the gradient contains transformations, the rendering result would be inconsistent with the AE result. Please try the attache AE project, and you should be able to compare the differences. 
Thanks a lot.
[cms_v4_mainprocess_animation_1704.aep.zip](https://github.com/airbnb/lottie-android/files/949835/cms_v4_mainprocess_animation_1704.aep.zip)

**Comment by gpeal** [comment]
Tracking this issue in #47
