### ISSUE TITLE
File not working when exported to .json Body Movin

### ISSUE THREAD

**Issue by BreeKeogh** [airbnb/lottie-android#263]
Hi there, 

I'm really hoping that someone can help me!

I am trying to make an animation for an android app and when I export my animation using BodyMovin and when the .json file is used the animation doesn't show up. 

Hoping someone can help me figure out what is in my file that isn't supported and possibly help me out with a work around! 

The Comp is Comp 5 in the file.
[Green circle tick 2.aep.zip](https://github.com/airbnb/lottie-android/files/950405/Green.circle.tick.2.aep.zip)

Thanks

**Comment by gpeal** [comment]
@BreeKeogh Lottie doesn't support slider control effects. You can achieve this same effect by animating a trim pat though
