### ISSUE TITLE
Add color filter sample code

### ISSUE THREAD

**Issue by TinoGuo** [airbnb/lottie-android#267]
Thank u for the great library!
Could u commit some sample code about add color filter? Because I'm not familiar with AE, also have no idea about layer name and content name. I just want to implement color filter with progress.
Thanks a lot!!!👍

**Comment by gpeal** [comment]
@TinoGuo Are you trying to use an animation created by somebody else? If so, you can search for "nm" in the json in which you see something like this:
![image](https://cloud.githubusercontent.com/assets/1307745/25598960/4bd23d64-2e8d-11e7-9ec9-b4f1b7d48927.png)

**Comment by TinoGuo** [comment]
@gpeal I got it! Thanks
