### ISSUE TITLE
Unknown Crop! 

### ISSUE THREAD

**Issue by Animissimo** [airbnb/lottie-android#270]
When I export my animation and test it with Android Studio it's croped! 
[Assets.zip](https://github.com/airbnb/lottie-android/files/964826/Assets.zip)
![preview](https://cloud.githubusercontent.com/assets/28153243/25536280/e5c50070-2c42-11e7-93c6-20faa5d63b69.png)

**Comment by gpeal** [comment]
@Animissimo I think your composition may be too large. The size of your composition will be converted to dps so try making it smaller.

**Comment by Animissimo** [comment]
When I try to do the same for any other shape layers - it works perfectly. How do you think, what's wrong with my animation shape layer?

**Comment by Animissimo** [comment]
I spent the weekend figuring out what the problem is))) It seems like the case in the project in which I'm testing the animation
