### ISSUE TITLE
Can we add touch listeners separately for every object in a json file?

### ISSUE THREAD

**Issue by arshujain** [airbnb/lottie-android#272]
suppose your json file has 4 objects that are animating.
I want to control one object irrespective of others. Ex- pausing animation, slow down animation ,etc for only one object while others are animating at normal pace.

**Comment by gpeal** [comment]
@arshujain You can have multiple LottieDrawables/LottieAnimationViews going at once. I suggest you export each object as a separate animation then you can control them all independently and just make them overlap by putting them all in a FrameLayout or something.

If you want them to play in sync, create your own ValueAnimator that goes from 0 to 1 and in the update listener for that, set the progress of all of your objects together and they'll stay in sync.
