### ISSUE TITLE
The Octopus animation looks like something is wrong

### ISSUE THREAD

**Issue by AlanCheen** [airbnb/lottie-android#275]
screenshot:

![octpus](http://ww1.sinaimg.cn/large/98900c07gy1ff7zc8wmk7j20u01hc0v0.jpg)

**Comment by gpeal** [comment]
I don't like any of my workarounds so far. I'll keep working on it but if you encounter this, add control point handles to vertices that are missing them.

**Comment by AlanCheen** [comment]
Ok, thank you.

**Comment by gpeal** [comment]
I can no longer repro this
