### ISSUE TITLE
Wicht is the proper way to trigger other events when animation gets to a certain point/progress

### ISSUE THREAD

**Issue by asdfg17** [airbnb/lottie-android#276]
If I try to use getProgress inside addAnimatorUpdateListener(), I will always receive other values. That is because addAnimatorUpdateListener() will not return a constant counter that increments itselfs, and I can't compare that values in order to trigger other events, like showing a text under etc. Should be other way to do this? Thanks.

**Comment by gpeal** [comment]
@asdfg17 I don't understand your question. Can you be more specific?

**Comment by asdfg17** [comment]
How can I know exactly the progress of my animation, so that I can compare and show certain things at a specific time/progress that I want? For example showing a text under, when anim reached 1000 ms.

**Comment by gpeal** [comment]
You can add an update listener to LottieAnimationView or LottieDrawable and check the progress there.
