### ISSUE TITLE
API-specific animation bug

### ISSUE THREAD

**Issue by amatsegor** [airbnb/lottie-android#278]
I've done all the steps of implementing Lottie animation in my project
On API 23 and above things are going well, but when I'm triyng to test an animation on Lollipop or Kitkat device (device or emulator, doesn't matter, result is the same), I'm getting a strange look such as this

<= API22
![screenshot_1493805302](https://cloud.githubusercontent.com/assets/1627127/25656776/482c3602-3003-11e7-8e34-38a297c6ff91.png)

\> API22
![screenshot_1493805363](https://cloud.githubusercontent.com/assets/1627127/25656807/68304542-3003-11e7-8253-7a96d8dbdb41.png)

JSON+image:
[Animation.zip](https://github.com/airbnb/lottie-android/files/973026/Animation.zip)

**Comment by gpeal** [comment]
Hmm, it looks fine for me. this is on 4.2.2. Can you try cloning the repo trying it in the sample app?
![image](https://cloud.githubusercontent.com/assets/1307745/25785926/a13a5a68-3359-11e7-837e-2a465dc35b9a.png)

**Comment by gpeal** [comment]
@amatsegor Feel free to reopen this if it's still an issue.
