### ISSUE TITLE
Bad JSON opt calls

### ISSUE THREAD

**Issue by Igor1201** [airbnb/lottie-android#279]
Hey there, I'm using lottie `2.0.0-beta4` via lottie-react-native `1.1.1`.
My app crashes when I try to use `<Animation />`. The crash however only happens on Android:

```
05-03 15:31:04.106 26506 26536 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-03 15:31:04.106 26506 26536 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:325)
05-03 15:31:04.106 26506 26536 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
05-03 15:31:04.106 26506 26536 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
05-03 15:31:04.106 26506 26536 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
05-03 15:31:04.106 26506 26536 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-03 15:31:04.106 26506 26536 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-03 15:31:04.106 26506 26536 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
05-03 15:31:04.106 26506 26536 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.json.JSONArray.length()' on a null object reference
05-03 15:31:04.106 26506 26536 E AndroidRuntime: 	at com.airbnb.lottie.LottieComposition$Factory.parseLayers(LottieComposition.java:200)
05-03 15:31:04.106 26506 26536 E AndroidRuntime: 	at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(LottieComposition.java:194)
05-03 15:31:04.106 26506 26536 E AndroidRuntime: 	at com.airbnb.lottie.JsonCompositionLoader.doInBackground(JsonCompositionLoader.java:17)
05-03 15:31:04.106 26506 26536 E AndroidRuntime: 	at com.airbnb.lottie.JsonCompositionLoader.doInBackground(JsonCompositionLoader.java:7)
05-03 15:31:04.106 26506 26536 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
05-03 15:31:04.106 26506 26536 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-03 15:31:04.106 26506 26536 E AndroidRuntime: 	... 3 more
```

Every `opt` call to `json` object is returning the fallback. Strangely enough, the `get` calls return the value correctly. While debugging, if I do `json.getJSONArray("layers")` it returns `[]`, and `json.optJSONArray("layers")` returns `null`.

The same happens with the other key names:
![image](https://cloud.githubusercontent.com/assets/735858/25677232/88ddec78-301b-11e7-858e-7534b2155025.png)

That's probably related with https://github.com/airbnb/lottie-android/pull/128, as using v1.0.3 down doesn't crash the app (but doesn't show the animation either).

**Comment by gpeal** [comment]
@Igor1201 What version of After Effects/bodymovin are you using? Can you attach the aep or json file? I'm not sure why this would only happen in certain situations unless it's with a different version of AE or bodymovin.

**Comment by Igor1201** [comment]
@gpeal I've tested with some proprietary exported animations using AE CC, but it behaves exactly the same way with the [lottie-react-native samples](https://github.com/airbnb/lottie-react-native/blob/master/example/animations/). Also, all animations I've tested work fine on iOS.

We're compiling to android 25, with minSdkVersion 16, using build-tools 25.0.2.
The `json` object while debugging seems to have all data (and that's why I can `.get` something from it).
The only reason I can think of is thread concurrency, as `JSONObject` [is not thread-safe](https://developer.android.com/reference/org/json/JSONObject.html).

**Comment by gpeal** [comment]
@Igor1201 Is this coming from React Native?

**Comment by Igor1201** [comment]
@gpeal yes, it is

**Comment by gpeal** [comment]
@Igor1201 Seems like the json marshalling isn't correct coming from the javascript side. I may create a workaround but I'd like to fix the root cause.

**Comment by Igor1201** [comment]
@gpeal of course, what can I do to help?
