### ISSUE TITLE
Is this a Facebook Keyframes clone?

### ISSUE THREAD

**Issue by ber4444** [airbnb/lottie-android#28]
Very similar to https://github.com/facebookincubator/Keyframes, at least you should explain why do we need a new project? What is it that you are improving?

**Comment by gpeal** [comment]
We do actually mention Keyframes and the differences in the [blog post](https://medium.com/airbnb-engineering/introducing-lottie-4ff4a0afac0e#.qm73q4xek) and [readme](https://github.com/airbnb/lottie-android#alternatives).

Keyframes was built primarily for reactions and includes the After Effects feature set that they needed for reactions. We set out to support as much of After Effects as possible. Currently Lottie supports trim paths, dash patterns, masks, mattes, more time interpolations, different kinds of shapes, and a few things that Keyframes doesn't. Keyframes currently supports gradients and Lottie doesn't. However, that's something we're looking at adding.

Both projects were started independently and in parallel. We started ours in 2015 and Facebook started to build Reactions. We think it's awesome that Facebook saw the same need as us and we're looking forward to learning from each other's discoveries and collaborating to make the entire ecosystem better.
