### ISSUE TITLE
Animation takes a long time to "show"

### ISSUE THREAD

**Issue by madd86** [airbnb/lottie-android#284]
I'm trying to show a dialog with an animation while the user waits for the AsyncTask to finish.

To achieve this, I used the following code (inside AsyncTask)?

```
protected void onPreExecute() {
super.onPreExecute();
    //Custom Dialog
    customDialog = new Dialog(mContext);
    customDialog.setContentView(R.layout.dialog_custom);
    customDialog.setTitle("Looking for address");

    //Custom Dialog Animation
    LottieAnimationView animationView = (LottieAnimationView) customDialog.findViewById(R.id.animation_view);
    animationView.setAnimation("PinJump.json"); //Lottie's premade animation
    animationView.loop(true);
    animationView.playAnimation();

    //Custom Dialog Text
    TextView text = (TextView) customDialog.findViewById(R.id.textView);
    text.setText(R.string.dialog_looking_for_address);
    customDialog.show();
}
```

The code above works wonderfully.

The only problem is that the animation takes about north of 1 second to show up. So I end up seeing the text way before the animation.

Is there anyway to make the animation show up as soon as the dialog is up? I tried casting the json file directly to the XML, but no dice, same thing happened.

**Comment by gpeal** [comment]
@madd86 It's likely the time it takes to do the json parsing. You can load the create the LottieDrawable or LottieComposition ahead of time and just set it on your LottieAnimationView so you can do the loading ahead of time. It should show up immediately then.

**Comment by madd86** [comment]
@gpeal How do I load it ahead of time? Can I load it on the MainActivity?

**Comment by gpeal** [comment]
Yes, you can call LottieComposition.fromAssetFileName whenever/wherever you'd like.

**Comment by gpeal** [comment]
@madd86

**Comment by madd86** [comment]
@gpeal only problem is that my custom dialog is reused a few times, so I can't exactly set an animation beforehand.

Can I use that command to parse all the available animation, maybe asynchronously? 

Get the animations ready somehow..

**Comment by madd86** [comment]
@gpeal Made it work, thank you.

**Comment by RobertoIDL** [comment]
Hi,

I'm facing the exact same issue now. I want to show the animation inside one of my dialog, and the animation takes a few milliseconds to show. Can you please let us know what you did to fix it? 

Meanwhile I will try to load the animation in advance.

Thanks.

**Comment by madd86** [comment]
@RobertoIDL You can find what I used below:

```
        LottieComposition.Factory.fromAssetFileName(mContext, "PinJump.json", new OnCompositionLoadedListener() {
            @Override
            public void onCompositionLoaded(LottieComposition composition) {
                mAnimationView.loop(true);
                mAnimationView.playAnimation();
                TextView text = (TextView) customDialog.findViewById(R.id.textView);
                text.setText(R.string.dialog_looking_for_address);
                customDialog.show();
            }
        });
```

The above code should be loaded before the dialog shows up.

**Comment by RobertoIDL** [comment]
Thanks!!!

I was just trying exactly the same:

`  LottieComposition.Factory.fromAssetFileName(ActMain.this, "test.json", new OnCompositionLoadedListener() {
            @Override
            public void onCompositionLoaded(@Nullable LottieComposition composition) {
                LayoutInflater inflater = LayoutInflater.from(ActMain.this);`

Working good!

**Comment by saketkumar** [comment]
@gpeal I'm using the LottieAnimationView in my splash screen. How to load the json fast to avoid white screen. 

Currently the flow is : 

White screen(for max 2-3 seconds) -> LottieAnimationView -> MainActivity. 

How to solve this ?

**Comment by MegBasutkar05** [comment]
LottieComposition.Factory.fromAssetFileName is deprecated now

**Comment by gpeal** [comment]
@MegBasutkar05 The APIs have moved to `LottieCompositionFactory`
