### ISSUE TITLE
Is executing animation with fail

### ISSUE THREAD

**Issue by charleston10** [airbnb/lottie-android#287]
**Version: 2.0.0-beta4**
I'm changing animation with same lotties

1 - lottie1.json (2 seconds)
2 - lottie2.json (2 seconds)
3 - lottie3.json (2 seconds)

When I change lottie1 to lottie2, the second lottie is executing by 1 seconds or some times don't executing
I did have this problem with queue animation in view, because this android don't delete this animation in some devices causing conflicts bettween them

I used this code for correct this problem, for after change animation in another components that I worked

```
@Override
public void onAnimationEnd(Animator animation) {
        removeQueueAnimator();
        onEnd();
}

@Override
public void onAnimationCancel(Animator animation) {
        removeQueueAnimator();
        onCancel();
}

private void removeQueueAnimator() {
        view.clearAnimation();
        view.animate().setListener(null);
}
```

**Comment by gpeal** [comment]
@charleston10 It's not clear what the issue is without seeing more of the code. Is there something actionable here?

**Comment by charleston10** [comment]
When I change this animation in the LottieView, the second animation executing by self or in some times don't execute (this case only show this first frame)

**Comment by charleston10** [comment]
```
lottieView.setAnimation("lottie1.json");
lottieView.playAnimation();
lottieView.addAnimatorListener(new Animator.AnimatorListener() {
            @Override
            public void onAnimationStart(Animator animator) {
                
            }

            @Override
            public void onAnimationEnd(Animator animator) {
                lottieView.pauseAnimation();
                lottieView.setAnimation("lottie2.json");//only showed this first frame
                lottieView.playAnimation();
            }

            @Override
            public void onAnimationCancel(Animator animator) {

            }

            @Override
            public void onAnimationRepeat(Animator animator) {

            }
        });
```

**Comment by charleston10** [comment]
# # #

**Comment by gpeal** [comment]
@charleston10 Can you try my solution here: https://github.com/airbnb/lottie-android/issues/250

I think it's the same issue

**Comment by charleston10** [comment]
@gpeal can solve my problem.. But this code is very **"workaround"**

**Comment by gpeal** [comment]
@charleston10 I agree. I've been thinking about a way to set up scenes or animation sets. I'll start trying some stuff out after 2.0 final.

**Comment by gpeal** [comment]
#291

**Comment by charleston10** [comment]
No problems.. Thanks by your help ;)

**Comment by franrc** [comment]
Hi, I had the same problem, it seems that the setAnimation takes some time for load the json. 
My solution is to add a short timer before launching the animation : 

```
lottieView.setAnimation("lottie1.json");
lottieView.playAnimation();
lottieView.addAnimatorListener(new Animator.AnimatorListener() {
            @Override
            public void onAnimationStart(Animator animator) {
                
            }

            @Override
            public void onAnimationEnd(Animator animator) {
                lottieView.pauseAnimation();
                lottieView.setAnimation("lottie2.json");//only showed this first frame

                new Handler().postDelayed(new Runnable() {
                     @Override
                     public void run() {
                          lottieView.playAnimation();
                    }
                 }, 300);
            }

            @Override
            public void onAnimationCancel(Animator animator) {

            }

            @Override
            public void onAnimationRepeat(Animator animator) {

            }
        });
```

Hope it helps.

**Comment by Phoca** [comment]
I have the same problem. I want to play three jsons in sequence.
When I set the new Animation file in the `onAnimationEnd`-Callback and call `playAnimation` afterwards, the new animation can be seen for a split second, after that `onAnimationEnd` is called again. The workaround with the Handler from @franrc works, however it either causes an unnecessary delay worsening user experience if chosen too high, or there's a risk of the animation being skipped completely if the animation hasn't been loaded after the delay.

Now my feature request (should I open a new issue?): Is it possible to add another listener that fires as soon as the animation file is loaded and ready to play? That shouldn't be too complex to implement and solve the problem since `playAnimation` can then be called in the listener. Thanks!

**Comment by Phoca** [comment]
I've been digging in the sources and found out that the public method `setComposition` is called as soon as the json is loaded. I've overridden the LottieAnimationView with the following (Kotlin) code:

```
class LottieAnimationView @JvmOverloads constructor(context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0) :
        LottieAnimationView(context, attrs, defStyleAttr) {

    var playWhenReady = false

    override fun setComposition(composition: LottieComposition) {
        super.setComposition(composition)
        if(playWhenReady) {
            playAnimation()
            playWhenReady = false
        }
    }
}
```
Now I just set `playWhenReady` to true instead of calling `playAnimation` and it works like a charm :)

**Comment by gpeal** [comment]
@Phoca https://github.com/airbnb/lottie-android/pull/625

**Comment by Phoca** [comment]
@gpeal Thanks for the super fast fix! Calling `playAnimation` works as expected now with 2.5-RC2.
