### ISSUE TITLE
How do i use a json that refers to images without having them in the assets folder

### ISSUE THREAD

**Issue by mattinger** [airbnb/lottie-android#290]
I'm trying to load a .json file with the sample app from the Download folder on my device.  In there, i have a .json file which references two images within the "images" folder (relative to the .json file).  However it keeps crashing.

I can see on the main docs page it talks about having images in the assets folder, but i'm not going to be delivering these in the assets folder.  They will be downloaded at runtime.

**Comment by mattinger** [comment]
```
05-09 12:00:57.809 15858-15858/com.airbnb.lottie E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.airbnb.lottie, PID: 15858
                                                                   java.lang.IllegalStateException: You must set an images folder before loading an image. Set it with LottieComposition#setImagesFolder or LottieDrawable#setImagesFolder
                                                                       at com.airbnb.lottie.ImageAssetBitmapManager.bitmapForId(ImageAssetBitmapManager.java:70)
                                                                       at com.airbnb.lottie.LottieDrawable.getImageAsset(LottieDrawable.java:445)
                                                                       at com.airbnb.lottie.ImageLayer.getBitmap(ImageLayer.java:57)

```

**Comment by gpeal** [comment]
You can use `ImageAssetDelegate` :) There is an example in the README.

**Comment by RishabhTayal** [comment]
Is there a way to download the images asynchronously and then provide it to `setImageAssetDelegate` method? I want to load image from a url asynchronously.

**Comment by gpeal** [comment]
@RishabhTayal Yes, just return null until the image downloads then return the bitmap.

**Comment by RishabhTayal** [comment]
@gpeal Will try that. Thanks!  👍
