### ISSUE TITLE
Create a Scene/AnimationSet to sequence/loop sets of animations.

### ISSUE THREAD

**Issue by gpeal** [airbnb/lottie-android#291]

**Comment by gpeal** [comment]
setMinAndMax* are sufficient for now.

**Comment by utkarshGithub** [comment]
please in detail how to use it

**Comment by gpeal** [comment]
@utkarshGithub http://airbnb.io/lottie/#/android?id=performance

**Comment by gpeal** [comment]
@utkarshGithub http://airbnb.io/lottie/#/android?id=looping plus you can read the documentation for each of the functions in Android Studio.

**Comment by kritikalST** [comment]
Hello @gpeal, I was more into how to chain animations like indefinitely play a set of animations, I saw in other responses that animation listener is used to accomplish this but wanted to confirm is there's another approach.

**Comment by gpeal** [comment]
@kritikalST That's your best bet

**Comment by voghDev** [comment]
Hello! Have you noticed a little "blink" or "flash" when you switch from one animation to the other? I'm experiencing a non-clean animation transition. This is my code:

```
      animationView.addAnimatorListener(animatorListener)
      animationView.setAnimation(animation)
      animationView.playAnimation()
```
Then in the AnimatorListener:
```
private val animatorListener = object : Animator.AnimatorListener {
    override fun onAnimationRepeat(animator: Animator?) {
    }

    override fun onAnimationEnd(animator: Animator?) {
      if (nextAnimation != null) {
        animationView.setAnimation(nextAnimation)
        animationView.playAnimation()
        nextAnimation = null
      }
    }

    override fun onAnimationCancel(animator: Animator?) {
    }

    override fun onAnimationStart(animator: Animator?) {
    }
  }
```
Is there something I'm doing wrong? could someone paste a code snippet for cleanly transitioning from one animation to another? 

Thanks in advance!
