### ISSUE TITLE
Open image loading and cache module access permissions

### ISSUE THREAD

**Issue by imliujun** [airbnb/lottie-android#294]
Hope to be able to open the `ImageAssetBitmapManager` access, allowing developers to manage their own bitmap load and cache.
We have a lot of animation using the image to render, Lottie now on these images cache management is not open enough.
For example, an animation has 90 images, one of which requires dynamic processing, each time you start the animation need to modify this image, but the` ImageAssetBitmapManager.bitmaps` attribute is not allowed to access, can not modify the bitmap

**Comment by imliujun** [comment]
Hope Lottie can better support the image animation, in different platforms above the use of network download json and images can achieve the same ValueAnimator, greatly reducing the workload of the developer

**Comment by gpeal** [comment]
I've added the ability to update the bitmap. However, why do you need 90 images. Is it possible to use after effects shapes instead? That will be much more efficient.
