### ISSUE TITLE
scale on api 16-17

### ISSUE THREAD

**Issue by shweps** [airbnb/lottie-android#299]
Hi,
i'm an Android developer using your 'Lottie' library & i'm facing a strange issue:
when using lottie on several old devices running Android API level 16/17 sutch as HTC one, Xperia Z etc. the animation seems to be a lot more densed / distorted than the same animation when used on devices with Higher API level (18+)
i have tried playing a bit with the scaleType & adjustViewBounds parameters & didnt see much change in behavior. 

here's a snippet of my code:

<com.airbnb.lottie.LottieAnimationView
                    android:id="@+id/animation_view_in"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:adjustViewBounds="true"
                    app:lottie_autoPlay="false"
                    android:scaleType="fitXY"
                    app:lottie_fileName="Anim_01_fordev 2.json" />

i would appreciate your response regarding this issue.
Thank you.

**Comment by gpeal** [comment]
@shweps Try removing scaleType and adjustViewBounds and give the view a fixed width and height

**Comment by gpeal** [comment]
@shweps Do you still have an issue?

**Comment by gpeal** [comment]
Feel free to reopen this if it's still an issue
