### ISSUE TITLE
No animation on HTC m8

### ISSUE THREAD

**Issue by brianchu** [airbnb/lottie-android#300]
No animation appear in HTC m8 (4.4.2). It pretty much just stay in the first 'frame'.
The only animated I saw is running Animated App Tutorial and the Lottie animated a little bit (but not completely).

Version: master

Also, running the app from Playstore (2.0.0-rc1) result in following crash:

E/AndroidRuntime( 9203): FATAL EXCEPTION: main
E/AndroidRuntime( 9203): Process: com.airbnb.lottie, PID: 9203
E/AndroidRuntime( 9203): android.view.InflateException: Binary XML file line #100: Error inflating class ImageButton
E/AndroidRuntime( 9203): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
E/AndroidRuntime( 9203): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
E/AndroidRuntime( 9203): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
E/AndroidRuntime( 9203): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/AndroidRuntime( 9203): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/AndroidRuntime( 9203): 	at com.airbnb.lottie.samples.AnimationFragment.onCreateView(AnimationFragment.java:106)
E/AndroidRuntime( 9203): 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
E/AndroidRuntime( 9203): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
E/AndroidRuntime( 9203): 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
E/AndroidRuntime( 9203): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
E/AndroidRuntime( 9203): 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
E/AndroidRuntime( 9203): 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
E/AndroidRuntime( 9203): 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
E/AndroidRuntime( 9203): 	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
E/AndroidRuntime( 9203): 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
E/AndroidRuntime( 9203): 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
E/AndroidRuntime( 9203): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 9203): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 9203): 	at android.os.Looper.loop(Looper.java:157)
E/AndroidRuntime( 9203): 	at android.app.ActivityThread.main(ActivityThread.java:5872)
E/AndroidRuntime( 9203): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 9203): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 9203): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:852)
E/AndroidRuntime( 9203): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:668)
E/AndroidRuntime( 9203): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 9203): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_invert.xml from drawable resource ID #0x7f02005f
E/AndroidRuntime( 9203): 	at android.content.res.Resources.loadDrawable(Resources.java:2134)
E/AndroidRuntime( 9203): 	at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
E/AndroidRuntime( 9203): 	at android.widget.ImageView.<init>(ImageView.java:129)
E/AndroidRuntime( 9203): 	at android.widget.ImageButton.<init>(ImageButton.java:87)
E/AndroidRuntime( 9203): 	at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:60)
E/AndroidRuntime( 9203): 	at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:56)
E/AndroidRuntime( 9203): 	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:118)
E/AndroidRuntime( 9203): 	at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1029)
E/AndroidRuntime( 9203): 	at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1087)
E/AndroidRuntime( 9203): 	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
E/AndroidRuntime( 9203): 	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:172)
E/AndroidRuntime( 9203): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
E/AndroidRuntime( 9203): 	... 24 more
E/AndroidRuntime( 9203): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_invert_black.xml from drawable resource ID #0x7f020060
E/AndroidRuntime( 9203): 	at android.content.res.Resources.loadDrawable(Resources.java:2134)
E/AndroidRuntime( 9203): 	at android.content.res.Resources.getDrawable(Resources.java:711)
E/AndroidRuntime( 9203): 	at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:176)
E/AndroidRuntime( 9203): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:937)
E/AndroidRuntime( 9203): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
E/AndroidRuntime( 9203): 	at android.content.res.Resources.loadDrawable(Resources.java:2130)
E/AndroidRuntime( 9203): 	... 35 more
E/AndroidRuntime( 9203): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
E/AndroidRuntime( 9203): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
E/AndroidRuntime( 9203): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
E/AndroidRuntime( 9203): 	at android.content.res.Resources.loadDrawable(Resources.java:2130)
E/AndroidRuntime( 9203): 	... 40 more
E/ActivityManager(  958): App crashed! Process: com.airbnb.lottie

**Comment by gpeal** [comment]
@brianchu Can you attach a video of what the animation looks like? They render fine on JB/KK emulators

**Comment by brianchu** [comment]
@gpeal https://youtu.be/08E6Lo6tJcw Yes, emulator is okay, but the device is not.

**Comment by gpeal** [comment]
@brianchu You have system animations disabled don't you :)

**Comment by brianchu** [comment]
@gpeal It is correct! The animation is back once I enable the system animation.
My understanding of _system_ animation is for ... system animation (e.g. activity animation, dialog animation), why a library will honor that? Can we turn this behaviour off?

**Comment by gpeal** [comment]
@brianchu Lottie uses ValueAnimator under the hood. Those settings affect that. If you want to get around that, you can create your own animator that sets the progress from 0 to 1.
