### ISSUE TITLE
It show error page when I use Lottie.

### ISSUE THREAD

**Issue by wdmxzf** [airbnb/lottie-android#301]
It is found in my page of fragment, the picture is 
![error](https://cloud.githubusercontent.com/assets/19531732/26136816/c08775e2-3af0-11e7-938b-7189a01543cf.png)

**Comment by gpeal** [comment]
@wdmxzf Try making your animation smaller? The After Effects composition size gets converted from pixels to dps. See what happens when you make your composition like 200px wide max

**Comment by wdmxzf** [comment]
This is my layout 
`<com.airbnb.lottie.LottieAnimationView
                android:id="@+id/animation_view"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:lottie_fileName="measure_animation.json"
                app:lottie_loop="true"
                app:lottie_autoPlay="true"
                android:layout_centerHorizontal="true"
                android:layout_centerVertical="true"
                android:scaleType="centerCrop"/>`
And the bug is happening in OPPO R831S , Galaxy Note II(GT-N7100) and so on.
<img width="783" alt="2017-05-20 6 43 47" src="https://cloud.githubusercontent.com/assets/19531732/26275133/673122ce-3d8c-11e7-924d-44ff9cf1ef41.png">
Above are the device.

**Comment by gpeal** [comment]
@wdmxzf I understand that. There are limitations in the Android drawing framework that limits the size of the canvas that can be used for a matte. In this case, it appears as if the composition is drawing larger than the screen and being scaled down but everything that was originally larger than the screen is getting clipped. Try making your AE comp smaller or using the setScale method on LottieAnimationView

**Comment by wdmxzf** [comment]
Thank you for your help.
