### ISSUE TITLE
Android crash with Lottie

### ISSUE THREAD

**Issue by joemartins** [airbnb/lottie-android#303]
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xb9a462c0 in tid 9361 (RenderThread)

A Native crash happens.

**Comment by 1zaman** [comment]
@joemartins: Was this resolved? We're having similar issues on our app after deploying a new Lottie animation.

**Comment by joemartins** [comment]
Guess it did. It stopped happening.

**Comment by pranishres** [comment]
How has this issue been resolved? I am facing the same issue now.

**Comment by joemartins** [comment]
I remember updating AE and reinstalling Bodymovin. I don't know if that resolved the issue, but it stopped happening.
