### ISSUE TITLE
Inconsistent source and result animations

### ISSUE THREAD

**Issue by ming13** [airbnb/lottie-android#304]
We have a couple of animations that do not look consistent with the source material. All the things can be found [on the Google Drive](https://drive.google.com/drive/folders/0B7UjLPFHU6NFdGhJWmlCLU5TclU), including before and after videos, JSON files and source After Effects file.

* Square. It was supposed to be bouncy. We used a plugin called Motion 2 to achieve the desired effect to check if it will translate well into JSON. I guess it is not supported? Can we somehow transform it into native AE thingies?
* Bubble. There is easing at the source material, but not in the resulting animation, even the Bezier Interpolation was used it is marked as supported as it seems.

**Comment by gpeal** [comment]
@ming13 Sorry, Lottie doesn't support Motion 2 or expressions. You should be able to achieve these effects with normal time interpolations though
