### ISSUE TITLE
Lottie Drawable Scale is overridden with new composition

### ISSUE THREAD

**Issue by howard0020** [airbnb/lottie-android#305]
Setting the scale anytime before `OnCompositionLoadedListener` fire doesn't do anything.
Ideally, `LottieDrawable` should keep the scale that was set.

It will be nice if Scale can be set via xml with `LottieAnimationView`.

https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java#L157

**Comment by gpeal** [comment]
@howard0020 I can add this but ideally, if your scale is know ahead of time, you should just request a smaller composition from your designer.

**Comment by howard0020** [comment]
@gpeal thanks for the reply, sometimes I want to use the same animation smaller in different places.
