### ISSUE TITLE
BUG: Inaccurate custom ease

### ISSUE THREAD

**Issue by erikalutz** [airbnb/lottie-android#308]
@gpeal I've attached the file that's not accurately displaying its custom eases. There is an ease being displayed, but it's not accurate to what's been designed in the After Effects file.

The custom eases are on layers 'Icon - Mountain 1 Base' and 'Icon - Mountain 2 Base' on frame 25, scale transformation. The handles have been pulled out in the curve editor to give it a longer ease out.

[CustomEaseBug.aep.zip](https://github.com/airbnb/lottie-android/files/1026620/CustomEaseBug.aep.zip)

**Comment by gpeal** [comment]
@erikalutz it actually appears as if there may be an issue with bodymovin here. Filed: https://github.com/bodymovin/bodymovin/issues/444

**Comment by gpeal** [comment]
@erikalutz Can you try your animation with the a version of bodymovin pos v4.6.11?

**Comment by gpeal** [comment]
This was fixed in bodymovin.
