### ISSUE TITLE
needs >= 2 number of colors

### ISSUE THREAD

**Issue by bijuC1983** [airbnb/lottie-android#309]
Hi,
    I have received 4 json files from my designer after export from After Effects. One of them works fine but get the following Exception with others:
"java.lang.IllegalArgumentException: needs >= 2 number of colors"
Any help towards resolving this issue?
Thanks in Advance

**Comment by gpeal** [comment]
Can you post the full stack and the aep file?

**Comment by gpeal** [comment]
@bijuC1983

**Comment by bijuC1983** [comment]
@gpeal Sure. I shall get aep files from the design team on Monday & post it here along with the trace.

**Comment by gpeal** [comment]
@bijuC1983 one potential thing is that if there are gradients, you have to save your composition before bodymovin will pick up the change.

**Comment by bijuC1983** [comment]
@gpeal You may find the aep file & the jsons here http://bit.ly/2rjaS1b
The message I received from the design team is that there are no gradients, but only flat colors.

**Comment by gpeal** [comment]
@bijuC1983 A few things stand out already.
1) Right click any illustrator layers and convert them to shape layers. This will allow Lottie to render them as shapes instead of exporting them as pngs. For reference, you should never need lots of pngs for a Lottie animation.
2) Lottie doesn't yet support text so you'll want to remove those layers.
3) Lottie doesn't support time remaping (yet)

The issue you're facing is on the gradient stroke. For now you can remove that but I'll look in to it more.

**Comment by quanquanams** [comment]
@gpeal I have the same problem! But my designer promise no text! And no png!
And I don't know what is time remaping

**Comment by simensqpg** [comment]
Same problem came up to me, and here is my json file, any help will be appreciated.It blocked me for a long time.
[data.json.zip](https://github.com/airbnb/lottie-android/files/1141827/data.json.zip)

**Comment by therealsalih** [comment]
@simensqpg can you post your AE file as well?

**Comment by quanquanams** [comment]
@simensqpg 
I found the problem
Lottie-android don't have 

Currently Unsupported After Effects Features

I see it in lottie-ios

**Comment by gpeal** [comment]
@quanquanams I need to update that. Lottie does support gradients. There is just a bug with a certain gradient configuration that I have to look in to

**Comment by quanquanams** [comment]
@gpeal Did you fix this bug already?Or When?  
I really need it! Or my designer have to give me a many png

**Comment by CarlosVimos** [comment]
@gpeal Hello, how is going with this issue? I have the same problems as above. Can we expect this in this month? Regards

**Comment by webyjulo** [comment]
Hi, I'm still facing this issue. Wish anyone could help me to fix the issue.

[data.json (1).zip](https://github.com/airbnb/lottie-android/files/1406508/data.json.1.zip)

**Comment by sumit-anantwar** [comment]
This issue still exists

**Comment by CaoThien96** [comment]
This issue still exists
