### ISSUE TITLE
Pause/Resume restarts the animation on Samsung Galaxy S4/Note 3 5.0.1

### ISSUE THREAD

**Issue by kakai248** [airbnb/lottie-android#310]
Hello,

I couldn't find any issue regarding this.

Pausing and then resuming an animation on one of the following devices makes the animation restart:
- Samsung Galaxy S4 5.0.1
- Samsung Note 3 5.0.1

It works fine on this device:
- Samsung Galaxy J3 (2016) 5.1.1
- And all the other devices I've tested

You can see this behavior on the sample app (using Lottie 2.0.0-rc1). I mainly tested with the `EmptyState.json`.

From what I've seen, it seems that the ValueAnimator emits a progress `0.0f` upon resuming. I couldn't find any bug related to this on Google.

Thank you.

**Comment by kakai248** [comment]
I can add some more information on this. I could also reproduce it on an LG G3.

Upon resuming, `playAnimation(true)` will be called (on LottieDrawable).
There we have the following code:
```
if (setStartTime) {
  animator.setCurrentPlayTime((long) (progress * animator.getDuration()));
}
animator.start();
```

Switching the order of these instructions would potentially fix the problem. However, the `AnimatorUpdateListener` is called with `0.0f` as soon as we call `animator.start()`, which happens before we set the current play time.

```
animator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
      @Override public void onAnimationUpdate(ValueAnimator animation) {
        if (systemAnimationsAreDisabled) {
          animator.cancel();
          setProgress(1f);
        } else {
      ----> setProgress((float) animation.getAnimatedValue());
        }
      }
    });
```

This will set the progress and when the `setCurrentPlayTime` finally runs, the progress will already be at `0.0f`.

In my app, I fixed the problem by saving the progress before calling resume and setting it myself.
```
    void resumeAnimation() {
        float progress = animationView.getProgress();
        animationView.resumeAnimation();

        ValueAnimator animator = getAnimator();
        if (animator != null) {
            animator.setCurrentPlayTime((long) (progress * animator.getDuration()));
        }
    }
```

This is not ideal as `getAnimator()` uses reflection.

**Comment by CCorrado** [comment]
We are seeing this issue on API 23 and below across all devices. Serious issue with this library, is there a better fix?

**Comment by gpeal** [comment]
@CCorrado Can you try with 2.2.1. There are a number of changes in 2.2.1 related to the way progress is handled.

**Comment by CCorrado** [comment]
Yes, we're compiling Lottie 2.2.1. 

To start the animation, we're running this: (Our animator is dependent on a Timer, which is where the totalStateSeconds variable is updated/initialized)

```
(LottieAnimationView) view;
view.setSpeed((BigDecimal.valueOf(SECONDS_IN_MINUTE_FLOAT)
        .divide(BigDecimal.valueOf(totalStateSeconds), 
                MathContext.DECIMAL128)).floatValue());
view.setProgress(totalStateSeconds);
view.playAnimation();
```

and noticing that when we run:

`(LottieAnimationView) view.pauseAnimation`

The Animation restarts and plays from 0 on APIs 23 and below instead of pausing in its current state. We've tested on emulators running 23, 22, and 19, and tested on a Samsung Galaxy S4 running API 21 (5.0.1). 

Our XML looks like this:

```
<com.airbnb.lottie.LottieAnimationView
            android:id="@+id/animation_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_gravity="center"
            android:layout_margin="10dp"
            android:background="@android:color/transparent"
            android:gravity="center"
            app:lottie_autoPlay="false"
            app:lottie_fileName="json_data/animation.json"
            app:lottie_loop="false"/>
```

To resume the animation after being in a paused state, we run this:

`if (!view.isAnimating()) {
            view.resumeAnimation();
        }`

I've tried playing with the different APIs, but this current setup works on API 24 and above. Not sure what could be causing it.

**Comment by CCorrado** [comment]
Update, we have figured out a workaround for the issue....

```
(LottieAnimationView) view;
view.setSpeed((BigDecimal.valueOf(SECONDS_IN_MINUTE_FLOAT)
        .divide(BigDecimal.valueOf(totalStateSeconds), 
                MathContext.DECIMAL128)).floatValue());
view.setProgress(totalStateSeconds);
view.playAnimation();
view.pauseAnimation();
view.resumeAnimation();
```

Definitely not ideal! but it works for us for now.

**Comment by gpeal** [comment]
I think this will fix your issue @CCorrado. It fixes some logic as well as the pre-23 issues you experienced. I tested this down to API 16.

**Comment by CCorrado** [comment]
Nice. I'll review it in a bit. Had a feeling something was off internally, Android APIs are such a pain. +1 for Kotlin

**Comment by gpeal** [comment]
@CCorrado I wish I could write the Lottie library itself in it :(

**Comment by CCorrado** [comment]
@gpeal is there a snapshot of 2.2.2 with those changes you made? The workaround start/pause/resume is pretty unreliable, although it significantly reduced the amount of times the issue occurs it still sometimes does happen. Just curious, we can wait for 2.2.2 to be released before compiling it

**Comment by gpeal** [comment]
@CCorrado @kakai248  2.2.3 is now out

**Comment by cooperkong** [comment]
Still happens on Samsung S5 6.0.1

**Comment by kevinbeauchamps7575** [comment]
I have the same issue on a Google Pixel 3, the animation restart itself with onResume
