### ISSUE TITLE
Bug while rendering shape layers 

### ISSUE THREAD

**Issue by ShaunShi** [airbnb/lottie-android#311]
Hi team,
Thank you very much for your great job, and I'm so glad that my team are able to try out lottie animations in native iOS app.
I am an interaction designer and my team is working on a Chinese travelling App called "TongCheng". When we were testing on lottie, we found some issues and may need your help.
This is a loading animation on AE. I mainly get it work by trimming path of shape layers. Then I used bodymovin to render into a json file, which I've sent to _**lottie@airbnb.com**_  together with aep file as email attachment . The email is with the same title.
But it's kinda not working correctly. Let me show you more details:
![image](https://cloud.githubusercontent.com/assets/28948997/26446081/403a6bc0-4175-11e7-8a93-cd33f367cbf5.png)
this is what we see on AE at 02:02.

![image](https://cloud.githubusercontent.com/assets/28948997/26446126/67b22a3a-4175-11e7-9d5c-43e394f85ddc.png)
and this  is what we see on bodymovin preview at 61/75(the very same frame on AE).

But after we coding the json file out on iOS, we got this odd shape at the same frame:
![image](https://cloud.githubusercontent.com/assets/28948997/26446265/e46cfdac-4175-11e7-8e1f-1e3789534f05.png)

And what's more, we also got some odd shapes at other frames:
![image](https://cloud.githubusercontent.com/assets/28948997/26446301/0e40e594-4176-11e7-83b4-19383fea395c.png)
![image](https://cloud.githubusercontent.com/assets/28948997/26446315/20097232-4176-11e7-8873-812127a0a21c.png)

I don't know how to get this issue fixed. 
Really looking forward to your kind reply.
Thank you very much.

**Comment by gpeal** [comment]
@ShaunShi Do you have an issue on Android or just iOS? If it's just iOS then please file an issue on lottie-ios

**Comment by ShaunShi** [comment]
Currently we just tried lottie on iOS.  Will try on Android a little bit later. Sorry I didn't notice it's android issue board.
