### ISSUE TITLE
How to restore animation to first frame

### ISSUE THREAD

**Issue by shuixingge** [airbnb/lottie-android#312]
Before opening a new issue:

* Look through open and existing issues for duplicates.
* Apply an appropriate label.

If this is a bug:
* Attach your After Effects file. If you do not feel comfortable posting it on github, email 
it to lottie@airbnb.com. There are 500 ways to do everything in After Effects that achieves the 
same visual effect so it is nearly impossible to reproduce your issue without the original After 
Effects file. Github doesn't allow you to attach a json or aep file directly so compress it and attach it as a zip file.

If this is a feature request:
* Explain what feature you would like and why you need it. There are usually After Effects 
workarounds that we can provide in the meantime that achieve the same effect.
* What version of Lottie did you test this on? Check the readme for the latest version and makes sure it hasn't been resolved.

**Comment by gpeal** [comment]
@shuixingge Call `setProgress(0)`

**Comment by iuliuvisovan** [comment]
For me there's not `setProgress` function on `LottieView`. 

The one that worked for me was `reset`.


```
<LottieView ref={x => this.animation = x} />

this.animation.reset();
```
