### ISSUE TITLE
How to reset a lottie a animtion 

### ISSUE THREAD

**Issue by shuixingge** [airbnb/lottie-android#314]
when  i called  setComposition ,the LottieAnimationView will display the first frame of the animation,but when the animation finished, i can not reset the animation to first frame except i call animation.reverse(),but this will lead to the animation reverse play.
so ,is there some way to reset the animation to the first frame

**Comment by howard0020** [comment]
Will this work for you? set progress to 0 should show you the first frame.

```
  animationView.addAnimatorListener(new AnimatorListenerAdapter() {
      @Override public void onAnimationEnd(Animator animation) {
        animationView.setProgress(0);
      }
    });
```

**Comment by gpeal** [comment]
@shuixingge if @howard0020's suggestion doesn't work for you, reopen this.

**Comment by samy-baili** [comment]
Doesn't work for me

**Comment by gpeal** [comment]
@samy-baili What version of Lottie? And can you post your code?

**Comment by zijing07** [comment]
Not working for me either. version 2.5.4. Code:

```
            Completable.fromEmitter {
                animationView.removeAllAnimatorListeners()
                animationView.addAnimatorListener(object : Animator.AnimatorListener {
                    override fun onAnimationRepeat(animation: Animator?) {
                    }

                    override fun onAnimationCancel(animation: Animator?) {
                    }

                    override fun onAnimationStart(animation: Animator?) {
                    }

                    override fun onAnimationEnd(animation: Animator?) {
                        it.onCompleted()
                    }
                })
                animationView.playAnimation()
            })
```

When I reach the code for the second time, the `Completable` directly emits `onComplete`.

**Comment by iuliuvisovan** [comment]
For me there's not `setProgress` function on `LottieView`. 

The one that worked for me was `reset`.


```
<LottieView ref={x => this.animation = x} />

this.animation.reset();
```

**Comment by gpeal** [comment]
@iuliuvisovan You're using React Native. This thread is for Android.

**Comment by iuliuvisovan** [comment]
Oh well. This is awkward.

I can just hope other RN devs will be as distracted as I was and find this helpful. 💃

**Comment by ganeshpadhayay** [comment]
Why are you marking these as closed when you haven't posted the solution yet??? how to reset animation view so that a different animation can be played in the same container???? don't mark it closed till it is not closed properly

**Comment by PrinceVergil** [comment]
i am having same problem how to set first frame when animation is ended??

**Comment by gpeal** [comment]
@ganeshpadhayay @PrinceVergil https://github.com/airbnb/lottie-android/issues/314#issuecomment-304468565

**Comment by Damercy** [comment]
I don't know if this helps but I set my animation frame to 0 (initial) & it's as good as resetting.
```kotlin
 myLottieAnimationView.frame = 0
```

**Comment by programmkia** [comment]
> 

This is nice Thx

**Comment by LegacyLive88** [comment]
This is the only thing that works consistently for me:
animation.setSpeed(-1); 
animation.playSegments([1,0], true);
animation.setSpeed(1);

You can try this too though:
animation.goToAndStop(0, true);
