### ISSUE TITLE
JUnit asserts in production classes

### ISSUE THREAD

**Issue by RobertLK** [airbnb/lottie-android#319]
Two classes in lottie library include JUnit asserts:
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/ImageAssetBitmapManager.java
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/CanvasPool.java

Mixing test asserts and production code is bad practice (https://stackoverflow.com/questions/17620520/is-it-okay-to-use-junit-assert-api-in-java-production-code), and can lead to copies of junit classes being packaged into APKs using lottie. Should replace these with more explicit Exceptions.

**Comment by gpeal** [comment]
Fixed by https://github.com/airbnb/lottie-android/commit/c1fdae0b7a962ff5e0b936274ef5559eef47f9e7
