### ISSUE TITLE
Animation timing drifts for a long animation (233s or more)

### ISSUE THREAD

**Issue by creynaud** [airbnb/lottie-android#323]
I am trying to play long animations with lottie 2.0.0-rc2.
There is a drift of 7s, so the animation ends after 240s instead of 233s.

Here the json file that I use:
[lottie-drift.zip](https://github.com/airbnb/lottie-android/files/1048318/lottie-drift.zip)

I used the lottie sample, and replaced the "WeAccept" demo by my json file and my images. I also added some System.currentTimeMillis() logs in the AnimatorListener onAnimationStart and onAnimationEnd methods to measure the drift.

Note that I can reproduce the issue with other json files that are similar (images animation, with a duration of several minutes).

Let me know if you need more information.

**Comment by sjenasears** [comment]
Hi creynaud ,

How you changed Lottie json file.
Beacuse it is a huge file.
I was trying to change.
Could you please help me
