### ISSUE TITLE
The last few frames are missing for file https://www.lottiefiles.com/296-react-logo

### ISSUE THREAD

**Issue by brianchu** [airbnb/lottie-android#324]
Using the demo app Animated Viewer and point to use https://www.lottiefiles.com/296-react-logo

Instead see: https://youtu.be/rAa6_Fufqag
Observed: The last frame few frame is missing something.
Expected: The animation finish nicely.

* Attach your After Effects file: AE file download from https://www.lottiefiles.com/296-react-logo

**Comment by gpeal** [comment]
I noticed this too. I'll take a look.

**Comment by reallynattu** [comment]
It works well on iOS. Yet to test it on Android. Nothing special just trim paths and stroke width used on the animation.

**Comment by gpeal** [comment]
@reallynattu there is a bug at the end with some trim path math

**Comment by brianchu** [comment]
Tested on 2.0.0. Works as expected.
