### ISSUE TITLE
A little delay when change json file

### ISSUE THREAD

**Issue by SwayChen** [airbnb/lottie-android#325]
It may be a 0.2s~0.3s delay in Nexus 5. Please check it. The size of json is about 60KB

My code:
```java
animView.clearAnimation();
animView.setAnimation(animJsonName);
animView.loop(true);
animView.playAnimation();
```

**Comment by ymyronov** [comment]
I have the same problem. Generally we need a way to seamlessly change animation "on the fly". Maybe some pre-caching/pre-loading?

**Comment by gpeal** [comment]
You can:
a) Load a LottieComposition and set the composition on the LottieAnimationView.
b) Load a LottieDrawable and set the drawable on the LottieAnimationView. LottieDrawable acts like any other drawable and LottieAnimationView acts like any other ImageView.
c) Set the composition with a CacheStrategy if you set it multiple times (but there will be a flicker the first time if you do this).
