### ISSUE TITLE
Animation is cut off when LottieAnimationView is not big enough

### ISSUE THREAD

**Issue by dfpalomar** [airbnb/lottie-android#326]
Hi guys.

At work the UI/UX team has designed an animation that works perfectly fine in iOS but not in Android. When the LottieAnimationView is big enough the animation work perfectly fine but when that widget is small the animation is cut off. Below the videos of the animation:

**Animation working as expected (the view size has to be big)**

![gif_working](https://cloud.githubusercontent.com/assets/5319517/26794505/cfe575d8-4a19-11e7-9ba8-63c48e3800fb.gif)

**Animation not working as expected (the view size is small)**

![gif_not_working](https://cloud.githubusercontent.com/assets/5319517/26794528/e26a5a84-4a19-11e7-8583-c6ea61f04897.gif)
_(the blink is not an issue, it's just that I wasn't very accurate when I cut the video XD)_

In the animation our team has used opacity, scale, position and a mask and there are no added effects. I have tried using different scale types for the LottieAnimationView but with no luck. 

I have published an [Android app](https://github.com/dfpalomar/LottieAnimationIssue) with the source files including the JSON file and the images.

Any help will be very much appreciated :)

**Comment by gpeal** [comment]
@dfpalomar Lottie can't render a mask or matter larger than view for performance reasons. Try a) making the composition smaller and using scaleType=centerCrop or playing around with setScale on the LottieAnimationView.

**Comment by dfpalomar** [comment]
@gpeal thanks for your reply. We're gonna try what you suggest 👍

**Comment by dfpalomar** [comment]
Thanks for the solution guys, it works! 👍

**Comment by muzir** [comment]
Thanks guys, @elliottetzkorn's solution in code solve my issue

```
<com.airbnb.lottie.LottieAnimationView
            android:id="@+id/result_extra_check_animation"
            android:layout_width="200dp"
            android:layout_height="200dp"
            android:layout_below="@id/close_button"
            android:scaleType="centerCrop"
            app:lottie_scale="0.1"
            android:layout_centerHorizontal="true"
            android:layout_marginTop="50dp"
            app:lottie_autoPlay="true"
            app:lottie_fileName="lottie/anim-extra-check.json" />
```
