### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by ltlovezh** [airbnb/lottie-android#327]
GC Path: 
com.tencent.qgame.presentation.activity.XXXXActivity@a69534c8
    |-mBase, android.support.v7.widget.TintContextWrapper@a6a27a78
        |-mContext, com.airbnb.lottie.LottieAnimationView@a6525008
            |-this$0, com.airbnb.lottie.LottieAnimationView$2@a688b320
                |-loadedListener, com.airbnb.lottie.FileCompositionLoader@a688c358
                    |-this$0, android.os.AsyncTask$3@a688c3b8
                        |-, java.lang.Thread(AsyncTask #1)@a688c430

because AsyncTask lead to Memory Leak!!!

**Comment by gpeal** [comment]
@ltlovezh Can you attach a sample project that repros this?

**Comment by gpeal** [comment]
@ltlovezh bump
