### ISSUE TITLE
Whether can Lottie run in Xamarin ?

### ISSUE THREAD

**Issue by vulcanlee** [airbnb/lottie-android#33]
I am a Xamarin programmer and whether can Lottie run in Xamarin ?

**Comment by martijn00** [comment]
I've released bindings for Xamarin Android for Lottie! https://github.com/martijn00/LottieXamarin

It's also available on Nuget: https://www.nuget.org/packages/Com.Airbnb.Android.Lottie/

**Comment by gpeal** [comment]
Thanks @martijn00! I'll add this and the NativeScript bindings to the README

**Comment by martijn00** [comment]
It's now also available for Xamarin iOS: https://www.nuget.org/packages/Com.Airbnb.iOS.Lottie/

The source is available here: https://github.com/martijn00/LottieXamarin

**Comment by modplug** [comment]
It is now also available for Xamarin Forms: (https://github.com/martijn00/LottieXamarin)

**Comment by starkovss** [comment]
Hi Martin,
can you tell me what why this code is not working
My project created using **XAMARIN.FORMS**

I used animation file: lottielogo1.json
**This file added that file to all 3 projects :** 
**(Portable)**/resources/lottielogo1.json
**(Droid)**/Assets/lottielogo1.json
**(iOS)**/Resources/lottielogo1.json

Code from **(Portable)** project:
```   JAVA
public partial class PageIntro : ContentPage
    {
        public PageIntro()
        {
            InitializeComponent();

            // CREATE ANIMATION LOTTIE VIEW
            AnimationView animation = new Lottie.Forms.AnimationView()
            {
                // Initial parameters
                Animation = "lottielogo1.json",
                Loop = true,
                AutoPlay = true,
                WidthRequest = 400,
                HeightRequest = 400,
                VerticalOptions = LayoutOptions.FillAndExpand,
                HorizontalOptions = LayoutOptions.FillAndExpand
            };

            // START PLAYING
            animation.IsEnabled = true;
            animation.IsVisible = true;
            animation.Play();

            // ADDING ANIMATION TO THE VIEW
            CONTENT_LOCAL.Children.Add(animation);

            // CHECKING BY TAP : Playing or not
            var tap = new TapGestureRecognizer
            {
                Command = new Command(() =>
                {
                    if (animation.IsPlaying)
                    {
                        DisplayAlert("Animation", "is Playing : Progress is " + animation.Progress, "Close");

                    }
                    else
                    {
                        DisplayAlert("Animation", "is NOT Playing", "Close");
                    }
                } ),
                NumberOfTapsRequired = 1
            };
            animation.GestureRecognizers.Add(tap);
        }
```

So as result there is nothing happens. 
I tested on Android and iOS. Just blank screen.
By TAPing , I'm getting IS NOT PLAYING message.
Can you please advice what do I miss in that code.
Thank you.

**Comment by gpeal** [comment]
@starkovss You may have the most luck filing an issue directly on that repo

**Comment by starkovss** [comment]
@gpeal , yup you are right. I already post it to FORMS repo. I noticed that I'm on Android branch only after the posting..

**Comment by lucasrloliveira** [comment]
Hey, I´m having a problem trying to use Lottie json animation within a carousel view, I intent to change the animation´s reference when swiping my carousel, and I want to start the new animation at this very moment, but when I try to set AutoPlay to false and IsPlaying to true when swiping, my animations weren´t able to start, if I set AutoPlay to true, the animations will start independently from my swipe actions, this if I leave Loop to true, does anyone have any sugestions on how to start it at the changeIndexEvent of my carouselView?

**Comment by gpeal** [comment]
@lucasrloliveira Can you lost this on lottie-xamarin? I don't maintain the xamarin port.
