### ISSUE TITLE
You must set an images folder before loading an image.IllegalStateException

### ISSUE THREAD

**Issue by Bekakk** [airbnb/lottie-android#331]
Hello
I'm using this repo and have one problem.
I generated .json  file with images from Adobe After Effect successfully.I inserted my json file in assets folder and images(5 images) in assets/Image.WeAccept folder.This is a part in my code
`  ```
`<FrameLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:paddingBottom="32dp"
        android:background="@color/colorPrimary">
        <com.airbnb.lottie.LottieAnimationView
            android:id="@+id/animation_view"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            app:lottie_fileName="Test.json"
            app:lottie_loop="true" />
    </FrameLayout>``

But when i run my app i have  IllegalStateException.
More about log message:

> java.lang.IllegalStateException: You must set an images folder before loading an image. Set it with LottieComposition#setImagesFolder or LottieDrawable#setImagesFolder

How i can solve this problem? 
Thanks

                                                      

```

**Comment by gpeal** [comment]
@Bekakk if you're trying to test it in the sample app, add your animation to [this map](https://github.com/airbnb/lottie-android/blob/master/LottieSample/src/main/java/com/airbnb/lottie/samples/AnimationFragment.java#L82)

**Comment by jpboro** [comment]
Found out that removing and reloading Assets folder removed the error

**Comment by fang1994042128** [comment]
Hello

**Comment by gpeal** [comment]
@fang1994042128 http://airbnb.io/lottie/android/images.html

**Comment by patelmanthan777** [comment]
> Hello
> I used version 2.70。The same problem has occurred。
> I used image resources。
> mLottieAnimationView.setImageAssetsFolder("images");
> mLottieAnimationView.setAnimation("data.json");
> 
> You must set an images folder before loading an image. Set it with LottieComposition#setImagesFolder or LottieDrawable#setImagesFolder
> com.airbnb.lottie.manager.ImageAssetManager.bitmapForId(ImageAssetManager.java:107)

Thank you so much @fang1994042128 . It is very helpful.

**Comment by baallalAbderrahim** [comment]
Hello , 
or you can do it directly in the layout  file : 
            app:lottie_imageAssetsFolder="images"
regards
