### ISSUE TITLE
[Feature request] initialize a LottieAnimationView with a remote url directly

### ISSUE THREAD

**Issue by haoranuber** [airbnb/lottie-android#338]
Would like to have a way to initialize a LottieAnimationView with a remote url directly, which is available in lottie-ios as `initWithContentsOfURL`.

In the sample app, `private void loadUrl(String url) { ... }` loads the json file and passes the parsed json string to the `private void loadJsonString(String jsonString) { ... }` method. Why not put that logic inside lottie?

**Comment by gpeal** [comment]
@haoranuber I don't want to add dependencies on third party libraries. Most apps have their own and it would be ideal for you to leverage that to have better handling for lifecycles and caching.

**Comment by RishabhTayal** [comment]
Why can't we have this feature? The lottie-ios library has this? It would be nice to have the parallel features in both platforms. 

https://github.com/airbnb/lottie-ios/blob/master/lottie-ios/Classes/PublicHeaders/LOTAnimationView.h#L36

**Comment by gpeal** [comment]
@RishabhTayal iOS has better networking support in the platform. Android's is pretty crap and almost every app uses okhttp or some other library. I've intentionally not tried to build something directly on the Android APIs so people would use their own networking stack.

**Comment by RishabhTayal** [comment]
I understand Android development's pain. Hopefully you will have a better networking support from Android API in future.

**Comment by gpeal** [comment]
@RishabhTayal This is intentional and there are many great open source alternatives. There are examples of loading from the network [here](https://github.com/airbnb/lottie-android/blob/master/LottieSample/src/main/kotlin/com/airbnb/lottie/samples/AnimationFragment.kt#L377) though.

**Comment by AndroidDeveloperLB** [comment]
@gpeal Link is broken. 
Can you please show how it's done in the sample perhaps?
Is it at least possible to set it to load from a file on the file system ? Meaning that I download the json file, and then view it?

**Comment by AndroidDeveloperLB** [comment]
OK never mind. Basic usage can be as such:

        object : Thread() {
            override fun run() {
                super.run()
                val url = "https://www.lottiefiles.com/download/478"
                val streamForUrl = StreamUtil.getInputStreamFromUrl(url)
                val reader = JsonReader(BufferedReader(InputStreamReader(streamForUrl)))
                Handler(Looper.getMainLooper()).post {
                    animationView.setAnimation(reader )
                }
            }
        }.start()


    public static InputStream getInputStreamFromUrl(final String urlStr) throws IOException {
        if (TextUtils.isEmpty(urlStr))
            return null;
        InputStream input = null;
        HttpURLConnection connection = null;
        final URL url = new URL(urlStr);
        connection = (HttpURLConnection) url.openConnection();
        connection.setConnectTimeout(CONNECTION_TIMEOUT_IN_MILLIS);
        connection.setReadTimeout(CONNECTION_TIMEOUT_IN_MILLIS);
        // See the http://stackoverflow.com/questions/15411213/android-httpsurlconnection-eofexception for
        // explanations
        connection.setRequestProperty("Connection", "close");
        // this is an attempt to overcome an error of "FileNotFoundException"
        connection.setDoOutput(false);
        connection.connect();
        // expect HTTP 200 OK, so we don't mistakenly save error report
        // instead of the file
        if (connection.getResponseCode() != HttpURLConnection.HTTP_OK)
            return null;
        // download the file
        input = connection.getInputStream();
        return input;
    }

**Comment by rajivrnair** [comment]
In case anyone's still looking for how to do this (as I was), just do:
```
lottieView.setAnimationFromUrl("https://somsite.com/assets/file.json")
```
Thanks for all the effort @gpeal!

**Comment by AndroidDeveloperLB** [comment]
@rajivrnair When was it added? Where did you find about it?

**Comment by rajivrnair** [comment]
> @rajivrnair When was it added? Where did you find about it?
> Are you writing about what I wrote? Or something official?

I just saw this commit: https://github.com/airbnb/lottie-android/commit/9d233a0f9ce099c2bc0f44116a48e330befa01b2

**Comment by AndroidDeveloperLB** [comment]
Does it work well? Can we safely use it?

**Comment by rajivrnair** [comment]
Yep. Been using it for a couple of days and no issues so far.

**Comment by AndroidDeveloperLB** [comment]
Thank you. Good to know.
