### ISSUE TITLE
Change Animation Text Dynamically [Android/iOS]

### ISSUE THREAD

**Issue by adityamore** [airbnb/lottie-android#340]
Hi,

We were trying use Lottie in our App (both Android and iOS) to create this animated map marker. I wanted to know if the text can be dynamically changed at runtime using Lottie as each Map Marker will have different data.

![marker](https://user-images.githubusercontent.com/6376679/27171926-f3716e94-51d0-11e7-8437-52ac4e7e727a.gif)

In case there is any method that can be used in complement to Lottie for this purpose, that would be fine too. 

Would appreciate any help in this regards!

(Also attached the original After Effects file)

[Map_Pointer.zip](https://github.com/airbnb/lottie-android/files/1077003/Map_Pointer.zip)

**Comment by gpeal** [comment]
I'm currently working on #173 to add support for text and probably dynamic text. However, it's worth noting that it may be difficult to have the pin respond to different size text since your shape may not know the size of the text at runtime.
