### ISSUE TITLE
Performance with multiple AnimationViews in ViewPager

### ISSUE THREAD

**Issue by TheRishka** [airbnb/lottie-android#341]
Hi! To be short:
How should I implement such feature, as multiple LottieAnimationViews in fragments in ViewPagers.
Right now, it has FPS-drop when there are multiple fragments with LottieAnimationView attached.
I'm trying to achieve nearly same behaviour as in Example2.gif, but with fully separated pages (fragments) with fully separated AnimationViews.

I've tried to enable experimental hardware acceleration - no result. I've also tried to play with scale - no acceptable result.

How should I use Lottie in this case? Accept the performance drop or there is a solution?

**Comment by gpeal** [comment]
@TheRishka How is the performance of your animation on its own? Are there masks and mattes?
If your animation is in a ViewPager, you can make sure it's not playing until it's visible too so you aren't trying to animate them at the same time.

**Comment by jonasdoliveira** [comment]
@TheRishka, one approach is too set limit of pages to be loaded for ViewPager to 1.

https://developer.android.com/reference/android/support/v4/view/ViewPager.html#setOffscreenPageLimit(int)

Maybe it helps too...
