### ISSUE TITLE
Add support for render caching

### ISSUE THREAD

**Issue by gpeal** [airbnb/lottie-android#348]
In some very specific cases, it may be advantageous to save the render output as an array of bitmaps and then just draw them over and over again instead of looping. 

What I'm currently thinking is to create a LottieRenderCache that takes a frame rate and can either be passed in to or created by a LottieDrawable. There will then be a hook in a LottieDrawable draw method that will pull from or render to the cache.

This will also allow you to choose to reuse or create multiple LottieRenderCaches for a single animation, potentially with different color filters. 

The main use case for this is very short, small, looping animations that will be displayed multiple/many times simultaneously such as for [Periscope super hearts](https://medium.com/@periscope/super-hearts-a-new-way-to-show-the-love-dd2d9676709c).

@seanfchan How does this sound?

**Comment by seanfchan** [comment]
That sounds good.

**Comment by jonasdoliveira** [comment]
@gpeal is that enhancement related to the issue #337 ?

**Comment by gpeal** [comment]
@jonasdoliveira Nope. This is an alternative rendering solution that is useful in few but specific circumstances.

**Comment by gpeal** [comment]
@jonasdoliveira Depending on your specific use case, this may, in face be beneficial though.

**Comment by gpeal** [comment]
Closing this because it has been deprioritized. If this seems like an important/valuable feature. Feel free to reopen it.

**Comment by a141199** [comment]
i really could use something like this

**Comment by gpeal** [comment]
@a141199 You could implement something like this by extending LottieAnimationView, overriding `draw` and storing a cache of the progress to the rendered frames for your own use case.
