### ISSUE TITLE
Cannot select json file stored locally

### ISSUE THREAD

**Issue by taylorling** [airbnb/lottie-android#35]
I have tried placing the sample json files in my device storage, and from the app, they don't seem to be selectable from the default file manager. 

Nexus 6P, running latest stable 7.1.1.

**Comment by gpeal** [comment]
Thanks for the report. I'll put up 1.0.1 today with a fix.

**Comment by maxi182** [comment]
Hi, does it work to load Json lottie file from local storage?

**Comment by gpeal** [comment]
@maxi182 yes. You can view the source for the LottieSample app to see how.
https://github.com/airbnb/lottie-android/blob/master/LottieSample/src/main/kotlin/com/airbnb/lottie/samples/AnimationFragment.kt
