### ISSUE TITLE
Improve the keyframe value caching

### ISSUE THREAD

**Issue by gpeal** [airbnb/lottie-android#352]
https://github.com/airbnb/lottie-android/commit/d5f141dbbe6c7e1ab90e7ca94bb0b38af561fec5 doesn't work. Investigate.

**Comment by azchohfi** [comment]
Yup, same wrong behavior on LottieUWP:
https://github.com/azchohfi/LottieUWP/commit/038222b6d63948aae2df3a3d4ea02df9e3c0129e#diff-3beb6887bf96b8d4981b98f00518ebcaR74

**Comment by gpeal** [comment]
The regression is now fixed. I'll open future issues for perf improvements.
