### ISSUE TITLE
High GPU usage (enable GPU profiling)

### ISSUE THREAD

**Issue by sumitsahoo** [airbnb/lottie-android#355]
I was testing Lottie animation library in one of my sample project and I am noticing a significant GPU usage. In newer hardware it will work fine but in lower end devices it may create problem. 

Library version used : v2.0
Sample project link : https://github.com/sumitsahoo/reCAPTCHADemo
Lottie file used : https://www.lottiefiles.com/264-vr-animation
Device : Nexus 6 

Attached screenshot of GPU profiling 

![device-2017-06-28-125340](https://user-images.githubusercontent.com/6181114/27625060-d8dc6374-5c00-11e7-8b32-278f4525d6e2.png)

**Comment by gpeal** [comment]
@sumitsahoo unfortunatly there is nothing actionable in this issue. I just did some additional work around performance profiling profiling ([here](https://github.com/airbnb/lottie-android/commit/0f2539cf5ca19d1dc578388d39871ca1f846e442) and [here](https://github.com/airbnb/lottie-android/commit/5cf67028e882659af366b4504096d77427a879a8)) which may lend themselves to some solid performance improvements.

**Comment by sumitsahoo** [comment]
That's great. Hope the future versions improve the performance :)
