### ISSUE TITLE
Masks not sequencing on android 

### ISSUE THREAD

**Issue by samiam2017** [airbnb/lottie-android#359]
Hey guys I'm trying to get these masks to sequence on and off in opacity. It works in the bodymovin demo file, but not on Android and iOS using the Lottie Library. Any advice would be appreciated.

-S
[TO_GitHub.zip](https://github.com/airbnb/lottie-android/files/1112649/TO_GitHub.zip)

**Comment by samiam2017** [comment]
Hey @gpeal I'm not a dev, so don't understand the code side of things. Can you give me an answer on this. Also I know our devs won't do adjustments to the library on the fly is this a bug with the library that will be corrected in the next release? Or are there work arounds that I can do on my side to avoid this issue?

best, -S

**Comment by gpeal** [comment]
I actually fixed this in the https://github.com/airbnb/lottie-android/commit/8a4a3004b046198bd3b58a4a19d0a9c83f3b6c07 in activity message above!

It'll be released with 2.1 in the next week or so.

**Comment by gpeal** [comment]
@samiam2017 ^
