### ISSUE TITLE
Support separated x and y values for points

### ISSUE THREAD

**Issue by madsbf** [airbnb/lottie-android#36]
Currently, Lottie searches for "k" as a direct child of "p". However, in some cases, After Effects animations will have separated keyframes for x and y, resulting in a structure like this:

```
"p": {
    "x": {
        "k": {
        }
    }
    "y": {
        "k": {
        }
    }
}
```

LottieComposition will throw an IllegalArgumentException with the message "Point values have no keyframes", when trying to load the above JSON.

It would be nice if Lottie could support this structure as it seems to be a common approach to use.
Fixing this will also require changes further down the chain, as JsonUtils.pointFromJsonArray will throw an exception as well as it expects at least two values, but the point may now be 1-dimensional and therefore only contain one value.

Let me know, what your thoughts on this are - I might try to fix this myself, but won't waste time on it, if you are already aware of this limitation and are already working on it f.x..

**Comment by bodymovin** [comment]
In case it helps, it gets exported as
```
"px": {
        "k": {
        },
"py": {
        "k": {
        }
```

**Comment by madsbf** [comment]
Thanks for the input. As far as I can tell from the source code, this structure would not be supported by Lottie either.

Slightly unrelated to the original issue, but do you know if my designer is on an older version of Bodymovin or possibly After Effects if the file he exports has the structure in my original comment @bodymovin ?

**Comment by bodymovin** [comment]
Hmm I don't remember having created it with that structure. Can you send me the exported json to my email?

**Comment by gpeal** [comment]
Yes! This is a feature I've looked in to supporting! I'll add it to my shortlist :) 

In the meantime, you should be able to turn off separate dimensions to work around this.

**Comment by pdenise708** [comment]
K

**Comment by gpeal** [comment]
@madsbf @pdenise708 @bodymovin I've added support for this in `1.0.2` which I plan to release next week. iOS may take a little longer though.

**Comment by gpeal** [comment]
Fixed by https://github.com/airbnb/lottie-android/commit/0bace80fc86963e19ad7b17c2bf9127e8b4a48c8

**Comment by gpeal** [comment]
@madsbf @pdenise708 1.0.2 is now live. Can you try split dimensions?

**Comment by madsbf** [comment]
I have verified this is working with 1.0.2 @gpeal ! Thanks for the swift response 👍
