### ISSUE TITLE
Can't subtract paths/masks for iOS

### ISSUE THREAD

**Issue by martyprague** [airbnb/lottie-android#367]
Hi, I can't find a way how to cut out two animated holes in a shape. I have tried masks and paths with different settings but without success.  It works perfectly on windows and android but not on iOS.

AE project: [Bodymovin_test.zip](https://github.com/airbnb/lottie-android/files/1119401/Bodymovin_test.zip)

Thanks for help

**Comment by gpeal** [comment]
Please post this on the lottie-ios repo
