### ISSUE TITLE
Can't animate images from assets with setImageAssetsFolder

### ISSUE THREAD

**Issue by Qamar4P** [airbnb/lottie-android#368]
assets/demo/img_1.jpg, img_2.jpg upto img_20.jpg

Doesn't appear anything on simulator and S7

Try 1
```
<com.airbnb.lottie.LottieAnimationView
        android:id="@+id/animation_view"
        android:layout_width="300dp"
        android:layout_height="300dp"
        app:lottie_imageAssetsFolder="demo"
        android:background="#444"
        android:layout_centerHorizontal="true"
        app:lottie_loop="true"
        app:lottie_autoPlay="true" />
```
Try 2
```
animationView.setImageAssetsFolder("demo");
animationView.playAnimation();
```

**Comment by gpeal** [comment]
@Qamar4P can you attach a sample project that repros this?

**Comment by Qamar4P** [comment]
@gpeal check out https://github.com/Qamar4P/CircularAnimationExamples, build and click on Gif button

**Comment by gpeal** [comment]
@Qamar4P You're missing the animation itself (the json file). Add the json file exported by bodymovin to assets/ and set `app:lottie_fileName="yourAnimation.json"` in your layout.
