### ISSUE TITLE
why addAnimatorUpdateListener not work

### ISSUE THREAD

**Issue by dannyzhuang** [airbnb/lottie-android#369]
first I set the animation 

`    private  LottieAnimationView  mLottieAnimationView;
    private int mCurAnimIndex = 0;
    private String[] mAnimName = new String[] {"818data1.json","818data2.json","818data3.json",
           "818data4.json"};

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        requestWindowFeature(Window.FEATURE_NO_TITLE); 
        getWindow().setFlags(WindowManager.LayoutParams. FLAG_FULLSCREEN ,
            WindowManager.LayoutParams. FLAG_FULLSCREEN); 
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_lottie);
        mLottieAnimationView = (LottieAnimationView)findViewById(R.id
            .animation_view);
        mLottieAnimationView.setAnimation(mAnimName[0], LottieAnimationView.CacheStrategy.Strong);
        mLottieAnimationView.playAnimation();

        mLottieAnimationView.addAnimatorUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
            @Override
            public void onAnimationUpdate(ValueAnimator animation) {
                Log.i("Danny","---AnimatorUpdateListener--onAnimationUpdate-");

            }
        });
        mLottieAnimationView.addAnimatorListener(this);
    }

    @Override
    public void onAnimationStart(Animator animation) {
        Log.e("Danny","---AnimatorUpdateListener--onAnimationStart-:"+animation);

    }

    @Override
    public void onAnimationEnd(Animator animation) {
        mCurAnimIndex = (mCurAnimIndex + 1) % mAnimName.length;
        Log.e("Danny","---AnimatorUpdateListener--onAnimationEnd-mCurAnimIndex:"+mCurAnimIndex);
        Log.e("Danny","---AnimatorUpdateListener--onAnimationEnd-111:"+mAnimName[mCurAnimIndex]);
        mLottieAnimationView.setAnimation(mAnimName[mCurAnimIndex],
            LottieAnimationView.CacheStrategy.Strong);
        mLottieAnimationView.playAnimation();

    }

    @Override
    public void onAnimationCancel(Animator animation) {
        Log.e("Danny","---AnimatorUpdateListener--onAnimationCancel-");

    }

    @Override
    public void onAnimationRepeat(Animator animation) {
        Log.e("Danny","---AnimatorUpdateListener--onAnimationRepeat-");

    } `

when animation end, I reset the animation file name into LottieAnimationView.

For the first time，it's ok,and the method onAnimationEnd is called. But the second time,it not work,the method onAnimationEnd  not called.

**Comment by xanatrobe** [comment]
I am running into this as well using a fragment.

**Comment by gpeal** [comment]
@dannyzhuang @xanatrobe  Can you try again with 2.2.1?

**Comment by gpeal** [comment]
I'm going to close this because it's *probably* fixed in 2.3.0. Reopen if it's not.
