### ISSUE TITLE
Lottie animation not playing on android as previewed in lottie files.

### ISSUE THREAD

**Issue by EdwinMurari** [airbnb/lottie-android#371]
https://stackoverflow.com/questions/43177613/lottie-animation-is-not-working-as-expected

Why is this happening? Even I faced such an issue, it played well on iOS device and on lottie preview but didn't work when I played it in lottie animation view in android.

**Comment by adamfisher** [comment]
I am having a similar issue.

I attempted to load the example [Pink Drink Machine](https://www.lottiefiles.com/351-pink-drink-machine) from the Lottie Files website. The animation works! It looks super cool. The only problem is it only renders part of the image. If you compare the bolts and the plunger in the canister, they do not even show up. It's like pieces of the animation are missing.

This is my Xamarin Forms code:

```
public partial class AnimationDemoAppPage : ContentPage
    {
        public AnimationDemoAppPage()
        {
            InitializeComponent();

            var animationView = new AnimationView()
            {
                Animation = "pink_drink_machine.json",
                Loop = true,
                AutoPlay = true,
                VerticalOptions = LayoutOptions.FillAndExpand,
                HorizontalOptions = LayoutOptions.FillAndExpand,
                BackgroundColor = Color.Yellow
            };

            Content = animationView;
        }
    }
```
And this is the resulting image on the iOS simulator. I also tried it on a real device. I also tried a different lottie file altogether and get the same result. I only added the yellow background to see if it made a difference in the bolts showing up. Any ideas on why the animation is only partially showing up?

<img width="500" src="https://user-images.githubusercontent.com/1834711/27608330-19b6b48c-5b55-11e7-895d-db4e56f018c6.png" />

**Comment by gpeal** [comment]
@adamfisher Make sure the Xamarin plugin is using the latest version of Lottie (2.0, soon to be 2.1). If you load that animation in the lottie sample app, it looks correct so the Xamarin plugin must be using an old version.

**Comment by gpeal** [comment]
@EdwinMurari Just noticed that that's an iOS screenshot. iOS doesn't support fill rules yet but we're working on it so stay tuned

**Comment by gpeal** [comment]
@adamfisher ^

**Comment by EdwinMurari** [comment]
No check the post below :

> I am using lottie file for animation purpose. It is not loading as expected. It should be like this http://www.lottiefiles.com/48-progress-barCurrent State https://www.dropbox.com/s/xgvj9pss2cauv37/device-2017-04-03-113913.mp4?dl=0```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
>     xmlns:app="http://schemas.android.com/apk/res-auto"
>     xmlns:tools="http://schemas.android.com/tools"
>     android:layout_width="match_parent"
>     android:layout_height="match_parent"
>     tools:context="com.icici.iciciappathon.checkout.PaymentSucessActivity"
>     android:background="@color/sky_blue">
> 
>     <com.airbnb.lottie.LottieAnimationView
>         android:id="@+id/animation_view"
>         android:layout_width="wrap_content"
>         android:layout_height="wrap_content"
>         app:lottie_fileName="progress_bar.json"
>         app:lottie_loop="true"
>         app:lottie_autoPlay="true"
>         android:layout_centerInParent="true"/>
> 
> </RelativeLayout>Any idea what I am doing wrong ?
```
> 


I am having a similar issue on android with some other animation. But it plays perfectly on Lottie preview and iOS device.

**Comment by gpeal** [comment]
The progress bar does have an issue that I'll look in to

**Comment by gpeal** [comment]
@EdwinMurari the progress bar uses expressions which aren't supported by lottie.

**Comment by gpeal** [comment]
@EdwinMurari 2.1.2 is out

**Comment by harshpatel2810** [comment]
i'm facing issue with v 2.7.1 in xamarin forms android
in ios its showing perfect but in android its not showing properly its showing at out of screen i mean its showing at right bottom of the screen and also its not showing whole animation image
can any one help me with this ?
Thank You...!!!!
:)
