### ISSUE TITLE
Lottie Android - Using Lottie Android with vector image (xml) or svg image?

### ISSUE THREAD

**Issue by khoatd92** [airbnb/lottie-android#373]
I'm using Lottie Android for animation and I put images (png) in assets folder of Android. And now I want to scale image base on devices density so I want to using vector image(xml file) or svg image instead but I haven't found any solution yet. Anyone has experience about that? Please give me some advice!

**Comment by gpeal** [comment]
@khoatd92 Why are you using Lottie to animate pngs? Most of the time, you are better off just using After Effects shapes which are inherently vectors and will scale perfectly to any size.

**Comment by khoatd92** [comment]
@gpeal I tried to use svg and xml file for image vector also and put them to assets folder of Android then I use the function setImageAssetsFolder but it's still not work.

**Comment by gpeal** [comment]
@khoatd92 I don't understand exactly what you're trying to do. Can you attach a sample project?

**Comment by khoatd92** [comment]
@gpeal Really appreciate your help and yeah sure I can attach a sample project but let me try to clear it first. 

I try to implement animation is loaded from assets and my image file is in a subdirectory of assets. 

Just call setImageAssetsFolder with the relative folder inside of assets  (img_#). 

First time I tried with img_01.png  img_02.png  img_03.png  etc then I want to scale it so I move to using img_01.svg, img_02.svg img_03.svg instead and hope that it can be scaled but it's not work, animation can not run. Is it more clearly for now?

**Comment by gpeal** [comment]
@khoatd92 Lottie can't do anything with svgs. Why don't you just create the vector assets that you're using svgs for directly inside of After Effects?

**Comment by khoatd92** [comment]
@gpeal yeah you're right, thanks for your help
