### ISSUE TITLE
Show wrong, how do i use it correctly?

### ISSUE THREAD

**Issue by wyfang** [airbnb/lottie-android#375]
Before, I used png pictures to do animation, but not fluent. So, this time to use AI to draw and then use AE to make animation, export, they are all wrong, where is the way I made it wrong?

Youtebe：https://youtu.be/NMDJjhh2UkM

This is AEP&json:[aepandjson.zip](https://github.com/airbnb/lottie-android/files/1137964/aepandjson.zip)

**Comment by gpeal** [comment]
@wyfang Can you post this on the bodymovin repo? There is an issue with the way it is being exported by bodymovin.

**Comment by wyfang** [comment]
ok
