### ISSUE TITLE
How to play multiple animations at the same time

### ISSUE THREAD

**Issue by qssq** [airbnb/lottie-android#377]
How to play multiple animations at the same time ?
How to make animation's background color transparent?

**Comment by gpeal** [comment]
@qssq just use multiple LottieAnimationViews
Animations are transparent by default, the background must be baked into the animation from your designer.

**Comment by makkhay** [comment]
@gpeal can we access the source code for MOBILO animation?  I want to include multiple letters in my app. Thanks.  Here's the gif that I'm referring to. 
https://github.com/airbnb/lottie-android/blob/master/gifs/Community%202_3.gif
