### ISSUE TITLE
LottieBoundsTest_01.json fullscreen crash

### ISSUE THREAD

**Issue by qssq** [airbnb/lottie-android#379]
download demo fullactivity crash

      Caused by: java.lang.IllegalStateException: Unable to find file LottieBoundsTest_01.json

i want download LottieBoundsTest_01.json  test

**Comment by leehong2005** [comment]
you can debug the demo to find the root cause

**Comment by gpeal** [comment]
@qssq Can you try with the latest lottie sample app?

**Comment by qssq** [comment]
versionCode 13
    versionName "2.0.0

**Comment by qssq** [comment]
yes
