### ISSUE TITLE
The Size is 2 times larger for wrap_content

### ISSUE THREAD

**Issue by talentqing** [airbnb/lottie-android#380]
LottieAnimationView use wrap_content for size, the actual size will be scaled 2 times.

for example:
PinJump.json size is 150x150
the actual is 2 times（screen size is 1080x1920）
![2](https://user-images.githubusercontent.com/30134668/28148475-8047a330-67b9-11e7-9a26-6cd501fab894.png)

the correct size
![image](https://user-images.githubusercontent.com/30134668/28148523-c1116324-67b9-11e7-9b50-a3514ade3e10.png)

float scale = res.getDisplayMetrics().density is no problem? this scale is used for dip, should the scale divide 2?

**Comment by gpeal** [comment]
@talentqing Not sure I understand the question. Lottie converts all px values in AE to dps which will be ~2-3x depending on the device.

**Comment by talentqing** [comment]
PinJump.json size is 150x150px
in picture 1, LottieAnimationView size is wrap_content in xml
in picture 2, LottieAnimationView size is 75dp in xml
picture 2 is correct size but picture 1 is not, so i think wrap_content has bug
in picture 2, 75dp correctly converts px value depending on the device

**Comment by talentqing** [comment]
This is may be not a bug, main current ui making lottie in AE base 2x device.

**Comment by gpeal** [comment]
@talentqing I'm not sure I understand the bug or the suggestion. Can you clarify?

**Comment by maoruibin** [comment]
I meet same issue, my designer give me 120 * 120 json file,  and i attache it  to my LottieAnimationView, LottieAnimationView use wrap_content for size, my device is 3x, so LottieAnimationView's size is change 360 * 360,  it's no problem, animation is play normally,  but i want it 120 * 120, so i used setScale(1f/3f) method for LottieAnimationView, but animation is play error, Now, i want to know this issue is Json file error or not ? thanks @gpeal

**Comment by GuillaumeLachaud** [comment]
I am not sure I can clarify what the original author of this task is meaning but I think I am seeing something very similar. It affects LottieAnimationView when using `wrap_content `. It got introduced somewhere between Lottie 2.0.0 and 2.2.0. I can also confirm https://github.com/airbnb/lottie-android/pull/461 fixes the issue.
As an alternative, using `.setScale(0.5f)` in our app solves the issue. But it used to be working properly on 2.0.0 without setting the scale explicitly.

See screens below taken from the sample app. 

**Lottie 2.2.3:**
![screenshot_1505862595](https://user-images.githubusercontent.com/2076017/30619679-81816cf0-9d55-11e7-9b1a-29b23f3243ea.png)

**master**
![screenshot_1505862688](https://user-images.githubusercontent.com/2076017/30619707-a9d365c8-9d55-11e7-9ec5-bf6430c0e6f8.png)

**Comment by gpeal** [comment]
@talentqing @GuillaumeLachaud v2.2.4 is now out
