### ISSUE TITLE
Crash in Lottie 

### ISSUE THREAD

**Issue by ymyronov** [airbnb/lottie-android#382]
Hello, we have the following crash in our live app for a small percent of users. We obviously can't reproduce it. Any idea why it may be happening?
We use 2.0.0-rc2.

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.Object java.util.ArrayList.clone()' on a null object reference

android.animation.ValueAnimator.cancel (ValueAnimator.java:1067)
  | com.airbnb.lottie.LottieDrawable$1.onAnimationUpdate (LottieDrawable.java:59)
  | android.animation.ValueAnimator.animateValue (ValueAnimator.java:1374)
  | android.animation.ValueAnimator.setCurrentFraction (ValueAnimator.java:602)
  | android.animation.ValueAnimator.setCurrentPlayTime (ValueAnimator.java:550)
  | android.animation.ValueAnimator.start (ValueAnimator.java:1039)
  | android.animation.ValueAnimator.start (ValueAnimator.java:1050)
  | com.airbnb.lottie.LottieDrawable.playAnimation (LottieDrawable.java:317)
  | com.airbnb.lottie.LottieDrawable.playAnimation (LottieDrawable.java:303)
  | com.airbnb.lottie.LottieDrawable.setComposition (LottieDrawable.java:156)
  | com.airbnb.lottie.LottieAnimationView.setComposition (LottieAnimationView.java:370)
  | com.airbnb.lottie.LottieAnimationView$2.onCompositionLoaded (LottieAnimationView.java:335)
  | com.airbnb.lottie.FileCompositionLoader.onPostExecute (FileCompositionLoader.java:21)
  | com.airbnb.lottie.FileCompositionLoader.onPostExecute (FileCompositionLoader.java:7)

**Comment by gpeal** [comment]
@ymyronov Are there any trends in the crashes? Only for certain manufacturers or certain versions of Android?

**Comment by ymyronov** [comment]
not really, I can't see any trends:
[https://ibb.co/jZCkPa](image)

*It does correspond to overall device distribution

**Comment by ymyronov** [comment]
I suspect it might be something to do with devices that have systemAnimations disabled as we had issues on those before. (systemAnimationsAreDisabled property in LottieDrawable)

**Comment by gpeal** [comment]
@ymyronov Are you doing anything funny with threading? We haven't seen in production nor have I heard any other reports.
Digging into the code, it's trying to clone a listener inside of ValueAnimator.

**Comment by ymyronov** [comment]
@gpeal We don't see what is the cause from the logs, but I would suspect the following code:

`
//called from RecyclerViewAdapter.onBindViewHolder
public static void animate(final LottieAnimationView view) {
        Animator.AnimatorListener listener = new AnimatorListenerAdapter() {
            @Override
            public void onAnimationEnd(Animator animation) {
                view.removeAnimatorListener(this);
                view.setAnimation("loop.json", LottieAnimationView.CacheStrategy.Weak);
                view.loop(true);
                view.playAnimation();
            }
        };
        view.addAnimatorListener(listener);
        view.setTag(listener);

        view.setAnimation("intro.json", LottieAnimationView.CacheStrategy.Weak);
        view.loop(false);
        view.playAnimation();
    }

//called from RecyclerViewAdapter.onViewRecycled
    public static void clear(LottieAnimationView view) {
        Animator.AnimatorListener listener = (Animator.AnimatorListener) view.getTag();
        if (listener != null) {
            view.removeAnimatorListener(listener);
        }
        view.clearAnimation();
    }`

Can you see any problem with this logic?

**Comment by gpeal** [comment]
@ymyronov onBind and onRecycled are not analogous methods. Bind can get called many times before it's recycled. This may be causing your issue.

**Comment by ymyronov** [comment]
@gpeal thanks, you are right, bind can be called many, I have fixed that part, however it was not the cause for the issue.
I actually managed to reproduce the issue now and spotted the exact place it is happening. 

Animations has to be disabled in phone settings and than when we call animateFromTo we can observe this crash every time. 

'''java
public static void animateFromTo(LottieAnimationView from, LottieAnimationView to) {
        to.cancelAnimation();
        to.setProgress(0);
        from.setVisibility(VISIBLE);
        to.setVisibility(VISIBLE);
        to.addAnimatorListener(new AnimatorListenerAdapter() {
            @Override
            public void onAnimationStart(Animator animation) {
                from.setVisibility(GONE);
                from.cancelAnimation();
                to.removeAnimatorListener(this);
            }
        });
        to.playAnimation();
    }
'''

This method is obviously a mess(it is not mine), but I still feel like it should not crash from inside Lottie...
In case we call "animateFromTo" in custom view constructor we get the original crash, however if we simply call it on button click we get more meaningful crash:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.ArrayList.clone()' on a null object reference
                                                                         at android.animation.ValueAnimator.cancel(ValueAnimator.java:1135)
                                                                         at com.airbnb.lottie.LottieDrawable$1.onAnimationUpdate(LottieDrawable.java:64)
                                                                         at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
                                                                         at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:642)
                                                                         at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:589)
                                                                         at android.animation.ValueAnimator.start(ValueAnimator.java:1106)
                                                                         at android.animation.ValueAnimator.start(ValueAnimator.java:1117)
                                                                         at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:340)
                                                                         at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:326)
                                                                         at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:446)
                                                                         at com.discovery.fusionr.kids.prototype.utils.LottieUtils.animateFromTo(LottieUtils.java:24)

**Comment by gpeal** [comment]
@ymyronov Can you attach a sample project that repros this?

**Comment by Kane-Shih** [comment]
In LottieDrawable, if systemAnimationsAreDisabled is true, it will cancel the animator immediately.
In ValueAnimator.cancel(), it will call notifyStartListeners() if the animation has not run yet, before calling onAnimationCancel().

Thus, you should not remove animator listeners at onAnimationStart(). 

To reproduce this crash, do:
1. remove animator listeners at onAnimationStart(), and 
2. go to Settings to disable system animation.

ref:
http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.1.1_r1/android/animation/ValueAnimator.java#ValueAnimator.cancel%28%29
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java#L69

**Comment by ymyronov** [comment]
Sorry guys, a bit busy those days... will come to you shortly

**Comment by gpeal** [comment]
@Kane-Shih I can't repro this by following those two steps. If you could attach a repro project, that would be great.

**Comment by ymyronov** [comment]
@gpeal Please find test project, you should be able to reliably reproduce the issue.
[project link](https://drive.google.com/open?id=0ByqvAe20o3oUYzFqUlJaOF84T28)
[screenshot](https://pasteboard.co/GHh1se7y.png)

Steps to reproduce:
1. start the emulator - Nexus_5_API_17
2. go to developer-settings, "drawing" section and set:
Window animation scale: Animation off
Transition animation scale: Animation off
Animator duration scale: Animation off
3. make sure app is not running, if it is running - kill it via task manager
4. start the app and press the button.
5. should see the crash.

**Comment by rksinghj4** [comment]
public static void animate(final LottieAnimationView view) {
        Animator.AnimatorListener listener = new AnimatorListenerAdapter() {
            @Override
            public void onAnimationEnd(Animator animation) {
                view.removeAnimatorListener(this);
                view.setAnimation("teliscope.json", LottieAnimationView.CacheStrategy.Weak);
                view.loop(true);
                view.playAnimation();
            }
        };
        view.addAnimatorListener(listener);
        view.setTag(listener);

        view.setAnimation("intro.json", LottieAnimationView.CacheStrategy.Weak);
        view.loop(false);
        view.playAnimation();
    }

I have debug the code, "intro.json" animating once and then  control is going inside "onAnimationEnd" but "teliscope.json" is not animating. Any great mind here please answer this question?

Thanks in advance.
