### ISSUE TITLE
useExperimentalHardwareAcceleration has a bug

### ISSUE THREAD

**Issue by talentqing** [airbnb/lottie-android#383]
If the LottieAnimationView invoke setAnimation, playAnimation and useExperimentalHardwareAcceleration at the same time. useExperimentalHardwareAcceleration will be unusable. But if it invoke playAnimation after json parse,  then useExperimentalHardwareAcceleration will be usable.

The method of useExperimentalHardwareAcceleration is the View method, playAnimation will check it, but if playAnimation first, and setComposition of drawable after json parse will be invoke playAnimation of drawable (not View), then it can not  check useExperimentalHardwareAcceleration.

**Comment by gpeal** [comment]
@talentqing 2.1.2 is out
