### ISSUE TITLE
X-/Y-Axis Problems with 3D Layers

### ISSUE THREAD

**Issue by loptik** [airbnb/lottie-android#384]
Json File ignores rotation keyframes of x- and y-axis of 3D-Layers when exporting out of after effects 

looks fine in the demo. 
but when using the code, it ignores the 3D-Layer and just does the rotation keyframes of the z-axis

![bildschirmfoto 2017-07-13 um 14 57 08](https://user-images.githubusercontent.com/12908463/28167371-b976fc88-67db-11e7-9c6e-d9137df00d0c.png)

**Comment by therealsalih** [comment]
Hi @loptik 3d layers are supported by bodymovin but are not supported by Lottie

**Comment by sepehr1014** [comment]
Any plans on adding 3D support?

**Comment by gpeal** [comment]
3D currently isn't on the roadmap for Lottie. I'll create subsequent issues in the future if that changes.
