### ISSUE TITLE
OutOfMemoryError when loading a ludicrously huge JSON animation on a Galaxy S3

### ISSUE THREAD

**Issue by subtleGradient** [airbnb/lottie-android#39]
JSON is 1.5 MB uncompressed, 94 KB zipped.
Lottie should probably switch from JSON to Flatbuffers. I'll open a separate issue for that.

**Comment by gpeal** [comment]
@subtleGradient Can you attach the json file? There may be some things we can do in the meantime to reduce overhead.

**Comment by gpeal** [comment]
@subtleGradient so I spent way too many hours this week migrating over the JsonReader. However, the existing json structure of bodymovin makes it *incredibly* inconvenient unfortunately. I'm going work with Hernan from bodymovin to figure out a good solution here.

**Comment by gpeal** [comment]
@subtleGradient Only took a year but I finally got this working :)
