### ISSUE TITLE
Bug with shape layers

### ISSUE THREAD

**Issue by re-player** [airbnb/lottie-android#390]
Hi, I have an issue with rendering shape layers. Bug appears not only on complex shapes, but even on text converted to shapes (!).

Here, take a look please:
1) in after effects everything is ok: http://c2n.me/3MdXVut.png
2) here it is after rendering in bodymovin: http://c2n.me/3MdY8xR.png. i've pointed with arrows problem places + u can see what happened to the letters 

This problem can be solved?

I've attached ae-file in hud.zip + JSON-file in eagle.zip.

[eagle.zip](https://github.com/airbnb/lottie-android/files/1155581/eagle.zip)
[HUD.zip](https://github.com/airbnb/lottie-android/files/1155576/HUD.zip)

**Comment by gpeal** [comment]
@re-player Lottie doesn't support layer effects or expressions (getWarnings() reports your use of both). If there are still issues without using those, feel free to reopen this.

**Comment by re-player** [comment]
I wasn't asking about animation bugs. My question was about shape issues. Can u tell me why this is happening http://c2n.me/3MhMIEq.png? No effects on this layers.
