### ISSUE TITLE
Unable to subtract multiple masks from one shape layer

### ISSUE THREAD

**Issue by bajabob** [airbnb/lottie-android#391]
Hello team and thank you for such a great framework, I have been following the progress for quite some time. 

I am attempting to subtract two masks from a single shape layer and am not getting the desired effect, although adding two masks seems to be working just fine! The Lottie Animation viewer (available on the play store) has the same effect on the animation as our local 2.1.0 build. The animation renders properly on lottiefiles.com/preview. This seems to be specific to Android, though I have not been able to confirm on iOS. Any guidance would be much appreciated! 

Diagnosing: 
We have updated to the latest bodymovin, AE and are running on Lottie-Android 2.1.0. We have witnessed multiple additive masks working for a single shape in this project as well. Please see attached AE and JSON. 

[multi-subtract.zip](https://github.com/airbnb/lottie-android/files/1156704/multi-subtract.zip)

**Comment by therealsalih** [comment]
Hi @bajabob If you take those two masks and make them PATHS within the shape layer that should solve your problem

See this example:
![image](https://user-images.githubusercontent.com/5893643/28383469-168410e8-6c76-11e7-914a-6b09a78cd123.png)



Thanks!

**Comment by therealsalih** [comment]
Also, we'll add Subtracting masks to our list of upcoming features. Thanks!

**Comment by bajabob** [comment]
Thank you so much for the awesome help!
