### ISSUE TITLE
Animation containing vector image is cut off because of the height of the container view

### ISSUE THREAD

**Issue by sathvik87** [airbnb/lottie-android#393]
I am using lottie:2.1.0 
Test device is Nexus 5x running Android 7.x

Layout File:

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.airbnb.lottie.LottieAnimationView
        android:id="@+id/animation_view"
        android:layout_width="300dp"
        android:layout_height="300dp"
        android:layout_gravity="center_horizontal"
        android:layout_marginBottom="30dp" />
</LinearLayout>

I am trying to load the animation as below
 
animationView.setAnimation("bubbles.json");
animationView.playAnimation();

I have other animations of same height which does not get cut off by the height of the animation_view but here, the animation of the "+" at the end is cut off with the given height but if I increase the height of the animation_view to say 350dp, animation is fine. Though the animation does not require that much height. Even designer checked the animation files and could not find the underlying reason.

[bubbles.json.zip](https://github.com/airbnb/lottie-android/files/1162318/bubbles.json.zip)

**Comment by gpeal** [comment]
@sathvik87 All px values get converted to dp. Your animation is 375x375 so it'll actually render 375dpx375dp. The correct solution is to have the designer change the composition size to 300x300 but you can also work around it by using scaleType=centerInside just like you would with any other ImageView.

**Comment by sathvik87** [comment]
@gpeal Hi, Thanks for the reply. I just tried android:scaleType="centerInside" and it did not fix the issue. But sure can be fixed by adjusting the container size or composition size. I think it will also be good if there is a warning in logs if the height of the animationView is smaller than the actual size of the animation. Probably, should add in feature request. Thanks again.

**Comment by gpeal** [comment]
@sathvik87 If there are masks or mattes, only the region inside the view size will be rendered which is why you only see part of the plusses. If you can achieve the same animation without masks or mattes (which you can in this case), it'll be more performant not to use them anyway.

**Comment by sathvik87** [comment]
@gpeal Thanks for informing about the Masks. We recreated the animation without masks and animation is working as expected on resize of the container too.
