### ISSUE TITLE
Scale breaks layers

### ISSUE THREAD

**Issue by PaulWoitaschek** [airbnb/lottie-android#395]
When scaling the image, it breaks some layers.

I created a video using the latest lottie app (2.1.0):
https://drive.google.com/file/d/0B5mpR2iy1EwyWVN0SnFmQWdWUmM/view

**Comment by gpeal** [comment]
@PaulWoitaschek This is a limitation of the way masks work. A mask or matted layer can't be larger than the LottieAnimationView. What's happening here is that the view is rendering larger but the masked layers are getting clipped. The solution is to not make the animation larger than the view if there are masks or mattes.

**Comment by gpeal** [comment]
@PaulWoitaschek 2.1.2 is out
