### ISSUE TITLE
crash: Unable to find file hello-world.json

### ISSUE THREAD

**Issue by AhYousefi** [airbnb/lottie-android#396]
animationView.setAnimation("hello-world.json");

The hello-world.jsonis in the assets folder but 
  crash : Unable to find file hello-world.json
i use java no kotlin

**Comment by gpeal** [comment]
@AhYousefi I'm not sure I understand the problem. Is this in your own project?

**Comment by gpeal** [comment]
@AhYousefi You should replace hello-world.json with the name of your animation.
