### ISSUE TITLE
Rotated text not rendered correctly

### ISSUE THREAD

**Issue by JamieJuliusSundaySky** [airbnb/lottie-android#397]
The attached zip contains:
- JSON input
- Image of expected output
- Image of actual output

The composition contains two text layers "AB" and "CD". One is point text and one is paragraph text. They both have their Rotation property animated. The expected result is that each text sequence rotates around the anchor point, which is at the bottom left of each text sequence. The actual result is that each glyph is being rotated individually. This happens with both point text and paragraph text alike.
[ABCDRotate.zip](https://github.com/airbnb/lottie-android/files/1170247/ABCDRotate.zip)

**Comment by JamieJuliusSundaySky** [comment]
Note that in the example above the text is rendered via the "useTextGlyphs" route. When going through the "Font" route all is well as the rotation is applied to the canvas as a whole and not to the individual paths:

    if (!lottieDrawable.useTextGlyphs()) {
      canvas.setMatrix(parentMatrix);
    }

**Comment by liukaichi** [comment]
Happens with me too. Any workarounds?

**Comment by azchohfi** [comment]
This JSON is not even working anymore. That's because on your file, "sw" is 0.00999999977648 but we are reading it as an int. @gpeal Should this be read as a double? The only usage of this variable is already being multiplied by the scale so it is returning a float anyway.

**Comment by gpeal** [comment]
@azchohfi Update your bodymovin plugin

**Comment by axitasavani** [comment]
Which BodyMovin Plugin used to make animation For Lottie?  @gpeal

**Comment by gpeal** [comment]
@axitasavani Use whatever the latest version is. The comment above is from a version that is many years old.

**Comment by Pavel87** [comment]
> The attached zip contains:
> 
> * JSON input
> * Image of expected output
> * Image of actual output
> 
> The composition contains two text layers "AB" and "CD". One is point text and one is paragraph text. They both have their Rotation property animated. The expected result is that each text sequence rotates around the anchor point, which is at the bottom left of each text sequence. The actual result is that each glyph is being rotated individually. This happens with both point text and paragraph text alike. [ABCDRotate.zip](https://github.com/airbnb/lottie-android/files/1170247/ABCDRotate.zip)

I know this has been few years but what is the solution to this issue?  @JamieJuliusSundaySky

**Comment by Pavel87** [comment]
Ok got the solution... like said above we have to avoid rendering text as glyphs but rather we need to render as font:

`if (!lottieDrawable.useTextGlyphs()) {
  canvas.setMatrix(parentMatrix);
}`

If we just set the text delegate then the rotation is working as expected.

`binding.lottie.setTextDelegate(TextDelegate(binding.lottie))`
