### ISSUE TITLE
Paragraph Text is not supported

### ISSUE THREAD

**Issue by JamieJuliusSundaySky** [airbnb/lottie-android#399]
The DocumentData class does not seem to support the "sz" and "ps" properties, which are present for Paragraph Text.

As such, paragraph text is not rendered correctly.

**Comment by gpeal** [comment]
@JamieJuliusSundaySky Lottie currently only supports single line text but I'll make a new issue to support multiline

**Comment by gpeal** [comment]
https://github.com/airbnb/lottie-android/issues/401
