### ISSUE TITLE
Text with newlines crashes Lottie

### ISSUE THREAD

**Issue by JamieJuliusSundaySky** [airbnb/lottie-android#400]
If text contains a newline (possibly any whitespace) Lottie will crash.
This is because Lottie is assuming that every character contains a "data" property with an embeded "shapes" property.

FontCharacter newInstance contains this line:

JSONArray shapesJson = json.optJSONObject("data").optJSONArray("shapes");

This does not take into account that json.optJSONObject("data") can return null. Such is the case for whitespace, which has no shapes.

For example:

	"chars": [{
		"ch": "H",
		"size": 144,
		"style": "Regular",
		"w": 72.22,
		"data": {
			"shapes": [{
				...
			}]
		},
		"fFamily": "Arial"
	},
	{
		"ch": "i",
		"size": 144,
		"style": "Regular",
		"w": 22.22,
		"data": {
			"shapes": [{
				...
			}]
		},
		"fFamily": "Arial"
	},
	{
		"ch": "\r",
		"size": 144,
		"style": "Regular",
		"w": 0,
		"fFamily": "Arial"
	},
	
	etc.

**Comment by gpeal** [comment]
@JamieJuliusSundaySky Correct. Lottie doesn't yet support newlines but I should make it not crash at least.

**Comment by gpeal** [comment]
https://github.com/airbnb/lottie-android/issues/401
