### ISSUE TITLE
Add support for multiline text

### ISSUE THREAD

**Issue by gpeal** [airbnb/lottie-android#401]

**Comment by JamieJuliusSundaySky** [comment]
Thanks!

Please note that Paragraph Text doesn't work correctly even for single line text as it justifies the text to the layer's origin as opposed to the Paragraph Text box.

Speaking of justification, it would be great to add support for that too (at least center and right).

**Comment by rogererill** [comment]
Are there any news on this? It could be a very useful feature for us :)

**Comment by gpeal** [comment]
@rogererill I haven't been able to find the time to make it happen. I would accept a PR though.

**Comment by MONIKA-KUMAR-JETHANI** [comment]
Hi @gpeal , Is this issue open? Can I start work on this?

**Comment by gpeal** [comment]
@MONIKA-KUMAR-JETHANI Sure
