### ISSUE TITLE
Image asset with alpha matte will be broken.

### ISSUE THREAD

**Issue by bearprada** [airbnb/lottie-android#402]
Please see the attachment:

![device-2017-07-26-112857](https://user-images.githubusercontent.com/1080103/28603355-107c1b34-71f6-11e7-85d0-05a2a6c3a4a4.png)

**Comment by gpeal** [comment]
@bearprada Can you provide more information and attach an animation that repros this?

**Comment by gpeal** [comment]
@bearprada I just did a test and it worked. Can you try again with the latest version and reopen with an example if it still fails?
