### ISSUE TITLE
Gradient Fill Issue

### ISSUE THREAD

**Issue by J20170726** [airbnb/lottie-android#407]
The Gradient fill from AE does not work in the Android application.

I've tested it on lottiesfiles.com and it looks fine but not in Android.

It is showing me wrong color like below;
![screenshot_2017-07-27-10-15-15](https://user-images.githubusercontent.com/30452221/28650172-c6f1373c-72b4-11e7-9588-351e72fcf75d.png)

It is supposed to look like this;
<img width="758" alt="screen shot 2017-07-27 at 10 15 26 am" src="https://user-images.githubusercontent.com/30452221/28650202-f44ddabe-72b4-11e7-842e-82ca8d1d87be.png">

**Comment by J20170726** [comment]
Attached a zip including .json and .aep.
[Gradient Fill.zip](https://github.com/airbnb/lottie-android/files/1178476/Gradient.Fill.zip)

**Comment by gpeal** [comment]
This is a screenshot of your gradients vs what I see when I open after effects and export the json with bodymovin. Both of your gradients look different than what I'm seeing and after effects and lottie look the same on my computer.
![image](https://user-images.githubusercontent.com/1307745/28842142-64eb6214-76b1-11e7-9198-602a94ff74b2.png)

**Comment by gpeal** [comment]
I'm going to close this but if you can come up with some repro steps, feel free to reopen.
Make sure to try on 2.1.2 as well.

**Comment by J20170726** [comment]
Where can I get the Bodymovin 2.1.2?

**Comment by gpeal** [comment]
Sorry for the delay. Just pushed it to maven. It's rolling out now.
