### ISSUE TITLE
Repeater issue

### ISSUE THREAD

**Issue by re-player** [airbnb/lottie-android#410]
Hi,

I have an issue with repeater. For unknown reason it doesn't work right. 
That's how it must be: http://c2n.me/3MvIBtT.png
And that's how it's in the app: http://c2n.me/3MvINPx.png

I've attached json file. No bugs after exporting via bodymovin http://c2n.me/3MvJlpW.png, smth happening exactly in lotty.

Can u help? I've send after effects file on ur email.
[data.zip](https://github.com/airbnb/lottie-android/files/1183524/data.zip)

p.s.: also can provide .apk file if needed

**Comment by gpeal** [comment]
@re-player I think you're actually running into the issue fixed by this: https://github.com/airbnb/lottie-android/commit/fcdac57b1918fb500d10f21bba7a02b8a8b597a1

I'll release 2.1.2 soon so you can test it or you can clone the repo yourself.

**Comment by gpeal** [comment]
Lottie also doesn't support layer effects yet

**Comment by re-player** [comment]
Em, i don't have any layer effects in there. Only shapes + repeater + alpha matte.Did u check my ae-file? All has been done very & very simple.20:50, 28 июля 2017 г., Gabriel Peal <notifications@github.com>:Lottie also doesn't support layer effects yet  —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.         Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by re-player** [comment]
Previous reply was from smartphone. Just have checked the link https://github.com/airbnb/lottie-android/commit/fcdac57b1918fb500d10f21bba7a02b8a8b597a1. 

So, i need to update this files:

lottie/src/main/java/com/airbnb/lottie/CompositionLayer.java
lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java

and this bug will go away, yes?

**Comment by gpeal** [comment]
@re-player well you'll want to upgrade to 2.1.2 but yeah it should. I'll try and push that out today

**Comment by re-player** [comment]
Ok, thx)

**Comment by gpeal** [comment]
@re-player 2.1.2 is out

**Comment by re-player** [comment]
Downloading, thank u for a notice)

**Comment by re-player** [comment]
Hi, @gpeal 

Sadly, but new release didn't do any better http://c2n.me/3Mynp97.png. Actually, it made repeater look worse than before(

**Comment by re-player** [comment]
My idea is that smth very wrong with track mattes. It doesn't work right & all looks messed up cause of it.

**Comment by re-player** [comment]
No, i was wrong. Track mattes has nothing to do with that. Even with simple masks we having this http://c2n.me/3MyteGN.png.

**Comment by re-player** [comment]
I've checked several scenarios  http://c2n.me/3MyUPor.png.

As u can see, repeater works fine, but masks & track mattes not. It's happening because of them.

**Comment by gpeal** [comment]
There was an issue uploading 2.1.2. Can you try it again. It's rolling out
now.

**Comment by re-player** [comment]
Sadly, but nothing changed(

I have another problem, now with trim path. Pls, have a look here, i've recorded video
[trim path bug video.zip](https://github.com/airbnb/lottie-android/files/1193532/trim.path.bug.video.zip)

Lines appears via trim path, but not go away http://c2n.me/3MCyWXC.png. Trim path works only first time, don't know why.

I've send ae-file on ur email.

**Comment by re-player** [comment]
UPD: i've changed trim path to scale, so now it working fine. But still would be great to figure out why this bug appeared.

**Comment by gpeal** [comment]
@re-player Can you attach an aep file that reproduces the bug and open a new issue? Happy to take a look.
