### ISSUE TITLE
Unable to clear animation from memory

### ISSUE THREAD

**Issue by tekinarslan** [airbnb/lottie-android#412]
Hi,
Thanks for great lib for animations.
I am define xml and play animation from java code. 
My problem, When I finished activity but, memory usage not decreasing. 
I try cache strategy types for tutorial pages, but I cannot reach solution.

Thanks.

**Comment by gpeal** [comment]
@tekinarslan Did you try triggering a GC from Android Studio? If that doesn't help, can you attach a project that repros this?

**Comment by tekinarslan** [comment]
@gpeal  Thanks for reply. I used GC for clear.
