### ISSUE TITLE
Animation error with Android

### ISSUE THREAD

**Issue by henriqrossatto** [airbnb/lottie-android#413]
Hi there.

I created some animations for a app and when the developer test on android, the animation had a fill error that didn't have in IOS version. The problem is that there is not any fill where the error occour.

I attached the ae files and the images with the error

I'm a beginner in bodymovin, so I do not know if the way to export to Android is different from the one for IOS
[report_error.zip](https://github.com/airbnb/lottie-android/files/1190414/report_error.zip)

**Comment by gpeal** [comment]
@henriqrossatto can you try again with 2.1.2.
What's happening is you have a mask or matte and the animation is much larger than the view itself. The composition size in px in after effects gets converted to dps. In the mean time, try making your composition smaller or call setScale with value < 1 and use scaleType centerInside

**Comment by henriqrossatto** [comment]
Thanks @gpeal. We resize the comp and works correctly.
