### ISSUE TITLE
NumberFormatException in LottieComposition.fromJsonSync() 

### ISSUE THREAD

**Issue by Ari-Jin** [airbnb/lottie-android#422]
When calling setAnimation(JSONObject) with JSONObject that does not fit the format,
crash (NumberFormatException) occurs at LottieComposition.fromJsonSync().

```
Caused by: java.lang.NumberFormatException: Invalid int: ""
	at java.lang.Integer.invalidInt(Integer.java:138)
	at java.lang.Integer.parseInt(Integer.java:358)
	at java.lang.Integer.parseInt(Integer.java:334)
	at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(LottieComposition.java:257)
	at com.airbnb.lottie.JsonCompositionLoader.doInBackground(JsonCompositionLoader.java:17)
	at com.airbnb.lottie.JsonCompositionLoader.doInBackground(JsonCompositionLoader.java:7)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
```

Because the call of LottieComposition.fromJsonSync() is made in doInBackground() of AsyncTask, however, exception cannot be handled at the point that calls setAnimation().

Therefore, I want you to handle the exception that could happen due to JSONObject that does not fit the format in doInBackground().

I think like..
< JsonCompositionLoader.java >
```
@Override protected LottieComposition doInBackground(JSONObject... params) {
   LottieComposition lottieCompotision = null;
   try {
      lottieCompotision = LottieComposition.Factory.fromJsonSync(res, params[0]);
   } catch (NumberFormatException e) {
   }
   return lottieCompotision;
}
```

**Comment by gpeal** [comment]
@Ari-Jin Can you attach the aep file that causes this?

**Comment by Ari-Jin** [comment]
JSONObject that I send to setAnimation() does not fit the format.
I mean, it is not the aep file.
setAnimation() is called with JSONObject that is from the response of server.
So it is for dealing with exceptions of response of wrong JSONObject.

**Comment by gpeal** [comment]
@Ari-Jin I understand that but I can't debug what part of the original animation is causing malformed json without the aep. I don't want to blindly catch an exception without understanding why it's happening.

**Comment by Ari-Jin** [comment]
It is a malformed json that crased.
`{
"roi":""
}`

I want to prevent crash due to unpredictable response of server.

**Comment by gpeal** [comment]
@Ari-Jin I recommend you do some sanity checks on the JSONObject before you pass it to Lottie then. Lottie will assume that the json is valid.
