### ISSUE TITLE
Android menu list item lottie 

### ISSUE THREAD

**Issue by sinzen** [airbnb/lottie-android#427]
Hi, I start with lottie in Android,

I want to create menu slider in after effect with an hamburger icon but now I want to add a list of items inside the animation.. How can I do that with lottie ? Thanks for your answer.

**Comment by gpeal** [comment]
@sinzen What do you mean a list of items inside the animation?

**Comment by sinzen** [comment]
Thanks for your answer.. I mean when the menu is open in a mobile device
The links in this menu like Settings,User account..
I attach an image, I want to add links in the area orange
<img width="158" alt="capture d ecran 2017-08-10 a 08 24 29" src="https://user-images.githubusercontent.com/11914312/29157129-aee72d4e-7da5-11e7-95c8-2b78d49a2058.png">

**Comment by gpeal** [comment]
@sinzen Can't you just use normal views and lottie drawable or lottie animation views where appropriate?

**Comment by sinzen** [comment]
Yes I understand a little, can you explain me more about lottie drawable, lottie animation.
And how can I use it?

**Comment by gpeal** [comment]
@sinzen There is documentation on the readme. Please refer to that.

**Comment by sinzen** [comment]
You confirm me Is that possible to do a complete menu with links and more?

**Comment by gpeal** [comment]
@sinzen Not entirely with Lottie but you could use Lottie for the animations

**Comment by gpeal** [comment]
Use normal views when you can
