### ISSUE TITLE
Unable to play json plays in sequence or animation jumps

### ISSUE THREAD

**Issue by ericawong** [airbnb/lottie-android#428]
Hi,

We were trying to play these 4 json in sequence (1, 2, 3, 3b) with a new button to play the next animation on each file. However, while playing the 2nd file, the animation would just stop in the middle. The 3rd one played just fine but when we were trying to play 3b, it loops back to 3 and won't play 3b.
[Archive.zip](https://github.com/airbnb/lottie-android/files/1213276/Archive.zip)

We are just not sure what the problem is......

Thank you,
Erica

**Comment by gpeal** [comment]
@ericawong Does this comment help?
https://github.com/airbnb/lottie-android/issues/250#issuecomment-296399128

**Comment by ericawong** [comment]
@gpeal Thank you! It does! 

But another issue came up in file 2, I animated the spinner using trim path as mentioned in the document, but it doesn't seem to be rendering properly as well as the spinner is being cut off around the corners?

**Comment by gpeal** [comment]
@ericawong Can you attach the animation?

**Comment by ericawong** [comment]
@gpeal Here it is! Thanks alot for the help!

[android.aep.zip](https://github.com/airbnb/lottie-android/files/1219328/android.aep.zip)

**Comment by ericawong** [comment]
I have also attached a simple video and commented on the video as well.

Thanks a lot for the help,
Erica

**Comment by gpeal** [comment]
@ericawong It seems to be rendering fine for me. Can you try on 2.2.1?
![slide](https://user-images.githubusercontent.com/1307745/30251898-d1318670-961d-11e7-995c-9bd95231cbdf.gif)
