### ISSUE TITLE
Native typeface cannot be made

### ISSUE THREAD

**Issue by sllikson** [airbnb/lottie-android#429]
I wanted to use this library in android for first time.
I added the tag in my xml layout
```
<com.airbnb.lottie.LottieAnimationView
        android:id="@+id/animation_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />
```
and i Passed animation name from javafile:
```
LottieAnimationView animationView = (LottieAnimationView) findViewById(R.id.animation_view);
        animationView.setAnimation("hello-world.json");
        animationView.loop(true);
        animationView.playAnimation();
```
I also added the `hello-world.json` to assets folder.
**My Exception is:**
`java.lang.RuntimeException: native typeface cannot be made`
How can i solve this?

**Comment by gpeal** [comment]
@sllikson Sound like there is something wrong with your font itself or something about it that Android doesn't support. It doesn't sound like the exception is coming from Lottie itself.

**Comment by sllikson** [comment]
@gpeal The problem was from the `.json` animation. As you said the Lottie works fine. I tested **another** one from the provided samples and it worked. Thanks for the answer.
