### ISSUE TITLE
SetScale not working

### ISSUE THREAD

**Issue by sinzen** [airbnb/lottie-android#431]
Hi,

I'm using lottie to do an animation. I try to resize the animation with : `animationView.setScale(0.9f);`

but isn't works.. here are my layout:
`<com.airbnb.lottie.LottieAnimationView
        android:id="@+id/animation_view"
        android:layout_width="100sp"
        android:layout_height="100sp"
        app:lottie_autoPlay="true"
        app:lottie_fileName="data.json"
        app:lottie_loop="true"
       />`

Thanks for your help

**Comment by sinzen** [comment]
I'm back..
Is the property below is missed to scale the animation?
`scaleType=centerCrop` 
In my xml view I saw it here: [https://github.com/airbnb/lottie-android/issues/326](url)

**Comment by gpeal** [comment]
@sinzen can you attach a sample project that repros this?

**Comment by TheEnsis** [comment]
Me too.
I'm used file checked_done.json from lottiefile.com

**Comment by sinzen** [comment]
Hi,
To solve the issue I tried another way and it works..
I took the aep file, and I réduction the border of composition into the limit of my animation..
Android reseize to get a an animation without pixels.
In my XML (Android proj) I fixe the size and that's it. I'm doesn't use setscale in the java class.
I can post the project if you need ?

**Comment by gpeal** [comment]
@sinzen @TheEnsis v2.2.4 is now out
