### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by re-player** [airbnb/lottie-android#436]
Hi,

We having not typical issue with fps & perfomance. I've created 3 animated buttons in ae. When run test with 3 same buttons, fps is just awesome. Take a look pls: https://www.dropbox.com/s/nhom6eo8q9k31h7/video%20%2835%29.mp4?dl=0

But when it's not 3 copies of the same button, fps is way lower. U can see for yourself: https://www.dropbox.com/s/kqx23c5k5us8p8k/video%20%2841%29.mp4?dl=0

Can u tell why is this happening? Buttons are completely the same, only difference is the number of letters on every button.

Maybe lottie uses cache when buttons are the same? Is there any way to make lottie work as fast as on the first video?

**Comment by gpeal** [comment]
@re-player What do you mean by 3 copies of the same button?

**Comment by re-player** [comment]
@gpeal hm, i guess u wouldn't ask this question if u would watch first video)

we've run several performance tests & sometimes we use the same button for that. 1 button is used 3 times (instead of 3 different buttons), like this http://c2n.me/3N1QUzC.png. but as i've already said, all 3 buttons have the very same animation, only difference between them is number of letters.

**Comment by therealsalih** [comment]
Hi @re-player can you send us the AE file so we can see how the animation is built?

**Comment by re-player** [comment]
I've already solved the problem. Shapes in pattern have been replaced with same png-pattern. And fps became just awesome)

**Comment by therealsalih** [comment]
@re-player oh awesome!
hrm so shapes were replaced with a png? Can you still send me an AE of the shapes that were causing the problem? I want to see if theres something about the way it was built that we can fix for other users down the line.

Thanks!

**Comment by re-player** [comment]
@therealsalih, yeah, sure, i can give it to u. can u pls tell me ur email, so i will send u ae-file?

**Comment by therealsalih** [comment]
@re-player can you send to lottie@airbnb.com

Thanks!
