### ISSUE TITLE
My Lottie file is not rendered properly on Android.

### ISSUE THREAD

**Issue by aidan-kang** [airbnb/lottie-android#437]
Hello,
My Lottie file is not rendered properly on Android unlike preview in "https://www.lottiefiles.com".
Please check the following. [https://www.lottiefiles.com/share/Xog2Ry](url)
Thank you.

**Comment by gpeal** [comment]
Hah, you have to admit, it looks sort of neat how it gets rendered on Android...

Thanks for the report. I'll take a look.

**Comment by gpeal** [comment]
@aidan-kang Can you attach the aep file?

**Comment by dhenry** [comment]
Hi @gpeal, I'm having a similar issue. I've posted the json here: https://pastebin.com/fQQLUqHf

The animation is rendered as a solid red square that fades in and out. Here's the same json on lottie preview: https://www.lottiefiles.com/share/khYBXv

**Comment by gpeal** [comment]
@dhenry Your animation renders fine with 2.2.0

**Comment by dhenry** [comment]
Thanks for the quick response @gpeal. It turns out I was just missing the lottie_scale attribute.

**Comment by gpeal** [comment]
@aidan-kang Can you attach your aep file?

**Comment by gpeal** [comment]
Feel free to reopen this if there is still an issue with 2.2.4

**Comment by gpeal** [comment]
@dhenry 2.2.4 is now out
