### ISSUE TITLE
Add mention of NativeScript plugin

### ISSUE THREAD

**Issue by bradmartin** [airbnb/lottie-android#44]
Repo: https://github.com/bradmartin/nativescript-lottie

Would be nice to have this on the README so devs know it is supported on another framework for mobile development. Thanks. Was fun working with 👍

**Comment by gpeal** [comment]
Awesome! Thanks for putting that together!

**Comment by bradmartin** [comment]
I'd have submitted a PR, but not sure where you all would prefer it on the README since it's not on Airbnb account like the initial header mention of the RN version.

**Comment by gpeal** [comment]
I don't see the PR. I can put it on the Readme, it'll just be in a different section.

**Comment by bradmartin** [comment]
Yea sorry, that reads weird `I'd have submitted`. Meant I would have but didn't know where you would like it. Thanks for adding it though 😄
