### ISSUE TITLE
Add touchable support

### ISSUE THREAD

**Issue by gpeal** [airbnb/lottie-android#444]

**Comment by Heuid384** [comment]
we would like you add more interactive features, the animation divided into several parts,for example, this file: https://www.lottiefiles.com/popular?page=5  , the boy and the bicycle,if we touch the boy only,and the boy moves alone,the bike stays.thanks if you understand what I said

**Comment by alexhorsa** [comment]
How would you implement touchable support? 

I imagine there will be a way to set a layer as touchable and then compare the touch point with layer's bounds?

**Comment by gpeal** [comment]
@alexhorsa Yes, it would have to do some math to find the KeyPaths being touched. This hasn't been prioritized though.

**Comment by alexhorsa** [comment]
@gpeal I am new to the library, which are the position properties for KeyPaths?

**Comment by gpeal** [comment]
@alexhorsa http://airbnb.io/lottie/android/dynamic.html

**Comment by gpeal** [comment]
Closing this as it has not been a priority.
