### ISSUE TITLE
Can't pause animation when 'loop=true'

### ISSUE THREAD

**Issue by SwayChen** [airbnb/lottie-android#446]
Lottie keeps animating if `loop="true"`, and it is using CPU & Memory.

You can try this JSON: 
[unconnected.json.zip](https://github.com/airbnb/lottie-android/files/1262580/unconnected.json.zip)

**Comment by gpeal** [comment]
@SwayChen I just tried this and it works. If you can't fix it, can you reopen and attach a sample project that repros this?
