### ISSUE TITLE
Not building on Ubuntu 16.04, Studio 2.2

### ISSUE THREAD

**Issue by starship9** [airbnb/lottie-android#45]
The `LottieSample` app is not being compiled by the Studio, for some reason it asks to setup a Gradle plugin, after which it keeps showing the building dialog box indefinitely.
The same thing happened while building the `lottie` app, am I doing something wrong?

**Comment by felipecsl** [comment]
can you build from the command line with `./gradlew build`?

**Comment by saketkumar95** [comment]
@starship9 I too got this issue. Just try to wait for some time. It just takes time to build the gradle according to system. :)

**Comment by gpeal** [comment]
If you see a dialog about gradle when you open the project, use the default gradle wrapper.

I'm going to close this for now unless there is action needed.

**Comment by gpeal** [comment]
Also, when you open the project, open the root folder of the repo, not LottieSample.

**Comment by starship9** [comment]
It's working fine now, thanks so much!
