### ISSUE TITLE
Text layer position issue

### ISSUE THREAD

**Issue by RishabhTayal** [airbnb/lottie-android#451]
Here is the [json file](https://gist.github.com/RishabhTayal/a7668f67b75003fe12b852d7319f19e1). I am trying to animate a simple text layer. It works on iOS SDK and also looks good on [lottiefiles](https://www.lottiefiles.com/share/VlID5H). The final position of the text in the actual animation file is horizontally centered while in the Android it goes all the way to the right. Is this a known issue? Is there something wrong in the `json` file? Is there a fix for this?

**Comment by gpeal** [comment]
Duplicate of #388
