### ISSUE TITLE
Text Layer opacity changes not reflecting on Android app

### ISSUE THREAD

**Issue by krishnasajja** [airbnb/lottie-android#453]
[lottie_text_opacity_test.zip](https://github.com/airbnb/lottie-android/files/1278025/lottie_text_opacity_test.zip)

This is the AE file that I'm using to test. The opacity changes on text layer are not reflecting on Android app.
I see opacity changes are supported on both Android and iOS. Is opacity not supported for text layer on Android?

**Comment by krishnasajja** [comment]
@gpeal Thank you for fixing this issue. Any idea on when the fix will be released? Thanks!

**Comment by gpeal** [comment]
@krishnasajja aiming to get a release out today

**Comment by RishabhTayal** [comment]
Do you need to update the milestone and add this fix?

**Comment by gpeal** [comment]
@RishabhTayal Done. 2.2.1 is out.

**Comment by RishabhTayal** [comment]
:hooray:

**Comment by RishabhTayal** [comment]
🎉
