### ISSUE TITLE
Using ImageAssetDelagate and setImageAssetsFolder together

### ISSUE THREAD

**Issue by krishnasajja** [airbnb/lottie-android#454]
I'm trying to use Lottie with 10 static images in 'images' folder inside assets directory and 1 dynamic image, downloaded from the internet at runtime. 

If I use ImageAssetDelagate, I need to provide bitmaps for the static images as well along with the dynamic one using fetchBitmap() method. Is there a way that I can use 'setImageAssetsFolder' for all the static images and 'ImageAssetDelagate' for only the dynamic ones?

Thanks!

**Comment by gpeal** [comment]
@krishnasajja In this case, I'd recommend just doing the asset loading yourself and returning it from the image asset delegate. That way you won't incur the performance overhead of checking if the file already exists.
