### ISSUE TITLE
Static images not working within the Android Lottie app

### ISSUE THREAD

**Issue by scotchirish** [airbnb/lottie-android#456]
Whenever I try to load an animation file (that references a static image) from a json URL (or a local folder on my sd card) from within the Android Lottie app, I get the following error message:
"This animation has images and no image folder was set"

For example, attempting to load https://www.lottiefiles.com/storage/datafiles/987d763ea05b6b57a3b2362a69408947/Health%20increase.json found at https://www.lottiefiles.com/186-height-increase will result in this error message in the Android Lottie app.

The 'WeAccept.json' example within the app does work (because it's internal to the app). How do I get this to work with external json files that have static images placed within the images/ folder?

**Comment by gpeal** [comment]
@scotchirish You'll have to either compile the app with the images or add an ImageAssetDelegate to test out specific animations on lottiefiles with images.

**Comment by gpeal** [comment]
That animation shouldn't need images for the record. I think whoever made it imported the man from Illustrator and didn't convert it to a shape layer.
http://airbnb.io/lottie/after-effects/artwork-to-lottie-walkthrough.html
