### ISSUE TITLE
Lottie animation not rendered properly on Android O on my Nexus 6P

### ISSUE THREAD

**Issue by GauthierChan** [airbnb/lottie-android#457]
Since I updated to Android O from 7.1.2 on my Nexus 6P, my animation doesn't render correctly.

Here is the expected animation. It's a robot with a loader in its helmet:

![good](https://user-images.githubusercontent.com/14746791/30111814-754b3f9c-930f-11e7-897b-844a87340cf7.gif)

and here is what I see on Android O on my nexus 6P

![bad](https://user-images.githubusercontent.com/14746791/30111800-656a824a-930f-11e7-97a0-7156d35f1475.gif)

However I tested it on an emulated device running O and it ran fine.

Our designer told us that there is a problem with the masks as the bottom of both arms of the robot shouldn't appear. I can share all files by mail if needed :)

**Comment by gpeal** [comment]
@GauthierChan Yes, can you email me the aep files at lottie@airbnb.com

**Comment by gpeal** [comment]
@GauthierChan v2.2.4 is now out
