### ISSUE TITLE
LottieDrawable setComposition() doing too much on main thread

### ISSUE THREAD

**Issue by drinkthestars** [airbnb/lottie-android#459]
Hey guys, 

I'm trying to display animations on a large area of the screen, and these `.json` animation files are around `~500KB` in size. 

After using `LottieComposition.Factory.fromAssetFileName(...)` and having the `LottieComposition composition` in hand, I realized a need to to `lottieDrawable.setComposition(composition)` asynchronously on another thread because it seemed to be doing some expensive work on the main thread and causing stuttering + frame drops even before the animation showed up on the view.

Is there a way to "prepare" the `LottieDrawable` (including setting the `LottieComposition`) asynchronously, and then apply it to `LottieAnimationView` ?

Thanks!

**Comment by gpeal** [comment]
@drinkthestars Sure, you can create your own LottieDrawable and then set it on any ImageView or even a LottieImageView

**Comment by drinkthestars** [comment]
Didn't get it to work the first time since after setting the prepared `LottieDrawable` on the `LottieAnimationView`, I called `playAnimation()` on the _view_.
It only works if `playAnimation()` is called on the `LottieDrawable` that was externally set on the `LottieAnimationView` (see https://github.com/airbnb/lottie-android/issues/458#issuecomment-332919567)

**Comment by gpeal** [comment]
I, unfortunately, won't have time to do much here in the near future. I would accept PRs though.
