### ISSUE TITLE
Lint NewApi error (bug in lint?) for using LottieValueAnimator#resume 

### ISSUE THREAD

**Issue by daisy1754** [airbnb/lottie-android#462]
https://github.com/airbnb/lottie-android/commit/509da1bca7f5b363574279c9f0633c24b4ae5faa causes lint failure. It seems this is bug in lint tool (LottieValueAnimator implements `resume` but lint tool thinks it's `ValueAnimator#resume` which only exists on API 19+). 

![screen shot 2017-09-11 at 7 17 59 pm](https://user-images.githubusercontent.com/980077/30305148-196f2f88-9726-11e7-9808-5151c409f2b8.png)

**Comment by gpeal** [comment]
@daisy1754 I just need to ignore lint. I made my own ValueAnimator#resume: https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/utils/LottieValueAnimator.java#L128

**Comment by daisy1754** [comment]
Yup, please take a look on https://github.com/airbnb/lottie-android/pull/463, which suppress the lint

**Comment by gpeal** [comment]
Fixed by https://github.com/airbnb/lottie-android/pull/463
