### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by xaxup** [airbnb/lottie-android#464]
1 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.Reference.get()' on a null object reference
2 java.lang.RuntimeException:An error occurred while executing doInBackground()
3 android.os.AsyncTask$3.done(.java:330)
4 ......
5 Caused by:
6 java.lang.NullPointerException:Attempt to invoke virtual method 'java.lang.Object java.lang.ref.Reference.get()' on a null object reference
7 com.airbnb.lottie.Keyframe$Factory.newInstance(:159)
8 com.airbnb.lottie.PathKeyframe$Factory.newInstance(:26)
9 com.airbnb.lottie.AnimatablePathValue.<init>(:39)
10 com.airbnb.lottie.AnimatablePathValue.createAnimatablePathOrSplitDimensionPath(:15)
11 com.airbnb.lottie.AnimatableTransform$Factory.newInstance(:108)
12 com.airbnb.lottie.Layer$Factory.newInstance(:258)
13 com.airbnb.lottie.LottieComposition$Factory.parseLayers(:283)
14 com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(:267)
15 com.airbnb.lottie.LottieComposition$Factory.fromInputStream(:226)
16 com.airbnb.lottie.FileCompositionLoader.doInBackground(:17)
17 com.airbnb.lottie.FileCompositionLoader.doInBackground(:7)
18 android.os.AsyncTask$2.call(AsyncTask.java:316)
19 java.util.concurrent.FutureTask.run(FutureTask.java:237)
20 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
21 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
22 java.lang.Thread.run(Thread.java:776)

**Comment by gpeal** [comment]
Fixed by https://github.com/airbnb/lottie-android/commit/6669e4d41b7c3e69c7597fb7be2c5e05e9b03df7 in 2.2.3 which is now out.
