### ISSUE TITLE
Hello, I was using Lottie2.2.0 in my project on the emergence of this error, V7 package version is 25.0.0

### ISSUE THREAD

**Issue by memorycj** [airbnb/lottie-android#465]
No resource found that matches the given name (at 'icon' with value '@drawable/abc_ic_search_api_mtrl_alpha').

**Comment by gpeal** [comment]
@memorycj I'm not sure what this means. Can you post a stack trace or something?

**Comment by memorycj** [comment]
@gpeal Sorry, V7 25 package in the name of some of the documents made a change, resulting in a project inside the aar can not find the resources, not lottie problem. lottie cited in the V7 26.0.1 in China can not download ...

**Comment by gpeal** [comment]
You can follow the steps here: https://github.com/airbnb/lottie-android/issues/77

**Comment by memorycj** [comment]
@gpeal thank you
