### ISSUE TITLE
Animation do start at IOS without Android.

### ISSUE THREAD

**Issue by LxFFF** [airbnb/lottie-android#466]
@gpeal 

the [images.zip](https://github.com/airbnb/lottie-android/files/1302265/images.zip) unzip at android and iOS successful.
#260
without water 😭, 
other files were successful to show like that [paoche.zip](https://github.com/airbnb/lottie-android/files/1302320/paoche.zip)

## IOS:
![5fd97e74731b025285c165ad9ce3cb42](https://user-images.githubusercontent.com/10859832/30419471-06f71eca-9969-11e7-93cd-8ccc0d59debd.jpg)

## Android:
![7d234fb4dd381b4989d749f3f62a5261](https://user-images.githubusercontent.com/10859832/30419578-787d4d80-9969-11e7-9b1e-f10859948a49.jpg)

**Comment by gpeal** [comment]
This is what it looks like for me. If it's not correct, feel free to reopen.
![boat](https://user-images.githubusercontent.com/1307745/30491380-f2f156c8-99f1-11e7-8e74-948750b3abe2.gif)

**Comment by LxFFF** [comment]
@gpeal Think u,i'll be try again. 👍
