### ISSUE TITLE
Android version some image size problem

### ISSUE THREAD

**Issue by microink** [airbnb/lottie-android#471]
Thank you for providing such a good library.

I was in use when I encountered a problem with my compressed package in the animation, the rainbow showed incomplete, or not shown. In some large-size flat panel will show some, or a complete display, test the IOS version, and there is no such issue, whether the Android version size calculation of some problems?

I upload image always fail, you can see them on url
Android: http://url.cn/5lGQMFU
IOS: http://url.cn/5xXi701
zip source: http://url.cn/5A87yEn

my email : microink@foxmail.com

**Comment by gpeal** [comment]
@microink Can you try again with 2.2.4?

**Comment by microink** [comment]
Oh,The problem is solved and thank you very much.

But there is a problem, I use 2.1.2, directly in the same LottieView directly on the allocation of resources and then playAnim no problem, but in 2.2. * After the above android 5.0 and above must cancelAnim, and then playAnim can be normal Display animation, or only show the first frame animation, and then directly into the AnimEnd, android7.1 above version canleAnim and then palyAnim can not perform animation, after the first implementation of the animation are only the first frame and then directly into the AnimEnd Method, the following is my code, what needs to be adjusted?

`LottieComposition.Factory.fromInputStream(Sheng.getInstance(), fis, new OnCompositionLoadedListener() {
                                    @Override
                                    public void onCompositionLoaded(LottieComposition composition) {
                                        sLottieAnimationView.setVisibility(View.VISIBLE);
                                        sLottieAnimationView.setComposition(composition);
                                        sLottieAnimationView.addAnimatorListener(new Animator.AnimatorListener() {
                                            @Override
                                            public void onAnimationStart(Animator animation) {
                                            }
                                            @Override
                                            public void onAnimationEnd(Animator animation) {
                                                if (null != sLottieAnimationView) {
                                                    synchronized (sGiftNewQueue) {
                                                        if (0 == sGiftNewQueue.size()) {
                                                            sLottieAnimationView.setVisibility(View.GONE);
                                                        }
                                                        sLottieAnimationView.removeAnimatorListener(this);
                                                        sGiftNewQueue.notifyAll();
                                                    }
                                                }
                                            }

                                            @Override
                                            public void onAnimationCancel(Animator animation) {

                                            }

                                            @Override
                                            public void onAnimationRepeat(Animator animation) {

                                            }
                                        });
                                        sLottieAnimationView.cancelAnimation();
                                        sLottieAnimationView.playAnimation();`

**Comment by microink** [comment]
@gpeal

**Comment by microink** [comment]
//5.0                                       
sLottieAnimationView.cancelAnimation();
//7.0
sLottieAnimationView.reverseAnimation();
sLottieAnimationView.playAnimation();
