### ISSUE TITLE
Crash when using animation

### ISSUE THREAD

**Issue by fermuch** [airbnb/lottie-android#474]
Please see https://github.com/airbnb/lottie-react-native/issues/154

The crash happens on the latest version of lottie-android (2.2.5) and the Lottie Preview app.

Here are the files I used that caused the crash:
[Morphing icon.zip](https://github.com/airbnb/lottie-android/files/1326944/Morphing.icon.zip)

Inside there is a file called `exported.json`, which works okay with bodymovin.

**Comment by flamaniac** [comment]
Have you set path to image folder?

**Comment by gpeal** [comment]
@fermuch This doesn't crash anymore but Lottie doesn't support difference masks. You can achieve this animation with a normal shape though.

**Comment by fermuch** [comment]
Thank you @gpeal and sorry for not answering @flamaniac
