### ISSUE TITLE
animation splash a shot in the end. 

### ISSUE THREAD

**Issue by chievent** [airbnb/lottie-android#475]
my animation splashed a shot in the end. but the same json worked well in ios version and web version.
[ThumbAnim.zip](https://github.com/airbnb/lottie-android/files/1328156/ThumbAnim.zip)

**Comment by gpeal** [comment]
@chievent What's the issue exactly? What does splash a shot mean?
I recommend using a shape layer instead of a png for the thumb as well. The performance and memory will be much better.

**Comment by chievent** [comment]
the "splash" means that the alpha animation was intented from 1 to 0, but it splashed to 1 at the end

**Comment by gpeal** [comment]
I just tried your animation on master (2.3.2-SNAPSHOT) and it seems to be working great. Can you try on 2.3.1 or 2.3.2-SNAPSHOT?
