### ISSUE TITLE
animation stay in the first frame  and  can’t play

### ISSUE THREAD

**Issue by keyguan** [airbnb/lottie-android#476]
when use LottieAnimationView  play animation,the animation stay in the first frame  and  can’t play.
device params:  android version 4.4.2
DEVICE=8675-HD HARDWARE=mt6592 FINGERPRINT=Coolpad/8675-HD/8675-HD:4.4.2/KOT49H/4.4.043.P0.150802.8675-HD:user/release-keys BOARD=cp8675_t01 MODEL=Coolpad 8675-HD

![lottie_error](https://user-images.githubusercontent.com/6700343/30847887-bea9be96-a2cf-11e7-89dd-523a2c1add90.jpg)
![wechatimg380](https://user-images.githubusercontent.com/6700343/30847974-04915306-a2d0-11e7-8fc8-4dff0c01471b.jpeg)

**Comment by keyguan** [comment]
this phone use example from github is the same error.

**Comment by gpeal** [comment]
@keyguan Can you attach the animation?

**Comment by gpeal** [comment]
Please reopen this if it's still an issue on 2.2.5 and please attach the aep file.
