### ISSUE TITLE
Animation is rendered incorrectly on Android

### ISSUE THREAD

**Issue by PavelSynek** [airbnb/lottie-android#478]
I am using Lottie 2.2.5 and this animation [anim.json.zip](https://github.com/airbnb/lottie-android/files/1332671/anim.json.zip) isn't rendered properly. When opened on iOS or in web player, the mask animation follows the scanner line, but in Lottie Android app, the mask animation is twice as fast. Is there anything we can do with the animation to fix it or is the problem in Lottie?

I can send you the original AEP file if needed.

**Comment by gpeal** [comment]
@PavelSynek yeah, can you zip and attach the aep?

**Comment by PavelSynek** [comment]
Here's the aep [scanning_animation_error.aep.zip](https://github.com/airbnb/lottie-android/files/1336291/scanning_animation_error.aep.zip)
