### ISSUE TITLE
How to control the animation view's Size

### ISSUE THREAD

**Issue by wangshaolei** [airbnb/lottie-android#479]
How to control the animation view's Size, thanks~

**Comment by gpeal** [comment]
@wangshaolei Just use layout_width, layout_height and scaleType as you would with any ImageView and make sure you're on Lottie 2.2.5.

**Comment by wangshaolei** [comment]
@gpeal hi, layout_width,layout_height and scaleType is valid only on 2.2.5， i cant find about api ? thanks~

**Comment by wangshaolei** [comment]
@gpeal api address? thanks

**Comment by wangshaolei** [comment]
@gpeal api docs and address? thanks

**Comment by gpeal** [comment]
@wangshaolei These are just attributes on ImageView.

**Comment by wangshaolei** [comment]
@gpeal thanks,i see
