### ISSUE TITLE
com.airbnb.lottie.value missing

### ISSUE THREAD

**Issue by Tobias-Reich** [airbnb/lottie-android#480]
I wanted to use the dynamic properties for changing the opacity of one of my layers.

I found a DynamicPropertiesFragment file in your samples that got removed. Trying to use _com.airbnb.lottie.value.*_ also led to an error. It looks like the package is no longer included in Lottie 2.2.5
Is there any workaround currently?

**Comment by gpeal** [comment]
@Tobias-Reich It hasn't been released yet
https://github.com/airbnb/lottie-android/pull/447
