### ISSUE TITLE
Animation is not playing properly neither ios nor android 

### ISSUE THREAD

**Issue by OzgurSe** [airbnb/lottie-android#482]
I cant get the animation correctly to show up on ios and android, on exported html file the animation is fine but when I ll import it to ios first part of the animation is wrong

Don't know what i'm doing wrong!

attaching my ae file, json file and android screen grab.

 Any help would be great!

[AE-06.aep.zip](https://github.com/airbnb/lottie-android/files/1343411/AE-06.aep.zip)
[json-html.zip](https://github.com/airbnb/lottie-android/files/1343412/json-html.zip)
[ScreenVideo.zip](https://github.com/airbnb/lottie-android/files/1343413/ScreenVideo.zip)

**Comment by bijuC1983** [comment]
@OzgurSe We are facing the same issue & I am curious how you were able to get past it.

**Comment by OzgurSe** [comment]
Sorry, I don't remember how did I solved that exactly, I guess I removed mask effects.
