### ISSUE TITLE
In 2.2.5 resumeReverseAnimation() doesn't start from current progress

### ISSUE THREAD

**Issue by drinkthestars** [airbnb/lottie-android#484]
Recently updated to `2.2.5` and noticed some weird behavior with `LottieAnimationView#resumeReverseAnimation()`

Doing something like:

```
lottieAnimationView.setAnimation("animation.json")

lottieAnimationView.setProgress(0.05f)
lottieAnimationView.resumeReverseAnimation()
```

Doesn't seem to reverse the animation from `0.05f` -> `0f` , but instead reverses from `1f` -> `0f`. 

On `2.2.0` which I was using before, that code works as expected, i.e. `resumeReverseAnimation()` caused it to be played from `0.05f` -> `0f`

Sample project: https://github.com/drinkthestars/LottiePlayground 
In the sample, after changing the version to `2.2.0` it works as expected. with version `2.2.5` it reverses the whole animation

**Comment by gpeal** [comment]
Fixed by #496
