### ISSUE TITLE
Non-glyphed text support doesn't work

### ISSUE THREAD

**Issue by luciancioroga** [airbnb/lottie-android#486]
Referring to lottie 2.2.5. Even if the TextLayer class seems to support generating text without receiving the glyphs in the json, it doesn't seem to render.

**Comment by gpeal** [comment]
@luciancioroga Did you provide the font?

**Comment by luciancioroga** [comment]
@gpeal, I placed the font in assets/fonts. Without it, it crashes. However, if this is something that is implemented and not replicable for you, I can make more attempts. Thank you!

**Comment by gpeal** [comment]
@luciancioroga This seems like the expected behavior to me. If the fonts aren't glyphed then you must provide it yourself. Feel free to reopen if that's not the case.

**Comment by luciancioroga** [comment]
This is the simple text bodymotion json I use:

`{
  "v": "4.11.1",
  "fr": 29.9700012207031,
  "ip": 0,
  "op": 900.000036657751,
  "w": 1920,
  "h": 1080,
  "nm": "LottieDemo",
  "ddd": 0,
  "assets": [],
  "fonts": {
    "list": [
      {
        "origin": 0,
        "fPath": "",
        "fClass": "",
        "fFamily": "Arial",
        "fWeight": "",
        "fStyle": "Regular",
        "fName": "ArialMT",
        "ascent": 71.5988159179688
      }
    ]
  },
  "layers": [
    {
      "ddd": 0,
      "ind": 1,
      "ty": 5,
      "nm": "This is some random text",
      "sr": 1,
      "ks": {
        "o": {
          "a": 0,
          "k": 100,
          "ix": 11
        },
        "r": {
          "a": 0,
          "k": 0,
          "ix": 10
        },
        "p": {
          "a": 0,
          "k": [
            568,
            556,
            0
          ],
          "ix": 2
        },
        "a": {
          "a": 0,
          "k": [
            0,
            0,
            0
          ],
          "ix": 1
        },
        "s": {
          "a": 0,
          "k": [
            100,
            100,
            100
          ],
          "ix": 6
        }
      },
      "ao": 0,
      "t": {
        "d": {
          "k": [
            {
              "s": {
                "s": 72,
                "f": "ArialMT",
                "t": "This is some random text",
                "j": 0,
                "tr": 0,
                "lh": 86.4,
                "ls": 0,
                "fc": [
                  0.92,
                  0.92,
                  0.92
                ]
              },
              "t": 0
            }
          ]
        },
        "p": {},
        "m": {
          "g": 1,
          "a": {
            "a": 0,
            "k": [
              0,
              0
            ],
            "ix": 2
          }
        },
        "a": []
      },
      "ip": 0,
      "op": 900.000036657751,
      "st": 0,
      "bm": 0
    }
  ]
}`

I'm adding **Arial.ttf** to **assets/fonts** and load the json with:
`LottieComposition.Factory.fromAssetFileName(this, "data.json", new OnCompositionLoadedListener() {
            @Override
            public void onCompositionLoaded(@Nullable LottieComposition composition) {
                lottie.setComposition(composition);
                String warnings = "Warnings:";
                for (String warning : composition.getWarnings())
                    warnings += "\n" + warning;
                ((TextView) findViewById(R.id.lottie_debug)).setText(warnings);
            }
        });`

Text is not rendered but no warnings / errors are thrown.

Even overriding the font delegate doesn't fix it:
`lottie.setFontAssetDelegate(new FontAssetDelegate() {
                    @Override
                    public Typeface fetchFont(String fontFamily) {
                        return Typeface.SANS_SERIF;
                    }
                });`

Not sure what else I can do.

**Comment by luciancioroga** [comment]
@gpeal, do you have any idea what I'm missing in the previous code? Thank you.
