### ISSUE TITLE
Some kind of Layer Marker support available?

### ISSUE THREAD

**Issue by brian-chu-twc** [airbnb/lottie-android#487]
This is a general question.

Is there a way to put some kind of marker(s) in the AE and so we can loop or jump according to the marker inside Android?

I know https://github.com/airbnb/lottie-android/issues/415 exist but getting the frame right every time when there is a change in animation is painful. 

If, say, designer can mark in the timeline, and programmatically we can jump to there, it will save a lot of manual processing.

Thanks

**Comment by gpeal** [comment]
@brian-chu-twc Soon :)

**Comment by rosconabn** [comment]
They should add some Key frame naming and so also the time.
 I had to do this manually until now and I agree is a pain!

**Comment by mattkenefick** [comment]
Any progress on this?

**Comment by gpeal** [comment]
@mattkenefick nothing yet
