### ISSUE TITLE
Memory  occupation too large

### ISSUE THREAD

**Issue by lihb** [airbnb/lottie-android#489]
this is my code:

```
public class LottieFragment extends BaseFragment {
    Unbinder unbinder;
    @BindView(R.id.animation_view_layout)
    FrameLayout animationViewLayout;

 @BindView(R.id.start_btn)
    Button startBtn;

    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_lottie, null);
        unbinder = ButterKnife.bind(this, view);

     startBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                for (int i = 0; i < 3; i++) {
                    LottieAnimationView animationView = new LottieAnimationView(getContext());
                    FrameLayout.LayoutParams layoutParams = new FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT, FrameLayout.LayoutParams.MATCH_PARENT);
                    layoutParams.gravity = Gravity.CENTER;
                    animationViewLayout.addView(animationView, layoutParams);
                }

            }
        });
        return view;
    }
 @Override
    public void onDestroyView() {
        super.onDestroyView();
        if (unbinder != null)
            unbinder.unbind();
    }
}
```

I just add 3 LottieAnimationView in the view and don't do anything. the memory is as below:

![222222222](https://user-images.githubusercontent.com/3703252/31381548-748e392c-ade7-11e7-9451-977f7dd5b4f1.png)

how can reduce the memory occupation.

**Comment by gpeal** [comment]
@lihb How large is your json file?

**Comment by lihb** [comment]
@gpeal The size of json file is 87kb. but I think it's dosen't matter with ths json file because I didn't set the json file to the LottieAnimationView. I just add three LottieAnimationView to the layout file.

**Comment by gpeal** [comment]
@lihb Can you attach a sample project that repros this?
If you haven't even set the animation yet, my guess is that there is something else going on that's not Lottie related.

**Comment by gpeal** [comment]
@lihb bump

**Comment by gpeal** [comment]
My guess is that this memory comes from something other than Lottie. If you attach a sample project that still repros this on 2.3.0, please reopen.
