### ISSUE TITLE
The elements of the animation change their position when I am running the animation on an Android device

### ISSUE THREAD

**Issue by victorboieru** [airbnb/lottie-android#490]
I'm trying to use this animation 
[data.json.zip](https://github.com/airbnb/lottie-android/files/1372387/data.json.zip), but it doesn't work as I expected. In Lottie Preview web page it is running as I want, but when I'm trying to use it on my Android app  the elements of the animation are not placed on the center of the view. I can attach a screenshot of my Android app.

![screenshot_2017-10-10-18-18-59](https://user-images.githubusercontent.com/32678008/31394833-ffe5ca3a-ade7-11e7-9e27-9825e6795f68.png)

For showing the animation I am using this code:

<com.airbnb.lottie.LottieAnimationView
                      android:id="@+id/lootie"
                      android:layout_width="wrap_content"
                      android:layout_height="wrap_content"
                      app:lottie_fileName="data.json"
                      app:lottie_autoPlay="true"
                      app:lottie_loop="true"
                      android:layout_gravity="center"/>

Can anyone help me with this issue?
Thnak you.

**Comment by gpeal** [comment]
@victorboieru Can you attach the aep?

**Comment by victorboieru** [comment]
Here is the aep file.
[171024_WLAN-Scan.aep.zip](https://github.com/airbnb/lottie-android/files/1410399/171024_WLAN-Scan.aep.zip)

**Comment by fengmingye** [comment]
same issue as I'm now encountering, have you resolved it?

**Comment by victorboieru** [comment]
No, I haven't resolved yet.

**Comment by gpeal** [comment]
I'm looking on to it.

**Comment by gpeal** [comment]
@victorboieru Lottie doesn't support expressions.
