### ISSUE TITLE
LottieValueAnimator#playAnimation(float, float) should queue a lazy composition task

### ISSUE THREAD

**Issue by asuszek** [airbnb/lottie-android#492]
If you call playAnimation(float, float), it only updates the float values without updating the min or max values. This means if it's called before the composition is loaded, once it is loaded it will overwrite the current float values with min and max (0 and 1).

It seems like this method should add a lazy composition task the way the other play methods do.

**Comment by gpeal** [comment]
This will be fixed as a side effect of #496
