### ISSUE TITLE
 lottie-android support  animation type? why not run

### ISSUE THREAD

**Issue by jiyewushen** [airbnb/lottie-android#501]
* Expect effect
![6666](https://user-images.githubusercontent.com/16441451/31814238-92622176-b5bb-11e7-979b-a56542023890.gif)
* Actual effect
  * it can show ，but not run
  * 666.aep can run
* [file is here](https://github.com/airbnb/lottie-android/files/1401431/file.zip)

thanks!

**Comment by gpeal** [comment]
Lottie doesn't support difference masks. Your animation will be more performant if you use shapes instead of masks as well.
