### ISSUE TITLE
Lottie Transition in Android 

### ISSUE THREAD

**Issue by AndroidAuth** [airbnb/lottie-android#503]
Salutations,
I have a question reguarding the transitioning when it comes to lottie, is it possible that
there is a version that meets the iOS View Controller Transitioning in android ? 
would love to know more about it, or if it exists would love some documentation , thank you ! 
P.S : I love your work.

**Comment by gpeal** [comment]
@AndroidAuth @buba447 and I have spoken about it but I haven't figured a good analogous set of Android APIs to use. The Transition/window animation APIs don't seem to map as well.
Do you have any suggestions for what the API might look like?

**Comment by gpeal** [comment]
I'm going to close this for now since I'm unlikely to implement this in the near future. If you'd like to propose an API and maybe work on a PR for it, feel free to reopen it.
