### ISSUE TITLE
Request for getFrame/setFrame on the LottieAnimationView

### ISSUE THREAD

**Issue by gshysun** [airbnb/lottie-android#506]
Similar to the set/getProgress, it would be beneficial to have frame accurate setter/getters. Right now I work around this by using duration/progress to get the same effect.

Thanks,
Shyam

**Comment by gpeal** [comment]
@gshysun This actually helped uncover a bug :) I'll release this soon.

**Comment by gshysun** [comment]
I have a bug on the same lines to report (may be you found the same too :) but I will point it out here just in case.

I think there is an off by one error in the frame book keeping, you guys are likely missing a frame? (eg. for the following it should be inclusive right?). 
```
public long getDuration() {
        long frameDuration = this.endFrame - this.startFrame;
        return (long)((float)frameDuration / this.frameRate * 1000.0F);
    }
```

it should be 
```this.endFrame - this.startFrame + 1``` ?

I have not dug into other parts of the code, but for my work, I have my own wrappers apis (implemented using ```progress```)  for ```getCurrentFrame``` and ```setStartFrame``` and by adding +1 I am able to achieve frame accurate setter.

Hope it helps!

Thanks,
Shyam
