### ISSUE TITLE
Where i can finde appcompat-v7-26.1.0.jar??

### ISSUE THREAD

**Issue by phantoxe** [airbnb/lottie-android#509]
Hi Folks... i m trying use a Lottie in my project... in a MacOs with React-Native.

But i need this dependencie to work. Can u help me?

![captura de tela 2017-11-04 as 12 12 51](https://user-images.githubusercontent.com/29681268/32406199-084ca01e-c15b-11e7-83e9-0ed576cdd9b8.png)

**Comment by gpeal** [comment]
Add 
```
maven {
  url "https://maven.google.com"
}
```
to your project build.gradle.
This isn't a lottie specific issue.
