### ISSUE TITLE
Letters disappears on changing the screen orientation in FontActivity of Sample App

### ISSUE THREAD

**Issue by saketkumar95** [airbnb/lottie-android#51]
Currently when the screen orientation is changed then the letters written disappears.

Expected that letters should not disappears on changing the orientation. :)

**Comment by gpeal** [comment]
I think I may just lock the orientation to portrait ;)

**Comment by saketkumar95** [comment]
Can i fix this ??

**Comment by gpeal** [comment]
@saketkumar95 sure, go for it :)

**Comment by the-dagger** [comment]
Maybe saving the letters entered to bundle and restoring them is a better idea? @gpeal

**Comment by saketkumar95** [comment]
@the-dagger Yeah i too thought of that only but @gpeal said to lock the orientation so created the PR for that. :)

**Comment by gpeal** [comment]
@the-dagger Yeah that would definitely work too. I don't see any need for the sample app to be landscape anyways so that seemed like a simpler fix :)

**Comment by the-dagger** [comment]
Alright, makes sense. :)
