### ISSUE TITLE
API changes report for the latest snapshot of Lottie

### ISSUE THREAD

**Issue by lvc** [airbnb/lottie-android#511]
Hi,

I'd like to share report on API changes and backward compatibility for the Lottie library: https://abi-laboratory.pro/java/tracker/timeline/lottie/

BC — binary compatibility
SC — source compatibility

The report includes analysis result for the latest snapshot of the library from https://oss.sonatype.org/content/repositories/snapshots/com/airbnb/android/lottie/.

The report is generated according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2 by the https://github.com/lvc/japi-tracker tool.

Hope it will be helpful for users and maintainers of the library.

Thank you.

![lottie-1](https://user-images.githubusercontent.com/1517837/32411947-e9059acc-c1f9-11e7-9d83-c918a4d0414a.png)

![lottie-2](https://user-images.githubusercontent.com/1517837/32411951-0d002e1a-c1fa-11e7-9dfb-4cca841d03d1.png)

**Comment by gpeal** [comment]
Thank you for this information!
