### ISSUE TITLE
Can LottieAnimationView use compressed json in assets?

### ISSUE THREAD

**Issue by twlkyao** [airbnb/lottie-android#514]
The size of json file may be large, will there be an `API` that can set compressed files as the content of the `LottieAnimationView`, now I can achieve this manually, but the implements of others may be differ, so I tend there will be an unified `API`.

**Comment by gpeal** [comment]
@twlkyao Depending on the compression method, you should handle any sort of decompression yourself. You can then pass the decompressed version to Lottie.
