### ISSUE TITLE
Lottie play animation does not work in android 7.0 (26.0.1)

### ISSUE THREAD

**Issue by mitko9000** [airbnb/lottie-android#516]
Hello I downloaded the demo app on android 7 and the animation just shift from start to end without animating anything only when I go threw with the slider everything is ok and I can see some frame changing but by calling playAnimation or hit the play button nothing is happening ?

**Comment by gpeal** [comment]
@mitko9000 Can you attach a project that reproduces this? There isn't enough information to act on here.

**Comment by mitko9000** [comment]
@gpeal it turns out that somehow I dissabled animation from the development menu which was the reason this not to work, sorry to bother.
False alarm
