### ISSUE TITLE
LottieAnimationView not displayed because it is too large to fit into a software layer (or drawing cache), needs 8644320 bytes, only 8294400 available

### ISSUE THREAD

**Issue by maoqis** [airbnb/lottie-android#517]
LottieAnimationView not displayed because it is too large to fit into a software layer (or drawing cache), needs 8644320 bytes, only 8294400 available

**Comment by maoqis** [comment]
it is work when memory is enough。when memory is not enough，it is not work。
i do not know why has such warning and not work。
why the usable memory is not increased when memory is not enough？
the log is printed in View.

**Comment by maoqis** [comment]
![image](https://user-images.githubusercontent.com/3467849/32656481-edb6db1a-c64c-11e7-8a44-173046ec76b6.png)

**Comment by gpeal** [comment]
@maoqis After Effects sizes in px get converted to dp. You can either a) make the composition size smaller in after effects, b) use the `setScale` api or c) call `useHardwareAcceleration()`

**Comment by maoqis** [comment]
thanks,I set Lottie view layout size
smaller in scrollview.
