### ISSUE TITLE
bitmap handle

### ISSUE THREAD

**Issue by maoqis** [airbnb/lottie-android#520]
it is bad load bitmap in main thread . at view ondraw() . 
bitmap cache may be used gilde 。

**Comment by gpeal** [comment]
@maoqis Can you be more specific? Bitmaps are fetched once and then cached by the ImageAssetManager.

I also can't introduce any transitive dependencies such as Glide.

**Comment by maoqis** [comment]
Bitmaps are fetched once in main thread or background Thread ？

**Comment by maoqis** [comment]
and bitmap cache has not biggest size。must combine with the bitmap cache of app。

**Comment by gpeal** [comment]
@maoqis I'm still not sure I understand the issue.
