### ISSUE TITLE
OutOfMemoryError when loading  JSON animation on  OZZY phone

### ISSUE THREAD

**Issue by LoveMyBaby** [airbnb/lottie-android#521]
the same as(JSON is 680 KB): [https://github.com/airbnb/lottie-android/issues/39](url), any solution?

log:
Caused by java.lang.OutOfMemoryError:
java.util.ArrayList.<init> (ArrayList.java:75)
com.airbnb.lottie.ci$a.a (ci.java:141)
com.airbnb.lottie.ci$a.b (ci.java:101)
com.airbnb.lottie.n.a (n.java:54)
com.airbnb.lottie.n.a (n.java:32)
com.airbnb.lottie.h$a.a (h.java:37)
com.airbnb.lottie.cn$a.a (cn.java:41)
com.airbnb.lottie.ck.a (ck.java:31)
com.airbnb.lottie.ck$a.b (ck.java:68)
com.airbnb.lottie.ck$a.a (ck.java:58)
com.airbnb.lottie.ck.a (ck.java:19)
com.airbnb.lottie.bf$a.a (bf.java:275)
com.airbnb.lottie.bg$a.a (bg.java:283)
com.airbnb.lottie.bg$a.a (bg.java:267)
com.airbnb.lottie.bg$a.a (bg.java:226)
com.airbnb.lottie.ag.a (ag.java:17)
com.airbnb.lottie.ag.doInBackground (ag.java:7)
android.os.AsyncTask$2.call (AsyncTask.java:287)
java.util.concurrent.FutureTask.run (FutureTask.java:234)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1080)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:573)
java.lang.Thread.run (Thread.java:838)

**Comment by gpeal** [comment]
@LoveMyBaby Closing this in favor of #10. It is on my roadmap to take another look at this though

**Comment by LoveMyBaby** [comment]
@gpeal 
 Crashes still occur after I update to 2.3.1-SNAPSHOT( Samsung Galaxy Note2 2048MB RAM, Android 4.4).
  crash log:        
  at java.lang.AbstractStringBuilder.enlargeBuffer (AbstractStringBuilder.java:94)
  at java.lang.AbstractStringBuilder.append0 (AbstractStringBuilder.java:124)
  at java.lang.StringBuilder.append (StringBuilder.java:271)
  at java.io.BufferedReader.readLine (BufferedReader.java:414)
  at com.airbnb.lottie.e$a.a (rewardServerURL:248)
  at com.airbnb.lottie.e$a.a (rewardServerURL:228)

**Comment by gpeal** [comment]
@LoveMyBaby Nothing has changed. Meant to link to #39 though.
