### ISSUE TITLE
New method boolean isInReverseMode()

### ISSUE THREAD

**Issue by DenisMondon** [airbnb/lottie-android#522]
Hello :)

I was wondering if you can add a method name `boolean isInReverseMode()` for example.
It would be great :)
Thanks a lot!

Tested with Lottie v2.2.5

Denis

**Comment by fabionuno** [comment]
Hi Denis. You can check if the `getSpeed()` value is less than zero to know if animation is playing backwards.
Will this help you?

**Comment by gpeal** [comment]
@DenisMondon @fabionuno Correct. Reverse just calls `setSpeed(-getSpeed())`
