### ISSUE TITLE
playAnimation(startFrame, endFrame) briefly shows endFrame at beginning, causing flicker

### ISSUE THREAD

**Issue by JensBoeykens** [airbnb/lottie-android#523]
lottie version 2.2.5

Code below switches to a new animation composition after a looped animation, and starts playing from frame 30, until frame 50.
However, when running this code, the last frame (50) briefly pops up, before frame 30 is shown. This causes the animation to flicker.

```
fun onAnimationRepeat(animation: Animator?) {

                switchAnimationComposition?.let {
                    clearAnimation()
                    progress = 0F 
                    setComposition(it)         
                    loop(false)
                    playAnimation(30, 50)
                 }
}
```

**Comment by JensBoeykens** [comment]
The issue above can be recreated every time. Using post seems to help a bit:

`post { playAnimation(30, 50) }`

With post the problem happens only now and then, apparently at random. So I still need a proper solution for this.

**Comment by gpeal** [comment]
@JensBoeykens Can you try this wit `2.3.0` using the setMinAndMaxFrame API followed by playAnimation?

**Comment by gpeal** [comment]
@JensBoeykens If it still repros, can you attach the animation/

**Comment by gpeal** [comment]
@JensBoeykens This API no longer exists in 2.3.0. Can you try it with 2.3.0 using setMinAndMaxFrame followed by playAnimation?

**Comment by JensBoeykens** [comment]
Doesn't help. But I'll try a workaround using 2 views. Hide view1 and show view2 to switch animations, instead of setting a different file/composition on a single view

**Comment by ityancs** [comment]
I also find this problem in 2.3.1-SNAPSHOT

**Comment by Dsudzy** [comment]
Im having the same problem, not sure why this was closed. When I call the function `anim.playSegments([[1,2], [3, 4]], true);` when I play another segment say `anim.playSegments([5,6], true);`  it plays the 3,4 frames quickly before playing the next segment 5,6.
