### ISSUE TITLE
2.2.5bug ,setImageAssetDelegate not work good

### ISSUE THREAD

**Issue by walkthehorizon** [airbnb/lottie-android#526]
animationView.setImageAssetDelegate(new ImageAssetDelegate() {
  @Override public Bitmap fetchBitmap(LottieImageAsset asset) {
    // Your bitmap fetching code
  }
});
I am now using the 2.2.0 version of Json, if I have four pictures, when I first through the setImageAssetDelegate method for Lottie images, fetchBitmap method in asset asked me to provide img_0, img_1, img_2, img_3 these pictures, when I was second times for the same Lottie call setImageAssetDelegat, fetchBitmap method start from img_0, but the 2.2.5 version in second after a call to the setImageAssetDelegate method is img_4 from the beginning, which leads to the error

**Comment by gpeal** [comment]
@walkthehorizon I don't understand the issue. Can you explain it again and attach an animation that reproduces it?

**Comment by walkthehorizon** [comment]
`       mLottieView.setImageAssetDelegate(new ImageAssetDelegate() {
            @Override
            public Bitmap fetchBitmap(LottieImageAsset asset) {
                Bitmap bitmap = BitmapFactory.decodeFile(GiftUtil.getJsonFileDir(mCurrentZipName , mGiftType) + "/images/" + asset.getFileName(), options);
                if (bitmap == null) {
                    LogUtils.e(TAG, "GiftType: "+mGiftType +"  FullScreenGiftView Lottie 加载json图片资源失败：" + asset.getFileName());
                }
                return bitmap;
            }
        });`
I dynamically load the resource pictures in the way above.
I suppose there are two JSON files A and B, they all need 3 pictures, when I first went to use this way to load A, asset.getFileName were img_0, img_1, img_2, but when the second time I use the same LottieView and reset the setImageAssetDelegate to load B, asset.getFileName return img_3, img_4 so, img_5, error loading, I think when I use the same Lottie (different JSON files) again when loading the B should return img_0, img_1, img_2.

**Comment by gpeal** [comment]
@walkthehorizon Can you attach a sample project that reproduces this? Lottie caches the images once you have provided them once. You can call `updateBitmap` if you need to clear or change it.

**Comment by gpeal** [comment]
@walkthehorizon bump

**Comment by walkthehorizon** [comment]
ok，i will try it too and attach a sample project in the future，

**Comment by gpeal** [comment]
If there is anything actionable here, feel free to reopen.
