### ISSUE TITLE
stroke dash animates fine on web, not on ios/android

### ISSUE THREAD

**Issue by evanfuture** [airbnb/lottie-android#529]
* **Android Version:** Tested on 8, need to support 6+
* **After Effects Version:** CC 2017

**What did you do? Please explain the steps you took before you encountered the problem.**
exported from AE, other files from lottiefiles work fine.

**What did you expect to happen?**
![cap-ok](https://user-images.githubusercontent.com/2659994/32890901-beddb004-cae1-11e7-8ad2-b6c5c35a2309.gif)
This is more or less how it should look.  Spinner should repeat properly.

**What actually happened? Please include as much _relevant_ detail as possible.**
So, I built a loader, and exported to json.  It plays fine in the web player.  But using it on mobile there are two problems.

## iOS: 
![cap-ios](https://user-images.githubusercontent.com/2659994/32890921-d0ce4292-cae1-11e7-9aaa-04acb8e47252.gif)
The first time through, the animation works fine, after that the Dash doesn't seem to make it back to 0, and it just keeps repeating like that.  I've tried adding keyframes at the end of the file to jump it back before it repeats, but that didn't change anything.

## Android:
![cap-android](https://user-images.githubusercontent.com/2659994/32890997-0c238852-cae2-11e7-8f95-4c49c37ff710.gif)
The first part of the animation is just fine, but the 2nd part seems to get all weird and play twice as fast.

I'm wondering if there's anything you can spot that's wrong with the AE file, or the JSON.  It's baffling to me.

**Please provide a download link to the After Effects file that demonstrates the problem.**
attached: 
[Archive.zip](https://github.com/airbnb/lottie-android/files/1481367/Archive.zip)

**Comment by gpeal** [comment]
@evanfuture I took a quick look. I think you'll have more success achieving this with trim path start/end rather than dash + offset. I'll still look in to this though.

**Comment by evanfuture** [comment]
Trim Paths worked great!  Thank you for the suggestion.  I'll leave the issue open, because there's bound to be others using stroke/offset animations down the line.

**Comment by gpeal** [comment]
This seems to be working on master now
![dash](https://user-images.githubusercontent.com/1307745/33636719-4da03d3a-d9d2-11e7-8c40-467b71ce7cac.gif)
