### ISSUE TITLE
Feature Request Pull To Refresh

### ISSUE THREAD

**Issue by timrijckaert** [airbnb/lottie-android#531]
Hi, 

I have a feature request for another custom view you guys could provide in this great lib, for both iOS and Android.
This view will aid to emphasize your brand to your app as will it be something that helps to let your app stand out from the rest.     
Namely a custom pull to refresh layout.  It could conveniently be named `LottieSwipeRefreshLayout`.  

We actually already provide such view in our app.  
Source code of this view, albeit slightly modified one, can be found on my [Github](https://github.com/timrijckaert/LottieSwipeRefreshLayout)
However this code is sub-optimal since it produces some crashes in our app at least for Android and it proved to be a big challenge to get all these touch listeners to work in sync.

![screenshot from 2017-11-20 00 31 29](https://user-images.githubusercontent.com/6739443/32996973-303949ca-cd8a-11e7-945e-6763001193d3.png)

# Features:
- A custom pull to refresh view that takes a `LottieView` as a drawable that will be displayed once the user has pulled to a certain threshold. 
- We also call the `.setProgress()` method in sync with this threshold.  

![giphy](https://user-images.githubusercontent.com/6739443/32996781-d4df2d76-cd87-11e7-8fc7-0587a07078f7.gif)

In this fashion it would be very easy to swap these out occasionally for certain events like Christmas.

![preview](https://user-images.githubusercontent.com/6739443/32996947-d35b8790-cd89-11e7-9663-34fa1bb7c3ba.gif) 

Sorry for this long colorful post.   
Thanks

Tim

**Comment by gpeal** [comment]
@timrijckaert Thanks for the details explanation with example. Although I think this would be out of scope of the lottie library itself, I would accept a PR to the Lottie sample app that implements this as a demo of what Lottie can do. The Lottie Sample app is already Kotlin too :)
