### ISSUE TITLE
Animation component not placed correctly

### ISSUE THREAD

**Issue by IonutNegru87** [airbnb/lottie-android#535]
Hello,

I have an issue with an lottie animation which is rendered correctly on any preview tool but in Android application it is not.
The issue is that a part of animation is not placed correctly in it's center. It seems like it is not centered.

I have attached the zip containing the json data for the animation.
I have added a screen shot with how the animation looks on a real Android device (Samsung S6).

I have struggled with this issue for a few weeks trying different approaches for the animation, different Android implementations. The results were always wrong.

[data (2).zip](https://github.com/airbnb/lottie-android/files/1496248/data.2.zip)
![device-2017-11-22-161536](https://user-images.githubusercontent.com/7695951/33131834-7087c2c8-cfa0-11e7-8eb7-f1f1ab02ee9c.png)

LE: I have also checked it with LottiePreview app and the result is the same: https://play.google.com/store/apps/details?id=com.lottiefiles.sampler&hl=ro&rdid=com.lottiefiles.sampler

**Comment by esiek** [comment]
+1

**Comment by neugartf** [comment]
+1

**Comment by neugartf** [comment]
There might be an issue with the sketch2ae plugin.

**Comment by gpeal** [comment]
@IonutNegru87 @esiek @neugartf This animation has expressions which lottie doesn't support on Android or iOS.

**Comment by IonutNegru87** [comment]
Hello @gpeal,

I have looked at the animation and couldn't identify expressions. Can you please let me know which expressions did you identify? 
Also, do you think there could be an issue with the plugin exporting the `json` file?

Thank you.

**Comment by gpeal** [comment]
@IonutNegru87 
![image](https://user-images.githubusercontent.com/1307745/33296522-02d407ba-d391-11e7-8164-bb4a89762c67.png)

**Comment by gpeal** [comment]
(p sets the position of a transform)

**Comment by IonutNegru87** [comment]
@gpeal 
Thank you very much for your help. 

I've removed the `"x"` from that `"p"`, but the animation is the same.
Do I have to remove all the `"p"` keys?

**Comment by HauLuu** [comment]
Sorry, but may I ask what is it mean by removing the expression? I'm facing a familiar issue and have no idea what you guys talking about. Could you please add more details about "removing the expression"? It this something that a have to do in AE project?

**Comment by gpeal** [comment]
@HauLuu Lottie Android doesn't support After Effects Expressions
https://airbnb.io/lottie/#/supported-features
https://helpx.adobe.com/after-effects/how-to/animating-with-expressions.html
