### ISSUE TITLE
Can't animate images from assets with setImageAssetsFolder

### ISSUE THREAD

**Issue by IT--boy** [airbnb/lottie-android#536]
use compile 'com.airbnb.android:lottie:2.3.0' , setImageAssetsFolder  no use  

project demo address :--  svn://gitee.com/zhanshisu/cartoonDemo

**Comment by gpeal** [comment]
@IT--boy Can you attach a sample project that repros this?

**Comment by IT--boy** [comment]
such https://github.com/IT--boy/CartoonDemo?

**Comment by IT--boy** [comment]
very sorry,i solve this problem,the path is wrong... ”demo/“  change  ”images/demo/“

**Comment by gpeal** [comment]
@IT--boy Is this an iOS issue? If so, please close this and open an issue on lottie-ios

**Comment by IT--boy** [comment]
thank you
