### ISSUE TITLE
A beginner's help

### ISSUE THREAD

**Issue by heyleon** [airbnb/lottie-android#539]
when I add this :
compile 'com.airbnb.android:lottie:2.3.0'
and sync my project,the android studio has been like this:
![facebook20171127161750](https://user-images.githubusercontent.com/19371845/33256781-a10a00d6-d38e-11e7-9392-191470da0da1.png)
and  how is going on?

**Comment by heyleon** [comment]
and I saw the closed issues ,add this:
maven { url 'https://maven.google.com' }
unfortunately live in China,the Great Firewall blocked that,
and are there any alternatives?

**Comment by gpeal** [comment]
This is not lottie related. You'll need the support library yourself but if you want to provide it some other way, you can do `compile ('com.airbnb.android:lottie:2.3.0'){ exclude group: 'com.android.support' }`
