### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by mhdtouban** [airbnb/lottie-android#544]
Our crashlytics reported this issue:
Device : Android 4.4.2
- smartphone HTC Desire 820G PLUS dual sim
Stacktrace : com.airbnb.lottie.CompositionLayer. (SourceFile)
com.airbnb.lottie.LottieDrawable.buildCompositionLayer (SourceFile:189)
com.airbnb.lottie.LottieDrawable.setComposition (SourceFile:155)
com.airbnb.lottie.LottieAnimationView.setComposition (SourceFile:370)
com.airbnb.lottie.LottieAnimationView$2.onCompositionLoaded (SourceFile:335)
com.airbnb.lottie.FileCompositionLoader.onPostExecute (SourceFile:21)
com.airbnb.lottie.FileCompositionLoader.onPostExecute (SourceFile:7)

**Comment by gpeal** [comment]
Duplicate of #524
