### ISSUE TITLE
Gradients with transparency

### ISSUE THREAD

**Issue by parfagerberg** [airbnb/lottie-android#547]
Hey,

Looking for a way of exporting gradients with transparency in it. The gradient with 0% opacity in one end and 100% in the other end, white colors, it turns black in the exported version/previewing it locally.

Is it possible with some sort of workaround or any other ideas?

**Comment by gpeal** [comment]
@parfagerberg Save your composition before hitting export. Gradients are the only thing that require saving before exporting. Reopen if this doesn't fix it.

**Comment by parfagerberg** [comment]
Sorry, saved and made a new export - same result as before.

**Comment by gpeal** [comment]
Can you attach the aep?
