### ISSUE TITLE
Animation Not same as iOS and web.

### ISSUE THREAD

**Issue by happymario** [airbnb/lottie-android#552]
I make one json file for lottie animation.

It works on iOS and android, web.
But it had not same result for display.

iOS and web is same, but android showed first black line in first position animation.

My json file is:
https://www.lottiefiles.com/share/tgvRxz

It is android sdk issue. 

Why is it? How can I resolve it?

**Comment by gpeal** [comment]
@happymario Can you attach an aep? If you don't want to attach the entire thing, you can attach one with just the X.

**Comment by happymario** [comment]
Thank you for your response.
My file is attached below. You can check it on android and iOS. iOS result
is ok, but android is not same with good result.
I've already attached it with url.

Thank you.

**Comment by gpeal** [comment]
@happymario Email attachments don't go through. Please attach it as a zip to the issue.

**Comment by happymario** [comment]
sure.

**Comment by happymario** [comment]
https://www.lottiefiles.com/share/tgvRxz


Did you resolve it?

**Comment by gpeal** [comment]
@happymario Can you attach the aep as a zip file? Looking at the json, the X shape has a trim path with a static start value of 0 and end value of 100 so this is actually what I would expect to see.

**Comment by maozleta** [comment]
Hi, How did you resolve this issue? 
I have the same problem, in iOs and web, Json animation looks fine, but in Android appears a little blink. 
I'm using 2.2.5 library version, with 2.5.0 animations go too slow.

**Comment by gpeal** [comment]
@maozleta 2.5.0 shouldn't have a performance regression per-se but you may be affected by https://github.com/airbnb/lottie-android/issues/647

I think I'm going to switch it back to default to 60fps for the next release

**Comment by gpeal** [comment]
@maozleta Every animation is different. Can you open an new issue and attach your animation?

**Comment by maozleta** [comment]
@gpeal ok, thanks.

**Comment by maozleta** [comment]
@gpeal by the way, in 2.5.0 the blink effect dissapears.

**Comment by gpeal** [comment]
@happymario You didn't attach the aep file. I'll need that to debug it.

**Comment by happymario** [comment]
Yes.
It showed it. I attached. 
[tgvRxz.zip](https://github.com/airbnb/lottie-android/files/1775683/tgvRxz.zip)

**Comment by happymario** [comment]
iOS result is not same with android.

**Comment by gpeal** [comment]
@happymario You still didn't attach the aep

**Comment by YaweiWang** [comment]
I have the same problem，when I improve the version to 2.2.4， the  problem fixed.

**Comment by gpeal** [comment]
Closing until you attach the aep.

**Comment by sheon** [comment]
This is now happening again!!! The animation on iOs/Web is different from the android...
I am using lottie files player!
