### ISSUE TITLE
Setting setMinAndMaxProgress for a second time does nothing on versions below 8.0

### ISSUE THREAD

**Issue by RobertoIDL** [airbnb/lottie-android#555]
Hi,

First of all thanks for a great library. 

The problem seems to happen on versions of Android below 8.0. I have an animation of a progress bar, I do cicles to animate from A to B until I run out of points.

This works fine on Android 8.0 and above but below it does not throws errors but the second iteration does nothing.

I call this again:

                levelBar.setProgress(progresoActual);
                levelBar.setMinAndMaxProgress(progresoActual, progresoFinal);

With new values, for example 0 and 0.3 and I can't see the animation at all. I make sure I also reset min and max from previous iteration to avoid crashes, so by default I put them on 0 and 1 before doing anything else.

All works well on my Nexus 5x but in any other device with older Android it does not.

Any help is more than welcome

**Comment by gpeal** [comment]
@RobertoIDL Lottie for Android doesn't support expressions.

**Comment by BenSchwab** [comment]
Hi @RobertoIDL! 

I think I can reproduce the issue a form of this issue, but need a little more information from you to make sure it's the same thing.

So from my understanding you are gradually increasing the portion of the animation you show? i.e. you start from `0 to .1` then `0 to .2` and so on? Do you happen to be changing the animation in a call to `onAnimationEnd`?

**Comment by gpeal** [comment]
@RobertoIDL This API has been deprecated in 2.5.0. I'm going to release an rc today. Can you try it again and reopen if there is still an issue?

**Comment by mateusgrb** [comment]
@gpeal any ETA for 2.5.0?
