### ISSUE TITLE
Animation not playing in Android

### ISSUE THREAD

**Issue by akkichaudhary29** [airbnb/lottie-android#556]
I have exported json file by using Bodymovin extension, and when i am uploading that json file into Lottie Preview, then it's working, but in android it's not working. 

Here is the link of my file
[https://www.lottiefiles.com/share/qqRsBP](url)

also here is my android source code 

In XML

` <com.airbnb.lottie.LottieAnimationView
        android:id="@+id/animation_view"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        android:layout_above="@+id/linearLayoutBottom"
        app:lottie_autoPlay="true"
        app:lottie_fileName="data.json"
        app:lottie_loop="true" />`

IN Kotlin

`  animation_view.setAnimation("data.json")
        animation_view.setImageAssetsFolder("images/")
        animation_view.loop(true)
        animation_view.playAnimation()`

Please help me whats going wrong with me.
Thank you

**Comment by gpeal** [comment]
@akkichaudhary29 Lottie doesn't support expressions on Android.
