### ISSUE TITLE
why the shapes does not show correct on json file ?

### ISSUE THREAD

**Issue by rezapordel** [airbnb/lottie-android#557]
I import vector files as "ai" format to after effect,then "create shape from vector layers" and render by bodymovin plugin but show the file like this picture,whats rong?
![photo_2017-12-10_12-52-44](https://user-images.githubusercontent.com/34413210/33803791-4c2280ba-ddad-11e7-9924-93244ee554d5.jpg)

my design is this:
![page21](https://user-images.githubusercontent.com/34413210/33803793-5741c6a4-ddad-11e7-997a-310bf09f55ae.jpg)

**Comment by gpeal** [comment]
@rezapordel Sometimes the conversion uses merge paths which you have to explicitly enable (with `enableMergePathsForKitKatAndAbove()`). You can also call `getWarnings()` to see if it lists anything on the Android side.

Sometimes the ai auto conversion needs some massaging because it's not perfect.

If you reopen this, please attach an aep file to reproduce this with.

**Comment by jishinhv** [comment]
Hey @gpeal, seeing a similar issue with a couple of Lottie files we have even with `enableMergePathsForKitKatAndAbove` set to `true` on `com.airbnb.android:lottie:5.0.3`. 
The preview looks fine when loaded on https://lottiefiles.com/preview but breaks on android.

This is how the animation is supposed to look
![Screenshot 2022-04-12 at 9 13 37 PM](https://user-images.githubusercontent.com/97527517/163156898-0e75d326-c6f6-405a-908c-d0ba2baa1b81.png)

but this is how its rendered on android, notice the missing handle and fill for the magnifying glass
![Screenshot 2022-04-12 at 9 13 22 PM](https://user-images.githubusercontent.com/97527517/163157393-99678dc4-9a4c-45a6-a27c-56f7e8a9da69.png)

This log is also still printed after enabling the merge paths.
```
LOTTIE: Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().
```

Let me know if you want me to open a new issue instead.
