### ISSUE TITLE
Animation on android glitchy in comparison with web sample

### ISSUE THREAD

**Issue by evatamanitsa** [airbnb/lottie-android#558]
Xml code of the view:
```
<com.airbnb.lottie.LottieAnimationView
        android:id="@+id/animation"
        android:layout_width="match_parent"
        android:layout_height="240dp"
        app:lottie_autoPlay="false"
        app:lottie_loop="false"/>

```
Animation is played programmatically:

```
fun playAnimation() {
        animation.apply {
            cancelAnimation()
            progress = 0F
            playAnimation()
        }
    }
```

Tested with fallowing versions of sdk and got the same result:

- implementation 'com.airbnb.android:lottie:2.2.5'
- implementation 'com.airbnb.android:lottie:2.3.1'

Animation resources:
[anim.zip](https://github.com/airbnb/lottie-android/files/1548007/anim.zip)

**Comment by evatamanitsa** [comment]
Thanks! When will you release new library with that fix?

**Comment by gpeal** [comment]
@evatamanitsa Soon. In the meantime, you can use 2.3.2-SNAPSHOT or change the value curve on your animation such that the opacity doesn't go above 255 (which it does in your case)
