### ISSUE TITLE
Terrible error when setScaleX!!!!!!!!!!!Help!!!!!!!!!!!!!!!!!!!!!! 

### ISSUE THREAD

**Issue by Pluckypan** [airbnb/lottie-android#571]
![lottie](https://user-images.githubusercontent.com/12028060/34093807-5053e06c-e405-11e7-9efa-1eddad941d72.png)

![lottie scale](https://user-images.githubusercontent.com/12028060/34093950-0259f40e-e406-11e7-9a90-5f1ce421ddb4.png)

Here is my code.
![lottie code](https://user-images.githubusercontent.com/12028060/34093979-2a27ca9c-e406-11e7-84c2-dd434beb6ee9.png)

**Comment by Pluckypan** [comment]
And Here it's the lottie file.
[ar_download.zip](https://github.com/airbnb/lottie-android/files/1566967/ar_download.zip)

**Comment by Pluckypan** [comment]
@gpeal i need your help.

**Comment by Pluckypan** [comment]
what's more,when i use hardware,lottie display nothing on Android4.4 Devices

**Comment by gpeal** [comment]
@Pluckypan `lottie_scale` is the attribute you want. You can also use `scaleType="centerInside"`

I just tested your animation in the sample app in the repo with hardware acceleration on on an api 19 device and it rendered just fine. Please attach a sample project that reproduces this if you want me to take a look. No need to include 500 exclamation marks in the title though.

**Comment by Pluckypan** [comment]
@gpeal  I want to express that if you setScaleX or setScaleY to lottie parent view.the problem happended.

i use lottie in recyclerview with viewpagerlayoutmanager (compile 'rouchuan.viewpagerlayoutmanager:viewpagerlayoutmanager:2.0.0').when scroll to center position,the itemview will be scale.this is my scene.

if you want to reproduces this problem.you just try the code below.
'<LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center"
            android:scaleX="1.2"
            android:scaleY="1.2">

            <com.airbnb.lottie.LottieAnimationView
                android:layout_width="48dp"
                android:layout_height="48dp"
                android:layout_gravity="center"
                android:background="#000000"
                android:scaleType="centerInside"
                app:lottie_fileName="ar_download.json"/>
        </LinearLayout>'

and 'lottie_scale' it's not what i want.

**Comment by gpeal** [comment]
What's the actual problem?

**Comment by Pluckypan** [comment]
@gpeal 
 if you setScaleX or setScaleY to lottie parent view. lottie perfermence like the image below.

![lottie scale](https://user-images.githubusercontent.com/12028060/34093950-0259f40e-e406-11e7-9a90-5f1ce421ddb4.png)

**Comment by gpeal** [comment]
Are you referring to the aliasing?

**Comment by Pluckypan** [comment]
@gpeal yep!

**Comment by gpeal** [comment]
Use lottie_scale or scaleType centerCrop. What you're using is an Api on
View itself which is why it's aliasing.

**Comment by Pluckypan** [comment]
Here is my scene:
i use lottie in recyclerview with viewpagerlayoutmanager (compile 'rouchuan.viewpagerlayoutmanager:viewpagerlayoutmanager:2.0.0').when scroll to center position,the itemview will be scaled.

lottie is aliasing when the parent view is scaled.and I didn't scale Lottie itself.
it's useless when i use lottie_scale or scaleType centerCrop to lottie.

my english is poor,but i think you got what i am talking about.

i hope your guys can fix it.so many thanks.

**Comment by gpeal** [comment]
@Pluckypan scaleX and scaleY are handled by Android and Lottie has no control over how it is done.

**Comment by Pluckypan** [comment]
@gpeal  well,thank you all the same.
