### ISSUE TITLE
When first shown, it can't play animation

### ISSUE THREAD

**Issue by wlxyhy** [airbnb/lottie-android#575]
for lottie2.5.0-beta1, on Android7.0
When it is first shown, the animation shows the first frame and stays, but it plays when I turned to another page and return again

**Comment by wlxyhy** [comment]
For attrs"app:lottie_fileName",the LottieAnimationView does not support dataBinding, so I make a view extends LottieAnimationView, but there's the issue above, what's the matter? Or how can LottieAnimationView support dataBinding?

**Comment by gpeal** [comment]
@wlxyhy Can you attach a sample project that repros this? I've never actually used data binding or tried it to be honest but nobody has reached out with issues in the past so it may be project specific rather than due to data binding.

**Comment by gpeal** [comment]
@wlxyhy bump

**Comment by gpeal** [comment]
Feel free to reopen if you create a sample project.

**Comment by wlxyhy** [comment]
Already resolved it by add playAnimation method for my setLottie_fileName()

**Comment by Akshshr** [comment]
@wlxyhy  I think it would be helpful to all others if you details your solution

**Comment by gpeal** [comment]
Can you try 2.5.1?

**Comment by Akshshr** [comment]
@gpeal Gave it a go, no good with databinding
