### ISSUE TITLE
represent PNGs with base64 encoding

### ISSUE THREAD

**Issue by rotman** [airbnb/lottie-android#576]
I'm trying to use animation json file that contains PNGs that are represented with base64 encoding string.
Does the library support it?

**Comment by gpeal** [comment]
@rotman [Convert it to a Bitmap](https://stackoverflow.com/questions/4837110/how-to-convert-a-base64-string-into-a-bitmap-image-to-show-it-in-a-imageview/35799454) then use a BitmapAssetDelegate.
