### ISSUE TITLE
Request: in the sample, allow to go to previous/next animation

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [airbnb/lottie-android#577]
On this screen:

![image](https://user-images.githubusercontent.com/5357526/34379275-1e40313e-eb03-11e7-815b-94ea46eda6bd.png)

In addition to be able to choose from the list in the dialog that appears, I'd like to just go to the next one.
I request this because each time I open a sample animation from the video, the list goes to the top, so I have to scroll all the way to the one I've opened before, to try the next one...

**Comment by gpeal** [comment]
@AndroidDeveloperLB Any suggestions on what the UI should be? I'd like to avoid cluttering it up if possible.

**Comment by AndroidDeveloperLB** [comment]
Yes you are correct. It starts to have too many buttons.
Maybe try putting some of the buttons you have, in the action bar, and the next&previous, near the "play" button.

**Comment by AndroidDeveloperLB** [comment]
@gpeal Why closed the issue?
I don't see it in newer version.

Also, I have a suggestion of how to handle the built in samples:
Allow to swipe between them, using a ViewPager, like a gallery app.
You might even be able to do it when choosing from storage, but I'm not sure it's possible.

**Comment by gpeal** [comment]
@AndroidDeveloperLB Because I updated the asset picker to scroll to the current animation.
I may redesign the app in the future but I don't currently have plans to do more than this.

**Comment by AndroidDeveloperLB** [comment]
@gpeal Please do consider adding this.
Even swiping like in a gallery could be nice.
Also, I see the new change only on the repo, but not on the Play Store app.

Speaking of the sample, I don't think the "full screen animation" shows animation. All I see is this:
![image](https://user-images.githubusercontent.com/5357526/34710538-6f76a3b4-f524-11e7-9426-a5270a96d9a0.png)
