### ISSUE TITLE
Provide script to strip unused bodymovin features

### ISSUE THREAD

**Issue by 0legg** [airbnb/lottie-android#58]
As lottie is using only subset of bodymovin features, it'll be a good idea to have script that minifies animation JSON file by dropping unused parts

**Comment by gpeal** [comment]
@0legg I would support this :) However, over time, we hope to support most if not all features of bodymovin though.

**Comment by gpeal** [comment]
Right now my top priority is going to be around supporting more After Effects features and performance so I won't be able to do this for quite some time (if ever).

I'm going to close this issue but feel free to write one :)
