### ISSUE TITLE
Help Android: Y axis rotation not workin, iOS: Ellipse repeater animation not working.

### ISSUE THREAD

**Issue by AsheStarlight** [airbnb/lottie-android#583]
Android: Y axis rotation not working but ellipse repeater animation is working while iOS: Ellipse repeater animation is not working but Y axis rotation not working

**Comment by gpeal** [comment]
@AsheStarlight Can you attach an animation that repros this?

**Comment by gpeal** [comment]
@AsheStarlight bump

**Comment by gpeal** [comment]
Feel free to reopen if you attach a repro animation.
