### ISSUE TITLE
Optimization ideas for PathKeyframeAnimation

### ISSUE THREAD

**Issue by alexjlockwood** [airbnb/lottie-android#584]
I was taking a look at [`PathKeyframeAnimation`](https://github.com/airbnb/lottie-android/blob/2df1c2bac1cb886dce38d64e0b3a80d603e8dc51/lottie/src/main/java/com/airbnb/lottie/animation/keyframe/PathKeyframeAnimation.java) and although I haven't profiled it myself, I suspect that it could be optimized by avoiding the calls to `PathMeasure#getPosTan()` and `PathMeasure#getLength()` in `getValue()`. Both of these result in JNI calls, so it's probably not great to be calling them inside a method that is called rapidly every 16ms.

The way the framework avoids this is by using the [`Path#approximate(float)`](https://developer.android.com/reference/android/graphics/Path.html#approximate(float)), which returns a float array of points along the path, which can be used to significantly speed up calculating keyframe values during the animation. You can see the framework's implementation of a similar class [here](https://github.com/aosp-mirror/platform_frameworks_base/blob/oreo-mr1-release/core/java/android/animation/PathKeyframes.java).

For future reference, I wrote a similar [`PathMotionKeyframe`](https://github.com/alexjlockwood/kyrie/blob/6784af813f3a60b4cc219f32535ff49eb6ed7759/library/src/main/java/com/github/alexjlockwood/kyrie/animation/keyframe/PathMotionKeyframe.java) class that uses this approach. Note that I had to backport [`Path#approximate(float)`](https://developer.android.com/reference/android/graphics/Path.html#approximate(float)) since it was only recently introduced in API 26. My backport is based on a similar implementation used by `AnimatedVectorDrawableCompat`, which you can view [here](https://github.com/aosp-mirror/platform_frameworks_support/blob/034bc505154bbb42c588e2fc06f46596e3a44a1b/graphics/drawable/animated/src/main/java/android/support/graphics/drawable/AnimatorInflaterCompat.java#L432-L495).

**Comment by gpeal** [comment]
@alexjlockwood Interesting idea. How would you suggest handling the memory for all of the path approximations considering that there could be hundreds of paths that all animate?

I just did a benchmark and on a relatively complex animation (the star wars one in the sample app), each frame spends 0.1-0.15ms in the getPosTan method which doesn't seem all that bad to me.

**Comment by gpeal** [comment]
@alexjlockwood bump

**Comment by alexjlockwood** [comment]
Hmm... I guess that is a good point. Does the star wars animation in the sample app animate hundreds of paths using PathKeyframeAnimation?

**Comment by gpeal** [comment]
@alexjlockwood I picked it because it's one of the most complicated in the app. I tried a few others and they were all very small.

**Comment by gpeal** [comment]
@alexjlockwood I'm going to close this for now. If you think this is still valuable, we can discuss it more.
