### ISSUE TITLE
addColorFilter doesnt work with lottie:2.5.0-beta1

### ISSUE THREAD

**Issue by shishram** [airbnb/lottie-android#585]
.addColorFilter(new PorterDuffColorFilter(mContext.getResources().getColor(R.color.colorAccent), PorterDuff.Mode.LIGHTEN));

doesn't work with updated version, what should I use instead to change color dynamically.

**Comment by AHerbel** [comment]
There's a method called .setColorFilter with 3 versions.
A: .setColorFilter(int color)
B: setColorFilter(int color, Mode mode)
C: setColorFilter(ColorFilter cf)

but it doesn't seem to do anything at all... it doesn't change the color overlay of the animation. This is for the latest version (2.5.0-beta1)

**Comment by shishram** [comment]
@AHerbel Yes, I tried making these changes it didn't work, any other work around?

**Comment by AHerbel** [comment]
@shishram I downgraded the version to 2.3.1 and use addColorFilter and it worked... It's not the ideal, but since the last version is in beta I think this solution is acceptable.

**Comment by gpeal** [comment]
@shishram @AHerbel 2.5.0 replaces the existing color filter APIs with a *much* more powerful one that lets you update any property at runtime. You can view the docs for it [here](http://airbnb.io/lottie/android/dynamic.html). The API may change slightly before release but please try it out and let me know if it works for you!
