### ISSUE TITLE
Animation works on iOS but looks strange on Android

### ISSUE THREAD

**Issue by dustynl** [airbnb/lottie-android#587]
Hi,
This animation (attached) works perfectly on iOS, but behaves really strangely on Android.
Could you guys possibly give us an idea as to why?
[coffeanim.zip](https://github.com/airbnb/lottie-android/files/1616141/coffeanim.zip)

Kind Regards,
Dustyn

**Comment by gpeal** [comment]
@dustynl Can you attach the aep?

**Comment by dustynl** [comment]
Hey Gabriel,

Yes sure ... here it is 
[waiting_cup_simple.zip](https://github.com/airbnb/lottie-android/files/1619675/waiting_cup_simple.zip)

**Comment by NoahZu** [comment]
@dustynl  can fix this bug by modify generated json file?

**Comment by gpeal** [comment]
@NoahZu I don't understand your question.
