### ISSUE TITLE
Unsynchronized cache construction

### ISSUE THREAD

**Issue by 0legg** [airbnb/lottie-android#59]
Right now neither strong nor weak cache construction is covered with any synchronization primitives. In case of concurrent animation loading (say, showing list of animation for a first time), due to lack of synchronization we can create multiple instances of each cache, thus get worse performance and larger memory usage.

**Comment by gpeal** [comment]
@0legg Are you calling `setAnimation` from multiple threads? If all of your calls are coming from the main thread, that shouldn't be necessary.

**Comment by 0legg** [comment]
Yes, if we're tied to the single UI thread, then we're fine. But, library user can utilize, for example, [AsyncLayoutInflater](https://developer.android.com/reference/android/support/v4/view/AsyncLayoutInflater.html), so we're no more in a UI-thread only.

Anyway, I think it'll be nice of you to either guard cache with thread-safety operation, or explicitly mark class as thread-unsafe.
