### ISSUE TITLE
Animation looks good in web but it was distorted in movil Andriod 

### ISSUE THREAD

**Issue by dragonyhr** [airbnb/lottie-android#592]
When I render out the animation with **Bodymovin** with selection  **GUIDES**, it works fine on web but when placed in mobile. The character start to get distorted. Any idea what may be the problem? Looked through the unsupported feature list and none of the unsupported features are being used in the animations so not too sure whats happening.
Is problem of the selection GUIDES in Bodymovin？ because I have to select it for using **DUIK**.  If I can’t use Duik to making animation. is there any others solution for spinning the characters? 

[prueba2.zip](https://github.com/airbnb/lottie-android/files/1622430/prueba2.zip)

**Comment by gpeal** [comment]
I can't tell what this is supposed to be but Lottie doesn't support expressions or most effects
![image](https://user-images.githubusercontent.com/1307745/34837977-51adf16e-f6b1-11e7-984e-15b704681b42.png)

**Comment by dragonyhr** [comment]
@gpeal  hi  thank you very much , sorry to respond so late
