### ISSUE TITLE
Real time rendering graph doesn't show up on black in the animation viewer

### ISSUE THREAD

**Issue by alexjlockwood** [airbnb/lottie-android#594]
This is a bug in the sample app.

The real time rendering graph doesn't show up when you use the "view on black" setting.

![screenshot_20180113-090713](https://user-images.githubusercontent.com/1380747/34908227-698344ce-f841-11e7-8ad3-47f4e37873e2.png)

![screenshot_20180113-090726](https://user-images.githubusercontent.com/1380747/34908226-67381168-f841-11e7-968b-b2b127e0142e.png)

**Comment by alexjlockwood** [comment]
The instructions don't display either.

![screenshot_20180113-091446](https://user-images.githubusercontent.com/1380747/34908319-5eca0ee0-f842-11e7-91a3-ff6184a2da69.png)

![screenshot_20180113-091451](https://user-images.githubusercontent.com/1380747/34908321-625536d4-f842-11e7-8440-4b992c625c19.png)

**Comment by gpeal** [comment]
@alexjlockwood Would you like to submit a PR for this? Not sure I'll have time to get around to this since it's not a showstopper.

**Comment by alexjlockwood** [comment]
I will if I have time. I've never written Kotlin code before... maybe now is a good opportunity to start. :D

**Comment by gpeal** [comment]
@alexjlockwood Yes! Kotlin will change your life.

**Comment by hearsilent** [comment]
@gpeal I just create PR (#644) to fix this issue 👍
