### ISSUE TITLE
Interact with elements from animation

### ISSUE THREAD

**Issue by fweigl** [airbnb/lottie-android#595]
Hi, is there a possibility or feature planned to interact with certain elements in an animation?
For instance, find a "button" (as a shape in the animation, not a native button) via some sort of ID and set an Android onClickListener to it?

**Comment by gpeal** [comment]
@fweigl Yes, I plan to add support for this in the future but it doesn't support it yet.

**Comment by gpeal** [comment]
Duplicate of #444
