### ISSUE TITLE
Included sample graphics rights

### ISSUE THREAD

**Issue by kosiarska** [airbnb/lottie-android#60]
Is it possible to use included sample animations in my google play app (not released yet)?

**Comment by gpeal** [comment]
Let me get back to you on that. Which one are you interested in using?

**Comment by kosiarska** [comment]
@gpeal 
Only one, jumping location icon. Btw. great library :+1:

**Comment by gpeal** [comment]
@kosiarska The included animations fall under the same license as the repo.
