### ISSUE TITLE
Animations glitchy on Android

### ISSUE THREAD

**Issue by mister11** [airbnb/lottie-android#601]
There was an issue #558 which was similar problem to this one - animations work fine on iOS, but are glitchy on Android. In that issue, someone said issue was fixed in 2.3.2-SNAPSHOT but this version is not available anymore and the newest library version (2.5.0-beta3) still has some issues with some of the animations we use.

You can look at mentioned issue to see how view is defined and how animation is played. I've also added `app:lottie_enableMergePathsForKitKatAndAbove="true"` but it did not help.

I've attached zip with two animations we have problem with. If aep files are needed, I can provide those too.
[Animations.zip](https://github.com/airbnb/lottie-android/files/1653923/Animations.zip)

**Comment by gpeal** [comment]
@mister11 What are the issues with 2.5.0? I'm planning on releasing it soon

**Comment by mister11** [comment]
There are animation files attached in first message which you can download and run to see. Best way to describe it is "glichy" or, in the case of second animation, "broken" since part of it is completely wrong size

**Comment by mister11** [comment]
@gpeal I've tried with the 2.5.0-rc1 and it fixed the issue with animation-5 from the zip, but animation-4 is still glitchy. Can you take a look at it?
