### ISSUE TITLE
performance problem

### ISSUE THREAD

**Issue by SwayChen** [airbnb/lottie-android#603]
Hi, I got high rate of `Slow Rendering` in Play Console. See the pictures of following, and I don't know to optimize it. The size of json is about 50KB.

![image](https://user-images.githubusercontent.com/6345749/35321148-46d48e04-0121-11e8-88fb-2ea6dff27a4a.png)
![image](https://user-images.githubusercontent.com/6345749/35321625-4dbd45f2-0122-11e8-81ef-95cba482ea4c.png)

Impacted sessions means:
```
Percentage of daily sessions during which more than 50% of frames took longer than 16 to render.
A daily sessions refer to a day during which your app was used.
Google collects the render time of each frame rendered by your app if your app uses the UI Toolkit framework, but not if your app uses OpenGL directly.
```

**Comment by gpeal** [comment]
This isn't actionable and that graph can't be attributed to lottie. I have written some [docs on performance](http://airbnb.io/lottie/android/performance.html) though.

**Comment by otopba** [comment]
@gpeal Hi! Could you provide valid link to performance docs please?

**Comment by gpeal** [comment]
@otopba http://airbnb.io/lottie/#/android?id=performance

**Comment by otopba** [comment]
> @otopba http://airbnb.io/lottie/#/android?id=performance

Thank you!
