### ISSUE TITLE
compile 'com.airbnb.android:lottie:2.5.0-rc1' Failed

### ISSUE THREAD

**Issue by zoky2017** [airbnb/lottie-android#609]
change compile 2.5.0-rc1 failed, but compile 2.5.0- beta3 is available
![image](https://user-images.githubusercontent.com/14806642/35613096-f195d3fa-06a5-11e8-9f4a-1089d278fec5.png)

**Comment by gpeal** [comment]
Sorry about that, I'll try and get it up today

**Comment by gpeal** [comment]
This is available now!
