### ISSUE TITLE
add back LottieComposition.Factory.fromJsonSync (regression from prev release?)

### ISSUE THREAD

**Issue by gshysun** [airbnb/lottie-android#612]
With the 2.5.0 release `LottieComposition.Factory.fromJsonSync` has disappeared could you look into adding it back?

Thanks,
Shyam

**Comment by gpeal** [comment]
@gshysun Ah, I just removed the factory method.

**Comment by gpeal** [comment]
`LottieComposition.fromJsonSync`

**Comment by gpeal** [comment]
Actually, I'll revert it so the API doesn't change
