### ISSUE TITLE
app:lottie_imageAssetsFolder not work?

### ISSUE THREAD

**Issue by geolyth** [airbnb/lottie-android#614]
I'm using latest version of Lottie (com.airbnb.android:lottie:2.5.0-beta3) but I receive an error when I try to put animation in a folder inside assets (assets/animations/notification.json)

```
android.view.InflateException: Binary XML file line #57: Binary XML file line #57: Error inflating class com.airbnb.lottie.LottieAnimationView
Caused by: android.view.InflateException: Binary XML file line #57: Error inflating class com.airbnb.lottie.LottieAnimationView
Caused by: java.lang.reflect.InvocationTargetException
```

I use this code:
```
<com.airbnb.lottie.LottieAnimationView
                        android:layout_width="match_parent"
                        android:layout_height="250dp"
                        android:layout_marginBottom="@dimen/spacing_normal"
                        android:scaleType="centerCrop"
                        app:lottie_autoPlay="true"
                        app:lottie_fileName="notification.json"
                        app:lottie_imageAssetsFolder="animations/"
                        app:lottie_loop="true"/>
```

If I put this in assets it works.

**Comment by gpeal** [comment]
@geolyth imageAssetsFolder is if your animation has actual images (which is rarely necessary).
Just put your json in `assets/` and remove that attribute.

**Comment by geolyth** [comment]
@gpeal Ah ok.
So If I would like to organize my animations in folders inside "Assets"? Is possibile?

**Comment by gpeal** [comment]
No, you can also put your animations in res/raw and reference them though `@raw/animationName`

**Comment by gpeal** [comment]
This is the same for any Android resource though.

**Comment by geolyth** [comment]
@gpeal Ok, I put all animations in /assets, so all animations works well.
Thanks you
