### ISSUE TITLE
lottie animation doesn't show up in react native android build .

### ISSUE THREAD

**Issue by vinnyHero** [airbnb/lottie-android#616]
react-native : "0.48.3"
lottie-react-native : "^2.3.2"

when ever i run my project, it shows blank page . no animation. 
integrated successfully , linked with android studio . 
have put my json file into assets folder but no luck 

here is my code snippet

`import LottieView from 'lottie-react-native';`

`  componentDidMount(){
   this.animation.play()
  }`

 render(){
    return(
      <LottieView
        ref={animation => {
          this.animation = animation;
        }}
        source="{require('../../../../anim/success.json')}"
      />

    )
  }

**Comment by gpeal** [comment]
Please file this on airbnb/lottie-react-native.
There are a few paths in docs that I need to update. Check https://github.com/airbnb/lottie-react-native/issues/242 for more info.
