### ISSUE TITLE
Animation on click works only after the first try?

### ISSUE THREAD

**Issue by geolyth** [airbnb/lottie-android#618]
I'm using Lottie 2.5.0-rc1.

I'm trying to do a simple change of animation (selected/unselected) after a click on an object like so:
```
if (value) {
   animationView.setAnimation("checkbox_selected.json");
   animationView.playAnimation();
} else {
   animationView.setAnimation("checkbox_unselected_grey.json");             
   animationView.playAnimation();
}
```
On first click on object the animation is "empty" (I am not able to see nothing), but after this one the animation works perfectly.

Some ideas on why this happens?

P.S. If I use Lottie 2.3.1 this behaviour not happen (so all works well)

**Comment by gpeal** [comment]
@geolyth Can you attach a sample project that repros this?

**Comment by geolyth** [comment]
@gpeal I am using in a personal project so in this moment it is difficult to clone in sample project.
I'm using that snippet in a BindingAdapter (from DataBinding).

**Comment by gpeal** [comment]
Without a sample project, I won't be able to repro this. One thing to note is that animations are loaded async so it may have to do with an animation not being loaded.
