### ISSUE TITLE
Adding templates for issues and Pull Requests

### ISSUE THREAD

**Issue by saketkumar95** [airbnb/lottie-android#62]
https://github.com/blog/2111-issue-and-pull-request-templates

This will make sure that important information is not missed in an issue.
**Points in issue template**

- Actual

- Behaviour

- Expected Behaviour
- Steps to reproduce it
- LogCat for the issue
- Screenshots of the issue
- Would you like to work on the issue?

@gpeal Any views on this?

**Comment by gpeal** [comment]
Fixed by https://github.com/airbnb/lottie-android/commit/49783f23f93515b40a0ba81a0540242ea27b2b4c
