### ISSUE TITLE
LlottieAnimationView addColorFilterToLayer removed in version 2.5.0-rc1

### ISSUE THREAD

**Issue by AroundPixels** [airbnb/lottie-android#620]
Hi,

Using addColorFilterToLayer to change animation layer colors dinamically, I'm updating library to 2.5.0-rc1 but can't find LlottieAnimationView.addColorFilterToLayer. There is any new method to do the same?

Thank you
Ruben

**Comment by gpeal** [comment]
http://airbnb.io/lottie/android/dynamic.html#migrating-from-the-old-addcolorfilter-api
