### ISSUE TITLE
Change animation success to fail ?

### ISSUE THREAD

**Issue by FabioMorcillo** [airbnb/lottie-android#626]
Hi,

I am trying to change animation to fail in android studio, but i not found this way, anyhere can help me ?

https://www.lottiefiles.com/627-loading-success-failed

Thank you,

**Comment by gpeal** [comment]
Sorry, I don't understand your issue.

**Comment by jossuediazperez** [comment]
> Hola,
> 
> Estoy tratando de cambiar la animación para que falle en Android Studio, pero no he encontrado de esta forma. ¿Algún lugar me puede ayudar?
> 
> https://www.lottiefiles.com/627-loading-success-failed
> 
> Gracias,

Entiendo cual es tu inquietud, es lo mismo que necesito pero no creo que con Lottie no lo puedas conseguir, debes encontrar una animación que contemple los casos de éxito y error sin que el cambio para cada caso en la animación se brusco, ademas debe tener en cuenta que la carga puede ser por un tiempo indefinido.
