### ISSUE TITLE
Can't get control progress in "Lottie Animation" to work

### ISSUE THREAD

**Issue by Alexef910** [airbnb/lottie-android#630]
Hi guys I have an issue regarding the progress of an animation in Xcode.
My code is this:

let animationView = LOTAnimationView(name: "AnimationOne")
        animationView.frame = CGRect(x: 100, y: 100, width: 250, height: 250)
        animationView.contentMode = .scaleAspectFill
        
        self.view.addSubview(animationView)
        animationView.play(fromProgress: 0.25, toProgress: 0.5, withCompletion: nil)

If I set the last line to "animationView.play()" it works fine, but as soon as I try to control its progress I get an error that says:
"Argument passed to call that takes no arguments"

Does anyone knows how to fix this?

**Comment by gpeal** [comment]
@Alexef910 This is the wrong repo. Please post this on airbnb/lottie-ios
