### ISSUE TITLE
2.5.0: Visibility issues

### ISSUE THREAD

**Issue by PaulWoitaschek** [airbnb/lottie-android#636]
The migration guide suggests to use:

```java
animationView.addValueCallback(new KeyPath("hello_layer", "**"), LottieProperty.COLOR_FILTER, new LottieValueCallback(colorFilter));
```

instead  of `animationView.addColorFilterToLayer("hello_layer", colorFilter);`

However `LottieValueCallback` is marked as `@RestrictTo(RestrictTo.Scope.LIBRARY)`

**Comment by gpeal** [comment]
Ah, I meant to remove that before release. Feel free to use it and suppress/ignore it until 2.5.1 is out.
