### ISSUE TITLE
Change minSdkVersion

### ISSUE THREAD

**Issue by ntsparis** [airbnb/lottie-android#64]
Actually i am wonder if is possible for the near future to implement support for minSdkVersion 15.

Thanks a lot!

**Comment by rishabh876** [comment]
Even I would like to see support till 14. Any explanation why minSdkVersion  is 16?

**Comment by lord19871207** [comment]
I also want to know the reason why minSdkVersion is 16。

**Comment by gpeal** [comment]
I set it at 16 because that's our minSdk at Airbnb. I can investigate lowering it to 14 or 15. No guarantees but I'll take a look.

**Comment by gpeal** [comment]
I lowered the minSdk to 14 and made the API changes necessary. Neither Google nor Genymotion has ICS emulators available anymore so it's untested. Let me know if it works.

**Comment by gpeal** [comment]
1.0.2 is now live, I haven't been able to test lottie on ics but I lowered the minsdk and fixed the necessary apis. Can you try?

**Comment by Drjacky** [comment]
@gpeal I'm using 3.4.0, but still doesn't support API 15
`com.airbnb.android:lottie:3.4.0`
