### ISSUE TITLE
Updating value does not work

### ISSUE THREAD

**Issue by PaulWoitaschek** [airbnb/lottie-android#640]
Calling `setValue` on `LottieValueCallback` has no effect when the view is not laid out yet.

Here is a project for reproducing this:

```kotlin
package de.paul_woitaschek.lottiecallbackbug

import android.annotation.SuppressLint
import android.os.Bundle
import android.support.v7.app.AppCompatActivity
import com.airbnb.lottie.LottieAnimationView
import com.airbnb.lottie.LottieProperty
import com.airbnb.lottie.model.KeyPath
import com.airbnb.lottie.value.LottieValueCallback

class MainActivity : AppCompatActivity() {

    @SuppressLint("RestrictedApi")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val lottie = LottieAnimationView(this)
        setContentView(lottie)

        lottie.setAnimation("HamburgerArrow.json")

        val valueCallback = LottieValueCallback(0)
        lottie.addValueCallback(KeyPath("A3", "**"), LottieProperty.OPACITY, valueCallback)
        valueCallback.setValue(100)
    }
}
```

[HamburgerArrow.json](https://github.com/airbnb/lottie-android/blob/master/LottieSample/src/main/assets/HamburgerArrow.json)

A3 is the top bar. I expect the bar to be shown as I call `setValue(100)`. However it is not shown and hidden through the value specified  in the constructor.

**Comment by gpeal** [comment]
@PaulWoitaschek This code worked for me. If you can recreate this in a sample project, feel free to reopen it.

(I set A3 to 50)
![image](https://user-images.githubusercontent.com/1307745/36400721-ab6afef0-1587-11e8-991d-9c5bb2c46cb6.png)

**Comment by PaulWoitaschek** [comment]
Sure. Actually it is already the sample project, there is nothing more.

So here  a full repo: https://github.com/PaulWoitaschek/LottieBug/blob/master/app/src/main/java/de/paul_woitaschek/lottiecallbackbug/MainActivity.kt

**Comment by PaulWoitaschek** [comment]
@gpeal Did you read this?
