### ISSUE TITLE
Rotate animation element independently

### ISSUE THREAD

**Issue by brystel** [airbnb/lottie-android#643]
Hi,

I want to rotate one element from animation independently.
I follow *Updating Properties Dynamically* tutorial and tried to use `LottieAnimationView.addValueCallback` methods, but them allow only to change element parameters during animation progress change.

Is there a way to get animation element (for example using `KeyPath`) and rotate it infinitely (for example using handler which will change rotation)?

**Comment by gpeal** [comment]
@brystel Call setValue on your ValueCallback.

**Comment by brystel** [comment]
Unfortunately it does not work.
I am playing animation using `ValueAnimator` via `setProgress(float progress)` method.
So when there are no updates from ValueAnimator then `setValue` on `ValueCallback` method has no impact.

Maybe there is different way to do this?
Can I get drawable or ImageView from animation and rotate it manually?

**Comment by Nk-pa** [comment]
how to rotate animation element independently to specific angle in Swift 

@brystel can you please answer how you managed it?

**Comment by Nk-pa** [comment]
I need to change angle of cycle in cyclist Lottie aniamation but there are different nodes available for one cycle like 
1.wheel net *.Group 1.Fill 1.Color
2.wheel circle *.Group 1.Fill 1.Color
3.bike.Group *.Fill 1.Color


many more nodes related to cycle parts and I want to change angle of whole cycle Please Please share your thoughts on this.. It will be really helpful

**Comment by gpeal** [comment]
@Nk-pa You'll want to post that on https://github.com/airbnb/lottie-ios
