### ISSUE TITLE
How to convert .aep to .json

### ISSUE THREAD

**Issue by itsDanLEL** [airbnb/lottie-android#645]
Can you teach me how to convert ?

**Comment by fabionuno** [comment]
I hope the [Installing Bodymovin](http://airbnb.io/lottie/after-effects/bodymovin-installation.html) tutorial and the [How to export an animation with Bodymovin](https://www.youtube.com/watch?v=5XMUJdjI0L8) video  can help you.

**Comment by gpeal** [comment]
Thank you @fabionuno

**Comment by siaaha** [comment]
Hi there! how to implement this animation for both success and failure
https://www.lottiefiles.com/search?q=success+failed
