### ISSUE TITLE
setAnimation not working after another drawable was set

### ISSUE THREAD

**Issue by sin3hz** [airbnb/lottie-android#648]
Steps to reproduce
```java
lottieAnimationView.setAnimation("animation.json");
lottieAnimationView.setImageDrawable(drawable);
lottieAnimationView.setAnimation("animation.json"); // Not working
```

The problem is [setComposition](https://github.com/airbnb/lottie-android/blob/c6c1a966b746881a22732ac93dbddf90be101ac3/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L470) does not reapply the lottieDrawble after drawable changed.
I think call `clearComposition` in `setImageDrawable` will fix this.

**Comment by rosconabn** [comment]
Try to set LottieAnimationView.setImageDrawable to null because I think it doesn't change if is the same. 
e.g.
lottieAnimationView.setImageDrawable(null);
lottieAnimationView.setImageDrawable(R.drawable.drawable);

**Comment by sin3hz** [comment]
@rosconabn It's not working.

**Comment by gpeal** [comment]
@sin3hz It does reset the drawable [here](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L494)

I tried equivalent code to yours and it worked fine. Can you attach a sample project that repros this?

**Comment by sin3hz** [comment]
@gpeal The issue happened when the composition cached, check the right code or sample.
```java
        lottieAnimationView = findViewById(R.id.lottie_view);
        final Drawable drawable = ContextCompat.getDrawable(this, R.mipmap.ic_launcher);
        lottieAnimationView.setAnimation("EmptyState.json");
        Log.d(TAG, "setAnimation(\"EmptyState.json\")");
        lottieAnimationView.postDelayed(new Runnable() {
            @Override
            public void run() {
                lottieAnimationView.setImageDrawable(drawable);
                Log.d(TAG, "setImageDrawable(drawable)");
            }
        }, 1000);
        lottieAnimationView.postDelayed(new Runnable() {
            @Override
            public void run() {
                Log.d(TAG, "setAnimation(\"EmptyState.json\")");
                lottieAnimationView.setAnimation("EmptyState.json");
            }
        }, 2000);
```

[LottieIssue648.zip](https://github.com/airbnb/lottie-android/files/1800233/LottieIssue648.zip)
