### ISSUE TITLE
[Bug] Lottie is not releasing memory even after activity/fragment is destroyed.

### ISSUE THREAD

**Issue by pranayairan** [airbnb/lottie-android#65]
I tried Lottie sample app and in my own app as well. Once we open activity/fragment with LottieAnimationView and exit that activity, the memory is still allocated. I used android studio memory monitor tool to get memory footprint of the app.

Ideally it should free up the memory if that Animation is not used anymore. 

Here is my screenshot showing memory allocation before opening Typographic activity, after opening it and after quitting it. 
<img width="1208" alt="screen shot 2017-02-04 at 10 56 18 am" src="https://cloud.githubusercontent.com/assets/430940/22620876/c9875ed6-eac9-11e6-9a55-c424fa86ae03.png">

**Comment by satria977** [comment]
https://cloud.githubusercontent.com/assets/430940/22620876/c9875ed6-eac9-11e6-9a55-c424fa86ae03.png

**Comment by imankitaman** [comment]
@pranayairan  I tried **ButterKnife Unbinder** and in DestroyView I  called **unbinder.unbind().** It is working fine for me.

**Comment by pranayairan** [comment]
@imankitaman I am not sure about BK but i tried this 2 methods, i tried setting LottieAnimationView reference to null or LottieAnimationView.clearAnimation but neither of this worked. The memory is still not released.

**Comment by gpeal** [comment]
@pranayairan I'll take a look at this

**Comment by gpeal** [comment]
@pranayairan I just tried this and after forcing a GC (the garbage truck icon), memory returned to the original value of ~4mb.

**Comment by satria977** [comment]
reply@reply.github.com
