### ISSUE TITLE
compileSdkVersion

### ISSUE THREAD

**Issue by zoky2017** [airbnb/lottie-android#650]
hello, I had some problems when compile 'com.airbnb.android:lottie:2.5.0-rc1' to my project
because other reason, my project compileSdkVersion is 22 , but the lottie compileSdkVersion  is 27
Do I have to  upgrade my compileSdkVersion to 27 for using lottie?

**Comment by rosconabn** [comment]
Yes use 
    compileSdkVersion 27
    buildToolsVersion '27.0.2'

it's "fine"...

**Comment by gpeal** [comment]
@zoky2017 You should keep your compileSdkVersion up to date.
https://medium.com/google-developers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd
