### ISSUE TITLE
minSDK still seems to be 16

### ISSUE THREAD

**Issue by min0623** [airbnb/lottie-android#651]
Hi, I saw that since version 2.5.0 Lottie supports minSDK version of 14.

When I tried building my app with 2.5.0-rc1, it worked well with minSDK of 14, but as I upgraded Lottie to stable version 2.5.0, it says that Lottie supports minSDK of 16. Is the change rollbacked, or am I doing something wrong?

Thanks

**Comment by gpeal** [comment]
The minSdk had to be raised to 16 for https://github.com/airbnb/lottie-android/pull/624

I tried to support 14 for as long as possible but I had to raise it for this change.

**Comment by min0623** [comment]
@gpeal Oh okay. Hope you get to update the documentation soon! Thanks
