### ISSUE TITLE
Lottie isn't rendering stars correctly

### ISSUE THREAD

**Issue by LaurensVandevyver** [airbnb/lottie-android#654]
Hello

First of all, thank you for creating this amazing kick-ass library the work it does is amazing! 

Now, I drew this in illustrator and animated it in after effects. I created shapes from all my vector layers and exported this using the bodymovin extension. 

<img width="404" alt="screen shot 2018-02-27 at 15 49 57" src="https://user-images.githubusercontent.com/23653318/36735218-ec9803ce-1bd5-11e8-8304-e7a8f7692b1a.png">

When I render this in the browser it looks like this:
![screen shot 2018-02-27 at 15 52 24](https://user-images.githubusercontent.com/23653318/36735339-3dfa4146-1bd6-11e8-98c0-601123099cb0.png)

The stars don't seem to render properly. The stars are created with with the standard Adobe Illustrator star tool. I'm attaching a zip file with my after effects and JSON code. 

Kind regard
Vandevyver Laurens 

[issue.zip](https://github.com/airbnb/lottie-android/files/1763339/issue.zip)

**Comment by gpeal** [comment]
@LaurensVandevyver Merge paths are only supported on KitKat and above so it's an opt-in API that you have to manually enable. There is also performance overhead with them so I recommend making the stars with shapes instead.

**Comment by gpeal** [comment]
Polystars are supported as well
