### ISSUE TITLE
Update documentation to demonstrate resource access

### ISSUE THREAD

**Issue by elihart** [airbnb/lottie-android#658]
Documentation still shows the old way of loading a file by explicit string name. Would be nice to update it to the newer way of accessing a resource

**Comment by Moes81** [comment]
Also an API doc/method docs would also be nice. Currently it's just browsing through autocomplete to find a method that might do what you need.

**Comment by gpeal** [comment]
I've added this to airbnb.io

**Comment by gpeal** [comment]
@Moes81 I haven't added 100% API docs because the docs repo is a separate repo and keeping them in sync across all platforms is difficult. However, I just added a lot of content to the docs that explains many more of the APIs.
