### ISSUE TITLE
组件未能正确适应大小

### ISSUE THREAD

**Issue by TJHello** [airbnb/lottie-android#659]
如题，json标注的大小是"w":1080,"h":800,"，但使用lottie显示之后，高度和宽度远远大于json标注的大小，这是不正常的，而且，有时候，json是长方形的，而lottieview却是正方形的(自动补全为正方形？)

**Comment by gpeal** [comment]
Lottie converts px to dp so your animation will be 1080x800dp
http://airbnb.io/lottie/android/performance.html#sizing-px---dp

You can also use scaleType like you would on an ImageView

**Comment by YaoPaine** [comment]
help ! how to resolve this issue?
