### ISSUE TITLE
Big

### ISSUE THREAD

**Issue by dighialamgir** [airbnb/lottie-android#66]
Before opening a new issue:

* Look through open and existing issues for duplicates.
* Apply an appropriate label.

If this is a bug:
* Attach your After Effects file. If you do not feel comfortable posting it on github, email 
it to lottie@airbnb.com. There are 500 ways to do everything in After Effects that achieves the 
same visual effect so it is nearly impossible to reproduce your issue without the original After 
Effects file.

If this is a feature request:
* Explain what feature you would like and why you need it. There are usually After Effects 
workarounds that we can provide in the meantime that achieve the same effect.

**Comment by gpeal** [comment]
I think you forgot to explain your problem.
