### ISSUE TITLE
setProgress on LottieAnimationView doesn't always reflect without playAnimation

### ISSUE THREAD

**Issue by MNDaveC** [airbnb/lottie-android#660]
For a LottieAnimationView I often want to set the progress 0.5f without playing any animation. I have found that this is not reliable without also calling playAnimation and setting setMaxProgress to 0.5f and calling playAnimation. This workaround seems to cause some extra flicker of the view. Ideally, I'd like setProgress to immediately render the desired progress point.

For background my animation file has 3 states:
0.0f = item not checked state
0.0-> 0.5f animate checking
0.5f = item checked state
0.5-1.0f = animate unchecking
1.0f = item not checked state

**Comment by gpeal** [comment]
@MNDaveC You should just be able to call setProgress. Can you attach a sample project that repros this?

**Comment by MNDaveC** [comment]
I see this behavior when the view containing the LottieAnimationView is in a RecyclerView.ViewHolder when I scroll the RecyclerView and the affected view gets recycled and recreated. Changing the cacheStrategy seems to have no impact. So the first time the ViewHolder binds the setProgress seems to work, but subsequent binds seem unreliable.

Example gist: https://gist.github.com/MNDaveC/0ebf0179c4ba56b66113c664f88d47de

**Comment by MNDaveC** [comment]
BTW this is using com.airbnb.android:lottie:2.5.0

**Comment by gpeal** [comment]
I think your issue will be solved by https://github.com/airbnb/lottie-android/commit/d2c47a78f4579b1eb25a3417a3a8902521263994 or https://github.com/airbnb/lottie-android/commit/7c65f1f0913000e160121e495e76eea3958fbd1e

This will be released in 2.5.1 this week

**Comment by huru277** [comment]
use LottieAnimationView.setMinAndMaxProgress(float,float)
