### ISSUE TITLE
LottieAnimationView setMaxProgress without setMinProgress doesn't stop at max

### ISSUE THREAD

**Issue by MNDaveC** [airbnb/lottie-android#661]
If I call the following on my LottieAnimationView, the animation goes past the max and wraps past the end of the animation and starts to play the beginning of the animation:
setProgress(0.5f) 
setMaxProgress(1.0f)
playAnimation()

Adding in a setMinProgress(0.5f) seems to be a successful workaround...  despite it seeming unnecessary.

**Comment by gpeal** [comment]
@MNDaveC I'm unclear as to what the issue is here. Why would it not wrap back to the beginning in this case?

**Comment by MNDaveC** [comment]
In the example above I want to start the animation in the middle (set progress to 0.5f) and play it to the end without having it wrap back to the beginning. My assumption is by setting max progress to 1.0f should stop it at the end.

**Comment by Moes81** [comment]
@MNDaveC max progress sets the "upper border" in case you only want to play a "segment" from your animation, e.g. from 10% to 70% you set the max progress to `0.7f`. If the animation is running in a loop, you should check the `repeatCount` and `repeatMode` values.

**Comment by MNDaveC** [comment]
I had not set either of those values... could have been due to the other issue I posted about setProgess not taking effect... ?

**Comment by gpeal** [comment]
@MNDaveC Have you tried using the repeatCount api?

**Comment by MNDaveC** [comment]
I have found a particular json file that always seems to replay when it animates, while the same code with a different lottie json animation works fine (does not replay). For now I have gone back to Lottie 2.1.0 where the problematic json animation plays fine. I can send you the problem json file if you let me know best way to send it to you. I don't want to post it publicly. Thanks

**Comment by gpeal** [comment]
@MNDaveC You can send it to lottie_at_airbnb_dot_com

**Comment by jda-tid** [comment]
Starting in Lottie 2.5.0, my animations are not starting in "progress  == 0" so I have to find where it should start. A workaround is to do something like `lottieView.setMinProgress(16.2f)` for every animation.

In Lottie 2.3.1 it works as expected.

**Comment by MNDaveC** [comment]
What does the `16.2f` represent? Do these values come from After Effects? How are these determined for beginning, middle and end of the animation?

Also, I'm not clear how this is resulting in the animation playing twice?

`In Lottie 2.3.1 it works as expected.` Are you implying this is a bug in 2.5 or has the functionality changed with 2.5?

**Comment by jda-tid** [comment]
The value is different for each animation. I have found these values logging the animation and I saw that iit was playing some weird stuff before the actual animation which is fixed using an offset of X. 

I am no designer, I just receive animations and insert them in an Android app.

I think that it is a bug in 2.5.0. It also works as expected in https://www.lottiefiles.com/preview

**Comment by gpeal** [comment]
@jda-tid Your issue is likely solved by https://github.com/airbnb/lottie-android/commit/3869e29ff221b586580a1e6a30e2ed0c36aac53b
