### ISSUE TITLE
setting new values for setMinAndMaxProgress in onAnimationEnd, new animation segment is not starting

### ISSUE THREAD

**Issue by Moes81** [airbnb/lottie-android#663]
I have a json that contains different "segments" for serveral states of the app. On certain states, I have to play different segments after each other. I ensured, that `loop` is always false, if there is a follow up animation. However, with the code example below (simplified), the very first animation runs fine, but the next animation segment doesn't show. The `AnimatorListener.onAnimationStart()` is called for the new segment, but it doesn't show on the screen. I cannot post the json file, because it's under NDA. But it is working without any problems on iOS. Am I missing something?
 
    override fun onResume() {
        super.onResume()
        setupAndStartAnimation(0f, 0.09f)
    }

    fun setupAndStartAnimation(start: Float, end: Float, loop: Boolean = false)
        animation_view.cancelAnimation() //also tried with .pauseAnimation()
        animation_view.setMinAndMaxProgress(start, end)
        if (loop) {
            animation_view.repeatCount = LottieDrawable.INFINITE
        } else {
            animation_view.repeatCount = 0
        }
        animation_view.removeAllAnimatorListeners()
        animation_view.addAnimatorListener(object : Animator.AnimatorListener {
            override fun onAnimationStart(animator: Animator) { /* no-op */ }
            override fun onAnimationRepeat(animator: Animator) { /* no-op */ }
            override fun onAnimationCancel(animator: Animator) { /* no-op */ }

            override fun onAnimationEnd(animator: Animator) {
                setupAndStartAnimation(0.14f, 0.29f, true)
            }
        })
        animation_view.playAnimation() // also tried with resumeAnimation()

**Comment by gpeal** [comment]
@Moes81 I'm pretty sure your issue will be fixed by https://github.com/airbnb/lottie-android/commit/8c3339906ef8a6349e7efed60923097e5fcbe425

This will be released as 2.5.1 this week.

**Comment by Moes81** [comment]
Sorry, I cannot confirm it's working. Still, the second animation is not played. `animatorListener.onAnimationStart()` is called, but that's it. No new animation segment played on the screen. Any hints? Do you have a sample animation with different segment, I can use for testing?

**Comment by gpeal** [comment]
@Moes81 Can you attach a sample project? Maybe your project is doing something differently than mine.

**Comment by Moes81** [comment]
@gpeal I really hope I can do it next week. But unfortunately, as I said, I cannot attach the animation json because the feature is still under NDA. But I'll try to recreate the issue with a "clean" project. Good point.

**Comment by gpeal** [comment]
@Moes81 You can email it to Lottie [at] airbnb.com if you want

**Comment by Moes81** [comment]
I was able to reproduce the error with the attached json (from www.lottiefiles.com).
The code is identical to the one from my first comment here. I also attached a screen record, where you can see that the animation stops instead of looping the second part.
[motorcycle.json.zip](https://github.com/airbnb/lottie-android/files/1830316/motorcycle.json.zip)
[animation_stops.mp4.zip](https://github.com/airbnb/lottie-android/files/1830324/animation_stops.mp4.zip)

**Comment by Moes81** [comment]
I found out, that it works fine if I load and set the `composition` anew on the `animationDrawable` / `animationImageView` before the next segment is played.

**Comment by Moes81** [comment]
@gpeal A sample project, where you can see, that the next animation segment is not played.
[LottieTest_NextSegmentNotPlaying.zip](https://github.com/airbnb/lottie-android/files/1848097/LottieTest_NextSegmentNotPlaying.zip)
