### ISSUE TITLE
first build of lottie-android

### ISSUE THREAD

**Issue by hussanirizvi2** [airbnb/lottie-android#666]
Hi,

this is probably a very silly issue that is extremely simple (as I have googled everywhere and found nothing)

Trying to use Android studio with this project on git hub

https://github.com/airbnb/lottie-android

every time I run it I get this error at the build stage:

Executing tasks: [assemble]

Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\lottie-android-master\build.gradle' line: 34

* What went wrong:
A problem occurred evaluating root project 'lottie-android-master'.
> No .git directory found!

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

I have tried to change my build.gradle file (in the commented ways below), but to no effect

git = Grgit.open()
//Grgit.open(dir: file('.'))
//Grgit.open(file('.'))

can anyone tell me what I am doing wrong?

**Comment by gpeal** [comment]
@hussanirizvi2 Make sure to clone the repo with git. Don't just download an archive of it with a zip file or something. Somehow your lottie directory isn't a git repo.

**Comment by XD-Z** [comment]
I have the same problem as you，How to solve this problem？
