### ISSUE TITLE
NPE - FontFragment aren't binded. 

### ISSUE THREAD

**Issue by namgungsook** [airbnb/lottie-android#670]
After commit 79c6471, NPE is occurred when FontFragment launch.
It happens because butterknife can not bind FontFragment.
butterknife log is as follows:

03-09 16:15:36.652 3662-3662/com.airbnb.lottie D/ButterKnife: Looking up binding for com.airbnb.lottie.samples.FontFragment
03-09 16:15:36.652 3662-3662/com.airbnb.lottie D/ButterKnife: Not found. Trying superclass android.support.v4.app.Fragment
03-09 16:15:36.652 3662-3662/com.airbnb.lottie D/ButterKnife: MISS: Reached framework class. Abandoning search.

**Comment by namgungsook** [comment]
You guy should change it
annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'  ->
kapt com.jakewharton:butterknife-compiler:8.8.1'

**Comment by gpeal** [comment]
This is now fixed.
