### ISSUE TITLE
recyclerview  onBindViewHolder  lottie reanim bug

### ISSUE THREAD

**Issue by iweey** [airbnb/lottie-android#672]
recyclerview  onBindViewHolder  lottie reanim bug

package com.baidu.adu.hmi.pilothud.ui.adapter;

import android.animation.Animator;
import android.content.Context;
import android.support.v4.content.ContextCompat;
import android.support.v7.widget.RecyclerView;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.view.WindowManager;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;

import com.airbnb.lottie.LottieAnimationView;
import com.airbnb.lottie.LottieComposition;
import com.baidu.adu.hmi.pilothud.R;
import com.baidu.adu.hmi.pilothud.utility.DensityUtils;

import adu.hmi.HudInfo;

public class OngoingHorizontalAdapter extends RecyclerView.Adapter<OngoingHorizontalAdapter.CustomViewHolder> {

    private Context mContext;
    private int mCount;
    private int mUIIndex = -1;
    private String mScene;
    private HudInfo mHudInfo;
    private int mLineWidth;
    private int mAnimPostion=-1;
    private LottieComposition mLottieComposition;
    private boolean mAnimFlag;

    public OngoingHorizontalAdapter(Context context) {
        this.mContext = context;
        LottieComposition.Factory.fromAssetFileName(mContext, "data2-0.json", (composition) -> {
            this.mLottieComposition = composition;
           });
    }

    @Override
    public CustomViewHolder onCreateViewHolder(ViewGroup viewGroup, int viewType) {
        View view = LayoutInflater.from(viewGroup.getContext()).inflate(R.layout.ongoing_item, null);
        CustomViewHolder viewHolder = new CustomViewHolder(view);
        return viewHolder;
    }

    @Override
    public void onBindViewHolder(CustomViewHolder holder, int position) {
//        position = mCount-position-1;
        //非常重要，去掉holder复用每个重新绘制
        //https://stackoverflow.com/questions/36313079/i-want-my-recyclerview-to-not-recycle-some-items
        holder.setIsRecyclable(false);
        if (mHudInfo == null) {
            return;
        }
        position = getItemCount() - position - 1;
        holder.txtView.setTextColor(ContextCompat.getColor(mContext, R.color.screen_background_black));
        holder.txtView.setText(mHudInfo.getLines(position).getName());
        Log.e("shen", position + "");
        if (mUIIndex <= 0) {

        }

//        holder.viewAllLy.setVisibility(View.INVISIBLE);
//
//        if(position< mUIIndex){
//            holder.viewAllLy.setVisibility(View.VISIBLE);
//            if (position==0){
//                holder.indicatorView.setImageDrawable(ContextCompat.getDrawable(mContext, R.drawable.ic_before_start));
//            }
//        }else if (position== mUIIndex){
//            holder.txtView.setTextColor(ContextCompat.getColor(mContext, R.color.solid_red));
//            if (mScene.equalsIgnoreCase("arriving")){
//
//            }else if (mScene.equalsIgnoreCase("arrived")){
//
//            }else if (mScene.equalsIgnoreCase("leaved")){
//
//            }
//
//        }else if (position> mUIIndex){
//
//        }

        if (position == 0 ) {
            holder.lineLy.setVisibility(View.GONE);
            holder.indicatorLy.setVisibility(View.VISIBLE);
            holder.indicatorAnim.setVisibility(View.GONE);
            holder.indicatorView.setVisibility(View.VISIBLE);
            holder.indicatorView.setImageDrawable(ContextCompat.getDrawable(mContext, R.drawable.ic_before_start));
        } else if (position == getItemCount() - 1 ) {
            holder.lineLy.setVisibility(View.VISIBLE);
            holder.lineAnim.setVisibility(View.GONE);
            holder.lineView.setVisibility(View.VISIBLE);
            holder.indicatorLy.setVisibility(View.VISIBLE);
            holder.indicatorAnim.setVisibility(View.GONE);
            holder.indicatorView.setVisibility(View.VISIBLE);
            holder.indicatorView.setImageDrawable(ContextCompat.getDrawable(mContext, R.drawable.ic_future_end));
        }
        int widthDp = DensityUtils.getWidth(mContext);
        int lineWidth = 60;
        if (getItemCount() >= 2) {
            lineWidth = (widthDp - 40) / (getItemCount() - 1);
        }
        ViewGroup.LayoutParams lp = holder.lineLy.getLayoutParams();
        lp.width = lineWidth;
        holder.lineLy.setLayoutParams(lp);

        //即将到站、已经到站
        if (position == mUIIndex && (mScene.equalsIgnoreCase("arriving") || mScene.equalsIgnoreCase("arrived"))) {
            holder.txtView.setTextColor(ContextCompat.getColor(mContext, R.color.solid_red));
//            mAnimPostion = position;
//            if (!holder.indicatorAnim.isAnimating()){
//                holder.indicatorLy.setVisibility(View.VISIBLE);
//                holder.indicatorAnim.setVisibility(View.VISIBLE);
//                holder.indicatorView.setVisibility(View.GONE);
//                showindicatorAnim(holder);
//            }
            if (!holder.indicatorAnim.isAnimating()){
                holder.indicatorLy.setVisibility(View.VISIBLE);
                holder.indicatorAnim.setVisibility(View.VISIBLE);
                holder.indicatorView.setVisibility(View.GONE);
                showindicatorAnim(holder);
            }
//            if (mAnimPostion!=position){
//                mAnimPostion = position;
//                if (!holder.indicatorAnim.isAnimating()){
//                    holder.indicatorLy.setVisibility(View.VISIBLE);
//                    holder.indicatorAnim.setVisibility(View.VISIBLE);
//                    holder.indicatorView.setVisibility(View.GONE);
//                    showindicatorAnim(holder);
//                }
//            }
        }

        //走过的路线置灰
        if (position < mUIIndex && position != 0) {
            holder.lineLy.setVisibility(View.VISIBLE);
            holder.lineAnim.setVisibility(View.GONE);
            holder.lineView.setVisibility(View.VISIBLE);
            holder.lineView.setBackgroundColor(ContextCompat.getColor(mContext, R.color.ongoing_gray));
            holder.indicatorLy.setVisibility(View.VISIBLE);
            holder.indicatorAnim.setVisibility(View.GONE);
            holder.indicatorView.setVisibility(View.VISIBLE);
            holder.indicatorView.setImageDrawable(ContextCompat.getDrawable(mContext, R.drawable.ic_before_mid));
        }

//        if (position == mUIIndex) {
//                holder.txtView.setTextColor(ContextCompat.getColor(mContext, R.color.solid_red));
//                holder.lineLy.setVisibility(View.VISIBLE);
//                holder.lineView.setVisibility(View.GONE);
//                LottieComposition.Factory.fromAssetFileName(mContext, "data-4.json", (composition) -> {
//                    holder.lineAnim.setVisibility(View.VISIBLE);
//                    holder.lineAnim.setComposition(composition);
//                    holder.lineAnim.loop(true);
//                    holder.lineAnim.playAnimation();
//                });
//        } else if (position == 0) {
//            holder.lineLy.setVisibility(View.GONE);
//            holder.lineView.setVisibility(View.GONE);
//            holder.lineAnim.setVisibility(View.GONE);
//        } else if (position< mUIIndex){
//            holder.lineView.setBackgroundColor(ContextCompat.getColor(mContext, R.color.ongoing_gray));
//        }
//        else {
//            holder.lineView.setBackgroundColor(ContextCompat.getColor(mContext, R.color.ongoing_blue));
//        }
//
//
//        if (position == 0) {
//            holder.indicatorView.setImageDrawable(ContextCompat.getDrawable(mContext, R.drawable.ic_future_end));
//        } else if (position == mUIIndex) {
//            LottieComposition.Factory.fromAssetFileName(mContext, "data2-1.json", (composition) -> {
//                holder.indicatorLy.findViewById(View.VISIBLE);
//                ViewGroup.LayoutParams params = holder.indicatorLy.getLayoutParams();
//                ViewGroup.MarginLayoutParams marginParams = null;
//                //获取view的margin设置参数
//                if (params instanceof ViewGroup.MarginLayoutParams) {
//                    marginParams = (ViewGroup.MarginLayoutParams) params;
//                } else {
//                    //不存在时创建一个新的参数
//                    //基于View本身原有的布局参数对象
//                    marginParams = new ViewGroup.MarginLayoutParams(params);
//                }
////                RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT);
////                layoutParams.setMargins(-8,0,0,0);
////                holder.indicatorLy.setLayoutParams(layoutParams);
//                holder.indicatorView.setVisibility(View.GONE);
//                holder.indicatorAnim.setVisibility(View.VISIBLE);
//                holder.indicatorAnim.setComposition(composition);
//                holder.indicatorAnim.loop(true);
//                holder.indicatorAnim.playAnimation();
////                holder.indicatorAnim.setVisibility(View.GONE);
//            });
//        } else if (position == mUIIndex +1){
//            holder.indicatorView.setImageDrawable(ContextCompat.getDrawable(mContext, R.drawable.ic_before_end));
//        }
//        else if (position == 0) {
//            holder.indicatorView.setImageDrawable(ContextCompat.getDrawable(mContext, R.drawable.ic_before_start));
//        } else if (position < mUIIndex +1){
//            holder.indicatorView.setImageDrawable(ContextCompat.getDrawable(mContext, R.drawable.ic_before_mid));
//        }
//        else {
//            holder.indicatorView.setImageDrawable(ContextCompat.getDrawable(mContext, R.drawable.ic_future_mid));
//        }

    }

    @Override
    public int getItemCount() {
        if (mHudInfo != null && mHudInfo.getLinesList() != null) {
            return mHudInfo.getLinesList().size();
        } else {
            return 3;
        }
    }

    public void showindicatorAnim(CustomViewHolder holder) {
        if (mAnimFlag){return;}
        holder.indicatorAnim.addAnimatorListener(new Animator.AnimatorListener() {
            @Override
            public void onAnimationStart(Animator animation) {
                Log.e("Animation:","start");
                mAnimFlag = true;
            }

            @Override
            public void onAnimationEnd(Animator animation) {
                Log.e("Animation:","end");
                mAnimFlag = false;
                //Your code for remove the fragment
                try {

                } catch(Exception ex) {
                    ex.toString();
                }
            }

            @Override
            public void onAnimationCancel(Animator animation) {
                mAnimFlag = false;
                Log.e("Animation:","cancel");
            }

            @Override
            public void onAnimationRepeat(Animator animation) {
                Log.e("Animation:","repeat");
            }
        });

        holder.indicatorAnim.setVisibility(View.VISIBLE);
        holder.indicatorAnim.setComposition(this.mLottieComposition);
        holder.indicatorAnim.loop(true);
        holder.indicatorAnim.playAnimation();

//        LottieComposition.Factory.fromAssetFileName(mContext, "data2-0.json", (composition) -> {
//            ViewGroup.LayoutParams params = holder.indicatorLy.getLayoutParams();
//            ViewGroup.MarginLayoutParams marginParams = null;
//            //获取view的margin设置参数
//            if (params instanceof ViewGroup.MarginLayoutParams) {
//                marginParams = (ViewGroup.MarginLayoutParams) params;
//            } else {
//                //不存在时创建一个新的参数
//                //基于View本身原有的布局参数对象
//                marginParams = new ViewGroup.MarginLayoutParams(params);
//            }
////                RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT);
////                layoutParams.setMargins(-8,0,0,0);
////                holder.indicatorLy.setLayoutParams(layoutParams);
//            holder.indicatorAnim.setVisibility(View.VISIBLE);
//            holder.indicatorAnim.setComposition(composition);
//            holder.indicatorAnim.loop(true);
//            holder.indicatorAnim.playAnimation();
//        });
    }

    public void updateContent(HudInfo info) {
        mHudInfo = info;
        mCount = mHudInfo.getLinesCount();
        mLineWidth = getLineWidth();
        mUIIndex = info.getIndex();
        mScene = info.getScene();
    }

    private int getLineWidth() {
        WindowManager wm = (WindowManager) mContext.getSystemService(Context.WINDOW_SERVICE);
        int width = wm.getDefaultDisplay().getWidth();
        int lineWidth = 0;
        if (mCount != 0) {
            lineWidth = (int) ((width - 100) / mCount);
        }
        return DensityUtils.px2dip(mContext, ((float) lineWidth));
    }

    class CustomViewHolder extends RecyclerView.ViewHolder {
        RelativeLayout viewAllLy;
        RelativeLayout lineLy;
        ImageView lineView;
        LottieAnimationView lineAnim;
        RelativeLayout indicatorLy;
        ImageView indicatorView;
        LottieAnimationView indicatorAnim;
        TextView txtView;

        CustomViewHolder(View itemView) {
            super(itemView);
            viewAllLy = itemView.findViewById(R.id.view_ly);
            lineLy = itemView.findViewById(R.id.line_ly);
            lineAnim = (LottieAnimationView) itemView.findViewById(R.id.line_anim);
            lineView = itemView.findViewById(R.id.line_view);
            indicatorLy = itemView.findViewById(R.id.indicator_ly);
            indicatorView = itemView.findViewById(R.id.indicator_view);
            indicatorAnim = (LottieAnimationView) itemView.findViewById(R.id.indicator_anim);
            txtView = (TextView) itemView.findViewById(R.id.txt_view);
        }

    }
}

**Comment by gpeal** [comment]
@iweey Can you explain the problem more specifically and provide the broken animation or a sample app the reproduces this?
I'm going to close this for now but feel free to reopen this if you can provide more specific information.
