### ISSUE TITLE
2.5.1: More visibility issues

### ISSUE THREAD

**Issue by mpeng3** [airbnb/lottie-android#678]
Following up on issue #636, there is an additional class visibility issue.

When using Lottie v2.5.1 in a project in Android Studio 3.0.1, the `KeyPath` class constructor also shows a library-only API restriction warning:
KeyPath constructor can only be called from within the same library

**Comment by gpeal** [comment]
@mpeng3 [this](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/model/KeyPath.java#L48) constructor? It's not restricted.

**Comment by DominikusKrueger** [comment]
I have the very same problem using Intellij 2018.1. Strangely, when I look into the code the constructor does not seem to be restricted (I do not see the anticipated annotation).

**Comment by Tywholland** [comment]
I'm also seeing the same thing when starting a fresh project in Android Studio (v3.1.1) and Lottie 2.5.3. I'll create a new issue as well since it's in 2.5.3 now.
