### ISSUE TITLE
compile error happens when compileSdkVersion<26,because the code in BaseLottieAnimator.java "Build.VERSION.SDK_INT >= Build.VERSION_CODES.O"

### ISSUE THREAD

**Issue by cuixbo** [airbnb/lottie-android#680]
Compile error happens in BaseLottieAnimator.java

void notifyStart(boolean isReverse) {
    for (Animator.AnimatorListener listener : listeners) {
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        listener.onAnimationStart(this, isReverse);
      } else {
        listener.onAnimationStart(this);
      }
    }
  }

In my project ,the compileSdkVersion must small than 26,while when compileSdkVersion<26,we can not find Build.VERSION_CODES.O.

I suggest use 26 instead of Build.VERSION_CODES.O.
For example: if (Build.VERSION.SDK_INT >= 26)

**Comment by gpeal** [comment]
This code should be precompiled in the lottie library. If this isn't the case for you, attach a sample project that repros this and reopen.
