### ISSUE TITLE
can't import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [airbnb/lottie-android#681]
I get this error, even though I've tried to update all :

![image](https://user-images.githubusercontent.com/5357526/37391941-81e9b2ec-2775-11e8-8239-5334e924e7e9.png)

**Comment by gpeal** [comment]
@AndroidDeveloperLB Did you resolve this? This is most likely specific to something on your computer and it would be hard for me to know what to do (if anything) on my end.

**Comment by AndroidDeveloperLB** [comment]
@gpeal No, that's why I wrote this thread. 
I've tried on another PC. Still got the same issue:

![image](https://user-images.githubusercontent.com/5357526/37447437-ca811a9e-282a-11e8-8d10-5dc001acf4a3.png)


Just install the latest IDE version on Windows:
Android Studio 3.2 Canary 6
Build #AI-173.4640885, built on March 8, 2018
JRE: 1.8.0_152-release-1136-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by gpeal** [comment]
Sorry, I'd like to help out with the ResourceSet issue but I can't repro it and the internet doesn't leave many clues. If other people start having this problem, I'll spend more time investigating though. Do try clearing your global gradle caches. I'm not sure what the path on Windows is.

**Comment by AndroidDeveloperLB** [comment]
Path of what? 
And by gradle cache, I used file->invalidate-cache/restart . 
Still occurs.
Here's more information:

![image](https://user-images.githubusercontent.com/5357526/37450695-945dcf86-2837-11e8-8500-e7f499c19403.png)

I've now tried to use a stable version of gradle (3.0.1), and it works fine.
This is very different than what we have on the Play Store.
Seems to be an issue with preview version of the gradle.
Please check it out. It might have an issue when the preview become final version.

**Comment by gpeal** [comment]
@AndroidDeveloperLB Sounds like you got this resolved, correct?
What was the problem?

**Comment by gpeal** [comment]
@AndroidDeveloperLB Which preview version are you referring to? This project uses [Gradle 4.4 stable](https://github.com/airbnb/lottie-android/blob/master/gradle/wrapper/gradle-wrapper.properties).

**Comment by AndroidDeveloperLB** [comment]
@gpeal The one you get from :

 classpath 'com.android.tools.build:gradle:3.2.0-alpha06'
