### ISSUE TITLE
conflict problem from 26 to 27 sdk version

### ISSUE THREAD

**Issue by leandro1995** [airbnb/lottie-android#685]
in the last version of lottie there is a conflict of versions use version 27, when updating android to version 3.0.1 it is still generated with the version 26 debito that is the version of android oreo version 27 is of android P that is still in beta that's why I can suggest that the version they have is down to version 26 debit that even the majority of programmers are still in 26 per oreo and change the version of sdk is not very nice

![screen shot 2018-03-14 at 7 48 55 pm](https://user-images.githubusercontent.com/25448691/37438704-189131f6-27c2-11e8-8912-b315b55d3962.png)

**Comment by gpeal** [comment]
@leandro1995 26 is 8.0, 27 is 8.1. Both are Oreo. 28 is P. 

You should actually update to 27. However, you can exclude dependencies if you need like this:
`compile ('com.airbnb.android:lottie:2.5.1'){ exclude group: 'com.android.support' }`

**Comment by renasti** [comment]
> @ leandro1995 26 é 8,0, 27 é 8,1. Ambos são Oreo. 28 é P.
> 
> Você deve realmente atualizar para 27. No entanto, você pode excluir dependências se precisar assim:
> `compile ('com.airbnb.android:lottie:2.5.1'){ exclude group: 'com.android.support' }`

Solved my problem
