### ISSUE TITLE
Minimum supported Gradle version is 3.3. Current version is 2.14.1

### ISSUE THREAD

**Issue by navinpd** [airbnb/lottie-android#69]
While building Lottie sample android project I am getting build error as:
Minimum supported Gradle version is 3.3. Current version is 2.14.1. If using the gradle wrapper, try editing the distributionUrl.

**Comment by navinpd** [comment]
While building Lottie sample android project I am getting build error as:
Minimum supported Gradle version is 3.3. Current version is 2.14.1. If using the gradle wrapper, try editing the distributionUrl.

**Comment by gpeal** [comment]
@navinpd When you opened the project did you:
1) Open the root of the repo, not LottieSample
2) Use the default gradle wrapper or choose a custom one?

**Comment by navinpd** [comment]
I tried using LottieSample got above mentioned error.
While importing root of repo I was getting another error as:
Error running Lottie sample. This version of Android Studio is incompatible with Gradle plugin used. 
Disabling instant run helped running it.
Thanks.

**Comment by rjk40** [comment]
Grade version 3.3
