### ISSUE TITLE
Animation flashes in middle of animation (when morphing shape)

### ISSUE THREAD

**Issue by kuoliangkwong** [airbnb/lottie-android#692]
[test.zip](https://github.com/airbnb/lottie-android/files/1824418/test.zip)

It happens when i use 2.5.1. It also happens when i try it at https://www.lottiefiles.com by drag and drop the json file. Strangely, when i use lottie demo app from Google Play, it works fine, but terrible performance. I'm guessing the reason Lottie demo app works is tat it's using software rendering by default instead of hardware.

**Comment by gpeal** [comment]
There is some performance overhead to mattes and masks and you have an alpha inverted mask on Layer 1 Outlines 2. As a result, 2/3 of the total rendering time is on that layer.

I'm about to update the sample app on the play store with a totally new one that will show you the [render times per layer](http://airbnb.io/lottie/android/performance.html#render-times-per-layer).

Regarding the flashes, I don't see it. Can you attach a video?

**Comment by kuoliangkwong** [comment]
[2018_03_20_15_42_13.zip](https://github.com/airbnb/lottie-android/files/1828362/2018_03_20_15_42_13.zip)

It has a very short flash, at about 00:00:02 s

**Comment by gpeal** [comment]
@kuoliangkwong Lottie plays everything at 60fps. What you are seeing is the opacity on frame 25-26 for "Layer 2 Outlines" in between 25 and 26 which AE does not render. You have a keyframe on frame 25 with opacity 0 and 26 with opacity 1 which causes it to fade in (and same with the letters fading out). As a result, the flash you are seeing is a crossfade between the letters and square.

I suggest using toggling to using a hold keyframe or adjusting your keyframes slightly.
