### ISSUE TITLE
Templates of animation JSON for android.

### ISSUE THREAD

**Issue by dryganets** [airbnb/lottie-android#695]
I have an extension of Lottie for android that I did for Skype. We would like to contribute it back to Lottie.

We had a plenty of the animations which are stored as assets in order to don't pass all of the animation data over the bridge again and again. The trick is that we have many animations which are different only in color scheme. In order to simplify the maintenance, I added templates support.

This change itself is pretty small and fits the library design well.

**The only concern is that I'm bringing an additional third-party library to the project.**
Currently, I'm using http://www.stringtemplate.org/. As it is relatively small and supported on both iOS and Android.

**I would like to know your opinion on that.**

This PR first of the building blocks of that change:
https://github.com/airbnb/lottie-react-native/pull/298

Next will be two PR's (one to lottie-react-native and another to lottie-android) which adds an additional parameter `templateContext` and it's usage.

Thank you!

**Comment by gpeal** [comment]
@dryganets Android and iOS just added full and comprehensive dynamic property APIs
[Android docs](http://airbnb.io/lottie/android/dynamic.html)
[iOS docs](http://airbnb.io/lottie/ios/dynamic.html)

How about bridging those APIs for React Native instead? That would be a contribution that would be great for the community.

**Comment by dryganets** [comment]
@gpeal, looks pretty similar to what I'm doing. The PR I made will be pre-requirement anyway. Will do the similar change for iOS. The dependent properties should be applied to the view simultaneously.

**Comment by gpeal** [comment]
I'm going to close this here since there is nothing actionable on Android.
