### ISSUE TITLE
can't debug in my android project

### ISSUE THREAD

**Issue by ericfjl** [airbnb/lottie-android#696]
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

**Comment by gpeal** [comment]
I don't think this is lottie related

**Comment by boyw165** [comment]
@ericfjl : You could try the answer under this thread, https://stackoverflow.com/questions/49044782/duplicate-zip-entry-classes-jarandroid-support-design-widget-coordinatorlayout

I guess it is the duplicate of `CoordinatorLayout$Behavior`.

Following is my solution
---

I upgraded the support library version to almost latest (e.g. `27.1.0`) and it was yet enough. Then I checked the dependencies and noticed that one 3rd party library I use depends on the old version support `design` library, where it contains support design library.

**Comment by gpeal** [comment]
@boyw165 You should always use the latest support library. If you need to exclude it, you can as with any other gradle dependency:
compile ('com.airbnb.android:lottie:2.5.1'){ exclude group: 'com.android.support' }

**Comment by sunnnydaydev** [comment]
> Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> 
> > java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

how do you resolve it ？

**Comment by gpeal** [comment]
@sunnnydaydev This is not lottie related.
