### ISSUE TITLE
exported json show perfect in ios but not in android

### ISSUE THREAD

**Issue by AhmadNemati** [airbnb/lottie-android#697]
why all my exported project show perfect in ios but in android not perfectly?
my json 
[data.json.zip](https://github.com/airbnb/lottie-android/files/1828791/data.json.zip)

**Comment by gpeal** [comment]
@AhmadNemati What is wrong with it?

**Comment by IveSix** [comment]
same issue, they don't scale correctly

**Comment by gpeal** [comment]
@AhmadNemati @IveSix can you attach the aep?
