### ISSUE TITLE
Request: in Showcase section, show how to use a progress-like animation that ends with a result

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [airbnb/lottie-android#698]
Sometimes, we have a progress animation that contains the ending result.
For example:
Suppose you have 100 frames, and the last 10 frames are for the ending result.
The animation would keep playing 0..89 , and when we decide we want to finish with a result, we play frames 90..99 (after we reached 89, to have a smooth transition).

We could even have multiple endings : success, error, ...

Can you please add such a thing in the sample, to show how to do it?

**Comment by AndroidDeveloperLB** [comment]
I know I can use something like that:

        animation_view.addAnimatorUpdateListener(object : ValueAnimator.AnimatorUpdateListener {
            var count = 0
            override fun onAnimationUpdate(animation: ValueAnimator?) {
                if (animation_view.frame == 30) {
                    if (count == 5) {
                        // just a simulation of finishing the progress
                        animation_view.loop(false)
                    } else {
                        animation_view.frame = 0
                        ++count
                    }
                }

                Log.d("AppLog", "" + animation_view.frame.toString())
            }
        })


But maybe it's possible to do something else?
Maybe I could add groups of frames, for the inner animations, and then choose which to play?

Or is it better to load a new animation instead? If so, how?

**Comment by AndroidDeveloperLB** [comment]
The next code, for example, doesn't work well:

in xml:

        lottie_loop="true"

in code:

        animation_view.setOnClickListener {
            animation_view.removeAllUpdateListeners()
        }

        animation_view.addAnimatorUpdateListener(object : ValueAnimator.AnimatorUpdateListener {
            override fun onAnimationUpdate(animation: ValueAnimator?) {
                if (animation_view.frame == 120)
                    animation_view.frame = 0
                Log.d("AppLog", "" + animation_view.frame.toString())
            }
        })

**Comment by gpeal** [comment]
@AndroidDeveloperLB Use the setMinAndMaxFrame or Progress API then update the max progress to 1f and set repeatCount to 0 when it's done.
I don't have time right now to make a showcase for this but I would accept a PR.

**Comment by AndroidDeveloperLB** [comment]
@gpeal The function `setMinAndMaxFrame` doesn't seem to do anything.
The animation I use has 0..179 frames.
When I use this:

    animation_view.setMinAndMaxFrame(0,119)

- it will still play to the end (meaning it reaches frame 179).

About Progress API, I haven't read about it yet. Where can I read about it?

**Comment by AndroidDeveloperLB** [comment]
I've searched now in the docs. There is no Progress API. Maybe you mean something else.
There is also no mention of the case I'm talking about. 
That's why I think it's best to create a sample for this.

**Comment by hendra4ditya** [comment]
qw8LMZ

**Comment by AndroidDeveloperLB** [comment]
@hendra4ditya I don't understand. Wrong post?
