### ISSUE TITLE
turn on the hardware acceleration,animation will be very stuck

### ISSUE THREAD

**Issue by hyne-shan** [airbnb/lottie-android#700]
Hi

I am very happy to use lottie, which greatly reduced my workload. Currently, I am optimizing performance issues. I have found some problems with the animation of attachments, but I do not know how to optimize! When I turn on the hardware acceleration, this animation will be very stuck. The lottie version  is 2.5.1. I hope you can tell me where the problem is.

Best or Best Wishes

json file
https://onepluscn-my.sharepoint.com/:u:/g/personal/hyne_shan_oneplus_net/EfD7y_UlSRFIp4Sf97JOitwB5IiRqRQCVJYCd8UTLUeRTQ?e=wo8J8H

**Comment by hyne-shan** [comment]
Please forgive me create issue. I sent an email the day before yesterday, but no one responded to me.

**Comment by gpeal** [comment]
@hyne-shan Hardware acceleration is not always more performant. It depends on the animation itself.
http://blog.danlew.net/2015/10/20/using-hardware-layers-to-improve-animation-performance/
