### ISSUE TITLE
Push 2.5.2 to Maven centeral

### ISSUE THREAD

**Issue by agrosner** [airbnb/lottie-android#701]
it appears that lottie 2.5.2 is not published and thus gradle cannot find the version: https://mvnrepository.com/artifact/com.airbnb.android/lottie

**Comment by gpeal** [comment]
2.5.2 was a release just for the sample app. I realize it's confusing but it's a one time thing.

**Comment by gpeal** [comment]
2.5.1 is the latest

**Comment by agrosner** [comment]
it says in the read me:
```
dependencies {
  compile 'com.airbnb.android:lottie:2.5.2'
}
```
which then is wrong.
It should instead say:
```
dependencies {
  implementation 'com.airbnb.android:lottie:2.5.1'
}
```
if 2.5.1 is the latest and `compile` is deprecated.

**Comment by hendra4ditya** [comment]
Pada tanggal Sen, 26 Mar 2018 20.08, Andrew Grosner <
notifications@github.com> menulis:

**Comment by gpeal** [comment]
I'm aware. I pushed 2.5.2 for the sample app. I'll push a release or update the docs but just use 2.6.1
