### ISSUE TITLE
Lottie App Crashes at the Lottiefiles Activity-Recent tab

### ISSUE THREAD

**Issue by Godwyyn** [airbnb/lottie-android#702]
#### Expected behavior
After navigating to the the Recent tab of the Lottiefiles Activity by clicking on  the lottiefiles option at the bottom navigation menu at the Home Activity, I should be able scroll through the list of the recent files without issue.

#### Actual behavior
At the Lottiefiles activity of the app and by selecting  the recent tab. Scrolling through the list of recent files till the end/bottom causes the Lottie app to crash and exit.

#### How to reproduce
Write here every possible detail to reproduce the bug.
- Download the Lottie App from Play Store
- Launch the App
- At the Home Screen, select "Lottiefiles" option at the bottom navigation menu

![Screenshot_20180322-074100.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521701981/gaxeuzqhcz3yhm56xelu.png)

- At the Lottiefiles activity, select the "Recent" tab
- When at the recent tab scroll down to the end

![Screenshot_20180322-074133.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521702010/o9gpihou79ypcf8jqimd.png)

- The App crashes and exit

![Screenshot_20180322-074116.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521702039/xfrjbago00gkddmopnvs.png)

- Version: Lottie Version 2.5.2
* Operating system: Tecno-C7: Android 6.0

#### Recording Of The Bug

https://www.youtube.com/watch?v=Lp7Lei8BqUQ
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@godwyn/lottie-app-crashes-at-the-lottiefiles-recent-tab">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by gpeal** [comment]
@Godwyyn Can you post the stack trace? This doesn't repro for me.

**Comment by gpeal** [comment]
There was an animation that caused this a few days ago but it's fixed now

**Comment by Godwyyn** [comment]
Yeah...it has been fixed,am not getting the error again and before then I
had already posted the bug report.
