### ISSUE TITLE
Min and Max Frame on View not Respected on initial load.

### ISSUE THREAD

**Issue by agrosner** [airbnb/lottie-android#704]
I am setting a min and max from on the animation (as I've segmented it off into 3 separate pieces as part of a `ViewPager`)
```kotlin
animationView.apply {
            imageAssetsFolder = "images"
            setAnimation("sc_onboarding.json", Strong)
            setMinAndMaxFrame(0, ANIMATION_FIRST_END_FRAME)

            addAnimatorListener(animatorListener(onAnimationEnd = {
                isClicked = false
                setAnimationBasedOnCurrentPage()
            }))
        }
```

when the composition is loaded by lottie, it overrides the preselected `minFrame` and `maxFrame` here:
```java
 public void setComposition(LottieComposition composition) {
    this.composition = composition;
    setMinAndMaxFrames((int) composition.getStartFrame(), (int) composition.getEndFrame());
    setFrame((int) frame);
    lastFrameTimeNs = System.nanoTime();
  }
``` 
We need it to A): respect the values when set before image loads. or B): provide a callback for the internal `OnCompositionLoadedListener` in the `LottieAnimationView` file. Then update docs to specify that's when you should modify those values.

**Comment by gpeal** [comment]
Fixed by https://github.com/airbnb/lottie-android/pull/694
