### ISSUE TITLE
Bug: sample app "bullseye" doesn't have its moving point going to the precise location

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [airbnb/lottie-android#706]
I get this:

![image](https://user-images.githubusercontent.com/5357526/37922242-b79a1e4a-3134-11e8-9806-d750194a2a98.png)

**Comment by gpeal** [comment]
It's just a placeholder demo with some sample code.

**Comment by AndroidDeveloperLB** [comment]
@gpeal  Well it looks bad

**Comment by gpeal** [comment]
Yup, it's still a WIP. Thanks for the feedback.
