### ISSUE TITLE
App Crashes when trying to search at the Lottiefiles Activity

### ISSUE THREAD

**Issue by Godwyyn** [airbnb/lottie-android#709]
#### Expected behavior
After navigating to the Lottiefiles activity of the app,and selecting the search tab. When i typed in a word at the edit text and click on the search icon, I expected the app to show me the search result.

#### Actual behavior
When I type in any  text at the edit text and click on the search icon the app crashes and exit.

#### How to reproduce
   - Download the Lottie App from Play Store
   -  Launch the App
   - At the Home Screen, select "Lottiefiles" option at the bottom navigation menu
   - At the Lottiefiles activity, select the "Search" tab
   - Type in any word or text at the search pane
   - Click on the Search icon
   - The app crashes and exit

 -  Version: Lottie Version 2.5.2
 -  Operating system: Infinix Hot: Android 4.4.2

#### Recording Of The Bug
https://www.youtube.com/watch?v=Y-d1ehfVgb8
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@godwyn/app-crashes-when-trying-to-search-at-the-lottiefiles-activity">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by gpeal** [comment]
@Godwyyn what is the stack trace? That doesn't repro for me.
