### ISSUE TITLE
Add image support

### ISSUE THREAD

**Issue by est7** [airbnb/lottie-android#71]
my animator need to operate some .png img ,build a new folder "images" and  put  .png file in it .
json like this:"
{
  "assets": [
    {
      "id": "image_0",
      "w": 200,
      "h": 120,
      "u": "images/",
      "p": "img_0.png"
    }
  ],
...
} "
but I has run app ,can't see  anything without empty

**Comment by zackpollard** [comment]
I would also like to know this, from what I can see this either isn't supported by lottie yet or isn't documented anywhere.

**Comment by gpeal** [comment]
@est7 @zackpollard Lottie doesn't yet support images but I've gotten a few requests for it so I'll look in to supporting it in future versions.

**Comment by zackpollard** [comment]
That would be great, this is a great library for animations, and would be great if it supported animations using static content that can't be vectorised too :)

**Comment by lizheng98** [comment]
Me really looking forward

**Comment by weiweixiaoyi** [comment]
I am looking forward to it.

**Comment by gpeal** [comment]
1.5.0 is now out!

**Comment by MrGatsby2** [comment]
hi,man,here is the image animation file which worked wrong. you can get all the files you need just change the postfix to .zip and upzip it.
[eyesafe.txt](https://github.com/airbnb/lottie-android/files/795939/eyesafe.txt)

**Comment by gpeal** [comment]
@MrGatsby2 I figured out the issue. It was what I suspected.
For this particular animation, I highly suggest making your image with shapes in after effects. The file will be smaller and will scale to any size with no artifacts if you do that and it'll use much less memory.

**Comment by MrGatsby2** [comment]
got it,thanks

**Comment by angarron** [comment]
Thanks for the wonderful work @gpeal ! Is there any way to use `.svg` files instead of `.png`? When I try to use `.svg` files, I get a lot of this line in the logs:

```
02-28 17:20:30.149 24768-24768/com.discord D/skia: --- SkAndroidCodec::NewFromStream returned null
```

I think it is worth asking in case I am just making a mistake configuring my `LottieAnimationView` :)

**Comment by gpeal** [comment]
@angarron Lottie doesn't load svg files. You should just import the svg into After Effects so that it's actually part of the animation.

**Comment by gpeal** [comment]
Also, that log line isn't from Lottie.

**Comment by angarron** [comment]
That log line isn't from Lottie directly, no, but Lottie eventually calls into code that logs that if you (erroneously, as I was doing) point it toward an animation which itself points toward SVGs the same way that it would point toward PNGs.

That is a valid configuration for bodymovin exports, but it's not a very useful one AFAIK because (as you mentioned and as we later discovered) there is After Effects support for directly including the images inside as part of the animation via "Create Shape from Vector Layer". Worked like a charm, thanks!

**Comment by Janardhanrao** [comment]
please anyone post example project with supports image animation in android....
