### ISSUE TITLE
App Crashes when choosing a file for Preview

### ISSUE THREAD

**Issue by Godwyyn** [airbnb/lottie-android#710]
#### Expected behavior
After launching the app and navigating to the Preview Activity,when I clicked on the "Open a file" option to select a file for preview and select on an image file or a text file I was expecting the app to either load the file for preview or prompt a message that I have selected the wrong file format. Also when I click on the "Scan a QR code " option was expecting a preview or a dialog if the QR code is not valid.

#### Actual behavior
When I click on the "Open a file" option and chose an image file or a text file, the app crashes. Also when I pick up any QR code and scan the app crashes.

#### How to reproduce
- Download the Lottie app from Playstore
- Launch the app
- From the bottom navigation menu click on "Preview"
- Click on "Open a file" or " Scan a QR code "
- Select a file or scan a QR code respectively
- App crashes on result

* Version: Lottie Version 2.5.2
* Operating system: Infinix Hot, Android Kitkat

#### Recording Of The Bug
https://www.youtube.com/watch?v=mJ5o251TiwQ
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@godwyn/app-crashes-when-choosing-a-file-for-preview">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by gpeal** [comment]
@Godwyyn Why are you trying to do that?

**Comment by gpeal** [comment]
Fixed by #830

**Comment by scottruigrok** [comment]
How did you make the files used in After Effects? I also had this problem when I used files exported from Experience Design. I recreated them in Illustrator and now the phone wont crash when using  Lottie Preview.

The animation also couldn't be used in Xcode, but after using Illustrator for the screens it did work.
