### ISSUE TITLE
'com.airbnb.android:lottie:2.5.2' not compiling

### ISSUE THREAD

**Issue by kdblue** [airbnb/lottie-android#711]
//Not Compiling 
```
dependencies {
  compile 'com.airbnb.android:lottie:2.5.2'
}
```
change to 
```
dependencies {
  compile 'com.airbnb.android:lottie:2.5.1'
}
```
Thank You !

**Comment by irfaan008** [comment]
I am also facing the similar issue

**Comment by md0092651** [comment]
Failed to resolve: com.airbnb.android:lottie:2.5.2 

Solved it using Failed to resolve: com.airbnb.android:lottie:2.5.1

**Comment by gpeal** [comment]
2.5.3 is out

**Comment by ranjithrayapati** [comment]
same issue with 2.5.3
