### ISSUE TITLE
Android having lag issues

### ISSUE THREAD

**Issue by ctgstudios** [airbnb/lottie-android#713]
Creating an animation using After Effects (CC 2018) and, though the animation is smooth in iOS, the frame rate drops in Andriod
File can be found here: [www.colorthegrayscale.com/tmg-hollyanimationFINAL.aep](url)
File isn't using anything that isn't supported, so I'm not sure what to make of it.

I am using the Lottie player on my Andriod device to view the animation.

**Comment by alexrest** [comment]
I'm having frame dropping issues too... why was this ticket closed? Did you find a solution?
