### ISSUE TITLE
Fatal Exception: android.os.BadParcelableException ClassNotFoundException when unmarshalling: com.airbnb.lottie.LottieAnimationView$SavedState

### ISSUE THREAD

**Issue by shishram** [airbnb/lottie-android#714]
Version used: com.airbnb.android:lottie:2.5.1

stack trace:-

android.os.Parcel.readParcelableCreator (Parcel.java:2295)
android.os.BaseBundle.putBoolean (BaseBundle.java:333)
android.support.v4.app.Fragment.setUserVisibleHint (Fragment.java:960)
 android.support.v4.app.FragmentStatePagerAdapter.instantiateItem (FragmentStatePagerAdapter.java:121)
 com.android.internal.os.ZygoteInit.main (ZygoteInit.java:697)

**Comment by moni890185** [comment]
Are you running the support library version 27.1.0? I have faced a similar issue, it does not look related to lottie but it seems to be a bug on that specific support lib Version. Ref. https://issuetracker.google.com/u/0/issues/74130311. Hope that helps.

**Comment by shishram** [comment]
@moni890185 Yes, support library version is 27.1.0. so any fix you have found? degrading the version or something?

**Comment by moni890185** [comment]
@shishram for now just degraded the version and waiting for a stable release with that fixed.
