### ISSUE TITLE
Request: allow to view a single animation frame in layout editor

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [airbnb/lottie-android#719]
Currently, if I use `LottieAnimationView` in XML, that has its `lottie_rawRes` defined, I still see an empty content.

Please allow to view it somehow in the layout editor. 

Maybe add `tools:frameToShow` attribute, to let us choose which frame of the animation to show on the layout editor.

**Comment by gpeal** [comment]
I would accept a PR for this.

**Comment by AndroidDeveloperLB** [comment]
Is it possible though?

**Comment by gpeal** [comment]
@AndroidDeveloperLB No idea. I haven't tried. Do you know?

**Comment by AndroidDeveloperLB** [comment]
Well the docs don't talk about getting a single frame from the animation:
http://airbnb.io/lottie/android/android.html#sample-app
I've also tried to search for "bitmap" in the project, but I don't think any of what I've seen allows to get a single image out of a single frame from the Lottie animation.

So this is why I asked about it...

**Comment by AndroidDeveloperLB** [comment]
Maybe consider adding an API to get a single Bitmap from a given animation?

**Comment by gpeal** [comment]
There is a [setFrame](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L843) API.

If the layout preview only renders bitmaps then that will be out of the scope of Lottie. I think the layout preview can actually render a set of Android drawing commands so it may actually be able to just render

**Comment by AndroidDeveloperLB** [comment]
Even better. You mean I can get a Drawable out of a specific frame of it?

**Comment by gpeal** [comment]
@AndroidDeveloperLB Just tried forcing the layout preview to render Lottie and it seems like its rendering is clearly limited in functionality. This is what the lottie logo looks like:
![image](https://user-images.githubusercontent.com/1307745/42743727-41f904e6-887b-11e8-99a8-74ddbd810aee.png)

**Comment by AndroidDeveloperLB** [comment]
What am I seeing?
And why close it? Have you added this feature?
