### ISSUE TITLE
Json animation not working when masks applied

### ISSUE THREAD

**Issue by kloskow** [airbnb/lottie-android#720]
Hi there, my .json file does not appear in Lottiefile preview nor standalone LottieUWP.sample. On the other hand everything looks totally in order when I run html via a browser. I use subtract masks to achieve the reveal effect. When the mask layer is fully removed from the composition within AE and exported with no mask layer, image shows up with no issues.
any help would be greatly appreciated.

Please find the attached project files.
[demo.1.zip](https://github.com/airbnb/lottie-android/files/1889159/demo.1.zip)

**Comment by gpeal** [comment]
It seems to render fine for me
![recording](https://user-images.githubusercontent.com/1307745/39705589-20ab602e-520f-11e8-9148-65a9b0f174f7.gif)
