### ISSUE TITLE
Request: in sample app, allow to see time instead of frames

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [airbnb/lottie-android#721]
Have a toggle or something, to show time instead of frames, including how long exactly is the animation duration.

I'm talking about this:

![image](https://user-images.githubusercontent.com/5357526/38498058-e3525a48-3c0b-11e8-98a4-385ca2d1b21c.png)

Frames aren't enough to know how long the animation takes. It can be 60FPS, and can be 2FPS...
Maybe it's a good idea to show the FPS too :)

**Comment by AndroidDeveloperLB** [comment]
Why close it?

**Comment by markstonehouse** [comment]
@AndroidDeveloperLB because it has been resolved now as per #814

**Comment by AndroidDeveloperLB** [comment]
We have it now?
Cool!
