### ISSUE TITLE
editing text in the json file

### ISSUE THREAD

**Issue by adidazzler16** [airbnb/lottie-android#723]
Hi
I am trying to update the text embeded in the lottie json files. Can I do that directly in json files, unfortunately I do not have access to original AEP files. Though I have already made the changes in json file for the text but it doesn't reflect.

I am sorry I am pretty new to Lottie.
I am using latest lottie version 2.5.4
Thanks,
Adi

**Comment by gpeal** [comment]
You can do it with a TextDelegate. There is an example [here](https://github.com/airbnb/lottie-android/blob/master/LottieSample/src/main/kotlin/com/airbnb/lottie/samples/FontFragment.java#L40).

**Comment by AhmadKabi** [comment]
I have tried TextDelegate but animation plays uncorrectly. 
when i don't use this class, animation is perfectly played
#774

**Comment by shirley737** [comment]
Hello @gpeal , the link to TextDelegate doesn't exist anymore, can you update that or link me the right documentation? Thank you!
