### ISSUE TITLE
cache

### ISSUE THREAD

**Issue by paradise0love** [airbnb/lottie-android#725]
It takes a while to show the animation for the first time,Can it be cached in advance in some places?

**Comment by gpeal** [comment]
Yes, you can. There are some docs [here](http://airbnb.io/lottie/android/android.html#getting-started).

**Comment by shoeguy** [comment]
The link is to the "getting started" page and does not appear to address how to preload the cache with images.  Can someone provide an updated link (or better yet, describe what to do here in the issue?).  Thanks.

**Comment by gpeal** [comment]
@shoeguy If you call any of the `LottieCompositionFactory` methods with your resource/json/whatever, that will work.

Any subsequent requests will rejoin the original task or pull from cache.
