### ISSUE TITLE
Add the option to use assets in a Drawable outside of a View

### ISSUE THREAD

**Issue by rogererill** [airbnb/lottie-android#726]
Hello, 

I need to use a `LottieDrawable` that is not attached to a `View`. So far is working ok for me but now I found that I cannot see any text on it, because the drawable is not able to get an `AssetManager`

Looking at the code, I've seen that:
 
From LottieDrawable

```
private FontAssetManager getFontAssetManager() {
    if (getCallback() == null) {
      // We can't get a bitmap since we can't get a Context from the callback.
      return null;
    }

    if (fontAssetManager == null) {
      fontAssetManager = new FontAssetManager(getCallback(), fontAssetDelegate);
    }

    return fontAssetManager;
  }
```
 
From FontAssetManager
```
public FontAssetManager(Drawable.Callback callback, @Nullable FontAssetDelegate delegate) {
    this.delegate = delegate;
    if (!(callback instanceof View)) {
      Log.w(L.TAG, "LottieDrawable must be inside of a view for images to work.");
      assetManager = null;
      return;
    }

    assetManager = ((View) callback).getContext().getAssets();
  }
```
In my case, `getCallback()` is null since it is not attached to any `View`. The callback is used only to get a context so we can get the `assetManager`. It would be helpful for people in my situation if we could have another way to provide a `Context` or `AssetManager` to `LottieDrawable` other than attaching it to a `View`.

**Comment by gpeal** [comment]
@rogererill That should be set once you add your Drawable to a View.

**Comment by rogererill** [comment]
In my use case, I don't use my Drawable inside a View, I just draw it in a canvas. That's why in this case I never call `LottieDrawable.setCallback()`

**Comment by gpeal** [comment]
@rogererill Since this is a pretty edge-case. It may be easier to just create a fake View to give it rather than to add more code to the library that ships to billions of devices for this. However, if you want to discuss other options or put up a PR yourself, you may reopen this.

**Comment by thelou1s** [comment]
I draw LottieDrawable in surface holder, and got no image showed too.
