### ISSUE TITLE
After Effects Samples

### ISSUE THREAD

**Issue by TomKilleenBBC** [airbnb/lottie-android#73]
Hi Gabriel, 

Any chance of getting downsaved versions of the After Effects samples? I can't open them in AE CC15.

Lottie looks great BTW. It'll be really useful for me once I figure out how to embed vectors rather than have them included as linked files.

Thanks!

**Comment by therealsalih** [comment]
Hi Tom,
Heres the saved down AE files.

[_AeFiles CC 2015.zip](https://github.com/airbnb/lottie-android/files/755547/_AeFiles.CC.2015.zip)

Cheers!

**Comment by gpeal** [comment]
@TomKilleenBBC

**Comment by TomKilleenBBC** [comment]
That's awesome, thanks @therealsalih !
