### ISSUE TITLE
is there is any way to get the image of the animation?

### ISSUE THREAD

**Issue by vipafattal** [airbnb/lottie-android#730]
I want to make LottieAnimationView draggable so when the user touches on the animation I want to display the last displayed frame of the animation before the user touches the view is that possible?

View.DragShadowBuilder(/*the frame image from the Animation*/getImage)

**Comment by gpeal** [comment]
@vipafattal why not just set the progress to 1?

**Comment by vipafattal** [comment]
Great idea thanks @gpeal

**Comment by vipafattal** [comment]
so as a solution I can get the progress of the animation
