### ISSUE TITLE
There is Frame Skip using v2.5.4 (the same Lottie file)

### ISSUE THREAD

**Issue by SwayChen** [airbnb/lottie-android#736]
The Lottie file shows normal using v2.2.3, but appear frame skip in v2.5.4.

I've attach the file & issue video as attachment. Please take a look, thanks!
[attachments.zip](https://github.com/airbnb/lottie-android/files/1940686/attachments.zip)

**Comment by gpeal** [comment]
@SwayChen what does frame skip mean?

**Comment by SwayChen** [comment]
As the video in attachment shows.

It seems lottie sometimes skips the last serveral frame then play from beginning.

**Comment by gpeal** [comment]
@SwayChen I ran this through systrace and can't find anything suspicious.
