### ISSUE TITLE
2.5.4 Setting LottieAnimationView Visibility doesn't work

### ISSUE THREAD

**Issue by lyew-phunware** [airbnb/lottie-android#737]
How to reproduce: (Basic fragment with Relative Layout)
2 LottieAnimationView's in the same layout (RelativeLayout)
1 view will show and then when the animation finishes, the second view will show and the first will be hidden.
Programmatic change in visibility is not working.
LottieAnimationView.visibility = View.GONE / View.INVISIBLE / View.VISIBLE is not working

Lottie Version: 2.5.4. 
Verified that this working in version 2.5.3.

AfterEffects files sent to lottie@airbnb.com

**Comment by gpeal** [comment]
@lyew-phunware I can't repro this. I modified BullseyeActivity in the sample app to test this:
I modified activity_bullseye:
```
    <com.airbnb.lottie.LottieAnimationView
        android:id="@+id/animationView"
        android:layout_width="256dp"
        android:layout_height="256dp"
        app:lottie_rawRes="@raw/bullseye"
        app:lottie_autoPlay="true"
        android:layout_gravity="center"/>

    <com.airbnb.lottie.LottieAnimationView
        android:id="@+id/animationView2"
        android:layout_width="256dp"
        android:layout_height="256dp"
        android:layout_marginTop="128dp"
        app:lottie_rawRes="@raw/bullseye"
        android:visibility="gone"
        android:layout_gravity="center"/>
```

and added this in BullseyeActivity#onCreate
```
        animationView.addAnimatorListener(AnimatorListenerAdapter(
                onEnd = {
                    animationView.visibility = View.GONE
                    animationView2.visibility = View.VISIBLE
                    animationView2.playAnimation()
                }
        ))
```

and it worked as expected
![bullseye](https://user-images.githubusercontent.com/1307745/39707274-3e789a5e-5214-11e8-913c-507d11e010d6.gif)

If you can make a sample project that repros this, feel free to reopen it.

The likely change in behavior from 2.5.3 to 2.5.4 is [this](https://github.com/airbnb/lottie-android/commit/06cc92bbc0f6d1b5c81f0a7c1cb3be46c98b4690) but that should only make things better unless you had a hack to workaround the broken behavior before.
