### ISSUE TITLE
Change text in any lottie text animation ?

### ISSUE THREAD

**Issue by AlexLutinNoir** [airbnb/lottie-android#740]
Hello there, 
thank you for making such a great project available for everyone, I'm trying to learn android, so I'm working on a small application that uses some of the lottie animations found in [https://www.lottiefiles.com/](url)
I'm interested in customizing the animations that animate a certain text like this one:
[https://www.lottiefiles.com/16-body-movin](url)
I searched a bit on the lottie tutorials and also in the issues section on how to change the text in the animation, I found that for that I need to render a new text glyphs ? 
I don't know what that is ?
I saw also that I need to do this:  [https://github.com/airbnb/lottie-android/blob/master/LottieSample/src/main/kotlin/com/airbnb/lottie/samples/DynamicTextActivity.kt](url)
The thing is I don't understand what it does...I mean you set a custom text alright but how to link this class to lottie ??? should I dwnload the entire project and add this class???, and It's in Kotlin...while I'm using java on android studio......Which is a bit harder...
Please tell me what I should do ? and if it's not a bother, would you explain to me things that I don't get in this?

Thank you in advance for answering, and please don't mind my questions, I'm very new to this :)

**Comment by gpeal** [comment]
Lottie just renders animations exported with bodymovin in After Effects.

The animation you linked to was custom made. It's not a font or anything like that. If you want something similar, you would have to learn how to animate it yourself with After Effects.
You can start with some fonts on [Animography](https://animography.net/) and play around with them if you want.

Making your own, high quality animations will require you to learn After Effects though.

**Comment by robbbsen** [comment]
> ... how to change the text in the animation, I found that for that I need to render a new text glyphs ?
> ...

Depends on the animation. Learning after effects is a bit like cracking a nut with a sledgehammer. My first try would be opening the animation in something like notepad++ and search for the _current_ text. If you are lucky you can just replace it.

Answering generally "learn AE" is a bit too much.

**Comment by mattbusuu** [comment]
Old post, but for anyone still looking. Try `TextDelegate` 
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/TextDelegate.java
