### ISSUE TITLE
Log print frequent

### ISSUE THREAD

**Issue by luhui2014** [airbnb/lottie-android#742]
The JSON animation exported by AE can run normally, but the Lottie log has been printed.
The frequency of occurrence is too frequent, but I did not find the corresponding way to shield it. I look at the other logs.

`choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.143 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.160 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.176 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.193 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.210 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.236 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.243 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.260 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.276 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.293 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.311 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.329 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.346 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.364 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.382 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.398 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.415 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.432 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.449 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.465 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.482 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.498 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.515 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.531 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.548 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.565 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.581 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
04-30 17:00:51.598 24325-24325/com.lanjinger.choiassociatedpress W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.`

**Comment by gpeal** [comment]
It means you are using the unsupported feature, intersect masks. I should make this less noisy though.
