### ISSUE TITLE
Example4.gif in README.md contains an error

### ISSUE THREAD

**Issue by borysboyko** [airbnb/lottie-android#744]
Context:

![Example4](https://github.com/airbnb/lottie-android/blob/master/gifs/Example4.gif)

The animations writes, "THE QUICK BROWN FOX JUMPED OVER THE LAZY DOG"

This sentence is missing the letter 'S', which is typically part of the sentence that includes every letter of the English language alphabet.

The sentence should be as follows: "THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG"

Please see https://en.wikipedia.org/wiki/The_quick_brown_fox_jumps_over_the_lazy_dog

Thank you!

**Comment by gpeal** [comment]
Ours is unique 😄

**Comment by borysboyko** [comment]
Ok :+1: :smiley:
