### ISSUE TITLE
Migrate from deprecated Canvas.saveLayer

### ISSUE THREAD

**Issue by sorotokin** [airbnb/lottie-android#747]
Canvas.saveLayer with 3 parameters is deprecated in API level 26. Replacement is 2-parameter version which is available in level 21. To start the process, all flags, except ALL_SAVE_FLAG could be eliminated.

**Comment by sorotokin** [comment]
https://github.com/airbnb/lottie-android/pull/748

**Comment by paulsowden** [comment]
Worse than just being deprecated this method will throw IllegalArgumentException when the targetSdkVersion is >= 28 (P).

**Comment by sorotokin** [comment]
With ALL_SAVE_FLAG it would not (yet)

**Comment by amid67** [comment]
I received this error on android P and be crashed

Invalid Layer Save Flag - only ALL_SAVE_FLAGS is allowed com.airbnb.lottie.model.layer.BaseLayer.draw

**Comment by gpeal** [comment]
@amid67 Upgrade Lottie

**Comment by dingshaoran** [comment]
@gpeal   what is the version  fix the bug

**Comment by gpeal** [comment]
@dingshaoran anything 2.6 or later
