### ISSUE TITLE
Support animating trim paths on multiple shapes individually

### ISSUE THREAD

**Issue by gpeal** [airbnb/lottie-android#75]
See: https://github.com/airbnb/lottie-ios/issues/22

**Comment by yozef** [comment]
Great :)

**Comment by gpeal** [comment]
This now works in almost all cases.
One caveat is that you should use a single stroke when possible rather than nesting strokes within groups:
Instead of:
<img width="406" alt="screen shot 2017-03-19 at 6 57 39 pm" src="https://cloud.githubusercontent.com/assets/1307745/24086982/03a2ea26-0cd6-11e7-9845-58da2a3a2022.png">
Do:
<img width="400" alt="screen shot 2017-03-19 at 6 57 21 pm" src="https://cloud.githubusercontent.com/assets/1307745/24086983/074c9942-0cd6-11e7-87a9-944898e2cce6.png">
