### ISSUE TITLE
Lottie file in a Dialog Android

### ISSUE THREAD

**Issue by young1872** [airbnb/lottie-android#755]
Hello there,
I'm developing an app in android, and I want to use lottie for a Dialog that could have an animated icon of checked-done or fail. Wellcome some examples or ideas. I guess this is possible.
Thanks

**Comment by gpeal** [comment]
http://airbnb.io/lottie/android/android.html#getting-started
and
https://github.com/airbnb/lottie-android/tree/master/LottieSample/src/main/kotlin/com/airbnb/lottie/samples
