### ISSUE TITLE
KeyPath constructor warning

### ISSUE THREAD

**Issue by chronvas** [airbnb/lottie-android#757]
Trying to do:

`loadingView.addValueCallback(new KeyPath("**"), LottieProperty.COLOR_FILTER, lottieValueCallback);
`

The IDE gives me a warning for "new KeyPath..." stating:

> KeyPath constructor can only be called from within the same library (com.airbnb.android:lottie)

using 2.5.4 from the related [docs](http://airbnb.io/lottie/android/dynamic.html)

**Comment by gpeal** [comment]
Fixed by https://github.com/airbnb/lottie-android/commit/c9bb8384fd0ccc33dafe775487e045a865f34921
