### ISSUE TITLE
Migrating from the old addColorFilter API clarification

### ISSUE THREAD

**Issue by chronvas** [airbnb/lottie-android#758]
From the [documentation](http://airbnb.io/lottie/android/dynamic.html) 
`animationView.addValueCallback(new KeyPath("**"), LottieProperty.COLOR_FILTER, new LottieValueCallback(colorFilter));`

And adopted it this way:
`loadingView.addValueCallback(new KeyPath("**"), LottieProperty.COLOR_FILTER, new LottieValueCallback(new SimpleColorFilter(getResources().getColor(android.R.color.black))));`

I get a warning of _unchecked assignment_ on the third parameter (LottieValueCallback), probably should change that to something like 

```
loadingView.addValueCallback(new KeyPath(""), LottieProperty.COLOR_FILTER, new SimpleLottieValueCallback<ColorFilter>() {
            @Override
            public ColorFilter getValue(LottieFrameInfo<ColorFilter> frameInfo) {
                return new SimpleColorFilter(getResources().getColor(android.R.color.black));
            }
        });
``` 
This way I don't get the warning any more.

**Comment by gpeal** [comment]
Thanks! Docs have been updated.
