### ISSUE TITLE
Autoplay LottieAnimationViews animate even when not attached to window

### ISSUE THREAD

**Issue by bwill** [airbnb/lottie-android#762]
When running the profiler, I noticed that I had a LottieAnimationView which was animating, even though it had no parent and was not attached to a window.

I believe the view had been inflated, but never attached to a window (it was a view that would be used in a RecyclerView).

Why does LottieAnimationView start the animation in the constructor, and not do it in onAttachedToWindow?

https://github.com/airbnb/lottie-android/blob/c360f7cc0a1cc1bb197c0cafd8ec6c7448d02d44/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L139

Rather than starting the animation, the autoplay attribute could set `wasAnimatingWhenDetached` to true - then the animation would start when the view was attached to a window.

**Comment by gpeal** [comment]
@bwill Good fix. I'll correct this.
