### ISSUE TITLE
Use new .androidx package from Android Jetpack instead of android.support

### ISSUE THREAD

**Issue by dommerq** [airbnb/lottie-android#767]
At Google io18 was announced Android Jetpack. 
The main issue now is libraries using the old support libraries. 
I'd suggest moving to jetpack.

**Comment by gpeal** [comment]
@dommerq moving to androidx right now would prevent the many apps that will inevitably take a while to upgrade from upgrading Lottie. I will definitely upgrade but I'll give apps time to update before updating Lottie.

I'll tentatively do this at the end of 2018.
