### ISSUE TITLE
Reduce support library version

### ISSUE THREAD

**Issue by muthuraj57** [airbnb/lottie-android#77]
Lottie uses appcompat library version 25.1.1

https://github.com/airbnb/lottie-android/blob/master/lottie/build.gradle#L24

I'm using 24.1.1 version of support library. When adding lottie dependency, android studio changes my app support library version to the latest version used by any dependencies which here is 25.1.1

I'm not moving to 25.1.1 due to certain bugs in that version. It would be better if lottie uses lowest possible version of support library. For ex if it uses 23.x, and the user uses 24.x or 25.x, then on build time everyones support library version would be the maximum version used (24.x or 25.x).

**Comment by muthuraj57** [comment]
Found a workaround to override version.
This excludes the support library dependency from lottie. Hence the support library added in app gradle will be used.

`compile ('com.airbnb.android:lottie:1.0.1'){
        exclude group: 'com.android.support'
    }`

**Comment by gpeal** [comment]
I'll upgrade our gradle dependencies to require the support library to be provided:
`provided 'com.android.support:appcompat-v7:25.1.1'`

**Comment by MrBuggySan** [comment]
Thank you @muthuraj57 !

**Comment by wingjay** [comment]
Thank you @muthuraj57 !

**Comment by jhwsx** [comment]
Here is my error.
`Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex`
Thank you @muthuraj57 ! for saving me!

**Comment by jygzdx** [comment]
@muthuraj57 after remove appcompact_v7,you can use LottieAnimationView (extends AppCompatImageView)?
