### ISSUE TITLE
Json File is incorrectly rendered, but perfect in web

### ISSUE THREAD

**Issue by AhmadKabi** [airbnb/lottie-android#774]
Hi, I'm impressed with this great work. thanks for eye catching effect for the users by using your library.
but i have bug here. I have an bodymovin converted json file that is rendered incorrectly in android app, but it looks perfect if we play this json in web. i have attached the file below. 

Thanks a lot

aep file : https://drive.google.com/file/d/1vn4AU9rJiAXLp1p16kKLWFEM0a-W3GWO/view?usp=sharing
web rendered : https://www.lottiefiles.com/share/oVimcn#

Update:  incorrectly rendering occurs when i use TextDelegate to the LottieAnimationView. Without it, animation play perfectly

**Comment by gpeal** [comment]
Duplicate of #388
