### ISSUE TITLE
Lottie Animation background

### ISSUE THREAD

**Issue by Anmolk22** [airbnb/lottie-android#778]
I am trying to make the lottie animation background transparent but couldn't find any configuration to do the same. I've tried the online bodymovin but the color background is not changing. 
Please suggest 
https://editor.lottiefiles.com/?src=https://www.lottiefiles.com/download_public/305

**Comment by gpeal** [comment]
@Anmolk22 the background is transparent. You can tell by dragging the json over lottiefiles, scanning the qr code with the Lottie app on the play store and changing the background color.

The background is probably on your view itself.

**Comment by gpeal** [comment]
@EmilAlipiev Lottie has no default background. It is transparent by default.

**Comment by chitgoks** [comment]
there does not seem to be any way to make it transparent.

in the editing layer page for lottie files, i set the background to transparent, nothing happens.
i set the background of  com.airbnb.lottie.LottieAnimationView to null or transparent, nothing happens. it's still white.

anyone solved this?

**Comment by gpeal** [comment]
It must be there in After Effects. Lottie has no notion of a background, it would only show up that way if it's part of your animation.

**Comment by mchiasson-youi** [comment]
I am also seeing an unwanted white background with lottie-android with Compose while the same exact asset remains transparent on lottie-web.
