### ISSUE TITLE
gradle error for instant run

### ISSUE THREAD

**Issue by Adnan9011** [airbnb/lottie-android#78]
i have this error : 

Error:Could not determine the dependencies of task ':LottieSample:transformClassesWithInstantRunForDebug'.
> In order to use Instant Run with this device running API 17, you must install platform 17 in your SDK

Android Studio 2.1.3
Ubuntu 14.04
i just change buildToolsVersion from 25.0.2 to 25.0.0 , and doesn't change anything from root project .

thanks in advance

**Comment by gpeal** [comment]
You need to install the api 17 platform tools in the sdk manager her: https://developer.android.com/studio/intro/update.html
or disable instant run (settings -> build, execution, deployment -> instant run)

**Comment by Adnan9011** [comment]
for another one that have this issue : 
if you use Android Studio 2.1 , you haven't instant run . the solution should be install your sdk for your device .
if you use Android Studio 2.2 , disable instant run .

thanks @gpeal
