### ISSUE TITLE
Android---Rest the image asset but lottie still use the resource  image assert before.

### ISSUE THREAD

**Issue by SunJenry** [airbnb/lottie-android#782]
The problem is I want to display the animation from different resources, like assert and the download file . So I have to change the Image Asset by reset the  Image Asset Delegate. But no matter how i reset the image assert , once used the `setImageAssetDelegate()` , the lottie won't accept the`setImageAssetsFolder()` anymore. This is a bug or lottie just don't support change between them?

**Comment by gpeal** [comment]
I recommend using a separate LottieAnimationView if you have some with an image delegate and some without.
