### ISSUE TITLE
Animation looks correct on android 5 & 6, but incorrect on android 7 & 8

### ISSUE THREAD

**Issue by moonsweel** [airbnb/lottie-android#785]
I faced with a strange issue, my animation looks correct on android 5 & 6, but on android 7 & 8 it doesn't.

It draws 3 lines, on after another, and this's how it starts on android 5 & 6:
<img width="299" alt="screen shot 2018-05-24 at 15 24 29" src="https://user-images.githubusercontent.com/3405348/40482792-f8374cc4-5f66-11e8-9c80-48740a895d7a.png">

But on newer android versions it starts like this: 
<img width="255" alt="screen shot 2018-05-24 at 15 23 56" src="https://user-images.githubusercontent.com/3405348/40482842-23355ede-5f67-11e8-88dc-16aadd45e7f2.png">

The problem is we see small pieces of second and third lines at the start of animation. 

Here is the json:

`{"v":"5.1.1","fr":29.9700012207031,"ip":0,"op":66.0000026882351,"w":100,"h":50,"nm":"logo1","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":4,"nm":"logo1 Outlines 2","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[50,29,0],"ix":2},"a":{"a":0,"k":[50,20,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"hasMask":true,"masksProperties":[{"inv":false,"mode":"a","pt":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0]],"v":[[0,0],[0,39],[100,39],[100,0]],"c":true},"ix":1},"o":{"a":0,"k":100,"ix":3},"x":{"a":0,"k":0,"ix":4},"nm":"Mask 1"}],"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0]],"v":[[-16.559,14.292],[-0.035,-14.333],[16.559,14.333]],"c":false},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"st","c":{"a":0,"k":[0.1254902035,0.509803950787,0.882352948189,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":9.6,"ix":5},"lc":3,"lj":1,"ml":10,"d":[{"n":"d","nm":"dash","v":{"a":0,"k":70,"ix":1}},{"n":"o","nm":"offset","v":{"a":1,"k":[{"i":{"x":[0.404],"y":[1]},"o":{"x":[0.333],"y":[0]},"n":["0p404_1_0p333_0"],"t":8,"s":[70],"e":[5]},{"i":{"x":[0.808],"y":[1]},"o":{"x":[0.167],"y":[0]},"n":["0p808_1_0p167_0"],"t":16,"s":[5],"e":[5]},{"i":{"x":[0.682],"y":[1]},"o":{"x":[0.167],"y":[0]},"n":["0p682_1_0p167_0"],"t":56,"s":[5],"e":[-70]},{"t":62.0000025253118}],"ix":7}}],"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"tr","p":{"a":0,"k":[77.959,24.625],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 2","np":2,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0]],"v":[[-16.559,14.292],[-0.034,-14.333],[16.559,14.333]],"c":false},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"st","c":{"a":0,"k":[0.1254902035,0.509803950787,0.882352948189,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":9.6,"ix":5},"lc":3,"lj":1,"ml":10,"d":[{"n":"d","nm":"dash","v":{"a":0,"k":70,"ix":1}},{"n":"o","nm":"offset","v":{"a":1,"k":[{"i":{"x":[0.404],"y":[1]},"o":{"x":[0.333],"y":[0]},"n":["0p404_1_0p333_0"],"t":0,"s":[70],"e":[5]},{"i":{"x":[0.808],"y":[1]},"o":{"x":[0.167],"y":[0]},"n":["0p808_1_0p167_0"],"t":8,"s":[5],"e":[5]},{"i":{"x":[0.682],"y":[1]},"o":{"x":[0.167],"y":[0]},"n":["0p682_1_0p167_0"],"t":47,"s":[5],"e":[-70]},{"t":53.0000021587343}],"ix":7}}],"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"tr","p":{"a":0,"k":[22.075,24.625],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 3","np":2,"cix":2,"ix":2,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":66.0000026882351,"st":0,"bm":0},{"ddd":0,"ind":2,"ty":4,"nm":"logo1 Outlines","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":0,"s":[50,20,0],"e":[50,20,0],"to":[0,0,0],"ti":[0,0,0]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.333,"y":0},"n":"0p833_0p833_0p333_0","t":22,"s":[50,20,0],"e":[50,30.583,0],"to":[0,1.76387357711792,0],"ti":[0,-1.12029790878296,0]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"n":"0p667_1_0p333_0","t":27,"s":[50,30.583,0],"e":[50,26.722,0],"to":[0,1.12029790878296,0],"ti":[0,0.26387360692024,0]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"n":"0p667_1_0p333_0","t":32,"s":[50,26.722,0],"e":[50,29,0],"to":[0,-0.26387360692024,0],"ti":[0,-0.3797020316124,0]},{"t":35.0000014255792}],"ix":2},"a":{"a":0,"k":[50,20,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"hasMask":true,"masksProperties":[{"inv":false,"mode":"a","pt":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0]],"v":[[0,1],[0,40],[100,40],[100,1]],"c":true},"ix":1},"o":{"a":0,"k":100,"ix":3},"x":{"a":0,"k":0,"ix":4},"nm":"Mask 1"}],"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0]],"v":[[-16.559,-14.292],[-0.034,14.333],[16.559,-14.333]],"c":false},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"st","c":{"a":0,"k":[0.1254902035,0.509803950787,0.882352948189,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":9.6,"ix":5},"lc":3,"lj":1,"ml":10,"d":[{"n":"d","nm":"dash","v":{"a":0,"k":70,"ix":1}},{"n":"o","nm":"offset","v":{"a":1,"k":[{"i":{"x":[0.404],"y":[1]},"o":{"x":[0.333],"y":[0]},"n":["0p404_1_0p333_0"],"t":18,"s":[70],"e":[5]},{"i":{"x":[0.792],"y":[1]},"o":{"x":[0.167],"y":[0]},"n":["0p792_1_0p167_0"],"t":26,"s":[5],"e":[5]},{"i":{"x":[0.682],"y":[1]},"o":{"x":[0.167],"y":[0]},"n":["0p682_1_0p167_0"],"t":52,"s":[5],"e":[-70]},{"t":58.0000023623884}],"ix":7}}],"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"tr","p":{"a":0,"k":[50.075,15.333],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Group 5","np":2,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":900.000036657751,"st":0,"bm":0}],"markers":[]}`

Could you help with this?

**Comment by gpeal** [comment]
@moonsweel I just tried this on master and they render the same on both platforms. There have been a ton of improvements, especially to masks which may have fixed this.
