### ISSUE TITLE
第一次进入App时，动画不能显示。

### ISSUE THREAD

**Issue by TJHello** [airbnb/lottie-android#789]
你好，我有一个问题：第一次进入App时，动画不能显示。
可能的原因：有大量的 Asynctask 或者 Thread 在运行。
请问你们是用到了Asynctask作为后台线程吗？因为我知道，如果Asynctask运行的数量过多的话，很有可能会无法进入Run。
希望你们可以解决这个问题，谢谢！

**Comment by TJHello** [comment]
解决方法：
LottieComposition lottieComposition = LottieComposition.Factory.fromFileSync(context,"anim/unlock.json");
        if(lottieComposition!=null)
        {
            lottieAnimationView.setComposition(lottieComposition);
            lottieAnimationView.playAnimation();
        }

**Comment by gpeal** [comment]
Please attach a repro project. There isn't enough information to go on here. Also, please translate it to English so others can understand.
