### ISSUE TITLE
Failed to resolve: com.airbnb.android:lottie:2.5.1

### ISSUE THREAD

**Issue by kmjyothish** [airbnb/lottie-android#794]
I export the unity project and import into android studio. i want show some lottie animation before launching the unity player.If i added this depedency  com.airbnb.android:lottie:2.5.1 it throws Error.(Failed to resolve: com.airbnb.android:lottie:2.5.1). for same depedency added for new project its working without unity.

**Comment by gpeal** [comment]
Use 2.5.5

**Comment by JaySX** [comment]
2.5.5 is not working too

**Comment by octivia** [comment]
same problem . how can we solve this problem. 2.5.5 is also not working

**Comment by JaySX** [comment]
@octivia you can change 2.5.5 to 2.5.6,but you must update your compileSdkVersion,and then update your java version,and update your gradle version,and update all of your thrid-sdk version

**Comment by JaySX** [comment]
compile('com.airbnb.android:lottie:2.5.5') {
        exclude group: 'com.android.support'
    }
It works for me

**Comment by MohamedHajr** [comment]
I'm having the same issue with 2.5.5
