### ISSUE TITLE
LottieDrawable always draw on top-left 

### ISSUE THREAD

**Issue by woyelin** [airbnb/lottie-android#799]
Hi, I would want my lottieDrawable to draw on a ImageView as a foreground. Currently it always draws on the top-left of the lottieDrawable. I want to make it draw on the center of the ImageView. I try use lottieDrawable.setBounds(l, t, r, b) but that doesn't work.

How can I position my lottieDrawable on the ImageView?

**Comment by gpeal** [comment]
@woyelin I don't think this is a lottie specific issue. If you think it is, can you attach a sample project?

**Comment by WinKawaks** [comment]
You can use LottieDrawable like this.

`

@Override
    public void invalidateDrawable(@NonNull Drawable drawable) {
        super.invalidateDrawable(mLottieDrawable);
        invalidate();
    }

    @Override
    public void draw(Canvas canvas) {
        super.draw(canvas);
        canvas.save();
        canvas.translate(100, 100);
        mLottieDrawable.draw(canvas);
        canvas.restore();
    }

`
