### ISSUE TITLE
Support trim path offset

### ISSUE THREAD

**Issue by subtleGradient** [airbnb/lottie-android#80]
Trim path start and end works.
But trim path offset does not yet.

**Comment by therealsalih** [comment]
Seems like its working on our end, can you send our AE file?

![feb-08-2017 12-25-27](https://cloud.githubusercontent.com/assets/5893643/22755850/cd498b42-edf9-11e6-811a-ba6295090eee.gif)

**Comment by gpeal** [comment]
@subtleGradient can you attach the AE file of the animation that's not working?

**Comment by gpeal** [comment]
@kevinrob have you had issues with trim path offset? If so, can you attach a sample AE file?

**Comment by Kevinrob** [comment]
@gpeal yes, but I wait for the AE file. Then I will add it here.

**Comment by Kevinrob** [comment]
@gpeal The problem was in our AE file, I don't know what. But I receive a new JSON that work good!
