### ISSUE TITLE
Developers having issue playing Lottie animation correctly

### ISSUE THREAD

**Issue by vapour07** [airbnb/lottie-android#800]
Hi all,

This is one issue my developer encounters while embedding my lottie animation into android format
https://www.dropbox.com/s/xkonoaj34cy75ca/2018-06-08%2010.45.11.mp4?dl=0
Seems fine to be playing on browser but looks wonky in the android mobile.

I've tried previewing on Lottiefiles site and it seems to be working fine.

Then my developer sent me this error log regarding the issue:

`E  FATAL EXCEPTION: main
                         E  Process: sg.ndi.sp, PID: 31862
                         E  java.lang.RuntimeException: Unable to start activity ComponentInfo{sg.ndi.sp/sg.ndi.activity.AuthenticationVerifyActivity}: android.view.InflateException: Binary XML fil
                            e line #142: Binary XML file line #142: Error inflating class sg.ndi.view.TintableImageButton
                         E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                         E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                         E      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                         E      at android.os.Handler.dispatchMessage(Handler.java:102)
                         E      at android.os.Looper.loop(Looper.java:154)
                         E      at android.app.ActivityThread.main(ActivityThread.java:6119)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                         E  Caused by: android.view.InflateException: Binary XML file line #142: Binary XML file line #142: Error inflating class sg.ndi.view.TintableImageButton
                         E  Caused by: android.view.InflateException: Binary XML file line #142: Error inflating class sg.ndi.view.TintableImageButton
                         E  Caused by: java.lang.reflect.InvocationTargetException
                         E      at java.lang.reflect.Constructor.newInstance0(Native Method)
                         E      at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                         E      at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                         E      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                         E      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                         E      at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                         E      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                         E      at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                         E      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                         E      at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                         E      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                         E      at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                         E      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                         E      at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                         E      at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                         E      at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                         E      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                         E      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                         E      at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:303)
                         E      at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284)
                         E      at sg.ndi.activity.AuthenticationVerifyActivity$binding$2.invoke(AuthenticationVerifyActivity.kt:45)
                         E      at sg.ndi.activity.AuthenticationVerifyActivity$binding$2.invoke(Authentication` 

Wondering if its an issue related to my Lottie AEP file or is it more of an issue from my developer's end?

json file link here, if it helps to debug the problem
https://drive.google.com/open?id=1r1BfaRys9GVqAdyqqTRqrG0d9LUm22Nt

**Comment by gpeal** [comment]
@vapour07 Can you attach the json as a zip file directly? I can't access it there

**Comment by vapour07** [comment]
I think it's all good now! Thanks alot @gpeal

**Comment by cesards** [comment]
@vapour07 How did you fix it? Was it an error related to how the animation was done? I had a similar problem so I'm interested in the final solution. Thanks!

**Comment by vapour07** [comment]
The developers just told me things are ok now so I’m not too sure what they did on their end, I thought probably Gabriel did something to it though.

But its definitely not the animation problem since i didnt do anything fancy to it at all and one day my devs just told me everything is fine already!

**Comment by cesards** [comment]
Cool! Thanks :)
