### ISSUE TITLE
scale issue with fitXY scale type 

### ISSUE THREAD

**Issue by zjupure** [airbnb/lottie-android#801]
hi, 

   I am using lottie to do animation, and when upgrade version to 2.3.1, the fitXY scale type not work as well. The animation will be scaled larger than the view bounds and only display part of images.
  [#461](https://github.com/airbnb/lottie-android/pull/461) seems to be related. This PR fix the scale issue with centerInside and centerCrop, but make the fitXY not match.

```
<com.airbnb.lottie.LottieAnimationView
            android:id="@+id/loading_vip"
            android:layout_width="245dp"
            android:layout_height="4dp"
            android:layout_gravity="center"
            android:scaleType="fitXY"/>
```

**Comment by gpeal** [comment]
@zjupure Can you use centerInside or centerCrop instead? Lottie doesn't support non-original aspect ratio scale types.

**Comment by scsfwgy** [comment]
If the LottieAnimationView is in full-screen mode, some mobile devices may have an adaptation problem. such as:Some have built-in keyboards at the bottom of the screen, as this results in an error in the aspect ratio.

**Comment by mgp0000606** [comment]
**Exponential scale issue**
I've made the tunnel effect through exponential scale in after effects but when I export its lottie file the effect becomes somewhat different. Don't know may be lottie is skipping few frames or what, can you help me to figure out and fix this issue.

[Lottie animation.zip](https://github.com/airbnb/lottie-android/files/3339121/Lottie.animation.zip)
