### ISSUE TITLE
Activity transition shared element

### ISSUE THREAD

**Issue by danivalvo** [airbnb/lottie-android#804]
Hello there!

I'm trying to implement transition between activities using an instance of `LottieAnimationView` as shared element using [android reference](https://developer.android.com/training/transitions/start-activity).

In my case the animation views have different sizes on their activities. Everything work fine about the centering. The issue is about the **scaling**: there's no interpolation and the second animation view starts from the origin of the first, like the pivot was set as 0, 0.

Everything works fine if I use an ImageView as shared element.
Any suggestion?

Thank you in advance!

**Comment by gpeal** [comment]
Your best bet is to debug it with a [SharedElementCallback](https://developer.android.com/reference/android/app/SharedElementCallback.html#onCaptureSharedElementSnapshot(android.view.View,%20android.graphics.Matrix,%20android.graphics.RectF))
