### ISSUE TITLE
Suggestion: remove "buildToolsVersion" from sample

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [airbnb/lottie-android#805]
The IDE doesn't require it anymore. 
It's automatically choosing the best one for the project.

**Comment by leleliu008** [comment]
@AndroidDeveloperLB  the real reason is here:
[https://developer.android.com/studio/releases/build-tools](https://developer.android.com/studio/releases/build-tools)
[https://developer.android.com/studio/releases/gradle-plugin#3-0-0](https://developer.android.com/studio/releases/gradle-plugin#3-0-0)

**Comment by AndroidDeveloperLB** [comment]
@leleliu008 Well this is actually the reason of not putting it, so that it will use the latest there is.

**Comment by AndroidDeveloperLB** [comment]
Why close this?
Was it applied?
