### ISSUE TITLE
Lottie animation flashes white

### ISSUE THREAD

**Issue by ColtonIdle** [airbnb/lottie-android#806]
Not sure where to post this, but I have lottie working fine except that on every loop there is a quick white flash to fill out the rest of the image (fills in the transparency). This is weird because it doesn't happen when loading the exact file in the Lottie preview app. I checked out the source code and didn't see anything different that is being set to the animation_view. Any hints on what could be the problem? Our iOS team is using this as well and there are no issues with the white flash there.

**Comment by gpeal** [comment]
If you attach a sample project that repros this, I can take a look. Without that, there isn't much I can do. Sorry.

**Comment by ColtonIdle** [comment]
It's okay. I just thought maybe there was something simple I was missing. Unfortunately I can't post the animation since it's proprietary. I will try to resolve this myself.
