### ISSUE TITLE
exporting dynamic text with custom font

### ISSUE THREAD

**Issue by samiam2017** [airbnb/lottie-android#807]
Attempting to output a determinate progress bar with a dynamic text counter of 0%->100%

goal is to have something that works for iOS and Android, but currently it's not even working for demo test.

After Effects Version 15.1.1
Bodymovin Version 5.1.10

I build the animated text using two different techniques for testing neither seems to work:

the Numbers Effect on a shape layer

an expression on a text layer

When I export as Glyphs all of the animation plays except text counter just flashes between 0 and 100 rather than playing the sequence.

When I export without Glyph I get the dialog box for the font families, css class, font path, font family, font weight, font style.

I'm not sure what to do here.

Not sure if I supposed to select None (since I have a custom font) or what I'm supposed to put in for font path. I also have multiple instances of the font in different sizes how do I know that everything will be output correctly. What if I wanted to output 2 different font styles?

Regardless when I render it out using this method I get a blank screen, I don't even get the progress bar loading in this instance so I'm not sure what to do.

Any help would be appreciated.

UPDATE:
iOS and Android I ended up just manually doing the countdown (1 layer for each character (was something like 80 layers to sequence)) a bit laborious but seems to be working. If there are any better work arounds to create a text countdown please share.

**Comment by gpeal** [comment]
Lottie [doesn't support](http://airbnb.io/lottie/supported-features.html) "Number Effect" or Expressions.

For Android, you should use a Text Layer and TextDelegate like [this](https://github.com/airbnb/lottie-android/blob/master/LottieSample/src/main/kotlin/com/airbnb/lottie/samples/DynamicTextActivity.kt#L19).
