### ISSUE TITLE
Error: Program type already present: android.support.v4.os.ResultReceiver

### ISSUE THREAD

**Issue by goldyonwar** [airbnb/lottie-android#810]
Error: Program type already present: android.support.v4.os.ResultReceiver
   implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.0.0-alpha3'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0-alpha3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0-alpha3'
    implementation 'com.airbnb.android:lottie:2.5.5'

**Comment by Thiago0803** [comment]
gradle.properties:

android.useAndroidX=true
android.enableJetifier=true

**Comment by gpeal** [comment]
@goldyonwar You can try `compile ('com.airbnb.android:lottie:2.5.1'){ exclude group: 'com.android.support' }`

**Comment by Riyaz0001** [comment]
I am already solved this problem: https://stackoverflow.com/questions/50676100/program-type-already-present-android-support-v4-os-resultreceivermyresultrecei/55345901#55345901
