### ISSUE TITLE
Error on show from url

### ISSUE THREAD

**Issue by tahagit** [airbnb/lottie-android#811]
hi, i want to show json file from url but i have error "JsonReader near".
this is my code:
` JsonReader jsonReader = new JsonReader(new StringReader(response.toString()));
                animationView.setAnimation(String.valueOf(jsonReader));
                animationView.playAnimation();
`

**Comment by gpeal** [comment]
Use [this](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L463) version with your JsonReader directly, not `String.valueOf`.
