### ISSUE TITLE
display different on Android and iOS when screen orientation is landscape

### ISSUE THREAD

**Issue by leleliu008** [airbnb/lottie-android#812]
lottie-android version: 2.5.5
lottie-ios version: 2.5.0

here I have write a simple Demo(android and iOS)
[LottieDemo.zip](https://github.com/airbnb/lottie-android/files/2113982/LottieDemo.zip)

And I want the effect of ios, how to do in android?

**Comment by gpeal** [comment]
Add `android:scaleType="centerCrop"`

**Comment by leleliu008** [comment]
Add android:scaleType="centerCrop" not work well as iOS. I will find other way to resolve this problem, thank you!
