### ISSUE TITLE
trimpath + multiple gradient strokes issues

### ISSUE THREAD

**Issue by macZielinski** [airbnb/lottie-android#813]
Hi, 

I had to use 3 paths with trim path, and gradient that intermigle each other. Terrible effect is in lottie viewer. Gradient moves, flickers ....
Below I give You reproduced problem in json file, html and project file:
https://drive.google.com/file/d/1Px2AOLDJWvaDdgJ7Ui79Z-gkWiGWUCa1/view?usp=sharing

**Comment by gpeal** [comment]
I just tried this on 3.4.0 and master and it seems to be working fine now.
