### ISSUE TITLE
spring-android-rest-template + lottie

### ISSUE THREAD

**Issue by cassiohoffmann** [airbnb/lottie-android#817]
Hello friends, I would very much like to use dependency on my project, my application does not work when I insert the lottie. Is there a problem with lottie and spring for android? how should I proceed?
everything related to spring stops working.
java.lang.NoClassDefFoundError: org.springframework.http.client.SimpleClientHttpRequestFactory

**Comment by gpeal** [comment]
This is not lottie related. This library runs on Android. Spring is a backend web framework.

**Comment by cassiohoffmann** [comment]
I'm talking about the spring to android in which all but all of the resources, annotagions like @REST, @APLICATION, etc.
You can learn more about spring to android at:
http://projects.spring.io/spring-android/

my project runs normally with spring porem, when I enter:
compile 'com.airbnb.android:lottie:2.5.5'
all of it.

Thank you for your help.

**Comment by cassiohoffmann** [comment]
I would like to understand what has in the lottie project that is affecting the operation of my application with spring. maybe annotations, etc. .. can you help me? many people use spring for android.
