### ISSUE TITLE
it doesn't look right

### ISSUE THREAD

**Issue by luobin23628** [airbnb/lottie-android#819]
在android上部分元素不能正常显示，但是在iOS和web上都是正常的，为什么呢？我查了不能显示的元素应该都是支持的。
文件预览地址：https://www.lottiefiles.com/share/Na1i46

[tianxiao.json.zip](https://github.com/airbnb/lottie-android/files/2136699/tianxiao.json.zip)

**Comment by gpeal** [comment]
@luobin23628 What doesn't look right? Please reply in English so others can use this as a reference.
