### ISSUE TITLE
Some images in same image asset folder is not rendering - Native android

### ISSUE THREAD

**Issue by balaje123** [airbnb/lottie-android#821]
I used JSON file to load animation which is provided by my UI designer. But some images getting rendering meanwhile some is not rendering and got following logs. I have gone through the JSON and image path is also same.

05-30 11:35:16.183 23030-23030/com.innovellent.lottiedemo W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.
05-30 11:35:16.263 23030-23030/com.innovellent.lottiedemo W/LOTTIE: Animation contains intersect masks. They are not supported but will be treated like add masks.

05-30 11:42:49.080 24782-24782/com.innovellent.lottiedemo W/LOTTIE: Animation contains merge paths but they are disabled.
05-30 11:42:49.081 24782-24782/com.innovellent.lottiedemo W/LOTTIE: Animation contains merge paths but they are disabled.

**Comment by gpeal** [comment]
@balaje123 Those logs are not related. If you attach a sample project that can reproduce this, please reopen this issue and attach it.
