### ISSUE TITLE
Lottie not showing onActivityResult

### ISSUE THREAD

**Issue by da224** [airbnb/lottie-android#826]
First of all, Thank you for great library.

lottie animation is working well in my code except for code in onActivityResult.
 - implementation : 'com.airbnb.android:lottie:2.5.4'

My code in onActivityResult is as below,

  @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (resultCode == RESULT_OK && requestCode == EDIT_REQUEST_CODE) {
             runOnUiThread(
                    new Runnable() {
                        @Override
                        public void run() {
                            progressBar.setVisibility(View.VISIBLE);
                           //above is lottieAnimationView
                            Toast.makeText(MainNotiDetailActivity.this,"sdfdsfs", Toast.LENGTH_SHORT).show();
                            Log.d(TAG, "onActivityResult RC_PHOTO_PICKER progressbar called");
                        }
                    });
         }
}    

Toast is working but lottie animation view is now showing.

Please let me know how to fix this code.

Thank you.

**Comment by gpeal** [comment]
Can you attach a sample project the reproduces this? If so, feel free to reopen.

**Comment by dahan224** [comment]
It was my mistake. Sorry and Thank you for reply.
