### ISSUE TITLE
Question: Does Lottie-android library support all Lottie files?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [airbnb/lottie-android#829]
I ask this because a lot of times, when I download a lottie file (json file) from the Lottie-files website, it is faulty and I can't use it, even though the website seems to show it fine.

Example is this one:
https://www.lottiefiles.com/1786-profile

**Comment by gpeal** [comment]
@AndroidDeveloperLB Different platforms support different features. For example, some animations work well with Lottie Web but not Android/iOS and vice versa.

Refer to [supported features](http://airbnb.io/lottie/supported-features.html) for specifics.

**Comment by AndroidDeveloperLB** [comment]
Can you at least put a mark for each of the files, to show on which platforms it's supported, and add a filter so that we will see only those that are supported for the selected platform ?

Currently if I want to use a file there, I have to try each till I find one that works...
