### ISSUE TITLE
Documentation error - # Play animation segments (methods)

### ISSUE THREAD

**Issue by jooleeanh** [airbnb/lottie-android#832]
http://airbnb.io/lottie/android/android.html#play-animation-segments

The current text:

> setMinFrame(...)
> setMinFrame(...)
> setMaxProgress(...)
> setMaxProgress(...)

Should be: 

> setMinFrame(...)
> set*Max*Frame(...)
> set*Min*Progress(...)
> setMaxProgress(...)

**Comment by markstonehouse** [comment]
@gpeal This issue can now be closed as it has been resolved.
