### ISSUE TITLE
Gradient and transparency

### ISSUE THREAD

**Issue by samiam2017** [airbnb/lottie-android#833]
[to_lottie.zip](https://github.com/airbnb/lottie-android/files/2182438/to_lottie.zip)

I'm having an issue with a linear gradient that is going from 0%--->100%----0% opacity. The json plays back correctly on the web demo, but when I play it back on the lottiefiles player on android one side does not go completely to 0% opacity before getting clipped by the shape. 

Any help would be appreciated.

**Comment by samiam2017** [comment]
K figured it out. Lottie runs into issues with the placement of opacity markers and color markers in the gradient editor. This doesn't appear to be an issue on the json files when played via the bodymovin web library. just when they are read by the lottie native plugin, only have tested on android so not sure what iOS will reveal.  If you don't have an opacity market at the beginning and end there will be an issue, and if there are not color markets between each opacity marker it appears there will be an issue as well. 
I've attach the original gradient editor setup (fewer markers) and the corrected one that solves the problem (with the extra markers).
![original gradient setting](https://user-images.githubusercontent.com/29287850/42590958-1afda466-84fa-11e8-9c13-f267f93f5b80.png)


![fixed gradient setting](https://user-images.githubusercontent.com/29287850/42590959-1b195f9e-84fa-11e8-83e4-058e1d23d766.png)

**Comment by gpeal** [comment]
@bodymovin what is the exact spec for how gradients are rendered to the values array in the json?

**Comment by samiam2017** [comment]
Hey thanks for looking into this @gpeal. I don't fully understand what you mean. Want this traveling gradient that goes from 0% opacity--> 70%--> 0%. I added in the extra points because it was banding and transitioning slow enough between the 70% and 0%. Also was seeing a hard clipping edge so I pulled the 0% away from the edge of the shape to try to guarantee that it wouldn't she the shape layer's edge. I provided the original file above.  I was looking at the asset again on lottie preview and it seems like there still might be an issue on android.

**Comment by samiam2017** [comment]
@gpeal has an update been created for this issue?

**Comment by gpeal** [comment]
No update yet. I would accept a PR though.

**Comment by samiam2017** [comment]
@gpeal what is a PR?

**Comment by samiam2017** [comment]
@gpeal is that a "pull request"? Im just a motion designer trying to use the tool. More than happy to try to learn the basics of coding to help out but don't really know where to start. What is the code base for the plugin and library?

**Comment by gpeal** [comment]
@samiam2017 Upon further inspection, I see that you used separate opacity and color stops. The correct thing to do here is to just use opacity on each color in the color stop. Lottie doesn't support opacity stops.

**Comment by rocifier** [comment]
@gpeal I have a similar issue. I'd like to take your advice to use color stops with opacity set on them but Ae 2019 only seems to support separate stops for color and opacity. Ie, you can't set the opacity of a colour, just RGB or HSL for it. Typing an extra 2 digits in hex just gets truncated. Can you please clarify what you meant by your supported solution?

**Comment by rocifier** [comment]
After a long time of playing around with this stuff, I found the above solution to pretty much work as well. I can also align the percentages of the colors with the percentages of the opacity stops and it works. But.. here's the kicker I needed to do to support multiple shapes with gradients:

**All gradient fills on shapes need to be named uniquely.** That's right.. by default mine were called "Gradient Fill 1" on each shape, and that isn't unique enough for the export to work properly.. I think it either shares or ignore ones with the same name :(

**Comment by N0t-Simon** [comment]
Hi @rocifier, my gradient doesn't appear on my export. Can you share your file ? I would like to understand how to export gradient to my Lottie file :)

**Comment by gpeal** [comment]
@N0t-Simon sometimes, they don't export unless your AEP file is saved.

**Comment by N0t-Simon** [comment]
hi @gpeal , AEP fils is saved, but gradients don't export... Have any idea ?

**Comment by gpeal** [comment]
@N0t-Simon Can you attach your aep as a zip file?

**Comment by N0t-Simon** [comment]
@gpeal sorry for time passed, find AEP attached ;) 
[Shimmer-Coupons-20191104T081811Z-001.zip](https://github.com/airbnb/lottie-android/files/3803064/Shimmer-Coupons-20191104T081811Z-001.zip)
