### ISSUE TITLE
Release 2.5.7 not on Maven

### ISSUE THREAD

**Issue by Kevinrob** [airbnb/lottie-android#835]
The last release `2.5.7` is not present on Maven.

https://mvnrepository.com/artifact/com.airbnb.android/lottie

**Comment by gpeal** [comment]
@Kevinrob It's not out yet. Master is always ahead of maven.

**Comment by Kevinrob** [comment]
Okay 👍   
I thought that it was a mistake because I see `v.2.5.7` on https://github.com/airbnb/lottie-android/releases

**Comment by PaulWoitaschek** [comment]
Why is not out yet? There is a release tag as @Kevinrob mentioned. (15 days ago)

**Comment by eygraber** [comment]
Can this please be released? Devices on Android P crash on versions less than 2.5.6, and 2.5.6 doesn't build if minSdk is lower than 24 (because of Java 8 changes).
