### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by scsfwgy** [airbnb/lottie-android#836]
Before opening a new issue:

minSdkVersion 15
targetSdkVersion 27
compileSdkVersion 27

If this is a bug:

```
Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [com.airbnb.android:lottie:2.5.5] /Users/wgyscsf/.gradle/caches/transforms-1/files-1.1/lottie-2.5.5.aar/465af30f7470f56030d89a1889e7f934/AndroidManifest.xml as the library might be using APIs not available in 15
	Suggestion: use a compatible library with a minSdk of at most 15,
		or increase this project's minSdk version to at least 16,
		or use tools:overrideLibrary="com.airbnb.lottie" to force usage (may lead to runtime failures)
```

**Comment by gpeal** [comment]
@scsfwgy 2.3.1 is the last version that supported API 14 and 15. Very few apps have minSdk < 16. Most are on 19 or 21, even very large ones.

**Comment by scsfwgy** [comment]
@gpeal  some Multiple dex files define like:

`Multiple dex files define Landroid/support/constraint/solver/widgets/ConstraintWidget$DimensionBehaviour;
`

I try to sovle like this, It‘s still cann't work! :  

```
 implementation ('com.airbnb.android:lottie:2.5.5') {
        exclude group: 'com.android.support', module: 'support-v7'
        exclude group: 'com.android.support', module: 'support-v4'
        exclude group: 'com.android.support', module: 'design'
        exclude group: 'com.android.support', module: 'recyclerview'
        exclude group: 'com.android.support', module: 'transition'
    }
```

thx!

**Comment by bahmandamia6982** [comment]
> @gpeal some Multiple dex files define like:
> 
> `Multiple dex files define Landroid/support/constraint/solver/widgets/ConstraintWidget$DimensionBehaviour; `
> 
> I try to sovle like this, It‘s still cann't work! :
> 
> ```
>  implementation ('com.airbnb.android:lottie:2.5.5') {
>         exclude group: 'com.android.support', module: 'support-v7'
>         exclude group: 'com.android.support', module: 'support-v4'
>         exclude group: 'com.android.support', module: 'design'
>         exclude group: 'com.android.support', module: 'recyclerview'
>         exclude group: 'com.android.support', module: 'transition'
>     }
> ```
> thx!

Not worked for me? another way?

**Comment by chanonly123** [comment]
`implementation` ('com.airbnb.android:lottie:3.0.1') { transitive = false }`  
worked for me
and also androidx compatible
