### ISSUE TITLE
External image won't load

### ISSUE THREAD

**Issue by jonathanisaac** [airbnb/lottie-android#837]
Hi, great job with the lottie,

I have a problem with Android, the external image generated by bodymovim is not loading (the animation is loading normally), I've tried some things listed here, without success.

**Note:** Everything works perfectly well with the demo of bodymovim (html + javascript)

I'm working as follows:

```
<com.airbnb.lottie.LottieAnimationView
        xmlns: app = "http://schemas.android.com/apk/res-auto"
        android: layout_width = "wrap_content"
        android: layout_height = "wrap_content"
        android: layout_marginLeft = "@dimen/default_huge_margin"
        android: layout_marginRight = "@dimen/default_huge_margin"
        android: layout_gravity = "center_horizontal|center_vertical"
        app: lottie_rawRes = "@raw/loading"
        app: lottie_imageAssetsFolder = "images/"
        app: lottie_loop = "true"
        app: lottie_autoPlay = "true" />

```

Being my **assets** and **raw** (Android Folder):

```
app/
   assets/
      images/
          img_0.png
   res/
      raw/  
          loading.json
```

Inside **loading.json** I have:

```
"assets": [{
        "id": "image_0", 
        "w": 1024, 
        "h": 1024, 
        "u": "images/", 
        "p": "img_0.png",
        "e": 0
}]
```

**Notes:**
I already tried changing the "id" and/or "refid" to "loading", "img_0" ...
if I change

```

app: lottie_imageAssetsFolder = "images/" 
app: lottie_imageAssetsFolder = "/"

```

I got (proof that "images/" path is correct): 
```

W / LOTTIE: Unable to open asset. java.io.FileNotFoundException: /img_0.png

```

I'm using the latest version.

```

implementation 'com.airbnb.android:lottie:2.5.5'

```

**If it is not a path problem, it is not a problem in rendering, it is not a problem in bodymovin, what would be the problem if the image does not appear?**

**Comment by gpeal** [comment]
@jonathanisaac Can you attach a sample project that repros this?

**Comment by jonathanisaac** [comment]
Hi @gpeal , 

Sorry for the delay, I ended up converting the image to vectors and solved my problem. 

But I believe that this information can help in some way, so I decided to recreate the same experience.
**Attached files**, in case you need any additional information, please contact me.

Just an additional info: I'm using Kotlin and on iOS I had no problem.

[testing_purpose.aep.zip](https://github.com/airbnb/lottie-android/files/2204024/testing_purpose.aep.zip)

**Comment by gpeal** [comment]
@jonathanisaac It probably won't render because your image is 1024x1024. That will get converted to dp on device and will try to render it at ~3000x3000. That's too large to fit in a software graphics buffer and Android will silently drop it.

**Comment by gongtingshisi** [comment]
me too,any resolution ?
