### ISSUE TITLE
Render Graph vs. Android GPU rendering profiler

### ISSUE THREAD

**Issue by gautamjain** [airbnb/lottie-android#844]
I'm trying to better understand rendering performance.

To test an animation - I opened Render Graph and turned on the Android Profile GPU Rendering tool at the same time.

![screenshot_20180718-120530 1](https://user-images.githubusercontent.com/1161630/42904600-5f3fc56a-8a8a-11e8-9f07-b028a591570c.png)

The graphs seem contradictory.  The Android tool shows the 16 ms target is not being met, whereas Render Graph (in the background) is showing well below 16 ms.

Do you have any insight as to what might be going on here?  fwiw, visually there does not seem to be any dropped frames or jank.

**Comment by gpeal** [comment]
@gautamjain the render graph measures the time from the beginning of drawing to the end of drawing. The bars show the value for the entire screen which may have additional overhead.
