### ISSUE TITLE
Failed to resolve: com.airbnb.android:lottie:2.5.5

### ISSUE THREAD

**Issue by JaySX** [airbnb/lottie-android#845]
Android Studio 3.1.3
Gradle 3.3
compileSdkVersion = 25
compile 'com.airbnb.android:lottie:2.5.5'

**Comment by gpeal** [comment]
2.5.5 and 2.5.6 are both on [maven central](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.airbnb.android%22%20AND%20a%3A%22lottie%22).
