### ISSUE TITLE
Request: add Android-Studio plugin, to preview Lottie Json files

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [airbnb/lottie-android#852]
Currently the only way to go through the animations files (in `/res/raw/...`) , is via the device.
Please allow to preview the files within the IDE itself.
Maybe also have a gallery view of them, similar to this plugin, which shows VectorDrawable files in a gallery style :

https://plugins.jetbrains.com/plugin/10741-vector-drawable-thumbnails

**Comment by gpeal** [comment]
@AndroidDeveloperLB The canvas APIs in IntellJ don't render accurately enough. Most have serious rendering errors.

**Comment by AndroidDeveloperLB** [comment]
How come the Vector plugin succeeded?
It also handles vectors...
And how come Google succeeded showing VectorDrawables...

Please re-consider.
It's impossible to manage Lottie files this way, especially when we have a lot of them...

At the very least, make a plugin that I will tell it to show which image for each lottie file. An image shouldn't be a problem, right?

**Comment by YassinCoffeeIT** [comment]
+1

**Comment by AbdulDroid** [comment]
> How come the Vector plugin succeeded?
> It also handles vectors...
> And how come Google succeeded showing VectorDrawables...
> 
> Please re-consider.
> It's impossible to manage Lottie files this way, especially when we have a lot of them...
> 
> At the very least, make a plugin that I will tell it to show which image for each lottie file. An image shouldn't be a problem, right?

+1

**Comment by rayarteagas** [comment]
+1

**Comment by RyfThink** [comment]
+1

**Comment by rbenza** [comment]
+1

**Comment by Llorc** [comment]
+1

**Comment by abhishekgidde** [comment]
+1

**Comment by dwzrlp** [comment]
+1

**Comment by birdieandreea** [comment]
+1
