### ISSUE TITLE
Android frame drop after updating from 2.3.0 to 2.5.5

### ISSUE THREAD

**Issue by klamborowski** [airbnb/lottie-android#853]
I have problem with frame drop/animation lag in my app tutorial. Everything was fine, when I was using version 2.3.0, but after updating to 2.5.5 animation starts lagging and lost frames.

This bug can be reproduced with sample app "Animated App Tutorial". Open app tutorial and swipe page slowly. 

Below two screen records showing diffrence in behaviour.

[2_3_0.zip](https://github.com/airbnb/lottie-android/files/2228422/2_3_0.zip)
[2_5_5.zip](https://github.com/airbnb/lottie-android/files/2228423/2_5_5.zip)

Is there any property, which I can set to achieve the same behaviour as in  2.3.0?

**Comment by gpeal** [comment]
@klamborowski I cannot reproduce this. This is the render graph of the animation on master:
<img width="562" alt="screen shot 2018-08-04 at 10 59 34 am" src="https://user-images.githubusercontent.com/1307745/43679175-9e76be98-97d5-11e8-91fc-cdf4cefb1214.png">

If you could create an actual sample project that reproduces this, I can take another look.
Lottie has many systrace markers so if you could run systrace and see if you can identify any culprits, that would also make things much easier.
