### ISSUE TITLE
Android frame drop 2.2.0 to 2.5.5

### ISSUE THREAD

**Issue by dujp** [airbnb/lottie-android#857]
Before opening a new issue:

* Look through open and existing issues for duplicates.
* Apply an appropriate label.

If this is a bug:
* Simplify your animation to the simplest animation that reproduces the issue.
* Attach your After Effects file.

If this is a feature request:
* Explain what feature you would like and why you need it. There are usually After Effects
workarounds that we can provide in the meantime that achieve the same effect.

If you leave the template text in your issue, it will be closed.

**Comment by ColtonIdle** [comment]
> If you leave the template text in your issue, it will be closed.

 :eyes:
