### ISSUE TITLE
About licencing issues

### ISSUE THREAD

**Issue by gkathir15** [airbnb/lottie-android#86]
As seen so far,
there is no license specified,
so if I have this to be used in my projects which may be used commercial,
does Bodymovin come under Gnu or open source license or how
Will there be any legal issues forward?

**Comment by hansemannn** [comment]
The Lottie library is under [Apache 2](https://github.com/airbnb/lottie-android/blob/master/LICENSE), Bodymovin under [MIT](https://github.com/bodymovin/bodymovin/blob/master/LICENSE.md).

**Comment by gkathir15** [comment]
Yeah Thanks @hansemannn
