### ISSUE TITLE
Question: lottie_autoPlay not available at runtime?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [airbnb/lottie-android#860]
Currently we can use LottieAnimationView within a layout, as such:

        <com.airbnb.lottie.LottieAnimationView
            android:id="@+id/animationView" android:layout_width="match_parent" android:layout_height="match_parent"
            android:background="#000" android:scaleType="centerCrop" app:lottie_autoPlay="true" app:lottie_loop="true"
            app:lottie_rawRes="@raw/flow" tools:alpha="0.1" tools:src="@android:drawable/sym_def_app_icon"/>

Thing is, sometimes we would want to create it in code:

                val animationView=LottieAnimationView(context)
                animationView.setBackgroundColor(0xff000000.toInt())
                animationView.scaleType=ImageView.ScaleType.CENTER_CROP

But when I wanted to set the alternative to lottie_autoPlay , I can't find it. 

How come?

**Comment by gpeal** [comment]
If you just call `playAnimation()` it will queue it up for when the composition loads and have the same effect.

**Comment by AndroidDeveloperLB** [comment]
Why the different naming? It's confusing ... :(
