### ISSUE TITLE
How to download and apply multiple images?

### ISSUE THREAD

**Issue by scsfwgy** [airbnb/lottie-android#862]
If this is a feature request:

I want apply multipe imges,but this method just return a Bitmap:

`animationView.setImageAssetDelegate(new ImageAssetDelegate() {
  @Override public Bitmap fetchBitmap(LottieImageAsset asset) {
    if (downloadedBitmap == null) {
      // We don't have it yet. Lottie will keep
      // asking until we return a non-null bitmap.
      return null;
    }
    return downloadedBitmap;
  }
});`

ref:
 #290
http://airbnb.io/lottie/android/images.html

**Comment by gpeal** [comment]
@scsfwgy Each image has an id. You can only have one image per id.

**Comment by scsfwgy** [comment]
@gpeal  Thx, I know the concept of "Each image has an id".    But, when I download  a jsop file with mulitpe images from service,like this:
![image](https://user-images.githubusercontent.com/16045179/43705514-4460c5b8-9995-11e8-9ff9-7ddddf3e7ba1.png)   ,   how can i load the mulitpe images by below method,or there are other ways to load multiple images downloaded from the network?




animationView.setImageAssetDelegate(new ImageAssetDelegate() {
  @Override public Bitmap fetchBitmap(LottieImageAsset asset) {
    if (downloadedBitmap == null) {
      // We don't have it yet. Lottie will keep
      // asking until we return a non-null bitmap.
      return null;
    }
    return downloadedBitmap;
  }
});

**Comment by scsfwgy** [comment]
ref :https://github.com/airbnb/lottie-android/commit/8439bdc370a9ca9a8d6f9e9272fd24774aacacfd

**Comment by pagrawal1407** [comment]
@gpeal Hello! I used the LottieCompositionFactory.fromUrl() method to download Lottie animations from network and they are working fine. Thanks for providing that use case. But I need to download 20-30 Lottie compositions from server, so I was wondering if there is a way to batch those network requests and pre-download the Lottie Compositions (Json) from server and then use them wherever required?

**Comment by gpeal** [comment]
@pagrawal1407 Yes, just call `LottieCompositionFactory.fromUrl()` whenever you want to start preloading them. Internally, Lottie will join that task if it is in-flight and also cache the composition in a LruCache so it will be available immediately if called again after it finishes.

**Comment by Ravipatel401** [comment]
Hello,
 
Need help! 
Stuck on getting images from the directory(Just want Lottie automatically get images from given folder )
