### ISSUE TITLE
Expo XDE where is Assets Folders? 

### ISSUE THREAD

**Issue by shipcake** [airbnb/lottie-android#864]
1.) i have a json file and i export (babymovin in Adobe AF) with images Assets . Jpg Because if i include the shape. file is too big (about 215KB) render so a liite lag (Real Samsung S8+)
2.) i use expo XDE and run on android simulator i can't find Assets in my project folders same the Lottie Guidebook

<Lottie
          source={require('./img/data.json')} 
          ref={animation => {this.animation = animation;}}
          imageAssetsFolder={'lottie/bg'}
/>

**Comment by gpeal** [comment]
Please post this on [lottie-react-native](https://github.com/react-community/lottie-react-native)
