### ISSUE TITLE
Animation doesn't work when positioned above enabled Button

### ISSUE THREAD

**Issue by Goudri** [airbnb/lottie-android#870]
in the attached XML layout file, when i change the button state to enabled="true", the animation doesn't work, else when i change it to false it's work properly.
this problem occur in android api 20+ 
when i test it in android api 19 it's work without any problem.
what i found is that i shouldn't put the animation above the button.
Xml layout: 
--------------
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        
        <Button
            android:id="@+id/button_select_video"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:textColor="@color/colorPrimary"
            android:enabled="true"
            android:text="select_video"/>

        <com.airbnb.lottie.LottieAnimationView
            android:id="@+id/check_animation_select_video"
            android:layout_width="36dp"
            android:layout_height="36dp"
            app:lottie_rawRes="@raw/heart"
            android:layout_gravity="end|center_vertical"
            android:layout_marginRight="8dp"
            android:layout_marginEnd="8dp"
            app:lottie_autoPlay="true"
            app:lottie_loop="true"
            app:lottie_enableMergePathsForKitKatAndAbove="true"
            />

    </FrameLayout>

    </LinearLayout>

</android.support.constraint.ConstraintLayout>
----------------
in the xml above if you change the button state to disabled, the animation work.

**Comment by Goudri** [comment]
nothing, still the same prblm.

**Comment by gpeal** [comment]
@Goudri This is unlikely a Lottie issue since it's just a Drawable and doesn't do anything pertaining to layout. If you can create a sample project that repros this, please attach it as a zip file and reopen.

**Comment by tsuharesu** [comment]
I had the same _problem_ and what happens is that `Button` have elevation on API 21+. To overcome this, you have to set `android:elevation="Xdp"` on your `com.airbnb.lottie.LottieAnimationView`

Src: https://stackoverflow.com/a/28980908/1981356
