### ISSUE TITLE
setMinAndMaxFrame isn't working 2.5.5

### ISSUE THREAD

**Issue by minudf** [airbnb/lottie-android#872]
Hello.
In 2.5.5 version, setMinAndMaxFrame isn't working properly.
        animationView.setMinAndMaxFrame(50, 100);
        animationView.setRepeatCount(-1);
        animationView.playAnimation();
It doesn't repeat 50~100 frame, it's repeating whole frame.
It's working properly in 2.5.4 version.

Thank you.

**Comment by minudf** [comment]
@gpeal You can use any JSON file for this case.
And code is very simple.
   animationView.setMinAndMaxFrame(50, 100);
   animationView.setRepeatCount(-1);
   animationView.playAnimation();
Thank you.

**Comment by krishom** [comment]
I experienced the same problem with 2.5.5 on Android only. iOS plays the specified frames correctly.

Downgrading to 2.5.4 in my build.gradle with the resolutionStrategy below makes it work again on Android.

subprojects { subproject ->
    configurations.all {
        resolutionStrategy {
            force 'com.airbnb.android:lottie:2.5.4'
        }
    }
}

**Comment by handstandsam** [comment]
Thank you!  I got a codebase with `2.5.1` that had this problem, and upgrading to `2.7.0` fixed it!  Upgrading to 2.8.0 threw all kinds of `androidx` exceptions, but luckily `2.7.0` has everything I need regarding this.  Thanks!
