### ISSUE TITLE
this method should be protected or public to be overridden in subclass

### ISSUE THREAD

**Issue by fb64** [airbnb/lottie-android#873]
https://github.com/airbnb/lottie-android/blob/f675a5575db138e759f09e71806d1a913539ecd0/lottie/src/main/java/com/airbnb/lottie/TextDelegate.java#L47

**Comment by gpeal** [comment]
That's actually not how the API works. There is [an example](https://github.com/airbnb/lottie-android/blob/master/LottieSample/src/main/kotlin/com/airbnb/lottie/samples/DynamicTextActivity.kt) in the sample app.

The input text is the text in the original animation. The output text is what it should be replaced with.

**Comment by fb64** [comment]
Ok, thanks. 
Class comment misled me:
```java
**
 * Extend this class to replace animation text with custom text. This can be useful to handle
 * translations.
 *
 * The only method you should have to override is {@link #getText(String)}.
 */
```
