### ISSUE TITLE
LottieToggleView implementation ?

### ISSUE THREAD

**Issue by stanbar** [airbnb/lottie-android#874]
Hello,
Since I don't like to reinvent wheel, is there any ToggleView implementation for LottieAnimationView ? Uncheck could be reverse animation, or even better custom check and uncheck animation. I think it's quite common for "Like" button

**Comment by CoderVishalSehgal** [comment]
@stanbar Check out this If you're looking for something like this, https://github.com/CoderVishalSehgal/lottie-toggles

@gpeal Can I raise a PR for a custom LottieToggleView/ switch for same? Jetpack compose supportably. Please have a look at the link I shared above. Here is the [sample app](https://play.google.com/store/apps/details?id=dev.vishalsehgal.lottietoggles.sample)

P.S- Entered late to the party.
