### ISSUE TITLE
How do we interact with animations in lottie?

### ISSUE THREAD

**Issue by sriranjanr** [airbnb/lottie-android#875]
I came across lottie and lottie just blew my mind away. Such fast and nice animations we can do in android now with lottie but one question has been troubling my mind since yesterday and I was unable to sleep. My question is how can we make interactive animations like the bulls eye example in lottie app? How can we interact with the elements in animation or part of the animation using lottie? I want to know the source code for bulls eye example and where can I find its source code? Has the bulls eye interactive animation been made in after effects? I do now want to know about the dynamic properties example because the way we are interacting with it is not actually true interaction with animation because we press buttons on the bottom portion of the screen to change the attributes of the animation, where as in the bulls eye example you are actually touching the elements of the animation like the blue circle and the animation attributes are being changes. So I want to know how to create interactive animations like these.. My other question is can we make interactive animated buttons in lottie, like you click on the actual animated button and it gets animated. Where can I find source code for animated interactive buttons? And how do we create animated user interfaces using lottie? Please let me know. I am excited to learn lottie.

**Comment by gpeal** [comment]
Glad you're excited for Lottie 😄 
[Here](https://github.com/airbnb/lottie-android/blob/master/LottieSample/src/main/kotlin/com/airbnb/lottie/samples/BullseyeActivity.kt) is the code for the bullseye demo!

**Comment by sriranjanr** [comment]
So what you are saying is this bulleye demo has got nothing to do with adobe after effects animation? How do I create an animated button (animation done in after effects,imported by lottie to android) and interact with it? Please let me know.

**Comment by laustdeleuran** [comment]
+1. The documentation is incredibly sparse, for all platforms. I'm mostly interested in how to do this for web, but it's hard to find this documentation regardless of platform. Thanks!

**Comment by Superhands89** [comment]
@laustdeleuran @sriranjanr Did you find a method of achieving interactivity by clicking on elements within the animation?

**Comment by laustdeleuran** [comment]
@Superhands89 Sorry, this was so long ago that I honestly don't remember :/
