### ISSUE TITLE
How do I create an animated button in lottie?

### ISSUE THREAD

**Issue by sriranjanr** [airbnb/lottie-android#876]
How do I create an animated button in lottie? Are there example codes and tutorials for this? What I want to do is create the button animation in after effects but when I import with lottie in android, I want to interact with it. Like I click on the button, it should play the button animation and also it should run a subtask, or another function in android. Please let me know.

**Comment by gpeal** [comment]
Hi @sriranjanr you can use standard APIs like `playAnimation()` and `reverseAnimationSpeed()` to achieve this.

And use LottieDrawable instead of LottieAnimationView.
