### ISSUE TITLE
How can the animation itself in its whole be a button or a part of it

### ISSUE THREAD

**Issue by sriranjanr** [airbnb/lottie-android#880]
I understand that adobe effects will help with creating the animation. But my question is how can the animation that is **imported from after effects** itself be a button or some elements of the animation be a button? How to implement this. Any example code would help.

**Comment by sriranjanr** [comment]
Guys...any idea on how to achieve this. I want to start my development with lottie. Please share some ideas on this.

**Comment by gpeal** [comment]
There is an entire [sample app](https://github.com/airbnb/lottie-android/tree/master/LottieSample) in the repo and a site with lots of documentation [here](http://airbnb.io/lottie/).
