### ISSUE TITLE
How to intercept each frame of the animation

### ISSUE THREAD

**Issue by panzhi1** [airbnb/lottie-android#883]
I need intercept each frame of the animation,how can i do?
I try to animationView.draw(canvas),but it occasionally cause memory problem.
such as Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 5839.how can i do ?thank you

**Comment by panzhi1** [comment]
Only slightly more complicated text type animations will happen

**Comment by gpeal** [comment]
You can use the dynamic properties API
http://airbnb.io/lottie/android/dynamic.html

**Comment by panzhi1** [comment]
Thank you! But this doesn't seem to solve my problem.how can i do ?

**Comment by panzhi1** [comment]
I try it in lottie 2.5.5 .but the valuecallback without effect.please you help me!
