### ISSUE TITLE
Execute CompositionLoader classes with the Thread Pool Executor

### ISSUE THREAD

**Issue by mauricio9308** [airbnb/lottie-android#89]
I have encountered with an special case that involves multiple AsyncTasks running in a Context, where the fact that the Composition Loader is running in the basic AsyncTask Executor is causing problems with the task execution order.

I don't know if there's a reason, on why the loader task are executed this way, but it would be great to take a look on this.

**Comment by gpeal** [comment]
@mauricio9308 This would be a nice improvement. Feel free to submit a PR to get this in sooner. If not, I'll try to get around to it soonish.

**Comment by felipecsl** [comment]
I can take a look into this one
