### ISSUE TITLE
  Fixed the width and height of the LottieAnimationView. The animation display is incomplete.

### ISSUE THREAD

**Issue by webyouling** [airbnb/lottie-android#890]
My layout is like this
<com.airbnb.lottie.LottieAnimationView
        android:layout_below="@+id/iv_refresh_header"
        android:id="@+id/lottieAnimationView"
        android:layout_width="@dimen/dp_50"
        android:layout_height="@dimen/dp_50"
        android:scaleType="centerCrop"
        android:layout_centerHorizontal="true"
        app:lottie_cacheStrategy="strong"
        app:lottie_repeatCount="-1"/>
![screenshot_2018-08-13-10-05-38](https://user-images.githubusercontent.com/33200001/44009799-dc6454a6-9ee0-11e8-8edd-50d4f7ee32fc.png)
May I ask if this situation should be solved?

**Comment by gpeal** [comment]
Use `centerInside`. If that doesn't resolve it. Attach a sample project that repros this.
