### ISSUE TITLE
Text Layer can not use dynamic properties?

### ISSUE THREAD

**Issue by panzhi1** [airbnb/lottie-android#892]
I try add a colorfilter properties to text layer,but it is invalid.
 sticker.getAnimationView().addValueCallback(keyPaths.get(0), LottieProperty.COLOR_FILTER, new LottieValueCallback(colorFilter);
the keyPaths.get(0) is a text layer.

**Comment by gpeal** [comment]
Text does not support color filters. I would accept a pull request for this though.

**Comment by kartik1225** [comment]
> Text does not support color filters. I would accept a pull request for this though.

It seems like we are still not able to use `color filters` in `v3.0.0` .
Can you suggest alternative solution? If any !
