### ISSUE TITLE
Add value callbacks for RectangleContent

### ISSUE THREAD

**Issue by gpeal** [airbnb/lottie-android#894]

**Comment by MONIKA-KUMAR-JETHANI** [comment]
Hi @gpeal , Is this issue open?Can you please describe the issue?

**Comment by gpeal** [comment]
@MONIKA-KUMAR-JETHANI [This](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/animation/content/RectangleContent.java#L158) was never implemented.

**Comment by gpeal** [comment]
![image](https://user-images.githubusercontent.com/1307745/53290939-247bec00-3760-11e9-8eb5-536b3a120c18.png)
