### ISSUE TITLE
text deformation in bitmap

### ISSUE THREAD

**Issue by ArtisanM** [airbnb/lottie-android#896]
this is my origin bitmap provided by ImageAssetDelegate
my debug screenshot:
[http://7xt2sn.com1.z0.glb.clouddn.com/1.jpg](url)
text in bitmap is normal,but after canvas.drawBitmap(bitmap, src, dst , paint); excuted
the text  transformed
debug screenshot:[http://7xt2sn.com1.z0.glb.clouddn.com/2.jpg](url)

why?how can i fix it

**Comment by gpeal** [comment]
@ArtisanM You'll need to attach an AEP file that reproduces this. If this is still an issue, feel free to do so and reopen.
