### ISSUE TITLE
Animation stays in final state in Android, works fine on iOS and web

### ISSUE THREAD

**Issue by Jcongdon91** [airbnb/lottie-android#897]
The animation stays in its final state, but “animates” for the time set in the duration (verified in Android Lottie Preview app).  No warnings are provided in the Preview app. It works perfectly fine in iOS and on web.

[hired.json.zip](https://github.com/airbnb/lottie-android/files/2288478/hired.json.zip)

After Effects file:
[hired.zip](https://github.com/airbnb/lottie-android/files/2288499/hired.zip)

**Comment by Mikerr1111** [comment]
What version of Android and Gradle are you running?

**Comment by Jcongdon91** [comment]
API 27 & 28 and Gradle 4.9. The animation also didn't work in the Lottie Preview app on API 28

**Comment by gpeal** [comment]
@Jcongdon91 in Lottie Android, a shape can only have one trim path. Delete "Trim Paths 1" and it works perfectly.
