### ISSUE TITLE
Question: is it possible to show Lottie animation in live wallpaper?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [airbnb/lottie-android#899]
If so, what's the best way to do it?

**Comment by gpeal** [comment]
I have never used a live wallpaper. Lottie is just a drawable so you should be able to use it anywhere you can use a drawable.

**Comment by AndroidDeveloperLB** [comment]
Why close the issue?
Can a drawable really be used in a live wallpaper ? Can you please show how?

**Comment by AndroidDeveloperLB** [comment]
I don't see that drawing a Drawable is mentioned there. Are you sure they talk about it?

**Comment by Glennmen** [comment]
I am trying to do the same but so far it isn't working. @AndroidDeveloperLB where you able to find the solution?

My code so far:
```kotlin
		private val lottieDrawable: LottieDrawable = LottieDrawable()

        init {
            lottieDrawable.apply {
                composition =
                    if (context.resources.configuration.orientation == Configuration.ORIENTATION_PORTRAIT) {
                        setMinAndMaxFrame(0, 40)
                        LottieCompositionFactory.fromRawResSync(
                            context,
                            R.raw.launcher_bg_port
                        ).value!!
                    } else {
                        setMinAndMaxFrame(0, 20)
                        LottieCompositionFactory.fromRawResSync(context, R.raw.launcher_bg).value!!
                    }

                speed = 0.6f
                addAnimatorUpdateListener {
                    draw()
                }
            }
        }

        override fun onSurfaceCreated(holder: SurfaceHolder?) {
            super.onSurfaceCreated(holder)
            lottieDrawable.playAnimation()
        }

        private fun draw() {
            val holder: SurfaceHolder = surfaceHolder
            var canvas: Canvas? = null

            try {
                canvas = holder.lockCanvas()
                if (canvas != null) {
                    canvas.drawColor(Color.CYAN) // TODO correct background color
                    lottieDrawable.draw(canvas)
                }
            } finally {
                if (canvas != null) {
                    holder.unlockCanvasAndPost(canvas)
                }
            }
        }
```

**Comment by Glennmen** [comment]
Just an update @AndroidDeveloperLB 
I was able to find the problem and got it working.
For us it didn't work because we had a base64 image in our lottie json, using a lottie json with only vectors does work (with above code).

**Comment by AndroidDeveloperLB** [comment]
@Glennmen So the above works? This includes when you don't want a background? If so, how do you avoid the background?

**Comment by Glennmen** [comment]
@AndroidDeveloperLB Yes the above code worked for me, after replacing the lottie json with one that only contains vector images.
What do you mean with don't want a background? Wallpaper service is your background.

**Comment by AndroidDeveloperLB** [comment]
@Glennmen I mean the part of `// TODO correct background color` . Would removing this line make the background transparent?

**Comment by Glennmen** [comment]
@AndroidDeveloperLB Oh I see what you mean.
Removing that will not work because wallpaper services reuses the same canvas and it will draw your animation over and over again on top of your previous frames.

But maybe you can do `canvas.drawColor(Color.TRANSPARENT)` or `canvas.drawColor(Color.TRANSPARENT, PorterDuff.Mode.CLEAR)`
I can try in about an hour and let you know.

**Comment by Glennmen** [comment]
@AndroidDeveloperLB Drawing a static image on the canvas works, I did that last week already.
But what are you trying to do? Because leaving the background transparent will only be black anyways as there is nothing behind it.

**Comment by AndroidDeveloperLB** [comment]
@Glennmen I was just wondering if I could go one frame after another, as a Bitmap that I can see during debug.
But then, couldn't I avoid being in sync with the playing of the Drawable? Can't I tell the Drawable to go over each frame, and use some FPS ? 
Also, why do you have setMinAndMaxFrame ? I think you can avoid using it, no?

**Comment by Glennmen** [comment]
@AndroidDeveloperLB Getting one frame at a time would require some changes, manually setting the frame and drawing it at a set framerate using a runnable + delay. But that is not what I wanted, I wanted a real animated background.

I think I have `setMinAndMaxFrame` because the animation file itself had some other things in it that we don't want. Not sure anymore honestly, the files are old but we are making new ones so that can indeed be removed.

**Comment by AndroidDeveloperLB** [comment]
@Glennmen I think there is some Lottie-to-mp4 project out there that does it.

**Comment by thelou1s** [comment]
I draw Lottie json in Wallpaper.Engine like this, the only problem is Animation is running without images:

```
// lottie animator
                    lottieAnimator.cancel()
                    lottieAnimator.setIntValues(0, lottieDrawable.maxFrame.toInt())
                    lottieAnimator.repeatCount = LottieDrawable.INFINITE
                    lottieAnimator.duration = 6000
                    lottieAnimator.addUpdateListener { anim ->
                        val frame = anim.animatedValue as Int
                        lottieDrawable.frame = frame
                        // lottieDrawable.draw(canvas)
                        Log.i(TAG, "LOT::addUpdateListener, frame = ${lottieDrawable.frame}")
                    }
                    lottieAnimator.start()
```

I post an issue, but got no reply yet: https://github.com/airbnb/lottie-android/issues/2085

**Comment by Glennmen** [comment]
@thelou1s You need to draw it on the SurfaceHolder of the Wallpaper Engine.

**Comment by thelou1s** [comment]
@Glennmen Yes, I did it in the SurfaceHolder. And finally it works by setting a FakeAnimView: https://stackoverflow.com/questions/72443966/images-not-showing-after-load-my-lotties-json-into-lottiedrawable-in-surfacehol

**Comment by Glennmen** [comment]
@thelou1s I didn't need to do that but glad you found a solution.

This was basically everything that I did 🤷‍♂️
```kotlin
private fun draw(context: Context) {
    if (isVisible) {
        val holder: SurfaceHolder = surfaceHolder
        var canvas: Canvas? = null

        try {
            canvas = holder.lockHardwareCanvas()
            if (canvas != null) {
                val bgColor: Int =
                    context.getThemeColor(R.attr.bg_home, R.color.default_bg_home)
                canvas.drawColor(bgColor)

                lottieDrawable.apply {
                    val scale = (canvas.width.toFloat() / composition.bounds.width())
                    canvas.scale(scale, scale)
                    draw(canvas)
                }
            }
        } finally {
            if (canvas != null) {
                holder.unlockCanvasAndPost(canvas)
            }
        }
    }
}
```
