### ISSUE TITLE
3D Layers and trim paths not exporting 

### ISSUE THREAD

**Issue by sharonyu822** [airbnb/lottie-android#901]
Hi, 
I'm having trouble with exporting strokes and getting recognition of 3d layers on this file.. It works fine on the Lottie's web preview but on Android it shows up as 2d layers and without a stroke. The trim paths seem to not be working as well.

[ANIMATE.aep.zip](https://github.com/airbnb/lottie-android/files/2304132/ANIMATE.aep.zip)

**Comment by gpeal** [comment]
Lottie doesn't support 3d layers. If you're having issues with trim paths on 2d layers, you can reopen.
