### ISSUE TITLE
Animations with transparency transitions are rendered differently in Android

### ISSUE THREAD

**Issue by nima-ahmadi** [airbnb/lottie-android#902]
In a transparency transition (like a fade-out), Android seems to be adding up the overlapping layers (in the same group) while it is not happening in iOS/web. I think the iOS/web behaviour in expected.

[files.zip](https://github.com/airbnb/lottie-android/files/2306869/test.for.lottie.zip)

![lottie](https://user-images.githubusercontent.com/5301577/44410219-f2c86500-a531-11e8-8598-56551c82caa4.png)

**Comment by gpeal** [comment]
This is a limitation of the way opacity works on Android. To achieve the correct behavior would incur a huge performance penalty unfortunately.

**Comment by gpeal** [comment]
@nima-ahmadi  3.1.0 will have a new API `setApplyingOpacityToLayersEnabled` where you can manually enable this to render correctly. It isn't on by default because there is a performance overhead in doing so.

**Comment by nima-ahmadi** [comment]
Great! Thanks for keeping Lottie awesome! @gpeal @r-ralph
