### ISSUE TITLE
Textfield not shown right in Android

### ISSUE THREAD

**Issue by D4rkness** [airbnb/lottie-android#908]
There is a kind of strange issue with the Textfield.

When exporting centered text from after effects, it is displayed left aligned in android. It is also positioned with an offset to the right (half of the width of the textfield to the right).
But in the preview it looks totally fine.

Here the AE and the json files:
[sample_datar.zip](https://github.com/airbnb/lottie-android/files/2318175/sample_datar.zip)

Android screen:

![screen](https://user-images.githubusercontent.com/18185328/44583177-71c4d400-a7a4-11e8-9896-b1f4a9783395.png)

**Comment by gpeal** [comment]
(closing duplicate)
