### ISSUE TITLE
Extract resource loading/caching logic out of LottieAnimationView

### ISSUE THREAD

**Issue by evant** [airbnb/lottie-android#909]
There are cases where you want to use the `LottieDrawable` directly in a custom view instead of using a `LottieAnimationView`. To make this easier, it would be nice if the resource loading and caching logic can be reused. This would also allow a single cache to be shared between both.

Haven't thought about the api much, but something like:
```java
LottieCompositionInflater.from(context).inflate(R.raw.my_animation, CacheStrategy.Weak, composition -> {
    ...
});
```

**Comment by evant** [comment]
Actually, seems like this might be in `2.6.0` with `LottieCompositionFactory`, is this going to be released soon?

**Comment by gpeal** [comment]
Yes, very soon! 2.6.0-beta19 is already on maven.
