### ISSUE TITLE
 java.lang.AssertionError

### ISSUE THREAD

**Issue by ValuesFeng** [airbnb/lottie-android#913]
java.lang.RuntimeException:An error occurred while executing doInBackground()
--
2 android.os.AsyncTask$3.done(AsyncTask.java:353)
3 ......
4 Caused by:
5 java.lang.AssertionError:
6 android.util.JsonReader.peek(JsonReader.java:363)
7 android.util.JsonReader.expect(JsonReader.java:308)
8 android.util.JsonReader.beginObject(JsonReader.java:293)
9 com.airbnb.lottie.d.u.a(LottieCompositionParser.java:42)
10 com.airbnb.lottie.e$a.a(LottieComposition.java:276)
11 com.airbnb.lottie.d.e.a(AsyncCompositionLoader.java:22)
12 com.airbnb.lottie.d.e.doInBackground(AsyncCompositionLoader.java:12)
13 android.os.AsyncTask$2.call(AsyncTask.java:333)
14 java.util.concurrent.FutureTask.run(FutureTask.java:266)
15 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
16 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
17 java.lang.Thread.run(Thread.java:764)

System version
Android 8.0.0

ROM
samsung/star2qltezc

**Comment by gpeal** [comment]
@ValuesFeng Please attach the crashing animation.

**Comment by Abelzzg** [comment]
why you close this ? It just happened in v2.6.0

**Comment by gpeal** [comment]
@Abelzzg Forgot to link to this but https://github.com/airbnb/lottie-android/pull/1013
