### ISSUE TITLE
lottie replace the image in animation

### ISSUE THREAD

**Issue by panzhi1** [airbnb/lottie-android#918]
Can lottie dynamically replace the images in the animation with local images or bitmaps?
I try use the image in assets replace animation's image,it is effective.now I want use local image ,how i can do?thank you

**Comment by gpeal** [comment]
Use [ImageAssetDelegate](http://airbnb.io/lottie/android/images.html#providing-your-own-images)

**Comment by rkcoders** [comment]
hello if i want to replace images dynamically with other image ?
in ImageAssetDelegate all image replace with  bitmap which i have passed

**Comment by panzhi1** [comment]
you  can use ImageAssetsDelegate .
By assetsId , you can replace the image that you need replace;
