### ISSUE TITLE
how to reverse animation?

### ISSUE THREAD

**Issue by taejungkim** [airbnb/lottie-android#92]
I want to playing reverse animation after cancel animation.

Instead of using Handler and LottieAnimView.setProgress(x) to reverse played time,
i want to find other ways.
ex) ValueAnimator.reverse()

**Comment by taejungkim** [comment]
I solved this issue. 

```
        float progress = animView.getProgress();
        ValueAnimator valueAnimator = ValueAnimator.ofFloat(-progress,0 ).setDuration((long) ( animView.getDuration()* progress));
        valueAnimator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
            @Override
            public void onAnimationUpdate(ValueAnimator animation) {
               
                animView.setProgress(Math.abs((float)animation.getAnimatedValue()));
            }
        });
        valueAnimator.start();
```

**Comment by wildstarzw** [comment]
I also had this problem, you can try clearAnimation() and setAnimation again. Its work for me.

animationView.setAnimation("animation.json")
animationView.visibility = View.VISIBLE
animationView.addAnimatorUpdateListener {
    if (it.animatedFraction == 1f) {
        animationView?.let {
            it.visibility = View.INVISIBLE
            it.clearAnimation()
        }
    }
}
animationView.playAnimation()

**Comment by gpeal** [comment]
Fixed by https://github.com/airbnb/lottie-android/commit/0ca8ad880ae565a4c67ea849b89f37b38de0cc21

Will be in 1.0.3

**Comment by martinbonnin** [comment]
Could we possibly have a `setSpeed()` method and pass `-1` to reverse the animation ?

**Comment by gpeal** [comment]
@martinbonnin you got it :)

**Comment by sijanr** [comment]
> Fixed by [0ca8ad8](https://github.com/airbnb/lottie-android/commit/0ca8ad880ae565a4c67ea849b89f37b38de0cc21)
> 
> Will be in 1.0.3

I tried using it in 3.5.0, but I couldn't find the method to reverse the view. It seems that the method might have been removed. Passing -1 to setSpeed(float) works fine, however.

**Comment by gpeal** [comment]
@sijanr That is the correct way to do this.

**Comment by sijanr** [comment]
@gpeal Great! I've just started using Lottie and totally love it so far.

**Comment by alizarei95** [comment]
@sijanr you saved my time, thanks
