### ISSUE TITLE
can lottie support for identifying text line breaks

### ISSUE THREAD

**Issue by panzhi1** [airbnb/lottie-android#927]
There are two lines of text in the ae text animation, but only one line is displayed on the lottie side, and the & character is not recognized.please tell me how to solve this problem?

**Comment by gpeal** [comment]
Lottie's text support is *very* limited. Could you attach a failing animation for testing if support is added?

**Comment by panzhi1** [comment]
[合成1.zip](https://github.com/airbnb/lottie-android/files/2355112/1.zip)
ok.

**Comment by martin-huang** [comment]
why lottie doesn't use staticLayout to draw  two lines or more lines text ? ?  could you support it? thank you  very much

**Comment by gpeal** [comment]
Duplicate of #401
