### ISSUE TITLE
LottieDrawable is package visible in v1.0.2

### ISSUE THREAD

**Issue by nickaein-a** [airbnb/lottie-android#93]
can't use LottieDrawable anymore.
whats the solution?
is there any alternative?
how can i set animation to ImageView

**Comment by gpeal** [comment]
Ah, that was an accident during a recent change. I'll push out 1.0.3 with it fixed.

**Comment by gpeal** [comment]
@felipecsl fyi

**Comment by nickaein-a** [comment]
@gpeal thank you

**Comment by gpeal** [comment]
The first tagged commit is not relevant, only the second.

**Comment by microstudent** [comment]
but LottieDrawable is still package visible in v1.0.3 ?

**Comment by gpeal** [comment]
@microstudent LottieDrawable is public in 1.0.3. You can see it in the commit that is linked above in this issue.

**Comment by microstudent** [comment]
@gpeal Haven't it sync to Maven or something?
 I can't see this change when I use compile 'com.airbnb.android:lottie:1.0.3'

**Comment by zeeeliza** [comment]
I've lost my reply to you, so here goes again, thank you for letting me know the deal.  You have been so kind. Just do something for me and text your friend daze and let her know he came on to you. She thinks im crazy!!! And he has everyone believing it. She don't believe I'm talking to you now. I don't blame you not one bit. He should have his old ass home. Thanks for that and deja say she is waiting!

**Comment by gpeal** [comment]
@microstudent Ah, you know, the constructor wasn't made public :(
You can use 1.0.1 or reflection for now. I'm going to push a significant update this week and will fix it properly.

**Comment by microstudent** [comment]
@gpeal all right, Thank you

**Comment by zeeeliza** [comment]
I'm just learning how to do this today! I'm not that good at it and still really don't know how to send it. If you do get  it's by luck cus I really don't know what the hell im doing lol
