### ISSUE TITLE
airbnb:lottie:2.6.0 doesn't work for android

### ISSUE THREAD

**Issue by nehagr** [airbnb/lottie-android#932]
The latest version of airbnb:lottie:2.6.0 doest work in Android, 

I have the images and json file in my assets 
My XML file includes 
```

    <com.airbnb.lottie.LottieAnimationView
        tools:ignore="MissingRegistered"
         android:id="@+id/animation_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
       android:layout_alignEnd="@+id/legalInfoTextView"
        android:layout_below="@+id/editText1"
         android:layout_gravity="center"
        app:lottie_autoPlay="true"
        app:lottie_imageAssetsFolder="images"
        app:lottie_fileName="data.json"
       app:lottie_loop="true" />
```
 

when I load the screen for very 1st time , the animations show up and when go to background and open the screen again , I cannot see any animations on the screen 
It is just blank . 
 I had to Ignore MissingRegistered because for some strange reason Lint is unable to
find the reference even though the view and animation load correctly. it shows up the warning

**Comment by gpeal** [comment]
@nehagr Did this happen with an older version of Lottie?

**Comment by gpeal** [comment]
This behavior works fine in the Lottie sample app for what it's worth.

**Comment by nehagr** [comment]
no , the version 2.5.5 works fine , and 2.6.0 doesn't work on android

**Comment by nehagr** [comment]
@gpeal

**Comment by gpeal** [comment]
I'm pretty sure this should be fixed by https://github.com/airbnb/lottie-android/commit/604299aa4f15a191cc7f8247dfd0724d8324aed0

Can you try 2.6.1?

**Comment by nehagr** [comment]
@gpeal 2.6.1 works 
Thank you

**Comment by zany1** [comment]
> @gpeal 2.6.1 works
> Thank you

How do you get 2.6.1 in nuget. All I see is 2.6 as the latest even checking the prerelease option doesn't show up.

**Comment by gpeal** [comment]
@zany1 use 2.7.0 (android.support) or 2.8.0 (androidx)
