### ISSUE TITLE
Aapt2Exception in android 3.2.0 with lottie:2.6.0

### ISSUE THREAD

**Issue by NithinJohn** [airbnb/lottie-android#936]
Implemented app bundle in the app, and com.airbnb.lottie.LottieAnimationView is using attr name="animationDirection" which is the same name used by android lib. Since its having the same name its throwing crash in 3.2.0. Below is the crash logs. 

For the fix, need to rename the attr name "animationDirection". 

=====================
Caused by: org.gradle.internal.UncheckedException: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
Output:  ***/merged.dir/values/values.xml:3275: error: duplicate value for resource 'attr/animationDirection' with config ''.
/merged.dir/values/values.xml:3275: error: resource previously defined here.
==========================
Command: aapt2-3.2.0-rc02-4818971-osx.jar/ba7a29d0c9250056c3db01a0ee8f19b0/aapt2-3.2.0-rc02-4818971-osx/aapt2 compile --legacy \
        -o \
        ***/build/intermediates/incremental/***/merged.dir/values/values.xml
Daemon:  AAPT2 aapt2-3.2.0-rc02-4818971-osx Daemon #0
Output:  ****/res/values/values.xml:64:5-67:36: AAPT: error: duplicate value for resource 'attr/animationDirection' with config ''.
    
***/.gradle/caches/transforms-1/files-1.1/nativesdk-2.4.35.aar/8f209ed649d9bf9c2cb3404dc23661fe/res/values/values.xml:64:5-67:36: AAPT: error: resource previously defined here.

**Comment by gpeal** [comment]
`animationDirection` isn't part of lottie.

**Comment by harshrajpurohit** [comment]
Sometimes cleaning the project might not work and so will reinstalling anything (be in Android Studio or any other component). In my case, Aapt2.exe was renamed from a virus. Deleting the folder of aapt2-3.2.0-(version) from the directory from where the gradle was building (from the cached state).Building the project after that solved the error.
