### ISSUE TITLE
Lottie and Android battery saver mode

### ISSUE THREAD

**Issue by Thisisgodzilla** [airbnb/lottie-android#941]
Would a phone in battery saver mode prevent lottie animations from playing in android apps?
If so, what is the prefered implementation method to circumvent this?
Fallback to .svg? ability to display static lottie?

**Comment by MONIKA-KUMAR-JETHANI** [comment]
@gpeal Can I work on this?

**Comment by gpeal** [comment]
@Thisisgodzilla Lottie works with battery saver mode because it has its own Choreographer based animation and handles timing itself rather than relying on the platform for animation.
