### ISSUE TITLE
Distortion only on Android

### ISSUE THREAD

**Issue by alloflow** [airbnb/lottie-android#944]
Hi there,

before anything, thanks for sharing this incredible library ! It's just awesome for a designer like me to be able to create animations like that without any line of code !

Here is my problem: I created a simple scene where i just use scale, translate, rotation and opacity. Everything works fine on AE and on web version. But when it comes on Android, i got a strange distortion. I assume this is because of the scale property. I tried to scale up my canvas because elements were too close of it, but it didn't change anything.
Could you help me ?

Here is the file: https://lottiefiles.com/share/3WyeA2

Thanks !

**Comment by MONIKA-KUMAR-JETHANI** [comment]
@gpeal Can I work on this?

**Comment by gpeal** [comment]
@alloflow Hah, sure looks funky. Can you attach the aep? Even better would be a minimal aep that reproduces just this.

@MONIKA-KUMAR-JETHANI Sure, if you would like.

**Comment by alloflow** [comment]
@gpeal @MONIKA-KUMAR-JETHANI Here is the .aep file (that's actually the same scene) : https://www.dropbox.com/s/ap5ut9oaxdesmsw/loader.aep?dl=0

Thanks for your feedback, i really appreciate it

**Comment by gpeal** [comment]
@alloflow this seems to be a bug with bodymovin/javascript. Your json has this:
```
                "y": [
                  -2277243.977,
                  0.944,
                  1
                ]
```

This likely works on lottie-web because of some javascript artifact of the way the exporter/web player work. 
Can you file a bug on lottie-web?

cc @bodymovin

**Comment by bodymovin** [comment]
@alloflow this is related to having two consecutive keyframes with the same value.
For example, if you change the value of the keyframe from 100 to 99.9 on the layer "body" on the 4th keyframe, it will export correctly.

**Comment by alloflow** [comment]
Thanks for your feedback gentlemen ! I'll try asap and open an issue on lottie-web
