### ISSUE TITLE
Updating Textview during animation?

### ISSUE THREAD

**Issue by JosueB** [airbnb/lottie-android#945]
Hello,

I was wondering if there's a way to update a textview during an animation.
My team and I are creating a tutorial guide where we would like to update the content
of a textview at a given time when the animation is played.

 Ei: at x seconds of the animation being played, change the text to "Well done!" etc

**Comment by MONIKA-KUMAR-JETHANI** [comment]
@gpeal  Can I work on this?

**Comment by alexhorsa** [comment]
Here is how you can listen to the animation progress
```
LottieAnimationView.addAnimatorUpdateListener(new ValueAnimator.AnimatorUpdateListener() {          
    @Override
    public void onAnimationUpdate(ValueAnimator animation) {
        animation.getCurrentPlayTime()
        --- update your TextView --- (maybe use a Handler to post to UI thread if needed)
    }
});
```

**Comment by alexhorsa** [comment]
@JosueB Yes, use these methods from **LottieAnimationView** or **LottieDrawable** to play a part of the animation

`setMinAndMaxFrame(int minFrame, int maxFrame);`

or specify a progress from 0.0 to 1.0

```
setMinAndMaxProgress(
    @FloatRange(from = 0f, to = 1f) float minProgress,
    @FloatRange(from = 0f, to = 1f) float maxProgress
);
```

**Comment by JosueB** [comment]
@alexhorsa Thansk for the help! Min and max have been working for me. I do have a JSON file that references images in the assets folder. Is there a way to programmatically choose the start progress based on the change of images from the json file?

**Comment by gpeal** [comment]
@JosueB It seems like you can use min/max setFrame/setProgress/listeners or any combination of these to achieve what you need. If not, you may reopen this.
