### ISSUE TITLE
Lottie animation still plays and wastes cpu when the view becomes invisible

### ISSUE THREAD

**Issue by zjupure** [airbnb/lottie-android#947]
Use LottieImageView to play lottie animation and set it invisible or gone, the animation will not auto stop according to the view state. I must call stop by myself everywhere it was used.

I think the `LottieAnimationView` should override the `onVisibilityChanged` to start or stop the animation automatically.

**Comment by gpeal** [comment]
This seems reasonable but I am hesitant to change the existing behavior because people use Lottie all sorts of ways and this could break their assumptions. It is easy enough to override this for your own project though.
