### ISSUE TITLE
"Could not get unknown property 'lottieVersion'"

### ISSUE THREAD

**Issue by pedroRelvas** [airbnb/lottie-android#950]
Hi!

When I try to implement the dependency the follow error occurs:
**"Could not get unknown property 'lottieVersion' for DefaultConfig_Decorated{name=main, dimension=null, minSdkVersion=DefaultApiVersion{mApiLevel=22, mCodename='null'}, targetSdkVersion=DefaultApiVersion{mApiLevel=28, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=null, versionName=null, applicationId=com.example.josep.testema, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.DefaultConfig."**

Can you help me? 

Thank you very much!

**Comment by gpeal** [comment]
This is an issue with your gradle project setup, not Lottie.

**Comment by Aluna145** [comment]
add this: final lottieVersion = '2.7.0' to the top of your build.gradle
