### ISSUE TITLE
Why is it that when i make the lottie animation larger performance suffers?

### ISSUE THREAD

**Issue by aaronbond** [airbnb/lottie-android#952]
I'm trying to figure out what i'm doing wrong here, I wanted to make the animation larger.
lottieview sites within a constraint layout and i set the height to match a constraint so that the animation will fill any available space between two views (and thus be larger)

but this one change causes a huge amount of extra resources to be used bringing the fps down and causing a lot of jank.

I would not have assumed scaling the lottieview up would have such a performance impact, am i missing something?

note: I am using hardware acceleration and i am using masks (i will hopefully be able to work on a solution that removes them)

![image](https://user-images.githubusercontent.com/6385840/45733907-c9305580-bc25-11e8-85b2-244dd0166d01.png)

![image](https://user-images.githubusercontent.com/6385840/45733725-2677d700-bc25-11e8-97a6-f8a95e808dc9.png)

**Comment by gpeal** [comment]
@aaronbond Masks have a very large performance overhead that is proportional to their size.  For starters, I would try and eliminate them if possible. If not, you can try to render the view small but use the Android scaleX and scaleY translations to do a post-render scale. It will be pixelated but the tradeoff against performance may be worth it and you can tweak how much to scale by.
