### ISSUE TITLE
why lottie textLayer do not use the spannable and Layout to draw Text?

### ISSUE THREAD

**Issue by martin-huang** [airbnb/lottie-android#953]
it could be support more effect by use the spannable and Layout 。

**Comment by gpeal** [comment]
@martin-huang Text rendering is very primitive right now. If somebody wants to take ownership of it, that would be great but it hasn't been at the top of our priority list.

When we do another text pass, we'll take some time to look into performance and supporting more features. You can take a look at other issues with the Text label here to see some of them.
