### ISSUE TITLE
Expression 'marquee' of type 'Int' cannot be invoked as a function. The function 'invoke()' is not found

### ISSUE THREAD

**Issue by kouhengsheng** [airbnb/lottie-android#955]
Expression 'marquee' of type 'Int' cannot be invoked as a function. The function 'invoke()' is not found

how can I solve this problem in kotlin file

**Comment by gpeal** [comment]
This seems like a Kotlin compilation issue in your project. If you attach a sample project that reproduces this, I can try and help.

**Comment by neuberfran** [comment]
https://github.com/neuberfran/firebase
