### ISSUE TITLE
Subtitle text in example GIF is wrong

### ISSUE THREAD

**Issue by hyperdo** [airbnb/lottie-android#96]
On the third GIF of [this example](https://github.com/airbnb/lottie-android/blob/master/gifs/Example3.gif), the "Great" text does not update depending on the amount of stars.

**Comment by chetanya-shrimali** [comment]
where do i find the relevant files.... Since i am new to lottie .

**Comment by gpeal** [comment]
@chetanya-shrimali Lottie is just the rendering library. You use it with your own animations.
@hyperdo was just referring to the example gif on the readme. We don't ship animations outside of the ones in the sample app.

**Comment by gpeal** [comment]
Fixed by https://github.com/airbnb/lottie-android/commit/44ff69a149b964ac1224e09d4d4d958903ba1c67
