### ISSUE TITLE
Animation is janky on first display in Android

### ISSUE THREAD

**Issue by shoeguy** [airbnb/lottie-android#963]
The first time an animation is shown on Android, it is slow and janky.  Can it be pre-cached?  Can the bitmaps be build in advance.

There was an issue on this which was closed, but it did not answer the question:  https://github.com/airbnb/lottie-android/issues/725

**Comment by shoeguy** [comment]
Just to clarify.  The link points to the "getting started" documentation but does not seem to specifically describe how to preload cache with bitmaps.  There is a section that related to caching but does not describe the specific technique: 

    http://airbnb.io/lottie/android/android.html#caching-animations

**Comment by gpeal** [comment]
@shoeguy Lottie doesn't do render caching and if everything else is equal, performance will be the same on every loop. The only reason it would be janky at first is if your device is doing other things that coincide with it or Android takes time to ramp up the CPU governor.

Doing render caching would take orders of magnitude more RAM so we don't do it.
