### ISSUE TITLE
2.8.0 POM file on Maven is wrong

### ISSUE THREAD

**Issue by perdubug** [airbnb/lottie-android#964]
The 2.8.0 Maven is at https://search.maven.org/artifact/com.airbnb.android/lottie/2.8.0/aar. As you can see that the version of appcompat dependency is wrong, which caused build error when import 2.8.0 in gradle project.

 _<dependencies>
    <dependency>
      <groupId>androidx.appcompat</groupId>
      <artifactId>appcompat</artifactId>
      <version>1.0.0</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>_

**Comment by slhddn** [comment]
@gpeal The error is:
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:29:5-133:19 to override.

**Comment by gpeal** [comment]
@slhddn Is your project on androidx?

**Comment by slhddn** [comment]
@gpeal not yet. All the libraries I use in my project is still on support. I can't migrate directly. Can't I use 2.8.0 without x?

**Comment by gpeal** [comment]
@slhddn Nope, androidx is not backwards compatible. 2.7.0 is the final appcompat release.

**Comment by JSpiner** [comment]
same here `2.8.0`
```
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
Suggestion: add 'tools:replace="android:appComponentFactory"' to element at AndroidManifest.xml:29:5-133:19 to override.
```

**Comment by gpeal** [comment]
@JSpiner 2.8.0 is not compatible with android.support.*. You must [migrate to androidx](https://developer.android.com/jetpack/androidx/migrate) to use 2.8.0 or above.

**Comment by JSpiner** [comment]
https://github.com/airbnb/lottie-android/commit/65c5ee8ccb6c7258e644a99df729552890706108 good 👍
