### ISSUE TITLE
use lottie in kotlin, i got a error : Failed to process resources,

### ISSUE THREAD

**Issue by dengzhao7053** [airbnb/lottie-android#965]
this is the detail:

AGPBI: {"kind":"error","text":"error: resource android:attr/dialogCornerRadius not found.","sources":[{"file":".gradle/caches/transforms-1/files-1.1/appcompat-1.0.0.aar/ddd7ec876db44ff77f6935a92aadfb11/res/values-v28/values-v28.xml","position":{"startLine":8,"startColumn":4,"startOffset":447,"endLine":11,"endColumn":12,"endOffset":684}}],"original":"","tool":"AAPT"}

i have tried many methods ,but still failed...

**Comment by richjhart** [comment]
Same issue using Java only. Between this and the other issue raised, it looks like 2.8.0 could be broken.

**Comment by dengzhao7053** [comment]
emmmm.......so how can i solve this problem ?

**Comment by gpeal** [comment]
@dengzhao7053 @richjhart @HelenaSewell Have you all migrated your projects to androidx?

**Comment by richjhart** [comment]
@gpeal No. Because migrating is far from a trivial process for some projects (a very big library I use does not yet work properly with AndroidX). I am looking into migrating, but IMHO libraries shouldn't be forcing the switch yet - the official release is still too recent

**Comment by richjhart** [comment]
@dengzhao7053 The best solution I have so far is this:

    // 2.8.0 requires androidx. Do not upgrade to it
    //noinspection GradleDependency
    implementation 'com.airbnb.android:lottie:2.7.0'

**Comment by gpeal** [comment]
@richjhart It's a chicken and egg problem. Libraries have to migrate to allow app developers to upgrade. 2.7.0 is the last appcompat release but you can stay on it for as long as you need to. When you are ready to upgrade, you can switch to 2.8.0+

**Comment by Ribesg** [comment]
> Libraries don't have to migrate to allow app developers to upgrade
That's wrong. I'm an app developer and I'm waiting for some libraries to update to AndroidX. I can't upgrade to AndroidX if a library doesn't support it. On the other hand, I can stay at older version of libraries who upgraded. The situation is the exact opposite of what you described: I need all libraries depending on Android Support to upgrade before I can.

**Comment by nhaarman** [comment]
You can just use the Jetifier tool, right?

**Comment by richjhart** [comment]
@Ribesg Do you have an example of a library that needs to be upgraded? I use quite a few libraries, and this is the only one that forced me to upgrade to androidx. I have now done it on this project, and there was a bit of pain because the migration tool missed a couple of things that needed to be corrected, but otherwise:

```
android.enableJetifier=true
android.useAndroidX=true
```

(in `gradle.properties`) worked fine for me

**Comment by gpeal** [comment]
@richjhart Butterknife did as well. It was intentional as a forcing function to help get the community to migrate.
https://github.com/JakeWharton/butterknife/blob/master/CHANGELOG.md

If you really don't want to upgrade, just stick with 2.7.0.

**Comment by nhaarman** [comment]
Except butterknife did a major version bump instead of a minor.

**Comment by gpeal** [comment]
@nhaarman That's fair. I went back and forth on whether to do a 3.0.0 release. I decided to keep it 2.x to stay in line with iOS though.

**Comment by gpeal** [comment]
@Ribesg You can use 2.7.0 until you are ready to upgrade.
