### ISSUE TITLE
Bug: can't use v2.8.0, while 2.7.0 builds just fine

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [airbnb/lottie-android#967]
Android Studio 3.3 Canary 12
Build #AI-182.4505.22.33.5026711, built on September 24, 2018
JRE: 1.8.0_152-release-1248-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Steps:
1. Create a new project.
2. Just add this:
    implementation 'com.airbnb.android:lottie:2.7.0'
3. Note that it builds and runs fine.
4. Update to 2.8.0 :
    implementation 'com.airbnb.android:lottie:2.8.0'
5. Try to build.

The bug:
You get this error:
```
* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
  	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
  	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:4:5-14:19 to override.
```

Attached video to show issue.
[2018-10-02_11-45-52.zip](https://github.com/airbnb/lottie-android/files/2437140/2018-10-02_11-45-52.zip)

**Comment by GuilhE** [comment]
I don't believe this is an error, I believe version 2.8.0 is probably using **[androidx](https://developer.android.com/jetpack/androidx/)** while your project isn't.

**Comment by AndroidDeveloperLB** [comment]
@GuilhE It doesn't let me build&run, while 2.7.0 did...
Does 2.8.0 require to use android-x ?

**Comment by GuilhE** [comment]
@AndroidDeveloperLB I believe it does.

**Comment by AndroidDeveloperLB** [comment]
@GuilhE I see. 
I think this one is also related, and easy to check:

https://issuetracker.google.com/issues/116542121

**Comment by koehleru** [comment]
@AndroidDeveloperLB 
2.8.0 is for androidX
if you want to use 2.8.0 you have to remove all dependencies to android support libs

**Comment by AndroidDeveloperLB** [comment]
@koehleru I see, but why didn't they write about this on the main page?
Anyway, I close this now.
