### ISSUE TITLE
Possible to animate single layers?

### ISSUE THREAD

**Issue by wypa** [airbnb/lottie-android#972]
Hi,

Our designer made some animations which have composition and layers. 
I'm struggling with animations which have layers. Is it possible to play a layer from the composition? The only i can set is min/max progress and min/max frame

**Comment by Gwy** [comment]
Is it possible to pause one layer and only play them upon a condition (for example button click)?

**Comment by gpeal** [comment]
Not 100% out of the box but as stated above, you could use dynamic properties with your own ticker/frame clock that returns an alternative time value for a specific layer per the code snippet above
https://github.com/airbnb/lottie-android/blob/8f8da11969ebc821824f3dd4d4044f6dbd8625c4/LottieSample/src/main/kotlin/com/airbnb/lottie/samples/DynamicActivity.kt#L61
