### ISSUE TITLE
"lottie resolve key path process" can't find matte layer

### ISSUE THREAD

**Issue by v-silin** [airbnb/lottie-android#974]
Hi, guys.

My issue is the following:

Animation has three layers:
layer_1
layer_2
layer_3

I am trying to set custom value callback, as I did in iOS Application, but can't because:

public class CompositionLayer line 50-69: layer_2.matteLayer = layer_1
especial lines 58-59
CompositionLayer doesn't add layer_1 to array of layers.

And when I am trying to use KeyPath("layer_1", "Group", "Transform", "Position") Lottie can't find "layer_1" because "lottie resolve key path process" ignores matteLayer.

**Comment by v-silin** [comment]
There is possible another issue with scaling:
class LottieCompositionParser line 91: width and height for bounds are multiplied by scale (not sure why. iOS doesn't multiply)
class LottieDrawable line 716: if I set AnimationView scale to screen density, then bounds multiplied again.

**Comment by gpeal** [comment]
@v-silin I would accept a PR for this. I wouldn't add the layer to the list of layers as that would cause all sorts of other issues. However, resolveKeyPath should check matte layers.
