### ISSUE TITLE
LottieCompositionFactory.fromUrl  has no  Memory cache of  composition 

### ISSUE THREAD

**Issue by yjiang2009** [airbnb/lottie-android#978]
can you give me some suggest?  i use lottieview.setAnimationFromUrl( ) to load animation from net(is zip,contains json and images)，i saw the source has use  disk cache 。but  i want first use  memory cache ,then use disk cache .last  from net .if
i just use setAnimationFromUrl  or  LottieCompositionFactory.fromUrl，it there have two same url  ,they have no memory cache ,they will load from net once ,then load from disk ,but i want load from memory the second time to keep lottiew  fast 。
if  i  use lottiecomposition disk cache  myself .i dont know the image folder default ,they are load direct from zip by  fromZipStreamSync.,  how can i solve this ? thank you .

**Comment by gpeal** [comment]
This is fixed as of that PR.
