### ISSUE TITLE
Add support for Polystars

### ISSUE THREAD

**Issue by MrGatsby2** [airbnb/lottie-android#98]
hi,man.
I got a problem,here is the html file 
[demo.txt](https://github.com/airbnb/lottie-android/files/770945/demo.txt)

 create by AE CC 2015,(plz change the  postfix to .html)as you could see the effect, there is a circle and a triangle. 
however,when I run the EXACTLY SAME json file (the json string you can find in the html file) I only got the cirle animation,there's no triangle. Is this a bug or I open it wrong? plz help.

**Comment by therealsalih** [comment]
Can you attach the AE file?

**Comment by gpeal** [comment]
@MrGatsby2 ^

**Comment by gpeal** [comment]
@MrGatsby2 I just took a look at your json. The second layer doesn't render because we don't currently support stars. Convert the layer into a shape and it should work.

**Comment by MrGatsby2** [comment]
okay,thanks, I'll try it. @gpeal

**Comment by MrGatsby2** [comment]
I'v succeed by convert the layer into a shape, hope you guys could support Polystars asap !

**Comment by gpeal** [comment]
@MrGatsby2 1.5.0 is now out!
