### ISSUE TITLE
Looping animations continue when LottieAnimationView is invisible

### ISSUE THREAD

**Issue by florianPOLARSTEPS** [airbnb/lottie-android#987]
I recently did some benchmarking on an app which uses lottie to do some animations (autoplay and looping). I noticed that there is quite some CPU usage when the app is in the background and tried to investigate.

It seems to me looping animations do not pause/stop when the containing `LottieAnimationView` is off screen, and/or the Activity is paused. 

I believe this is due to the cleanup code being only in `onDetachedFromWindow()` which is not necessarily being called once the Activity goes into a paused state and most definitely not, when the view is simply not visible (`GONE`, `INVISIBLE` ) anymore.

I have created a little test project illustrating the issue:
https://github.com/florianPOLARSTEPS/lottie_leak 

Starting it up you will see an empty screen, with an invisible (`GONE`) lottie view, that shows a toast each time the animation is repeated. If you put the app in the background, the toast will continue.

**Comment by florianPOLARSTEPS** [comment]
Overriding `LottieAnimationView` and doing the following solves the visibility issue for me and Lottie is paused when not visible.

```
    @Override
    protected void onVisibilityChanged(@NonNull View changedView, int visibility) {
        super.onVisibilityChanged(changedView, visibility);
        if (visibility == VISIBLE && wasAnimatingWhenVisibilityChanged) {
            resumeAnimation();
        } else {
            if (isAnimating()) {
                wasAnimatingWhenVisibilityChanged = true;
                pauseAnimation();
            } else {
                wasAnimatingWhenVisibilityChanged = false;
            }
        }
    }
```

**Comment by adityaarora1** [comment]
I am trying to add/remove lottieAnimationView in a frame layout. However, lottie restores to last set frame after a remove/add. I need to reinitialise lottie on adding back.

**Comment by gpeal** [comment]
@florianPOLARSTEPS Thank you very much!
