### ISSUE TITLE
Exporting red (#ff000) into xml file.

### ISSUE THREAD

**Issue by oneuglybastard** [airbnb/lottie-android#988]
Exporting a fairly simple animation and it's exporting red (#ff000) as a bg fill color for some reason. It looks fine in the browser demo but is rendering a red bg in production.

AE attached.
[AndroidExport.zip](https://github.com/airbnb/lottie-android/files/2536937/AndroidExport.zip)

**Comment by gpeal** [comment]
@oneuglybastard Can you attach a converted AEP? I have creative cloud and it won't open your project.
![image](https://user-images.githubusercontent.com/1307745/49093699-47af0200-f22a-11e8-982a-8a44cc59fbe5.png)

**Comment by gpeal** [comment]
@oneuglybastard bump

@bodymovin any reason why this would be happening?

**Comment by bodymovin** [comment]
hi, can you try using the latest version 5.4.2?
The previous version was exporting hidden fills and strokes that were picked up by the native players.
If using the latest exporter doesn't work you can try removing the stroke and fill properties that are disabled from the AE composition.

**Comment by gpeal** [comment]
I think this is some combination of an old version of after effects and hidden layers (which Lottie now supports).
