### ISSUE TITLE
I can't play Annimation from the sample app

### ISSUE THREAD

**Issue by JulienGenoud** [airbnb/lottie-android#99]
on Xiaomi Mi5 and honor 8,
the animation won't play.

i don't have more debug to provide.

? I/art: Late-enabling -Xcheck:jni
? D/TidaProvider: TidaProvider()
? V/BoostFramework: mAcquireFunc method = public int com.qualcomm.qti.Performance.perfLockAcquire(int,int[])
? V/BoostFramework: mReleaseFunc method = public int com.qualcomm.qti.Performance.perfLockRelease()
? V/BoostFramework: mAcquireTouchFunc method = public int com.qualcomm.qti.Performance.perfLockAcquireTouch(android.view.MotionEvent,android.util.DisplayMetrics,int,int[])
? V/BoostFramework: mIOPStart method = public int com.qualcomm.qti.Performance.perfIOPrefetchStart(int,java.lang.String)
? V/BoostFramework: mIOPStop method = public int com.qualcomm.qti.Performance.perfIOPrefetchStop()
? V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@e811de3
com.airbnb.lottie W/System: ClassLoader referenced unknown path: /data/app/com.airbnb.lottie-1/lib/arm64
com.airbnb.lottie W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
com.airbnb.lottie V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@ce545d3
com.airbnb.lottie V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@d173510
com.airbnb.lottie D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
com.airbnb.lottie D/ActivityThreadInjector: clearCachedDrawables.
com.airbnb.lottie I/Adreno: QUALCOMM build                   : 0a3bdfc, Ifb508eebcd
                            Build Date                       : 08/04/16
                            OpenGL ES Shader Compiler Version: XE031.09.00.03
                            Local Branch                     : 
                            Remote Branch                    : 
                            Remote Branch                    : 
                            Reconstruct Branch               : 
com.airbnb.lottie I/OpenGLRenderer: Initialized EGL, version 1.4
com.airbnb.lottie V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@39ebf1f
com.airbnb.lottie I/Timeline: Timeline: Activity_launch_request time:10240302
com.airbnb.lottie V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@e446b22
com.airbnb.lottie V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@df0aae8
com.airbnb.lottie D/ActivityThreadInjector: clearCachedDrawables.`

**Comment by gpeal** [comment]
@JulienGenoud Do you have animations disabled?

**Comment by JulienGenoud** [comment]
that the point thanks ! @gpeal
