### ISSUE TITLE
Lottie doesn't support layer effects

### ISSUE THREAD

**Issue by 11hhlin1** [airbnb/lottie-android#990]
Lottie doesn't support layer effects. If you are using them for " " fills, strokes, trim paths etc. then try adding them directly as contents " " in your shape

**Comment by gpeal** [comment]
This is correct. Lottie doesn't support layer effects.

**Comment by Evaldy3** [comment]
what's the solution i have the same issue

**Comment by ahsanz024** [comment]
@Evaldy3 Judging by the silence on this issue, i guess there's no Solution.
I have the same problem :/

**Comment by Jigar-zest** [comment]
Any update on this issue?

**Comment by rezyfr** [comment]
Any update on this issue?
The warning says nothing on the found layer effects
"...then try adding them directly as contents  in your shape. Found: []"
