### ISSUE TITLE
Animations on top of Camera - Very Laggy

### ISSUE THREAD

**Issue by MrLizer** [airbnb/lottie-android#991]
Adding animations over the top of a live camera view on Android devices dont seem to work. Seems like the CPU cannot handle adding any animation. Has anyone find a fix?

Thanks

Liam

**Comment by carkchard** [comment]
Just leaving a bit of extra information here. It looks like on devices with better hardware there doesn't seem to be an issue, but on a mid range phone the camera preview becomes very laggy.

Was testing on a Nexus 5X running Android 8.1.0

**Comment by gpeal** [comment]
@MrLizer Animations with mattes and masks incur a large performance overhead (although I may have a fix for that soon).
You can also enable hardware acceleration which should help. Unfortunately, this isn't really actionable on its own so I'm going to close it.

**Comment by MrLizer** [comment]
Thanks for response, how soon is soon?!?!

**Comment by gpeal** [comment]
@MrLizer Depends on how much time I can find but _hopefully_ in the next month assuming it all goes well.
