### ISSUE TITLE
Series of Issues with the version 2.8.0

### ISSUE THREAD

**Issue by Algit73** [airbnb/lottie-android#994]
Hi,

I'm just new to Lottie and it is going to exhaust me with no clear answer.

I'm using Android SDK version 28 with the minimum SDK version 23. First, I just add  `implementation 'com.airbnb.android:lottie:2.8.0'` simply in my gradle. Syncing it arises no error.  Then Android studio tells me this:

> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:6:5-21:19 to override.

Then I simply add two attributes: `tools:replace="android:appComponentFactory"` and `android:appComponentFactory="whateverString"` in my manifest application to solve it.

Now I will face a series of problems. First this message appears which tells me that "META-INF/androidx.legacy_legacy-support-core-utils.version" has already an installed version. Then I exclude it in my gradle: `packagingOptions
    {
        exclude 'META-INF/androidx.legacy_legacy-support-core-utils.version'
    }`.

Then this message appears:
> D:\...\Lottie_Tetst\app\build\intermediates\transforms\mergeJavaRes\debug\0.jar: The process cannot access the file because it is being used by another process.

I've migrated my code to androidx and the result was nothing. Also I've added `compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }`
Then the result was nothing. I'm totally sticked with loop of errors and I've no idea how to confront them.

Help me please!

Bests
Alireza Alikhani

**Comment by gpeal** [comment]
@Algit73 2.8.0 requires migrating to AndroidX. You must use 2.7.0 if you haven't upgraded.
[CHANGELOG](https://github.com/airbnb/lottie-android/blob/master/CHANGELOG.md)

**Comment by GorkemKarayel** [comment]
> @Algit73 2.8.0 requires migrating to AndroidX. You must use 2.7.0 if you haven't upgraded.
> [CHANGELOG](https://github.com/airbnb/lottie-android/blob/master/CHANGELOG.md)

I agree. I'm getting this error in version 2.8.0.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:

**Comment by e9ab98e991ab** [comment]
在Androidx 导入lottie时 构建出现一下错误
Cannot convert a null value to an object of type Dependency.
The following types/formats are supported:
  - Instances of Dependency.
  - String or CharSequence values, for example 'org.gradle:gradle-core:1.0'.
  - Maps, for example [group: 'org.gradle', name: 'gradle-core', version: '1.0'].
  - FileCollections, for example files('some.jar', 'someOther.jar').
  - Projects, for example project(':some:project:path').
  - ClassPathNotation, for example gradleApi().

Comprehensive documentation on dependency notations is available in DSL reference for DependencyHandler type.
