### ISSUE TITLE
The Image does not switch to the image of set language when OS language is changed

### ISSUE THREAD

**Issue by koutarou-akiyoshi** [airbnb/lottie-android#995]
- Before changing the language setting（The language of the text matches the language of the image）
<img src="https://user-images.githubusercontent.com/38872271/48383499-50cba980-e729-11e8-9a5a-0c5d3697ceac.png" width="300">

<br />

- After changing the language setting（Text language and image language are different）
<img src="https://user-images.githubusercontent.com/38872271/48383510-5cb76b80-e729-11e8-9ea3-0be0e95a4787.png" width="300">

<br />

- When you kill the process and start the application again, it switches to the image of the changed language.

<br />

- Folder containing image files
  - raw/lottie_animation.json
  - raw-en/lottie_animation.json

<br />

- Setting LottieAnimationView in layout-file

```
            <com.airbnb.lottie.LottieAnimationView
                android:id="@+id/animation_view"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:layout_marginBottom="@dimen/wearing_margin_image_top_bottom"
                android:layout_marginTop="@dimen/wearing_margin_image_top_bottom"
                android:contentDescription="@string/img_desc_tutorial_image"
                android:scaleType="fitCenter"
                app:layout_constraintDimensionRatio="h,1:1"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintLeft_toLeftOf="parent"
                app:layout_constraintRight_toRightOf="parent"
                app:layout_constraintTop_toBottomOf="@id/explanation_label"
                app:lottie_autoPlay="true"
                app:lottie_loop="true"/>
```

<br />

- The image file is dynamically set as follows

```
val resourceId = R.raw.lottie_animation
animationView.setAnimation(resourceId)
```
<br />

- Device
  - maker - SHARP
  - model - SH-M05
- OS
  - 8.0.0

<br />

How can I solve it?

**Comment by gpeal** [comment]
@koutarou-akiyoshi Are you using a TextDelegate that returns a resource string?

**Comment by koutarou-akiyoshi** [comment]
@gpeal

As pointed out,
I am using a TextDelegate in `MyFragmentPagerAdapter` class.

```
class MyActivity : DaggerAppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {

        binding.viewPager.adapter =
          MyFragmentPagerAdapter(supportFragmentManager)
         
    }
}

class MyFragmentPagerAdapter(fm: FragmentManager) : FragmentPagerAdapter(fm) {
    // Here, I set the resourceId of Lottie

    private val contents = arrayOf(
        Triple(R.string.title_1,
            R.raw.lottie_1),
        Triple(R.string.title_2,
            R.raw.lottie_2)
    )

    override fun getItem(position: Int): Fragment {
        return MyFragment.newInstance(
            contents[position].first,
            contents[position].second)
    }
}


class MyFragment : DaggerFragment() {
    private lateinit var binding: MyFragmentBinding

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        
        binding = DataBindingUtil.inflate(inflater, R.layout.my_fragment, container, false)
        binding.apply {
            arguments?.let {
                titleLabel.setText(it.getInt(ARG_TITLE))

                val resourceId = it.getInt(ARG_IMAGE)
                animationView.setAnimation(resourceId)
            }
        }
        return binding.root
    }

    companion object {
        private const val ARG_TITLE = "title"
        private const val ARG_IMAGE = "image"

        fun newInstance(@StringRes title: Int, @StringRes explanation: Int, @DrawableRes image: Int) = MyFragment().apply {
            arguments = Bundle().apply {
                putInt(ARG_TITLE, title)
                putInt(ARG_IMAGE, image)
            }
        }
    }
}

```

I think that the way to solve the problem I contacted will be the following, but how do you think?

1. `MyFragmentPagerAdapter#contens` Create a function to set a value for this variable

2. Make sure to call this function in the constructor of `MyFragmentPagerAdapter`

**Comment by koutarou-akiyoshi** [comment]
@gpeal 

I'm sorry.
I should have tried the solution described earlier and commented later.
As I mentioned earlier, I tried it, but it did not work.

```
class MyFragmentPagerAdapter(fm: FragmentManager) : FragmentPagerAdapter(fm) {

    private lateinit var contents : Array<Pair<Int, Int>>

    init {
        contents = setContents()
    }

    private fun setContents(): Array<Pair<Int, Int>> = arrayOf(
        Pair(R.string.title_1,
            R.drawable.lottie_1),
        Pair(R.string.title_2,
            R.drawable.lottie_2)
    )

    override fun getItem(position: Int): Fragment {
        return TutorialFragment.newInstance(
            contents[position].first,
            contents[position].second)
    }

    override fun getCount(): Int {
        return contents.count()
    }
}
```

Since I got a hint, I will try various things.
Thank you.

**Comment by gpeal** [comment]
You could register a broadcast receiver to know when the language changes.
https://stackoverflow.com/a/43584678/715633

I think this is out of scope for Lottie though.

**Comment by gpeal** [comment]
@'

**Comment by gpeal** [comment]
@koutarou-akiyoshi

**Comment by michealfriesen** [comment]
I am also encountering this issue, and I think it is due to the caching being done for raw resources. If there is a good way to clear this cache on lang change or if it can be done in a different way, please advise.

**Comment by ngthanhphuc** [comment]
@michealfriesen use `lottie_cacheComposition="false"` to clear this cache on lang change

**Comment by gpeal** [comment]
That could work or you could use LottieCompositionFactory.* functions with your own language-specific cache keys and set the composition directly.
