### ISSUE TITLE
Animation disappears  when app background and resume

### ISSUE THREAD

**Issue by Umar3x** [airbnb/lottie-android#996]
Hello,

REF : https://github.com/martijn00/LottieXamarin/issues/200

I'm posting here as I don't have any answer on the lottie xamarin repo.

I think here I can have some help. I'm referencing the issue, thus not to duplicate an entire post.

Thanks for your help.

**Comment by gpeal** [comment]
I think this might be a Xamarin issue since it occurs on both platforms. If you can reproduce it in an Android sample app, I can take a look.
