### ISSUE TITLE
Need Help when to call cancelAnimation() and recycleBitmaps() in RecyclerView

### ISSUE THREAD

**Issue by iamdangerous** [airbnb/lottie-android#998]
When should I **call** **LottieAnimationView.cancelAnimation()** and **LottieAnimationView.recycleBitmaps()**

Scenario
I have a Recyclerview and LottieAnimationView is present inside one of its ViewHolder, I have to call notifydatasetChanged() on recyclerview's adapter. So after this call LottieAnimationView.onDetachedFromWindow() is called and because of this the animation freezes - because it internally calls cancel animation. 

Original - 
```
  @Override protected void onDetachedFromWindow() {
    if (isAnimating()) {
      cancelAnimation();
      wasAnimatingWhenDetached = true;
    }
    recycleBitmaps();
    super.onDetachedFromWindow();
  }

```
Modified class - 
 ```
override fun onDetachedFromWindow() {
        //Do nothing
    }
```

So I have **extended** the LottieAnimationView  class **commented everything under onDetachedFromWindow()**, so now the animation does not freezes but I want to know how will it **impact the app** because cancelAnimation() and recycleBitmaps() are not getting called now **and** how can i resolve those issues. And is there alternate way to make sure the animation not stops when a  view holder is refreshed via adapter's notifyDatasetChanged()

**Comment by gpeal** [comment]
@iamdangerous recycleBitmaps will be removed from the next version of Lottie so you don't have to worry about it anymore.
